In [1]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [5]:
df = pd.read_csv('predict_site.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict_site'].to_list()
predicts = [i.split('|') for i in predicts]
atomidxs = []
for i in predicts:
    atomidxs_part = []
    for j in i:
        try:
            atomidx = get_reactive_atom_indices(j)
            atomidxs_part.append(atomidx)
        except:
            pass
    atomidxs.append(atomidxs_part)
df['atomidxs'] = atomidxs
df

,SMILES,metabolite,predict_site,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,CC(=O)O[C@@]1(C#C)CC[C@@H]2[C@]1(CC)CC[C@@H]1[...,"[[21], [19], [5], [19], [18], [19], [18], [25]..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC([CH3:1])(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O...,"[[2], [33, 34], [19], [14], [13], [40], [21], ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCC[CH2:...,"[[23], [5], [1], [23], [5], [0], [22], [3], [4..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1C2=CC=CC=C2[S:1]C2=CC=CC=C12)N(C)C|CC(CN...,"[[10], [10], [7], [10], [9], [14], [9, 10], [1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,"[[26], [6], [23], [2], [15], [7], [3], [60], [..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,C1=CC=C2C(=C1OC1C(O)C(O)C(O)C(CO)O1)C(=O)C1=C(...,"[[47], [48], [27], [24], [47], [4], [48], [7],..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1[CH2:1]N=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1|O...,"[[2], [15], [4], [8], [1], [1], [16], [18], [9..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1[OH:1]|C...,"[[19], [6], [19], [14], [19], [6], [10], [2], ..."
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1(NCCCl)OCCCN1[...,"[[9], [11], [9], [9], [10], [10], [7], [1], [8..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOC[CH2:1]N1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C...,"[[5], [10], [10], [1], [14], [6], [6], [10], [..."

In [6]:
df.to_pickle('ourmodel_results.pickle')

In [7]:
df = pd.read_pickle('ourmodel_results.pickle')
df

,SMILES,metabolite,predict_site,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,CC(=O)O[C@@]1(C#C)CC[C@@H]2[C@]1(CC)CC[C@@H]1[...,"[[21], [19], [5], [19], [18], [19], [18], [25]..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC([CH3:1])(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O...,"[[2], [33, 34], [19], [14], [13], [40], [21], ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCC[CH2:...,"[[23], [5], [1], [23], [5], [0], [22], [3], [4..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1C2=CC=CC=C2[S:1]C2=CC=CC=C12)N(C)C|CC(CN...,"[[10], [10], [7], [10], [9], [14], [9, 10], [1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,"[[26], [6], [23], [2], [15], [7], [3], [60], [..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,C1=CC=C2C(=C1OC1C(O)C(O)C(O)C(CO)O1)C(=O)C1=C(...,"[[47], [48], [27], [24], [47], [4], [48], [7],..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1[CH2:1]N=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1|O...,"[[2], [15], [4], [8], [1], [1], [16], [18], [9..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1[OH:1]|C...,"[[19], [6], [19], [14], [19], [6], [10], [2], ..."
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1(NCCCl)OCCCN1[...,"[[9], [11], [9], [9], [10], [10], [7], [1], [8..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOC[CH2:1]N1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C...,"[[5], [10], [10], [1], [14], [6], [6], [10], [..."

In [8]:
subs = df['SMILES'].to_list()
atomidxs = df['atomidxs'].to_list()
dict_sub2atomidxs = dict(zip(subs,atomidxs))
dict_sub2atomidxs

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [[21],
  [19],
  [5],
  [19],
  [18],
  [19],
  [18],
  [25],
  [2],
  [10],
  [10, 18],
  [19]],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [[2],
  [33, 34],
  [19],
  [14],
  [13],
  [40],
  [21],
  [19],
  [34],
  [23],
  [39, 40],
  [22],
  [12]],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [[23],
  [5],
  [1],
  [23],
  [5],
  [0],
  [22],
  [3],
  [4],
  [1],
  [4],
  [21],
  [18],
  [2],
  [2]],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [[10],
  [10],
  [7],
  [10],
  [9],
  [14],
  [9, 10],
  [17],
  [17],
  [2],
  [11],
  [18, 19],
  [0],
  [17]],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [[26],
  [6],
  [23],
  [2],
  [15],
  [7],
  [3],
  [60],
  [31],
  [32],
  [4],
  [26],
  [40],
  [34],
  [46],
  [51],
  [7],
  [7],
  [56, 57]],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [[8],
  [18],
  [15],
  [0],
  [20],
  [3],
  [20],
  [18, 20],
  [9],
  [16],
  [8],
  [18],
  [13],
  [18],
  [7],
  [18],
  [18],
  [13]],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [[6],
  [5, 6],
  [6],
  [6, 7],
  [5],
  [5],
  [5, 6],
  [0],
  [1],
  [15, 16],
  [14],
  [15],
  [5],
  [5, 6],
  [8],
  [11],
  [6],
  [6, 7],
  [5],
  [5, 6],
  [12],
  [15]],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [[6],
  [7],
  [19],
  [0],
  [2],
  [18],
  [18],
  [1],
  [5],
  [20, 21],
  [18, 19],
  [6],
  [19],
  [5]],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [[0],
  [1],
  [17],
  [7],
  [2],
  [19],
  [17],
  [3],
  [19],
  [4],
  [5],
  [6],
  [0],
  [2],
  [19],
  [3],
  [17],
  [11]],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [[12],
  [3],
  [13],
  [15],
  [6],
  [36],
  [12],
  [8],
  [18],
  [30],
  [15],
  [16],
  [2],
  [24],
  [21],
  [33],
  [27],
  [19]],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [[0],
  [29],
  [1],
  [16],
  [16],
  [27],
  [20],
  [26],
  [3],
  [13, 14],
  [2],
  [3],
  [19],
  [28],
  [15],
  [11, 12]],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [[1],
  [0],
  [27],
  [12],
  [3],
  [23],
  [8],
  [32],
  [2],
  [12],
  [32],
  [32],
  [27],
  [25],
  [33],
  [32],
  [27],
  [32]],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [[16],
  [16],
  [16],
  [24],
  [16],
  [16],
  [22],
  [26],
  [16],
  [16],
  [0],
  [24],
  [24],
  [16]],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [[2],
  [2],
  [13],
  [4],
  [16],
  [13],
  [15],
  [3],
  [11],
  [5],
  [5],
  [5],
  [19],
  [17]],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [[14],
  [14],
  [12],
  [2],
  [2],
  [1],
  [14],
  [14],
  [11],
  [5],
  [4],
  [9],
  [9],
  [9],
  [16],
  [5],
  [15],
  [16]],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [[24],
  [36],
  [15],
  [16],
  [16],
  [30],
  [41],
  [41],
  [40],
  [32],
  [41],
  [37],
  [37],
  [0],
  [0],
  [27],
  [28],
  [17],
  [17],
  [17]],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [[6],
  [0],
  [14],
  [1],
  [15],
  [11],
  [15],
  [3],
  [12, 13],
  [18],
  [16],
  [0],
  [1],
  [15],
  [3]],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [[27],
  [28],
  [13],
  [0],
  [24],
  [8],
  [20],
  [0],
  [0]],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [[22],
  [22],
  [8],
  [22],
  [24],
  [25],
  [25],
  [8],
  [8],
  [12],
  [3],
  [22],
  [0],
  [0],
  [1, 2]],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [[14],
  [3],
  [27],
  [3],
  [15],
  [26],
  [26],
  [15],
  [24]],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [[6, 7],
  [14],
  [18],
  [17],
  [4, 5],
  [20],
  [12],
  [1],
  [1],
  [16],
  [9],
  [6],
  [6],
  [6, 7],
  [14],
  [6],
  [6, 7]],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [[7],
  [5],
  [7],
  [26],
  [1]],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [[18],
  [16],
  [18],
  [16],
  [16],
  [18],
  [1],
  [1],
  [9],
  [3],
  [3],
  [16],
  [0],
  [7],
  [6],
  [14],
  [9],
  [3]],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [[18],
  [17],
  [5],
  [19],
  [3],
  [4],
  [0, 1],
  [10],
  [16, 17],
  [21],
  [20],
  [14, 15],
  [12],
  [4, 5]],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [[10],
  [10],
  [10],
  [21],
  [0],
  [2],
  [26],
  [23],
  [23],
  [4],
  [7],
  [22],
  [6],
  [1],
  [6],
  [21],
  [27]],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [[9],
  [12],
  [0],
  [16],
  [15],
  [1],
  [13],
  [8],
  [9],
  [17],
  [14],
  [13],
  [14],
  [9]],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [[2],
  [1],
  [2],
  [13],
  [13],
  [1],
  [0],
  [1],
  [19],
  [2],
  [1],
  [1],
  [18],
  [12],
  [10]],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [[5],
  [7],
  [7],
  [9],
  [9],
  [5],
  [7],
  [9],
  [7],
  [0],
  [9],
  [0]],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [[7],
  [5],
  [7],
  [9],
  [9],
  [7],
  [7],
  [9],
  [5],
  [9],
  [0],
  [5],
  [5],
  [9]],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [[34],
  [22, 23],
  [22],
  [32],
  [18],
  [13],
  [8, 9],
  [9],
  [22],
  [34],
  [23],
  [18]],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [[8],
  [8],
  [11],
  [11],
  [7],
  [7],
  [5],
  [7],
  [9],
  [14],
  [12],
  [3],
  [10],
  [8],
  [16],
  [17],
  [0],
  [12],
  [7],
  [7],
  [19],
  [19]],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [[15],
  [5],
  [5],
  [18],
  [18],
  [20],
  [8],
  [23],
  [15],
  [1],
  [24],
  [8],
  [7],
  [6],
  [3],
  [25],
  [25],
  [20]],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [[17],
  [10],
  [12],
  [24],
  [17],
  [17],
  [15],
  [20],
  [9],
  [7],
  [7],
  [23]],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [[15],
  [16],
  [26],
  [17],
  [22],
  [14],
  [26],
  [20],
  [25],
  [26],
  [18],
  [9, 10]],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [[17],
  [17],
  [6],
  [2, 3],
  [7],
  [8],
  [4],
  [5],
  [14],
  [13, 14],
  [17],
  [7],
  [1],
  [14]],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [[36],
  [26],
  [4],
  [13],
  [21],
  [21],
  [3],
  [5],
  [0],
  [0],
  [1, 4]],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [[26],
  [17],
  [7],
  [5],
  [38, 39],
  [5],
  [7],
  [16],
  [16],
  [5],
  [39],
  [30],
  [17],
  [3],
  [0],
  [35, 37],
  [29],
  [16]],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [[13],
  [12],
  [9],
  [27],
  [27],
  [8],
  [13],
  [12],
  [12],
  [14],
  [25],
  [25],
  [27],
  [16],
  [12, 13],
  [26],
  [20, 21],
  [14],
  [24]],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [[26],
  [0],
  [0],
  [24],
  [1, 26]],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [[6],
  [12],
  [11],
  [0],
  [10],
  [7],
  [6],
  [7],
  [7, 13],
  [8],
  [14, 15],
  [0],
  [7],
  [0]],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [[17],
  [17],
  [4],
  [16],
  [4],
  [2],
  [3],
  [6],
  [1],
  [20],
  [10],
  [2],
  [14],
  [1],
  [18],
  [6],
  [20],
  [14],
  [0]],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [[14],
  [14],
  [17],
  [16],
  [25],
  [23],
  [17],
  [17],
  [16],
  [18],
  [11],
  [24],
  [11],
  [17],
  [15],
  [11],
  [11],
  [14],
  [14]],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [[23],
  [29],
  [27],
  [23]],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [[11],
  [19],
  [21],
  [3],
  [3],
  [19],
  [9],
  [19],
  [5],
  [22],
  [9],
  [21],
  [6],
  [15]],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [[24],
  [0],
  [7],
  [17],
  [15],
  [25],
  [24],
  [24],
  [14],
  [17],
  [29],
  [19],
  [19],
  [14],
  [25],
  [28],
  [25],
  [17],
  [0],
  [24]],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [[19],
  [0],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [8],
  [11],
  [9],
  [18],
  [18],
  [10],
  [7],
  [10],
  [11],
  [10]],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [[23],
  [0],
  [1],
  [20],
  [27],
  [11],
  [24],
  [28],
  [30],
  [25],
  [29],
  [15],
  [29],
  [15],
  [27],
  [26],
  [30, 31],
  [0],
  [0],
  [11]],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [[21],
  [21],
  [0],
  [21],
  [22],
  [21],
  [21],
  [24],
  [27],
  [15],
  [21],
  [16],
  [8],
  [11],
  [21]],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [[42],
  [40],
  [40],
  [44],
  [6],
  [10],
  [38],
  [11],
  [3],
  [18],
  [15],
  [3],
  [4],
  [10],
  [42],
  [44],
  [20],
  [15]],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [[5],
  [12],
  [12],
  [17],
  [15],
  [11],
  [7],
  [16],
  [17],
  [6],
  [19],
  [11],
  [18],
  [9],
  [17],
  [8]],
 'Clc1ccccc1CN1CCc2sccc2C1': [[14],
  [13, 14],
  [8],
  [8],
  [13],
  [14],
  [15],
  [11, 12],
  [4],
  [4],
  [10],
  [8],
  [11],
  [14],
  [7],
  [5],
  [14],
  [15]],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [[7],
  [7],
  [7],
  [7],
  [7],
  [7],
  [0],
  [11],
  [3],
  [13],
  [13],
  [3],
  [12, 13]],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [[17],
  [16, 17],
  [14],
  [16],
  [21],
  [21],
  [14],
  [14],
  [24],
  [5],
  [16],
  [7],
  [26],
  [16],
  [16, 17]],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [[1],
  [6],
  [2],
  [16],
  [3, 4],
  [0],
  [0],
  [4],
  [13],
  [15],
  [0],
  [13],
  [13],
  [15, 16],
  [0],
  [0],
  [4],
  [5],
  [3]],
 'NC(=O)c1nc(F)cnc1O': [[1],
  [7],
  [10],
  [10],
  [1],
  [7],
  [4],
  [7],
  [7],
  [10],
  [0],
  [3],
  [7],
  [10],
  [5],
  [5],
  [9],
  [4],
  [0],
  [3],
  [8]],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [[8],
  [8],
  [8],
  [14],
  [7],
  [2],
  [9],
  [6],
  [8],
  [5],
  [10],
  [16],
  [9],
  [1],
  [4],
  [8],
  [8],
  [18]],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [[4],
  [0],
  [1],
  [14],
  [8],
  [0],
  [4],
  [11],
  [1]],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [[1],
  [22],
  [22],
  [24],
  [10],
  [19],
  [20],
  [4],
  [16],
  [13],
  [8],
  [22],
  [15],
  [22, 23],
  [22],
  [6]],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [[5],
  [15],
  [12],
  [5],
  [7],
  [19],
  [8],
  [1],
  [12],
  [14],
  [12],
  [19],
  [5],
  [17]],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [[26],
  [24],
  [23],
  [26],
  [26],
  [24],
  [6],
  [17],
  [23],
  [26],
  [24]],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [[47],
  [48],
  [27],
  [24],
  [47],
  [4],
  [48],
  [7],
  [24],
  [17],
  [7],
  [24],
  [17]],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [[2],
  [15],
  [4],
  [8],
  [1],
  [1],
  [16],
  [18],
  [9],
  [2],
  [10],
  [2],
  [5, 6],
  [8],
  [2],
  [8],
  [11],
  [7],
  [7, 16],
  [5]],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [[19],
  [6],
  [19],
  [14],
  [19],
  [6],
  [10],
  [2],
  [6],
  [13],
  [2],
  [17],
  [1],
  [6],
  [4],
  [19]],
 'O=P1(NCCCl)OCCCN1CCCl': [[9],
  [11],
  [9],
  [9],
  [10],
  [10],
  [7],
  [1],
  [8],
  [10],
  [10],
  [3],
  [1],
  [11]],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [[5],
  [10],
  [10],
  [1],
  [14],
  [6],
  [6],
  [10],
  [21],
  [23],
  [24],
  [4],
  [25],
  [9],
  [9],
  [25],
  [1]]}

In [9]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
ourmodel_results_old = [dict_sub2atomidxs[i] for i in substrates]
df_total['ourmodel_results_old'] = ourmodel_results_old
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,xenosite_results,somp_results,metapredictor_results_old,ourmodel_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","[[3], [17], [15, 17], [12], [15], [13, 14], [1...","[[21], [19], [5], [19], [18], [19], [18], [25]..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","[[6], [19], [40], [7], [1, 40], [40], [1], [40...","[[2], [33, 34], [19], [14], [13], [40], [21], ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","[[23], [22], [25], [4], [1], [3], [3, 25], [13...","[[23], [5], [1], [23], [5], [0], [22], [3], [4..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1...","[[10], [10], [7], [10], [9], [14], [9, 10], [1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","[[58], [2], [59], [45], [60], [25], [39], [34]...","[[26], [6], [23], [2], [15], [7], [3], [60], [..."
...,...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","[[30], [11], [10, 30], [30, 47], [11, 30], [47...","[[47], [48], [27], [24], [47], [4], [48], [7],..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","[[8], [16], [15], [18], [18], [9], [16, 17, 18...","[[2], [15], [4], [8], [1], [1], [16], [18], [9..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","[[19], [14], [18], [15], [19], [18, 19], [5]]","[[19], [6], [19], [14], [19], [6], [10], [2], ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","[[2], [10], [12], [9], [4], [12, 13], [5], [2,...","[[9], [11], [9], [9], [10], [10], [7], [1], [8..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","[[1], [6], [3], [20, 21], [21], [21], [22], [9...","[[5], [10], [10], [1], [14], [6], [6], [10], [..."

In [10]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')

In [14]:
gnn_results = df_total['gnn_results'].to_list()
smartcyp_results = df_total['smartcyp_results'].to_list()
xenosite_results = df_total['xenosite_results'].to_list()
somp_results = df_total['somp_results'].to_list()

gnn_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in gnn_results]
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in smartcyp_results]
xenosite_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in xenosite_results]
somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in somp_results]

df_total['gnn_results'] = gnn_sorted_atoms
df_total['smartcyp_results'] = smartcyp_sorted_atoms
df_total['xenosite_results'] = xenosite_sorted_atoms
df_total['somp_results'] = somp_sorted_atoms
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,xenosite_results,somp_results,metapredictor_results_old,ourmodel_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"[3, 2, 17, 4, 16, 1, 7, 15, 0, 18, 19, 14, 6, ...","[5, 12, 18, 20, 7, 25, 19, 8, 14, 11, 23, 22, ...","[16, 17, 19, 11, 8, 14, 0, 21, 18, 7, 5, 3, 12...","[14, 20, 10, 27, 7, 29, 12, 30, 23, 18, 25, 21...","[[3], [17], [15, 17], [12], [15], [13, 14], [1...","[[21], [19], [5], [19], [18], [19], [18], [25]..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","[40, 32, 10, 19]","[3, 1, 13, 19, 39, 2, 0, 31, 17, 33, 36, 30, 8...","[13, 34, 12, 33, 14, 28, 6, 37, 27, 10, 16, 0,...","[13, 3, 19, 0, 7, 33, 2, 27, 28, 25, 39, 6, 11...","[14, 6, 7, 25, 35, 10, 13, 24, 21, 34, 22, 29,...","[[6], [19], [40], [7], [1, 40], [40], [1], [40...","[[2], [33, 34], [19], [14], [13], [40], [21], ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","[1, 4, 5, 22, 23, 25]","[16, 4, 17, 18, 19, 5, 3, 23, 13, 14, 7, 15, 1...","[3, 21, 22, 5, 20, 23, 4, 13, 1, 12, 0, 2, 11,...","[4, 0, 19, 2, 1, 13, 12, 21, 7, 20, 22, 5, 3, ...","[20, 23, 1, 12, 13, 5, 16, 0, 2, 8, 7, 11, 24,...","[[23], [22], [25], [4], [1], [3], [3, 25], [13...","[[23], [5], [1], [23], [5], [0], [22], [3], [4..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","[10, 11, 12, 13, 14, 15, 16, 17]","[17, 19, 18, 2, 3, 1, 10, 14, 15, 9, 6, 0, 5, ...","[18, 19, 10, 1, 7, 13, 6, 14, 2, 8, 12, 5, 15,...","[17, 3, 10, 6, 7, 14, 13, 0, 1, 18, 2, 5, 8, 1...","[18, 19, 10, 7, 13, 6, 14, 5, 8, 1, 12, 15, 17...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1...","[[10], [10], [7], [10], [9], [14], [9, 10], [1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","[34, 18, 8, 35, 36, 54, 51, 59, 25, 39, 40, 9,...","[26, 12, 49, 29, 31, 45, 9, 25, 50, 6, 23, 7, ...","[25, 7, 10, 17, 44, 29, 30, 31, 34, 8, 0, 42, ...","[29, 31, 6, 3, 61, 45, 7, 26, 4, 28, 56, 32, 5...","[[58], [2], [59], [45], [60], [25], [39], [34]...","[[26], [6], [23], [2], [15], [7], [3], [60], [..."
...,...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","[30, 47]","[5, 6, 19, 20, 47, 52, 1, 15, 3, 31, 46, 18, 2...","[30, 51, 27, 32, 48, 53, 29, 34, 50, 55, 36, 5...","[31, 52, 33, 54, 35, 56, 37, 58, 6, 20, 32, 2,...","[39, 44, 30, 51, 38, 45, 40, 43, 34, 32, 55, 5...","[[30], [11], [10, 30], [30, 47], [11, 30], [47...","[[47], [48], [27], [24], [47], [4], [48], [7],..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","[16, 17, 18]","[1, 3, 0, 18, 2, 4, 15, 9, 6, 8, 12, 16, 11, 1...","[2, 3, 8, 15, 7, 9, 6, 10, 16, 12, 18, 0, 1, 1...","[18, 3, 8, 15, 7, 6, 9, 10, 0, 2, 12, 16, 4, 1...","[2, 7, 8, 9, 15, 6, 10, 0, 16, 3, 12, 5, 14, 1...","[[8], [16], [15], [18], [18], [9], [16, 17, 18...","[[2], [15], [4], [8], [1], [1], [16], [18], [9..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","[16, 17, 18, 19]","[19, 17, 18, 2, 1, 0, 10, 7, 6, 3, 14, 9, 5, 1...","[18, 14, 17, 5, 13, 15, 12, 16, 4, 8, 2, 0, 1,...","[2, 19, 14, 17, 5, 12, 13, 15, 16, 0, 4, 18, 8...","[18, 13, 14, 15, 5, 12, 16, 0, 4, 19, 8, 7, 17...","[[19], [14], [18], [15], [19], [18, 19], [5]]","[[19], [6], [19], [14], [19], [6], [10], [2], ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","[2, 4, 9, 10, 12, 13]","[2, 3, 10, 11, 9, 0, 12, 1, 13, 7, 4, 5, 6, 8]","[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]","[7, 2, 10, 1, 9, 4, 8, 3, 11, 6, 12, 0, 5, 13]","[9, 11, 3, 13, 5, 7, 8, 0, 2, 12, 10, 4, 6, 1]","[[2], [10], [12], [9], [4], [12, 13], [5], [2,...","[[9], [11], [9], [9], [10], [10], [7], [1], [8..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"[0, 1, 8, 10, 24, 4, 25, 9, 21, 6, 3, 23, 14, ...","[5, 10, 7, 25, 1, 2, 8, 24, 6, 14, 9, 19, 22, ...","[0, 6, 9, 14, 13, 2, 15, 1, 7, 19, 3, 4, 22, 8...","[2, 5, 1, 10, 4, 14, 6, 13, 15, 19, 22, 18, 12...","[[1], [6], [3], [20, 21], [21], [21], [22], [9...","[[5], [10], [10], [1], [14], [6], [6], [10], [..."

In [15]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withrank_noenzyme.pickle')

In [37]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

# 示例使用
nums = [1, 2, 2, 3, 4, 3, 5, 1, 6]
n = 4
result = get_unique_numbers(nums, n)
print(result)  # 输出: [1, 2, 3, 4]

[1, 2, 3, 4]

In [50]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withrank_noenzyme.pickle')

metapredictor_results_old = df_total['metapredictor_results_old'].to_list()
ourmodel_results_old = df_total['ourmodel_results_old'].to_list()
ourmodel_results_old_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_old_new.append(list_part)
metapredictor_results_new = []
for i in metapredictor_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    metapredictor_results_new.append(list_part)

In [52]:
true_sites_old = df_total['true_sites_old'].to_list()
true_sites = df_total['true_sites'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

gnn_top1_acc = acc_top_n(1,gnn_sorted_atoms,true_sites)
gnn_top3_acc = acc_top_n(3,gnn_sorted_atoms,true_sites)
gnn_top5_acc = acc_top_n(5,gnn_sorted_atoms,true_sites)

smartcyp_top1_acc = acc_top_n(1,smartcyp_sorted_atoms,true_sites)
smartcyp_top3_acc = acc_top_n(3,smartcyp_sorted_atoms,true_sites)
smartcyp_top5_acc = acc_top_n(5,smartcyp_sorted_atoms,true_sites)

xenosite_top1_acc = acc_top_n(1,xenosite_sorted_atoms,true_sites)
xenosite_top3_acc = acc_top_n(3,xenosite_sorted_atoms,true_sites)
xenosite_top5_acc = acc_top_n(5,xenosite_sorted_atoms,true_sites)

somp_top1_acc = acc_top_n(1,somp_sorted_atoms,true_sites)
somp_top3_acc = acc_top_n(3,somp_sorted_atoms,true_sites)
somp_top5_acc = acc_top_n(5,somp_sorted_atoms,true_sites)

metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_old,true_sites_old)
metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_old,true_sites_old)
metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_old,true_sites_old)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_old,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_old,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_old,true_sites_old)

top 1 accuracy = 0.36923076923076925
top 3 accuracy = 0.6461538461538462
top 5 accuracy = 0.7384615384615385
top 1 accuracy = 0.2153846153846154
top 3 accuracy = 0.49230769230769234
top 5 accuracy = 0.6307692307692307
top 1 accuracy = 0.4
top 3 accuracy = 0.6153846153846154
top 5 accuracy = 0.7384615384615385
top 1 accuracy = 0.12307692307692308
top 3 accuracy = 0.2923076923076923
top 5 accuracy = 0.4307692307692308

UnboundLocalError: local variable 'idx' referenced before assignment