In [1]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [2]:
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

In [3]:
df = pd.read_csv('predict_site.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict_site'].to_list()
predicts = [i.split('|') for i in predicts]
atomidxs = []
for i in predicts:
    atomidxs_part = []
    for j in i:
        try:
            j = standardize_smiles_with_atom_map(j)
            atomidx = get_reactive_atom_indices(j)
            atomidxs_part.append(atomidx)
        except:
            pass
    atomidxs.append(atomidxs_part)
df['atomidxs'] = atomidxs
df

[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:19] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger
[07:24:20] Running Uncharger

,SMILES,metabolite,predict_site,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,CC(=O)O[C@@]1(C#C)CC[C@@H]2[C@]1(CC)CC[C@@H]1[...,"[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC([CH3:1])(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O...,"[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCC[CH2:...,"[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1C2=CC=CC=C2[S:1]C2=CC=CC=C12)N(C)C|CC(CN...,"[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,"[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,C1=CC=C2C(=C1OC1C(O)C(O)C(O)C(CO)O1)C(=O)C1=C(...,"[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1[CH2:1]N=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1|O...,"[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1[OH:1]|C...,"[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1(NCCCl)OCCCN1[...,"[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOC[CH2:1]N1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C...,"[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [4]:
df.to_pickle('ourmodel_results.pickle')

In [5]:
df = pd.read_pickle('ourmodel_results.pickle')
df

,SMILES,metabolite,predict_site,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,CC(=O)O[C@@]1(C#C)CC[C@@H]2[C@]1(CC)CC[C@@H]1[...,"[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC([CH3:1])(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O...,"[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCC[CH2:...,"[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1C2=CC=CC=C2[S:1]C2=CC=CC=C12)N(C)C|CC(CN...,"[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,"[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,C1=CC=C2C(=C1OC1C(O)C(O)C(O)C(CO)O1)C(=O)C1=C(...,"[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1[CH2:1]N=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1|O...,"[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1[OH:1]|C...,"[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1(NCCCl)OCCCN1[...,"[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOC[CH2:1]N1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C...,"[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [6]:
subs = df['SMILES'].to_list()
atomidxs = df['atomidxs'].to_list()
dict_sub2atomidxs = dict(zip(subs,atomidxs))
dict_sub2atomidxs

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [[17],
  [15],
  [6],
  [12],
  [4],
  [12],
  [4],
  [25],
  [26],
  [21],
  [4, 21],
  [12]],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [[40],
  [37, 38],
  [19],
  [14],
  [32],
  [40],
  [21],
  [12],
  [8],
  [40],
  [38, 39],
  [21],
  [7]],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [[23],
  [5],
  [1],
  [23],
  [5],
  [25],
  [22],
  [3],
  [4],
  [16],
  [4],
  [4],
  [4],
  [25],
  [25]],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [[10],
  [10],
  [13],
  [10],
  [15],
  [14],
  [14, 15],
  [17],
  [17],
  [5],
  [13],
  [15, 16],
  [16],
  [13]],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [[26],
  [6],
  [34],
  [2],
  [15],
  [40],
  [60],
  [60],
  [31],
  [32],
  [59],
  [60],
  [18],
  [34],
  [50],
  [51],
  [7],
  [7],
  [45, 46]],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [[15],
  [18],
  [15],
  [2],
  [24],
  [9],
  [24],
  [22, 24],
  [9],
  [16],
  [15],
  [18],
  [9],
  [18],
  [7],
  [18],
  [18],
  [4]],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [[6],
  [6, 7],
  [6],
  [6, 7],
  [7],
  [7],
  [6, 7],
  [7],
  [1],
  [7, 8],
  [15],
  [12],
  [7],
  [6, 7],
  [8],
  [14],
  [6],
  [6, 7],
  [7],
  [6, 7],
  [14],
  [15]],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [[6],
  [7],
  [19],
  [21],
  [2],
  [18],
  [18],
  [1],
  [9],
  [7, 8],
  [8, 9],
  [10],
  [1],
  [8]],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [[19],
  [1],
  [19],
  [7],
  [2],
  [19],
  [19],
  [3],
  [19],
  [4],
  [5],
  [6],
  [13],
  [14],
  [19],
  [3],
  [19],
  [2]],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [[12],
  [3],
  [13],
  [15],
  [39],
  [36],
  [12],
  [40],
  [18],
  [30],
  [41],
  [16],
  [25],
  [24],
  [21],
  [33],
  [27],
  [19]],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [[20],
  [10],
  [19],
  [23],
  [23],
  [8],
  [27],
  [9],
  [3],
  [10, 11],
  [18],
  [4],
  [26],
  [11],
  [22],
  [9, 10]],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [[1],
  [29],
  [27],
  [27],
  [3],
  [23],
  [8],
  [33],
  [2],
  [27],
  [1],
  [33],
  [18],
  [29],
  [29],
  [1],
  [27],
  [33]],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [[16],
  [16],
  [16],
  [21],
  [16],
  [16],
  [2],
  [12],
  [16],
  [16],
  [15],
  [21],
  [13],
  [16]],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [[2],
  [2],
  [15],
  [19],
  [16],
  [15],
  [15],
  [18],
  [19],
  [5],
  [8],
  [5],
  [15],
  [12]],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [[14],
  [14],
  [15],
  [2],
  [2],
  [14],
  [14],
  [14],
  [14],
  [5],
  [6],
  [14],
  [14],
  [14],
  [14],
  [5],
  [16],
  [16]],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [[24],
  [36],
  [15],
  [16],
  [16],
  [30],
  [41],
  [15],
  [40],
  [10],
  [41],
  [15],
  [15],
  [11],
  [11],
  [27],
  [28],
  [40],
  [40],
  [40]],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [[6],
  [6],
  [13],
  [5],
  [16],
  [5],
  [16],
  [3],
  [12, 17],
  [18],
  [5],
  [2],
  [2],
  [16],
  [3]],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [[27],
  [28],
  [13],
  [26],
  [24],
  [11],
  [20],
  [28],
  [11]],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [[22],
  [22],
  [8],
  [22],
  [24],
  [25],
  [25],
  [8],
  [8],
  [12],
  [7],
  [22],
  [17],
  [7],
  [5, 20]],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [[15],
  [3],
  [28],
  [3],
  [15],
  [27],
  [24],
  [28],
  [22]],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [[18, 19],
  [14],
  [18],
  [17],
  [19, 20],
  [14],
  [19],
  [1],
  [1],
  [20],
  [14],
  [18],
  [18],
  [18, 19],
  [14],
  [18],
  [18, 19]],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [[7],
  [5],
  [7],
  [9],
  [21]],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [[18],
  [16],
  [18],
  [16],
  [16],
  [18],
  [1],
  [1],
  [18],
  [18],
  [3],
  [16],
  [16],
  [7],
  [6],
  [14],
  [18],
  [17]],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [[18],
  [21],
  [5],
  [19],
  [7],
  [4],
  [6, 7],
  [22],
  [19, 20],
  [8],
  [20],
  [20, 21],
  [12],
  [5, 6]],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [[10],
  [10],
  [10],
  [21],
  [3],
  [2],
  [8],
  [23],
  [23],
  [9],
  [7],
  [23],
  [6],
  [1],
  [11],
  [21],
  [27]],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [[9],
  [12],
  [12],
  [16],
  [10],
  [11],
  [11],
  [8],
  [9],
  [11],
  [12],
  [11],
  [12],
  [9]],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [[2],
  [1],
  [2],
  [21],
  [21],
  [1],
  [14],
  [1],
  [9],
  [2],
  [1],
  [1],
  [8],
  [20],
  [20]],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [[11],
  [11],
  [11],
  [9],
  [9],
  [11],
  [11],
  [10],
  [11],
  [11],
  [10],
  [9]],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [[11],
  [11],
  [11],
  [9],
  [9],
  [11],
  [11],
  [10],
  [11],
  [10],
  [11],
  [11],
  [11],
  [9]],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [[34],
  [27, 28],
  [28],
  [16],
  [23],
  [28],
  [11, 17],
  [9],
  [28],
  [29],
  [23],
  [18]],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [[8],
  [8],
  [11],
  [11],
  [13],
  [13],
  [5],
  [13],
  [9],
  [14],
  [12],
  [13],
  [10],
  [13],
  [13],
  [10],
  [12],
  [12],
  [8],
  [8],
  [8],
  [8]],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [[15],
  [29],
  [29],
  [18],
  [18],
  [20],
  [6],
  [23],
  [15],
  [27],
  [22],
  [8],
  [7],
  [6],
  [29],
  [25],
  [23],
  [17]],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [[17],
  [10],
  [22],
  [24],
  [17],
  [17],
  [21],
  [22],
  [18],
  [7],
  [22],
  [22]],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [[16],
  [15],
  [26],
  [18],
  [22],
  [17],
  [24],
  [20],
  [25],
  [20],
  [24],
  [11, 19]],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [[17],
  [17],
  [11],
  [14, 15],
  [7],
  [8],
  [4],
  [17],
  [14],
  [10, 11],
  [17],
  [7],
  [13],
  [14]],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [[22],
  [12],
  [4],
  [37],
  [31],
  [24],
  [38],
  [5],
  [32],
  [32],
  [19, 22]],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [[26],
  [17],
  [7],
  [5],
  [32, 33],
  [5],
  [7],
  [38],
  [38],
  [31],
  [33],
  [30],
  [17],
  [26],
  [35],
  [30, 31],
  [6],
  [6]],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [[14],
  [13],
  [10],
  [18],
  [18],
  [29],
  [14],
  [13],
  [13],
  [15],
  [25],
  [13],
  [20],
  [16],
  [26, 27],
  [17],
  [27, 28],
  [15],
  [27]],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [[10],
  [12],
  [12],
  [21],
  [8, 10]],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [[6],
  [12],
  [14],
  [15],
  [15],
  [5],
  [6],
  [5],
  [4, 15],
  [5],
  [14, 15],
  [12],
  [5],
  [11]],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [[17],
  [17],
  [4],
  [21],
  [4],
  [21],
  [3],
  [6],
  [1],
  [21],
  [18],
  [21],
  [14],
  [8],
  [3],
  [6],
  [5],
  [21],
  [21]],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [[9],
  [9],
  [22],
  [11],
  [23],
  [22],
  [12],
  [12],
  [11],
  [23],
  [22],
  [25],
  [22],
  [22],
  [10],
  [6],
  [6],
  [9],
  [9]],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [[6],
  [31],
  [18],
  [6]],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [[22],
  [19],
  [22],
  [3],
  [9],
  [19],
  [9],
  [19],
  [21],
  [22],
  [9],
  [18],
  [14],
  [18]],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [[17],
  [12],
  [26],
  [18],
  [8],
  [18],
  [17],
  [17],
  [18],
  [18],
  [27],
  [17],
  [12],
  [18],
  [18],
  [28],
  [17],
  [18],
  [12],
  [17]],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [[17],
  [17],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [9],
  [9],
  [9],
  [18],
  [18],
  [10],
  [12],
  [10],
  [9],
  [10]],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [[23],
  [23],
  [21],
  [25],
  [27],
  [11],
  [24],
  [28],
  [30],
  [15],
  [29],
  [17],
  [29],
  [17],
  [27],
  [8],
  [23, 24],
  [16],
  [16],
  [15]],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [[21],
  [21],
  [23],
  [21],
  [22],
  [21],
  [21],
  [23],
  [25],
  [5],
  [21],
  [16],
  [27],
  [21],
  [21]],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [[42],
  [45],
  [45],
  [45],
  [6],
  [10],
  [38],
  [41],
  [33],
  [18],
  [44],
  [3],
  [4],
  [42],
  [42],
  [45],
  [29],
  [44]],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [[5],
  [12],
  [12],
  [17],
  [15],
  [11],
  [7],
  [16],
  [17],
  [6],
  [19],
  [11],
  [18],
  [9],
  [17],
  [9]],
 'Clc1ccccc1CN1CCc2sccc2C1': [[13],
  [13, 14],
  [8],
  [8],
  [14],
  [13],
  [15],
  [11, 15],
  [15],
  [15],
  [15],
  [7],
  [3],
  [13],
  [16],
  [16],
  [13],
  [16]],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [[7],
  [7],
  [7],
  [7],
  [7],
  [7],
  [9],
  [9],
  [7],
  [10],
  [10],
  [11],
  [10, 11]],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [[17],
  [16, 17],
  [20],
  [20],
  [19],
  [19],
  [20],
  [20],
  [23],
  [22],
  [16],
  [16],
  [25],
  [16],
  [16, 17]],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [[1],
  [6],
  [13],
  [12],
  [3, 16],
  [11],
  [16],
  [16],
  [15],
  [16],
  [16],
  [15],
  [15],
  [11, 12],
  [6],
  [16],
  [16],
  [5],
  [16]],
 'NC(=O)c1nc(F)cnc1O': [[1],
  [7],
  [10],
  [10],
  [5],
  [7],
  [1],
  [7],
  [1],
  [10],
  [5],
  [9],
  [7],
  [7],
  [8],
  [8],
  [8],
  [9],
  [10],
  [8],
  [8]],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [[8],
  [8],
  [8],
  [14],
  [7],
  [8],
  [9],
  [17],
  [8],
  [11],
  [10],
  [17],
  [8],
  [11],
  [4],
  [8],
  [8],
  [13]],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [[6],
  [14],
  [6],
  [8],
  [8],
  [14],
  [6],
  [8],
  [6]],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [[1],
  [13],
  [9],
  [24],
  [23],
  [14],
  [14],
  [4],
  [24],
  [20],
  [15],
  [13],
  [19],
  [23, 24],
  [13],
  [6]],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [[5],
  [5],
  [5],
  [5],
  [16],
  [5],
  [5],
  [13],
  [5],
  [15],
  [12],
  [5],
  [5],
  [17]],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [[6],
  [6],
  [26],
  [26],
  [6],
  [6],
  [22],
  [26],
  [26],
  [6],
  [6]],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [[27],
  [27],
  [27],
  [27],
  [27],
  [29],
  [27],
  [27],
  [27],
  [30],
  [27],
  [27],
  [30]],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [[18],
  [15],
  [4],
  [8],
  [1],
  [13],
  [16],
  [18],
  [9],
  [18],
  [18],
  [17],
  [15, 16],
  [1],
  [18],
  [1],
  [15],
  [4],
  [1, 4],
  [17]],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [[19],
  [10],
  [19],
  [14],
  [19],
  [10],
  [1],
  [19],
  [10],
  [15],
  [19],
  [17],
  [1],
  [6],
  [9],
  [19]],
 'O=P1(NCCCl)OCCCN1CCCl': [[9],
  [11],
  [9],
  [9],
  [9],
  [9],
  [7],
  [4],
  [8],
  [10],
  [10],
  [1],
  [1],
  [7]],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [[5],
  [10],
  [5],
  [1],
  [21],
  [6],
  [6],
  [22],
  [4],
  [23],
  [24],
  [4],
  [25],
  [9],
  [9],
  [25],
  [22]]}

In [7]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
ourmodel_results_old = [dict_sub2atomidxs[i] for i in substrates]
df_total['ourmodel_results_old'] = ourmodel_results_old
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,xenosite_results,somp_results,metapredictor_results_old,ourmodel_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","[[3], [17], [15, 17], [12], [15], [13, 14], [1...","[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","[[6], [19], [40], [7], [1, 40], [40], [1], [40...","[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","[[23], [22], [25], [4], [1], [3], [3, 25], [13...","[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1...","[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","[[58], [2], [59], [45], [60], [25], [39], [34]...","[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","[[30], [11], [10, 30], [30, 47], [11, 30], [47...","[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","[[8], [16], [15], [18], [18], [9], [16, 17, 18...","[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","[[19], [14], [18], [15], [19], [18, 19], [5]]","[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","[[2], [10], [12], [9], [4], [12, 13], [5], [2,...","[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","[[1], [6], [3], [20, 21], [21], [21], [22], [9...","[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [8]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')

In [3]:
import pandas as pd
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')

In [4]:
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,xenosite_results,somp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ...","{0: 13, 1: 36, 2: 14, 3: 15, 4: 29, 5: 3, 6: 3...","{0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120,..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ...","{0: 50, 1: 54, 2: 76, 3: 123, 4: 94, 5: 22, 6:...","{0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3...","{0: 31, 1: 34, 2: 47, 3: 49, 4: 60, 5: 109, 6:...","{0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6:..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3...","{0: 59, 1: 103, 2: 71, 3: 23, 4: 138, 5: 61, 6...","{0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11...","{0: 55, 1: 104, 2: 63, 3: 30, 4: 116, 5: 12, 6...","{0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3...","{0: 62, 1: 46, 2: 72, 3: 128, 4: 29, 5: 133, 6...","{0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177,..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ...","{0: 52, 1: 73, 2: 167, 3: 118, 4: 37, 5: 198, ...","{0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ...","{0: 82, 1: 143, 2: 83, 3: 103, 4: 156, 5: 84, ...","{0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ...","{0: 80, 1: 102, 2: 27, 3: 140, 4: 77, 5: 51, 6...","{0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ...","{0: 44, 1: 148, 2: 119, 3: 87, 4: 45, 5: 94, 6...","{0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ...","{0: 17, 1: 8, 2: 7, 3: 23, 4: 14, 5: 19, 6: 28...","{0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6:..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6...","{0: 52, 1: 65, 2: 136, 3: 71, 4: 68, 5: 144, 6...","{0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, ..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ...","{0: 112, 1: 94, 2: 98, 3: 186, 4: 189, 5: 205,...","{0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4...","{0: 33, 1: 84, 2: 52, 3: 63, 4: 63, 5: 37, 6: ...","{0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6:..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2...","{0: 90, 1: 61, 2: 132, 3: 71, 4: 90, 5: 131, 6...","{0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136,..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73...","{0: 9, 1: 15, 2: 3, 3: 30, 4: 14, 5: 31, 6: 11...","{0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6...","{0: 17, 1: 9, 2: 13, 3: 11, 4: 24, 5: 27, 6: 2...","{0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39,..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33...","{0: 57, 1: 58, 2: 64, 3: 56, 4: 100, 5: 74, 6:...","{0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: ..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:...","{0: 33, 1: 36, 2: 53, 3: 14, 4: 43, 5: 63, 6: ...","{0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4...","{0: 48, 1: 66, 2: 36, 3: 72, 4: 56, 5: 125, 6:...","{0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6:..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7...","{0: 7, 1: 9, 2: 30, 3: 32, 4: 13, 5: 14, 6: 24...","{0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, ..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1...","{0: 38, 1: 42, 2: 17, 3: 48, 4: 46, 5: 57, 6: ...","{0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: ..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4...","{0: 60, 1: 128, 2: 96, 3: 85, 4: 51, 5: 80, 6:...","{0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61,..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:...","{0: 66, 1: 78, 2: 97, 3: 85, 4: 75, 5: 113, 6:...","{0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129,..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ...","{0: 91, 1: 137, 2: 79, 3: 59, 4: 110, 5: 43, 6...","{0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161,..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18...","{0: 6, 1: 1, 2: 9, 3: 7, 4: 5, 5: 12, 6: 10, 7...","{0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: ..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6...","{0: 13, 1: 6, 2: 20, 3: 2, 4: 24, 5: 1, 6: 22,...","{0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, ..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,...",None,"{0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 41..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ...","{0: 7, 1: 24, 2: 28, 3: 22, 4: 21, 5: 17, 6: 3...","{0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, ..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ...","{0: 44, 1: 65, 2: 46, 3: 40, 4: 85, 5: 77, 6: ...","{0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: ..."

In [6]:
gnn_results = df_total['gnn_results'].to_list()
smartcyp_results = df_total['smartcyp_results'].to_list()
xenosite_results = df_total['xenosite_results'].to_list()
somp_results = df_total['somp_results'].to_list()

gnn_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in gnn_results]
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in smartcyp_results]
# xenosite_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in xenosite_results]
xenosite_sorted_atoms = []
for i in xenosite_results:
    try:
        sub_result = [k for k, v in sorted(i.items(), key=lambda item: item[1])]
    except:
        sub_result = ['None']
    xenosite_sorted_atoms.append(sub_result)
somp_sorted_atoms = []
for i in somp_results:
    try:
        sub_result = [k for k, v in sorted(i.items(), key=lambda item: item[1])]
    except:
        sub_result = ['None']
    somp_sorted_atoms.append(sub_result)
# somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in somp_results]

df_total['gnn_results'] = gnn_sorted_atoms
df_total['smartcyp_results'] = smartcyp_sorted_atoms
df_total['xenosite_results'] = xenosite_sorted_atoms
df_total['somp_results'] = somp_sorted_atoms
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,xenosite_results,somp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"[6, 23, 1, 32, 35, 34, 2, 5, 24, 33, 3, 13, 27...","[17, 12, 15, 24, 13, 14, 20, 23, 3, 22, 25, 21...","[29, 7, 5, 31, 21, 20, 17, 32, 35, 13, 14, 15,...","[13, 16, 6, 4, 11, 7, 19, 8, 23, 26, 28, 3, 12..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","[3, 29, 5, 10, 40, 7, 37, 39, 32, 34, 24, 2, 1...","[11, 35, 26, 29, 23, 17, 12, 8, 2, 16, 21, 34,...","[5, 11, 0, 16, 1, 8, 19, 7, 2, 20, 26, 12, 40,...","[11, 13, 28, 27, 5, 12, 15, 17, 30, 31, 36, 35..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"[7, 8, 6, 1, 0, 14, 13, 15, 2, 11, 3, 19, 21, ...","[18, 1, 17, 22, 19, 2, 4, 21, 0, 16, 20, 3, 6,...","[0, 1, 8, 2, 3, 19, 12, 20, 18, 4, 14, 6, 16, ...","[1, 0, 4, 3, 2, 20, 18, 17, 19, 14, 15, 6, 21,..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"[10, 12, 3, 1, 13, 16, 22, 11, 14, 23, 20, 17,...","[0, 8, 21, 22, 13, 18, 20, 17, 5, 23, 16, 3, 6...","[3, 12, 18, 20, 21, 22, 0, 5, 14, 8, 25, 23, 2...","[8, 18, 22, 14, 23, 19, 5, 21, 3, 0, 13, 17, 2..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"[10, 5, 8, 11, 20, 18, 21, 4, 3, 9, 19, 14, 6,...","[5, 3, 0, 6, 19, 20, 11, 16, 18, 15, 2, 21, 14...","[5, 10, 3, 16, 19, 18, 6, 20, 0, 12, 2, 9, 11,...","[0, 16, 20, 3, 5, 12, 21, 17, 19, 15, 11, 22, ..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"[0, 4, 1, 18, 19, 16, 20, 11, 24, 22, 15, 6, 1...","[0, 11, 16, 12, 15, 21, 20, 10, 26, 4, 2, 13, ...","[4, 10, 17, 1, 13, 21, 27, 14, 0, 2, 11, 19, 6...","[0, 13, 17, 23, 14, 15, 24, 26, 12, 27, 16, 1,..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"[13, 40, 41, 15, 42, 37, 36, 23, 22, 33, 16, 3...","[0, 41, 42, 37, 23, 26, 25, 39, 38, 16, 33, 27...","[8, 4, 36, 40, 0, 1, 22, 26, 17, 18, 25, 32, 2...","[41, 42, 23, 37, 33, 16, 38, 40, 39, 17, 27, 1..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","[30, 15, 21, 29, 24, 14, 13, 9, 19, 12, 16, 25...","[8, 10, 7, 12, 14, 18, 5, 0, 30, 25, 28, 21, 2...","[9, 13, 11, 15, 10, 24, 29, 12, 14, 25, 7, 18,...","[35, 0, 10, 6, 9, 30, 13, 33, 16, 19, 2, 15, 1..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"[1, 28, 29, 19, 22, 26, 2, 27, 12, 0, 5, 24, 7...","[17, 25, 16, 21, 24, 23, 29, 30, 26, 5, 12, 28...","[19, 2, 24, 27, 5, 15, 12, 26, 29, 7, 4, 22, 0...","[17, 30, 25, 4, 24, 13, 29, 8, 5, 12, 26, 9, 2..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"[8, 2, 24, 4, 7, 1, 15, 25, 18, 3, 10, 0, 5, 1...","[26, 17, 28, 25, 7, 22, 0, 20, 5, 18, 11, 14, ...","[8, 0, 24, 4, 18, 7, 10, 11, 14, 15, 16, 26, 6...","[8, 6, 5, 17, 12, 30, 15, 0, 23, 18, 7, 29, 11..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","[13, 10, 8, 12, 9, 1, 14, 7, 2, 11, 23, 18, 20...","[11, 14, 20, 23, 9, 1, 12, 21, 10, 0, 25, 7, 1...","[13, 25, 7, 27, 9, 14, 2, 1, 23, 12, 11, 21, 2...","[12, 4, 17, 23, 11, 29, 14, 15, 1, 2, 3, 24, 8..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"[15, 16, 0, 13, 1, 2, 28, 3, 4, 7, 24, 26, 6, ...","[0, 18, 20, 26, 28, 17, 21, 3, 24, 4, 9, 23, 1...","[15, 19, 16, 0, 18, 20, 1, 9, 17, 7, 4, 3, 23,...","[0, 18, 20, 17, 21, 15, 24, 10, 9, 14, 22, 23,..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"[15, 14, 8, 26, 7, 30, 32, 6, 21, 29, 25, 4, 3...","[25, 0, 22, 27, 17, 1, 24, 29, 14, 7, 31, 2, 2...","[15, 26, 8, 28, 30, 36, 34, 14, 32, 38, 1, 11,...","[14, 11, 20, 10, 1, 0, 25, 2, 12, 9, 29, 7, 13..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"[5, 7, 6, 14, 24, 15, 8, 4, 13, 9, 23, 21, 22,...","[0, 17, 14, 9, 24, 15, 3, 13, 7, 21, 11, 8, 12...","[8, 0, 5, 10, 11, 9, 17, 2, 19, 15, 22, 13, 3,...","[24, 7, 21, 0, 17, 2, 3, 12, 14, 1, 6, 15, 16,..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"[0, 23, 22, 1, 3, 2, 4, 15, 11, 21, 10, 9, 5, ...","[0, 14, 11, 16, 13, 18, 20, 9, 6, 3, 23, 8, 7,...","[15, 17, 19, 21, 1, 16, 20, 13, 11, 3, 18, 6, ...","[0, 9, 14, 6, 7, 17, 20, 3, 23, 19, 8, 26, 16,..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"[14, 17, 6, 19, 26, 25, 11, 23, 18, 24, 16, 32...","[31, 5, 3, 29, 27, 17, 20, 16, 21, 8, 13, 0, 2...","[16, 26, 2, 24, 32, 30, 28, 21, 0, 10, 6, 14, ...","[17, 20, 29, 8, 31, 16, 1, 21, 13, 18, 7, 27, ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"[42, 10, 5, 36, 9, 6, 37, 41, 7, 27, 26, 1, 28...","[25, 26, 23, 35, 37, 36, 5, 27, 38, 3, 28, 44,...","[42, 10, 37, 44, 34, 46, 28, 26, 1, 25, 3, 33,...","[26, 5, 16, 51, 36, 25, 15, 3, 17, 23, 28, 40,..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"[4, 11, 5, 7, 8, 13, 26, 18, 19, 10, 27, 17, 6...","[1, 2, 9, 0, 7, 27, 3, 8, 26, 16, 15, 25, 6, 1...","[13, 10, 6, 8, 3, 0, 1, 7, 2, 9, 16, 26, 18, 5...","[0, 2, 1, 8, 12, 3, 4, 28, 20, 7, 16, 9, 5, 27..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"[1, 0, 21, 2, 10, 60, 42, 59, 51, 23, 9, 3, 39...","[9, 5, 13, 8, 23, 46, 6, 62, 27, 49, 26, 50, 6...","[61, 43, 60, 42, 63, 58, 14, 40, 64, 53, 22, 5...","[59, 6, 26, 35, 36, 46, 55, 40, 3, 54, 15, 39,..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"[5, 2, 6, 26, 27, 28, 7, 1, 3, 19, 12, 18, 0, ...","[0, 24, 2, 11, 25, 26, 1, 16, 7, 9, 27, 8, 10,...","[2, 26, 0, 4, 22, 18, 23, 1, 8, 3, 12, 13, 20,...","[0, 7, 9, 2, 15, 8, 25, 10, 26, 4, 22, 16, 14,..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"[8, 6, 16, 1, 0, 14, 25, 27, 4, 15, 26, 10, 29...","[0, 12, 28, 5, 4, 15, 25, 27, 10, 11, 17, 20, ...","[12, 15, 8, 16, 18, 7, 0, 26, 1, 20, 30, 32, 4...","[0, 28, 5, 27, 21, 11, 29, 30, 6, 7, 18, 34, 2..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"[15, 1, 3, 16, 4, 0, 2, 14, 13, 5, 12, 11, 6, ...","[14, 16, 0, 12, 18, 6, 7, 11, 5, 15, 17, 13, 2...","[2, 9, 0, 1, 12, 4, 11, 3, 15, 6, 5, 13, 18, 1...","[14, 16, 12, 5, 6, 0, 13, 15, 17, 1, 7, 2, 4, ..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"[5, 22, 20, 6, 7, 0, 1, 17, 18, 32, 13, 28, 2,...","[2, 16, 25, 4, 3, 15, 17, 5, 28, 30, 9, 11, 27...","[15, 22, 4, 0, 18, 17, 25, 33, 5, 3, 16, 26, 2...","[3, 6, 16, 18, 11, 14, 26, 5, 10, 8, 12, 17, 2..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"[32, 31, 11, 7, 5, 6, 12, 35, 19, 33, 22, 14, ...","[17, 1, 2, 18, 14, 6, 38, 40, 24, 22, 7, 13, 2...","[26, 34, 32, 11, 0, 4, 1, 3, 2, 15, 17, 20, 10...","[7, 1, 43, 40, 45, 34, 2, 42, 9, 44, 25, 28, 4..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"[9, 10, 16, 17, 2, 1, 21, 5, 6, 15, 18, 4, 22,...","[17, 21, 2, 15, 27, 10, 16, 18, 20, 5, 26, 0, ...","[16, 32, 5, 3, 18, 19, 20, 9, 2, 17, 12, 21, 6...","[11, 16, 17, 7, 0, 19, 21, 18, 28, 22, 8, 3, 1..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"[1, 0, 2, 4, 3, 7, 6, 5, 10, 9, 12, 11, 13, 8]","[0, 12, 2, 1, 4, 6, 7, 10, 3, 13, 8, 11, 9, 5]","[1, 12, 13, 11, 4, 0, 3, 7, 2, 6, 10, 5, 8, 9]","[18, 0, 1, 2, 3, 7, 8, 5, 9, 13, 12, 10, 6, 16..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"[7, 6, 8, 15, 5, 0, 13, 9, 22, 1, 17, 21, 18, ...","[26, 28, 5, 9, 10, 12, 4, 16, 18, 25, 13, 27, ...","[5, 3, 10, 24, 27, 1, 13, 25, 23, 14, 7, 8, 0,...","[30, 5, 10, 14, 18, 20, 28, 11, 3, 9, 7, 4, 15..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"[44, 43, 54, 53, 25, 41, 26, 42, 82, 80, 78, 7...","[44, 47, 79, 50, 74, 46, 39, 81, 31, 78, 82, 5...",[None],"[50, 23, 26, 72, 66, 74, 58, 53, 82, 18, 70, 1..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"[18, 17, 14, 1, 5, 21, 12, 23, 16, 26, 4, 6, 2...","[11, 19, 23, 6, 22, 24, 21, 25, 15, 27, 10, 12...","[18, 11, 6, 15, 27, 14, 0, 23, 22, 24, 10, 12,...","[23, 4, 15, 22, 11, 27, 19, 24, 16, 26, 1, 21,..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","[20, 1, 8, 10, 9, 13, 11, 21, 16, 0, 12, 15, 2...","[8, 17, 16, 3, 7, 4, 6, 2, 18, 10, 14, 9, 0, 1...","[8, 20, 3, 10, 0, 9, 2, 21, 12, 14, 13, 1, 5, ...","[17, 3, 7, 16, 2, 5, 1, 4, 6, 8, 18, 19, 20, 2..."

In [7]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withrank_noenzyme.pickle')

In [8]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

# 示例使用
nums = [1, 2, 2, 3, 4, 3, 5, 1, 6]
n = 4
result = get_unique_numbers(nums, n)
print(result)  # 输出: [1, 2, 3, 4]

[1, 2, 3, 4]

In [9]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withrank_noenzyme.pickle')

# metapredictor_results_old = df_total['metapredictor_results_old'].to_list()
# ourmodel_results_old = df_total['ourmodel_results_old'].to_list()
# ourmodel_results_new = []
# for i in ourmodel_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     ourmodel_results_new.append(list_part)
# metapredictor_results_new = []
# for i in metapredictor_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     metapredictor_results_new.append(list_part)

# true_sites_old = df_total['true_sites_old'].to_list()
true_sites = df_total['sites'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

# def acc_top_n_old(n,modelresults,true_sites):
#     total_num = len(true_sites)
#     correct_num = 0
#     for idx,i in enumerate(true_sites):
#         modelresult = modelresults[idx]
#         modelresult = get_unique_numbers(modelresult, n)
#         modelresult = set(modelresult)
#         i = set(i)
#         intersection = i & modelresult
#         if len(intersection) > 0:
#             correct_num = correct_num + 1
#     acc = correct_num/total_num
#     print(f'top {n} accuracy = {acc}')
#     return acc

gnn_top1_acc = acc_top_n(1,gnn_sorted_atoms,true_sites)
gnn_top3_acc = acc_top_n(3,gnn_sorted_atoms,true_sites)
gnn_top5_acc = acc_top_n(5,gnn_sorted_atoms,true_sites)
gnn_topn = []
gnn_topn.append(gnn_top1_acc)
gnn_topn.append(gnn_top3_acc)
gnn_topn.append(gnn_top5_acc)

smartcyp_top1_acc = acc_top_n(1,smartcyp_sorted_atoms,true_sites)
smartcyp_top3_acc = acc_top_n(3,smartcyp_sorted_atoms,true_sites)
smartcyp_top5_acc = acc_top_n(5,smartcyp_sorted_atoms,true_sites)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

xenosite_top1_acc = acc_top_n(1,xenosite_sorted_atoms,true_sites)
xenosite_top3_acc = acc_top_n(3,xenosite_sorted_atoms,true_sites)
xenosite_top5_acc = acc_top_n(5,xenosite_sorted_atoms,true_sites)
xenosite_topn = []
xenosite_topn.append(xenosite_top1_acc)
xenosite_topn.append(xenosite_top3_acc)
xenosite_topn.append(xenosite_top5_acc)

somp_top1_acc = acc_top_n(1,somp_sorted_atoms,true_sites)
somp_top3_acc = acc_top_n(3,somp_sorted_atoms,true_sites)
somp_top5_acc = acc_top_n(5,somp_sorted_atoms,true_sites)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

# metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites_old)
# metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites_old)
# metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites_old)
# metapredictor_topn = []
# metapredictor_topn.append(metapredictor_top1_acc)
# metapredictor_topn.append(metapredictor_top3_acc)
# metapredictor_topn.append(metapredictor_top5_acc)

# ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
# ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
# ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
# ourmodel_topn = []
# ourmodel_topn.append(ourmodel_top1_acc)
# ourmodel_topn.append(ourmodel_top3_acc)
# ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.13821138211382114
top 3 accuracy = 0.43089430894308944
top 5 accuracy = 0.6097560975609756
top 1 accuracy = 0.10569105691056911
top 3 accuracy = 0.3008130081300813
top 5 accuracy = 0.45528455284552843
top 1 accuracy = 0.2682926829268293
top 3 accuracy = 0.5040650406504065
top 5 accuracy = 0.6341463414634146
top 1 accuracy = 0.15447154471544716
top 3 accuracy = 0.35772357723577236
top 5 accuracy = 0.43089430894308944

In [10]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['gnnsom_topn'] = gnn_topn
df['smartcyp_topn'] = smartcyp_topn
df['xenosite_topn'] = xenosite_topn
df['somp_topn'] = somp_topn
# df['metapredictor_topn'] = metapredictor_topn
# df['ourmodel_topn'] = ourmodel_topn
df

         top_n  gnnsom_topn  smartcyp_topn  xenosite_topn  somp_topn
0  top1_recall     0.138211       0.105691       0.268293   0.154472
1  top3_recall     0.430894       0.300813       0.504065   0.357724
2  top5_recall     0.609756       0.455285       0.634146   0.430894