In [1]:
import pandas as pd
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/GNN-SOM-master/123_site_from_smiles.csv')
substrates = df['substrate'].to_list()
ecs = [(1,14) for _ in range(len(substrates))]
# dict_sub2ec = dict(zip(substrates,ecs))
# ecs = [i.strip() for i in ecs]

# # 凡是没有EC的我们用1.14代替
# ecs = [i.replace('None','1.14') for i in ecs]
# ecs = [i.split(' ') for i in ecs]
# ecs_new = []
# for eclist in ecs:
#     eclist = [tuple([int(j) for j in i.split('.')[:2]]) for i in eclist]
#     eclist = list(set(eclist))
#     ecs_new.append(eclist)

# subs_new = []
# for i in range(len(substrates)):
#     ecs = ecs_new[i]
#     num_repeat = len(ecs)
#     subs = [substrates[i] for _ in range(num_repeat)]
#     subs_new = subs_new + subs

# ecs_new = [i for k in ecs_new for i in k]

df_new = pd.DataFrame(columns=['substrate','ec','score'])
df_new['substrate'] = substrates
df_new['ec'] = ecs
df_new['score'] = ['None' for _ in range(len(substrates))]
df_new

                                             substrate       ec score
0      CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O  (1, 14)  None
1      CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2  (1, 14)  None
2    CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=C...  (1, 14)  None
3    CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=...  (1, 14)  None
4    CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=C...  (1, 14)  None
..                                                 ...      ...   ...
118  OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=C...  (1, 14)  None
119  OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC...  (1, 14)  None
120     OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2  (1, 14)  None
121  OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=...  (1, 14)  None
122                              C1=CN=C(N2CCNCC2)N=C1  (1, 14)  None

[123 rows x 3 columns]

In [4]:
from tqdm import tqdm

import json
from os.path import isfile

import torch
from torch_geometric.data import Data
from rdkit.Chem import Draw
import requests

from IPython.display import SVG

from gnn_som import createGnnSom, loadGnnSomState
from gnn_som.MolFromKcf import MolFromKcfFile

import os

from rdkit import Chem
from rdkit.Chem import AllChem

os.environ['CUDA_VISIBLE_DEVICES'] = "2"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

with open('data/config.json', 'r') as f:
    config = json.load(f)
config['features']['enzyme'] = [tuple(ec) for ec in config['features']['enzyme']] 

models = []
for i, params in enumerate(config['models']):
    model = createGnnSom(*config['models'][i])
    loadGnnSomState(model, torch.load('data/model%d.pt' % i, map_location=torch.device('cpu')))
    models.append(model)

# Convert SMILES to .mol file using RDKit 

atom_scores_list = []

for i in tqdm(range(len(df_new))):
    smi = df_new.iloc[i,0]
    enzyme = df_new.iloc[i,1]


    # Create RDKit mol object
    # molecule = 'CC1([C@@H]2[C@H]1[C@H](N(C2)C(=O)[C@H](C(C)(C)C)NC(=O)C(F)(F)F)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C#N)C'
    print(smi)
    molecule = Chem.MolFromSmiles(smi)
    molecule = Chem.AddHs(molecule)

    if os.path.exists("molecule.mol"):
        os.remove("molecule.mol")

    # Compute 2D coordenates and write to .mol file
    AllChem.Compute2DCoords(molecule)
    print(Chem.MolToMolBlock(molecule), file=open("molecule.mol", 'a+'))

    if os.path.exists("molecule.kcf"):
        os.remove("molecule.kcf")

    # Convert .mol to .kcf (KEGG format used in the paper) 
    # https://iwatobipen.wordpress.com/2016/12/23/convert-chemical-file-format/
    # https://www.genome.jp/tools/gn_ca_tools_api.html
    !curl -F molfile=@molecule.mol http://rest.genome.jp/mol2kcf/ > molecule.kcf

    # Define mol
    mol = MolFromKcfFile('molecule.kcf')

        # enzyme = (2,4)

    print(enzyme)
    numFeatures = sum(len(feature) for feature in config['features'].values())
    x = torch.zeros((mol.GetNumAtoms(), numFeatures), dtype=torch.float32)
    for atom in mol.GetAtoms():
        x[atom.GetIdx(), config['features']['enzyme'].index(enzyme)] = 1
        offset = len(config['features']['enzyme'])
        x[atom.GetIdx(), offset + config['features']['element'].index(atom.GetSymbol())] = 1
        offset += len(config['features']['element'])
        x[atom.GetIdx(), offset + config['features']['kcfType'].index(atom.GetProp('kcfType'))] = 1

    edgeIndex = torch.zeros((2, mol.GetNumBonds() * 2), dtype=torch.int64)
    for bond in mol.GetBonds():
        i = bond.GetIdx()
        edgeIndex[0][i * 2] = bond.GetBeginAtomIdx()
        edgeIndex[1][i * 2] = bond.GetEndAtomIdx()
        edgeIndex[0][i * 2 + 1] = bond.GetEndAtomIdx()
        edgeIndex[1][i * 2 + 1] = bond.GetBeginAtomIdx()

    data = Data(x=x, edgeIndex=edgeIndex)

    # 确保模型和数据都在同一设备上运行
    data = data.to(device)  # 将数据移动到 GPU 或保持在 CPU
    y = None

    for model in models:
        model = model.to(device)  # 将每个模型移动到 GPU（如果尚未移动）
        newY = torch.sigmoid(model(data.x, data.edgeIndex))  # 数据已在 GPU 或 CPU 上
        y = newY if y is None else torch.add(y, newY)

    # 计算模型平均输出
    y = torch.div(y, len(models))
    print(y.shape)

    # import torch

    # # 假设 scores 是你的 torch 张量，大小是 [14, 1]
    # scores = y  # 示例：14个原子的反应分数，实际使用时替换为你的数据

    # # 创建一个空字典来存储原子序号和对应的分数
    # atom_scores = {}

    # # 将分数映射到原子序号
    # for idx, score in enumerate(scores):
    #     atom_scores[idx] = score.item()  # 使用 item() 将张量转换为标量

    # 打印结果
    # print(atom_scores)

    atom_scores_list.append(y)

    print(f'substrate: {smi}, ec: {enzyme}, score: {y}')

/tmp/ipykernel_352752/3440858778.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loadGnnSomState(model, torch.load('data/model%d.pt' % i, map_location=torch.device('cpu')))
  0%|          | 0/72 [00:00<?, ?it/s]

C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7167    0  2034  100  5133   4570  11534 --:--:-- --:--:-- --:--:-- 16105
(1, 14)

  1%|▏         | 1/72 [00:02<02:35,  2.18s/it]

torch.Size([27, 1])
substrate: C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC, ec: (1, 14), score: tensor([[0.1723],
        [0.2866],
        [0.5596],
        [0.6462],
        [0.4943],
        [0.0226],
        [0.0584],
        [0.1977],
        [0.0186],
        [0.0059],
        [0.0049],
        [0.0308],
        [0.0327],
        [0.0077],
        [0.0733],
        [0.1889],
        [0.4892],
        [0.5515],
        [0.1425],
        [0.0872],
        [0.0181],
        [0.0025],
        [0.0077],
        [0.0172],
        [0.0121],
        [0.0360],
        [0.0486]], device='cuda:0', grad_fn=<DivBackward0>)
CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9739    0  3016  100  6723   5026  11205 --:--:-- --:--:-- --:--:-- 16231
(2, 4)

  3%|▎         | 2/72 [00:03<01:51,  1.59s/it]

torch.Size([41, 1])
substrate: CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1, ec: (2, 4), score: tensor([[3.4605e-02],
        [1.9624e-01],
        [3.8881e-02],
        [7.8217e-01],
        [6.5731e-03],
        [8.7484e-04],
        [4.7396e-04],
        [2.4858e-04],
        [2.3519e-03],
        [4.6296e-05],
        [1.2279e-04],
        [1.2823e-05],
        [1.4799e-04],
        [5.8173e-02],
        [7.7778e-05],
        [3.2717e-05],
        [1.5715e-04],
        [8.8820e-02],
        [1.0391e-02],
        [4.6588e-01],
        [4.5299e-04],
        [4.7600e-05],
        [3.0563e-06],
        [1.5319e-03],
        [5.4656e-04],
        [3.0717e-03],
        [2.6015e-04],
        [7.1433e-04],
        [2.4879e-04],
        [9.6100e-04],
        [7.0923e-04],
        [2.0172e-03],
        [7.8139e-04],
        [1.5243e-03],
        [1.7542e-04],
        [7.1614e-03],
        [7.4282e-02],
        [6.1563e-05],
        [2.8552e-03],
        [2.4379e-01],
        [3.0755e-05]], device='cuda:0', grad_fn=<DivBackward0>)
CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9739    0  3016  100  6723   6056  13500 --:--:-- --:--:-- --:--:-- 19556
(1, 14)

  4%|▍         | 3/72 [00:04<01:41,  1.47s/it]

torch.Size([41, 1])
substrate: CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1, ec: (1, 14), score: tensor([[0.2603],
        [0.9418],
        [0.2670],
        [0.8491],
        [0.0681],
        [0.0886],
        [0.0864],
        [0.0475],
        [0.0912],
        [0.0125],
        [0.0036],
        [0.0097],
        [0.1325],
        [0.4873],
        [0.0416],
        [0.0113],
        [0.0746],
        [0.0817],
        [0.0311],
        [0.1524],
        [0.0582],
        [0.0471],
        [0.0054],
        [0.0645],
        [0.0561],
        [0.0294],
        [0.0213],
        [0.0607],
        [0.0534],
        [0.0330],
        [0.5388],
        [0.8273],
        [0.2413],
        [0.4014],
        [0.2684],
        [0.0727],
        [0.0730],
        [0.0963],
        [0.0664],
        [0.1704],
        [0.0132]], device='cuda:0', grad_fn=<DivBackward0>)
CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6717    0  1929  100  4788   4822  11970 --:--:-- --:--:-- --:--:-- 16750
(1, 14)

  6%|▌         | 4/72 [00:05<01:25,  1.26s/it]

torch.Size([26, 1])
substrate: CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1, ec: (1, 14), score: tensor([[0.0740],
        [0.0268],
        [0.0609],
        [0.2904],
        [0.7938],
        [0.5783],
        [0.0265],
        [0.1250],
        [0.0393],
        [0.0014],
        [0.0046],
        [0.1082],
        [0.0576],
        [0.1682],
        [0.1623],
        [0.1120],
        [0.9807],
        [0.7709],
        [0.7340],
        [0.6450],
        [0.0515],
        [0.0849],
        [0.0353],
        [0.1937],
        [0.0132],
        [0.0372]], device='cuda:0', grad_fn=<DivBackward0>)
CC(CN1c2ccccc2Sc2ccccc21)N(C)C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5141    0  1515  100  3626   4809  11511 --:--:-- --:--:-- --:--:-- 16320
(1, 14)

  7%|▋         | 5/72 [00:06<01:19,  1.18s/it]

torch.Size([20, 1])
substrate: CC(CN1c2ccccc2Sc2ccccc21)N(C)C, ec: (1, 14), score: tensor([[0.0637],
        [0.2708],
        [0.4764],
        [0.4391],
        [0.0302],
        [0.0607],
        [0.0667],
        [0.0605],
        [0.0183],
        [0.0741],
        [0.1696],
        [0.0216],
        [0.0204],
        [0.0488],
        [0.1105],
        [0.0891],
        [0.0153],
        [0.9433],
        [0.8653],
        [0.9299]], device='cuda:0', grad_fn=<DivBackward0>)
CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14084    0  4474  100  9610   5456  11719 --:--:-- --:--:-- --:--:-- 17154
(1, 14)

  8%|▊         | 6/72 [00:08<01:24,  1.28s/it]

torch.Size([61, 1])
substrate: CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1, ec: (1, 14), score: tensor([[0.1239],
        [0.0657],
        [0.1263],
        [0.0571],
        [0.1392],
        [0.1860],
        [0.1800],
        [0.1393],
        [0.4979],
        [0.3057],
        [0.0629],
        [0.0138],
        [0.0937],
        [0.0413],
        [0.0234],
        [0.1822],
        [0.0586],
        [0.1951],
        [0.6805],
        [0.2791],
        [0.2235],
        [0.0022],
        [0.0119],
        [0.0146],
        [0.0908],
        [0.3613],
        [0.0727],
        [0.0534],
        [0.0306],
        [0.0837],
        [0.0141],
        [0.1154],
        [0.0512],
        [0.1120],
        [0.8480],
        [0.4895],
        [0.4055],
        [0.0026],
        [0.1390],
        [0.3504],
        [0.3097],
        [0.0079],
        [0.0395],
        [0.0023],
        [0.2630],
        [0.2186],
        [0.1918],
        [0.1084],
        [0.1345],
        [0.0493],
        [0.1993],
        [0.3816],
        [0.1251],
        [0.1712],
        [0.3818],
        [0.1673],
        [0.0108],
        [0.1442],
        [0.1855],
        [0.3724],
        [0.1675]], device='cuda:0', grad_fn=<DivBackward0>)
CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5818    0  1860  100  3958   4757  10122 --:--:-- --:--:-- --:--:-- 14879
(1, 14)

 10%|▉         | 7/72 [00:09<01:18,  1.21s/it]

torch.Size([25, 1])
substrate: CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O, ec: (1, 14), score: tensor([[0.0648],
        [0.0809],
        [0.1062],
        [0.0330],
        [0.0807],
        [0.1117],
        [0.2123],
        [0.3057],
        [0.0640],
        [0.3753],
        [0.5843],
        [0.0129],
        [0.0123],
        [0.0635],
        [0.1604],
        [0.4415],
        [0.0825],
        [0.0100],
        [0.0607],
        [0.0196],
        [0.0050],
        [0.0139],
        [0.0059],
        [0.0013],
        [0.0077]], device='cuda:0', grad_fn=<DivBackward0>)
CCC1(c2ccccc2)C(=O)NC(=O)NC1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3982    0  1282  100  2700   4316   9090 --:--:-- --:--:-- --:--:-- 13407
(1, 14)

 11%|█         | 8/72 [00:10<01:11,  1.12s/it]

torch.Size([17, 1])
substrate: CCC1(c2ccccc2)C(=O)NC(=O)NC1=O, ec: (1, 14), score: tensor([[0.2986],
        [0.3850],
        [0.8290],
        [0.0755],
        [0.1583],
        [0.0174],
        [0.0222],
        [0.0078],
        [0.1153],
        [0.5753],
        [0.3938],
        [0.3426],
        [0.3226],
        [0.1295],
        [0.3521],
        [0.5999],
        [0.3431]], device='cuda:0', grad_fn=<DivBackward0>)
CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4947    0  1653  100  3294   5247  10457 --:--:-- --:--:-- --:--:-- 15704
(1, 14)

 12%|█▎        | 9/72 [00:10<01:04,  1.02s/it]

torch.Size([22, 1])
substrate: CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1, ec: (1, 14), score: tensor([[0.0131],
        [0.2503],
        [0.1871],
        [0.0471],
        [0.0151],
        [0.0517],
        [0.0276],
        [0.0408],
        [0.0681],
        [0.0071],
        [0.4116],
        [0.7553],
        [0.1763],
        [0.3930],
        [0.0634],
        [0.1234],
        [0.0931],
        [0.1989],
        [0.1864],
        [0.0966],
        [0.0742],
        [0.1694]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6446    0  1601  100  4845   4191  12683 --:--:-- --:--:-- --:--:-- 16830
(2, 7)

 14%|█▍        | 10/72 [00:12<01:04,  1.03s/it]

torch.Size([22, 1])
substrate: CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1, ec: (2, 7), score: tensor([[1.5884e-02],
        [2.0781e-04],
        [1.6601e-06],
        [5.7344e-06],
        [6.3736e-04],
        [4.6342e-06],
        [7.9127e-04],
        [1.1702e-05],
        [3.9377e-06],
        [2.2603e-06],
        [5.0601e-06],
        [1.2842e-05],
        [8.2795e-06],
        [1.2163e-05],
        [2.9037e-02],
        [3.0159e-01],
        [1.2756e-01],
        [8.9764e-01],
        [7.4267e-02],
        [8.9885e-01],
        [1.0761e-04],
        [4.4984e-06]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11146    0  2981  100  8165   7844  21486 --:--:-- --:--:-- --:--:-- 29254
(3, 1)

 15%|█▌        | 11/72 [00:13<01:11,  1.18s/it]

torch.Size([42, 1])
substrate: CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1, ec: (3, 1), score: tensor([[1.6345e-03],
        [1.7848e-03],
        [1.9899e-04],
        [4.3165e-04],
        [9.1358e-02],
        [1.4612e-02],
        [1.2316e-03],
        [7.4134e-03],
        [2.5079e-04],
        [7.8575e-01],
        [3.1376e-03],
        [9.4798e-01],
        [4.2692e-01],
        [1.0495e-01],
        [2.7901e-01],
        [3.5985e-03],
        [1.4048e-02],
        [7.7761e-02],
        [9.0176e-04],
        [1.3365e-03],
        [8.1885e-02],
        [8.7654e-04],
        [1.2660e-03],
        [5.6994e-02],
        [6.4569e-04],
        [1.4450e-03],
        [5.8638e-02],
        [8.6392e-04],
        [3.7837e-04],
        [4.9342e-02],
        [3.1963e-03],
        [4.9516e-03],
        [2.7499e-02],
        [5.0097e-03],
        [9.8933e-03],
        [1.6474e-01],
        [3.2978e-03],
        [1.4000e-02],
        [1.6448e-01],
        [1.0131e-01],
        [9.8125e-03],
        [3.4631e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7560    0  2274  100  5286   5742  13348 --:--:-- --:--:-- --:--:-- 19090
(1, 14)

 17%|█▋        | 12/72 [00:14<01:08,  1.14s/it]

torch.Size([31, 1])
substrate: CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1, ec: (1, 14), score: tensor([[0.3241],
        [0.4649],
        [0.1849],
        [0.1563],
        [0.0552],
        [0.1086],
        [0.0377],
        [0.0623],
        [0.0790],
        [0.0454],
        [0.1322],
        [0.0051],
        [0.0654],
        [0.4094],
        [0.2887],
        [0.0513],
        [0.0440],
        [0.0057],
        [0.0323],
        [0.0142],
        [0.4599],
        [0.5760],
        [0.1935],
        [0.0929],
        [0.3597],
        [0.2089],
        [0.1775],
        [0.1497],
        [0.0074],
        [0.0345],
        [0.0500]], device='cuda:0', grad_fn=<DivBackward0>)
CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8315    0  2671  100  5644   1799   3803  0:00:01  0:00:01 --:--:--  5603
(1, 14)

 18%|█▊        | 13/72 [00:16<01:26,  1.47s/it]

torch.Size([36, 1])
substrate: CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1, ec: (1, 14), score: tensor([[3.0554e-01],
        [1.3685e-01],
        [2.9343e-01],
        [5.6083e-01],
        [2.1835e-02],
        [6.0954e-03],
        [2.1365e-03],
        [2.9892e-02],
        [2.0540e-01],
        [1.4918e-01],
        [1.7499e-01],
        [7.4127e-02],
        [1.8047e-01],
        [7.6112e-02],
        [1.4059e-02],
        [1.6075e-02],
        [6.8800e-02],
        [6.0721e-02],
        [6.3711e-02],
        [1.5496e-04],
        [7.7667e-04],
        [3.8688e-03],
        [5.2460e-03],
        [6.0718e-03],
        [2.1843e-03],
        [3.6174e-03],
        [2.8614e-02],
        [3.8255e-02],
        [2.1715e-01],
        [3.1932e-01],
        [6.1708e-02],
        [1.0199e-01],
        [3.4301e-02],
        [1.3927e-01],
        [1.2203e-04],
        [3.7291e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7245    0  1972  100  5273   5082  13590 --:--:-- --:--:-- --:--:-- 18624
(1, 14)

 19%|█▉        | 14/72 [00:17<01:16,  1.31s/it]

torch.Size([27, 1])
substrate: CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1, ec: (1, 14), score: tensor([[0.1145],
        [0.0834],
        [0.0450],
        [0.1604],
        [0.1057],
        [0.0454],
        [0.1050],
        [0.0086],
        [0.0626],
        [0.0048],
        [0.0598],
        [0.0073],
        [0.0435],
        [0.0032],
        [0.0009],
        [0.0037],
        [0.1170],
        [0.0092],
        [0.0200],
        [0.0316],
        [0.0787],
        [0.2182],
        [0.1014],
        [0.3329],
        [0.0610],
        [0.1426],
        [0.0875]], device='cuda:0', grad_fn=<DivBackward0>)
CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5229    0  1463  100  3766   3932  10123 --:--:-- --:--:-- --:--:-- 14056
(1, 14)

 21%|██        | 15/72 [00:18<01:08,  1.21s/it]

torch.Size([20, 1])
substrate: CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC, ec: (1, 14), score: tensor([[0.2063],
        [0.1962],
        [0.0666],
        [0.2103],
        [0.1359],
        [0.0905],
        [0.0107],
        [0.2983],
        [0.5840],
        [0.1113],
        [0.0442],
        [0.0337],
        [0.1210],
        [0.2518],
        [0.3515],
        [0.6736],
        [0.1344],
        [0.1332],
        [0.4778],
        [0.4645]], device='cuda:0', grad_fn=<DivBackward0>)
CCN(CC)CCOC(=O)c1ccc(N)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4607    0  1256  100  3351   4301  11476 --:--:-- --:--:-- --:--:-- 15723
(3, 1)
torch.Size([17, 1])

 22%|██▏       | 16/72 [00:19<01:03,  1.14s/it]

substrate: CCN(CC)CCOC(=O)c1ccc(N)cc1, ec: (3, 1), score: tensor([[9.7363e-04],
        [3.7961e-04],
        [7.2240e-03],
        [5.5292e-04],
        [1.7018e-03],
        [6.1201e-03],
        [6.5847e-01],
        [9.9778e-01],
        [9.7132e-01],
        [2.4339e-03],
        [1.1685e-02],
        [7.5297e-03],
        [6.8202e-04],
        [5.6645e-04],
        [6.1336e-02],
        [4.5683e-04],
        [7.0499e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10555    0  3085  100  7470   6207  15030 --:--:-- --:--:-- --:--:-- 21194
(1, 14)

 24%|██▎       | 17/72 [00:20<01:01,  1.12s/it]

torch.Size([42, 1])
substrate: CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1, ec: (1, 14), score: tensor([[0.1098],
        [0.3065],
        [0.3604],
        [0.0934],
        [0.0817],
        [0.0596],
        [0.0758],
        [0.0964],
        [0.1666],
        [0.0387],
        [0.2923],
        [0.5816],
        [0.4683],
        [0.5341],
        [0.1018],
        [0.3788],
        [0.5152],
        [0.1759],
        [0.0524],
        [0.0919],
        [0.0360],
        [0.6588],
        [0.2526],
        [0.6455],
        [0.4037],
        [0.1575],
        [0.0401],
        [0.1525],
        [0.0633],
        [0.1126],
        [0.1847],
        [0.1874],
        [0.1217],
        [0.0323],
        [0.0065],
        [0.0307],
        [0.1177],
        [0.1095],
        [0.1683],
        [0.0593],
        [0.1449],
        [0.1486]], device='cuda:0', grad_fn=<DivBackward0>)
CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4618    0  1420  100  3198   4781  10767 --:--:-- --:--:-- --:--:-- 15548
(1, 14)

 25%|██▌       | 18/72 [00:21<00:58,  1.08s/it]

torch.Size([19, 1])
substrate: CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21, ec: (1, 14), score: tensor([[1.6138e-03],
        [9.9114e-02],
        [9.4367e-02],
        [5.0814e-02],
        [7.2899e-03],
        [1.6758e-02],
        [3.3556e-03],
        [7.2084e-01],
        [4.7714e-01],
        [6.3114e-01],
        [3.7290e-03],
        [4.7887e-02],
        [1.7341e-02],
        [7.7168e-01],
        [1.7810e-01],
        [5.4432e-01],
        [4.4184e-01],
        [1.2323e-03],
        [3.3047e-04]], device='cuda:0', grad_fn=<DivBackward0>)
CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7256    0  2136  100  5120   5110  12248 --:--:-- --:--:-- --:--:-- 17358
(1, 14)

 26%|██▋       | 19/72 [00:22<00:56,  1.06s/it]

torch.Size([29, 1])
substrate: CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2, ec: (1, 14), score: tensor([[0.0071],
        [0.1440],
        [0.1918],
        [0.6039],
        [0.0179],
        [0.5679],
        [0.2463],
        [0.2017],
        [0.0762],
        [0.0417],
        [0.0695],
        [0.0658],
        [0.0863],
        [0.2735],
        [0.1206],
        [0.2150],
        [0.5679],
        [0.5298],
        [0.1017],
        [0.6802],
        [0.2445],
        [0.0202],
        [0.1525],
        [0.2275],
        [0.1501],
        [0.0873],
        [0.0055],
        [0.0247],
        [0.0240]], device='cuda:0', grad_fn=<DivBackward0>)
CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6924    0  2136  100  4788   3977   8916 --:--:-- --:--:-- --:--:-- 12869
(2, 4)

 28%|██▊       | 20/72 [00:23<00:57,  1.10s/it]

torch.Size([29, 1])
substrate: CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12, ec: (2, 4), score: tensor([[4.6835e-04],
        [5.7486e-04],
        [2.5241e-01],
        [3.1401e-01],
        [5.4651e-03],
        [3.5002e-04],
        [3.2286e-04],
        [4.1376e-04],
        [1.3650e-01],
        [4.6978e-04],
        [2.0685e-04],
        [3.0662e-04],
        [5.2347e-04],
        [5.3872e-04],
        [1.3003e-03],
        [1.1493e-01],
        [1.1361e-01],
        [1.3280e-04],
        [9.9178e-04],
        [2.2849e-03],
        [1.2697e-01],
        [8.9205e-02],
        [6.2940e-01],
        [1.4600e-03],
        [1.8080e-03],
        [2.1311e-01],
        [1.6204e-01],
        [1.3435e-01],
        [1.0063e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6924    0  2136  100  4788   5435  12183 --:--:-- --:--:-- --:--:-- 17573
(1, 14)
torch.Size([29, 1])

 29%|██▉       | 21/72 [00:24<00:54,  1.06s/it]

substrate: CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12, ec: (1, 14), score: tensor([[0.0020],
        [0.1434],
        [0.5649],
        [0.6562],
        [0.0747],
        [0.0103],
        [0.0032],
        [0.0980],
        [0.2653],
        [0.0414],
        [0.0848],
        [0.2025],
        [0.1308],
        [0.1029],
        [0.0807],
        [0.0744],
        [0.0648],
        [0.0057],
        [0.0038],
        [0.0155],
        [0.0440],
        [0.3584],
        [0.5655],
        [0.0678],
        [0.1576],
        [0.8117],
        [0.6613],
        [0.6705],
        [0.0050]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6636    0  2110  100  4526   5480  11755 --:--:-- --:--:-- --:--:-- 17236
(1, 14)

 31%|███       | 22/72 [00:26<00:53,  1.08s/it]

torch.Size([29, 1])
substrate: CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1, ec: (1, 14), score: tensor([[0.2441],
        [0.4519],
        [0.2128],
        [0.1967],
        [0.0500],
        [0.1995],
        [0.5416],
        [0.4292],
        [0.0437],
        [0.0738],
        [0.0056],
        [0.0060],
        [0.0344],
        [0.0249],
        [0.2206],
        [0.0497],
        [0.0080],
        [0.0555],
        [0.0944],
        [0.1009],
        [0.1136],
        [0.5141],
        [0.3818],
        [0.3410],
        [0.1940],
        [0.1308],
        [0.0912],
        [0.0439],
        [0.0055]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)CCCN1c2ccccc2CCc2ccccc21
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5625    0  1584  100  4041   3863   9856 --:--:-- --:--:-- --:--:-- 13719
(1, 14)

 32%|███▏      | 23/72 [00:27<00:54,  1.10s/it]

torch.Size([21, 1])
substrate: CN(C)CCCN1c2ccccc2CCc2ccccc21, ec: (1, 14), score: tensor([[0.8947],
        [0.9332],
        [0.9235],
        [0.1286],
        [0.1010],
        [0.2277],
        [0.2341],
        [0.0188],
        [0.3192],
        [0.3980],
        [0.3029],
        [0.0950],
        [0.0014],
        [0.0249],
        [0.0497],
        [0.0022],
        [0.1256],
        [0.3643],
        [0.4439],
        [0.3171],
        [0.0652]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7741    0  2442  100  5299   5426  11775 --:--:-- --:--:-- --:--:-- 17240
(1, 14)

 33%|███▎      | 24/72 [00:28<00:54,  1.13s/it]

torch.Size([33, 1])
substrate: CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O, ec: (1, 14), score: tensor([[0.3925],
        [0.4449],
        [0.3780],
        [0.0543],
        [0.0063],
        [0.0170],
        [0.0963],
        [0.1089],
        [0.0593],
        [0.0590],
        [0.3165],
        [0.0365],
        [0.0086],
        [0.0331],
        [0.0532],
        [0.1230],
        [0.0481],
        [0.0600],
        [0.0238],
        [0.0145],
        [0.1039],
        [0.0304],
        [0.0283],
        [0.0133],
        [0.1242],
        [0.0114],
        [0.4406],
        [0.5732],
        [0.3611],
        [0.2035],
        [0.1029],
        [0.2163],
        [0.0044]], device='cuda:0', grad_fn=<DivBackward0>)
CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4931    0  1541  100  3390   3951   8692 --:--:-- --:--:-- --:--:-- 12643
(1, 14)

 35%|███▍      | 25/72 [00:29<00:49,  1.06s/it]

torch.Size([20, 1])
substrate: CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3, ec: (1, 14), score: tensor([[0.0907],
        [0.0888],
        [0.1686],
        [0.0625],
        [0.0051],
        [0.0897],
        [0.1255],
        [0.1235],
        [0.0164],
        [0.0190],
        [0.0355],
        [0.0745],
        [0.0027],
        [0.0169],
        [0.0240],
        [0.8692],
        [0.8697],
        [0.8848],
        [0.8093],
        [0.0279]], device='cuda:0', grad_fn=<DivBackward0>)
CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4931    0  1541  100  3390   4087   8992 --:--:-- --:--:-- --:--:-- 13079
(2, 1)

 36%|███▌      | 26/72 [00:30<00:46,  1.02s/it]

torch.Size([20, 1])
substrate: CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3, ec: (2, 1), score: tensor([[6.3046e-01],
        [6.8725e-01],
        [3.5666e-02],
        [4.0522e-03],
        [8.0340e-04],
        [1.5682e-03],
        [4.3656e-04],
        [3.0570e-03],
        [8.2050e-04],
        [3.5082e-03],
        [8.1930e-03],
        [3.4469e-03],
        [2.2933e-04],
        [1.4825e-02],
        [1.0799e-02],
        [1.7456e-02],
        [8.7801e-01],
        [8.4155e-02],
        [6.4433e-01],
        [2.3973e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5426    0  1774  100  3652   3959   8151 --:--:-- --:--:-- --:--:-- 12111
(1, 14)

 38%|███▊      | 27/72 [00:31<00:48,  1.07s/it]

torch.Size([23, 1])
substrate: CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21, ec: (1, 14), score: tensor([[0.4530],
        [0.4358],
        [0.0141],
        [0.0699],
        [0.0727],
        [0.0924],
        [0.1165],
        [0.0463],
        [0.3001],
        [0.1070],
        [0.6031],
        [0.4061],
        [0.0730],
        [0.0165],
        [0.1680],
        [0.1211],
        [0.0440],
        [0.1430],
        [0.1846],
        [0.2544],
        [0.1065],
        [0.0336],
        [0.3652]], device='cuda:0', grad_fn=<DivBackward0>)
CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6230    0  2093  100  4137   4767   9423 --:--:-- --:--:-- --:--:-- 14191
(1, 14)

 39%|███▉      | 28/72 [00:32<00:48,  1.10s/it]

torch.Size([28, 1])
substrate: CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1, ec: (1, 14), score: tensor([[0.7678],
        [0.9058],
        [0.2775],
        [0.0710],
        [0.0094],
        [0.0680],
        [0.0948],
        [0.0547],
        [0.0363],
        [0.0201],
        [0.3932],
        [0.0413],
        [0.0515],
        [0.0407],
        [0.0149],
        [0.0153],
        [0.0713],
        [0.0596],
        [0.0392],
        [0.1991],
        [0.3189],
        [0.5188],
        [0.3813],
        [0.1466],
        [0.1795],
        [0.2935],
        [0.0478],
        [0.0089]], device='cuda:0', grad_fn=<DivBackward0>)
CNCC[C@@H](Oc1ccccc1C)c1ccccc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5033    0  1420  100  3613   4781  12164 --:--:-- --:--:-- --:--:-- 16946
(1, 14)

 40%|████      | 29/72 [00:33<00:45,  1.07s/it]

torch.Size([19, 1])
substrate: CNCC[C@@H](Oc1ccccc1C)c1ccccc1, ec: (1, 14), score: tensor([[9.4654e-01],
        [9.8405e-01],
        [2.1967e-01],
        [6.8986e-02],
        [3.6369e-01],
        [4.1798e-01],
        [2.9608e-02],
        [2.4193e-02],
        [1.7956e-02],
        [4.9251e-02],
        [2.8450e-02],
        [7.4809e-03],
        [6.7939e-02],
        [6.6642e-04],
        [3.9381e-03],
        [6.0185e-03],
        [3.2865e-03],
        [1.2507e-02],
        [8.1260e-03]], device='cuda:0', grad_fn=<DivBackward0>)
CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5417    0  1791  100  3626   5579  11295 --:--:-- --:--:-- --:--:-- 16875
(1, 14)

 42%|████▏     | 30/72 [00:34<00:44,  1.07s/it]

torch.Size([24, 1])
substrate: CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1, ec: (1, 14), score: tensor([[0.7331],
        [0.9458],
        [0.2726],
        [0.0158],
        [0.0107],
        [0.0308],
        [0.0040],
        [0.0497],
        [0.1137],
        [0.0713],
        [0.1016],
        [0.0485],
        [0.0306],
        [0.5160],
        [0.9911],
        [0.7225],
        [0.6919],
        [0.1685],
        [0.0475],
        [0.0260],
        [0.0179],
        [0.1452],
        [0.0876],
        [0.1840]], device='cuda:0', grad_fn=<DivBackward0>)
CN[C@@H](C)[C@@H](O)c1ccccc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3432    0   911  100  2521   3088   8545 --:--:-- --:--:-- --:--:-- 11633
(1, 14)

 43%|████▎     | 31/72 [00:35<00:43,  1.07s/it]

torch.Size([12, 1])
substrate: CN[C@@H](C)[C@@H](O)c1ccccc1, ec: (1, 14), score: tensor([[0.7508],
        [0.8844],
        [0.2848],
        [0.1258],
        [0.8155],
        [0.7137],
        [0.0025],
        [0.0162],
        [0.0054],
        [0.0095],
        [0.0074],
        [0.0102]], device='cuda:0', grad_fn=<DivBackward0>)
CN[C@@H](C)[C@H](O)c1ccccc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3432    0   911  100  2521   3088   8545 --:--:-- --:--:-- --:--:-- 11673
(1, 14)

 44%|████▍     | 32/72 [00:36<00:41,  1.03s/it]

torch.Size([12, 1])
substrate: CN[C@@H](C)[C@H](O)c1ccccc1, ec: (1, 14), score: tensor([[0.8176],
        [0.9227],
        [0.2692],
        [0.0186],
        [0.7434],
        [0.7151],
        [0.0032],
        [0.0193],
        [0.0132],
        [0.0056],
        [0.0318],
        [0.0259]], device='cuda:0', grad_fn=<DivBackward0>)
COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8041    0  2576  100  5465   5894  12505 --:--:-- --:--:-- --:--:-- 18358
(1, 14)

 46%|████▌     | 33/72 [00:37<00:42,  1.08s/it]

torch.Size([35, 1])
substrate: COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C, ec: (1, 14), score: tensor([[0.4872],
        [0.4571],
        [0.0443],
        [0.0222],
        [0.0077],
        [0.0552],
        [0.1878],
        [0.0022],
        [0.0905],
        [0.1707],
        [0.8481],
        [0.9820],
        [0.0285],
        [0.5898],
        [0.4085],
        [0.0213],
        [0.0557],
        [0.0143],
        [0.0250],
        [0.2059],
        [0.1775],
        [0.5234],
        [0.3284],
        [0.2975],
        [0.0591],
        [0.0071],
        [0.1870],
        [0.1203],
        [0.0510],
        [0.2170],
        [0.0519],
        [0.1173],
        [0.0845],
        [0.0437],
        [0.0576]], device='cuda:0', grad_fn=<DivBackward0>)
COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5088    0  1558  100  3530   5091  11535 --:--:-- --:--:-- --:--:-- 16573
(1, 14)

 47%|████▋     | 34/72 [00:38<00:39,  1.05s/it]

torch.Size([21, 1])
substrate: COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC, ec: (1, 14), score: tensor([[0.2383],
        [0.2048],
        [0.0857],
        [0.3487],
        [0.5170],
        [0.4722],
        [0.2776],
        [0.1429],
        [0.0803],
        [0.0053],
        [0.0290],
        [0.0285],
        [0.0152],
        [0.1392],
        [0.2854],
        [0.0862],
        [0.1646],
        [0.1484],
        [0.0070],
        [0.1774],
        [0.1159]], device='cuda:0', grad_fn=<DivBackward0>)
COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6617    0  2231  100  4386   3807   7484 --:--:-- --:--:-- --:--:-- 11272
(1, 14)

 49%|████▊     | 35/72 [00:40<00:40,  1.10s/it]

torch.Size([30, 1])
substrate: COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O, ec: (1, 14), score: tensor([[0.4144],
        [0.3528],
        [0.1196],
        [0.1598],
        [0.0541],
        [0.0763],
        [0.1663],
        [0.1585],
        [0.2297],
        [0.4012],
        [0.1517],
        [0.1185],
        [0.0495],
        [0.0024],
        [0.1447],
        [0.1497],
        [0.0423],
        [0.0950],
        [0.0042],
        [0.0619],
        [0.0807],
        [0.0380],
        [0.0732],
        [0.0516],
        [0.0628],
        [0.0065],
        [0.0064],
        [0.3531],
        [0.1469],
        [0.0851]], device='cuda:0', grad_fn=<DivBackward0>)
COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6194    0  1834  100  4360   4839  11503 --:--:-- --:--:-- --:--:-- 16343
(2, 4)

 50%|█████     | 36/72 [00:41<00:39,  1.09s/it]

torch.Size([25, 1])
substrate: COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1, ec: (2, 4), score: tensor([[6.3221e-03],
        [1.7676e-02],
        [9.2879e-05],
        [3.1084e-03],
        [2.7648e-03],
        [1.8331e-04],
        [4.7844e-05],
        [4.0419e-05],
        [5.7257e-05],
        [3.4460e-04],
        [4.3911e-04],
        [2.8960e-04],
        [2.8245e-01],
        [4.3139e-04],
        [6.3850e-05],
        [1.5703e-04],
        [2.3795e-05],
        [7.0739e-02],
        [2.1796e-03],
        [6.1107e-01],
        [8.0814e-01],
        [5.4931e-02],
        [2.3798e-04],
        [2.3211e-04],
        [1.9956e-04]], device='cuda:0', grad_fn=<DivBackward0>)
COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6194    0  1834  100  4360   4788  11383 --:--:-- --:--:-- --:--:-- 16214
(1, 14)

 51%|█████▏    | 37/72 [00:42<00:39,  1.13s/it]

torch.Size([25, 1])
substrate: COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1, ec: (1, 14), score: tensor([[4.5704e-01],
        [4.0099e-01],
        [1.3176e-01],
        [9.3104e-02],
        [1.6947e-02],
        [3.6135e-03],
        [8.9295e-03],
        [3.1103e-02],
        [4.7012e-02],
        [1.9703e-02],
        [6.4176e-03],
        [1.7422e-01],
        [3.9270e-01],
        [9.8899e-04],
        [9.6702e-04],
        [4.1686e-03],
        [9.3220e-03],
        [3.6705e-02],
        [1.1422e-02],
        [5.1213e-01],
        [9.5141e-01],
        [5.6925e-01],
        [4.2681e-04],
        [5.2268e-02],
        [1.4979e-01]], device='cuda:0', grad_fn=<DivBackward0>)
COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6161    0  2024  100  4137   4448   9092 --:--:-- --:--:-- --:--:-- 13540
(1, 14)

 53%|█████▎    | 38/72 [00:43<00:39,  1.17s/it]

torch.Size([27, 1])
substrate: COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1, ec: (1, 14), score: tensor([[0.4634],
        [0.3817],
        [0.0040],
        [0.0131],
        [0.0383],
        [0.0422],
        [0.9857],
        [0.8298],
        [0.7898],
        [0.1680],
        [0.0679],
        [0.0224],
        [0.0299],
        [0.0093],
        [0.0216],
        [0.0394],
        [0.0952],
        [0.0472],
        [0.0046],
        [0.0046],
        [0.1091],
        [0.2224],
        [0.7270],
        [0.5371],
        [0.2013],
        [0.0253],
        [0.0213]], device='cuda:0', grad_fn=<DivBackward0>)
COc1ccc2ccc(=O)oc2c1CC=C(C)C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4466    0  1351  100  3115   4372  10080 --:--:-- --:--:-- --:--:-- 14453
(1, 14)

 54%|█████▍    | 39/72 [00:44<00:36,  1.09s/it]

torch.Size([18, 1])
substrate: COc1ccc2ccc(=O)oc2c1CC=C(C)C, ec: (1, 14), score: tensor([[0.5632],
        [0.3626],
        [0.1839],
        [0.1823],
        [0.1150],
        [0.0045],
        [0.0570],
        [0.2986],
        [0.4191],
        [0.0150],
        [0.2338],
        [0.1948],
        [0.0998],
        [0.4607],
        [0.1228],
        [0.2155],
        [0.1988],
        [0.1071]], device='cuda:0', grad_fn=<DivBackward0>)
COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8815    0  2852  100  5963   2532   5295  0:00:01  0:00:01 --:--:--  7828
(1, 14)

 56%|█████▌    | 40/72 [00:46<00:41,  1.29s/it]

torch.Size([39, 1])
substrate: COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO, ec: (1, 14), score: tensor([[0.2595],
        [0.1822],
        [0.0090],
        [0.0187],
        [0.1398],
        [0.0645],
        [0.0889],
        [0.0835],
        [0.2598],
        [0.1422],
        [0.0160],
        [0.1655],
        [0.8280],
        [0.5650],
        [0.4103],
        [0.0078],
        [0.1867],
        [0.0827],
        [0.0480],
        [0.0391],
        [0.0374],
        [0.0850],
        [0.0157],
        [0.1159],
        [0.1869],
        [0.0072],
        [0.0045],
        [0.0018],
        [0.0367],
        [0.0371],
        [0.0333],
        [0.0597],
        [0.0300],
        [0.0223],
        [0.0431],
        [0.2481],
        [0.4364],
        [0.5429],
        [0.8491]], device='cuda:0', grad_fn=<DivBackward0>)
CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8757    0  2947  100  5810   5941  11713 --:--:-- --:--:-- --:--:-- 17655
(1, 14)

 57%|█████▋    | 41/72 [00:47<00:39,  1.27s/it]

torch.Size([40, 1])
substrate: CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1, ec: (1, 14), score: tensor([[0.0186],
        [0.8233],
        [0.7590],
        [0.6131],
        [0.0230],
        [0.0432],
        [0.1457],
        [0.0124],
        [0.0170],
        [0.0299],
        [0.0183],
        [0.0801],
        [0.0190],
        [0.0895],
        [0.0701],
        [0.0065],
        [0.0528],
        [0.0496],
        [0.0170],
        [0.0149],
        [0.2684],
        [0.0606],
        [0.0827],
        [0.0985],
        [0.1896],
        [0.7422],
        [0.7148],
        [0.2849],
        [0.2505],
        [0.0867],
        [0.2167],
        [0.0247],
        [0.0194],
        [0.0825],
        [0.1065],
        [0.0930],
        [0.0069],
        [0.0082],
        [0.0443],
        [0.0931]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6866    0  2231  100  4635   5047  10486 --:--:-- --:--:-- --:--:-- 15533
(1, 14)

 58%|█████▊    | 42/72 [00:48<00:37,  1.25s/it]

torch.Size([30, 1])
substrate: C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl, ec: (1, 14), score: tensor([[0.0937],
        [0.5524],
        [0.7633],
        [0.7573],
        [0.0557],
        [0.0056],
        [0.0053],
        [0.0457],
        [0.1701],
        [0.2067],
        [0.0260],
        [0.1495],
        [0.2352],
        [0.1672],
        [0.2380],
        [0.0944],
        [0.0877],
        [0.0240],
        [0.5054],
        [0.3524],
        [0.2423],
        [0.0176],
        [0.1779],
        [0.1802],
        [0.2044],
        [0.0631],
        [0.0110],
        [0.0515],
        [0.1051],
        [0.2995]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6916    0  2032  100  4884   4525  10877 --:--:-- --:--:-- --:--:-- 15368
(1, 14)

 60%|█████▉    | 43/72 [00:49<00:35,  1.23s/it]

torch.Size([27, 1])
substrate: C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4, ec: (1, 14), score: tensor([[0.0104],
        [0.0027],
        [0.0364],
        [0.0029],
        [0.0150],
        [0.0258],
        [0.0295],
        [0.3109],
        [0.4213],
        [0.2120],
        [0.0039],
        [0.0087],
        [0.0042],
        [0.0643],
        [0.0039],
        [0.0821],
        [0.0706],
        [0.0868],
        [0.0095],
        [0.1251],
        [0.1131],
        [0.0836],
        [0.0065],
        [0.0099],
        [0.0656],
        [0.0871],
        [0.0410]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4289    0  1187  100  3102   4107  10733 --:--:-- --:--:-- --:--:-- 14789
(1, 14)

 61%|██████    | 44/72 [00:50<00:32,  1.15s/it]

torch.Size([16, 1])
substrate: C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1, ec: (1, 14), score: tensor([[0.2186],
        [0.6795],
        [0.4183],
        [0.2716],
        [0.1904],
        [0.1449],
        [0.1229],
        [0.4803],
        [0.1515],
        [0.0183],
        [0.0952],
        [0.0911],
        [0.0208],
        [0.0330],
        [0.0619],
        [0.0384]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5279    0  1653  100  3626   5298  11621 --:--:-- --:--:-- --:--:-- 16865
(1, 14)

 62%|██████▎   | 45/72 [00:51<00:30,  1.12s/it]

torch.Size([22, 1])
substrate: C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12, ec: (1, 14), score: tensor([[0.0989],
        [0.1820],
        [0.4232],
        [0.7458],
        [0.2748],
        [0.0549],
        [0.1347],
        [0.1066],
        [0.9792],
        [0.6848],
        [0.7110],
        [0.0287],
        [0.0523],
        [0.0533],
        [0.0718],
        [0.0462],
        [0.2430],
        [0.3792],
        [0.2771],
        [0.0562],
        [0.0114],
        [0.0013]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6092    0  1955  100  4137   3613   7646 --:--:-- --:--:-- --:--:-- 11239
(1, 14)

 64%|██████▍   | 46/72 [00:53<00:29,  1.13s/it]

torch.Size([26, 1])
substrate: C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23, ec: (1, 14), score: tensor([[0.0077],
        [0.0818],
        [0.1063],
        [0.0784],
        [0.1322],
        [0.1601],
        [0.2591],
        [0.3967],
        [0.4094],
        [0.7467],
        [0.4791],
        [0.4763],
        [0.3712],
        [0.2256],
        [0.2655],
        [0.1564],
        [0.1275],
        [0.1092],
        [0.0657],
        [0.1779],
        [0.2149],
        [0.0547],
        [0.0628],
        [0.3178],
        [0.4805],
        [0.3086]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7854    0  2389  100  5465   5429  12420 --:--:-- --:--:-- --:--:-- 17809
(1, 14)

 65%|██████▌   | 47/72 [00:54<00:28,  1.12s/it]

torch.Size([32, 1])
substrate: C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O, ec: (1, 14), score: tensor([[2.2598e-02],
        [9.8182e-03],
        [3.0576e-02],
        [9.0725e-03],
        [2.6476e-02],
        [1.0977e-01],
        [4.6587e-02],
        [1.3232e-03],
        [1.3900e-02],
        [1.1788e-01],
        [3.6570e-02],
        [9.8381e-03],
        [1.0895e-02],
        [3.6382e-02],
        [3.7474e-02],
        [2.9337e-02],
        [1.9515e-02],
        [8.9264e-01],
        [8.8241e-01],
        [4.9234e-02],
        [5.7556e-03],
        [8.4747e-03],
        [4.9331e-01],
        [4.6003e-01],
        [1.6444e-01],
        [3.2466e-02],
        [1.8522e-02],
        [2.0002e-01],
        [8.2882e-02],
        [5.6650e-04],
        [2.2235e-03],
        [7.4742e-03]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6233    0  1764  100  4469   4027  10203 --:--:-- --:--:-- --:--:-- 14230
(1, 14)

 67%|██████▋   | 48/72 [00:55<00:27,  1.13s/it]

torch.Size([23, 1])
substrate: C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O, ec: (1, 14), score: tensor([[0.0838],
        [0.1200],
        [0.1734],
        [0.3796],
        [0.5101],
        [0.1372],
        [0.1168],
        [0.1186],
        [0.0136],
        [0.1127],
        [0.0659],
        [0.0151],
        [0.0276],
        [0.1264],
        [0.0598],
        [0.0486],
        [0.0403],
        [0.0204],
        [0.0608],
        [0.2515],
        [0.7487],
        [0.0586],
        [0.7366]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7569    0  2257  100  5312   4532  10666 --:--:-- --:--:-- --:--:-- 15198
(1, 14)

 68%|██████▊   | 49/72 [00:56<00:25,  1.12s/it]

torch.Size([30, 1])
substrate: Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1, ec: (1, 14), score: tensor([[0.1566],
        [0.1086],
        [0.2190],
        [0.4110],
        [0.4600],
        [0.2681],
        [0.1741],
        [0.0566],
        [0.2989],
        [0.2471],
        [0.2043],
        [0.2699],
        [0.5060],
        [0.2589],
        [0.2781],
        [0.1063],
        [0.1619],
        [0.1962],
        [0.1097],
        [0.1628],
        [0.1313],
        [0.1539],
        [0.6890],
        [0.1083],
        [0.0623],
        [0.0966],
        [0.0224],
        [0.0706],
        [0.0557],
        [0.3998]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5484    0  1679  100  3805   3842   8707 --:--:-- --:--:-- --:--:-- 12549
(2, 4)

 69%|██████▉   | 50/72 [00:57<00:24,  1.11s/it]

torch.Size([22, 1])
substrate: Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1, ec: (2, 4), score: tensor([[1.4193e-01],
        [2.9833e-02],
        [4.1530e-03],
        [5.0814e-02],
        [5.2661e-02],
        [7.3236e-01],
        [2.9649e-01],
        [5.5878e-03],
        [5.3883e-03],
        [6.0972e-03],
        [1.3382e-03],
        [5.4554e-04],
        [1.6942e-04],
        [1.9388e-01],
        [5.8469e-02],
        [1.8676e-01],
        [1.2495e-02],
        [2.2094e-04],
        [6.3374e-02],
        [8.0876e-02],
        [1.1566e-03],
        [2.8329e-03]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5484    0  1679  100  3805   3815   8647 --:--:-- --:--:-- --:--:-- 12463
(1, 14)

 71%|███████   | 51/72 [00:58<00:23,  1.11s/it]

torch.Size([22, 1])
substrate: Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1, ec: (1, 14), score: tensor([[0.4870],
        [0.3179],
        [0.1298],
        [0.0775],
        [0.0402],
        [0.6593],
        [0.1946],
        [0.0119],
        [0.0958],
        [0.2127],
        [0.2798],
        [0.0567],
        [0.0031],
        [0.0943],
        [0.0560],
        [0.1681],
        [0.1858],
        [0.2375],
        [0.5265],
        [0.5307],
        [0.1629],
        [0.1881]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7292    0  2395  100  4897   4877   9973 --:--:-- --:--:-- --:--:-- 14821
(1, 14)

 72%|███████▏  | 52/72 [00:59<00:22,  1.13s/it]

torch.Size([32, 1])
substrate: Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1, ec: (1, 14), score: tensor([[0.2649],
        [0.0294],
        [0.0450],
        [0.1807],
        [0.2032],
        [0.7293],
        [0.3518],
        [0.2639],
        [0.1496],
        [0.3963],
        [0.0217],
        [0.3500],
        [0.1442],
        [0.2391],
        [0.3935],
        [0.2669],
        [0.3469],
        [0.1843],
        [0.2982],
        [0.0545],
        [0.0787],
        [0.1341],
        [0.2207],
        [0.2375],
        [0.2365],
        [0.1474],
        [0.2988],
        [0.3748],
        [0.2961],
        [0.3182],
        [0.1659],
        [0.0138]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6274    0  2067  100  4207   5016  10211 --:--:-- --:--:-- --:--:-- 15191
(1, 14)

 74%|███████▎  | 53/72 [01:00<00:21,  1.15s/it]

torch.Size([28, 1])
substrate: Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1, ec: (1, 14), score: tensor([[0.1233],
        [0.0069],
        [0.0504],
        [0.0709],
        [0.1777],
        [0.9934],
        [0.6615],
        [0.5872],
        [0.5888],
        [0.0150],
        [0.0448],
        [0.0483],
        [0.0196],
        [0.0942],
        [0.0652],
        [0.0667],
        [0.1291],
        [0.0312],
        [0.1959],
        [0.7961],
        [0.7106],
        [0.5297],
        [0.8035],
        [0.1350],
        [0.0520],
        [0.0836],
        [0.0934],
        [0.0198]], device='cuda:0', grad_fn=<DivBackward0>)
Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11456    0  3335  100  8121   4847  11803 --:--:-- --:--:-- --:--:-- 16651
(1, 14)

 75%|███████▌  | 54/72 [01:02<00:21,  1.22s/it]

torch.Size([46, 1])
substrate: Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O, ec: (1, 14), score: tensor([[0.0684],
        [0.0110],
        [0.0438],
        [0.0242],
        [0.0228],
        [0.0134],
        [0.0457],
        [0.0659],
        [0.5829],
        [0.5406],
        [0.1815],
        [0.0851],
        [0.1816],
        [0.0879],
        [0.0280],
        [0.0260],
        [0.0300],
        [0.0161],
        [0.0108],
        [0.0407],
        [0.0412],
        [0.6294],
        [0.6708],
        [0.0954],
        [0.0232],
        [0.0235],
        [0.0039],
        [0.0317],
        [0.0561],
        [0.0104],
        [0.0463],
        [0.0258],
        [0.1997],
        [0.1942],
        [0.1203],
        [0.0987],
        [0.0047],
        [0.0175],
        [0.0204],
        [0.3458],
        [0.1700],
        [0.0670],
        [0.1941],
        [0.3334],
        [0.2522],
        [0.1550]], device='cuda:0', grad_fn=<DivBackward0>)
Clc1ccc(CCCOCCCN2CCCCC2)cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5600    0  1489  100  4111   3867  10677 --:--:-- --:--:-- --:--:-- 14545
(1, 14)

 76%|███████▋  | 55/72 [01:03<00:19,  1.15s/it]

torch.Size([20, 1])
substrate: Clc1ccc(CCCOCCCN2CCCCC2)cc1, ec: (1, 14), score: tensor([[0.0440],
        [0.0210],
        [0.1511],
        [0.1638],
        [0.0352],
        [0.2156],
        [0.0819],
        [0.7836],
        [0.6975],
        [0.8126],
        [0.1443],
        [0.2082],
        [0.4650],
        [0.4298],
        [0.0678],
        [0.0270],
        [0.0619],
        [0.3489],
        [0.1664],
        [0.1371]], device='cuda:0', grad_fn=<DivBackward0>)
Clc1ccccc1CN1CCc2sccc2C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4187    0  1308  100  2879   1352   2977 --:--:-- --:--:-- --:--:--  4329
(1, 11)

 78%|███████▊  | 56/72 [01:04<00:20,  1.29s/it]

torch.Size([17, 1])
substrate: Clc1ccccc1CN1CCc2sccc2C1, ec: (1, 11), score: tensor([[0.2693],
        [0.0944],
        [0.0162],
        [0.2035],
        [0.1215],
        [0.0278],
        [0.1187],
        [0.1578],
        [0.3418],
        [0.0598],
        [0.0686],
        [0.0219],
        [0.6712],
        [0.3376],
        [0.3186],
        [0.0091],
        [0.2322]], device='cuda:0', grad_fn=<DivBackward0>)
Clc1ccccc1CN1CCc2sccc2C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4187    0  1308  100  2879   4233   9317 --:--:-- --:--:-- --:--:-- 13506
(1, 14)

 79%|███████▉  | 57/72 [01:05<00:17,  1.19s/it]

torch.Size([17, 1])
substrate: Clc1ccccc1CN1CCc2sccc2C1, ec: (1, 14), score: tensor([[0.4896],
        [0.3654],
        [0.1679],
        [0.2938],
        [0.2952],
        [0.2204],
        [0.0927],
        [0.1149],
        [0.1827],
        [0.0572],
        [0.0366],
        [0.0198],
        [0.8457],
        [0.6513],
        [0.2836],
        [0.0201],
        [0.2376]], device='cuda:0', grad_fn=<DivBackward0>)
Cn1c(=O)c2c(ncn2C)n(C)c1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3360    0  1075  100  2285   3307   7030 --:--:-- --:--:-- --:--:-- 10306
(1, 14)

 81%|████████  | 58/72 [01:06<00:15,  1.12s/it]

torch.Size([14, 1])
substrate: Cn1c(=O)c2c(ncn2C)n(C)c1=O, ec: (1, 14), score: tensor([[0.9205],
        [0.9343],
        [0.0384],
        [0.0204],
        [0.0135],
        [0.0173],
        [0.1927],
        [0.1055],
        [0.1198],
        [0.1926],
        [0.9336],
        [0.9244],
        [0.1279],
        [0.0364]], device='cuda:0', grad_fn=<DivBackward0>)
Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5829    0  2024  100  3805   4652   8747 --:--:-- --:--:-- --:--:-- 13369
(1, 14)

 82%|████████▏ | 59/72 [01:07<00:14,  1.08s/it]

torch.Size([27, 1])
substrate: Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1, ec: (1, 14), score: tensor([[0.4596],
        [0.4030],
        [0.1209],
        [0.0099],
        [0.0254],
        [0.0340],
        [0.0419],
        [0.0743],
        [0.0415],
        [0.0065],
        [0.0153],
        [0.0532],
        [0.0469],
        [0.1344],
        [0.0937],
        [0.1959],
        [0.8619],
        [0.8112],
        [0.1007],
        [0.2474],
        [0.0705],
        [0.0220],
        [0.0253],
        [0.0121],
        [0.0999],
        [0.2082],
        [0.2868]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)c1cn(Cc2c(F)cccc2F)nn1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3650    0     0  100  2368      0  11551 --:--:-- --:--:-- --:--:-- 11495  1282  100  2368   1511   2792 --:--:-- --:--:-- --:--:--  4299
(1, 14)

 83%|████████▎ | 60/72 [01:09<00:14,  1.18s/it]

torch.Size([17, 1])
substrate: NC(=O)c1cn(Cc2c(F)cccc2F)nn1, ec: (1, 14), score: tensor([[0.0874],
        [0.3021],
        [0.1145],
        [0.0875],
        [0.1328],
        [0.8475],
        [0.4595],
        [0.0213],
        [0.1432],
        [0.1060],
        [0.2317],
        [0.2352],
        [0.1801],
        [0.0760],
        [0.0553],
        [0.4196],
        [0.0591]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)c1nc(F)cnc1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2367    0   842  100  1525   2844   5152 --:--:-- --:--:-- --:--:--  7996
(1, 17)

 85%|████████▍ | 61/72 [01:10<00:12,  1.11s/it]

torch.Size([11, 1])
substrate: NC(=O)c1nc(F)cnc1O, ec: (1, 17), score: tensor([[0.0515],
        [0.0637],
        [0.0212],
        [0.0205],
        [0.0940],
        [0.3770],
        [0.2734],
        [0.3976],
        [0.3930],
        [0.6648],
        [0.3929]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)c1nc(F)cnc1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2367    0   842  100  1525   2063   3737 --:--:-- --:--:-- --:--:--  5801
(1, 12)

 86%|████████▌ | 62/72 [01:11<00:10,  1.05s/it]

torch.Size([11, 1])
substrate: NC(=O)c1nc(F)cnc1O, ec: (1, 12), score: tensor([[0.0488],
        [0.0850],
        [0.0017],
        [0.0642],
        [0.0609],
        [0.4007],
        [0.3611],
        [0.0562],
        [0.6547],
        [0.4921],
        [0.3448]], device='cuda:0', grad_fn=<DivBackward0>)
NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4648    0  1463  100  3185   5044  10982 --:--:-- --:--:-- --:--:-- 16027
(1, 14)

 88%|████████▊ | 63/72 [01:12<00:09,  1.03s/it]

torch.Size([20, 1])
substrate: NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1, ec: (1, 14), score: tensor([[0.6763],
        [0.7039],
        [0.7365],
        [0.7094],
        [0.0469],
        [0.0013],
        [0.0047],
        [0.0176],
        [0.1321],
        [0.0232],
        [0.0068],
        [0.0828],
        [0.2006],
        [0.4693],
        [0.9508],
        [0.1580],
        [0.3062],
        [0.5611],
        [0.0356],
        [0.0853]], device='cuda:0', grad_fn=<DivBackward0>)
N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3491    0  1118  100  2373   3751   7963 --:--:-- --:--:-- --:--:-- 11714
(4, 1)

 89%|████████▉ | 64/72 [01:13<00:08,  1.03s/it]

torch.Size([15, 1])
substrate: N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O, ec: (4, 1), score: tensor([[0.3096],
        [0.9769],
        [0.5491],
        [0.0907],
        [0.0322],
        [0.2155],
        [0.0469],
        [0.2187],
        [0.0505],
        [0.0591],
        [0.1581],
        [0.1455],
        [0.8974],
        [0.0098],
        [0.0590]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5403    0  1860  100  3543   1823   3473  0:00:01  0:00:01 --:--:--  5297
(1, 14)

 90%|█████████ | 65/72 [01:14<00:08,  1.22s/it]

torch.Size([25, 1])
substrate: O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F, ec: (1, 14), score: tensor([[0.0585],
        [0.1150],
        [0.6061],
        [0.6595],
        [0.2757],
        [0.3007],
        [0.2378],
        [0.0026],
        [0.0106],
        [0.0164],
        [0.0072],
        [0.0672],
        [0.1409],
        [0.1077],
        [0.0591],
        [0.0375],
        [0.3327],
        [0.0449],
        [0.0823],
        [0.0466],
        [0.1574],
        [0.3157],
        [0.0050],
        [0.0980],
        [0.1509]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4425    0  1463  100  2962   1124   2276  0:00:01  0:00:01 --:--:--  3398
(1, 14)

 92%|█████████▏| 66/72 [01:16<00:08,  1.46s/it]

torch.Size([20, 1])
substrate: O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl, ec: (1, 14), score: tensor([[0.0655],
        [0.0883],
        [0.0115],
        [0.0441],
        [0.1530],
        [0.2647],
        [0.3145],
        [0.2490],
        [0.0073],
        [0.0137],
        [0.1566],
        [0.2286],
        [0.7425],
        [0.5400],
        [0.3816],
        [0.1813],
        [0.0368],
        [0.0149],
        [0.0206],
        [0.0414]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5821    0  1946  100  3875   5121  10197 --:--:-- --:--:-- --:--:-- 15278
(1, 14)

 93%|█████████▎| 67/72 [01:18<00:07,  1.40s/it]

torch.Size([27, 1])
substrate: O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1, ec: (1, 14), score: tensor([[0.0025],
        [0.0172],
        [0.0111],
        [0.0101],
        [0.0057],
        [0.1632],
        [0.0013],
        [0.3918],
        [0.2258],
        [0.0606],
        [0.0426],
        [0.0855],
        [0.0179],
        [0.0313],
        [0.0237],
        [0.0141],
        [0.3423],
        [0.4358],
        [0.0042],
        [0.0588],
        [0.0550],
        [0.1538],
        [0.8033],
        [0.5265],
        [0.4527],
        [0.0592],
        [0.0318]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13214    0  4543  100  8671   4049   7728  0:00:01  0:00:01 --:--:-- 11777
(1, 14)

 94%|█████████▍| 68/72 [01:20<00:06,  1.56s/it]

torch.Size([62, 1])
substrate: O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O, ec: (1, 14), score: tensor([[1.5096e-02],
        [2.3484e-01],
        [5.3985e-02],
        [1.8999e-01],
        [1.0242e-01],
        [6.1795e-01],
        [5.7274e-01],
        [6.8643e-02],
        [8.8562e-03],
        [7.3734e-02],
        [6.8781e-02],
        [7.9508e-02],
        [3.0190e-02],
        [3.3249e-02],
        [7.7600e-02],
        [1.9985e-01],
        [1.1505e-02],
        [7.2970e-02],
        [1.2538e-01],
        [5.3371e-01],
        [4.8024e-01],
        [2.7897e-02],
        [2.3578e-02],
        [5.0226e-03],
        [1.7956e-02],
        [3.6404e-02],
        [1.1577e-01],
        [3.1373e-02],
        [6.2782e-04],
        [3.7238e-04],
        [3.0521e-02],
        [1.7208e-01],
        [9.5511e-03],
        [1.3288e-02],
        [2.2995e-02],
        [3.8002e-02],
        [1.3486e-02],
        [7.2768e-02],
        [2.3512e-02],
        [8.5584e-02],
        [2.5759e-02],
        [8.6465e-03],
        [1.7326e-02],
        [3.2302e-02],
        [8.2187e-02],
        [5.6897e-02],
        [1.4420e-01],
        [3.1918e-01],
        [8.6454e-02],
        [7.2669e-04],
        [2.0315e-04],
        [8.7502e-02],
        [2.4265e-01],
        [2.5115e-03],
        [2.4844e-02],
        [1.0323e-02],
        [5.0833e-02],
        [3.0564e-02],
        [5.2829e-02],
        [2.0421e-02],
        [7.5375e-02],
        [9.1554e-03]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4242    0  1446  100  2796   4504   8710 --:--:-- --:--:-- --:--:-- 13214
(1, 14)

 96%|█████████▌| 69/72 [01:21<00:04,  1.40s/it]

torch.Size([19, 1])
substrate: O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1, ec: (1, 14), score: tensor([[0.6006],
        [0.9662],
        [0.5223],
        [0.8153],
        [0.2726],
        [0.0239],
        [0.0653],
        [0.0444],
        [0.0624],
        [0.0836],
        [0.0511],
        [0.0516],
        [0.0561],
        [0.0312],
        [0.0223],
        [0.2478],
        [0.0556],
        [0.0404],
        [0.5555]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4394    0  1515  100  2879   4661   8858 --:--:-- --:--:-- --:--:-- 13478
(2, 4)

 97%|█████████▋| 70/72 [01:21<00:02,  1.23s/it]

torch.Size([20, 1])
substrate: O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O, ec: (2, 4), score: tensor([[9.9079e-02],
        [1.8771e-01],
        [2.4033e-01],
        [1.5612e-03],
        [1.1937e-04],
        [4.5815e-04],
        [2.7366e-03],
        [1.0821e-02],
        [2.6935e-04],
        [5.4540e-04],
        [3.2846e-02],
        [7.4971e-05],
        [4.0471e-04],
        [1.4493e-04],
        [7.5622e-04],
        [2.1055e-04],
        [7.2798e-05],
        [4.2656e-01],
        [3.9386e-01],
        [7.4765e-01]], device='cuda:0', grad_fn=<DivBackward0>)
O=P1(NCCCl)OCCCN1CCCl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3736    0  1049  100  2687   3629   9297 --:--:-- --:--:-- --:--:-- 12882
(1, 14)

 99%|█████████▊| 71/72 [01:22<00:01,  1.12s/it]

torch.Size([14, 1])
substrate: O=P1(NCCCl)OCCCN1CCCl, ec: (1, 14), score: tensor([[0.1688],
        [0.0838],
        [0.9356],
        [0.8639],
        [0.0118],
        [0.0059],
        [0.0057],
        [0.0171],
        [0.0044],
        [0.4192],
        [0.8490],
        [0.7811],
        [0.1128],
        [0.0271]], device='cuda:0', grad_fn=<DivBackward0>)
OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6634    0  1929  100  4705   2028   4947 --:--:-- --:--:-- --:--:--  6968
(1, 14)

100%|██████████| 72/72 [01:24<00:00,  1.17s/it]

torch.Size([26, 1])
substrate: OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1, ec: (1, 14), score: tensor([[0.8060],
        [0.4816],
        [0.1687],
        [0.2425],
        [0.2999],
        [0.0622],
        [0.2464],
        [0.1973],
        [0.3632],
        [0.2738],
        [0.3328],
        [0.0274],
        [0.1121],
        [0.0789],
        [0.2265],
        [0.0971],
        [0.1053],
        [0.0570],
        [0.1969],
        [0.1583],
        [0.1666],
        [0.2654],
        [0.1717],
        [0.2384],
        [0.3145],
        [0.2815]], device='cuda:0', grad_fn=<DivBackward0>)

In [8]:
import torch
atom_scores_list_new = []
# 假设 scores 是你的 torch 张量，大小是 [14, 1]
for i in atom_scores_list:
    scores = i  # 示例：14个原子的反应分数，实际使用时替换为你的数据

    # 创建一个空字典来存储原子序号和对应的分数
    atom_scores = {}

    # 将分数映射到原子序号
    for idx, score in enumerate(scores):
        atom_scores[idx] = score.item()  # 使用 item() 将张量转换为标量

# 打印结果
    atom_scores_list_new.append(atom_scores)

In [11]:
df_new['score'] = atom_scores_list_new

,substrate,ec,score
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"(1, 14)","{0: 0.17234759032726288, 1: 0.2866118252277374..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(2, 4)","{0: 0.03460502251982689, 1: 0.1962412446737289..."
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(1, 14)","{0: 0.26034024357795715, 1: 0.9417978525161743..."
3,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"(1, 14)","{0: 0.07399298995733261, 1: 0.0268323067575693..."
4,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"(1, 14)","{0: 0.06365552544593811, 1: 0.2708439826965332..."
...,...,...,...
67,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"(1, 14)","{0: 0.015096035785973072, 1: 0.234839916229248..."
68,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"(1, 14)","{0: 0.6005780696868896, 1: 0.9662299156188965,..."
69,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"(2, 4)","{0: 0.09907922148704529, 1: 0.1877077072858810..."
70,O=P1(NCCCl)OCCCN1CCCl,"(1, 14)","{0: 0.16878382861614227, 1: 0.0837636962532997..."
71,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,"(1, 14)","{0: 0.8059802055358887, 1: 0.4815613329410553,..."

In [15]:
df_new.to_pickle('gnnsom_results.pickle')