In [1]:
import pandas as pd
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/main_cases/pred_results_score_new.csv')
substrates = df['substrate'].to_list()
ecs = [(1,14) for _ in range(len(substrates))]
# dict_sub2ec = dict(zip(substrates,ecs))
# ecs = [i.strip() for i in ecs]

# # 凡是没有EC的我们用1.14代替
# ecs = [i.replace('None','1.14') for i in ecs]
# ecs = [i.split(' ') for i in ecs]
# ecs_new = []
# for eclist in ecs:
#     eclist = [tuple([int(j) for j in i.split('.')[:2]]) for i in eclist]
#     eclist = list(set(eclist))
#     ecs_new.append(eclist)

# subs_new = []
# for i in range(len(substrates)):
#     ecs = ecs_new[i]
#     num_repeat = len(ecs)
#     subs = [substrates[i] for _ in range(num_repeat)]
#     subs_new = subs_new + subs

# ecs_new = [i for k in ecs_new for i in k]

df_new = pd.DataFrame(columns=['substrate','ec','score'])
df_new['substrate'] = substrates
df_new['ec'] = ecs
df_new['score'] = ['None' for _ in range(len(substrates))]
df_new

                                             substrate       ec score
0      CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O  (1, 14)  None
1      CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2  (1, 14)  None
2    CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=C...  (1, 14)  None
3    CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=...  (1, 14)  None
4    CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=C...  (1, 14)  None
..                                                 ...      ...   ...
118  OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=C...  (1, 14)  None
119  OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC...  (1, 14)  None
120     OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2  (1, 14)  None
121  OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=...  (1, 14)  None
122                              C1=CN=C(N2CCNCC2)N=C1  (1, 14)  None

[123 rows x 3 columns]

In [2]:
from tqdm import tqdm

import json
from os.path import isfile

import torch
from torch_geometric.data import Data
from rdkit.Chem import Draw
import requests

from IPython.display import SVG

from gnn_som import createGnnSom, loadGnnSomState
from gnn_som.MolFromKcf import MolFromKcfFile

import os

from rdkit import Chem
from rdkit.Chem import AllChem

os.environ['CUDA_VISIBLE_DEVICES'] = "2"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

with open('data/config.json', 'r') as f:
    config = json.load(f)
config['features']['enzyme'] = [tuple(ec) for ec in config['features']['enzyme']] 

models = []
for i, params in enumerate(config['models']):
    model = createGnnSom(*config['models'][i])
    loadGnnSomState(model, torch.load('data/model%d.pt' % i, map_location=torch.device('cpu')))
    models.append(model)

# Convert SMILES to .mol file using RDKit 

atom_scores_list = []

for i in tqdm(range(len(df_new))):
    smi = df_new.iloc[i,0]
    enzyme = df_new.iloc[i,1]


    # Create RDKit mol object
    # molecule = 'CC1([C@@H]2[C@H]1[C@H](N(C2)C(=O)[C@H](C(C)(C)C)NC(=O)C(F)(F)F)C(=O)N[C@@H](C[C@@H]3CCNC3=O)C#N)C'
    print(smi)
    molecule = Chem.MolFromSmiles(smi)
    molecule = Chem.AddHs(molecule)

    if os.path.exists("molecule.mol"):
        os.remove("molecule.mol")

    # Compute 2D coordenates and write to .mol file
    AllChem.Compute2DCoords(molecule)
    print(Chem.MolToMolBlock(molecule), file=open("molecule.mol", 'a+'))

    if os.path.exists("molecule.kcf"):
        os.remove("molecule.kcf")

    # Convert .mol to .kcf (KEGG format used in the paper) 
    # https://iwatobipen.wordpress.com/2016/12/23/convert-chemical-file-format/
    # https://www.genome.jp/tools/gn_ca_tools_api.html
    !curl -F molfile=@molecule.mol http://rest.genome.jp/mol2kcf/ > molecule.kcf

    # Define mol
    mol = MolFromKcfFile('molecule.kcf')

        # enzyme = (2,4)

    print(enzyme)
    numFeatures = sum(len(feature) for feature in config['features'].values())
    x = torch.zeros((mol.GetNumAtoms(), numFeatures), dtype=torch.float32)
    for atom in mol.GetAtoms():
        x[atom.GetIdx(), config['features']['enzyme'].index(enzyme)] = 1
        offset = len(config['features']['enzyme'])
        x[atom.GetIdx(), offset + config['features']['element'].index(atom.GetSymbol())] = 1
        offset += len(config['features']['element'])
        x[atom.GetIdx(), offset + config['features']['kcfType'].index(atom.GetProp('kcfType'))] = 1

    edgeIndex = torch.zeros((2, mol.GetNumBonds() * 2), dtype=torch.int64)
    for bond in mol.GetBonds():
        i = bond.GetIdx()
        edgeIndex[0][i * 2] = bond.GetBeginAtomIdx()
        edgeIndex[1][i * 2] = bond.GetEndAtomIdx()
        edgeIndex[0][i * 2 + 1] = bond.GetEndAtomIdx()
        edgeIndex[1][i * 2 + 1] = bond.GetBeginAtomIdx()

    data = Data(x=x, edgeIndex=edgeIndex)

    # 确保模型和数据都在同一设备上运行
    data = data.to(device)  # 将数据移动到 GPU 或保持在 CPU
    y = None

    for model in models:
        model = model.to(device)  # 将每个模型移动到 GPU（如果尚未移动）
        newY = torch.sigmoid(model(data.x, data.edgeIndex))  # 数据已在 GPU 或 CPU 上
        y = newY if y is None else torch.add(y, newY)

    # 计算模型平均输出
    y = torch.div(y, len(models))
    print(y.shape)

    # import torch

    # # 假设 scores 是你的 torch 张量，大小是 [14, 1]
    # scores = y  # 示例：14个原子的反应分数，实际使用时替换为你的数据

    # # 创建一个空字典来存储原子序号和对应的分数
    # atom_scores = {}

    # # 将分数映射到原子序号
    # for idx, score in enumerate(scores):
    #     atom_scores[idx] = score.item()  # 使用 item() 将张量转换为标量

    # 打印结果
    # print(atom_scores)

    atom_scores_list.append(y)

    print(f'substrate: {smi}, ec: {enzyme}, score: {y}')

/tmp/ipykernel_47104/173021330.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loadGnnSomState(model, torch.load('data/model%d.pt' % i, map_location=torch.device('cpu')))
  0%|          | 0/123 [00:00<?, ?it/s]

CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6222    0  1696  100  4526   3111   8304 --:--:-- --:--:-- --:--:-- 11395
(1, 14)

  1%|          | 1/123 [00:03<07:44,  3.80s/it]

torch.Size([23, 1])
substrate: CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O, ec: (1, 14), score: tensor([[0.0040],
        [0.0117],
        [0.0108],
        [0.0428],
        [0.0981],
        [0.0337],
        [0.2098],
        [0.1850],
        [0.1239],
        [0.1591],
        [0.0860],
        [0.1223],
        [0.1843],
        [0.1439],
        [0.0095],
        [0.0662],
        [0.0832],
        [0.0482],
        [0.0315],
        [0.1749],
        [0.1739],
        [0.0262],
        [0.1480]], device='cuda:0', grad_fn=<DivBackward0>)
CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5099    0  1722  100  3377   5079   9961 --:--:-- --:--:-- --:--:-- 15041
(1, 14)

  2%|▏         | 2/123 [00:04<04:22,  2.17s/it]

torch.Size([23, 1])
substrate: CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2, ec: (1, 14), score: tensor([[0.1134],
        [0.4291],
        [0.0957],
        [0.3131],
        [0.1107],
        [0.1619],
        [0.0905],
        [0.0548],
        [0.0923],
        [0.1184],
        [0.1848],
        [0.0344],
        [0.0711],
        [0.0942],
        [0.1818],
        [0.1082],
        [0.0961],
        [0.1744],
        [0.5397],
        [0.2675],
        [0.6467],
        [0.3292],
        [0.3770]], device='cuda:0', grad_fn=<DivBackward0>)
CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=CC=C(I)C=C4F)N(C)C(=O)C(C)=C23)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8052    0  2740  100  5312   2057   3987  0:00:01  0:00:01 --:--:--  6045
(1, 14)

  2%|▏         | 3/123 [00:07<04:55,  2.46s/it]

torch.Size([37, 1])
substrate: CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=CC=C(I)C=C4F)N(C)C(=O)C(C)=C23)=C1, ec: (1, 14), score: tensor([[0.1750],
        [0.4837],
        [0.1352],
        [0.5943],
        [0.1202],
        [0.1394],
        [0.1397],
        [0.1796],
        [0.1062],
        [0.2308],
        [0.0890],
        [0.0106],
        [0.1029],
        [0.0134],
        [0.0442],
        [0.0234],
        [0.0338],
        [0.0234],
        [0.0267],
        [0.0768],
        [0.3778],
        [0.0937],
        [0.1751],
        [0.0973],
        [0.1514],
        [0.4431],
        [0.0207],
        [0.2231],
        [0.1730],
        [0.7618],
        [0.6431],
        [0.1725],
        [0.1171],
        [0.0745],
        [0.1570],
        [0.0527],
        [0.1570]], device='cuda:0', grad_fn=<DivBackward0>)
CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=C3C2=O)C=C1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7173    0  2136  100  5037   4979  11741 --:--:-- --:--:-- --:--:-- 16720
(1, 14)

  3%|▎         | 4/123 [00:08<03:43,  1.88s/it]

torch.Size([29, 1])
substrate: CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=C3C2=O)C=C1O, ec: (1, 14), score: tensor([[0.1956],
        [0.0837],
        [0.0723],
        [0.1023],
        [0.2209],
        [0.0789],
        [0.0646],
        [0.0398],
        [0.0985],
        [0.0887],
        [0.0488],
        [0.0269],
        [0.7059],
        [0.7206],
        [0.4175],
        [0.1971],
        [0.0529],
        [0.0318],
        [0.0101],
        [0.0588],
        [0.0658],
        [0.0673],
        [0.1414],
        [0.0303],
        [0.0167],
        [0.0165],
        [0.1505],
        [0.4156],
        [0.3934]], device='cuda:0', grad_fn=<DivBackward0>)
CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=CC(OCCN5CCOCC5)=CC=C43)C=C2)=NO1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9294    0  2973  100  6321   4587   9754 --:--:-- --:--:-- --:--:-- 14342
(1, 14)

  4%|▍         | 5/123 [00:12<05:01,  2.55s/it]

torch.Size([40, 1])
substrate: CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=CC(OCCN5CCOCC5)=CC=C43)C=C2)=NO1, ec: (1, 14), score: tensor([[0.2384],
        [0.2645],
        [0.2388],
        [0.2699],
        [0.0461],
        [0.0223],
        [0.0027],
        [0.1181],
        [0.2801],
        [0.0481],
        [0.1590],
        [0.0079],
        [0.0115],
        [0.0101],
        [0.0030],
        [0.0121],
        [0.2171],
        [0.4342],
        [0.0154],
        [0.0515],
        [0.1054],
        [0.1020],
        [0.0133],
        [0.0598],
        [0.1524],
        [0.0570],
        [0.0204],
        [0.2424],
        [0.5033],
        [0.5223],
        [0.2599],
        [0.5492],
        [0.4854],
        [0.1184],
        [0.1228],
        [0.0546],
        [0.0088],
        [0.0129],
        [0.1768],
        [0.0711]], device='cuda:0', grad_fn=<DivBackward0>)
CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=C(O)C=N3)CC2)C(=O)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6952    0  1998  100  4954   1366   3388  0:00:01  0:00:01 --:--:--  4751
(1, 14)

  5%|▍         | 6/123 [00:14<04:41,  2.40s/it]

torch.Size([27, 1])
substrate: CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=C(O)C=N3)CC2)C(=O)C1, ec: (1, 14), score: tensor([[0.2256],
        [0.2049],
        [0.3398],
        [0.1640],
        [0.3249],
        [0.2027],
        [0.2722],
        [0.0176],
        [0.0648],
        [0.0541],
        [0.0325],
        [0.2865],
        [0.2953],
        [0.1937],
        [0.1677],
        [0.0504],
        [0.0513],
        [0.2113],
        [0.9004],
        [0.9804],
        [0.2331],
        [0.0423],
        [0.1393],
        [0.3173],
        [0.3359],
        [0.2351],
        [0.1349]], device='cuda:0', grad_fn=<DivBackward0>)
CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6800    0  1929  100  4871   1662   4199  0:00:01  0:00:01 --:--:--  5857
(1, 14)

  6%|▌         | 7/123 [00:17<04:57,  2.56s/it]

torch.Size([26, 1])
substrate: CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1, ec: (1, 14), score: tensor([[0.2015],
        [0.0583],
        [0.2063],
        [0.1241],
        [0.1674],
        [0.2215],
        [0.1770],
        [0.0259],
        [0.0461],
        [0.2077],
        [0.3802],
        [0.4788],
        [0.5296],
        [0.2048],
        [0.0926],
        [0.0355],
        [0.4001],
        [0.3581],
        [0.2724],
        [0.2581],
        [0.2470],
        [0.2537],
        [0.5848],
        [0.3212],
        [0.1996],
        [0.1978]], device='cuda:0', grad_fn=<DivBackward0>)
CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6952    0  1998  100  4954   4668  11574 --:--:-- --:--:-- --:--:-- 16205
(1, 14)

  7%|▋         | 8/123 [00:18<04:02,  2.11s/it]

torch.Size([27, 1])
substrate: CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1O, ec: (1, 14), score: tensor([[0.0488],
        [0.0159],
        [0.1090],
        [0.0395],
        [0.1642],
        [0.1459],
        [0.0929],
        [0.0087],
        [0.0455],
        [0.0285],
        [0.1967],
        [0.2958],
        [0.4137],
        [0.1713],
        [0.2235],
        [0.0196],
        [0.3891],
        [0.4383],
        [0.4704],
        [0.4506],
        [0.3617],
        [0.0654],
        [0.3451],
        [0.1818],
        [0.1022],
        [0.7581],
        [0.7463]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6031    0  1601  100  4430   3992  11047 --:--:-- --:--:-- --:--:-- 15002
(1, 14)

  7%|▋         | 9/123 [00:19<03:21,  1.76s/it]

torch.Size([22, 1])
substrate: CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1, ec: (1, 14), score: tensor([[0.2754],
        [0.0306],
        [0.0049],
        [0.0580],
        [0.0652],
        [0.0602],
        [0.0041],
        [0.1517],
        [0.0481],
        [0.0320],
        [0.0281],
        [0.0303],
        [0.0768],
        [0.1751],
        [0.0468],
        [0.1596],
        [0.0060],
        [0.0150],
        [0.0217],
        [0.0959],
        [0.7815],
        [0.6670]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6017    0  1670  100  4347   4123  10733 --:--:-- --:--:-- --:--:-- 14856
(1, 14)

  8%|▊         | 10/123 [00:22<03:52,  2.06s/it]

torch.Size([23, 1])
substrate: CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O, ec: (1, 14), score: tensor([[0.0359],
        [0.0037],
        [0.0104],
        [0.0233],
        [0.0275],
        [0.0426],
        [0.0250],
        [0.0216],
        [0.0752],
        [0.0726],
        [0.0248],
        [0.0184],
        [0.0794],
        [0.0995],
        [0.0306],
        [0.0636],
        [0.0130],
        [0.0232],
        [0.0364],
        [0.0693],
        [0.8438],
        [0.3775],
        [0.1032]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(/C=C/C(C)=C/C=C/C(C)=C\C(=O)O)C(C)(C)CCC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6031    0  1601  100  4430   1019   2819  0:00:01  0:00:01 --:--:--  3836
(1, 14)

  9%|▉         | 11/123 [00:24<03:57,  2.12s/it]

torch.Size([22, 1])
substrate: CC1=C(/C=C/C(C)=C/C=C/C(C)=C\C(=O)O)C(C)(C)CCC1, ec: (1, 14), score: tensor([[0.3068],
        [0.0839],
        [0.0259],
        [0.0723],
        [0.0628],
        [0.0235],
        [0.0051],
        [0.0445],
        [0.0527],
        [0.0385],
        [0.0504],
        [0.0465],
        [0.1558],
        [0.1974],
        [0.0375],
        [0.1237],
        [0.0180],
        [0.0554],
        [0.0382],
        [0.1405],
        [0.7720],
        [0.4736]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6031    0  1601  100  4430   4032  11158 --:--:-- --:--:-- --:--:-- 15191
(1, 14)

 10%|▉         | 12/123 [00:27<04:10,  2.25s/it]

torch.Size([22, 1])
substrate: CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC1, ec: (1, 14), score: tensor([[0.3031],
        [0.0295],
        [0.0404],
        [0.0355],
        [0.0637],
        [0.0702],
        [0.0168],
        [0.0405],
        [0.0795],
        [0.1268],
        [0.0339],
        [0.0394],
        [0.1506],
        [0.2474],
        [0.0511],
        [0.1071],
        [0.0055],
        [0.0552],
        [0.0770],
        [0.1919],
        [0.8209],
        [0.4288]], device='cuda:0', grad_fn=<DivBackward0>)
CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(O)C(C(F)(F)F)=C2)CC3)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7101    0  2300  100  4801   2062   4305  0:00:01  0:00:01 --:--:--  6374
(1, 14)

 11%|█         | 13/123 [00:28<03:49,  2.09s/it]

torch.Size([31, 1])
substrate: CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(O)C(C(F)(F)F)=C2)CC3)C1, ec: (1, 14), score: tensor([[0.1825],
        [0.3081],
        [0.3850],
        [0.2012],
        [0.3222],
        [0.2189],
        [0.1624],
        [0.2617],
        [0.2908],
        [0.0348],
        [0.0317],
        [0.1573],
        [0.1184],
        [0.0518],
        [0.0855],
        [0.2384],
        [0.3893],
        [0.3069],
        [0.2970],
        [0.1377],
        [0.5320],
        [0.6422],
        [0.0284],
        [0.2679],
        [0.1411],
        [0.0806],
        [0.1622],
        [0.0392],
        [0.0400],
        [0.0328],
        [0.0638]], device='cuda:0', grad_fn=<DivBackward0>)
CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(OC)C(C(F)(F)F)=C2)CC3)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7419    0  2369  100  5050   5150  10978 --:--:-- --:--:-- --:--:-- 16163
(1, 14)

 11%|█▏        | 14/123 [00:31<04:22,  2.41s/it]

torch.Size([32, 1])
substrate: CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(OC)C(C(F)(F)F)=C2)CC3)C1, ec: (1, 14), score: tensor([[0.2328],
        [0.2812],
        [0.4132],
        [0.1799],
        [0.3378],
        [0.1397],
        [0.1582],
        [0.1360],
        [0.1764],
        [0.0339],
        [0.0643],
        [0.1161],
        [0.0365],
        [0.0029],
        [0.0195],
        [0.3350],
        [0.4959],
        [0.1723],
        [0.2502],
        [0.1233],
        [0.0374],
        [0.4721],
        [0.4755],
        [0.0315],
        [0.0786],
        [0.0714],
        [0.0271],
        [0.0992],
        [0.1498],
        [0.0686],
        [0.0055],
        [0.0565]], device='cuda:0', grad_fn=<DivBackward0>)
CCC(C)N1N=CN(C2=CC=C(N3CCN(C4=CC=C(OC[C@H]5CO[C@](CN6C=NC=N6)(C6=CC=C(Cl)C=C6Cl)O5)C=C4)CC3)C=C2)C1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11203    0  3624  100  7579   5653  11823 --:--:-- --:--:-- --:--:-- 17477
(1, 14)

 12%|█▏        | 15/123 [00:33<03:38,  2.03s/it]

torch.Size([49, 1])
substrate: CCC(C)N1N=CN(C2=CC=C(N3CCN(C4=CC=C(OC[C@H]5CO[C@](CN6C=NC=N6)(C6=CC=C(Cl)C=C6Cl)O5)C=C4)CC3)C=C2)C1=O, ec: (1, 14), score: tensor([[0.2445],
        [0.1522],
        [0.2120],
        [0.2208],
        [0.4319],
        [0.2869],
        [0.2704],
        [0.4111],
        [0.0550],
        [0.0518],
        [0.2856],
        [0.2566],
        [0.1606],
        [0.2802],
        [0.2934],
        [0.0189],
        [0.0597],
        [0.1518],
        [0.1352],
        [0.3027],
        [0.7830],
        [0.4705],
        [0.0469],
        [0.0443],
        [0.0127],
        [0.2217],
        [0.4644],
        [0.5299],
        [0.2014],
        [0.1081],
        [0.0544],
        [0.2523],
        [0.0398],
        [0.0176],
        [0.0394],
        [0.0071],
        [0.0805],
        [0.0035],
        [0.0140],
        [0.0880],
        [0.0115],
        [0.1195],
        [0.1607],
        [0.2504],
        [0.1760],
        [0.2109],
        [0.0939],
        [0.2879],
        [0.0740]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6819    0  1808  100  5011   4542  12590 --:--:-- --:--:-- --:--:-- 17133
(1, 14)

 13%|█▎        | 16/123 [00:34<03:04,  1.73s/it]

torch.Size([25, 1])
substrate: CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O, ec: (1, 14), score: tensor([[0.3508],
        [0.0778],
        [0.0242],
        [0.0465],
        [0.0679],
        [0.6488],
        [0.3005],
        [0.4103],
        [0.1059],
        [0.1055],
        [0.4323],
        [0.4326],
        [0.1316],
        [0.4245],
        [0.3340],
        [0.0137],
        [0.0045],
        [0.0169],
        [0.0117],
        [0.0173],
        [0.0140],
        [0.0640],
        [0.1102],
        [0.0347],
        [0.0908]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6985    0  1808  100  5177   4497  12878 --:--:-- --:--:-- --:--:-- 17332
(1, 14)

 14%|█▍        | 17/123 [00:36<03:33,  2.01s/it]

torch.Size([25, 1])
substrate: CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O, ec: (1, 14), score: tensor([[0.1322],
        [0.0190],
        [0.0222],
        [0.0427],
        [0.1552],
        [0.7371],
        [0.3459],
        [0.2665],
        [0.1026],
        [0.0189],
        [0.3807],
        [0.4418],
        [0.1040],
        [0.3257],
        [0.2623],
        [0.0171],
        [0.0054],
        [0.0120],
        [0.0068],
        [0.0173],
        [0.0149],
        [0.0165],
        [0.0369],
        [0.0214],
        [0.0919]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCCOC(=O)NC1=NC(=O)N([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6028    0  1834  100  4194   1865   4266 --:--:-- --:--:-- --:--:--  6126
(1, 14)

 15%|█▍        | 18/123 [00:38<03:16,  1.88s/it]

torch.Size([25, 1])
substrate: CCCCCOC(=O)NC1=NC(=O)N([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)C=C1F, ec: (1, 14), score: tensor([[0.1192],
        [0.0481],
        [0.0523],
        [0.0709],
        [0.2896],
        [0.5855],
        [0.5479],
        [0.0174],
        [0.2167],
        [0.0067],
        [0.0033],
        [0.0037],
        [0.0050],
        [0.1156],
        [0.0469],
        [0.0042],
        [0.0253],
        [0.0939],
        [0.0802],
        [0.0965],
        [0.2145],
        [0.2592],
        [0.0322],
        [0.0063],
        [0.0129]], device='cuda:0', grad_fn=<DivBackward0>)
CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6985    0  1808  100  5177   1515   4339  0:00:01  0:00:01 --:--:--  5850
(1, 14)

 15%|█▌        | 19/123 [00:41<03:58,  2.29s/it]

torch.Size([25, 1])
substrate: CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O, ec: (1, 14), score: tensor([[0.2753],
        [0.1191],
        [0.0278],
        [0.0215],
        [0.0537],
        [0.7965],
        [0.8240],
        [0.0982],
        [0.0304],
        [0.0168],
        [0.3870],
        [0.3732],
        [0.1417],
        [0.2600],
        [0.0956],
        [0.0050],
        [0.0053],
        [0.0103],
        [0.0101],
        [0.0195],
        [0.0370],
        [0.0516],
        [0.0430],
        [0.0235],
        [0.0891]], device='cuda:0', grad_fn=<DivBackward0>)
CCCC1=NC(C)=C2C(=O)N=C(C3=CC(S(=O)(=O)N4CCN(CC)CC4)=CC=C3OCC)NN12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8304    0  2507  100  5797   2785   6441 --:--:-- --:--:-- --:--:--  9226
(1, 14)

 16%|█▋        | 20/123 [00:43<03:32,  2.06s/it]

torch.Size([34, 1])
substrate: CCCC1=NC(C)=C2C(=O)N=C(C3=CC(S(=O)(=O)N4CCN(CC)CC4)=CC=C3OCC)NN12, ec: (1, 14), score: tensor([[0.0480],
        [0.1232],
        [0.1366],
        [0.3380],
        [0.0586],
        [0.0375],
        [0.1329],
        [0.0696],
        [0.0425],
        [0.0388],
        [0.1216],
        [0.1710],
        [0.0214],
        [0.0370],
        [0.0452],
        [0.9221],
        [0.7354],
        [0.6250],
        [0.2565],
        [0.1359],
        [0.1940],
        [0.2025],
        [0.2861],
        [0.2945],
        [0.2767],
        [0.2977],
        [0.1392],
        [0.1724],
        [0.2982],
        [0.3314],
        [0.3361],
        [0.0129],
        [0.3179],
        [0.2240]], device='cuda:0', grad_fn=<DivBackward0>)
CCN(CC)C(=O)[C@@]1(C2=CC=CC=C2)C[C@H]1CN
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4968    0  1355  100  3613   4315  11506 --:--:-- --:--:-- --:--:-- 15872
(1, 14)

 17%|█▋        | 21/123 [00:45<03:54,  2.30s/it]

torch.Size([18, 1])
substrate: CCN(CC)C(=O)[C@@]1(C2=CC=CC=C2)C[C@H]1CN, ec: (1, 14), score: tensor([[0.0947],
        [0.1171],
        [0.3329],
        [0.1711],
        [0.1597],
        [0.8052],
        [0.3921],
        [0.0264],
        [0.0228],
        [0.0595],
        [0.0306],
        [0.0245],
        [0.0468],
        [0.0740],
        [0.0321],
        [0.0708],
        [0.3040],
        [0.7690]], device='cuda:0', grad_fn=<DivBackward0>)
CCN[C@H]1CN(CCCOC)S(=O)(=O)C2=C1C=C(S(N)(=O)=O)S2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5641    0  1696  100  3945   3889   9048 --:--:-- --:--:-- --:--:-- 12938
(1, 14)

 18%|█▊        | 22/123 [00:47<03:14,  1.93s/it]

torch.Size([23, 1])
substrate: CCN[C@H]1CN(CCCOC)S(=O)(=O)C2=C1C=C(S(N)(=O)=O)S2, ec: (1, 14), score: tensor([[3.7487e-03],
        [1.4183e-02],
        [5.9202e-02],
        [5.7120e-02],
        [1.7551e-01],
        [1.7262e-01],
        [4.5004e-02],
        [3.1763e-03],
        [1.5795e-01],
        [6.2681e-01],
        [7.1330e-01],
        [6.4852e-01],
        [4.2213e-01],
        [2.6650e-01],
        [1.3381e-02],
        [2.7069e-04],
        [1.1551e-03],
        [1.4223e-02],
        [6.3442e-01],
        [6.0867e-02],
        [2.6320e-01],
        [2.4307e-01],
        [4.8117e-02]], device='cuda:0', grad_fn=<DivBackward0>)
CCO[C@H]1CCN(CC2=C(OC)C=C(C)C3=C2C=CN3)[C@H](C2=CC=C(C(=O)O)C=C2)C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7682    0  2300  100  5382   5054  11828 --:--:-- --:--:-- --:--:-- 16846
(1, 14)

 19%|█▊        | 23/123 [00:48<02:49,  1.69s/it]

torch.Size([31, 1])
substrate: CCO[C@H]1CCN(CC2=C(OC)C=C(C)C3=C2C=CN3)[C@H](C2=CC=C(C(=O)O)C=C2)C1, ec: (1, 14), score: tensor([[0.1901],
        [0.5269],
        [0.2690],
        [0.1575],
        [0.0242],
        [0.0655],
        [0.3853],
        [0.3410],
        [0.2677],
        [0.1417],
        [0.4002],
        [0.4214],
        [0.0304],
        [0.0808],
        [0.0791],
        [0.0630],
        [0.1063],
        [0.1860],
        [0.1575],
        [0.1704],
        [0.2140],
        [0.1094],
        [0.1946],
        [0.1983],
        [0.1912],
        [0.1685],
        [0.0110],
        [0.0836],
        [0.0914],
        [0.1382],
        [0.0416]], device='cuda:0', grad_fn=<DivBackward0>)
CCOC1=CC=C(O)C=C1OCCN[C@H](C)CC1=CC=C(OC)C(S(N)(=O)=O)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7134    0  2110  100  5024   5108  12164 --:--:-- --:--:-- --:--:-- 17231
(1, 14)

 20%|█▉        | 24/123 [00:51<03:30,  2.13s/it]

torch.Size([29, 1])
substrate: CCOC1=CC=C(O)C=C1OCCN[C@H](C)CC1=CC=C(OC)C(S(N)(=O)=O)=C1, ec: (1, 14), score: tensor([[0.1389],
        [0.3784],
        [0.3164],
        [0.1464],
        [0.0274],
        [0.0524],
        [0.4917],
        [0.5722],
        [0.0336],
        [0.0123],
        [0.1400],
        [0.0716],
        [0.0067],
        [0.0997],
        [0.0778],
        [0.0337],
        [0.0110],
        [0.0035],
        [0.0358],
        [0.0331],
        [0.0869],
        [0.3018],
        [0.2953],
        [0.0248],
        [0.8472],
        [0.2754],
        [0.4659],
        [0.4562],
        [0.0694]], device='cuda:0', grad_fn=<DivBackward0>)
CC[C@@H](C1=CC(O)=CC(O)=C1)[C@@H](C)CN(C)C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4856    0  1256  100  3600   4118  11803 --:--:-- --:--:-- --:--:-- 15869
(1, 14)

 20%|██        | 25/123 [00:52<02:54,  1.78s/it]

torch.Size([17, 1])
substrate: CC[C@@H](C1=CC(O)=CC(O)=C1)[C@@H](C)CN(C)C, ec: (1, 14), score: tensor([[0.2454],
        [0.1099],
        [0.1529],
        [0.0122],
        [0.0909],
        [0.2867],
        [0.3028],
        [0.2768],
        [0.3440],
        [0.2811],
        [0.0486],
        [0.3011],
        [0.0780],
        [0.4850],
        [0.6423],
        [0.5665],
        [0.5004]], device='cuda:0', grad_fn=<DivBackward0>)
CC[C@@H](C1=CC=CC(O)=C1)[C@@H](C)CN(C)C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4704    0  1187  100  3517    334    990  0:00:03  0:00:03 --:--:--  1324
(1, 14)

 21%|██        | 26/123 [00:56<04:01,  2.49s/it]

torch.Size([16, 1])
substrate: CC[C@@H](C1=CC=CC(O)=C1)[C@@H](C)CN(C)C, ec: (1, 14), score: tensor([[0.1054],
        [0.0508],
        [0.1911],
        [0.0148],
        [0.0469],
        [0.0310],
        [0.1275],
        [0.2916],
        [0.4929],
        [0.0192],
        [0.2171],
        [0.0352],
        [0.3343],
        [0.7678],
        [0.7152],
        [0.7294]], device='cuda:0', grad_fn=<DivBackward0>)
CC[C@@H]1C(=O)OC[C@@H]1CC1=CN=CN1C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4010    0  1144  100  2866   3678   9215 --:--:-- --:--:-- --:--:-- 12852
(1, 14)
torch.Size([15, 1])
substrate: CC[C@@H]1C(=O)OC[C@@H]1CC1=CN=CN1C, ec: (1, 14), score: tensor([[0.0486],
        [0.0991],
        [0.0698],
        [0.4570],
        [0.2047],
        [0.1483],
        [0.3812],
        [0.1229],
        [0.0647],
        [0.0669],
        [0.1021],
        [0.1700],
        [0.2259],
        [0.6894],
        [0.5756]], device='cuda:0', grad_fn=<DivBackward0>)

 22%|██▏       | 27/123 [00:57<03:12,  2.00s/it]

CN(C)CCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5832    0  1791  100  4041   4315   9737 --:--:-- --:--:-- --:--:-- 14019
(1, 14)

 23%|██▎       | 28/123 [01:00<03:55,  2.48s/it]

torch.Size([24, 1])
substrate: CN(C)CCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12, ec: (1, 14), score: tensor([[0.9368],
        [0.9891],
        [0.9327],
        [0.2400],
        [0.0043],
        [0.0076],
        [0.0156],
        [0.0033],
        [0.0161],
        [0.0183],
        [0.0019],
        [0.0509],
        [0.0111],
        [0.0209],
        [0.0056],
        [0.0076],
        [0.0011],
        [0.0137],
        [0.0098],
        [0.0149],
        [0.0188],
        [0.0140],
        [0.0129],
        [0.0047]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)CCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5836    0  1795  100  4041   4346   9784 --:--:-- --:--:-- --:--:-- 14165
(1, 14)

 24%|██▎       | 29/123 [01:02<03:16,  2.09s/it]

torch.Size([24, 1])
substrate: CN(C)CCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12, ec: (1, 14), score: tensor([[0.8862],
        [0.9244],
        [0.9048],
        [0.1244],
        [0.0045],
        [0.0176],
        [0.0317],
        [0.0103],
        [0.0541],
        [0.0492],
        [0.0075],
        [0.0570],
        [0.0585],
        [0.0363],
        [0.0039],
        [0.0313],
        [0.0050],
        [0.0148],
        [0.0282],
        [0.0183],
        [0.0253],
        [0.0838],
        [0.0550],
        [0.0054]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)CCC1=CNC2=CC(O)=C(CN3C=NC=N3)C=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5210    0  1584  100  3626   4686  10727 --:--:-- --:--:-- --:--:-- 15414
(1, 14)

 24%|██▍       | 30/123 [01:03<02:43,  1.76s/it]

torch.Size([21, 1])
substrate: CN(C)CCC1=CNC2=CC(O)=C(CN3C=NC=N3)C=C12, ec: (1, 14), score: tensor([[0.9021],
        [0.9377],
        [0.9136],
        [0.2720],
        [0.0096],
        [0.0073],
        [0.0150],
        [0.0908],
        [0.0032],
        [0.0298],
        [0.4019],
        [0.5000],
        [0.0826],
        [0.3888],
        [0.4764],
        [0.2711],
        [0.0563],
        [0.0249],
        [0.2594],
        [0.0107],
        [0.0019]], device='cuda:0', grad_fn=<DivBackward0>)
CN(C)CCC1=CNC2=CC=C(CN3C=NC=N3)C=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5058    0  1515  100  3543   4647  10868 --:--:-- --:--:-- --:--:-- 15515
(1, 14)

 25%|██▌       | 31/123 [01:05<03:08,  2.05s/it]

torch.Size([20, 1])
substrate: CN(C)CCC1=CNC2=CC=C(CN3C=NC=N3)C=C12, ec: (1, 14), score: tensor([[0.9054],
        [0.9879],
        [0.9180],
        [0.3110],
        [0.0149],
        [0.0015],
        [0.0196],
        [0.0790],
        [0.0028],
        [0.0199],
        [0.0068],
        [0.0052],
        [0.2952],
        [0.4096],
        [0.1918],
        [0.0808],
        [0.0788],
        [0.3134],
        [0.0041],
        [0.0027]], device='cuda:0', grad_fn=<DivBackward0>)
CN1C(=O)CC(=O)N(C2=CC=C(O)C=C2)C2=CC(Cl)=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4864    0  1653  100  3211   4905   9528 --:--:-- --:--:-- --:--:-- 14433
(1, 14)

 26%|██▌       | 32/123 [01:06<02:33,  1.69s/it]

torch.Size([22, 1])
substrate: CN1C(=O)CC(=O)N(C2=CC=C(O)C=C2)C2=CC(Cl)=CC=C12, ec: (1, 14), score: tensor([[0.3897],
        [0.5113],
        [0.5002],
        [0.3737],
        [0.1237],
        [0.6400],
        [0.3944],
        [0.4289],
        [0.0605],
        [0.1075],
        [0.1207],
        [0.4732],
        [0.7399],
        [0.2457],
        [0.0847],
        [0.0899],
        [0.0271],
        [0.0221],
        [0.0702],
        [0.0261],
        [0.0885],
        [0.0572]], device='cuda:0', grad_fn=<DivBackward0>)
CN1CC[C@@H](NC(=O)NC2=CC=C(C#N)C=C2)C[C@@H]1C1=NC2=CC=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6562    0  2093  100  4469   4589   9800 --:--:-- --:--:-- --:--:-- 14421
(1, 14)

 27%|██▋       | 33/123 [01:07<02:12,  1.48s/it]

torch.Size([28, 1])
substrate: CN1CC[C@@H](NC(=O)NC2=CC=C(C#N)C=C2)C[C@@H]1C1=NC2=CC=CC=C2N1, ec: (1, 14), score: tensor([[0.5627],
        [0.5961],
        [0.5578],
        [0.2043],
        [0.0708],
        [0.1445],
        [0.2016],
        [0.0158],
        [0.0349],
        [0.0038],
        [0.0344],
        [0.0201],
        [0.0144],
        [0.2040],
        [0.2251],
        [0.0343],
        [0.0228],
        [0.0671],
        [0.2327],
        [0.0419],
        [0.0835],
        [0.0466],
        [0.0571],
        [0.2132],
        [0.1738],
        [0.1827],
        [0.0507],
        [0.1275]], device='cuda:0', grad_fn=<DivBackward0>)
CNC(=O)C1=CC(OC2=CC=C(NC(=O)NC3=CC=C(Cl)C(C(F)(F)F)=C3)C=C2)=CC=N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6633    0  2343  100  4290   5448   9976 --:--:-- --:--:-- --:--:-- 15425
(1, 14)

 28%|██▊       | 34/123 [01:10<02:50,  1.92s/it]

torch.Size([32, 1])
substrate: CNC(=O)C1=CC(OC2=CC=C(NC(=O)NC3=CC=C(Cl)C(C(F)(F)F)=C3)C=C2)=CC=N1, ec: (1, 14), score: tensor([[0.4216],
        [0.6476],
        [0.1279],
        [0.0338],
        [0.0018],
        [0.0113],
        [0.0902],
        [0.2106],
        [0.0462],
        [0.0189],
        [0.0137],
        [0.0135],
        [0.3087],
        [0.6040],
        [0.2050],
        [0.4798],
        [0.0582],
        [0.1578],
        [0.0785],
        [0.0054],
        [0.1198],
        [0.0177],
        [0.1429],
        [0.0802],
        [0.0498],
        [0.1132],
        [0.2062],
        [0.0085],
        [0.0343],
        [0.0895],
        [0.0122],
        [0.0146]], device='cuda:0', grad_fn=<DivBackward0>)
CNCC(=O)OCC1=CC=CN=C1N(C)C(=O)OC(C)[N+]1=CN(C[C@](O)(C2=CC(F)=CC=C2F)[C@@H](C)C2=NC(C3=CC=C(C#N)C=C3)=CS2)N=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11198    0  3710  100  7488   7434  15006 --:--:-- --:--:-- --:--:-- 22440
(1, 14)

 28%|██▊       | 35/123 [01:11<02:28,  1.69s/it]

torch.Size([51, 1])
substrate: CNCC(=O)OCC1=CC=CN=C1N(C)C(=O)OC(C)[N+]1=CN(C[C@](O)(C2=CC(F)=CC=C2F)[C@@H](C)C2=NC(C3=CC=C(C#N)C=C3)=CS2)N=C1, ec: (1, 14), score: tensor([[0.3001],
        [0.4978],
        [0.2125],
        [0.1277],
        [0.0015],
        [0.2925],
        [0.0519],
        [0.0013],
        [0.0020],
        [0.0065],
        [0.0047],
        [0.0073],
        [0.0418],
        [0.2029],
        [0.1087],
        [0.6133],
        [0.0540],
        [0.6258],
        [0.5941],
        [0.0141],
        [0.1094],
        [0.2042],
        [0.0205],
        [0.2421],
        [0.7496],
        [0.7497],
        [0.0130],
        [0.0108],
        [0.0806],
        [0.1477],
        [0.1378],
        [0.1491],
        [0.0254],
        [0.0177],
        [0.3259],
        [0.0221],
        [0.0800],
        [0.0916],
        [0.0059],
        [0.0010],
        [0.0481],
        [0.0733],
        [0.0318],
        [0.5692],
        [0.4452],
        [0.0708],
        [0.0719],
        [0.1423],
        [0.1397],
        [0.0045],
        [0.0410]], device='cuda:0', grad_fn=<DivBackward0>)
CNCCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5514    0  1722  100  3792   4080   8985 --:--:-- --:--:-- --:--:-- 13066
(1, 14)

 29%|██▉       | 36/123 [01:12<02:08,  1.48s/it]

torch.Size([23, 1])
substrate: CNCCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12, ec: (1, 14), score: tensor([[0.9160],
        [0.9716],
        [0.3000],
        [0.0100],
        [0.0070],
        [0.0231],
        [0.0210],
        [0.0432],
        [0.0304],
        [0.0038],
        [0.0228],
        [0.0223],
        [0.0413],
        [0.0052],
        [0.0084],
        [0.0035],
        [0.0478],
        [0.0550],
        [0.0674],
        [0.0637],
        [0.0274],
        [0.0287],
        [0.0037]], device='cuda:0', grad_fn=<DivBackward0>)
CNCCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5518    0  1726  100  3792   2123   4664 --:--:-- --:--:-- --:--:--  6787
(1, 14)

 30%|███       | 37/123 [01:15<02:36,  1.82s/it]

torch.Size([23, 1])
substrate: CNCCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12, ec: (1, 14), score: tensor([[0.9190],
        [0.9831],
        [0.3672],
        [0.0162],
        [0.0059],
        [0.0158],
        [0.0136],
        [0.0417],
        [0.0361],
        [0.0032],
        [0.0287],
        [0.0405],
        [0.0348],
        [0.0032],
        [0.0186],
        [0.0022],
        [0.0246],
        [0.0604],
        [0.0148],
        [0.0108],
        [0.0212],
        [0.0294],
        [0.0035]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=C(OCCCN2CCOCC2)C=CC2=C1N=C(NC(=O)C1=CN=C(N)N=C1)N1CCN=C21
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8163    0  2602  100  5561   4827  10317 --:--:-- --:--:-- --:--:-- 15116
(1, 14)

 31%|███       | 38/123 [01:16<02:17,  1.61s/it]

torch.Size([35, 1])
substrate: COC1=C(OCCCN2CCOCC2)C=CC2=C1N=C(NC(=O)C1=CN=C(N)N=C1)N1CCN=C21, ec: (1, 14), score: tensor([[0.0863],
        [0.1599],
        [0.0907],
        [0.1679],
        [0.4289],
        [0.4751],
        [0.0741],
        [0.0677],
        [0.4099],
        [0.3495],
        [0.2528],
        [0.0320],
        [0.2082],
        [0.3920],
        [0.0353],
        [0.2834],
        [0.1217],
        [0.0190],
        [0.0253],
        [0.0473],
        [0.5565],
        [0.8394],
        [0.2182],
        [0.4468],
        [0.1742],
        [0.0401],
        [0.0145],
        [0.0574],
        [0.0182],
        [0.1125],
        [0.1198],
        [0.0520],
        [0.0358],
        [0.0505],
        [0.0088]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC(C)=C2NC=CC2=C1CN1CC[C@H](O)C[C@H]1C1=CC=C(C(=O)O)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7046    0  2162  100  4884   4580  10347 --:--:-- --:--:-- --:--:-- 14896
(1, 14)

 32%|███▏      | 39/123 [01:17<02:02,  1.46s/it]

torch.Size([29, 1])
substrate: COC1=CC(C)=C2NC=CC2=C1CN1CC[C@H](O)C[C@H]1C1=CC=C(C(=O)O)C=C1, ec: (1, 14), score: tensor([[0.3887],
        [0.2988],
        [0.0509],
        [0.0541],
        [0.2081],
        [0.0845],
        [0.0260],
        [0.1857],
        [0.3058],
        [0.2157],
        [0.0248],
        [0.0482],
        [0.2042],
        [0.3433],
        [0.0543],
        [0.1082],
        [0.7410],
        [0.7275],
        [0.1208],
        [0.0644],
        [0.1181],
        [0.2369],
        [0.2079],
        [0.2815],
        [0.1868],
        [0.0066],
        [0.1137],
        [0.2616],
        [0.1349]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC(NC2=C(C#N)C=NC3=CC(OCCCN4CCN(C)CC4)=C(OC)C=C23)=C(Cl)C=C1Cl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8359    0  2645  100  5714   5487  11854 --:--:-- --:--:-- --:--:-- 17342
(1, 14)

 33%|███▎      | 40/123 [01:20<02:38,  1.91s/it]

torch.Size([36, 1])
substrate: COC1=CC(NC2=C(C#N)C=NC3=CC(OCCCN4CCN(C)CC4)=C(OC)C=C23)=C(Cl)C=C1Cl, ec: (1, 14), score: tensor([[0.3137],
        [0.3891],
        [0.0296],
        [0.0563],
        [0.0203],
        [0.4396],
        [0.0291],
        [0.0337],
        [0.1941],
        [0.0457],
        [0.0294],
        [0.0331],
        [0.0048],
        [0.0473],
        [0.2587],
        [0.6116],
        [0.3177],
        [0.2271],
        [0.0835],
        [0.2587],
        [0.2696],
        [0.3265],
        [0.2971],
        [0.3286],
        [0.2085],
        [0.2631],
        [0.0156],
        [0.0180],
        [0.0497],
        [0.0228],
        [0.0053],
        [0.0931],
        [0.1538],
        [0.0155],
        [0.0495],
        [0.2589]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC(OC)=CC(N(CCNC(C)C)C2=CC=C3N=CC(C4=CN(C)N=C4)=NC3=C2)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7986    0  2438  100  5548   5405  12301 --:--:-- --:--:-- --:--:-- 17707
(1, 14)

 33%|███▎      | 41/123 [01:21<02:16,  1.66s/it]

torch.Size([33, 1])
substrate: COC1=CC(OC)=CC(N(CCNC(C)C)C2=CC=C3N=CC(C4=CN(C)N=C4)=NC3=C2)=C1, ec: (1, 14), score: tensor([[0.3918],
        [0.2770],
        [0.1958],
        [0.0451],
        [0.0785],
        [0.1510],
        [0.2107],
        [0.1108],
        [0.2273],
        [0.7062],
        [0.1327],
        [0.1154],
        [0.2841],
        [0.0662],
        [0.0348],
        [0.0198],
        [0.1029],
        [0.0274],
        [0.0092],
        [0.0037],
        [0.0410],
        [0.0962],
        [0.0125],
        [0.0062],
        [0.1737],
        [0.6811],
        [0.4764],
        [0.2728],
        [0.0452],
        [0.0457],
        [0.0051],
        [0.0191],
        [0.2506]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC2=C(C(OC)=C1OC)C1=CC=C(OC)C(=O)C=C1[C@@H](NC(C)=O)CC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6924    0  2136  100  4788   4944  11083 --:--:-- --:--:-- --:--:-- 16027
(1, 14)

 34%|███▍      | 42/123 [01:25<02:59,  2.22s/it]

torch.Size([29, 1])
substrate: COC1=CC2=C(C(OC)=C1OC)C1=CC=C(OC)C(=O)C=C1[C@@H](NC(C)=O)CC2, ec: (1, 14), score: tensor([[0.3372],
        [0.2838],
        [0.1579],
        [0.1325],
        [0.1174],
        [0.1150],
        [0.1416],
        [0.0644],
        [0.0760],
        [0.0577],
        [0.0966],
        [0.0284],
        [0.2568],
        [0.1079],
        [0.0513],
        [0.2576],
        [0.0994],
        [0.1864],
        [0.4572],
        [0.1915],
        [0.0533],
        [0.0262],
        [0.1604],
        [0.1026],
        [0.0839],
        [0.0668],
        [0.0156],
        [0.1680],
        [0.3362]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC2=C(C=C1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6344    0  1722  100  4622    901   2418  0:00:01  0:00:01 --:--:--  3317
(1, 14)

 35%|███▍      | 43/123 [01:29<03:51,  2.89s/it]

torch.Size([23, 1])
substrate: COC1=CC2=C(C=C1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2, ec: (1, 14), score: tensor([[0.0270],
        [0.0166],
        [0.0099],
        [0.0173],
        [0.0184],
        [0.0130],
        [0.0197],
        [0.0420],
        [0.2167],
        [0.3047],
        [0.0678],
        [0.3556],
        [0.9587],
        [0.9100],
        [0.0528],
        [0.0020],
        [0.0030],
        [0.0113],
        [0.0099],
        [0.0816],
        [0.1090],
        [0.0701],
        [0.0840]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=C(C[C@@H](C)NCCOC2=CC=CC=C2O)C=C1S(N)(=O)=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6346    0  1903  100  4443   4641  10836 --:--:-- --:--:-- --:--:-- 15478
(1, 14)

 36%|███▌      | 44/123 [01:30<03:05,  2.35s/it]

torch.Size([26, 1])
substrate: COC1=CC=C(C[C@@H](C)NCCOC2=CC=CC=C2O)C=C1S(N)(=O)=O, ec: (1, 14), score: tensor([[0.3376],
        [0.2833],
        [0.0435],
        [0.0078],
        [0.0133],
        [0.0032],
        [0.0423],
        [0.0244],
        [0.0631],
        [0.0906],
        [0.0036],
        [0.2668],
        [0.4439],
        [0.1274],
        [0.0078],
        [0.0952],
        [0.0040],
        [0.1626],
        [0.1832],
        [0.4335],
        [0.0169],
        [0.0352],
        [0.9616],
        [0.2335],
        [0.4518],
        [0.5229]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=C2N=C(S(=O)CC3=NC=C(C)C(OC)=C3C)NC2=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5666    0  1791  100  3875   3885   8405 --:--:-- --:--:-- --:--:-- 12290
(1, 14)

 37%|███▋      | 45/123 [01:31<02:36,  2.00s/it]

torch.Size([24, 1])
substrate: COC1=CC=C2N=C(S(=O)CC3=NC=C(C)C(OC)=C3C)NC2=C1, ec: (1, 14), score: tensor([[0.1574],
        [0.1094],
        [0.0689],
        [0.1648],
        [0.2141],
        [0.0296],
        [0.1729],
        [0.0763],
        [0.8357],
        [0.6817],
        [0.1202],
        [0.0304],
        [0.1398],
        [0.1745],
        [0.1798],
        [0.2538],
        [0.0991],
        [0.3285],
        [0.3678],
        [0.1387],
        [0.1227],
        [0.1653],
        [0.0158],
        [0.1060]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)CC3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6388    0  2168  100  4220   4573   8902 --:--:-- --:--:-- --:--:-- 13476
(1, 14)

 37%|███▋      | 46/123 [01:34<02:57,  2.31s/it]

torch.Size([29, 1])
substrate: COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)CC3, ec: (1, 14), score: tensor([[4.1061e-02],
        [5.7422e-02],
        [5.7693e-02],
        [5.9997e-02],
        [5.6707e-02],
        [6.0248e-02],
        [5.2296e-02],
        [2.6918e-02],
        [3.9927e-02],
        [3.2472e-02],
        [8.4739e-02],
        [2.8269e-01],
        [2.1188e-01],
        [1.0072e-03],
        [9.2347e-04],
        [2.5831e-01],
        [1.8265e-01],
        [1.5868e-02],
        [4.4376e-02],
        [1.3851e-02],
        [6.6089e-02],
        [9.2647e-02],
        [1.4494e-01],
        [2.3629e-01],
        [2.7530e-02],
        [9.4559e-01],
        [9.6544e-01],
        [1.0749e-02],
        [1.3521e-03]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8860    0  2884  100  5976   5177  10728 --:--:-- --:--:-- --:--:-- 15906
(1, 14)

 38%|███▊      | 47/123 [01:35<02:27,  1.94s/it]

torch.Size([39, 1])
substrate: COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1, ec: (1, 14), score: tensor([[1.4925e-02],
        [1.2214e-02],
        [1.6401e-02],
        [4.9609e-02],
        [8.6068e-02],
        [1.0146e-01],
        [1.2842e-01],
        [7.6580e-02],
        [5.3198e-02],
        [3.4118e-02],
        [3.0215e-02],
        [1.4048e-02],
        [2.8261e-02],
        [8.2848e-04],
        [6.2025e-04],
        [1.0439e-01],
        [1.3213e-01],
        [2.6512e-03],
        [2.3618e-02],
        [3.9099e-02],
        [5.5286e-03],
        [5.8728e-03],
        [7.7165e-03],
        [2.2145e-01],
        [3.0931e-02],
        [9.2471e-01],
        [9.6830e-01],
        [3.1550e-02],
        [2.8136e-02],
        [8.6299e-02],
        [8.3027e-02],
        [2.6821e-02],
        [9.5320e-04],
        [4.6732e-03],
        [4.6445e-03],
        [1.7142e-02],
        [1.8965e-03],
        [1.4466e-03],
        [1.5447e-03]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(O)CO)CC3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6554    0  2168  100  4386   4642   9391 --:--:-- --:--:-- --:--:-- 14034
(1, 14)

 39%|███▉      | 48/123 [01:37<02:13,  1.78s/it]

torch.Size([29, 1])
substrate: COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(O)CO)CC3, ec: (1, 14), score: tensor([[0.0303],
        [0.0214],
        [0.0146],
        [0.0229],
        [0.1417],
        [0.1365],
        [0.0742],
        [0.0440],
        [0.0455],
        [0.0141],
        [0.0208],
        [0.2922],
        [0.2901],
        [0.0024],
        [0.0012],
        [0.2217],
        [0.1780],
        [0.0462],
        [0.0222],
        [0.0503],
        [0.0192],
        [0.0844],
        [0.2050],
        [0.5416],
        [0.4560],
        [0.6374],
        [0.7723],
        [0.0258],
        [0.0021]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9026    0  2884  100  6142   4050   8626 --:--:-- --:--:-- --:--:-- 12676
(1, 14)

 40%|███▉      | 49/123 [01:39<02:25,  1.97s/it]

torch.Size([39, 1])
substrate: COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1, ec: (1, 14), score: tensor([[3.6890e-02],
        [2.3393e-02],
        [1.2197e-02],
        [4.5968e-02],
        [1.2298e-01],
        [4.3345e-02],
        [4.7071e-02],
        [2.7753e-02],
        [1.2785e-01],
        [6.8032e-02],
        [5.4883e-02],
        [1.1695e-01],
        [4.1494e-02],
        [9.7131e-04],
        [3.1021e-04],
        [6.8013e-02],
        [3.4703e-02],
        [2.0247e-02],
        [8.3401e-03],
        [1.6812e-02],
        [2.2252e-03],
        [7.2090e-03],
        [7.0279e-03],
        [3.9907e-01],
        [3.6903e-01],
        [6.3042e-01],
        [6.0978e-01],
        [3.9952e-03],
        [4.5185e-02],
        [1.1104e-01],
        [3.9681e-02],
        [3.6334e-03],
        [3.4647e-03],
        [1.0445e-01],
        [4.0696e-03],
        [1.3426e-02],
        [1.2946e-03],
        [1.6211e-04],
        [1.0414e-03]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=NC(N)=NC2=C1N=CN2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2807    0   937  100  1870   2965   5917 --:--:-- --:--:-- --:--:--  8882
(1, 14)

 41%|████      | 50/123 [01:40<02:02,  1.68s/it]

torch.Size([12, 1])
substrate: COC1=NC(N)=NC2=C1N=CN2, ec: (1, 14), score: tensor([[0.8252],
        [0.7604],
        [0.3692],
        [0.1458],
        [0.0901],
        [0.1726],
        [0.0937],
        [0.0955],
        [0.0823],
        [0.2169],
        [0.1427],
        [0.5334]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=NC(N)=NC2=C1N=CN2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4878    0  1584  100  3294   4934  10261 --:--:-- --:--:-- --:--:-- 15196
(1, 14)

 41%|████▏     | 51/123 [01:41<01:44,  1.45s/it]

torch.Size([21, 1])
substrate: COC1=NC(N)=NC2=C1N=CN2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O, ec: (1, 14), score: tensor([[0.7365],
        [0.6167],
        [0.1118],
        [0.0137],
        [0.0045],
        [0.0121],
        [0.0240],
        [0.0215],
        [0.0100],
        [0.0353],
        [0.0261],
        [0.0579],
        [0.1090],
        [0.0009],
        [0.0008],
        [0.0789],
        [0.1961],
        [0.0167],
        [0.0850],
        [0.2030],
        [0.3126]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=NC2=CC=C(Br)C=C2C=C1[C@@H](C1=CC=CC=C1)[C@@](O)(CCN(C)C)C1=CC=CC2=CC=CC=C12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8720    0  2744  100  5976   4498   9796 --:--:-- --:--:-- --:--:-- 14295
(1, 14)

 42%|████▏     | 52/123 [01:44<02:13,  1.88s/it]

torch.Size([37, 1])
substrate: COC1=NC2=CC=C(Br)C=C2C=C1[C@@H](C1=CC=CC=C1)[C@@](O)(CCN(C)C)C1=CC=CC2=CC=CC=C12, ec: (1, 14), score: tensor([[7.7073e-01],
        [7.2864e-01],
        [1.9201e-01],
        [6.3154e-02],
        [5.3346e-03],
        [8.0627e-03],
        [2.0954e-02],
        [1.5110e-02],
        [1.3717e-01],
        [1.3488e-01],
        [1.9582e-02],
        [1.4491e-01],
        [5.8122e-02],
        [3.6291e-01],
        [1.1790e-03],
        [1.1315e-02],
        [4.5079e-03],
        [6.1989e-03],
        [5.6772e-03],
        [1.4885e-02],
        [7.8893e-01],
        [8.6430e-01],
        [5.0190e-02],
        [2.3282e-01],
        [9.5942e-01],
        [8.9256e-01],
        [8.7846e-01],
        [4.7665e-02],
        [4.5757e-02],
        [4.8635e-02],
        [1.6093e-02],
        [3.9609e-04],
        [4.7606e-02],
        [2.3959e-02],
        [2.5411e-02],
        [4.0214e-02],
        [4.9126e-04]], device='cuda:0', grad_fn=<DivBackward0>)
COC1=NC=C(N2CCC3=NC=NC(N)=C3C2)C=C1C(F)(F)F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5099    0  1722  100  3377   1268   2488  0:00:01  0:00:01 --:--:--  3757
(1, 14)

 43%|████▎     | 53/123 [01:46<02:13,  1.91s/it]

torch.Size([23, 1])
substrate: COC1=NC=C(N2CCC3=NC=NC(N)=C3C2)C=C1C(F)(F)F, ec: (1, 14), score: tensor([[0.5131],
        [0.3526],
        [0.1748],
        [0.1276],
        [0.3902],
        [0.1679],
        [0.4635],
        [0.2825],
        [0.1548],
        [0.0132],
        [0.2055],
        [0.1817],
        [0.1505],
        [0.0367],
        [0.2077],
        [0.0962],
        [0.2688],
        [0.2666],
        [0.0329],
        [0.1626],
        [0.0447],
        [0.0422],
        [0.0335]], device='cuda:0', grad_fn=<DivBackward0>)
CS(=O)(=O)C1=CC=C(C(=O)NC2=CC(O)=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5859    0  2067  100  3792   4840   8880 --:--:-- --:--:-- --:--:-- 13721
(1, 14)

 44%|████▍     | 54/123 [01:49<02:31,  2.19s/it]

torch.Size([28, 1])
substrate: CS(=O)(=O)C1=CC=C(C(=O)NC2=CC(O)=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1, ec: (1, 14), score: tensor([[0.0609],
        [0.9619],
        [0.6841],
        [0.7690],
        [0.0130],
        [0.0292],
        [0.0400],
        [0.0130],
        [0.5683],
        [0.1058],
        [0.5098],
        [0.0993],
        [0.1673],
        [0.7542],
        [0.6959],
        [0.0185],
        [0.0389],
        [0.0076],
        [0.0155],
        [0.3463],
        [0.4130],
        [0.3982],
        [0.2545],
        [0.1300],
        [0.0880],
        [0.0157],
        [0.0383],
        [0.0142]], device='cuda:0', grad_fn=<DivBackward0>)
CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=C(O)C=N3)=C2)C(Cl)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5859    0  2067  100  3792   4852   8901 --:--:-- --:--:-- --:--:-- 13721
(1, 14)

 45%|████▍     | 55/123 [01:50<02:08,  1.89s/it]

torch.Size([28, 1])
substrate: CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=C(O)C=N3)=C2)C(Cl)=C1, ec: (1, 14), score: tensor([[0.0636],
        [0.9535],
        [0.7426],
        [0.8025],
        [0.0294],
        [0.0480],
        [0.0237],
        [0.0066],
        [0.3360],
        [0.0363],
        [0.3051],
        [0.1071],
        [0.0851],
        [0.0484],
        [0.0373],
        [0.0417],
        [0.0067],
        [0.0099],
        [0.0651],
        [0.4836],
        [0.8973],
        [0.8704],
        [0.4066],
        [0.1949],
        [0.1406],
        [0.0076],
        [0.0991],
        [0.0640]], device='cuda:0', grad_fn=<DivBackward0>)
CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5707    0  1998  100  3709   1388   2577  0:00:01  0:00:01 --:--:--  3965
(1, 14)

 46%|████▌     | 56/123 [01:54<02:41,  2.42s/it]

torch.Size([27, 1])
substrate: CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1, ec: (1, 14), score: tensor([[0.0820],
        [0.9416],
        [0.8471],
        [0.6977],
        [0.0950],
        [0.0552],
        [0.0349],
        [0.0181],
        [0.7073],
        [0.1663],
        [0.6164],
        [0.1531],
        [0.0798],
        [0.1026],
        [0.0458],
        [0.0799],
        [0.0081],
        [0.0703],
        [0.4281],
        [0.4503],
        [0.5300],
        [0.3767],
        [0.2190],
        [0.0637],
        [0.0064],
        [0.0307],
        [0.0048]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)NC4=CC=CC(C(=O)O)=C4)C3)[C@H](C)[C@H]12
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7571    0  2438  100  5133   5478  11534 --:--:-- --:--:-- --:--:-- 17013
(1, 14)

 46%|████▋     | 57/123 [01:55<02:11,  2.00s/it]

torch.Size([33, 1])
substrate: C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)NC4=CC=CC(C(=O)O)=C4)C3)[C@H](C)[C@H]12, ec: (1, 14), score: tensor([[0.0715],
        [0.9187],
        [0.9100],
        [0.1726],
        [0.0111],
        [0.0135],
        [0.1002],
        [0.0553],
        [0.0017],
        [0.0010],
        [0.0038],
        [0.1655],
        [0.4555],
        [0.0304],
        [0.0196],
        [0.0086],
        [0.0477],
        [0.0901],
        [0.0133],
        [0.1817],
        [0.0853],
        [0.1606],
        [0.0981],
        [0.2880],
        [0.2944],
        [0.2036],
        [0.0209],
        [0.0746],
        [0.1533],
        [0.0251],
        [0.0092],
        [0.0153],
        [0.0684]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H]1CC[C@H]2[C@@H](C)[C@@H](O)O[C@@H]3O[C@]4(C)CC[C@@H]1[C@]23OO4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5524    0  1553  100  3971   3318   8485 --:--:-- --:--:-- --:--:-- 11778
(1, 14)

 47%|████▋     | 58/123 [01:56<01:50,  1.70s/it]

torch.Size([20, 1])
substrate: C[C@@H]1CC[C@H]2[C@@H](C)[C@@H](O)O[C@@H]3O[C@]4(C)CC[C@@H]1[C@]23OO4, ec: (1, 14), score: tensor([[0.0845],
        [0.0312],
        [0.0446],
        [0.0058],
        [0.0044],
        [0.0043],
        [0.0033],
        [0.3285],
        [0.4354],
        [0.0187],
        [0.0768],
        [0.0052],
        [0.1890],
        [0.0684],
        [0.0748],
        [0.0066],
        [0.0060],
        [0.0524],
        [0.0252],
        [0.0118]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8183    0  2622  100  5561   4900  10394 --:--:-- --:--:-- --:--:-- 15266
(1, 14)

 48%|████▊     | 59/123 [01:59<02:11,  2.06s/it]

torch.Size([35, 1])
substrate: C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)O, ec: (1, 14), score: tensor([[0.0737],
        [0.0124],
        [0.0419],
        [0.0406],
        [0.0156],
        [0.0862],
        [0.1442],
        [0.2114],
        [0.0149],
        [0.0190],
        [0.1330],
        [0.1187],
        [0.0284],
        [0.0207],
        [0.0049],
        [0.0152],
        [0.0115],
        [0.0149],
        [0.8049],
        [0.8347],
        [0.0757],
        [0.0120],
        [0.0324],
        [0.1076],
        [0.2374],
        [0.2664],
        [0.0077],
        [0.0494],
        [0.0393],
        [0.0629],
        [0.4273],
        [0.0519],
        [0.0841],
        [0.0114],
        [0.0194]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)SCF
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8570    0  2760  100  5810   5111  10759 --:--:-- --:--:-- --:--:-- 15841
(1, 14)

 49%|████▉     | 60/123 [02:00<01:52,  1.79s/it]

torch.Size([37, 1])
substrate: C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)SCF, ec: (1, 14), score: tensor([[0.0720],
        [0.0148],
        [0.0242],
        [0.0395],
        [0.0112],
        [0.0503],
        [0.2519],
        [0.2917],
        [0.0016],
        [0.0201],
        [0.2113],
        [0.1291],
        [0.0290],
        [0.0015],
        [0.0024],
        [0.0025],
        [0.0107],
        [0.0062],
        [0.8307],
        [0.9061],
        [0.0340],
        [0.0256],
        [0.0651],
        [0.0575],
        [0.0819],
        [0.1398],
        [0.0289],
        [0.0103],
        [0.0416],
        [0.0375],
        [0.1935],
        [0.0277],
        [0.1714],
        [0.0107],
        [0.1554],
        [0.0048],
        [0.0020]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7902    0  2105  100  5797   3433   9456 --:--:-- --:--:-- --:--:-- 12869
(1, 14)

 50%|████▉     | 61/123 [02:04<02:26,  2.37s/it]

torch.Size([28, 1])
substrate: C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C, ec: (1, 14), score: tensor([[0.0110],
        [0.0160],
        [0.0460],
        [0.0203],
        [0.1194],
        [0.0206],
        [0.1140],
        [0.0073],
        [0.0281],
        [0.0326],
        [0.0065],
        [0.0231],
        [0.6264],
        [0.1283],
        [0.8373],
        [0.4176],
        [0.1127],
        [0.0367],
        [0.0263],
        [0.0093],
        [0.0078],
        [0.0120],
        [0.0366],
        [0.0070],
        [0.0711],
        [0.1493],
        [0.0077],
        [0.0228]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8068    0  2105  100  5963   4556  12906 --:--:-- --:--:-- --:--:-- 17501
(1, 14)

 50%|█████     | 62/123 [02:05<02:01,  1.99s/it]

torch.Size([28, 1])
substrate: C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C, ec: (1, 14), score: tensor([[0.0221],
        [0.0491],
        [0.0351],
        [0.0137],
        [0.0606],
        [0.0171],
        [0.1241],
        [0.0146],
        [0.0351],
        [0.0601],
        [0.0075],
        [0.0079],
        [0.4940],
        [0.5066],
        [0.5064],
        [0.0531],
        [0.0469],
        [0.0743],
        [0.0148],
        [0.0281],
        [0.0164],
        [0.0014],
        [0.0143],
        [0.0114],
        [0.1027],
        [0.2412],
        [0.0423],
        [0.0819]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H](N)CC1=CC=C(O)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3114    0   842  100  2272    963   2599 --:--:-- --:--:-- --:--:--  3558
(1, 14)

 51%|█████     | 63/123 [02:08<02:29,  2.49s/it]

torch.Size([11, 1])
substrate: C[C@H](N)CC1=CC=C(O)C=C1, ec: (1, 14), score: tensor([[0.4093],
        [0.8355],
        [0.8788],
        [0.2685],
        [0.0980],
        [0.0331],
        [0.3873],
        [0.2714],
        [0.4853],
        [0.3807],
        [0.0351]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H](N)CC1=CC=CC=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2962    0   773  100  2189   2477   7016 --:--:-- --:--:-- --:--:--  9493
(1, 14)

 52%|█████▏    | 64/123 [02:09<01:57,  1.99s/it]

torch.Size([10, 1])
substrate: C[C@H](N)CC1=CC=CC=C1, ec: (1, 14), score: tensor([[0.6472],
        [0.8734],
        [0.9307],
        [0.1956],
        [0.0300],
        [0.1181],
        [0.0662],
        [0.0812],
        [0.0740],
        [0.0916]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@H]1O[C@@H](N2C=C(F)C(N)=NC2=O)[C@H](O)[C@@H]1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3982    0  1282  100  2700   4082   8598 --:--:-- --:--:-- --:--:-- 12681
(1, 14)

 53%|█████▎    | 65/123 [02:10<01:37,  1.68s/it]

torch.Size([17, 1])
substrate: C[C@H]1O[C@@H](N2C=C(F)C(N)=NC2=O)[C@H](O)[C@@H]1O, ec: (1, 14), score: tensor([[0.0900],
        [0.0798],
        [0.0288],
        [0.2276],
        [0.2599],
        [0.1771],
        [0.4925],
        [0.2796],
        [0.0972],
        [0.2498],
        [0.0253],
        [0.0053],
        [0.0123],
        [0.2414],
        [0.2285],
        [0.1080],
        [0.1620]], device='cuda:0', grad_fn=<DivBackward0>)
C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CC=C2C1=CC=CN=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7056    0  1993  100  5063   3656   9289 --:--:-- --:--:-- --:--:-- 12946
(1, 14)

 54%|█████▎    | 66/123 [02:13<02:01,  2.13s/it]

torch.Size([26, 1])
substrate: C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CC=C2C1=CC=CN=C1, ec: (1, 14), score: tensor([[0.0179],
        [0.0153],
        [0.0161],
        [0.0460],
        [0.0079],
        [0.0531],
        [0.5573],
        [0.0538],
        [0.0152],
        [0.0413],
        [0.1687],
        [0.1729],
        [0.0622],
        [0.0293],
        [0.0090],
        [0.0078],
        [0.0716],
        [0.2634],
        [0.0814],
        [0.0684],
        [0.2133],
        [0.2496],
        [0.1874],
        [0.3495],
        [0.2254],
        [0.3212]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1CC1)C(=O)N2C1=CC=C(O)C(N)=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7582    0  2602  100  4980   5224  10000 --:--:-- --:--:-- --:--:-- 15224
(1, 14)

 54%|█████▍    | 67/123 [02:14<01:41,  1.81s/it]

torch.Size([35, 1])
substrate: CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1CC1)C(=O)N2C1=CC=C(O)C(N)=C1, ec: (1, 14), score: tensor([[0.0812],
        [0.0814],
        [0.0261],
        [0.1322],
        [0.0317],
        [0.3620],
        [0.0412],
        [0.0845],
        [0.0708],
        [0.1300],
        [0.3976],
        [0.0117],
        [0.1397],
        [0.2078],
        [0.7741],
        [0.6056],
        [0.2386],
        [0.0735],
        [0.0381],
        [0.0660],
        [0.0204],
        [0.0083],
        [0.0167],
        [0.0180],
        [0.0254],
        [0.0183],
        [0.2735],
        [0.1707],
        [0.2862],
        [0.3398],
        [0.5678],
        [0.5101],
        [0.2209],
        [0.4410],
        [0.1739]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(OCC(F)(F)F)C=CN=C1CS(=O)C1=NC2=CC=C(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)C=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8082    0  2783  100  5299   2530   4817  0:00:01  0:00:01 --:--:--  7347
(1, 14)

 55%|█████▌    | 68/123 [02:18<02:11,  2.39s/it]

torch.Size([38, 1])
substrate: CC1=C(OCC(F)(F)F)C=CN=C1CS(=O)C1=NC2=CC=C(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)C=C2N1, ec: (1, 14), score: tensor([[0.0848],
        [0.0011],
        [0.1549],
        [0.4360],
        [0.2635],
        [0.0029],
        [0.0087],
        [0.0055],
        [0.0146],
        [0.1685],
        [0.0641],
        [0.1144],
        [0.0092],
        [0.2175],
        [0.8609],
        [0.6805],
        [0.0058],
        [0.0157],
        [0.0009],
        [0.0054],
        [0.0116],
        [0.0664],
        [0.4947],
        [0.3419],
        [0.0049],
        [0.0014],
        [0.0022],
        [0.0062],
        [0.0140],
        [0.0073],
        [0.0237],
        [0.0160],
        [0.0262],
        [0.0646],
        [0.0763],
        [0.0210],
        [0.0084],
        [0.0289]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(OCC(F)(F)F)C=CN=C1C[S@+](O)C1=NC2=C(OS(=O)(=O)O)C=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6268    0  2209  100  4059   5310   9757 --:--:-- --:--:-- --:--:-- 15031
(1, 14)

 56%|█████▌    | 69/123 [02:19<01:45,  1.95s/it]

torch.Size([30, 1])
substrate: CC1=C(OCC(F)(F)F)C=CN=C1C[S@+](O)C1=NC2=C(OS(=O)(=O)O)C=CC=C2N1, ec: (1, 14), score: tensor([[0.0110],
        [0.0095],
        [0.2892],
        [0.6527],
        [0.4027],
        [0.0032],
        [0.0087],
        [0.0054],
        [0.0069],
        [0.0846],
        [0.1022],
        [0.0493],
        [0.0034],
        [0.3266],
        [0.6955],
        [0.2758],
        [0.0582],
        [0.0599],
        [0.0345],
        [0.2436],
        [0.7586],
        [0.5022],
        [0.0032],
        [0.0098],
        [0.0033],
        [0.2563],
        [0.0724],
        [0.0682],
        [0.0310],
        [0.1246]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=C(O)C=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5561    0  1935  100  3626   5899  11054 --:--:-- --:--:-- --:--:-- 16902
(1, 14)

 57%|█████▋    | 70/123 [02:20<01:26,  1.63s/it]

torch.Size([26, 1])
substrate: CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=C(O)C=C2N1, ec: (1, 14), score: tensor([[0.0046],
        [0.0093],
        [0.0613],
        [0.5436],
        [0.4268],
        [0.0600],
        [0.0698],
        [0.0318],
        [0.0383],
        [0.0428],
        [0.0184],
        [0.0116],
        [0.0093],
        [0.2138],
        [0.9508],
        [0.7357],
        [0.1393],
        [0.2189],
        [0.0070],
        [0.0272],
        [0.1258],
        [0.3143],
        [0.6386],
        [0.0113],
        [0.0025],
        [0.0424]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5409    0  1866  100  3543   5706  10834 --:--:-- --:--:-- --:--:-- 16490
(1, 14)

 58%|█████▊    | 71/123 [02:23<01:46,  2.04s/it]

torch.Size([25, 1])
substrate: CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=CC=C2N1, ec: (1, 14), score: tensor([[0.0046],
        [0.0011],
        [0.1028],
        [0.5024],
        [0.4019],
        [0.0365],
        [0.0135],
        [0.0137],
        [0.0093],
        [0.0370],
        [0.0190],
        [0.0802],
        [0.0228],
        [0.3264],
        [0.9919],
        [0.8766],
        [0.0196],
        [0.0444],
        [0.0028],
        [0.0621],
        [0.0182],
        [0.0294],
        [0.0369],
        [0.0046],
        [0.0261]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=NC(NC2=NC=C(C(=O)NC3=C(C)C=CC=C3Cl)S2)=CC(N2CCN(CCO)CC2)=N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7654    0  2438  100  5216   5154  11027 --:--:-- --:--:-- --:--:-- 16147
(1, 14)

 59%|█████▊    | 72/123 [02:24<01:30,  1.78s/it]

torch.Size([33, 1])
substrate: CC1=NC(NC2=NC=C(C(=O)NC3=C(C)C=CC=C3Cl)S2)=CC(N2CCN(CCO)CC2)=N1, ec: (1, 14), score: tensor([[0.0779],
        [0.0408],
        [0.0102],
        [0.0501],
        [0.2890],
        [0.1072],
        [0.0488],
        [0.0231],
        [0.0451],
        [0.2721],
        [0.0789],
        [0.2102],
        [0.0196],
        [0.1902],
        [0.2536],
        [0.4304],
        [0.1212],
        [0.1809],
        [0.0430],
        [0.1169],
        [0.0187],
        [0.3415],
        [0.0440],
        [0.2503],
        [0.3725],
        [0.2292],
        [0.0454],
        [0.2417],
        [0.7997],
        [0.8453],
        [0.1948],
        [0.2851],
        [0.0208]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5055    0  1748  100  3307   4789   9060 --:--:-- --:--:-- --:--:-- 13849
(1, 14)

 59%|█████▉    | 73/123 [02:27<01:45,  2.11s/it]

torch.Size([23, 1])
substrate: CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2, ec: (1, 14), score: tensor([[0.0966],
        [0.3729],
        [0.4305],
        [0.4072],
        [0.5281],
        [0.8355],
        [0.0921],
        [0.1889],
        [0.1253],
        [0.0246],
        [0.0819],
        [0.0961],
        [0.1138],
        [0.0955],
        [0.0445],
        [0.2829],
        [0.4053],
        [0.2659],
        [0.1814],
        [0.1226],
        [0.0944],
        [0.4998],
        [0.3730]], device='cuda:0', grad_fn=<DivBackward0>)
CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5207    0  1817  100  3390   4937   9211 --:--:-- --:--:-- --:--:-- 14111
(1, 14)

 60%|██████    | 74/123 [02:28<01:24,  1.73s/it]

torch.Size([24, 1])
substrate: CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2O, ec: (1, 14), score: tensor([[0.1649],
        [0.0952],
        [0.0956],
        [0.0495],
        [0.5111],
        [0.1662],
        [0.0130],
        [0.0212],
        [0.0274],
        [0.0274],
        [0.0357],
        [0.0102],
        [0.0275],
        [0.0395],
        [0.0239],
        [0.0786],
        [0.1055],
        [0.0708],
        [0.0253],
        [0.0112],
        [0.0109],
        [0.5832],
        [0.9935],
        [0.9793]], device='cuda:0', grad_fn=<DivBackward0>)
ClC1=CC=C2C(=C1)N=C(N1CCNCC1)C1=CC=CC=C1N2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5235    0  1679  100  3556   4587   9715 --:--:-- --:--:-- --:--:-- 14264
(1, 14)

 61%|██████    | 75/123 [02:29<01:10,  1.48s/it]

torch.Size([22, 1])
substrate: ClC1=CC=C2C(=C1)N=C(N1CCNCC1)C1=CC=CC=C1N2, ec: (1, 14), score: tensor([[0.1680],
        [0.0560],
        [0.1214],
        [0.2145],
        [0.2822],
        [0.0706],
        [0.1239],
        [0.3181],
        [0.3692],
        [0.5691],
        [0.4476],
        [0.2896],
        [0.5040],
        [0.3552],
        [0.3951],
        [0.0270],
        [0.0695],
        [0.1585],
        [0.2551],
        [0.0644],
        [0.0458],
        [0.5430]], device='cuda:0', grad_fn=<DivBackward0>)
N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N(CC(=O)O)CC(=O)O)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7269    0  2481  100  4788   5677  10956 --:--:-- --:--:-- --:--:-- 16595
(1, 14)

 62%|██████▏   | 76/123 [02:30<01:04,  1.37s/it]

torch.Size([34, 1])
substrate: N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N(CC(=O)O)CC(=O)O)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.4270],
        [0.3902],
        [0.2351],
        [0.1358],
        [0.2751],
        [0.1028],
        [0.0086],
        [0.0494],
        [0.0381],
        [0.0048],
        [0.0234],
        [0.2026],
        [0.1095],
        [0.0974],
        [0.0794],
        [0.3672],
        [0.1650],
        [0.2440],
        [0.1811],
        [0.4698],
        [0.6861],
        [0.5673],
        [0.0803],
        [0.0304],
        [0.0148],
        [0.5661],
        [0.1025],
        [0.0175],
        [0.0138],
        [0.3127],
        [0.3161],
        [0.1005],
        [0.0567],
        [0.0814]], device='cuda:0', grad_fn=<DivBackward0>)
N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7018    0  2300  100  4718   5054  10369 --:--:-- --:--:-- --:--:-- 15390
(1, 14)

 63%|██████▎   | 77/123 [02:32<01:21,  1.77s/it]

torch.Size([31, 1])
substrate: N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.4422],
        [0.3874],
        [0.1500],
        [0.1803],
        [0.0820],
        [0.0253],
        [0.0016],
        [0.0086],
        [0.0242],
        [0.0098],
        [0.0385],
        [0.3168],
        [0.4932],
        [0.3368],
        [0.2124],
        [0.5951],
        [0.0968],
        [0.2225],
        [0.3603],
        [0.2619],
        [0.4083],
        [0.4044],
        [0.4316],
        [0.0520],
        [0.3934],
        [0.4657],
        [0.2855],
        [0.1598],
        [0.0436],
        [0.0593],
        [0.0094]], device='cuda:0', grad_fn=<DivBackward0>)
N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7004    0  2369  100  4635   5206  10186 --:--:-- --:--:-- --:--:-- 15393
(1, 14)

 63%|██████▎   | 78/123 [02:33<01:09,  1.55s/it]

torch.Size([32, 1])
substrate: N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.5619],
        [0.5151],
        [0.2537],
        [0.1418],
        [0.1378],
        [0.0688],
        [0.0009],
        [0.0073],
        [0.0204],
        [0.0064],
        [0.0292],
        [0.2210],
        [0.3239],
        [0.2947],
        [0.1691],
        [0.4685],
        [0.0324],
        [0.0655],
        [0.1565],
        [0.0641],
        [0.3740],
        [0.3508],
        [0.2594],
        [0.1853],
        [0.3646],
        [0.3521],
        [0.2632],
        [0.1552],
        [0.0278],
        [0.2346],
        [0.0269],
        [0.0082]], device='cuda:0', grad_fn=<DivBackward0>)
N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(NCCO)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6509    0  2136  100  4373   5073  10387 --:--:-- --:--:-- --:--:-- 15460
(1, 14)

 64%|██████▍   | 79/123 [02:35<01:01,  1.40s/it]

torch.Size([29, 1])
substrate: N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(NCCO)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.4975],
        [0.5249],
        [0.2969],
        [0.1781],
        [0.1935],
        [0.0519],
        [0.0019],
        [0.0180],
        [0.0189],
        [0.0070],
        [0.0077],
        [0.2737],
        [0.2424],
        [0.1788],
        [0.0072],
        [0.1239],
        [0.0238],
        [0.0972],
        [0.0907],
        [0.0444],
        [0.2831],
        [0.1182],
        [0.6204],
        [0.8315],
        [0.0526],
        [0.1019],
        [0.0267],
        [0.0155],
        [0.0081]], device='cuda:0', grad_fn=<DivBackward0>)
N#CC1=CC=C2C(=C1)COC2(CCC=O)C1=CC=C(F)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4947    0  1653  100  3294   5070  10104 --:--:-- --:--:-- --:--:-- 15174
(1, 14)

 65%|██████▌   | 80/123 [02:37<01:17,  1.81s/it]

torch.Size([22, 1])
substrate: N#CC1=CC=C2C(=C1)COC2(CCC=O)C1=CC=C(F)C=C1, ec: (1, 14), score: tensor([[0.0228],
        [0.0276],
        [0.0028],
        [0.0268],
        [0.0127],
        [0.0017],
        [0.0023],
        [0.0104],
        [0.0159],
        [0.0044],
        [0.0888],
        [0.0497],
        [0.0661],
        [0.9841],
        [0.8404],
        [0.0250],
        [0.0904],
        [0.0474],
        [0.0100],
        [0.0318],
        [0.0352],
        [0.0438]], device='cuda:0', grad_fn=<DivBackward0>)
N#CC1=CC=C2C(=C1)COC2(CCCN)C1=CC=C(F)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5196    0  1653  100  3543   5086  10901 --:--:-- --:--:-- --:--:-- 15987
(1, 14)

 66%|██████▌   | 81/123 [02:38<01:04,  1.55s/it]

torch.Size([22, 1])
substrate: N#CC1=CC=C2C(=C1)COC2(CCCN)C1=CC=C(F)C=C1, ec: (1, 14), score: tensor([[0.0458],
        [0.0455],
        [0.0322],
        [0.0843],
        [0.0480],
        [0.0082],
        [0.0093],
        [0.0607],
        [0.0250],
        [0.0077],
        [0.0902],
        [0.0364],
        [0.0701],
        [0.4676],
        [0.9464],
        [0.0158],
        [0.1184],
        [0.0583],
        [0.0041],
        [0.0874],
        [0.0495],
        [0.0845]], device='cuda:0', grad_fn=<DivBackward0>)
N#CC1=CC=C2C(=C1)CO[C@@]2(CCC=O)C1=CC=C(F)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4953    0  1659  100  3294   5057  10042 --:--:-- --:--:-- --:--:-- 15100
(1, 14)

 67%|██████▋   | 82/123 [02:39<00:55,  1.37s/it]

torch.Size([22, 1])
substrate: N#CC1=CC=C2C(=C1)CO[C@@]2(CCC=O)C1=CC=C(F)C=C1, ec: (1, 14), score: tensor([[0.0272],
        [0.0136],
        [0.0103],
        [0.0496],
        [0.0803],
        [0.0016],
        [0.0018],
        [0.0147],
        [0.0119],
        [0.0081],
        [0.0077],
        [0.0041],
        [0.1156],
        [0.9899],
        [0.7547],
        [0.0106],
        [0.0491],
        [0.0308],
        [0.0250],
        [0.0498],
        [0.0202],
        [0.0285]], device='cuda:0', grad_fn=<DivBackward0>)
N#CC1=CC=C2C(=C1)CO[C@@]2(CCCN)C1=CC=C(F)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5202    0  1659  100  3543   5012  10703 --:--:-- --:--:-- --:--:-- 15716
(1, 14)

 67%|██████▋   | 83/123 [02:42<01:13,  1.84s/it]

torch.Size([22, 1])
substrate: N#CC1=CC=C2C(=C1)CO[C@@]2(CCCN)C1=CC=C(F)C=C1, ec: (1, 14), score: tensor([[0.0378],
        [0.0622],
        [0.0434],
        [0.0367],
        [0.1200],
        [0.0078],
        [0.0049],
        [0.0271],
        [0.0924],
        [0.0234],
        [0.1496],
        [0.0270],
        [0.0653],
        [0.6909],
        [0.9701],
        [0.0632],
        [0.0869],
        [0.0633],
        [0.0111],
        [0.0328],
        [0.0758],
        [0.1036]], device='cuda:0', grad_fn=<DivBackward0>)
N#CC1=NC=C(N2C(=O)C3(CCC3)N(C3=CC=C(C(N)=O)C(F)=C3)C2=S)C=C1C(F)(F)F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6423    0  2369  100  4054   5445   9319 --:--:-- --:--:-- --:--:-- 14765
(1, 14)

 68%|██████▊   | 84/123 [02:43<01:02,  1.60s/it]

torch.Size([32, 1])
substrate: N#CC1=NC=C(N2C(=O)C3(CCC3)N(C3=CC=C(C(N)=O)C(F)=C3)C2=S)C=C1C(F)(F)F, ec: (1, 14), score: tensor([[0.4917],
        [0.6472],
        [0.0545],
        [0.2314],
        [0.2228],
        [0.0640],
        [0.1776],
        [0.2339],
        [0.1363],
        [0.1524],
        [0.0573],
        [0.0084],
        [0.0821],
        [0.1523],
        [0.2375],
        [0.3480],
        [0.0373],
        [0.0342],
        [0.1165],
        [0.0554],
        [0.0660],
        [0.0926],
        [0.0717],
        [0.1326],
        [0.3067],
        [0.4951],
        [0.0764],
        [0.0037],
        [0.0995],
        [0.0432],
        [0.0545],
        [0.0823]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)CNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7336    0  2369  100  4967   5061  10613 --:--:-- --:--:-- --:--:-- 15708
(1, 14)

 69%|██████▉   | 85/123 [02:44<00:55,  1.46s/it]

torch.Size([32, 1])
substrate: NC(=O)CNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.2741],
        [0.2737],
        [0.2722],
        [0.0522],
        [0.1007],
        [0.3431],
        [0.1193],
        [0.1517],
        [0.0675],
        [0.1555],
        [0.0267],
        [0.0487],
        [0.2184],
        [0.1435],
        [0.1030],
        [0.1015],
        [0.5066],
        [0.0297],
        [0.1643],
        [0.3558],
        [0.4064],
        [0.3941],
        [0.4580],
        [0.3906],
        [0.0433],
        [0.2845],
        [0.4195],
        [0.3788],
        [0.1796],
        [0.1393],
        [0.1373],
        [0.1136]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)NCC(F)C(=O)O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2424    0   746  100  1678   2414   5430 --:--:-- --:--:-- --:--:--  7844
(1, 14)

 70%|██████▉   | 86/123 [02:47<01:02,  1.69s/it]

torch.Size([10, 1])
substrate: NC(=O)NCC(F)C(=O)O, ec: (1, 14), score: tensor([[0.3966],
        [0.7481],
        [0.3447],
        [0.7811],
        [0.4536],
        [0.6248],
        [0.2955],
        [0.6675],
        [0.0415],
        [0.0995]], device='cuda:0', grad_fn=<DivBackward0>)
NC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6465    0  2162  100  4303   4700   9354 --:--:-- --:--:-- --:--:-- 14054
(1, 14)

 71%|███████   | 87/123 [02:48<00:53,  1.48s/it]

torch.Size([29, 1])
substrate: NC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.1219],
        [0.4109],
        [0.2188],
        [0.0699],
        [0.2695],
        [0.4529],
        [0.1189],
        [0.0990],
        [0.1694],
        [0.0763],
        [0.1195],
        [0.1425],
        [0.4252],
        [0.0440],
        [0.0485],
        [0.2452],
        [0.1147],
        [0.4233],
        [0.4373],
        [0.3199],
        [0.1794],
        [0.3496],
        [0.4831],
        [0.2186],
        [0.2330],
        [0.0428],
        [0.2407],
        [0.4565],
        [0.2609]], device='cuda:0', grad_fn=<DivBackward0>)
NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4477    0  1515  100  2962   4549   8894 --:--:-- --:--:-- --:--:-- 13444
(1, 14)

 72%|███████▏  | 88/123 [02:48<00:45,  1.31s/it]

torch.Size([20, 1])
substrate: NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2, ec: (1, 14), score: tensor([[0.2970],
        [0.2535],
        [0.3672],
        [0.1511],
        [0.0320],
        [0.0816],
        [0.2842],
        [0.2434],
        [0.0534],
        [0.1018],
        [0.1375],
        [0.1881],
        [0.1364],
        [0.0700],
        [0.2077],
        [0.7225],
        [0.7195],
        [0.7764],
        [0.5596],
        [0.5216]], device='cuda:0', grad_fn=<DivBackward0>)
NC1=NC(=O)C2=C(N=CN2)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2489    0   868  100  1621   2746   5129 --:--:-- --:--:-- --:--:--  7876
(1, 14)

 72%|███████▏  | 89/123 [02:49<00:40,  1.19s/it]

torch.Size([11, 1])
substrate: NC1=NC(=O)C2=C(N=CN2)N1, ec: (1, 14), score: tensor([[0.4449],
        [0.2920],
        [0.4211],
        [0.1662],
        [0.0476],
        [0.2038],
        [0.0939],
        [0.4682],
        [0.1166],
        [0.5615],
        [0.7142]], device='cuda:0', grad_fn=<DivBackward0>)
NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](CO)[C@@H](O)[C@@H]2O)C(=O)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4495    0  1515  100  2980   4633   9113 --:--:-- --:--:-- --:--:-- 13746
(1, 14)

 73%|███████▎  | 90/123 [02:52<00:53,  1.61s/it]

torch.Size([20, 1])
substrate: NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](CO)[C@@H](O)[C@@H]2O)C(=O)N1, ec: (1, 14), score: tensor([[0.0241],
        [0.0296],
        [0.0516],
        [0.1335],
        [0.0683],
        [0.1820],
        [0.1068],
        [0.3329],
        [0.1047],
        [0.0053],
        [0.0060],
        [0.3198],
        [0.3985],
        [0.0517],
        [0.1503],
        [0.4177],
        [0.5598],
        [0.0217],
        [0.0088],
        [0.1404]], device='cuda:0', grad_fn=<DivBackward0>)
NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](COP(=O)(O)O)[C@@H](O)[C@@H]2O)C(=O)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5186    0  1791  100  3395   5427  10287 --:--:-- --:--:-- --:--:-- 15715
(1, 14)

 74%|███████▍  | 91/123 [02:53<00:46,  1.47s/it]

torch.Size([24, 1])
substrate: NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](COP(=O)(O)O)[C@@H](O)[C@@H]2O)C(=O)N1, ec: (1, 14), score: tensor([[0.0589],
        [0.0044],
        [0.0926],
        [0.0887],
        [0.0345],
        [0.0888],
        [0.0531],
        [0.1224],
        [0.0685],
        [0.0076],
        [0.0139],
        [0.0027],
        [0.0041],
        [0.0005],
        [0.0006],
        [0.0077],
        [0.0153],
        [0.2048],
        [0.1726],
        [0.2496],
        [0.2664],
        [0.0067],
        [0.0055],
        [0.1664]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(C1CCCCC1)N1CC(=O)N2CCC3=CC=CC=C3C2C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5968    0  1748  100  4220   1322   3192  0:00:01  0:00:01 --:--:--  4514
(1, 14)

 75%|███████▍  | 92/123 [02:57<01:06,  2.13s/it]

torch.Size([23, 1])
substrate: O=C(C1CCCCC1)N1CC(=O)N2CCC3=CC=CC=C3C2C1, ec: (1, 14), score: tensor([[0.2149],
        [0.5873],
        [0.2058],
        [0.1470],
        [0.1081],
        [0.0338],
        [0.0305],
        [0.1059],
        [0.5713],
        [0.4264],
        [0.5965],
        [0.2730],
        [0.2165],
        [0.1890],
        [0.1392],
        [0.0033],
        [0.1433],
        [0.1746],
        [0.3775],
        [0.2624],
        [0.0630],
        [0.4364],
        [0.5394]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(C[C@H](O)C[C@H](O)/C=C/C1=C(C2=CC=C(F)C=C2)C2=CC=CC=C2N=C1C1CC1)OC1OC(C(=O)O)C(O)C(O)C1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9711    0  3154  100  6557   6270  13035 --:--:-- --:--:-- --:--:-- 19267
(1, 14)

 76%|███████▌  | 93/123 [02:58<00:56,  1.87s/it]

torch.Size([43, 1])
substrate: O=C(C[C@H](O)C[C@H](O)/C=C/C1=C(C2=CC=C(F)C=C2)C2=CC=CC=C2N=C1C1CC1)OC1OC(C(=O)O)C(O)C(O)C1O, ec: (1, 14), score: tensor([[0.0152],
        [0.1745],
        [0.0841],
        [0.3726],
        [0.2084],
        [0.0110],
        [0.1275],
        [0.3576],
        [0.0323],
        [0.0132],
        [0.0087],
        [0.0424],
        [0.0315],
        [0.2269],
        [0.2463],
        [0.0975],
        [0.1831],
        [0.2200],
        [0.2679],
        [0.1131],
        [0.2074],
        [0.1886],
        [0.2574],
        [0.2029],
        [0.0280],
        [0.2650],
        [0.0200],
        [0.0329],
        [0.1509],
        [0.1216],
        [0.5143],
        [0.2089],
        [0.0092],
        [0.0029],
        [0.0026],
        [0.0071],
        [0.0023],
        [0.0269],
        [0.0878],
        [0.0169],
        [0.0221],
        [0.0319],
        [0.0750]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6938    0  2067  100  4871   4909  11570 --:--:-- --:--:-- --:--:-- 16440
(1, 14)

 76%|███████▋  | 94/123 [03:00<00:53,  1.85s/it]

torch.Size([28, 1])
substrate: O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O, ec: (1, 14), score: tensor([[0.0098],
        [0.1155],
        [0.0274],
        [0.2412],
        [0.7525],
        [0.6343],
        [0.0863],
        [0.3341],
        [0.6512],
        [0.2105],
        [0.4402],
        [0.0763],
        [0.1023],
        [0.0416],
        [0.0363],
        [0.0563],
        [0.1730],
        [0.4965],
        [0.2476],
        [0.3623],
        [0.1372],
        [0.1281],
        [0.0362],
        [0.0219],
        [0.0387],
        [0.1382],
        [0.5762],
        [0.1408]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([C@H]2CC[C@H](O)CC2)C1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7408    0  2205  100  5203   4651  10976 --:--:-- --:--:-- --:--:-- 15595
(1, 14)

 77%|███████▋  | 95/123 [03:02<00:52,  1.86s/it]

torch.Size([30, 1])
substrate: O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([C@H]2CC[C@H](O)CC2)C1O, ec: (1, 14), score: tensor([[0.0025],
        [0.0059],
        [0.0041],
        [0.0536],
        [0.3714],
        [0.3144],
        [0.0169],
        [0.1539],
        [0.4362],
        [0.1723],
        [0.3121],
        [0.0544],
        [0.0724],
        [0.0252],
        [0.0895],
        [0.3920],
        [0.5831],
        [0.0639],
        [0.2701],
        [0.0646],
        [0.3307],
        [0.0489],
        [0.0367],
        [0.0317],
        [0.2503],
        [0.3534],
        [0.0222],
        [0.0131],
        [0.6814],
        [0.5879]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)C[C@H](O)C[C@H](O)/C=C/C1=C(C2CC2)N=C2C=CC=CC2=C1C1=CC=C(F)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7184    0  2300  100  4884   5054  10734 --:--:-- --:--:-- --:--:-- 15754
(1, 14)

 78%|███████▊  | 96/123 [03:03<00:43,  1.60s/it]

torch.Size([31, 1])
substrate: O=C(O)C[C@H](O)C[C@H](O)/C=C/C1=C(C2CC2)N=C2C=CC=CC2=C1C1=CC=C(F)C=C1, ec: (1, 14), score: tensor([[0.0152],
        [0.0390],
        [0.0913],
        [0.1065],
        [0.4867],
        [0.4440],
        [0.0656],
        [0.5899],
        [0.5282],
        [0.1266],
        [0.0165],
        [0.0288],
        [0.0555],
        [0.0794],
        [0.1112],
        [0.2125],
        [0.1987],
        [0.0351],
        [0.1243],
        [0.1099],
        [0.1993],
        [0.1025],
        [0.0124],
        [0.0177],
        [0.0394],
        [0.2583],
        [0.2918],
        [0.1621],
        [0.1560],
        [0.2637],
        [0.2579]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)C1=CC(/N=N/C2=CC=C(O)C(C(=O)O)=C2)=CC=C1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4576    0  1627  100  2949   4960   8990 --:--:-- --:--:-- --:--:-- 13908
(1, 14)

 79%|███████▉  | 97/123 [03:04<00:36,  1.40s/it]

torch.Size([22, 1])
substrate: O=C(O)C1=CC(/N=N/C2=CC=C(O)C(C(=O)O)=C2)=CC=C1O, ec: (1, 14), score: tensor([[0.0213],
        [0.1525],
        [0.0390],
        [0.4407],
        [0.0440],
        [0.1578],
        [0.7517],
        [0.7940],
        [0.2708],
        [0.0732],
        [0.2767],
        [0.9012],
        [0.8919],
        [0.3395],
        [0.1143],
        [0.0189],
        [0.0128],
        [0.0548],
        [0.1027],
        [0.1934],
        [0.8317],
        [0.8010]], device='cuda:0', grad_fn=<DivBackward0>)
O=C(O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6396    0  2093  100  4303   1911   3929  0:00:01  0:00:01 --:--:--  5841
(1, 14)

 80%|███████▉  | 98/123 [03:06<00:44,  1.80s/it]

torch.Size([28, 1])
substrate: O=C(O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1, ec: (1, 14), score: tensor([[0.0136],
        [0.2472],
        [0.1400],
        [0.2943],
        [0.3463],
        [0.2709],
        [0.1155],
        [0.0890],
        [0.2623],
        [0.3724],
        [0.3401],
        [0.2762],
        [0.6716],
        [0.2430],
        [0.1390],
        [0.2571],
        [0.3415],
        [0.4581],
        [0.3552],
        [0.4145],
        [0.0229],
        [0.4067],
        [0.5724],
        [0.3259],
        [0.2145],
        [0.2426],
        [0.3042],
        [0.4090]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CC(=O)N(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4394    0  1515  100  2879   4482   8517 --:--:-- --:--:-- --:--:-- 13000
(1, 14)

 80%|████████  | 99/123 [03:07<00:37,  1.54s/it]

torch.Size([20, 1])
substrate: O=C1CC(=O)N(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1, ec: (1, 14), score: tensor([[0.4859],
        [0.8141],
        [0.5449],
        [0.8752],
        [0.3722],
        [0.6395],
        [0.1931],
        [0.1476],
        [0.1162],
        [0.0913],
        [0.0879],
        [0.1055],
        [0.2213],
        [0.1410],
        [0.0506],
        [0.0378],
        [0.1274],
        [0.0378],
        [0.0928],
        [0.6193]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CC(O)CC(/C=C/C2=C(C3=CC=C(F)C=C3)C3=CC=CC=C3N=C2C2CC2)O1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6905    0  2257  100  4648   4731   9744 --:--:-- --:--:-- --:--:-- 14475
(1, 14)

 81%|████████▏ | 100/123 [03:09<00:33,  1.44s/it]

torch.Size([30, 1])
substrate: O=C1CC(O)CC(/C=C/C2=C(C3=CC=C(F)C=C3)C3=CC=CC=C3N=C2C2CC2)O1, ec: (1, 14), score: tensor([[0.0650],
        [0.2353],
        [0.1225],
        [0.3416],
        [0.1701],
        [0.0061],
        [0.1065],
        [0.2199],
        [0.2819],
        [0.1116],
        [0.0456],
        [0.1398],
        [0.4438],
        [0.3751],
        [0.2520],
        [0.2063],
        [0.3535],
        [0.4291],
        [0.0274],
        [0.3306],
        [0.3665],
        [0.2815],
        [0.1678],
        [0.0392],
        [0.2529],
        [0.0626],
        [0.0985],
        [0.2063],
        [0.2019],
        [0.1426]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CN=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4242    0  1446  100  2796   4355   8421 --:--:-- --:--:-- --:--:-- 12815
(1, 14)

 82%|████████▏ | 101/123 [03:11<00:39,  1.79s/it]

torch.Size([19, 1])
substrate: O=C1CN=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1, ec: (1, 14), score: tensor([[0.4088],
        [0.9188],
        [0.8270],
        [0.7869],
        [0.2878],
        [0.0122],
        [0.0414],
        [0.0894],
        [0.1382],
        [0.1049],
        [0.0525],
        [0.0511],
        [0.0950],
        [0.0121],
        [0.0125],
        [0.1676],
        [0.0379],
        [0.0310],
        [0.6123]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CN=C(C2=CC=CC=C2Cl)C2=CC([N+](=O)[O-])=CC=C2N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4641    0  1653  100  2988   2915   5269 --:--:-- --:--:-- --:--:--  8185
(1, 14)

 83%|████████▎ | 102/123 [03:12<00:33,  1.58s/it]

torch.Size([22, 1])
substrate: O=C1CN=C(C2=CC=CC=C2Cl)C2=CC([N+](=O)[O-])=CC=C2N1, ec: (1, 14), score: tensor([[0.3826],
        [0.6048],
        [0.3138],
        [0.5794],
        [0.3269],
        [0.0864],
        [0.1331],
        [0.1412],
        [0.3171],
        [0.1029],
        [0.1029],
        [0.1482],
        [0.0867],
        [0.0384],
        [0.3854],
        [0.8148],
        [0.4697],
        [0.4342],
        [0.2178],
        [0.1009],
        [0.0772],
        [0.2995]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1CN=C(C2=CC=CC=C2F)C2=CC(Cl)=CC=C2N1CC(F)(F)F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5154    0  1860  100  3294   1337   2368  0:00:01  0:00:01 --:--:--  3705
(1, 14)

 84%|████████▎ | 103/123 [03:16<00:45,  2.26s/it]

torch.Size([25, 1])
substrate: O=C1CN=C(C2=CC=CC=C2F)C2=CC(Cl)=CC=C2N1CC(F)(F)F, ec: (1, 14), score: tensor([[0.6523],
        [0.8679],
        [0.6712],
        [0.6428],
        [0.1752],
        [0.0457],
        [0.1697],
        [0.2120],
        [0.2350],
        [0.1409],
        [0.1075],
        [0.0306],
        [0.0174],
        [0.0210],
        [0.0031],
        [0.0868],
        [0.0845],
        [0.0940],
        [0.1059],
        [0.7862],
        [0.2484],
        [0.1721],
        [0.0770],
        [0.0456],
        [0.0739]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NCC(F)C(=O)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2144    0   702  100  1442   2257   4636 --:--:-- --:--:-- --:--:--  6893
(1, 14)

 85%|████████▍ | 104/123 [03:17<00:35,  1.89s/it]

torch.Size([9, 1])
substrate: O=C1NCC(F)C(=O)N1, ec: (1, 14), score: tensor([[0.1360],
        [0.2045],
        [0.9191],
        [0.5245],
        [0.8559],
        [0.4606],
        [0.5030],
        [0.3961],
        [0.4008]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC2=CC=C([N+](=O)[O-])C=C2C(C2=CC=CC=C2Cl)=NC1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4793    0  1722  100  3071   5064   9032 --:--:-- --:--:-- --:--:-- 14097
(1, 14)

 85%|████████▌ | 105/123 [03:18<00:28,  1.61s/it]

torch.Size([23, 1])
substrate: O=C1NC2=CC=C([N+](=O)[O-])C=C2C(C2=CC=CC=C2Cl)=NC1O, ec: (1, 14), score: tensor([[0.0726],
        [0.5178],
        [0.1936],
        [0.0108],
        [0.0626],
        [0.0410],
        [0.1567],
        [0.6845],
        [0.2909],
        [0.4313],
        [0.0267],
        [0.0135],
        [0.0672],
        [0.0195],
        [0.0430],
        [0.0460],
        [0.1255],
        [0.1315],
        [0.0295],
        [0.0892],
        [0.5466],
        [0.9783],
        [0.9140]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1C2=CC=CC(O)=C2C(=O)C2=C(O)C3=C(C(O)=C12)C[C@@](O)(C(O)CO)CC3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6234    0  2097  100  4137   4461   8802 --:--:-- --:--:-- --:--:-- 13292
(1, 14)

 86%|████████▌ | 106/123 [03:21<00:34,  2.00s/it]

torch.Size([28, 1])
substrate: O=C1C2=CC=CC(O)=C2C(=O)C2=C(O)C3=C(C(O)=C12)C[C@@](O)(C(O)CO)CC3, ec: (1, 14), score: tensor([[0.0083],
        [0.0565],
        [0.0141],
        [0.0953],
        [0.0052],
        [0.0032],
        [0.0281],
        [0.1408],
        [0.0099],
        [0.0148],
        [0.0091],
        [0.0750],
        [0.4160],
        [0.3630],
        [0.0105],
        [0.0028],
        [0.4253],
        [0.2964],
        [0.0519],
        [0.0616],
        [0.1170],
        [0.0812],
        [0.5629],
        [0.4400],
        [0.5335],
        [0.6332],
        [0.0321],
        [0.0104]], device='cuda:0', grad_fn=<DivBackward0>)
O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4314    0  1282  100  3032   4044   9564 --:--:-- --:--:-- --:--:-- 13608
(1, 14)

 87%|████████▋ | 107/123 [03:22<00:27,  1.69s/it]

torch.Size([17, 1])
substrate: O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1, ec: (1, 14), score: tensor([[0.8251],
        [0.9207],
        [0.6892],
        [0.0143],
        [0.0063],
        [0.2010],
        [0.0652],
        [0.2469],
        [0.0086],
        [0.0132],
        [0.9824],
        [0.6460],
        [0.8219],
        [0.2806],
        [0.0177],
        [0.1020],
        [0.2889]], device='cuda:0', grad_fn=<DivBackward0>)
O=S1(=O)CCNCN1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2241    0   633  100  1608   2117   5377 --:--:-- --:--:-- --:--:--  7470
(1, 14)

 88%|████████▊ | 108/123 [03:23<00:21,  1.45s/it]

torch.Size([8, 1])
substrate: O=S1(=O)CCNCN1, ec: (1, 14), score: tensor([[0.9277],
        [0.9963],
        [0.9322],
        [0.0562],
        [0.1213],
        [0.1866],
        [0.1235],
        [0.5530]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)C2=C(N=CN2)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2406    0   868  100  1538   2773   4913 --:--:-- --:--:-- --:--:--  7686
(1, 14)

 89%|████████▊ | 109/123 [03:25<00:23,  1.71s/it]

torch.Size([11, 1])
substrate: O=C1NC(=O)C2=C(N=CN2)N1, ec: (1, 14), score: tensor([[0.2490],
        [0.2294],
        [0.7889],
        [0.1402],
        [0.0389],
        [0.0778],
        [0.0919],
        [0.3472],
        [0.1789],
        [0.5459],
        [0.8208]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2CC(O)C(CO)O2)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3899    0  1282  100  2617   4069   8307 --:--:-- --:--:-- --:--:-- 12417
(1, 14)

 89%|████████▉ | 110/123 [03:26<00:19,  1.52s/it]

torch.Size([17, 1])
substrate: O=C1NC(=O)N(C2CC(O)C(CO)O2)C=C1F, ec: (1, 14), score: tensor([[0.0059],
        [0.0070],
        [0.0313],
        [0.0271],
        [0.0120],
        [0.9001],
        [0.9179],
        [0.5720],
        [0.1669],
        [0.1334],
        [0.0063],
        [0.0669],
        [0.1515],
        [0.0280],
        [0.1179],
        [0.0435],
        [0.0168]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)O)O2)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4590    0  1558  100  3032   4946   9625 --:--:-- --:--:-- --:--:-- 14571
(1, 14)

 90%|█████████ | 111/123 [03:27<00:16,  1.37s/it]

torch.Size([21, 1])
substrate: O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)O)O2)C=C1F, ec: (1, 14), score: tensor([[0.0038],
        [0.0174],
        [0.0590],
        [0.0484],
        [0.0305],
        [0.3849],
        [0.2884],
        [0.1168],
        [0.0257],
        [0.0288],
        [0.0074],
        [0.0093],
        [0.0172],
        [0.0019],
        [0.0020],
        [0.0516],
        [0.0475],
        [0.0145],
        [0.0724],
        [0.0680],
        [0.0594]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)O)O2)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5281    0  1834  100  3447   5840  10977 --:--:-- --:--:-- --:--:-- 16818
(1, 14)

 91%|█████████ | 112/123 [03:30<00:19,  1.81s/it]

torch.Size([25, 1])
substrate: O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)O)O2)C=C1F, ec: (1, 14), score: tensor([[5.4530e-03],
        [2.4936e-03],
        [9.6180e-03],
        [5.3911e-03],
        [6.6691e-03],
        [4.1791e-01],
        [3.5141e-01],
        [2.0358e-01],
        [1.7716e-01],
        [4.1406e-02],
        [8.3439e-02],
        [9.9347e-02],
        [1.1358e-01],
        [5.9941e-03],
        [1.4385e-03],
        [2.0661e-03],
        [1.3572e-03],
        [8.3037e-05],
        [3.8626e-04],
        [3.4963e-03],
        [9.2588e-03],
        [3.8024e-02],
        [1.0999e-02],
        [4.2893e-03],
        [3.1332e-03]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O2)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5972    0  2110  100  3862   4988   9130 --:--:-- --:--:-- --:--:-- 14151
(1, 14)

 92%|█████████▏| 113/123 [03:31<00:16,  1.63s/it]

torch.Size([29, 1])
substrate: O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O2)C=C1F, ec: (1, 14), score: tensor([[0.0068],
        [0.0068],
        [0.0188],
        [0.0052],
        [0.0022],
        [0.3883],
        [0.4715],
        [0.2242],
        [0.1240],
        [0.0234],
        [0.0414],
        [0.0017],
        [0.0093],
        [0.0009],
        [0.0007],
        [0.0006],
        [0.0056],
        [0.0019],
        [0.0114],
        [0.0040],
        [0.0081],
        [0.0108],
        [0.0023],
        [0.0606],
        [0.0802],
        [0.0253],
        [0.0355],
        [0.0263],
        [0.0057]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2OC(CO)C(O)C2O)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4051    0  1351  100  2700   4358   8709 --:--:-- --:--:-- --:--:-- 13067
(1, 14)

 93%|█████████▎| 114/123 [03:32<00:12,  1.40s/it]

torch.Size([18, 1])
substrate: O=C1NC(=O)N(C2OC(CO)C(O)C2O)C=C1F, ec: (1, 14), score: tensor([[6.2038e-03],
        [3.6961e-02],
        [9.9912e-02],
        [8.8113e-02],
        [3.1322e-02],
        [7.7410e-01],
        [4.2409e-01],
        [2.4720e-03],
        [4.7246e-04],
        [2.4947e-02],
        [1.1244e-01],
        [9.1704e-03],
        [3.1514e-02],
        [4.8805e-01],
        [5.3248e-01],
        [2.7946e-01],
        [1.1433e-01],
        [9.6841e-02]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2OC(COP(=O)(O)O)C(O)C2O)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4742    0  1627  100  3115   5084   9734 --:--:-- --:--:-- --:--:-- 14818
(1, 14)

 93%|█████████▎| 115/123 [03:36<00:16,  2.00s/it]

torch.Size([22, 1])
substrate: O=C1NC(=O)N(C2OC(COP(=O)(O)O)C(O)C2O)C=C1F, ec: (1, 14), score: tensor([[0.0133],
        [0.0554],
        [0.1280],
        [0.0270],
        [0.0064],
        [0.3224],
        [0.3321],
        [0.0209],
        [0.0074],
        [0.0021],
        [0.0139],
        [0.0009],
        [0.0009],
        [0.0092],
        [0.0295],
        [0.0316],
        [0.0698],
        [0.2597],
        [0.1828],
        [0.0461],
        [0.1121],
        [0.0427]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC(=O)N(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)C=C1F
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5433    0  1903  100  3530   6178  11461 --:--:-- --:--:-- --:--:-- 17639
(1, 14)

 94%|█████████▍| 116/123 [03:37<00:11,  1.71s/it]

torch.Size([26, 1])
substrate: O=C1NC(=O)N(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)C=C1F, ec: (1, 14), score: tensor([[8.7727e-03],
        [3.7126e-03],
        [3.4608e-02],
        [5.1323e-03],
        [5.0846e-03],
        [3.3835e-01],
        [3.0997e-01],
        [7.8296e-03],
        [8.0421e-03],
        [3.6622e-02],
        [4.9334e-02],
        [1.4901e-02],
        [9.2610e-04],
        [2.3082e-03],
        [6.0748e-03],
        [1.3656e-03],
        [1.5203e-04],
        [4.6426e-02],
        [1.2984e-02],
        [2.6112e-02],
        [1.7530e-02],
        [2.4433e-01],
        [2.0342e-01],
        [4.8857e-02],
        [1.1775e-02],
        [7.5320e-03]], device='cuda:0', grad_fn=<DivBackward0>)
O=C1NC=C(F)C(=O)N1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1978    0   702  100  1276   2309   4197 --:--:-- --:--:-- --:--:--  6506
(1, 14)

 95%|█████████▌| 117/123 [03:38<00:09,  1.51s/it]

torch.Size([9, 1])
substrate: O=C1NC=C(F)C(=O)N1, ec: (1, 14), score: tensor([[0.0534],
        [0.1164],
        [0.9401],
        [0.3063],
        [0.5399],
        [0.1436],
        [0.0833],
        [0.0222],
        [0.1942]], device='cuda:0', grad_fn=<DivBackward0>)
OC(Cl)(Cl)C(C1=CC=C(Cl)C=C1)C1=CC=CC=C1Cl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4120    0  1420  100  2700   4507   8571 --:--:-- --:--:-- --:--:-- 13079
(1, 14)

 96%|█████████▌| 118/123 [03:40<00:09,  1.87s/it]

torch.Size([19, 1])
substrate: OC(Cl)(Cl)C(C1=CC=C(Cl)C=C1)C1=CC=CC=C1Cl, ec: (1, 14), score: tensor([[0.6934],
        [0.8035],
        [0.2404],
        [0.3457],
        [0.5196],
        [0.0117],
        [0.5490],
        [0.5376],
        [0.2230],
        [0.2805],
        [0.4738],
        [0.4993],
        [0.1937],
        [0.5617],
        [0.2398],
        [0.3730],
        [0.3111],
        [0.3929],
        [0.5556]], device='cuda:0', grad_fn=<DivBackward0>)
OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=CC=CC=C3)(CC1)CC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8223    0  2395  100  5828   4927  11991 --:--:-- --:--:-- --:--:-- 16919
(1, 14)

 97%|█████████▋| 119/123 [03:41<00:06,  1.65s/it]

torch.Size([32, 1])
substrate: OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=CC=CC=C3)(CC1)CC2, ec: (1, 14), score: tensor([[0.8854],
        [0.9300],
        [0.0738],
        [0.1043],
        [0.0744],
        [0.0153],
        [0.0867],
        [0.1474],
        [0.0986],
        [0.1684],
        [0.0744],
        [0.0290],
        [0.1072],
        [0.1415],
        [0.0479],
        [0.1098],
        [0.4083],
        [0.5399],
        [0.3741],
        [0.5970],
        [0.5558],
        [0.5812],
        [0.0210],
        [0.0877],
        [0.1333],
        [0.2077],
        [0.1181],
        [0.0855],
        [0.2839],
        [0.1239],
        [0.2898],
        [0.0580]], device='cuda:0', grad_fn=<DivBackward0>)
OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC4)C=C3)=C2)[C@H](O)[C@@H](O)[C@@H]1O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7751    0  2369  100  5382   5172  11751 --:--:-- --:--:-- --:--:-- 16923
(1, 14)

 98%|█████████▊| 120/123 [03:43<00:04,  1.49s/it]

torch.Size([32, 1])
substrate: OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC4)C=C3)=C2)[C@H](O)[C@@H](O)[C@@H]1O, ec: (1, 14), score: tensor([[0.2679],
        [0.1574],
        [0.0108],
        [0.0008],
        [0.0268],
        [0.0671],
        [0.1041],
        [0.0254],
        [0.0023],
        [0.0062],
        [0.0079],
        [0.0187],
        [0.0029],
        [0.1322],
        [0.1506],
        [0.2596],
        [0.1813],
        [0.1212],
        [0.1200],
        [0.0613],
        [0.0027],
        [0.0125],
        [0.0153],
        [0.0962],
        [0.0967],
        [0.0285],
        [0.2291],
        [0.2758],
        [0.1432],
        [0.1009],
        [0.0498],
        [0.1028]], device='cuda:0', grad_fn=<DivBackward0>)
OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5207    0  1817  100  3390   4950   9237 --:--:-- --:--:-- --:--:-- 14149
(1, 14)

 98%|█████████▊| 121/123 [03:45<00:03,  1.84s/it]

torch.Size([24, 1])
substrate: OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2, ec: (1, 14), score: tensor([[0.9624],
        [0.9831],
        [0.3073],
        [0.1678],
        [0.0348],
        [0.1267],
        [0.2230],
        [0.0170],
        [0.0405],
        [0.0459],
        [0.0057],
        [0.0448],
        [0.0431],
        [0.0087],
        [0.1007],
        [0.0708],
        [0.2106],
        [0.1359],
        [0.1746],
        [0.1039],
        [0.0905],
        [0.0431],
        [0.2630],
        [0.1094]], device='cuda:0', grad_fn=<DivBackward0>)
OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=CC=C4)(CC2)CC3)C=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8375    0  2464  100  5911   4947  11869 --:--:-- --:--:-- --:--:-- 16817
(1, 14)

 99%|█████████▉| 122/123 [03:46<00:01,  1.65s/it]

torch.Size([33, 1])
substrate: OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=CC=C4)(CC2)CC3)C=C1, ec: (1, 14), score: tensor([[0.8272],
        [0.5704],
        [0.2418],
        [0.0238],
        [0.0054],
        [0.5217],
        [0.7458],
        [0.5693],
        [0.0570],
        [0.4404],
        [0.3916],
        [0.0441],
        [0.0470],
        [0.8608],
        [0.8554],
        [0.0460],
        [0.2163],
        [0.1941],
        [0.0818],
        [0.2473],
        [0.1749],
        [0.0440],
        [0.1898],
        [0.1895],
        [0.1014],
        [0.1286],
        [0.1132],
        [0.1617],
        [0.3347],
        [0.1602],
        [0.2943],
        [0.0315],
        [0.2196]], device='cuda:0', grad_fn=<DivBackward0>)
C1=CN=C(N2CCNCC2)N=C1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3222    0   937  100  2285   3012   7347 --:--:-- --:--:-- --:--:-- 10360
(1, 14)

100%|██████████| 123/123 [03:47<00:00,  1.85s/it]

torch.Size([12, 1])
substrate: C1=CN=C(N2CCNCC2)N=C1, ec: (1, 14), score: tensor([[0.3050],
        [0.1364],
        [0.3661],
        [0.3512],
        [0.5289],
        [0.5266],
        [0.4213],
        [0.3062],
        [0.3807],
        [0.3642],
        [0.3995],
        [0.2873]], device='cuda:0', grad_fn=<DivBackward0>)

In [3]:
import torch
atom_scores_list_new = []
# 假设 scores 是你的 torch 张量，大小是 [14, 1]
for i in atom_scores_list:
    scores = i  # 示例：14个原子的反应分数，实际使用时替换为你的数据

    # 创建一个空字典来存储原子序号和对应的分数
    atom_scores = {}

    # 将分数映射到原子序号
    for idx, score in enumerate(scores):
        atom_scores[idx] = score.item()  # 使用 item() 将张量转换为标量

# 打印结果
    atom_scores_list_new.append(atom_scores)

In [4]:
df_new['score'] = atom_scores_list_new

In [5]:
df_new

,substrate,ec,score
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,"(1, 14)","{0: 0.00403987243771553, 1: 0.0116602797061204..."
1,CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2,"(1, 14)","{0: 0.11337683349847794, 1: 0.4291064441204071..."
2,CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=C...,"(1, 14)","{0: 0.1749592274427414, 1: 0.48370441794395447..."
3,CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=...,"(1, 14)","{0: 0.19561421871185303, 1: 0.083653524518013,..."
4,CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=C...,"(1, 14)","{0: 0.23840060830116272, 1: 0.2645083367824554..."
...,...,...,...
118,OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=C...,"(1, 14)","{0: 0.8853639960289001, 1: 0.9299560785293579,..."
119,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC...,"(1, 14)","{0: 0.2678848206996918, 1: 0.15740716457366943..."
120,OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2,"(1, 14)","{0: 0.9624060988426208, 1: 0.9830583930015564,..."
121,OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=...,"(1, 14)","{0: 0.8271753191947937, 1: 0.5703520178794861,..."
122,C1=CN=C(N2CCNCC2)N=C1,"(1, 14)","{0: 0.3049726188182831, 1: 0.1364114135503769,..."

In [6]:
df_new.to_pickle('gnnsom_results_drugbank.pickle')