In [1]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [6]:
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/metapredictor/metapredictor_som.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict'].to_list()
predicts = [i.split('|') for i in predicts]

In [7]:
predicts

[['C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/[OH:1])CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/[C:1](=N/[OH:1])CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3C[CH2:1]C4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/[C:1](=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CC[C:1]4=[CH:1]/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=[N:1]/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3C[CH2:1][C@@:1]21CC',
  'C#C[C@@]1([O:1]C(C)=O)[C@@]2(CC)CC[C@H]3[C@@H](CCC4=C\\C(=N/O)CC[C@@H]43)[C@@H]2C1',
  'C#C[C@@]1([O:1]C(C)=O)[C@@]2(CC)CC[C@H]3[C@@H](CCC4=C\\C(=N\\O)CC[C@@H]43)[C@@H]2C1'],
 ['CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[CH3:1]',
  'CC(C)(O)c1cc[cH:1]cc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'C[C:1](O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[CH3:1]',
  'CC(C)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[OH:1]',
  'C[C:1](C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)[cH:1]1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3c[cH:1]c(Cl)cc3n2)c1',
  'CC(C)(O)c1c(CC[C@@H](SCC2(CC(=O)O)CC2)c2cccc(/C=C/c3ccc4ccc(Cl)cc4n3)c2)ccc[cH:1]1'],
 ['CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)cc1',
  'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CC[CH2:1]C2)cc1',
  'CC(CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]',
  'CC(C)C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'C[CH:1](C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C)[CH2:1]NCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]',
  'CC(C)CNCc1ccc(-c2cc[cH:1]cc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)[N:1]2CCCC2)cc1',
  'C[CH:1](CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]'],
 ['CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C',
  'CC(CN1c2ccccc2Sc2cc[cH:1]cc21)N(C)C',
  'CC(CN1c2ccccc2[S:1]c2ccccc21)N(C)C',
  'CC(CN1c2cc[cH:1]cc2Sc2ccccc21)N(C)C',
  'CC(CN1c2ccccc2S[c:1]2[cH:1][cH:1][cH:1][cH:1][c:1]21)N(C)C',
  'CC(CN1c2ccccc2Sc2ccc[cH:1]c21)N(C)C',
  'CC(CN1c2ccccc2Sc2ccccc21)[N:1](C)C',
  'CC(CN1c2ccccc2Sc2c1ccc[cH:1]2)N(C)C',
  'CC(C[N:1]1c2ccccc2Sc2ccccc21)N(C)C',
  'CN(C)C(CN1c2ccccc2Sc2ccccc21)[CH3:1]'],
 ['CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)[cH:1]c2)C1',
  'CC1([CH3:1])CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)c[cH:1]2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH][cH:1]cc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)[CH2:1]1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc([NH:1]CC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c([O:1]c4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+:1](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(C[N:1]2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2cc[c:1](Cl)cc2)C1'],
 ['CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc([OH:1])cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1([CH3:1])S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H:1](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)[cH:1]c3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H]([NH:1]C(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)[OH:1]',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@@H](c3ccc(O)cc3)[NH2:1])C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)[N:1]2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@@H:1](c3ccc(O)cc3)[NH2:1])C(=O)N2[C@H]1C(=O)O',
  'C[C:1]1([CH3:1])S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O'],
 ['CCC1(c2ccccc2)C(=O)NC(=O)[NH:1]C1=O',
  'CCC1(c2cc[cH:1]cc2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)N[C:1]1=[O:1]',
  'CCC1(c2ccccc2)C(=O)[NH:1]C(=O)NC1=O',
  'O=C1NC(=O)C(C[CH3:1])(c2ccccc2)C(=O)N1',
  'C[CH2:1]C1(c2ccccc2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)[NH:1][C:1]1=[O:1]',
  'CCC1(c2ccc[cH:1]c2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)[NH:1][C:1]1=O',
  'CCC1(c2ccccc2)C(=O)N[C:1](=[O:1])NC1=O'],
 ['CCC1C(C(=O)c2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c([OH:1])c(Br)c1',
  'CCC1Oc2ccccc2[CH:1]1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1C(C(=O)[c:1]2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'CCC1Oc2cc[cH:1]cc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)[c:1](Br)c1',
  'CCC1Oc2c[cH:1]ccc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CC[CH:1]1C(C(=O)c2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'C[CH2:1]C1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)[cH:1]1'],
 ['CCCCCCCCc1ccc(CCC(N)(CO)C[OH:1])cc1',
  'CCCCCCCCc1ccc(CCC(CO)(CO)[NH2:1])cc1',
  'CCCCCCCCc1ccc(CCC(CO)(C[OH:1])[NH2:1])cc1',
  'C[CH2:1]CCCCCCc1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCC[CH2:1]c1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCCCc1ccc(CCC(N)(C[OH:1])C[OH:1])cc1',
  'CC[CH2:1]CCCCCc1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCC[CH2:1][CH2:1]c1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCCCc1ccc(CCC(N)(CO)[CH2:1]O)cc1',
  'CCCCCCCCc1ccc(CC[C:1](N)(CO)C[OH:1])cc1'],
 ['CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCC[O:1]C)cc1',
  'CCCC[NH:1]c1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCC[O:1]CCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCC[O:1]CCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)[O:1]CCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCC[O:1]CCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOC[CH2:1][O:1]C)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCC[O:1]CCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCC[O:1]CCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCO[CH3:1])cc1'],
 ['CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCC[N:1](CC)CC)c(I)c1',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c(CC[CH2:1]C)oc3ccccc23)cc1I',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)[cH:1]1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)[c:1](I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)C[CH3:1])c(I)c1',
  'CCCCc1oc2c[cH:1]ccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)[CH2:1]C)c(I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OC[CH2:1]N(CC)CC)c(I)c1',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c(CCC[CH3:1])oc3ccccc23)cc1I',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c([CH2:1]CCC)oc3ccccc23)cc1I'],
 ['CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H]([O:1]CCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1]O)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1][OH:1])[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCC[OH:1])[C@@H](O)[C@H]3O)c2n1',
  'CCC[S:1]c1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'C[CH2:1]CSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nn[n:1]([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CC[CH2:1]Sc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc([NH:1][C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1]O)[C@@H]([OH:1])[C@H]3O)c2n1'],
 ['CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H]([S:1]C)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)[N:1](C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H]([OH:1])[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2[OH:1])N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H]([OH:1])[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H]([C:1](=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)[CH2:1]1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](S[CH3:1])[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)[NH:1]C(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H:1](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1'],
 ['CCN(CC)CCNC(=O)c1cc(Cl)c([NH2:1])cc1OC',
  'CCN(CC)CCNC(=O)c1cc(Cl)c(N)[cH:1]c1OC',
  'CC[N:1](CC)CCNC(=O)c1cc(Cl)c(N)cc1OC',
  'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1[O:1]C',
  'CCN(CC)CC[NH:1]C(=O)c1cc(Cl)c(N)cc1OC',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1[O:1]C)CC',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1OC)[CH2:1]C',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1OC)C[CH3:1]',
  'COc1cc(N)c(Cl)cc1C(=O)NCCN(C[CH3:1])CC',
  'CCN(CC)CCNC(=O)c1c(OC)cc(N)c(Cl)[cH:1]'],
 ['CCN(CC)CCOC(=O)c1ccc([NH2:1])cc1',
  'CC[N:1](CC)CCOC(=O)c1ccc(N)cc1',
  'CCN(CC)CC[O:1]C(=O)c1ccc(N)cc1',
  'CCN(CC)CCOC(=O)c1ccc(N)[cH:1]c1',
  'CCN(CC)C[CH2:1][O:1]C(=O)c1ccc(N)cc1',
  'CC[N:1](CC)CC[O:1]C(=O)c1ccc(N)cc1',
  'CCN(CC)[CH2:1]COC(=O)c1ccc(N)cc1',
  'CCN(CC)C[CH2:1]OC(=O)c1ccc(N)cc1',
  'CC[N:1](CC)CCOC(=O)c1cc[c:1](N)cc1',
  'CCN(CCOC(=O)c1ccc(N)cc1)[CH2:1]C'],
 ['CC[N:1](c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCO[CH2:1]C1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CC[O:1]CC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc([CH3:1])[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOC[CH2:1]3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc([CH2:1]N3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH:1]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCO[CH2:1]C3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(C[N:1]3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CC[O:1][CH2:1]C3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1'],
 ['CC[NH:1][C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(=O)(=O)[NH2:1])cc21',
  'C[C@H]1C[C@H](N[CH2:1]C)c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'C[C@@H]1C[C@H](N[CH2:1]C)c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc([S:1](N)(=O)=O)cc21',
  'CCN[C@H]1C[C@H]([CH3:1])S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'CCN[C@H:1]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'C[C@H]1C[C@H](NC[CH3:1])c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'NS(=O)(=O)c1cc2c(s1)S(=O)(=O)[C@@H](C)C[C@@H]2N[CH2:1][CH3:1]',
  'C[CH2:1]N[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21'],
 ['CCOC(=O)Nc1ccc2c(c1)N(C(=O)C[N:1](CC)CC)c1ccccc1CC2',
  'CCOC(=O)[NH:1]c1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1cc[cH:1]cc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)C[CH3:1])c1ccccc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1[CH2:1]C2',
  'CCOC(=O)Nc1cc2c(c[cH:1]1)CCc1ccccc1N2C(=O)CN(CC)CC',
  'CCN(CC)CC(=O)N1c2ccccc2CCc2ccc(NC(=O)[O:1]CC)cc21',
  'CCOC(=O)Nc1ccc2c(c1)[N:1](C(=O)CN(CC)CC)c1ccccc1CC2',
  'CCN(CC)CC(=O)N1c2ccccc2CCc2ccc(NC(=O)OC[CH3:1])cc21',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccc[cH:1]c1CC2'],
 ['CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c([OH:1])c(CN(C)C)c12',
  'CCOC(=O)c1c(C[S:1]c2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CC[O:1]C(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(C[N:1](C)C)c12',
  'CCOC(=O)c1c([CH2:1]Sc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2cc[cH:1]cc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CC[O:1]C(=O)c1c(C[S:1]c2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)[n:1](C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2cccc[cH:1]2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)[CH3:1])c12'],
 ['CN(C)C(=O)C[O:1]C(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'C[N:1](C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)[C:1](=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)[C:1](=O)C[O:1]C(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(N[C:1](=[NH:1])[NH2:1])cc2)cc1',
  'CN(C)C(=O)COC(=O)Cc1ccc([O:1]C(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)C(=O)COC(=O)[CH2:1]c1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'C[N:1](C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(N[C:1](=[NH:1])[NH2:1])cc2)cc1',
  'CN(C)[C:1](=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(N)=[NH:1])cc2)cc1',
  'CN(C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(N)=[NH:1])cc2)cc1)[CH3:1]'],
 ['C[N:1](C)CCCN1c2ccccc2CCc2ccccc21',
  'CN(C)CCCN1c2ccccc2CCc2c[cH:1]ccc21',
  'CN(C)CCCN1c2ccccc2C[CH2:1]c2ccccc21',
  'CN(C)CCCN1c2cc[cH:1]cc2CCc2ccccc21',
  'CN(C)[CH2:1]CCN1c2ccccc2CCc2ccccc21',
  'CN(C)CCCN1c2c[cH:1]ccc2CCc2ccccc21',
  'CN(C)CCCN1c2ccccc2[CH2:1]Cc2ccccc21',
  'CN(C)CCCN1c2ccccc2CC[c:1]2[cH:1][cH:1][cH:1][cH:1][c:1]21',
  'CN(C)CCCN1c2ccccc2CCc2cc[cH:1]cc21',
  'CN(C)CCCN1c2ccc[cH:1]c2CCc2ccccc21'],
 ['CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1c[cH:1]c(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc([OH:1])c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1c[cH:1]c(O)c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1[C:1]2=[O:1]',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1C2=O',
  'CN(C)c1ccc([OH:1])c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1[CH2:1][C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C([OH:1])=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1[C:1]2=O'],
 ['CN1CCc2cccc3c2[C@H]1Cc1ccc([OH:1])c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c([OH:1])c1-3',
  'C[N:1]1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1C[c:1]1[cH:1][cH:1][c:1]([OH:1])[c:1]([OH:1])[c:1]1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)[c:1](O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1cc[c:1](O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1c[cH:1]c(O)c(O)c1-3',
  'C[N:1]1[CH2:1][CH2:1][c:1]2cccc3[c:1]2[C@H:1]1Cc1ccc(O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1[CH2:1]c1ccc(O)c(O)c1-3',
  'CN1CCc2c[cH:1]cc3c2[C@H]1Cc1ccc(O)c(O)c1-3'],
 ['CN1c2ccccc2C(=O)N2CCc3c([nH]c4cc[cH:1]cc34)C21',
  'CN1c2ccccc2C(=O)N2CCc3c([nH]c4c[cH:1]ccc34)C21',
  'C[N:1]1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2ccccc2C(=O)N2C[CH2:1]c3c([nH]c4ccccc34)C21',
  'O=C1c2ccccc2N([CH3:1])C2c3[nH]c4ccccc4c3CCN12',
  'C[N:1]1[c:1]2cccc[c:1]2[C:1](=O)[N:1]2CCc3c([nH]c4ccccc34)[CH:1]21',
  'CN1c2c[cH:1]ccc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2cc[cH:1]cc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2ccccc2C(=O)N2CCc3c([nH]c4c3ccc[cH:1]4)C21',
  'CN1c2ccccc2C(=O)[N:1]2CCc3c([nH]c4ccccc34)C21'],
 ['CNC(=O)c1ccccc1[S:1]c1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'C[NH:1]C(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'O=C(N[CH3:1])c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1c[cH:1]ccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CN[C:1](=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1cc[cH:1]cc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1c(Sc2ccc3c(/C=C/c4ccccn4)n[nH]c3c2)ccc[cH:1]1',
  'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3cc[cH:1]cn3)n[nH]c2c1',
  'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH:1]c2c1',
  'C[NH:1][C:1](=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1'],
 ['CNCC[C@@H](Oc1ccc[cH:1]c1C)c1ccccc1',
  'CNCC[C@@H](Oc1ccccc1[CH3:1])c1ccccc1',
  'CNCC[C@@H](Oc1cc[cH:1]cc1C)c1ccccc1',
  'Cc1ccccc1O[C@H](CC[NH:1]C)c1ccccc1',
  'CNCC[C@@H:1](Oc1ccccc1C)c1ccccc1',
  'CNCC[C@@H](Oc1ccccc1C)c1cc[cH:1]cc1',
  'CNCC[C@H](c1ccccc1)[O:1]c1ccccc1C',
  'CNCC[C@@H](Oc1c[cH:1]ccc1C)c1ccccc1',
  'CN[CH2:1]C[C@@H](Oc1ccccc1C)c1ccccc1',
  'CNCC[C@H:1](c1ccccc1)[O:1]c1ccccc1C'],
 ['C[NH:1]Cc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'CN[CH2:1]c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'C[NH:1][CH2:1]c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2ccc[n:1]c2)c1',
  'O=S(=O)(c1cccnc1)n1cc(CN[CH3:1])cc1-c1ccccc1F',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)[cH:1]1',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cc[cH:1]nc2)c1',
  'O=S(=O)(c1cccnc1)n1cc(C[NH:1][CH3:1])cc1-c1ccccc1F',
  'CNCc1cc(-c2cc[cH:1]cc2F)n(S(=O)(=O)c2cccnc2)c1',
  'C[NH:1]Cc1cc(-c2ccccc2F)[n:1](S(=O)(=O)c2cccnc2)c1'],
 ['C[C@@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@H:1](c1ccccc1)[OH:1]',
  'CN[C@@H](C)[C@@H:1](O)c1ccccc1',
  'CN[C@@H](C)[C@@H](O)c1cc[cH:1]cc1',
  'CN[C@@H](C)[C@H](c1ccccc1)[OH:1]',
  'C[C@@H](N[CH3:1])[C@@H](O)c1ccccc1',
  'CN[C@@H](C)[C@@H](O)c1ccc[cH:1]c1',
  'C[C@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'C[C@@H]([NH:1]C)[C@@H:1](O)c1ccccc1',
  'CN[C@@H:1](C)[C@@H](O)c1ccccc1'],
 ['CN[C@@H](C)[C@@H:1](c1ccccc1)[OH:1]',
  'C[C@@H]([C@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@@H](c1ccccc1)[OH:1]',
  'C[C@@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@H](O)c1cc[cH:1]cc1',
  'CN[C@@H](C)[C@H:1](O)c1ccccc1',
  'C[C@@H](N[CH3:1])[C@H](O)c1ccccc1',
  'CN[C@@H](C)[C@H](O)c1ccc[cH:1]c1',
  'C[C@@H]([NH:1]C)[C@@H:1](c1ccccc1)[OH:1]',
  'C[C@@H](N[CH3:1])[C@@H](c1ccccc1)[OH:1]'],
 ['COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)[CH3:1]',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2c[cH:1]c(=O)[nH]c2=O)cc1C(C)(C)C',
  'CC(C)(C)c1cc(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)c1[O:1]C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH:1]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-[n:1]2[cH:1][cH:1][c:1](=O)[nH:1][c:1]2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=[O:1])ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc([NH:1]S(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2cc3ccc(NS(C)(=O)=O)cc3c[cH:1]2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)[cH:1]c1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2cc[c:1](=[O:1])[nH]c2=O)cc1C(C)(C)C'],
 ['COc1cc(Cc2cnc(N)nc2N)cc([O:1]C)c1OC',
  'COc1cc(Cc2cnc(N)[n:1]c2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc([NH2:1])nc2N)cc(OC)c1OC',
  'COc1cc(Cc2c[n:1]c(N)nc2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2N)[cH:1]c(OC)c1OC',
  'COc1cc([CH2:1]c2cnc(N)nc2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2[NH2:1])cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1[O:1]C',
  'COc1cc(Cc2cnc(N)nc2N)cc(O[CH3:1])c1OC',
  'COc1cc(Cc2cnc(N)n[c:1]2N)cc(OC)c1OC'],
 ['COc1cc2c(cc1C(N)=O)c(Oc1ccc(NC(=O)NC3CC3)c(Cl)c1)cc[n:1]2',
  'C[O:1]c1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2n[cH:1]cc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4C[CH2:1]4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(=O)[NH2:1]',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1](N)=O',
  'COc1c(C(N)=O)cc2c(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)ccnc2[cH:1]1',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1]([NH2:1])=[O:1]',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1](N)=[O:1]',
  'O=C(NC1CC1)Nc1ccc(Oc2ccnc3cc([O:1][CH3:1])c(C(=O)[NH2:1])cc23)cc1Cl'],

In [12]:
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/metapredictor/metapredictor_som.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict'].to_list()
predicts = [i.split('|') for i in predicts]
atomidxs = []
for i in predicts:
    atomidxs_part = []
    for j in i:
        try:
            atomidx = get_reactive_atom_indices(j)
            atomidxs_part.append(atomidx)
        except:
            pass
    atomidxs.append(atomidxs_part)
df['atomidxs'] = atomidxs
df

,SMILES,metabolite,predict,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,"[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,"[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)...,"[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C|CC(CN1c2cc...,"[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1CN=C(c2cc[cH:1]cc2)c2cc(Cl)ccc2N1|O=C1CN=C...,"[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1[OH:1]|O=C1Nc2...,"[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1([NH:1]CCCl)OCCCN1CCCl|O=P1(NCCCl)OCCC[N:1...,"[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|...,"[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [13]:
df.to_pickle('metapredictor_results.pickle')

In [14]:
df = pd.read_pickle('metapredictor_results.pickle')
df

,SMILES,metabolite,predict,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,"[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,"[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)...,"[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C|CC(CN1c2cc...,"[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1CN=C(c2cc[cH:1]cc2)c2cc(Cl)ccc2N1|O=C1CN=C...,"[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1[OH:1]|O=C1Nc2...,"[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1([NH:1]CCCl)OCCCN1CCCl|O=P1(NCCCl)OCCC[N:1...,"[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|...,"[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [23]:
subs = df['SMILES'].to_list()
atomidxs = df['atomidxs'].to_list()
dict_sub2atomidxs = dict(zip(subs,atomidxs))
dict_sub2atomidxs

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [[3],
  [17],
  [15, 17],
  [12],
  [15],
  [13, 14],
  [16],
  [23, 24],
  [3],
  [3]],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [[6],
  [19],
  [40],
  [7],
  [1, 40],
  [40],
  [1],
  [40],
  [34],
  [40]],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [[23],
  [22],
  [25],
  [4],
  [1],
  [3],
  [3, 25],
  [13],
  [19],
  [1, 25]],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [[13],
  [14],
  [10],
  [7],
  [11, 12, 13, 14, 15, 16],
  [15],
  [17],
  [16],
  [3],
  [19]],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [[58],
  [2],
  [59],
  [45],
  [60],
  [25],
  [39],
  [34],
  [7],
  [56]],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [[15],
  [2],
  [9],
  [16],
  [6],
  [24],
  [17],
  [20],
  [9, 17],
  [1, 2]],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [[14],
  [6],
  [15, 16],
  [11],
  [7],
  [1],
  [14, 15, 16],
  [7],
  [14, 15],
  [12, 13]],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [[21],
  [18],
  [10],
  [6, 21],
  [7],
  [19],
  [6],
  [2, 21],
  [1],
  [21]],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [[19],
  [19],
  [18, 19],
  [1],
  [7],
  [17, 19],
  [2],
  [6, 7],
  [18],
  [14, 19]],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [[38],
  [4],
  [35],
  [32],
  [11],
  [29],
  [37, 38],
  [26],
  [23],
  [39]],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [[23],
  [19],
  [30],
  [28],
  [27],
  [8],
  [26],
  [22],
  [20],
  [17]],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [[26],
  [28],
  [28, 29],
  [29],
  [3],
  [1],
  [22],
  [2],
  [7],
  [28, 31]],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [[16],
  [24],
  [19],
  [23],
  [21],
  [6],
  [26],
  [17],
  [8],
  [15]],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [[15],
  [16],
  [2],
  [18],
  [7],
  [16],
  [18],
  [19],
  [17]],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [[14],
  [2],
  [7],
  [15],
  [6, 7],
  [2, 7],
  [5],
  [6],
  [2, 13],
  [15]],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [[2],
  [40],
  [39],
  [30],
  [16],
  [10],
  [31],
  [15],
  [11],
  [14, 15]],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [[2],
  [16],
  [5],
  [5],
  [13],
  [6],
  [3],
  [6],
  [17, 18],
  [1]],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [[16],
  [5],
  [24],
  [20],
  [27],
  [11],
  [24],
  [12],
  [26],
  [25]],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [[22],
  [8],
  [2],
  [25],
  [7],
  [12],
  [2, 8],
  [15],
  [14],
  [27]],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [[6],
  [1],
  [3],
  [3, 6],
  [22, 23, 24],
  [14],
  [9],
  [1, 22, 23, 24],
  [3, 24],
  [23, 28]],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [[1],
  [17],
  [14],
  [10],
  [3],
  [9],
  [13],
  [15, 16, 17, 18, 19, 20],
  [18],
  [11]],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [[15],
  [5],
  [7],
  [5, 15],
  [28, 29, 30, 31, 32],
  [28, 29, 30],
  [7, 15],
  [10],
  [19],
  [28, 29, 30, 31]],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [[16],
  [18],
  [1],
  [12, 13, 14, 15, 16, 17, 18, 19],
  [17],
  [15],
  [14],
  [1, 2, 3, 4, 9, 10],
  [11],
  [6]],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [[19],
  [18],
  [1],
  [12],
  [9],
  [1, 2, 7, 8, 10, 22],
  [4],
  [5],
  [21],
  [10]],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [[10],
  [1],
  [3],
  [6],
  [2],
  [7],
  [27],
  [21],
  [25],
  [1, 2]],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [[10],
  [12],
  [9],
  [11],
  [4],
  [16],
  [11],
  [8],
  [2],
  [4, 11]],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [[1],
  [2],
  [1, 2],
  [21],
  [14],
  [23],
  [20],
  [13, 14],
  [9],
  [1, 13]],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [[10],
  [4, 11],
  [4],
  [9],
  [11],
  [3],
  [10],
  [10],
  [2, 4],
  [2]],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [[4, 11],
  [10],
  [11],
  [10],
  [9],
  [4],
  [3],
  [10],
  [2, 4, 11],
  [3, 11]],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [[34],
  [23],
  [33],
  [26],
  [21, 22, 23, 24, 26, 27],
  [14],
  [10],
  [18],
  [29],
  [24, 25]],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [[16],
  [11],
  [10],
  [8],
  [14],
  [5],
  [13],
  [19],
  [17],
  [12]],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [[29],
  [1],
  [6],
  [20],
  [29],
  [27],
  [29],
  [27, 28, 29],
  [27, 29],
  [19, 20, 24]],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [[22],
  [17],
  [7],
  [19],
  [9],
  [21],
  [11],
  [11, 22],
  [20],
  [7, 22]],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [[16],
  [1],
  [22],
  [24],
  [15],
  [9],
  [15, 16, 17, 22, 23, 24],
  [22, 24],
  [22, 24],
  [24]],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [[7],
  [7],
  [4],
  [17],
  [14, 15],
  [17],
  [13],
  [5, 6, 7, 8, 10, 11],
  [5, 7],
  [13, 14, 15]],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [[35],
  [37],
  [27, 28, 29, 30, 31, 32],
  [38],
  [4],
  [37, 38],
  [30],
  [11],
  [26, 35],
  [35]],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [[6],
  [17],
  [7],
  [5],
  [6, 7],
  [26],
  [25],
  [30],
  [33],
  [38]],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [[13],
  [14],
  [9],
  [15],
  [25],
  [12, 15],
  [8],
  [11],
  [28],
  [29]],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [[8],
  [25, 26],
  [22],
  [6],
  [3],
  [25, 26],
  [15],
  [21],
  [12],
  [20]],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [[6],
  [7],
  [14],
  [7, 15],
  [11],
  [15],
  [12],
  [15],
  [2, 7],
  [6, 7]],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [[3],
  [21],
  [18],
  [17],
  [4],
  [21],
  [15, 16, 17, 18, 19, 21],
  [13],
  [14],
  [19]],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [[22],
  [9],
  [20],
  [20, 22],
  [19],
  [6],
  [10],
  [11],
  [12],
  [23]],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [[27],
  [6],
  [31],
  [22],
  [31],
  [22, 31],
  [26],
  [6, 7, 8],
  [7, 8],
  [9, 10]],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [[19],
  [22],
  [9],
  [20, 22],
  [20],
  [18],
  [16],
  [21, 22],
  [10],
  [6]],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [[17],
  [18],
  [26],
  [29],
  [12],
  [4],
  [27],
  [14],
  [1],
  [7]],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [[17],
  [9],
  [18],
  [10],
  [20],
  [19],
  [6],
  [9, 18],
  [1, 17]],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [[28],
  [23],
  [27],
  [8],
  [23],
  [29],
  [24],
  [31],
  [16]],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [[21],
  [22],
  [23],
  [27],
  [23],
  [26],
  [24],
  [25],
  [8],
  [15, 16]],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [[42],
  [6],
  [23],
  [3],
  [29],
  [18],
  [43],
  [38],
  [44],
  [32]],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [[12, 17],
  [16],
  [12],
  [15],
  [5],
  [7, 8],
  [17],
  [11],
  [7],
  [8]],
 'Clc1ccccc1CN1CCc2sccc2C1': [[13],
  [15],
  [11, 12, 13, 14, 15],
  [4],
  [11, 12, 13, 14, 15, 16],
  [7],
  [14],
  [8],
  [3],
  [16]],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [[8],
  [7],
  [9],
  [10],
  [8],
  [4],
  [11],
  [4, 5, 8],
  [6],
  [10]],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [[16],
  [17],
  [16, 17],
  [1],
  [13, 15, 18, 20],
  [13, 15, 18],
  [13, 18, 20],
  [13, 15, 20],
  [15, 18],
  [26]],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [[1],
  [11],
  [12],
  [1, 16],
  [16],
  [16],
  [16],
  [12, 13, 14],
  [15],
  [10]],
 'NC(=O)c1nc(F)cnc1O': [[7],
  [10],
  [9],
  [8],
  [10],
  [9, 10],
  [1],
  [1, 2, 3, 9, 10],
  [1, 10],
  [3, 4, 5, 7, 8, 9]],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [[8],
  [17],
  [11, 17],
  [7],
  [3],
  [11, 16, 17],
  [11, 12, 13],
  [13],
  [14, 17],
  [16, 19]],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [[7],
  [8],
  [7],
  [5],
  [7],
  [6],
  [1],
  [8],
  [9]],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [[5],
  [6],
  [5, 6],
  [9],
  [20],
  [22],
  [20],
  [12],
  [23, 24],
  [14]],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [[5],
  [12],
  [12, 14, 17],
  [17],
  [5],
  [12, 14],
  [16],
  [15],
  [6],
  [13]],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [[21],
  [26],
  [7],
  [16, 26],
  [22],
  [13],
  [6],
  [13, 26],
  [4],
  [26]],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [[30],
  [11],
  [10, 30],
  [30, 47],
  [11, 30],
  [47],
  [10],
  [29, 30],
  [27, 30],
  [26]],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [[8],
  [16],
  [15],
  [18],
  [18],
  [9],
  [16, 17, 18],
  [14, 18],
  [8, 9],
  [1, 2, 3, 4, 11, 17, 18]],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [[19],
  [14],
  [18],
  [15],
  [19],
  [18, 19],
  [5]],
 'O=P1(NCCCl)OCCCN1CCCl': [[2],
  [10],
  [12],
  [9],
  [4],
  [12, 13],
  [5],
  [2, 10],
  [8],
  [7]],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [[1],
  [6],
  [3],
  [20, 21],
  [21],
  [21],
  [22],
  [9],
  [18, 19, 20, 21, 22, 23],
  [23]]}

In [18]:
df_total_old = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct.csv')
substrates_old = df_total_old['substrate'].to_list()
sites_old = df_total_old['site_truth'].to_list()
sites_old = [get_reactive_atom_indices(i) for i in sites_old]
df_total_old['sites_old'] = sites_old
df_total_old

,substrate,metabolite,mapped_rxn,pred_rxn,site_truth,sites_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,[CH:1]#[C:2][C@:3]1([OH:4])[CH2:8][CH2:9][C@H:...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,[3]
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1...,[19]
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,[CH3:1][C:2]([OH:4])([CH2:3]O)[c:5]1[cH:6][cH:...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[40]
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1[CH2:1]C[C@@H](SCC1(CC(=O)O)CC...,[10]
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[32]
...,...,...,...,...,...,...
174,O=P1(NCCCl)OCCCN1CCCl,O=CCCl,O=CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:7]=[CH:8][CH2:5][Cl:6]>>O=P1(NC[CH2:5][Cl:6...,O=P1(NC[CH2:1]Cl)N(CCCl)CC[CH2:1][O:1]1,"[4, 12, 13]"
175,O=P1(NCCCl)OCCCN1CCCl,NP1(=O)OCCCN1CCCl,NP1(=O)OCCCN1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[NH2:3][P:2]1(=[O:1])[O:7][CH2:8][CH2:9][CH2:1...,O=P1([NH:1]CCCl)OCCCN1CCCl,[2]
176,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[O:7][...,O=P1(NCCCl)OCC[CH2:1]N1CCCl,[9]
177,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)NCCCO1,O=P1(NCCCl)NCCCO1>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[NH:11...,O=P1(NCCCl)OCCC[N:1]1CCCl,[10]
178,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1>>O...,O=[C:2]([OH:1])[CH2:3][O:4][CH2:5][CH2:6][N:7]...,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1]

In [19]:
def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
dict_sub2site = group_by_column_to_dict(df_total_old,'substrate','sites_old')
for i in list(dict_sub2site.keys()):
    sitelist = dict_sub2site[i]
    sitelist = [i for k in sitelist for i in k]
    sitelist = list(set(sitelist))
    dict_sub2site[i] = sitelist
dict_sub2site

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [3],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [40,
  32,
  10,
  19],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [1, 4, 5, 22, 23, 25],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [10, 11, 12, 13, 14, 15, 16, 17],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [2,
  7,
  50,
  59,
  60],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [2,
  14,
  15,
  16,
  21],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [6],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [12, 13, 6],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [19],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [11],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [23],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [26,
  7],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [24,
  16],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [2, 15],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [2, 13, 7],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [2],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [2],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [16],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [8, 12, 21, 22, 25],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [6],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [1, 6, 17],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [25,
  5,
  15],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [1, 12, 13, 14, 15, 16, 17, 18, 19],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [19, 12],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [3, 10, 16, 17, 23],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [9, 11, 12],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [1, 2],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [10],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [10],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [34],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [5, 8, 11, 16, 19],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [1, 29],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [17, 19, 22, 7],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [1, 26, 20, 21],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [5, 6, 7, 8, 10, 11, 13, 14, 15, 17],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [35, 22],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [25,
  6],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [11],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [8],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [6, 7, 12, 14, 15],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [3, 4],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [9],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [27],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [21],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [17, 12],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [17, 10, 18, 6],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [30, 23],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [22, 23],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [42,
  45],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [17, 12],
 'Clc1ccccc1CN1CCc2sccc2C1': [8, 11, 12, 13, 14, 15, 16],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [8, 10, 7],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [1, 13, 15, 16, 17, 18],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [],
 'NC(=O)c1nc(F)cnc1O': [7],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [8],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [1],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [1, 2, 7, 15, 16, 20],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [17, 5, 15],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [7],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [30,
  47],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [16, 17, 18],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [16, 17, 18, 19],
 'O=P1(NCCCl)OCCCN1CCCl': [2, 4, 9, 10, 12, 13],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [1]}

In [24]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
true_sites_old = [dict_sub2site[i] for i in substrates]
metapredictor_results_old = [dict_sub2atomidxs[i] for i in substrates]
df_total.insert(2, 'true_sites_old', true_sites_old)
df_total['metapredictor_results_old'] = metapredictor_results_old
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,xenosite_results,somp_results,metapredictor_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [ ]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')