1. gnn-som

In [163]:
import pandas as pd

In [164]:
df = pd.read_pickle('gnnsom_results.pickle')
df

,substrate,ec,score
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"(1, 14)","{0: 0.17234759032726288, 1: 0.2866118252277374..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(2, 4)","{0: 0.03460502251982689, 1: 0.1962412446737289..."
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(1, 14)","{0: 0.26034024357795715, 1: 0.9417978525161743..."
3,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"(1, 14)","{0: 0.07399298995733261, 1: 0.0268323067575693..."
4,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"(1, 14)","{0: 0.06365552544593811, 1: 0.2708439826965332..."
...,...,...,...
67,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"(1, 14)","{0: 0.015096035785973072, 1: 0.234839916229248..."
68,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"(1, 14)","{0: 0.6005780696868896, 1: 0.9662299156188965,..."
69,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"(2, 4)","{0: 0.09907922148704529, 1: 0.1877077072858810..."
70,O=P1(NCCCl)OCCCN1CCCl,"(1, 14)","{0: 0.16878382861614227, 1: 0.0837636962532997..."
71,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,"(1, 14)","{0: 0.8059802055358887, 1: 0.4815613329410553,..."

In [165]:
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

In [166]:
scores = df['score'].to_list()
scores = list(map(assign_ranks,scores))
scores

[{0: 9,
  1: 6,
  2: 2,
  3: 1,
  4: 4,
  5: 18,
  6: 13,
  7: 7,
  8: 19,
  9: 25,
  10: 26,
  11: 17,
  12: 16,
  13: 23,
  14: 12,
  15: 8,
  16: 5,
  17: 3,
  18: 10,
  19: 11,
  20: 20,
  21: 27,
  22: 24,
  23: 21,
  24: 22,
  25: 15,
  26: 14},
 {0: 9,
  1: 4,
  2: 8,
  3: 1,
  4: 12,
  5: 20,
  6: 25,
  7: 29,
  8: 15,
  9: 37,
  10: 33,
  11: 40,
  12: 32,
  13: 7,
  14: 34,
  15: 38,
  16: 31,
  17: 5,
  18: 10,
  19: 2,
  20: 26,
  21: 36,
  22: 41,
  23: 17,
  24: 24,
  25: 13,
  26: 27,
  27: 22,
  28: 28,
  29: 19,
  30: 23,
  31: 16,
  32: 21,
  33: 18,
  34: 30,
  35: 11,
  36: 6,
  37: 35,
  38: 14,
  39: 3,
  40: 39},
 {0: 9,
  1: 1,
  2: 8,
  3: 2,
  4: 22,
  5: 16,
  6: 17,
  7: 29,
  8: 15,
  9: 37,
  10: 41,
  11: 39,
  12: 13,
  13: 5,
  14: 31,
  15: 38,
  16: 19,
  17: 18,
  18: 33,
  19: 12,
  20: 26,
  21: 30,
  22: 40,
  23: 24,
  24: 27,
  25: 34,
  26: 35,
  27: 25,
  28: 28,
  29: 32,
  30: 4,
  31: 3,
  32: 10,
  33: 6,
  34: 7,
  35: 21,
  36: 20,
  37: 14,
  38: 23,
  39: 11,
  40: 36},
 {0: 15,
  1: 22,
  2: 16,
  3: 7,
  4: 2,
  5: 6,
  6: 23,
  7: 11,
  8: 19,
  9: 26,
  10: 25,
  11: 13,
  12: 17,
  13: 9,
  14: 10,
  15: 12,
  16: 1,
  17: 3,
  18: 4,
  19: 5,
  20: 18,
  21: 14,
  22: 21,
  23: 8,
  24: 24,
  25: 20},
 {0: 12,
  1: 6,
  2: 4,
  3: 5,
  4: 16,
  5: 13,
  6: 11,
  7: 14,
  8: 19,
  9: 10,
  10: 7,
  11: 17,
  12: 18,
  13: 15,
  14: 8,
  15: 9,
  16: 20,
  17: 1,
  18: 3,
  19: 2},
 {0: 34,
  1: 42,
  2: 32,
  3: 45,
  4: 29,
  5: 20,
  6: 23,
  7: 28,
  8: 3,
  9: 12,
  10: 43,
  11: 55,
  12: 38,
  13: 49,
  14: 52,
  15: 22,
  16: 44,
  17: 18,
  18: 2,
  19: 13,
  20: 15,
  21: 61,
  22: 56,
  23: 53,
  24: 39,
  25: 9,
  26: 41,
  27: 46,
  28: 51,
  29: 40,
  30: 54,
  31: 35,
  32: 47,
  33: 36,
  34: 1,
  35: 4,
  36: 5,
  37: 59,
  38: 30,
  39: 10,
  40: 11,
  41: 58,
  42: 50,
  43: 60,
  44: 14,
  45: 16,
  46: 19,
  47: 37,
  48: 31,
  49: 48,
  50: 17,
  51: 7,
  52: 33,
  53: 24,
  54: 6,
  55: 26,
  56: 57,
  57: 27,
  58: 21,
  59: 8,
  60: 25},
 {0: 12,
  1: 10,
  2: 8,
  3: 16,
  4: 11,
  5: 7,
  6: 5,
  7: 4,
  8: 13,
  9: 3,
  10: 1,
  11: 19,
  12: 20,
  13: 14,
  14: 6,
  15: 2,
  16: 9,
  17: 21,
  18: 15,
  19: 17,
  20: 24,
  21: 18,
  22: 23,
  23: 25,
  24: 22},
 {0: 10,
  1: 5,
  2: 1,
  3: 14,
  4: 11,
  5: 16,
  6: 15,
  7: 17,
  8: 13,
  9: 3,
  10: 4,
  11: 8,
  12: 9,
  13: 12,
  14: 6,
  15: 2,
  16: 7},
 {0: 21,
  1: 4,
  2: 6,
  3: 17,
  4: 20,
  5: 16,
  6: 19,
  7: 18,
  8: 14,
  9: 22,
  10: 2,
  11: 1,
  12: 8,
  13: 3,
  14: 15,
  15: 10,
  16: 12,
  17: 5,
  18: 7,
  19: 11,
  20: 13,
  21: 9},
 {0: 7,
  1: 10,
  2: 22,
  3: 16,
  4: 9,
  5: 18,
  6: 8,
  7: 14,
  8: 20,
  9: 21,
  10: 17,
  11: 12,
  12: 15,
  13: 13,
  14: 6,
  15: 3,
  16: 4,
  17: 2,
  18: 5,
  19: 1,
  20: 11,
  21: 19},
 {0: 30,
  1: 29,
  2: 42,
  3: 39,
  4: 9,
  5: 16,
  6: 34,
  7: 21,
  8: 41,
  9: 2,
  10: 28,
  11: 1,
  12: 3,
  13: 7,
  14: 4,
  15: 24,
  16: 17,
  17: 11,
  18: 35,
  19: 32,
  20: 10,
  21: 36,
  22: 33,
  23: 13,
  24: 38,
  25: 31,
  26: 12,
  27: 37,
  28: 40,
  29: 14,
  30: 27,
  31: 23,
  32: 15,
  33: 22,
  34: 19,
  35: 5,
  36: 26,
  37: 18,
  38: 6,
  39: 8,
  40: 20,
  41: 25},
 {0: 6,
  1: 2,
  2: 10,
  3: 12,
  4: 20,
  5: 15,
  6: 25,
  7: 19,
  8: 17,
  9: 23,
  10: 14,
  11: 31,
  12: 18,
  13: 4,
  14: 7,
  15: 21,
  16: 24,
  17: 30,
  18: 27,
  19: 28,
  20: 3,
  21: 1,
  22: 9,
  23: 16,
  24: 5,
  25: 8,
  26: 11,
  27: 13,
  28: 29,
  29: 26,
  30: 22},
 {0: 3,
  1: 11,
  2: 4,
  3: 1,
  4: 23,
  5: 26,
  6: 33,
  7: 21,
  8: 6,
  9: 9,
  10: 8,
  11: 14,
  12: 7,
  13: 13,
  14: 25,
  15: 24,
  16: 15,
  17: 18,
  18: 16,
  19: 35,
  20: 34,
  21: 29,
  22: 28,
  23: 27,
  24: 32,
  25: 31,
  26: 22,
  27: 19,
  28: 5,
  29: 2,
  30: 17,
  31: 12,
  32: 20,
  33: 10,
  34: 36,
  35: 30},
 {0: 6,
  1: 11,
  2: 17,
  3: 3,
  4: 7,
  5: 16,
  6: 8,
  7: 22,
  8: 13,
  9: 24,
  10: 15,
  11: 23,
  12: 18,
  13: 26,
  14: 27,
  15: 25,
  16: 5,
  17: 21,
  18: 20,
  19: 19,
  20: 12,
  21: 2,
  22: 9,
  23: 1,
  24: 14,
  25: 4,
  26: 10},
 {0: 9,
  1: 10,
  2: 17,
  3: 8,
  4: 11,
  5: 16,
  6: 20,
  7: 6,
  8: 2,
  9: 15,
  10: 18,
  11: 19,
  12: 14,
  13: 7,
  14: 5,
  15: 1,
  16: 12,
  17: 13,
  18: 3,
  19: 4},
 {0: 12,
  1: 17,
  2: 7,
  3: 15,
  4: 11,
  5: 9,
  6: 3,
  7: 1,
  8: 2,
  9: 10,
  10: 5,
  11: 6,
  12: 13,
  13: 14,
  14: 4,
  15: 16,
  16: 8},
 {0: 25,
  1: 10,
  2: 9,
  3: 29,
  4: 31,
  5: 34,
  6: 32,
  7: 28,
  8: 17,
  9: 38,
  10: 11,
  11: 3,
  12: 6,
  13: 4,
  14: 27,
  15: 8,
  16: 5,
  17: 15,
  18: 36,
  19: 30,
  20: 39,
  21: 1,
  22: 12,
  23: 2,
  24: 7,
  25: 18,
  26: 37,
  27: 19,
  28: 33,
  29: 24,
  30: 14,
  31: 13,
  32: 22,
  33: 40,
  34: 42,
  35: 41,
  36: 23,
  37: 26,
  38: 16,
  39: 35,
  40: 21,
  41: 20},
 {0: 17,
  1: 8,
  2: 9,
  3: 10,
  4: 14,
  5: 13,
  6: 16,
  7: 2,
  8: 5,
  9: 3,
  10: 15,
  11: 11,
  12: 12,
  13: 1,
  14: 7,
  15: 4,
  16: 6,
  17: 18,
  18: 19},
 {0: 28,
  1: 15,
  2: 12,
  3: 2,
  4: 27,
  5: 4,
  6: 7,
  7: 11,
  8: 20,
  9: 23,
  10: 21,
  11: 22,
  12: 19,
  13: 6,
  14: 16,
  15: 10,
  16: 3,
  17: 5,
  18: 17,
  19: 1,
  20: 8,
  21: 26,
  22: 13,
  23: 9,
  24: 14,
  25: 18,
  26: 29,
  27: 24,
  28: 25},
 {0: 23,
  1: 19,
  2: 3,
  3: 2,
  4: 12,
  5: 25,
  6: 26,
  7: 24,
  8: 6,
  9: 22,
  10: 28,
  11: 27,
  12: 21,
  13: 20,
  14: 16,
  15: 9,
  16: 10,
  17: 29,
  18: 18,
  19: 13,
  20: 8,
  21: 11,
  22: 1,
  23: 15,
  24: 14,
  25: 4,
  26: 5,
  27: 7,
  28: 17},
 {0: 29,
  1: 11,
  2: 6,
  3: 4,
  4: 17,
  5: 24,
  6: 28,
  7: 14,
  8: 8,
  9: 22,
  10: 15,
  11: 9,
  12: 12,
  13: 13,
  14: 16,
  15: 18,
  16: 20,
  17: 25,
  18: 27,
  19: 23,
  20: 21,
  21: 7,
  22: 5,
  23: 19,
  24: 10,
  25: 1,
  26: 3,
  27: 2,
  28: 26},
 {0: 7,
  1: 3,
  2: 9,
  3: 11,
  4: 20,
  5: 10,
  6: 1,
  7: 4,
  8: 23,
  9: 18,
  10: 28,
  11: 27,
  12: 24,
  13: 25,
  14: 8,
  15: 21,
  16: 26,
  17: 19,
  18: 16,
  19: 15,
  20: 14,
  21: 2,
  22: 5,
  23: 6,
  24: 12,
  25: 13,
  26: 17,
  27: 22,
  28: 29},
 {0: 3,
  1: 1,
  2: 2,
  3: 12,
  4: 14,
  5: 11,
  6: 10,
  7: 19,
  8: 7,
  9: 5,
  10: 9,
  11: 15,
  12: 21,
  13: 18,
  14: 17,
  15: 20,
  16: 13,
  17: 6,
  18: 4,
  19: 8,
  20: 16},
 {0: 4,
  1: 2,
  2: 5,
  3: 19,
  4: 32,
  5: 27,
  6: 15,
  7: 12,
  8: 17,
  9: 18,
  10: 7,
  11: 22,
  12: 31,
  13: 23,
  14: 20,
  15: 11,
  16: 21,
  17: 16,
  18: 26,
  19: 28,
  20: 13,
  21: 24,
  22: 25,
  23: 29,
  24: 10,
  25: 30,
  26: 3,
  27: 1,
  28: 6,
  29: 9,
  30: 14,
  31: 8,
  32: 33},
 {0: 8,
  1: 10,
  2: 5,
  3: 12,
  4: 19,
  5: 9,
  6: 6,
  7: 7,
  8: 18,
  9: 16,
  10: 13,
  11: 11,
  12: 20,
  13: 17,
  14: 15,
  15: 3,
  16: 2,
  17: 1,
  18: 4,
  19: 14},
 {0: 4,
  1: 2,
  2: 6,
  3: 11,
  4: 18,
  5: 16,
  6: 19,
  7: 14,
  8: 17,
  9: 12,
  10: 10,
  11: 13,
  12: 20,
  13: 8,
  14: 9,
  15: 7,
  16: 1,
  17: 5,
  18: 3,
  19: 15},
 {0: 2,
  1: 3,
  2: 23,
  3: 18,
  4: 17,
  5: 15,
  6: 12,
  7: 19,
  8: 6,
  9: 13,
  10: 1,
  11: 4,
  12: 16,
  13: 22,
  14: 9,
  15: 11,
  16: 20,
  17: 10,
  18: 8,
  19: 7,
  20: 14,
  21: 21,
  22: 5},
 {0: 2,
  1: 1,
  2: 8,
  3: 14,
  4: 27,
  5: 15,
  6: 12,
  7: 17,
  8: 23,
  9: 24,
  10: 4,
  11: 20,
  12: 18,
  13: 21,
  14: 26,
  15: 25,
  16: 13,
  17: 16,
  18: 22,
  19: 9,
  20: 6,
  21: 3,
  22: 5,
  23: 11,
  24: 10,
  25: 7,
  26: 19,
  27: 28},
 {0: 2,
  1: 1,
  2: 5,
  3: 6,
  4: 4,
  5: 3,
  6: 9,
  7: 11,
  8: 12,
  9: 8,
  10: 10,
  11: 15,
  12: 7,
  13: 19,
  14: 17,
  15: 16,
  16: 18,
  17: 13,
  18: 14},
 {0: 3,
  1: 2,
  2: 7,
  3: 22,
  4: 23,
  5: 18,
  6: 24,
  7: 15,
  8: 11,
  9: 14,
  10: 12,
  11: 16,
  12: 19,
  13: 6,
  14: 1,
  15: 4,
  16: 5,
  17: 9,
  18: 17,
  19: 20,
  20: 21,
  21: 10,
  22: 13,
  23: 8},
 {0: 3, 1: 1, 2: 5, 3: 6, 4: 2, 5: 4, 6: 12, 7: 7, 8: 11, 9: 9, 10: 10, 11: 8},
 {0: 2, 1: 1, 2: 5, 3: 9, 4: 3, 5: 4, 6: 12, 7: 8, 8: 10, 9: 11, 10: 6, 11: 7},
 {0: 5,
  1: 6,
  2: 26,
  3: 30,
  4: 33,
  5: 23,
  6: 12,
  7: 35,
  8: 18,
  9: 15,
  10: 2,
  11: 1,
  12: 28,
  13: 3,
  14: 7,
  15: 31,
  16: 22,
  17: 32,
  18: 29,
  19: 11,
  20: 14,
  21: 4,
  22: 8,
  23: 9,
  24: 20,
  25: 34,
  26: 13,
  27: 16,
  28: 25,
  29: 10,
  30: 24,
  31: 17,
  32: 19,
  33: 27,
  34: 21},
 {0: 6,
  1: 7,
  2: 15,
  3: 3,
  4: 1,
  5: 2,
  6: 5,
  7: 11,
  8: 16,
  9: 21,
  10: 17,
  11: 18,
  12: 19,
  13: 12,
  14: 4,
  15: 14,
  16: 9,
  17: 10,
  18: 20,
  19: 8,
  20: 13},
 {0: 1,
  1: 4,
  2: 13,
  3: 7,
  4: 22,
  5: 18,
  6: 6,
  7: 8,
  8: 5,
  9: 2,
  10: 9,
  11: 14,
  12: 24,
  13: 30,
  14: 12,
  15: 10,
  16: 25,
  17: 15,
  18: 29,
  19: 21,
  20: 17,
  21: 26,
  22: 19,
  23: 23,
  24: 20,
  25: 27,
  26: 28,
  27: 3,
  28: 11,
  29: 16},
 {0: 7,
  1: 6,
  2: 20,
  3: 8,
  4: 9,
  5: 18,
  6: 23,
  7: 24,
  8: 22,
  9: 13,
  10: 11,
  11: 14,
  12: 3,
  13: 12,
  14: 21,
  15: 19,
  16: 25,
  17: 4,
  18: 10,
  19: 2,
  20: 1,
  21: 5,
  22: 15,
  23: 16,
  24: 17},
 {0: 4,
  1: 5,
  2: 9,
  3: 10,
  4: 16,
  5: 22,
  6: 19,
  7: 14,
  8: 12,
  9: 15,
  10: 20,
  11: 7,
  12: 6,
  13: 23,
  14: 24,
  15: 21,
  16: 18,
  17: 13,
  18: 17,
  19: 3,
  20: 1,
  21: 2,
  22: 25,
  23: 11,
  24: 8},
 {0: 6,
  1: 7,
  2: 27,
  3: 23,
  4: 17,
  5: 15,
  6: 1,
  7: 2,
  8: 3,
  9: 10,
  10: 13,
  11: 20,
  12: 18,
  13: 24,
  14: 21,
  15: 16,
  16: 12,
  17: 14,
  18: 26,
  19: 25,
  20: 11,
  21: 8,
  22: 4,
  23: 5,
  24: 9,
  25: 19,
  26: 22},
 {0: 1,
  1: 4,
  2: 10,
  3: 11,
  4: 13,
  5: 18,
  6: 16,
  7: 5,
  8: 3,
  9: 17,
  10: 6,
  11: 9,
  12: 15,
  13: 2,
  14: 12,
  15: 7,
  16: 8,
  17: 14},
 {0: 8,
  1: 12,
  2: 35,
  3: 32,
  4: 15,
  5: 21,
  6: 17,
  7: 19,
  8: 7,
  9: 14,
  10: 33,
  11: 13,
  12: 2,
  13: 3,
  14: 6,
  15: 36,
  16: 11,
  17: 20,
  18: 23,
  19: 25,
  20: 26,
  21: 18,
  22: 34,
  23: 16,
  24: 10,
  25: 37,
  26: 38,
  27: 39,
  28: 28,
  29: 27,
  30: 29,
  31: 22,
  32: 30,
  33: 31,
  34: 24,
  35: 9,
  36: 5,
  37: 4,
  38: 1},
 {0: 32,
  1: 1,
  2: 2,
  3: 5,
  4: 29,
  5: 26,
  6: 11,
  7: 37,
  8: 35,
  9: 27,
  10: 33,
  11: 20,
  12: 31,
  13: 16,
  14: 21,
  15: 40,
  16: 23,
  17: 24,
  18: 34,
  19: 36,
  20: 7,
  21: 22,
  22: 18,
  23: 13,
  24: 10,
  25: 3,
  26: 4,
  27: 6,
  28: 8,
  29: 17,
  30: 9,
  31: 28,
  32: 30,
  33: 19,
  34: 12,
  35: 15,
  36: 39,
  37: 38,
  38: 25,
  39: 14},
 {0: 19,
  1: 3,
  2: 1,
  3: 2,
  4: 22,
  5: 29,
  6: 30,
  7: 24,
  8: 14,
  9: 10,
  10: 25,
  11: 16,
  12: 9,
  13: 15,
  14: 8,
  15: 18,
  16: 20,
  17: 26,
  18: 4,
  19: 5,
  20: 7,
  21: 27,
  22: 13,
  23: 12,
  24: 11,
  25: 21,
  26: 28,
  27: 23,
  28: 17,
  29: 6},
 {0: 18,
  1: 27,
  2: 14,
  3: 26,
  4: 17,
  5: 16,
  6: 15,
  7: 2,
  8: 1,
  9: 3,
  10: 24,
  11: 21,
  12: 23,
  13: 12,
  14: 25,
  15: 9,
  16: 10,
  17: 7,
  18: 20,
  19: 4,
  20: 5,
  21: 8,
  22: 22,
  23: 19,
  24: 11,
  25: 6,
  26: 13},
 {0: 5,
  1: 1,
  2: 3,
  3: 4,
  4: 6,
  5: 8,
  6: 9,
  7: 2,
  8: 7,
  9: 16,
  10: 10,
  11: 11,
  12: 15,
  13: 14,
  14: 12,
  15: 13},
 {0: 13,
  1: 10,
  2: 5,
  3: 2,
  4: 8,
  5: 16,
  6: 11,
  7: 12,
  8: 1,
  9: 4,
  10: 3,
  11: 20,
  12: 18,
  13: 17,
  14: 14,
  15: 19,
  16: 9,
  17: 6,
  18: 7,
  19: 15,
  20: 21,
  21: 22},
 {0: 26,
  1: 21,
  2: 20,
  3: 22,
  4: 17,
  5: 15,
  6: 11,
  7: 6,
  8: 5,
  9: 1,
  10: 3,
  11: 4,
  12: 7,
  13: 12,
  14: 10,
  15: 16,
  16: 18,
  17: 19,
  18: 23,
  19: 14,
  20: 13,
  21: 25,
  22: 24,
  23: 8,
  24: 2,
  25: 9},
 {0: 19,
  1: 25,
  2: 16,
  3: 26,
  4: 18,
  5: 8,
  6: 11,
  7: 31,
  8: 22,
  9: 7,
  10: 13,
  11: 24,
  12: 23,
  13: 14,
  14: 12,
  15: 17,
  16: 20,
  17: 1,
  18: 2,
  19: 10,
  20: 29,
  21: 27,
  22: 3,
  23: 4,
  24: 6,
  25: 15,
  26: 21,
  27: 5,
  28: 9,
  29: 32,
  30: 30,
  31: 28},
 {0: 13,
  1: 9,
  2: 6,
  3: 4,
  4: 3,
  5: 7,
  6: 11,
  7: 10,
  8: 23,
  9: 12,
  10: 14,
  11: 22,
  12: 20,
  13: 8,
  14: 16,
  15: 18,
  16: 19,
  17: 21,
  18: 15,
  19: 5,
  20: 1,
  21: 17,
  22: 2},
 {0: 18,
  1: 22,
  2: 12,
  3: 4,
  4: 3,
  5: 9,
  6: 15,
  7: 28,
  8: 6,
  9: 11,
  10: 13,
  11: 8,
  12: 2,
  13: 10,
  14: 7,
  15: 24,
  16: 17,
  17: 14,
  18: 21,
  19: 16,
  20: 20,
  21: 19,
  22: 1,
  23: 23,
  24: 27,
  25: 25,
  26: 30,
  27: 26,
  28: 29,
  29: 5},
 {0: 5,
  1: 11,
  2: 16,
  3: 10,
  4: 9,
  5: 1,
  6: 2,
  7: 14,
  8: 15,
  9: 13,
  10: 18,
  11: 20,
  12: 22,
  13: 3,
  14: 8,
  15: 4,
  16: 12,
  17: 21,
  18: 7,
  19: 6,
  20: 19,
  21: 17},
 {0: 4,
  1: 5,
  2: 14,
  3: 17,
  4: 20,
  5: 1,
  6: 9,
  7: 21,
  8: 15,
  9: 8,
  10: 6,
  11: 18,
  12: 22,
  13: 16,
  14: 19,
  15: 12,
  16: 11,
  17: 7,
  18: 3,
  19: 2,
  20: 13,
  21: 10},
 {0: 13,
  1: 30,
  2: 29,
  3: 21,
  4: 19,
  5: 1,
  6: 5,
  7: 14,
  8: 23,
  9: 2,
  10: 31,
  11: 6,
  12: 25,
  13: 15,
  14: 3,
  15: 12,
  16: 7,
  17: 20,
  18: 10,
  19: 28,
  20: 27,
  21: 26,
  22: 18,
  23: 16,
  24: 17,
  25: 24,
  26: 9,
  27: 4,
  28: 11,
  29: 8,
  30: 22,
  31: 32},
 {0: 13,
  1: 28,
  2: 21,
  3: 17,
  4: 10,
  5: 1,
  6: 5,
  7: 7,
  8: 6,
  9: 27,
  10: 23,
  11: 22,
  12: 26,
  13: 14,
  14: 19,
  15: 18,
  16: 12,
  17: 24,
  18: 9,
  19: 3,
  20: 4,
  21: 8,
  22: 2,
  23: 11,
  24: 20,
  25: 16,
  26: 15,
  27: 25},
 {0: 20,
  1: 42,
  2: 26,
  3: 34,
  4: 37,
  5: 41,
  6: 25,
  7: 22,
  8: 3,
  9: 4,
  10: 12,
  11: 19,
  12: 11,
  13: 18,
  14: 31,
  15: 32,
  16: 30,
  17: 40,
  18: 43,
  19: 28,
  20: 27,
  21: 2,
  22: 1,
  23: 17,
  24: 36,
  25: 35,
  26: 46,
  27: 29,
  28: 23,
  29: 44,
  30: 24,
  31: 33,
  32: 8,
  33: 9,
  34: 15,
  35: 16,
  36: 45,
  37: 39,
  38: 38,
  39: 5,
  40: 13,
  41: 21,
  42: 10,
  43: 6,
  44: 7,
  45: 14},
 {0: 17,
  1: 20,
  2: 11,
  3: 10,
  4: 18,
  5: 7,
  6: 14,
  7: 2,
  8: 3,
  9: 1,
  10: 12,
  11: 8,
  12: 4,
  13: 5,
  14: 15,
  15: 19,
  16: 16,
  17: 6,
  18: 9,
  19: 13},
 {0: 5,
  1: 11,
  2: 16,
  3: 7,
  4: 9,
  5: 14,
  6: 10,
  7: 8,
  8: 2,
  9: 13,
  10: 12,
  11: 15,
  12: 1,
  13: 3,
  14: 4,
  15: 17,
  16: 6},
 {0: 3,
  1: 4,
  2: 11,
  3: 6,
  4: 5,
  5: 9,
  6: 13,
  7: 12,
  8: 10,
  9: 14,
  10: 15,
  11: 17,
  12: 1,
  13: 2,
  14: 7,
  15: 16,
  16: 8},
 {0: 4,
  1: 1,
  2: 10,
  3: 12,
  4: 14,
  5: 13,
  6: 5,
  7: 9,
  8: 8,
  9: 6,
  10: 2,
  11: 3,
  12: 7,
  13: 11},
 {0: 3,
  1: 4,
  2: 10,
  3: 26,
  4: 21,
  5: 20,
  6: 18,
  7: 14,
  8: 19,
  9: 27,
  10: 24,
  11: 16,
  12: 17,
  13: 9,
  14: 13,
  15: 8,
  16: 1,
  17: 2,
  18: 11,
  19: 6,
  20: 15,
  21: 23,
  22: 22,
  23: 25,
  24: 12,
  25: 7,
  26: 5},
 {0: 13,
  1: 4,
  2: 10,
  3: 12,
  4: 9,
  5: 1,
  6: 2,
  7: 17,
  8: 8,
  9: 11,
  10: 6,
  11: 5,
  12: 7,
  13: 14,
  14: 16,
  15: 3,
  16: 15},
 {0: 9, 1: 8, 2: 10, 3: 11, 4: 7, 5: 5, 6: 6, 7: 2, 8: 3, 9: 1, 10: 4},
 {0: 10, 1: 6, 2: 11, 3: 7, 4: 8, 5: 3, 6: 4, 7: 9, 8: 1, 9: 2, 10: 5},
 {0: 5,
  1: 4,
  2: 2,
  3: 3,
  4: 14,
  5: 20,
  6: 19,
  7: 17,
  8: 11,
  9: 16,
  10: 18,
  11: 13,
  12: 9,
  13: 7,
  14: 1,
  15: 10,
  16: 8,
  17: 6,
  18: 15,
  19: 12},
 {0: 4,
  1: 1,
  2: 3,
  3: 9,
  4: 14,
  5: 6,
  6: 13,
  7: 5,
  8: 12,
  9: 10,
  10: 7,
  11: 8,
  12: 2,
  13: 15,
  14: 11},
 {0: 17,
  1: 11,
  2: 2,
  3: 1,
  4: 6,
  5: 5,
  6: 7,
  7: 25,
  8: 22,
  9: 21,
  10: 23,
  11: 15,
  12: 10,
  13: 12,
  14: 16,
  15: 20,
  16: 3,
  17: 19,
  18: 14,
  19: 18,
  20: 8,
  21: 4,
  22: 24,
  23: 13,
  24: 9},
 {0: 12,
  1: 11,
  2: 19,
  3: 13,
  4: 10,
  5: 5,
  6: 4,
  7: 6,
  8: 20,
  9: 18,
  10: 9,
  11: 7,
  12: 1,
  13: 2,
  14: 3,
  15: 8,
  16: 15,
  17: 17,
  18: 16,
  19: 14},
 {0: 26,
  1: 20,
  2: 22,
  3: 23,
  4: 24,
  5: 8,
  6: 27,
  7: 5,
  8: 7,
  9: 11,
  10: 15,
  11: 10,
  12: 19,
  13: 17,
  14: 18,
  15: 21,
  16: 6,
  17: 4,
  18: 25,
  19: 13,
  20: 14,
  21: 9,
  22: 1,
  23: 2,
  24: 3,
  25: 12,
  26: 16},
 {0: 48,
  1: 7,
  2: 28,
  3: 9,
  4: 14,
  5: 1,
  6: 2,
  7: 26,
  8: 55,
  9: 22,
  10: 25,
  11: 19,
  12: 38,
  13: 33,
  14: 20,
  15: 8,
  16: 51,
  17: 23,
  18: 12,
  19: 3,
  20: 4,
  21: 39,
  22: 42,
  23: 57,
  24: 46,
  25: 32,
  26: 13,
  27: 35,
  28: 60,
  29: 61,
  30: 37,
  31: 10,
  32: 53,
  33: 50,
  34: 44,
  35: 31,
  36: 49,
  37: 24,
  38: 43,
  39: 17,
  40: 40,
  41: 56,
  42: 47,
  43: 34,
  44: 18,
  45: 27,
  46: 11,
  47: 5,
  48: 16,
  49: 59,
  50: 62,
  51: 15,
  52: 6,
  53: 58,
  54: 41,
  55: 52,
  56: 30,
  57: 36,
  58: 29,
  59: 45,
  60: 21,
  61: 54},
 {0: 3,
  1: 1,
  2: 5,
  3: 2,
  4: 6,
  5: 18,
  6: 9,
  7: 15,
  8: 10,
  9: 8,
  10: 14,
  11: 13,
  12: 11,
  13: 17,
  14: 19,
  15: 7,
  16: 12,
  17: 16,
  18: 4},
 {0: 6,
  1: 5,
  2: 4,
  3: 10,
  4: 18,
  5: 13,
  6: 9,
  7: 8,
  8: 15,
  9: 12,
  10: 7,
  11: 19,
  12: 14,
  13: 17,
  14: 11,
  15: 16,
  16: 20,
  17: 2,
  18: 3,
  19: 1},
 {0: 6,
  1: 8,
  2: 1,
  3: 2,
  4: 11,
  5: 12,
  6: 13,
  7: 10,
  8: 14,
  9: 5,
  10: 3,
  11: 4,
  12: 7,
  13: 9},
 {0: 1,
  1: 2,
  2: 17,
  3: 11,
  4: 6,
  5: 24,
  6: 10,
  7: 14,
  8: 3,
  9: 8,
  10: 4,
  11: 26,
  12: 20,
  13: 23,
  14: 13,
  15: 22,
  16: 21,
  17: 25,
  18: 15,
  19: 19,
  20: 18,
  21: 9,
  22: 16,
  23: 12,
  24: 5,
  25: 7}]

In [167]:
df['score'] = scores

In [168]:
df.to_pickle('gnnsom_results_rank.pickle')

In [169]:
df = pd.read_pickle('gnnsom_results_rank.pickle')
from rdkit import Chem
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new
smiles = df['substrate'].to_list()
smiles = list(map(canonicalsmiles,smiles))
df['substrate'] = smiles
df

,substrate,ec,score
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"(1, 14)","{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(2, 4)","{0: 9, 1: 4, 2: 8, 3: 1, 4: 12, 5: 20, 6: 25, ..."
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"(1, 14)","{0: 9, 1: 1, 2: 8, 3: 2, 4: 22, 5: 16, 6: 17, ..."
3,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"(1, 14)","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,..."
4,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"(1, 14)","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,..."
...,...,...,...
67,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"(1, 14)","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ..."
68,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"(1, 14)","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:..."
69,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"(2, 4)","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ..."
70,O=P1(NCCCl)OCCCN1CCCl,"(1, 14)","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ..."
71,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,"(1, 14)","{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,..."

In [170]:
df.to_pickle('gnnsom_results_rank.pickle')

In [171]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrate', 'score')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': {0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7: 7, 8: 19, 9: 25, 10: 26, 11: 17, 12: 16, 13: 23, 14: 12, 15: 8, 16: 5, 17: 3, 18: 10, 19: 11, 20: 20, 21: 27, 22: 24, 23: 21, 24: 22, 25: 15, 26: 14}, 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': {0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42, 7: 58, 8: 30, 9: 74, 10: 74, 11: 79, 12: 45, 13: 12, 14: 65, 15: 76, 16: 50, 17: 23, 18: 43, 19: 14, 20: 52, 21: 66, 22: 81, 23: 41, 24: 51, 25: 47, 26: 62, 27: 47, 28: 56, 29: 51, 30: 27, 31: 19, 32: 31, 33: 24, 34: 37, 35: 32, 36: 26, 37: 49, 38: 37, 39: 14, 40: 75}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23, 7: 11, 8: 19, 9: 26, 10: 25, 11: 13, 12: 17, 13: 9, 14: 10, 15: 12, 16: 1, 17: 3, 18: 4, 19: 5, 20: 18, 21: 14, 22: 21, 23: 8, 24: 24, 25: 20}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11, 7: 14, 8: 19, 9: 10, 10: 7, 11: 17, 12: 18, 13: 15, 14: 8, 15: 9, 16: 20, 17: 1, 18: 3, 19: 2}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: 23, 7: 28, 8: 3, 9: 12, 10: 43, 11: 55, 12: 38, 13: 49, 14: 52, 15: 22, 16: 44, 17: 18, 18: 2, 19: 13, 20: 15, 21: 61, 22: 56, 23: 53, 24: 39, 25: 9, 26: 41, 27: 46, 28: 51, 29: 40, 30: 54, 31: 35, 32: 47, 33: 36, 34: 1, 35: 4, 36: 5, 37: 59, 38: 30, 39: 10, 40: 11, 41: 58, 42: 50, 43: 60, 44: 14, 45: 16, 46: 19, 47: 37, 48: 31, 49: 48, 50: 17, 51: 7, 52: 33, 53: 24, 54: 6, 55: 26, 56: 57, 57: 27, 58: 21, 59: 8, 60: 25}, 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': {0: 12, 1: 10, 2: 8, 3: 16, 4: 11, 5: 7, 6: 5, 7: 4, 8: 13, 9: 3, 10: 1, 11: 19, 12: 20, 13: 14, 14: 6, 15: 2, 16: 9, 17: 21, 18: 15, 19: 17, 20: 24, 21: 18, 22: 23, 23: 25, 24: 22}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 10, 1: 5, 2: 1, 3: 14, 4: 11, 5: 16, 6: 15, 7: 17, 8: 13, 9: 3, 10: 4, 11: 8, 12: 9, 13: 12, 14: 6, 15: 2, 16: 7}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 21, 1: 4, 2: 6, 3: 17, 4: 20, 5: 16, 6: 19, 7: 18, 8: 14, 9: 22, 10: 2, 11: 1, 12: 8, 13: 3, 14: 15, 15: 10, 16: 12, 17: 5, 18: 7, 19: 11, 20: 13, 21: 9}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 7, 1: 10, 2: 22, 3: 16, 4: 9, 5: 18, 6: 8, 7: 14, 8: 20, 9: 21, 10: 17, 11: 12, 12: 15, 13: 13, 14: 6, 15: 3, 16: 4, 17: 2, 18: 5, 19: 1, 20: 11, 21: 19}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 30, 1: 29, 2: 42, 3: 39, 4: 9, 5: 16, 6: 34, 7: 21, 8: 41, 9: 2, 10: 28, 11: 1, 12: 3, 13: 7, 14: 4, 15: 24, 16: 17, 17: 11, 18: 35, 19: 32, 20: 10, 21: 36, 22: 33, 23: 13, 24: 38, 25: 31, 26: 12, 27: 37, 28: 40, 29: 14, 30: 27, 31: 23, 32: 15, 33: 22, 34: 19, 35: 5, 36: 26, 37: 18, 38: 6, 39: 8, 40: 20, 41: 25}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 6, 1: 2, 2: 10, 3: 12, 4: 20, 5: 15, 6: 25, 7: 19, 8: 17, 9: 23, 10: 14, 11: 31, 12: 18, 13: 4, 14: 7, 15: 21, 16: 24, 17: 30, 18: 27, 19: 28, 20: 3, 21: 1, 22: 9, 23: 16, 24: 5, 25: 8, 26: 11, 27: 13, 28: 29, 29: 26, 30: 22}, 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': {0: 3, 1: 11, 2: 4, 3: 1, 4: 23, 5: 26, 6: 33, 7: 21, 8: 6, 9: 9, 10: 8, 11: 14, 12: 7, 13: 13, 14: 25, 15: 24, 16: 15, 17: 18, 18: 16, 19: 35, 20: 34, 21: 29, 22: 28, 23: 27, 24: 32, 25: 31, 26: 22, 27: 19, 28: 5, 29: 2, 30: 17, 31: 12, 32: 20, 33: 10, 34: 36, 35: 30}, 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': {0: 6, 1: 11, 2: 17, 3: 3, 4: 7, 5: 16, 6: 8, 7: 22, 8: 13, 9: 24, 10: 15, 11: 23, 12: 18, 13: 26, 14: 27, 15: 25, 16: 5, 17: 21, 18: 20, 19: 19, 20: 12, 21: 2, 22: 9, 23: 1, 24: 14, 25: 4, 26: 10}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 9, 1: 10, 2: 17, 3: 8, 4: 11, 5: 16, 6: 20, 7: 6, 8: 2, 9: 15, 10: 18, 11: 19, 12: 14, 13: 7, 14: 5, 15: 1, 16: 12, 17: 13, 18: 3, 19: 4}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 12, 1: 17, 2: 7, 3: 15, 4: 11, 5: 9, 6: 3, 7: 1, 8: 2, 9: 10, 10: 5, 11: 6, 12: 13, 13: 14, 14: 4, 15: 16, 16: 8}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 25, 1: 10, 2: 9, 3: 29, 4: 31, 5: 34, 6: 32, 7: 28, 8: 17, 9: 38, 10: 11, 11: 3, 12: 6, 13: 4, 14: 27, 15: 8, 16: 5, 17: 15, 18: 36, 19: 30, 20: 39, 21: 1, 22: 12, 23: 2, 24: 7, 25: 18, 26: 37, 27: 19, 28: 33, 29: 24, 30: 14, 31: 13, 32: 22, 33: 40, 34: 42, 35: 41, 36: 23, 37: 26, 38: 16, 39: 35, 40: 21, 41: 20}, 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 17, 1: 8, 2: 9, 3: 10, 4: 14, 5: 13, 6: 16, 7: 2, 8: 5, 9: 3, 10: 15, 11: 11, 12: 12, 13: 1, 14: 7, 15: 4, 16: 6, 17: 18, 18: 19}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 28, 1: 15, 2: 12, 3: 2, 4: 27, 5: 4, 6: 7, 7: 11, 8: 20, 9: 23, 10: 21, 11: 22, 12: 19, 13: 6, 14: 16, 15: 10, 16: 3, 17: 5, 18: 17, 19: 1, 20: 8, 21: 26, 22: 13, 23: 9, 24: 14, 25: 18, 26: 29, 27: 24, 28: 25}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 52, 1: 30, 2: 9, 3: 6, 4: 29, 5: 49, 6: 54, 7: 38, 8: 14, 9: 44, 10: 43, 11: 36, 12: 33, 13: 33, 14: 32, 15: 27, 16: 30, 17: 54, 18: 45, 19: 36, 20: 29, 21: 18, 22: 6, 23: 34, 24: 24, 25: 5, 26: 8, 27: 9, 28: 43}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 7, 1: 3, 2: 9, 3: 11, 4: 20, 5: 10, 6: 1, 7: 4, 8: 23, 9: 18, 10: 28, 11: 27, 12: 24, 13: 25, 14: 8, 15: 21, 16: 26, 17: 19, 18: 16, 19: 15, 20: 14, 21: 2, 22: 5, 23: 6, 24: 12, 25: 13, 26: 17, 27: 22, 28: 29}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 3, 1: 1, 2: 2, 3: 12, 4: 14, 5: 11, 6: 10, 7: 19, 8: 7, 9: 5, 10: 9, 11: 15, 12: 21, 13: 18, 14: 17, 15: 20, 16: 13, 17: 6, 18: 4, 19: 8, 20: 16}, 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': {0: 4, 1: 2, 2: 5, 3: 19, 4: 32, 5: 27, 6: 15, 7: 12, 8: 17, 9: 18, 10: 7, 11: 22, 12: 31, 13: 23, 14: 20, 15: 11, 16: 21, 17: 16, 18: 26, 19: 28, 20: 13, 21: 24, 22: 25, 23: 29, 24: 10, 25: 30, 26: 3, 27: 1, 28: 6, 29: 9, 30: 14, 31: 8, 32: 33}, 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': {0: 12, 1: 12, 2: 11, 3: 23, 4: 37, 5: 25, 6: 25, 7: 21, 8: 35, 9: 28, 10: 23, 11: 24, 12: 40, 13: 25, 14: 24, 15: 10, 16: 3, 17: 6, 18: 7, 19: 29}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 2, 1: 3, 2: 23, 3: 18, 4: 17, 5: 15, 6: 12, 7: 19, 8: 6, 9: 13, 10: 1, 11: 4, 12: 16, 13: 22, 14: 9, 15: 11, 16: 20, 17: 10, 18: 8, 19: 7, 20: 14, 21: 21, 22: 5}, 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': {0: 2, 1: 1, 2: 8, 3: 14, 4: 27, 5: 15, 6: 12, 7: 17, 8: 23, 9: 24, 10: 4, 11: 20, 12: 18, 13: 21, 14: 26, 15: 25, 16: 13, 17: 16, 18: 22, 19: 9, 20: 6, 21: 3, 22: 5, 23: 11, 24: 10, 25: 7, 26: 19, 27: 28}, 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': {0: 2, 1: 1, 2: 5, 3: 6, 4: 4, 5: 3, 6: 9, 7: 11, 8: 12, 9: 8, 10: 10, 11: 15, 12: 7, 13: 19, 14: 17, 15: 16, 16: 18, 17: 13, 18: 14}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 3, 1: 2, 2: 7, 3: 22, 4: 23, 5: 18, 6: 24, 7: 15, 8: 11, 9: 14, 10: 12, 11: 16, 12: 19, 13: 6, 14: 1, 15: 4, 16: 5, 17: 9, 18: 17, 19: 20, 20: 21, 21: 10, 22: 13, 23: 8}, 'CN[C@@H](C)[C@@H](O)c1ccccc1': {0: 3, 1: 1, 2: 5, 3: 6, 4: 2, 5: 4, 6: 12, 7: 7, 8: 11, 9: 9, 10: 10, 11: 8}, 'CN[C@@H](C)[C@H](O)c1ccccc1': {0: 2, 1: 1, 2: 5, 3: 9, 4: 3, 5: 4, 6: 12, 7: 8, 8: 10, 9: 11, 10: 6, 11: 7}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 5, 1: 6, 2: 26, 3: 30, 4: 33, 5: 23, 6: 12, 7: 35, 8: 18, 9: 15, 10: 2, 11: 1, 12: 28, 13: 3, 14: 7, 15: 31, 16: 22, 17: 32, 18: 29, 19: 11, 20: 14, 21: 4, 22: 8, 23: 9, 24: 20, 25: 34, 26: 13, 27: 16, 28: 25, 29: 10, 30: 24, 31: 17, 32: 19, 33: 27, 34: 21}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 6, 1: 7, 2: 15, 3: 3, 4: 1, 5: 2, 6: 5, 7: 11, 8: 16, 9: 21, 10: 17, 11: 18, 12: 19, 13: 12, 14: 4, 15: 14, 16: 9, 17: 10, 18: 20, 19: 8, 20: 13}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 1, 1: 4, 2: 13, 3: 7, 4: 22, 5: 18, 6: 6, 7: 8, 8: 5, 9: 2, 10: 9, 11: 14, 12: 24, 13: 30, 14: 12, 15: 10, 16: 25, 17: 15, 18: 29, 19: 21, 20: 17, 21: 26, 22: 19, 23: 23, 24: 20, 25: 27, 26: 28, 27: 3, 28: 11, 29: 16}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 11, 1: 11, 2: 29, 3: 18, 4: 25, 5: 40, 6: 42, 7: 38, 8: 34, 9: 28, 10: 31, 11: 21, 12: 9, 13: 35, 14: 45, 15: 40, 16: 43, 17: 17, 18: 27, 19: 5, 20: 2, 21: 7, 22: 40, 23: 27, 24: 25}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 6, 1: 7, 2: 27, 3: 23, 4: 17, 5: 15, 6: 1, 7: 2, 8: 3, 9: 10, 10: 13, 11: 20, 12: 18, 13: 24, 14: 21, 15: 16, 16: 12, 17: 14, 18: 26, 19: 25, 20: 11, 21: 8, 22: 4, 23: 5, 24: 9, 25: 19, 26: 22}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 1, 1: 4, 2: 10, 3: 11, 4: 13, 5: 18, 6: 16, 7: 5, 8: 3, 9: 17, 10: 6, 11: 9, 12: 15, 13: 2, 14: 12, 15: 7, 16: 8, 17: 14}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 8, 1: 12, 2: 35, 3: 32, 4: 15, 5: 21, 6: 17, 7: 19, 8: 7, 9: 14, 10: 33, 11: 13, 12: 2, 13: 3, 14: 6, 15: 36, 16: 11, 17: 20, 18: 23, 19: 25, 20: 26, 21: 18, 22: 34, 23: 16, 24: 10, 25: 37, 26: 38, 27: 39, 28: 28, 29: 27, 30: 29, 31: 22, 32: 30, 33: 31, 34: 24, 35: 9, 36: 5, 37: 4, 38: 1}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 32, 1: 1, 2: 2, 3: 5, 4: 29, 5: 26, 6: 11, 7: 37, 8: 35, 9: 27, 10: 33, 11: 20, 12: 31, 13: 16, 14: 21, 15: 40, 16: 23, 17: 24, 18: 34, 19: 36, 20: 7, 21: 22, 22: 18, 23: 13, 24: 10, 25: 3, 26: 4, 27: 6, 28: 8, 29: 17, 30: 9, 31: 28, 32: 30, 33: 19, 34: 12, 35: 15, 36: 39, 37: 38, 38: 25, 39: 14}, 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 19, 1: 3, 2: 1, 3: 2, 4: 22, 5: 29, 6: 30, 7: 24, 8: 14, 9: 10, 10: 25, 11: 16, 12: 9, 13: 15, 14: 8, 15: 18, 16: 20, 17: 26, 18: 4, 19: 5, 20: 7, 21: 27, 22: 13, 23: 12, 24: 11, 25: 21, 26: 28, 27: 23, 28: 17, 29: 6}, 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 5, 1: 1, 2: 3, 3: 4, 4: 6, 5: 8, 6: 9, 7: 2, 8: 7, 9: 16, 10: 10, 11: 11, 12: 15, 13: 14, 14: 12, 15: 13}, 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 13, 1: 10, 2: 5, 3: 2, 4: 8, 5: 16, 6: 11, 7: 12, 8: 1, 9: 4, 10: 3, 11: 20, 12: 18, 13: 17, 14: 14, 15: 19, 16: 9, 17: 6, 18: 7, 19: 15, 20: 21, 21: 22}, 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 26, 1: 21, 2: 20, 3: 22, 4: 17, 5: 15, 6: 11, 7: 6, 8: 5, 9: 1, 10: 3, 11: 4, 12: 7, 13: 12, 14: 10, 15: 16, 16: 18, 17: 19, 18: 23, 19: 14, 20: 13, 21: 25, 22: 24, 23: 8, 24: 2, 25: 9}, 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': {0: 19, 1: 25, 2: 16, 3: 26, 4: 18, 5: 8, 6: 11, 7: 31, 8: 22, 9: 7, 10: 13, 11: 24, 12: 23, 13: 14, 14: 12, 15: 17, 16: 20, 17: 1, 18: 2, 19: 10, 20: 29, 21: 27, 22: 3, 23: 4, 24: 6, 25: 15, 26: 21, 27: 5, 28: 9, 29: 32, 30: 30, 31: 28}, 'C[C@H]1[C@H](OC(=O)CCC(=O)O)O[C@@H]2O[C@@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@@]24OO3': {0: 18, 1: 27, 2: 14, 3: 26, 4: 17, 5: 16, 6: 15, 7: 2, 8: 1, 9: 3, 10: 24, 11: 21, 12: 23, 13: 12, 14: 25, 15: 9, 16: 10, 17: 7, 18: 20, 19: 4, 20: 5, 21: 8, 22: 22, 23: 19, 24: 11, 25: 6, 26: 13}, 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': {0: 13, 1: 9, 2: 6, 3: 4, 4: 3, 5: 7, 6: 11, 7: 10, 8: 23, 9: 12, 10: 14, 11: 22, 12: 20, 13: 8, 14: 16, 15: 18, 16: 19, 17: 21, 18: 15, 19: 5, 20: 1, 21: 17, 22: 2}, 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 18, 1: 22, 2: 12, 3: 4, 4: 3, 5: 9, 6: 15, 7: 28, 8: 6, 9: 11, 10: 13, 11: 8, 12: 2, 13: 10, 14: 7, 15: 24, 16: 17, 17: 14, 18: 21, 19: 16, 20: 20, 21: 19, 22: 1, 23: 23, 24: 27, 25: 25, 26: 30, 27: 26, 28: 29, 29: 5}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 9, 1: 16, 2: 30, 3: 27, 4: 29, 5: 2, 6: 11, 7: 35, 8: 30, 9: 21, 10: 24, 11: 38, 12: 44, 13: 19, 14: 27, 15: 16, 16: 23, 17: 28, 18: 10, 19: 8, 20: 32, 21: 27}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 13, 1: 30, 2: 29, 3: 21, 4: 19, 5: 1, 6: 5, 7: 14, 8: 23, 9: 2, 10: 31, 11: 6, 12: 25, 13: 15, 14: 3, 15: 12, 16: 7, 17: 20, 18: 10, 19: 28, 20: 27, 21: 26, 22: 18, 23: 16, 24: 17, 25: 24, 26: 9, 27: 4, 28: 11, 29: 8, 30: 22, 31: 32}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': {0: 13, 1: 28, 2: 21, 3: 17, 4: 10, 5: 1, 6: 5, 7: 7, 8: 6, 9: 27, 10: 23, 11: 22, 12: 26, 13: 14, 14: 19, 15: 18, 16: 12, 17: 24, 18: 9, 19: 3, 20: 4, 21: 8, 22: 2, 23: 11, 24: 20, 25: 16, 26: 15, 27: 25}, 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': {0: 20, 1: 42, 2: 26, 3: 34, 4: 37, 5: 41, 6: 25, 7: 22, 8: 3, 9: 4, 10: 12, 11: 19, 12: 11, 13: 18, 14: 31, 15: 32, 16: 30, 17: 40, 18: 43, 19: 28, 20: 27, 21: 2, 22: 1, 23: 17, 24: 36, 25: 35, 26: 46, 27: 29, 28: 23, 29: 44, 30: 24, 31: 33, 32: 8, 33: 9, 34: 15, 35: 16, 36: 45, 37: 39, 38: 38, 39: 5, 40: 13, 41: 21, 42: 10, 43: 6, 44: 7, 45: 14}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {0: 17, 1: 20, 2: 11, 3: 10, 4: 18, 5: 7, 6: 14, 7: 2, 8: 3, 9: 1, 10: 12, 11: 8, 12: 4, 13: 5, 14: 15, 15: 19, 16: 16, 17: 6, 18: 9, 19: 13}, 'Clc1ccccc1CN1CCc2sccc2C1': {0: 8, 1: 15, 2: 27, 3: 13, 4: 14, 5: 23, 6: 23, 7: 20, 8: 12, 9: 27, 10: 27, 11: 32, 12: 2, 13: 5, 14: 11, 15: 33, 16: 14}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 4, 1: 1, 2: 10, 3: 12, 4: 14, 5: 13, 6: 5, 7: 9, 8: 8, 9: 6, 10: 2, 11: 3, 12: 7, 13: 11}, 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': {0: 3, 1: 4, 2: 10, 3: 26, 4: 21, 5: 20, 6: 18, 7: 14, 8: 19, 9: 27, 10: 24, 11: 16, 12: 17, 13: 9, 14: 13, 15: 8, 16: 1, 17: 2, 18: 11, 19: 6, 20: 15, 21: 23, 22: 22, 23: 25, 24: 12, 25: 7, 26: 5}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 13, 1: 4, 2: 10, 3: 12, 4: 9, 5: 1, 6: 2, 7: 17, 8: 8, 9: 11, 10: 6, 11: 5, 12: 7, 13: 14, 14: 16, 15: 3, 16: 15}, 'NC(=O)c1nc(F)cnc1O': {0: 19, 1: 14, 2: 21, 3: 18, 4: 15, 5: 8, 6: 10, 7: 11, 8: 4, 9: 3, 10: 9}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 5, 1: 4, 2: 2, 3: 3, 4: 14, 5: 20, 6: 19, 7: 17, 8: 11, 9: 16, 10: 18, 11: 13, 12: 9, 13: 7, 14: 1, 15: 10, 16: 8, 17: 6, 18: 15, 19: 12}, 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': {0: 4, 1: 1, 2: 3, 3: 9, 4: 14, 5: 6, 6: 13, 7: 5, 8: 12, 9: 10, 10: 7, 11: 8, 12: 2, 13: 15, 14: 11}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 17, 1: 11, 2: 2, 3: 1, 4: 6, 5: 5, 6: 7, 7: 25, 8: 22, 9: 21, 10: 23, 11: 15, 12: 10, 13: 12, 14: 16, 15: 20, 16: 3, 17: 19, 18: 14, 19: 18, 20: 8, 21: 4, 22: 24, 23: 13, 24: 9}, 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 12, 1: 11, 2: 19, 3: 13, 4: 10, 5: 5, 6: 4, 7: 6, 8: 20, 9: 18, 10: 9, 11: 7, 12: 1, 13: 2, 14: 3, 15: 8, 16: 15, 17: 17, 18: 16, 19: 14}, 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': {0: 26, 1: 20, 2: 22, 3: 23, 4: 24, 5: 8, 6: 27, 7: 5, 8: 7, 9: 11, 10: 15, 11: 10, 12: 19, 13: 17, 14: 18, 15: 21, 16: 6, 17: 4, 18: 25, 19: 13, 20: 14, 21: 9, 22: 1, 23: 2, 24: 3, 25: 12, 26: 16}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, 7: 26, 8: 55, 9: 22, 10: 25, 11: 19, 12: 38, 13: 33, 14: 20, 15: 8, 16: 51, 17: 23, 18: 12, 19: 3, 20: 4, 21: 39, 22: 42, 23: 57, 24: 46, 25: 32, 26: 13, 27: 35, 28: 60, 29: 61, 30: 37, 31: 10, 32: 53, 33: 50, 34: 44, 35: 31, 36: 49, 37: 24, 38: 43, 39: 17, 40: 40, 41: 56, 42: 47, 43: 34, 44: 18, 45: 27, 46: 11, 47: 5, 48: 16, 49: 59, 50: 62, 51: 15, 52: 6, 53: 58, 54: 41, 55: 52, 56: 30, 57: 36, 58: 29, 59: 45, 60: 21, 61: 54}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7: 15, 8: 10, 9: 8, 10: 14, 11: 13, 12: 11, 13: 17, 14: 19, 15: 7, 16: 12, 17: 16, 18: 4}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, 7: 8, 8: 15, 9: 12, 10: 7, 11: 19, 12: 14, 13: 17, 14: 11, 15: 16, 16: 20, 17: 2, 18: 3, 19: 1}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, 7: 10, 8: 14, 9: 5, 10: 3, 11: 4, 12: 7, 13: 9}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10, 7: 14, 8: 3, 9: 8, 10: 4, 11: 26, 12: 20, 13: 23, 14: 13, 15: 22, 16: 21, 17: 25, 18: 15, 19: 19, 20: 18, 21: 9, 22: 16, 23: 12, 24: 5, 25: 7}}

In [172]:
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [173]:
df_total = pd.read_csv('output_65_site_truth_correct.csv')
subs = df_total['substrate'].to_list()
metas = df_total['metabolite'].to_list()
sites = df_total['site_truth'].to_list()
atomidxs = list(map(get_reactive_atom_indices,sites))
df_total['sites'] = atomidxs
df_total

,substrate,metabolite,mapped_rxn,pred_rxn,site_truth,sites
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,[CH:1]#[C:2][C@:3]1([OH:4])[CH2:8][CH2:9][C@H:...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,[3]
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1...,[19]
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,[CH3:1][C:2]([OH:4])([CH2:3]O)[c:5]1[cH:6][cH:...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[40]
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1[CH2:1]C[C@@H](SCC1(CC(=O)O)CC...,[10]
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[32]
...,...,...,...,...,...,...
174,O=P1(NCCCl)OCCCN1CCCl,O=CCCl,O=CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:7]=[CH:8][CH2:5][Cl:6]>>O=P1(NC[CH2:5][Cl:6...,O=P1(NC[CH2:1]Cl)N(CCCl)CC[CH2:1][O:1]1,"[4, 12, 13]"
175,O=P1(NCCCl)OCCCN1CCCl,NP1(=O)OCCCN1CCCl,NP1(=O)OCCCN1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[NH2:3][P:2]1(=[O:1])[O:7][CH2:8][CH2:9][CH2:1...,O=P1([NH:1]CCCl)OCCCN1CCCl,[2]
176,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[O:7][...,O=P1(NCCCl)OCC[CH2:1]N1CCCl,[9]
177,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)NCCCO1,O=P1(NCCCl)NCCCO1>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[NH:11...,O=P1(NCCCl)OCCC[N:1]1CCCl,[10]
178,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1>>O...,O=[C:2]([OH:1])[CH2:3][O:4][CH2:5][CH2:6][N:7]...,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1]

In [174]:
df_total['sites'] = atomidxs
df_total

,substrate,metabolite,mapped_rxn,pred_rxn,site_truth,sites
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,[CH:1]#[C:2][C@:3]1([OH:4])[CH2:8][CH2:9][C@H:...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,[3]
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1...,[19]
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,[CH3:1][C:2]([OH:4])([CH2:3]O)[c:5]1[cH:6][cH:...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[40]
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1[CH2:1]C[C@@H](SCC1(CC(=O)O)CC...,[10]
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[32]
...,...,...,...,...,...,...
174,O=P1(NCCCl)OCCCN1CCCl,O=CCCl,O=CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:7]=[CH:8][CH2:5][Cl:6]>>O=P1(NC[CH2:5][Cl:6...,O=P1(NC[CH2:1]Cl)N(CCCl)CC[CH2:1][O:1]1,"[4, 12, 13]"
175,O=P1(NCCCl)OCCCN1CCCl,NP1(=O)OCCCN1CCCl,NP1(=O)OCCCN1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[NH2:3][P:2]1(=[O:1])[O:7][CH2:8][CH2:9][CH2:1...,O=P1([NH:1]CCCl)OCCCN1CCCl,[2]
176,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[O:7][...,O=P1(NCCCl)OCC[CH2:1]N1CCCl,[9]
177,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)NCCCO1,O=P1(NCCCl)NCCCO1>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[NH:11...,O=P1(NCCCl)OCCC[N:1]1CCCl,[10]
178,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1>>O...,O=[C:2]([OH:1])[CH2:3][O:4][CH2:5][CH2:6][N:7]...,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1]

In [175]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx.pickle')

In [176]:
dict_sub2site = group_by_column_to_dict(df_total,'substrate','sites')
for i in list(dict_sub2site.keys()):
    sitelist = dict_sub2site[i]
    sitelist = [i for k in sitelist for i in k]
    sitelist = list(set(sitelist))
    dict_sub2site[i] = sitelist
dict_sub2site

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [3],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [40,
  32,
  10,
  19],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [1, 4, 5, 22, 23, 25],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [10, 11, 12, 13, 14, 15, 16, 17],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [2,
  7,
  50,
  59,
  60],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [2,
  14,
  15,
  16,
  21],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [6],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [12, 13, 6],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [19],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [11],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [23],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [26,
  7],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [24,
  16],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [2, 15],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [2, 13, 7],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [2],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [2],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [16],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [8, 12, 21, 22, 25],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [6],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [1, 6, 17],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [25,
  5,
  15],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [1, 12, 13, 14, 15, 16, 17, 18, 19],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [19, 12],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [3, 10, 16, 17, 23],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [9, 11, 12],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [1, 2],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [10],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [10],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [34],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [5, 8, 11, 16, 19],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [1, 29],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [17, 19, 22, 7],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [1, 26, 20, 21],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [5, 6, 7, 8, 10, 11, 13, 14, 15, 17],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [35, 22],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [25,
  6],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [11],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [8],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [6, 7, 12, 14, 15],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [3, 4],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [9],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [27],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [21],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [17, 12],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [17, 10, 18, 6],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [30, 23],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [22, 23],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [42,
  45],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [17, 12],
 'Clc1ccccc1CN1CCc2sccc2C1': [8, 11, 12, 13, 14, 15, 16],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [8, 10, 7],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [1, 13, 15, 16, 17, 18],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [],
 'NC(=O)c1nc(F)cnc1O': [7],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [8],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [1],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [1, 2, 7, 15, 16, 20],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [17, 5, 15],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [7],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [30,
  47],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [16, 17, 18],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [16, 17, 18, 19],
 'O=P1(NCCCl)OCCCN1CCCl': [2, 4, 9, 10, 12, 13],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [1]}

In [177]:
df_new = pd.DataFrame()
df_new['substrates'] = list(dict_sub2site.keys())
df_new['true_sites'] = [dict_sub2site[i] for i in list(dict_sub2site.keys())]
df_new['gnn_results'] = [result_new.get(i,'None') for i in list(dict_sub2site.keys())]
df_new

,substrates,true_sites,gnn_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ..."
...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,..."

In [178]:
gnn_result_add = {0: 10,
 1: 24,
 2: 15,
 3: 20,
 4: 18,
 5: 16,
 6: 12,
 7: 3,
 8: 1,
 9: 2,
 10: 14,
 11: 13,
 12: 25,
 13: 26,
 14: 27,
 15: 23,
 16: 17,
 17: 6,
 18: 19,
 19: 5,
 20: 7,
 21: 8,
 22: 21,
 23: 22,
 24: 11,
 25: 4,
 26: 9}
gnn_results_new = df_new['gnn_results'].to_list()
gnn_results_new[38] = gnn_result_add
df_new['gnn_results'] = gnn_results_new
df_new

,substrates,true_sites,gnn_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ..."
...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,..."

In [179]:
df_new.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

2. smartcyp

In [180]:
df = pd.read_pickle('smartcyp_results.pickle')
df

,substrates,enzyme,scores
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,3A4,"{0: 17, 1: 22, 2: 24, 3: 23, 4: 20, 5: 3, 6: 1..."
1,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2D6,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
2,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2C9,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,3A4,"{0: 23, 1: 28, 2: 23, 3: 25, 4: 30, 5: 19, 6: ..."
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,2D6,"{0: 8, 1: 28, 2: 8, 3: 25, 4: 30, 5: 14, 6: 6,..."
...,...,...,...
190,O=P1(NCCCl)OCCCN1CCCl,2D6,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
191,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
192,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,3A4,"{0: 15, 1: 7, 2: 8, 3: 17, 4: 9, 5: 1, 6: 5, 7..."
193,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2D6,"{0: 15, 1: 1, 2: 2, 3: 17, 4: 10, 5: 4, 6: 11,..."
194,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2C9,"{0: 15, 1: 5, 2: 6, 3: 17, 4: 9, 5: 2, 6: 7, 7..."

In [181]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': {0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 53, 7: 15, 8: 27, 9: 42, 10: 43, 11: 31, 12: 6, 13: 75, 14: 29, 15: 63, 16: 56, 17: 53, 18: 9, 19: 24, 20: 10, 21: 40, 22: 35, 23: 34, 24: 78, 25: 18, 26: 40}, 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': {0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: 26, 7: 41, 8: 49, 9: 95, 10: 30, 11: 50, 12: 20, 13: 3, 14: 25, 15: 103, 16: 31, 17: 88, 18: 88, 19: 85, 20: 41, 21: 41, 22: 105, 23: 52, 24: 68, 25: 51, 26: 104, 27: 28, 28: 25, 29: 100, 30: 68, 31: 55, 32: 86, 33: 24, 34: 9, 35: 80, 37: 27, 38: 92, 39: 41, 40: 56}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 53, 7: 36, 8: 33, 9: 55, 10: 55, 11: 28, 12: 24, 13: 18, 14: 33, 15: 54, 16: 51, 17: 47, 18: 47, 19: 34, 20: 13, 21: 12, 22: 12, 23: 13, 24: 33, 25: 36}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: 15, 7: 11, 8: 19, 9: 36, 10: 6, 11: 36, 12: 19, 13: 11, 14: 15, 15: 24, 16: 39, 17: 33, 18: 5, 19: 5}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6: 26, 7: 35, 8: 50, 9: 21, 10: 53, 11: 138, 12: 12, 13: 75, 14: 140, 15: 136, 16: 137, 17: 76, 18: 136, 19: 133, 20: 133, 21: 126, 22: 63, 23: 34, 24: 109, 25: 21, 26: 6, 27: 45, 28: 36, 29: 18, 30: 87, 31: 18, 32: 36, 33: 117, 34: 115, 35: 113, 36: 113, 37: 67, 38: 143, 39: 139, 40: 122, 41: 58, 42: 54, 43: 105, 44: 96, 45: 18, 46: 39, 47: 109, 48: 48, 49: 15, 50: 21, 51: 50, 52: 120, 53: 115, 54: 65, 55: 60, 56: 90, 58: 60, 59: 65, 60: 48}, 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': {0: 21, 1: 48, 2: 21, 3: 6, 4: 14, 5: 19, 6: 32, 7: 56, 8: 53, 9: 7, 10: 14, 11: 53, 12: 23, 13: 17, 14: 42, 15: 38, 16: 17, 17: 23, 18: 54, 19: 50, 20: 29, 21: 16, 22: 47, 23: 45, 24: 41}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 15, 1: 8, 2: 36, 3: 29, 4: 11, 5: 7, 6: 4, 7: 7, 8: 11, 9: 30, 10: 26, 11: 18, 12: 25, 13: 25, 14: 18, 15: 30, 16: 26}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 23, 1: 14, 2: 5, 3: 42, 4: 36, 5: 13, 6: 13, 7: 5, 8: 24, 9: 45, 10: 14, 11: 52, 12: 53, 13: 48, 14: 24, 15: 39, 17: 33, 18: 30, 19: 39, 21: 24}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 19, 1: 9, 2: 13, 3: 20, 4: 25, 5: 28, 6: 31, 7: 14, 8: 51, 9: 39, 10: 39, 11: 51, 12: 22, 13: 31, 14: 50, 15: 12, 16: 13, 17: 46, 18: 13, 19: 46, 20: 39, 21: 39}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 50, 1: 30, 2: 58, 3: 4, 4: 10, 5: 72, 6: 18, 7: 65, 8: 79, 9: 78, 10: 87, 11: 90, 12: 62, 13: 46, 14: 93, 15: 43, 16: 46, 17: 96, 18: 51, 19: 54, 20: 99, 21: 54, 22: 51, 23: 96, 24: 46, 25: 43, 26: 93, 27: 39, 28: 36, 29: 90, 30: 33, 31: 30, 32: 82, 33: 27, 34: 24, 35: 79, 36: 16, 37: 11, 38: 69, 39: 6, 40: 65, 41: 18}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 24, 1: 12, 2: 19, 3: 7, 4: 55, 5: 48, 6: 45, 7: 29, 8: 16, 9: 26, 10: 23, 11: 51, 12: 59, 13: 65, 14: 65, 15: 65, 16: 35, 17: 69, 19: 63, 20: 69, 21: 23, 22: 14, 23: 42, 24: 11, 25: 34, 26: 11, 27: 34, 28: 69, 30: 35}, 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': {0: 60, 1: 41, 2: 16, 3: 3, 4: 94, 5: 50, 6: 91, 7: 13, 8: 6, 9: 38, 10: 33, 11: 92, 12: 54, 13: 41, 14: 75, 16: 78, 18: 57, 19: 89, 20: 64, 21: 65, 22: 69, 23: 30, 24: 44, 25: 26, 26: 81, 27: 14, 28: 11, 29: 72, 30: 21, 31: 81, 32: 25, 33: 95, 34: 88, 35: 47}, 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': {0: 42, 1: 35, 2: 42, 3: 50, 4: 51, 5: 18, 6: 77, 7: 76, 8: 60, 9: 40, 10: 51, 11: 52, 13: 35, 14: 72, 15: 19, 16: 3, 17: 12, 18: 18, 19: 63, 20: 23, 21: 66, 22: 26, 23: 69, 24: 28, 25: 11, 26: 14}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 22, 1: 6, 2: 30, 3: 6, 4: 22, 5: 10, 6: 20, 7: 27, 8: 49, 9: 49, 10: 46, 11: 21, 12: 36, 14: 33, 15: 6, 16: 12, 17: 42, 18: 39, 19: 11}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 18, 1: 5, 2: 24, 3: 5, 4: 18, 5: 9, 6: 19, 7: 39, 8: 34, 9: 34, 10: 31, 11: 17, 12: 10, 13: 27, 14: 6, 15: 10, 16: 17}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 57, 1: 9, 2: 35, 3: 101, 4: 28, 5: 103, 6: 99, 7: 55, 8: 59, 9: 93, 10: 21, 11: 26, 12: 15, 13: 28, 14: 77, 15: 28, 16: 15, 17: 59, 18: 55, 19: 28, 20: 98, 21: 87, 22: 98, 23: 60, 24: 32, 25: 86, 26: 77, 27: 23, 28: 46, 29: 68, 30: 16, 31: 33, 32: 74, 33: 71, 34: 93, 35: 38, 36: 13, 37: 47, 38: 24, 39: 80, 40: 24, 41: 47}, 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 20, 1: 3, 2: 11, 3: 7, 4: 19, 5: 19, 6: 22, 7: 42, 8: 37, 9: 37, 10: 46, 11: 16, 12: 43, 13: 41, 14: 22, 15: 35, 16: 35, 17: 26, 18: 50}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 16, 1: 9, 2: 54, 3: 57, 4: 54, 5: 41, 6: 66, 7: 34, 8: 39, 9: 72, 10: 76, 11: 43, 12: 48, 13: 73, 14: 67, 15: 11, 16: 51, 17: 5, 18: 30, 19: 5, 20: 30, 21: 68, 22: 34, 23: 24, 24: 18, 25: 27, 26: 61, 27: 12, 28: 17}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 28, 1: 23, 2: 53, 3: 60, 4: 53, 5: 67, 6: 67, 7: 17, 8: 5, 9: 48, 10: 22, 11: 25, 12: 13, 13: 25, 14: 22, 15: 36, 16: 22, 17: 60, 18: 23, 19: 48, 21: 47, 22: 43, 23: 59, 24: 14, 25: 39, 26: 6, 27: 6, 28: 66}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 9, 1: 24, 2: 9, 3: 41, 4: 38, 5: 17, 6: 54, 7: 47, 8: 54, 9: 10, 10: 57, 11: 28, 12: 23, 13: 56, 14: 64, 15: 57, 16: 59, 17: 58, 18: 26, 19: 31, 20: 53, 21: 17, 22: 46, 23: 8, 24: 5, 25: 31, 26: 26, 27: 23, 28: 28}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 5, 1: 33, 2: 5, 3: 10, 4: 23, 5: 17, 6: 30, 7: 39, 8: 25, 9: 17, 10: 9, 11: 20, 12: 36, 13: 9, 14: 9, 15: 36, 16: 20, 17: 9, 18: 17, 19: 25, 20: 39}, 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': {0: 3, 1: 12, 2: 3, 3: 46, 4: 9, 5: 19, 6: 49, 7: 46, 8: 63, 9: 56, 10: 21, 11: 25, 12: 30, 13: 31, 14: 16, 15: 36, 16: 9, 17: 9, 18: 68, 19: 60, 20: 59, 21: 45, 22: 23, 23: 42, 24: 69, 25: 59, 26: 86, 27: 75, 28: 85, 29: 80, 30: 79, 31: 72, 32: 68}, 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': {0: 3, 1: 11, 2: 6, 3: 16, 4: 46, 5: 25, 6: 30, 7: 32, 8: 60, 9: 53, 10: 10, 11: 23, 12: 54, 13: 23, 14: 19, 15: 39, 16: 36, 17: 47, 18: 42, 19: 55}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 4, 1: 30, 2: 63, 3: 9, 4: 31, 5: 5, 6: 35, 7: 51, 8: 60, 9: 54, 10: 42, 11: 37, 12: 18, 13: 66, 14: 69, 15: 57, 16: 45, 17: 17, 18: 16, 19: 22, 20: 25, 21: 48, 22: 24}, 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': {0: 4, 1: 41, 2: 60, 3: 57, 4: 66, 5: 33, 6: 12, 7: 30, 8: 34, 9: 79, 10: 5, 11: 80, 12: 44, 13: 39, 14: 77, 15: 77, 16: 19, 17: 15, 18: 63, 19: 46, 20: 29, 21: 21, 22: 45, 23: 17, 24: 54, 25: 70, 26: 76, 27: 25}, 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': {0: 5, 1: 16, 2: 11, 3: 31, 4: 24, 5: 49, 6: 43, 7: 24, 8: 24, 9: 12, 10: 27, 11: 40, 12: 10, 13: 46, 14: 35, 15: 28, 16: 19, 17: 28, 18: 35}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 5, 1: 18, 2: 12, 3: 56, 4: 23, 5: 63, 6: 57, 7: 29, 8: 22, 9: 11, 10: 25, 11: 48, 13: 45, 14: 64, 15: 58, 16: 58, 17: 53, 18: 33, 19: 26, 20: 26, 21: 12, 22: 39, 23: 34}, 'CN[C@@H](C)[C@@H](O)c1ccccc1': {0: 3, 1: 11, 2: 7, 3: 23, 4: 14, 5: 27, 6: 30, 7: 22, 8: 16, 9: 12, 10: 16, 11: 22}, 'CN[C@@H](C)[C@H](O)c1ccccc1': {0: 3, 1: 11, 2: 7, 3: 23, 4: 14, 5: 27, 6: 30, 7: 22, 8: 16, 9: 12, 10: 16, 11: 22}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 5, 1: 87, 2: 79, 3: 92, 4: 83, 5: 32, 6: 20, 7: 68, 8: 22, 9: 63, 10: 40, 11: 54, 12: 4, 13: 48, 14: 48, 15: 18, 16: 17, 17: 74, 18: 36, 19: 29, 20: 73, 21: 76, 22: 42, 23: 20, 24: 51, 25: 48, 26: 9, 27: 60, 28: 57, 29: 28, 30: 84, 31: 79, 32: 38, 33: 38, 34: 38}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 12, 1: 39, 2: 45, 3: 22, 4: 51, 5: 15, 6: 48, 7: 27, 8: 19, 9: 30, 10: 3, 11: 22, 12: 42, 13: 8, 14: 22, 15: 45, 16: 39, 17: 12, 18: 36, 19: 33, 20: 7}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 3, 1: 45, 2: 51, 3: 15, 4: 61, 5: 11, 6: 37, 7: 21, 8: 70, 9: 75, 10: 72, 11: 26, 12: 35, 13: 72, 14: 40, 15: 64, 16: 63, 17: 32, 18: 10, 19: 11, 20: 11, 21: 75, 23: 29, 24: 65, 25: 28, 26: 58, 27: 48, 28: 17, 29: 45}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 9, 1: 51, 2: 54, 3: 25, 4: 38, 5: 63, 6: 25, 7: 12, 8: 45, 9: 21, 10: 9, 11: 22, 12: 69, 13: 66, 14: 28, 15: 28, 16: 57, 17: 3, 18: 60, 19: 32, 20: 22, 21: 48, 22: 41, 23: 38, 24: 25}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 3, 1: 39, 2: 46, 3: 25, 4: 33, 5: 66, 6: 71, 7: 70, 8: 70, 9: 36, 10: 17, 11: 60, 12: 51, 13: 42, 14: 11, 15: 9, 16: 15, 17: 16, 18: 47, 19: 54, 20: 14, 21: 26, 22: 63, 23: 29, 24: 57, 25: 33, 26: 25}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 5, 1: 39, 2: 45, 3: 19, 4: 18, 5: 36, 6: 24, 7: 17, 8: 30, 9: 27, 10: 39, 11: 42, 12: 48, 13: 10, 14: 10, 15: 33, 16: 5, 17: 5}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 3, 1: 56, 2: 59, 3: 19, 4: 10, 5: 14, 6: 29, 7: 68, 8: 85, 9: 85, 10: 89, 11: 48, 12: 94, 13: 93, 14: 93, 15: 85, 16: 45, 17: 40, 18: 65, 19: 56, 20: 30, 21: 30, 22: 30, 23: 40, 24: 45, 25: 36, 26: 75, 27: 65, 28: 23, 29: 37, 30: 25, 31: 37, 32: 23, 33: 31, 34: 78, 35: 72, 36: 12, 37: 6, 38: 51}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 14, 1: 83, 2: 76, 3: 76, 4: 31, 5: 13, 6: 28, 7: 19, 8: 93, 9: 49, 10: 50, 11: 96, 12: 103, 13: 49, 14: 39, 15: 87, 16: 28, 17: 60, 18: 31, 19: 98, 20: 25, 21: 93, 22: 53, 23: 34, 24: 85, 25: 94, 26: 13, 27: 76, 28: 30, 29: 30, 30: 21, 31: 71, 33: 33, 34: 88, 36: 56, 37: 103, 38: 53, 39: 104}, 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 35, 1: 13, 2: 70, 3: 69, 4: 27, 5: 73, 6: 70, 7: 29, 8: 44, 9: 48, 10: 20, 11: 27, 12: 7, 13: 12, 14: 7, 15: 27, 16: 34, 17: 41, 18: 22, 19: 63, 20: 7, 21: 60, 22: 54, 24: 24, 25: 18, 26: 51, 28: 57}, 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': {0: 26, 1: 16, 2: 19, 3: 28, 4: 33, 5: 36, 6: 43, 7: 36, 8: 71, 9: 71, 10: 66, 11: 24, 12: 18, 13: 58, 14: 58, 15: 54, 16: 69, 17: 3, 18: 64, 19: 55, 20: 33, 21: 9, 22: 12, 23: 24, 24: 61, 25: 58, 26: 52}, 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 24, 1: 4, 2: 10, 3: 31, 4: 18, 5: 18, 6: 18, 7: 39, 8: 36, 9: 32, 10: 14, 11: 14, 12: 7, 13: 27, 15: 17}, 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 36, 1: 25, 2: 8, 3: 14, 4: 5, 5: 24, 6: 21, 7: 42, 8: 60, 9: 54, 10: 54, 11: 57, 12: 32, 13: 27, 14: 15, 15: 48, 16: 29, 17: 11, 18: 26, 19: 45, 21: 51}, 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 22, 1: 14, 2: 14, 3: 51, 4: 57, 5: 52, 6: 22, 7: 9, 8: 17, 9: 11, 10: 4, 11: 17, 12: 9, 13: 54, 15: 25, 16: 52, 17: 48, 18: 43, 19: 45, 20: 41, 21: 43, 22: 37, 23: 27, 24: 56, 25: 52}, 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': {0: 42, 1: 29, 2: 23, 3: 32, 4: 26, 5: 18, 6: 8, 7: 58, 8: 23, 9: 51, 10: 48, 11: 20, 12: 3, 13: 68, 14: 37, 15: 75, 17: 11, 18: 72, 19: 27, 20: 80, 21: 45, 22: 74, 23: 69, 24: 72, 25: 64, 26: 16, 27: 65, 28: 62, 29: 59, 30: 54, 31: 54}, 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': {0: 42, 1: 63, 2: 3, 3: 23, 4: 48, 5: 45, 6: 54, 8: 60, 9: 8, 10: 29, 11: 32, 12: 36, 13: 29, 14: 20, 15: 57, 16: 29, 17: 23, 18: 13, 19: 7, 20: 51, 21: 21, 22: 45}, 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 24, 1: 68, 2: 40, 3: 76, 4: 41, 5: 16, 6: 41, 7: 27, 8: 27, 9: 16, 10: 36, 11: 14, 12: 76, 13: 69, 14: 58, 15: 36, 16: 14, 17: 3, 18: 19, 19: 55, 20: 41, 21: 16, 22: 61, 23: 71, 24: 46, 25: 39, 26: 24, 27: 39, 28: 46, 29: 56}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 9, 1: 48, 2: 37, 3: 57, 4: 54, 5: 22, 6: 25, 7: 45, 8: 33, 9: 13, 10: 18, 11: 30, 12: 51, 13: 39, 14: 60, 15: 31, 16: 14, 17: 23, 18: 15, 19: 6, 20: 23, 21: 14}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 9, 1: 63, 2: 24, 3: 36, 4: 72, 5: 50, 6: 36, 7: 14, 8: 14, 9: 36, 10: 79, 11: 80, 12: 82, 13: 53, 14: 37, 15: 6, 16: 20, 17: 77, 18: 57, 19: 69, 20: 18, 21: 60, 23: 17, 24: 30, 25: 66, 26: 82, 27: 3, 28: 34, 29: 40, 30: 49, 31: 37}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': {0: 3, 1: 39, 2: 15, 3: 25, 4: 51, 5: 57, 6: 56, 7: 56, 8: 30, 9: 56, 10: 24, 11: 17, 12: 54, 13: 50, 14: 54, 15: 14, 16: 21, 17: 42, 18: 10, 19: 6, 20: 36, 21: 33, 22: 6, 23: 10, 24: 17, 25: 24, 26: 25, 27: 15}, 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': {0: 6, 1: 85, 2: 32, 3: 14, 4: 32, 5: 85, 6: 6, 7: 88, 8: 98, 9: 10, 10: 95, 11: 103, 12: 70, 13: 20, 14: 26, 15: 100, 16: 63, 17: 57, 18: 48, 19: 57, 20: 63, 21: 15, 22: 108, 23: 46, 24: 24, 25: 27, 26: 94, 27: 60, 28: 51, 29: 41, 30: 51, 31: 60, 32: 76, 33: 103, 34: 101, 35: 54, 36: 47, 37: 60, 38: 60, 39: 71, 40: 37, 41: 28, 42: 10, 43: 60, 44: 93, 45: 92}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {1: 39, 2: 19, 3: 26, 4: 42, 5: 14, 6: 26, 7: 16, 8: 45, 9: 18, 10: 29, 11: 11, 12: 36, 13: 5, 14: 20, 15: 14, 16: 20, 17: 5, 18: 26, 19: 19}, 'Clc1ccccc1CN1CCc2sccc2C1': {1: 44, 2: 30, 3: 23, 4: 27, 5: 36, 6: 48, 7: 13, 8: 19, 9: 6, 10: 18, 11: 39, 12: 12, 13: 15, 14: 26, 15: 43, 16: 9}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 9, 1: 41, 2: 34, 3: 25, 4: 30, 5: 29, 6: 16, 7: 5, 8: 17, 9: 4, 10: 38, 11: 12, 12: 27, 13: 28}, 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': {0: 5, 1: 35, 2: 27, 3: 36, 4: 64, 5: 67, 6: 35, 7: 34, 8: 71, 9: 72, 10: 21, 11: 24, 12: 66, 13: 35, 14: 11, 15: 9, 16: 5, 17: 51, 18: 54, 19: 57, 20: 54, 21: 27, 22: 65, 24: 44, 25: 21, 26: 39}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 10, 1: 30, 2: 27, 3: 33, 4: 12, 5: 24, 6: 7, 7: 39, 8: 36, 10: 10, 11: 6, 12: 10, 13: 36, 15: 21, 16: 18}, 'NC(=O)c1nc(F)cnc1O': {0: 9, 1: 24, 2: 20, 3: 27, 4: 8, 5: 18, 7: 10, 8: 3, 9: 21, 10: 15}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 8, 1: 42, 2: 8, 3: 24, 4: 47, 5: 32, 6: 48, 7: 16, 8: 4, 9: 15, 10: 21, 11: 49, 12: 11, 13: 45, 14: 45, 15: 25, 16: 39, 17: 39, 18: 24, 19: 18}, 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': {0: 6, 1: 4, 2: 13, 3: 38, 4: 13, 5: 28, 6: 25, 7: 22, 8: 18, 9: 9, 10: 33, 12: 30, 13: 30, 14: 27}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 66, 1: 62, 2: 36, 3: 53, 4: 7, 5: 4, 6: 43, 7: 66, 8: 27, 9: 16, 10: 53, 11: 12, 12: 33, 13: 8, 14: 38, 15: 63, 16: 23, 17: 57, 18: 28, 19: 19, 20: 44, 22: 22, 23: 48}, 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 30, 1: 36, 2: 20, 3: 11, 4: 3, 5: 39, 6: 8, 7: 44, 8: 43, 9: 19, 10: 15, 11: 33, 12: 27, 13: 24, 14: 24, 15: 15, 16: 19, 17: 8}, 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': {0: 41, 1: 41, 2: 37, 3: 10, 4: 13, 5: 50, 6: 45, 7: 56, 8: 18, 9: 10, 10: 27, 11: 46, 12: 49, 13: 16, 16: 5, 17: 54, 18: 49, 19: 21, 20: 15, 21: 38, 22: 35, 23: 30, 24: 30, 25: 15, 26: 21}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: 68, 7: 63, 8: 76, 9: 24, 10: 18, 11: 18, 12: 76, 13: 24, 14: 59, 15: 49, 16: 64, 17: 64, 18: 30, 19: 56, 20: 68, 21: 63, 22: 53, 23: 68, 24: 66, 25: 66, 26: 68, 27: 7, 28: 45, 29: 12, 30: 4, 31: 36, 32: 7, 33: 36, 34: 12, 35: 39, 36: 15, 37: 42, 38: 27, 39: 33, 40: 21, 41: 73, 42: 73, 43: 21, 44: 33, 45: 27, 46: 66, 47: 68, 48: 7, 49: 45, 50: 12, 51: 4, 52: 36, 53: 7, 54: 36, 55: 12, 56: 39, 57: 15, 58: 42, 59: 66, 60: 53, 61: 68}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19, 7: 17, 8: 8, 9: 17, 10: 19, 11: 45, 12: 22, 13: 36, 15: 11, 16: 20, 17: 39, 18: 27}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: 36, 8: 22, 9: 48, 10: 51, 11: 45, 12: 19, 13: 17, 14: 8, 15: 17, 16: 19, 17: 8, 18: 3, 19: 39}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 18, 8: 21, 9: 3, 10: 12, 11: 9, 12: 27}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 23, 7: 12, 8: 16, 9: 26, 10: 11, 11: 54, 12: 39, 13: 31, 14: 24, 15: 31, 16: 39, 17: 57, 18: 42, 19: 27, 20: 48, 22: 27, 23: 42, 24: 16, 25: 12}}

In [182]:
df_total = pd.read_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
smartcyp_results = [result_new[i] for i in substrates]
df_total['smartcyp_results'] = smartcyp_results
df_total

,substrates,true_sites,gnn_results,smartcyp_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2..."

In [183]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

3. somp

In [184]:
df = pd.read_pickle('somp_results.pickle')
df

,substrates,enzyme,scores
0,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 6, 1: 12, 2: 7, 3: 3, 4: 14, 5: 8, 6: 10, ..."
1,Clc1ccccc1CN1CCc2sccc2C1,UGT,"{0: 2, 1: 13, 2: 9, 3: 7, 4: 5, 5: 8, 6: 17, 7..."
2,Cn1c(=O)c2c(ncn2C)n(C)c1=O,3A4,"{0: 3, 1: 11, 2: 12, 3: 6, 4: 13, 5: 14, 6: 9,..."
3,Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)...,2C9,"{0: 5, 1: 48, 2: 28, 3: 7, 4: 29, 5: 49, 6: 6,..."
4,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,1A2,"{0: 45, 1: 27, 2: 55, 3: 41, 4: 13, 5: 21, 6: ..."
...,...,...,...
385,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,UGT,"{0: 6, 1: 20, 2: 15, 3: 2, 4: 16, 5: 13, 6: 7,..."
386,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,3A4,"{0: 13, 1: 1, 2: 6, 3: 31, 4: 23, 5: 7, 6: 11,..."
387,CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([...,2D6,"{0: 4, 1: 5, 2: 28, 3: 2, 4: 33, 5: 34, 6: 35,..."
388,NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1,3A4,"{0: 18, 1: 16, 2: 19, 3: 17, 4: 14, 5: 12, 6: ..."
389,Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1,UGT,"{0: 6, 1: 8, 2: 9, 3: 13, 4: 10, 5: 3, 6: 2, 7..."

In [185]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': {0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, 6: 124, 7: 52, 8: 85, 9: 168, 10: 48, 11: 147, 12: 54, 13: 82, 14: 28, 15: 146, 16: 102, 17: 82, 18: 62, 19: 115, 20: 32, 21: 71, 22: 146, 23: 60, 24: 157, 25: 66, 26: 85, 27: 51, 28: 183, 29: 52, 30: 56}, 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': {0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98, 6: 34, 7: 36, 8: 106, 9: 185, 10: 58, 11: 105, 12: 114, 13: 62, 14: 12, 15: 158, 16: 185, 17: 136, 18: 145, 19: 171, 20: 198, 21: 77, 22: 83, 23: 187, 24: 72, 25: 54, 26: 129, 27: 189, 28: 103, 29: 92, 30: 213, 31: 124, 32: 102, 33: 241, 34: 80, 35: 56, 36: 202, 37: 184, 38: 163, 39: 227, 40: 190, 41: 142}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6: 131, 7: 79, 8: 77, 9: 107, 10: 140, 11: 80, 12: 38, 13: 40, 14: 84, 15: 141, 16: 61, 17: 94, 18: 100, 19: 109, 20: 19, 21: 85, 22: 91, 23: 25, 24: 83, 25: 85}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6: 38, 7: 28, 8: 61, 9: 93, 10: 18, 11: 99, 12: 67, 13: 34, 14: 46, 15: 67, 16: 113, 17: 71, 18: 9, 19: 15}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160, 6: 49, 7: 79, 8: 208, 9: 246, 10: 241, 11: 313, 12: 245, 13: 175, 14: 277, 15: 270, 16: 178, 17: 304, 18: 131, 19: 240, 20: 246, 21: 296, 22: 159, 23: 159, 24: 300, 25: 159, 26: 93, 27: 176, 28: 101, 29: 35, 30: 199, 31: 41, 32: 107, 33: 319, 34: 230, 35: 196, 36: 202, 37: 201, 38: 307, 39: 282, 40: 183, 41: 225, 42: 208, 43: 283, 44: 234, 45: 78, 46: 174, 47: 136, 48: 239, 49: 198, 50: 322, 51: 252, 52: 214, 53: 205, 54: 198, 55: 118, 56: 104, 57: 253, 58: 253, 59: 110, 60: 124, 61: 60}, 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': {0: 38, 1: 107, 2: 44, 3: 35, 4: 91, 5: 35, 6: 71, 7: 41, 8: 113, 9: 134, 10: 102, 11: 95, 12: 47, 13: 104, 14: 144, 15: 93, 16: 41, 17: 126, 18: 140, 19: 47, 20: 99, 21: 119, 22: 98, 23: 104, 24: 106, 25: 53, 26: 129, 27: 116, 28: 138}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 26, 1: 36, 2: 86, 3: 68, 4: 44, 5: 22, 6: 13, 7: 28, 8: 50, 9: 83, 10: 43, 11: 80, 12: 64, 13: 51, 14: 86, 15: 89, 16: 49}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 27, 1: 20, 2: 91, 3: 99, 4: 67, 5: 45, 6: 30, 7: 28, 8: 44, 9: 107, 10: 105, 11: 55, 12: 83, 13: 87, 14: 83, 15: 86, 16: 54, 17: 81, 18: 85, 19: 92, 20: 60, 21: 89}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 27, 1: 29, 2: 55, 3: 46, 4: 63, 5: 66, 6: 51, 7: 35, 8: 114, 9: 86, 10: 92, 11: 98, 12: 39, 13: 63, 14: 92, 15: 90, 16: 23, 17: 106, 18: 29, 19: 112, 20: 98, 21: 104}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 140, 1: 102, 2: 157, 3: 65, 4: 144, 5: 189, 6: 160, 7: 172, 8: 224, 9: 174, 10: 188, 11: 219, 12: 45, 13: 124, 14: 159, 15: 35, 16: 41, 17: 165, 18: 47, 19: 53, 20: 171, 21: 59, 22: 65, 23: 177, 24: 71, 25: 77, 26: 183, 27: 83, 28: 89, 29: 189, 30: 95, 31: 101, 32: 195, 33: 107, 34: 113, 35: 201, 36: 107, 37: 136, 38: 218, 39: 34, 40: 178, 41: 166}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 37, 1: 35, 2: 60, 3: 64, 4: 154, 5: 149, 6: 141, 7: 88, 8: 47, 9: 60, 10: 102, 11: 169, 12: 180, 13: 150, 14: 113, 15: 125, 16: 111, 17: 137, 18: 80, 19: 117, 20: 134, 21: 65, 22: 49, 23: 59, 24: 24, 25: 72, 26: 30, 27: 78, 28: 143, 29: 86, 30: 117}, 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': {0: 47, 1: 63, 2: 161, 3: 21, 4: 178, 5: 173, 6: 195, 7: 166, 8: 113, 9: 55, 10: 99, 11: 159, 12: 61, 13: 219, 14: 123, 15: 95, 16: 204, 17: 185, 18: 227, 19: 174, 20: 124, 21: 134, 22: 125, 23: 111, 24: 134, 25: 113, 26: 67, 27: 143, 28: 119, 29: 73, 30: 210, 31: 31, 32: 37, 33: 203, 34: 79, 35: 79, 36: 197, 37: 130, 38: 85, 39: 184, 40: 151, 41: 171}, 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': {0: 39, 1: 60, 2: 55, 3: 165, 4: 52, 5: 156, 6: 155, 7: 58, 8: 182, 9: 149, 10: 179, 11: 96, 12: 124, 13: 63, 14: 120, 15: 146, 16: 64, 17: 150, 18: 138, 19: 70, 20: 20, 21: 126, 22: 100, 23: 76, 24: 145, 25: 78, 26: 82, 27: 152, 28: 91, 29: 88, 30: 157, 31: 109, 32: 30, 33: 95}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 38, 1: 15, 2: 43, 3: 21, 4: 44, 5: 33, 6: 44, 7: 77, 8: 97, 9: 67, 10: 108, 11: 74, 12: 99, 13: 73, 14: 100, 15: 45, 16: 61, 17: 106, 18: 90, 19: 25}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 46, 1: 14, 2: 55, 3: 20, 4: 52, 5: 28, 6: 32, 7: 88, 8: 82, 9: 74, 10: 87, 11: 65, 12: 39, 13: 79, 14: 41, 15: 45, 16: 71}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 97, 1: 33, 2: 156, 3: 157, 4: 137, 5: 224, 6: 212, 7: 110, 8: 136, 9: 228, 10: 58, 11: 61, 12: 95, 13: 75, 14: 162, 15: 81, 16: 101, 17: 142, 18: 118, 19: 181, 20: 219, 21: 234, 22: 201, 23: 216, 24: 142, 25: 207, 26: 155, 27: 33, 28: 86, 29: 170, 30: 56, 31: 179, 32: 76, 33: 179, 34: 143, 35: 204, 36: 66, 37: 102, 38: 99, 39: 35, 40: 162, 41: 41, 42: 107}, 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 61, 1: 25, 2: 87, 3: 68, 4: 26, 5: 83, 6: 81, 7: 32, 8: 42, 9: 44, 10: 63, 11: 69, 12: 84, 13: 24, 14: 105, 15: 93, 16: 86, 17: 76, 18: 82, 19: 55, 20: 100}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 58, 1: 40, 2: 148, 3: 112, 4: 124, 5: 131, 6: 143, 7: 57, 8: 104, 9: 136, 10: 145, 11: 80, 12: 121, 13: 89, 14: 95, 15: 32, 16: 86, 17: 18, 18: 80, 19: 24, 20: 86, 21: 149, 22: 87, 23: 48, 24: 41, 25: 85, 26: 157, 27: 64, 28: 70}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 75, 1: 49, 2: 145, 3: 128, 4: 123, 5: 165, 6: 160, 7: 89, 8: 18, 9: 123, 10: 86, 11: 64, 12: 54, 13: 70, 14: 92, 15: 80, 16: 34, 17: 96, 18: 84, 19: 111, 20: 97, 21: 134, 22: 126, 23: 136, 24: 43, 25: 68, 26: 16, 27: 22, 28: 122}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 15, 1: 55, 2: 21, 3: 74, 4: 107, 5: 27, 6: 136, 7: 101, 8: 111, 9: 55, 10: 130, 11: 98, 12: 49, 13: 86, 14: 149, 15: 62, 16: 112, 17: 131, 18: 100, 19: 64, 20: 118, 21: 108, 22: 135, 23: 120, 24: 111, 25: 70, 26: 106, 27: 55, 28: 104}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 8, 1: 46, 2: 14, 3: 30, 4: 102, 5: 46, 6: 90, 7: 111, 8: 83, 9: 42, 10: 29, 11: 69, 12: 107, 13: 62, 14: 68, 15: 113, 16: 75, 17: 35, 18: 50, 19: 89, 20: 117}, 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': {0: 19, 1: 76, 2: 25, 3: 114, 4: 81, 5: 64, 6: 172, 7: 173, 8: 135, 9: 160, 10: 69, 11: 123, 12: 49, 13: 89, 14: 134, 15: 55, 16: 74, 17: 61, 18: 100, 19: 31, 20: 37, 21: 134, 22: 138, 23: 119, 24: 152, 25: 137, 26: 139, 27: 137, 28: 108, 29: 110, 30: 145, 31: 183, 32: 152, 33: 158, 34: 191, 35: 152}, 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': {0: 12, 1: 68, 2: 30, 3: 36, 4: 96, 5: 39, 6: 23, 7: 42, 8: 96, 9: 123, 10: 76, 11: 41, 12: 69, 13: 86, 14: 58, 15: 38, 16: 72, 17: 101, 18: 88, 19: 93, 20: 99}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 11, 1: 57, 2: 108, 3: 66, 4: 41, 5: 21, 6: 79, 7: 124, 8: 116, 9: 99, 10: 80, 11: 73, 12: 42, 13: 113, 14: 99, 15: 107, 16: 42, 17: 116, 18: 64, 19: 38, 20: 26, 21: 64, 22: 136, 23: 78}, 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': {0: 16, 1: 131, 2: 104, 3: 114, 4: 137, 5: 64, 6: 35, 7: 38, 8: 52, 9: 139, 10: 15, 11: 100, 12: 75, 13: 66, 14: 120, 15: 121, 16: 90, 17: 81, 18: 168, 19: 106, 20: 86, 21: 53, 22: 135, 23: 107, 24: 107, 25: 97, 26: 42, 27: 136, 28: 75}, 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': {0: 12, 1: 74, 2: 68, 3: 109, 4: 39, 5: 44, 6: 98, 7: 101, 8: 73, 9: 42, 10: 28, 11: 68, 12: 96, 13: 23, 14: 98, 15: 76, 16: 46, 17: 31, 18: 52, 19: 82}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 13, 1: 94, 2: 50, 3: 94, 4: 61, 5: 101, 6: 140, 7: 61, 8: 48, 9: 38, 10: 76, 11: 132, 12: 120, 13: 84, 14: 24, 15: 66, 16: 72, 17: 114, 18: 79, 19: 39, 20: 95, 21: 35, 22: 102, 23: 62}, 'CN[C@@H](C)[C@@H](O)c1ccccc1': {0: 10, 1: 67, 2: 42, 3: 34, 4: 59, 5: 33, 6: 40, 7: 68, 8: 72, 9: 54, 10: 32, 11: 21, 12: 38, 13: 60}, 'CN[C@@H](C)[C@H](O)c1ccccc1': {0: 10, 1: 67, 2: 42, 3: 34, 4: 59, 5: 33, 6: 40, 7: 68, 8: 72, 9: 54, 10: 32, 11: 21, 12: 38, 13: 60}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 19, 1: 152, 2: 188, 3: 174, 4: 141, 5: 52, 6: 61, 7: 145, 8: 81, 9: 128, 10: 132, 11: 45, 12: 112, 13: 96, 14: 102, 15: 52, 16: 72, 17: 134, 18: 62, 19: 118, 20: 174, 21: 176, 22: 123, 23: 82, 24: 179, 25: 123, 26: 180, 27: 40, 28: 202, 29: 135, 30: 118, 31: 179, 32: 81, 33: 40, 34: 46, 35: 52}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 16, 1: 100, 2: 98, 3: 59, 4: 67, 5: 30, 6: 65, 7: 52, 8: 52, 9: 102, 10: 59, 11: 76, 12: 78, 13: 43, 14: 65, 15: 104, 16: 106, 17: 22, 18: 74, 19: 96, 20: 22}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 16, 1: 143, 2: 153, 3: 96, 4: 162, 5: 95, 6: 106, 7: 61, 8: 131, 9: 114, 10: 68, 11: 52, 12: 56, 13: 108, 14: 100, 15: 32, 16: 85, 17: 117, 18: 42, 19: 28, 20: 34, 21: 127, 22: 89, 23: 62, 24: 177, 25: 87, 26: 146, 27: 132, 28: 80, 29: 91}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 15, 1: 112, 2: 74, 3: 40, 4: 72, 5: 111, 6: 83, 7: 41, 8: 95, 9: 108, 10: 47, 11: 47, 12: 112, 13: 135, 14: 64, 15: 46, 16: 87, 17: 111, 18: 112, 19: 95, 20: 46, 21: 74, 22: 99, 23: 78, 24: 46}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 17, 1: 135, 2: 110, 3: 64, 4: 80, 5: 121, 6: 36, 7: 88, 8: 94, 9: 100, 10: 64, 11: 122, 12: 132, 13: 39, 14: 154, 15: 67, 16: 38, 17: 30, 18: 65, 19: 160, 20: 123, 21: 53, 22: 86, 23: 125, 24: 83, 25: 94, 26: 86, 27: 70}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 9, 1: 82, 2: 71, 3: 33, 4: 41, 5: 80, 6: 54, 7: 59, 8: 73, 9: 66, 10: 86, 11: 96, 12: 99, 13: 31, 14: 42, 15: 32, 16: 33, 17: 39}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 27, 1: 188, 2: 188, 3: 85, 4: 61, 5: 63, 6: 100, 7: 156, 8: 163, 9: 160, 10: 187, 11: 193, 12: 105, 13: 149, 14: 155, 15: 188, 16: 111, 17: 111, 18: 159, 19: 85, 20: 56, 21: 62, 22: 68, 23: 117, 24: 117, 25: 97, 26: 123, 27: 134, 28: 113, 29: 131, 30: 39, 31: 137, 32: 119, 33: 131, 34: 165, 35: 181, 36: 38, 37: 46, 38: 172}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 90, 1: 18, 2: 78, 3: 84, 4: 134, 5: 49, 6: 128, 7: 81, 8: 161, 9: 57, 10: 101, 11: 209, 12: 194, 13: 104, 14: 85, 15: 189, 16: 92, 17: 110, 18: 104, 19: 190, 20: 163, 21: 171, 22: 99, 23: 88, 24: 136, 25: 143, 26: 40, 27: 164, 28: 90, 29: 38, 30: 69, 31: 191, 32: 169, 33: 120, 34: 193, 35: 141, 36: 122, 37: 217, 38: 119, 39: 189}, 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 56, 1: 26, 2: 27, 3: 143, 4: 129, 5: 82, 6: 96, 7: 69, 8: 72, 9: 83, 10: 99, 11: 65, 12: 144, 13: 72, 14: 97, 15: 78, 16: 150, 17: 49, 18: 112, 19: 72, 20: 163, 21: 62, 22: 152, 23: 155, 24: 121, 25: 50, 26: 69, 27: 130, 28: 113, 29: 149, 30: 91}, 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': {0: 45, 1: 125, 2: 45, 3: 65, 4: 50, 5: 135, 6: 51, 7: 139, 8: 57, 9: 36, 10: 98, 11: 63, 12: 152, 13: 122, 14: 132, 15: 134, 16: 145, 17: 156, 18: 155, 19: 159, 20: 132, 21: 122, 22: 69, 23: 144, 24: 88, 25: 47, 26: 52, 27: 47, 28: 158, 29: 75, 30: 143, 31: 116, 32: 109}, 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 53, 1: 48, 2: 29, 3: 84, 4: 46, 5: 10, 6: 16, 7: 22, 8: 93, 9: 67, 10: 89, 11: 64, 12: 37, 13: 41, 14: 81, 15: 69, 16: 69}, 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 48, 1: 61, 2: 32, 3: 90, 4: 85, 5: 62, 6: 69, 7: 18, 8: 102, 9: 30, 10: 69, 11: 75, 12: 115, 13: 52, 14: 38, 15: 58, 16: 105, 17: 102, 18: 16, 19: 101, 20: 109, 21: 93, 22: 126}, 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 40, 1: 79, 2: 29, 3: 55, 4: 110, 5: 95, 6: 114, 7: 61, 8: 59, 9: 80, 10: 12, 11: 17, 12: 86, 13: 65, 14: 146, 15: 89, 16: 73, 17: 97, 18: 148, 19: 92, 20: 158, 21: 47, 22: 104, 23: 126, 24: 81, 25: 90, 26: 115}, 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': {0: 45, 1: 110, 2: 31, 3: 96, 4: 165, 5: 37, 6: 177, 7: 43, 8: 89, 9: 26, 10: 184, 11: 118, 12: 176, 13: 155, 14: 79, 15: 127, 16: 189, 17: 79, 18: 204, 19: 121, 20: 90, 21: 49, 22: 161, 23: 109, 24: 189, 25: 85, 26: 191, 27: 146, 28: 153, 29: 115, 30: 36, 31: 115, 32: 84, 33: 88, 34: 64, 35: 70}, 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': {0: 46, 1: 135, 2: 69, 3: 56, 4: 102, 5: 102, 6: 112, 7: 91, 8: 99, 9: 21, 10: 51, 11: 122, 12: 25, 13: 140, 14: 31, 15: 57, 16: 47, 17: 139, 18: 72, 19: 140, 20: 37, 21: 63, 22: 34, 23: 124, 24: 68, 25: 123}, 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 38, 1: 152, 2: 92, 3: 157, 4: 97, 5: 114, 6: 78, 7: 83, 8: 108, 9: 40, 10: 102, 11: 118, 12: 115, 13: 46, 14: 143, 15: 119, 16: 104, 17: 66, 18: 115, 19: 15, 20: 70, 21: 140, 22: 86, 23: 122, 24: 151, 25: 152, 26: 112, 27: 58, 28: 34, 29: 64, 30: 118, 31: 159}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 24, 1: 73, 2: 68, 3: 104, 4: 108, 5: 25, 6: 97, 7: 106, 8: 60, 9: 32, 10: 33, 11: 74, 12: 121, 13: 103, 14: 119, 15: 70, 16: 73, 17: 55, 18: 18, 19: 15, 20: 61, 21: 79}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 26, 1: 137, 2: 71, 3: 65, 4: 96, 5: 95, 6: 75, 7: 77, 8: 83, 9: 81, 10: 157, 11: 31, 12: 116, 13: 92, 14: 60, 15: 60, 16: 67, 17: 138, 18: 137, 19: 171, 20: 121, 21: 176, 22: 169, 23: 44, 24: 88, 25: 165, 26: 158, 27: 41, 28: 105, 29: 108, 30: 64, 31: 94}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': {0: 11, 1: 84, 2: 52, 3: 89, 4: 139, 5: 96, 6: 123, 7: 129, 8: 133, 9: 130, 10: 62, 11: 84, 12: 118, 13: 61, 14: 101, 15: 85, 16: 51, 17: 104, 18: 88, 19: 28, 20: 93, 21: 134, 22: 34, 23: 94, 24: 90, 25: 68, 26: 95, 27: 60}, 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': {0: 31, 1: 268, 2: 142, 3: 40, 4: 148, 5: 274, 6: 37, 7: 217, 8: 240, 9: 53, 10: 195, 11: 178, 12: 232, 13: 171, 14: 91, 15: 168, 16: 232, 17: 179, 18: 94, 19: 58, 20: 100, 21: 185, 22: 213, 23: 97, 24: 244, 25: 225, 26: 114, 27: 103, 28: 155, 29: 221, 30: 191, 31: 107, 32: 64, 33: 113, 34: 197, 35: 223, 36: 219, 37: 184, 38: 108, 39: 109, 40: 72, 41: 102, 42: 108, 43: 184, 44: 93, 45: 97, 46: 116, 47: 220, 48: 232, 49: 206}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {0: 99, 1: 95, 2: 62, 3: 89, 4: 106, 5: 49, 6: 45, 7: 24, 8: 96, 9: 14, 10: 72, 11: 18, 12: 62, 13: 53, 14: 55, 15: 38, 16: 61, 17: 59, 18: 95, 19: 68}, 'Clc1ccccc1CN1CCc2sccc2C1': {0: 76, 1: 96, 2: 40, 3: 28, 4: 33, 5: 58, 6: 96, 7: 34, 8: 34, 9: 47, 10: 47, 11: 77, 12: 21, 13: 37, 14: 63, 15: 86, 16: 45}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 19, 1: 55, 2: 67, 3: 41, 4: 65, 5: 76, 6: 41, 7: 34, 8: 27, 9: 22, 10: 53, 11: 19, 12: 67, 13: 44}, 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': {0: 24, 1: 92, 2: 99, 3: 108, 4: 146, 5: 123, 6: 52, 7: 59, 8: 120, 9: 87, 10: 75, 11: 67, 12: 101, 13: 93, 14: 39, 15: 64, 16: 31, 17: 23, 18: 101, 19: 113, 20: 79, 21: 83, 22: 113, 23: 152, 24: 117, 25: 112, 26: 58, 27: 105}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 59, 1: 72, 2: 64, 3: 63, 4: 31, 5: 41, 6: 17, 7: 82, 8: 87, 9: 60, 10: 38, 11: 24, 12: 44, 13: 93, 14: 66, 15: 40, 16: 37}, 'NC(=O)c1nc(F)cnc1O': {0: 44, 1: 61, 2: 50, 3: 53, 4: 25, 5: 20, 6: 16, 7: 27, 8: 21, 9: 36, 10: 43}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 77, 1: 83, 2: 83, 3: 82, 4: 78, 5: 70, 6: 120, 7: 73, 8: 16, 9: 76, 10: 54, 11: 71, 12: 59, 13: 54, 14: 33, 15: 63, 16: 44, 17: 50, 18: 60, 19: 14}, 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': {0: 56, 1: 47, 2: 14, 3: 42, 4: 78, 5: 37, 6: 41, 7: 65, 8: 43, 9: 53, 10: 26, 11: 86, 12: 40, 13: 83, 14: 42, 15: 63}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 81, 1: 78, 2: 66, 3: 111, 4: 16, 5: 23, 6: 125, 7: 79, 8: 43, 9: 40, 10: 100, 11: 118, 12: 41, 13: 70, 14: 105, 15: 104, 16: 99, 17: 121, 18: 59, 19: 57, 20: 61, 21: 71, 22: 68, 23: 124, 24: 90}, 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 75, 1: 80, 2: 96, 3: 39, 4: 21, 5: 23, 6: 87, 7: 36, 8: 27, 9: 102, 10: 95, 11: 65, 12: 73, 13: 118, 14: 92, 15: 84, 16: 90, 17: 79, 18: 71, 19: 67, 20: 46, 21: 52}, 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': {0: 129, 1: 123, 2: 147, 3: 107, 4: 103, 5: 97, 6: 88, 7: 131, 8: 25, 9: 63, 10: 23, 11: 108, 12: 88, 13: 86, 14: 73, 15: 46, 16: 52, 17: 42, 18: 29, 19: 123, 20: 120, 21: 75, 22: 81, 23: 154, 24: 117, 25: 103, 26: 109, 27: 87, 28: 81}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 204, 6: 239, 7: 241, 8: 316, 9: 145, 10: 200, 11: 206, 12: 322, 13: 151, 14: 279, 15: 170, 16: 214, 17: 283, 18: 122, 19: 211, 20: 246, 21: 248, 22: 150, 23: 160, 24: 196, 25: 141, 26: 248, 27: 158, 28: 266, 29: 194, 30: 48, 31: 214, 32: 105, 33: 240, 34: 101, 35: 247, 36: 150, 37: 271, 38: 59, 39: 40, 40: 78, 41: 284, 42: 290, 43: 84, 44: 46, 45: 67, 46: 147, 47: 265, 48: 165, 49: 280, 50: 201, 51: 58, 52: 227, 53: 112, 54: 256, 55: 108, 56: 262, 57: 156, 58: 288, 59: 204, 60: 156, 61: 166}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6: 42, 7: 20, 8: 24, 9: 26, 10: 48, 11: 110, 12: 65, 13: 81, 14: 71, 15: 36, 16: 53, 17: 98, 18: 90}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: 82, 7: 73, 8: 67, 9: 114, 10: 103, 11: 74, 12: 42, 13: 21, 14: 25, 15: 27, 16: 48, 17: 73, 18: 16, 19: 65}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: 61, 7: 40, 8: 46, 9: 17, 10: 58, 11: 18, 12: 55, 13: 32}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6: 54, 7: 92, 8: 116, 9: 95, 10: 30, 11: 149, 12: 85, 13: 55, 14: 39, 15: 61, 16: 91, 17: 156, 18: 83, 19: 61, 20: 106, 21: 109, 22: 67, 23: 89, 24: 122, 25: 98}}

In [186]:
df_total = pd.read_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
somp_results = [result_new[i] for i in substrates]
df_total['somp_results'] = somp_results
df_total

,substrates,true_sites,gnn_results,smartcyp_results,somp_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,..."
...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6..."

In [187]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

4. xenosite

In [188]:
df =  pd.read_pickle('xenosite_results.pickle')
df

,substrates,enzyme,atomscores,bondscores
0,NC(=O)c1nc(F)cnc1O,phase1.stable_oxygenation,"[0.028395801782608032, 0.001347571611404419, 2...","[0.00022098422050476074, 0.001357734203338623,..."
1,NC(=O)c1nc(F)cnc1O,phase1.unstable_oxygenation,"[0.0007294118404388428, 5.245208740234375e-06,...","[0.03473392128944397, 0.00991445779800415, 0.0..."
2,NC(=O)c1nc(F)cnc1O,phase1.dehydrogenation,"[0.007166236639022827, 1.4901161193847656e-06,...","[3.4183263778686523e-05, 0.0003910958766937256..."
3,NC(=O)c1nc(F)cnc1O,phase1.hydrolysis,"[5.59687614440918e-05, 2.592802047729492e-06, ...","[0.020581483840942383, 0.003480583429336548, 0..."
4,NC(=O)c1nc(F)cnc1O,phase1.reduction,"[0.001293569803237915, 0, 3.725290298461914e-0...","[0.0005504190921783447, 0.05507153272628784, 8..."
...,...,...,...,...
379,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.stable_oxygenation,"[0.0875401496887207, 0, 0.0875401496887207, 0....","[0.0002409517765045166, 0.0002409517765045166,..."
380,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.unstable_oxygenation,"[2.3365020751953125e-05, 0, 2.3365020751953125...","[0.02907702326774597, 0.02907702326774597, 0.0..."
381,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.dehydrogenation,"[0.0025099217891693115, 0, 0.00250992178916931...","[0.00010332465171813965, 0.0001033246517181396..."
382,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.hydrolysis,"[1.7881393432617188e-06, 0, 1.7881393432617188...","[2.9027462005615234e-05, 2.9027462005615234e-0..."
383,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.reduction,"[0, 0, 0, 0.00020059943199157715, 0, 8.9406967...","[5.960464477539063e-08, 5.960464477539063e-08,..."

In [189]:
df =  pd.read_pickle('xenosite_results.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC': {0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, 6: 85, 7: 70, 8: 62, 9: 80, 10: 92, 11: 61, 12: 77, 13: 119, 14: 64, 15: 129, 16: 38, 17: 49, 18: 67, 19: 55, 20: 98, 21: 65, 22: 84, 23: 84, 24: 159, 25: 83, 26: 79}, 'CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=Cc2ccc3ccc(Cl)cc3n2)c1': {0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, 6: 85, 7: 71, 8: 116, 9: 195, 10: 92, 11: 88, 12: 108, 13: 34, 14: 116, 15: 202, 16: 112, 17: 152, 18: 165, 19: 58, 20: 94, 21: 100, 22: 202, 23: 115, 24: 135, 25: 82, 26: 192, 27: 75, 28: 78, 29: 215, 30: 135, 31: 93, 32: 199, 33: 73, 34: 120, 35: 201, 36: 215, 37: 141, 38: 225, 39: 83, 40: 120}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: 137, 7: 68, 8: 80, 9: 143, 10: 137, 11: 85, 12: 65, 13: 64, 14: 99, 15: 135, 16: 85, 17: 86, 18: 92, 19: 46, 20: 68, 21: 66, 22: 72, 23: 76, 24: 89, 25: 74}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6: 39, 7: 45, 8: 65, 9: 102, 10: 22, 11: 108, 12: 71, 13: 51, 14: 47, 15: 73, 16: 118, 17: 18, 18: 61, 19: 67}, 'CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 36, 1: 45, 2: 15, 3: 82, 4: 30, 5: 36, 6: 42, 7: 63, 8: 43, 9: 82, 10: 46, 11: 37, 12: 37, 13: 83, 14: 84, 15: 55}, 'CC(Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 64, 1: 73, 2: 52, 3: 132, 4: 78, 5: 118, 6: 128, 7: 92, 8: 74, 9: 65, 10: 67, 11: 53, 12: 58, 13: 15, 14: 64, 15: 61, 16: 94, 17: 100, 18: 63, 19: 150, 20: 22, 21: 140, 22: 139, 23: 143, 24: 82, 25: 49, 26: 155, 27: 151, 28: 149, 29: 159}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 216, 6: 160, 7: 57, 8: 113, 9: 154, 10: 61, 11: 294, 12: 177, 13: 161, 14: 296, 15: 222, 16: 168, 17: 65, 18: 170, 19: 182, 20: 188, 21: 271, 22: 187, 23: 168, 24: 305, 25: 48, 26: 168, 27: 146, 28: 127, 29: 94, 30: 98, 31: 100, 32: 135, 33: 309, 34: 108, 35: 212, 36: 218, 37: 190, 38: 278, 39: 131, 40: 298, 41: 246, 42: 123, 43: 314, 44: 71, 45: 192, 46: 172, 47: 311, 48: 159, 49: 228, 50: 184, 51: 147, 52: 261, 53: 314, 54: 174, 55: 184, 56: 301, 57: 317, 58: 192, 59: 184, 60: 187}, 'CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O': {0: 57, 1: 140, 2: 64, 3: 44, 4: 83, 5: 95, 6: 39, 7: 106, 8: 78, 9: 77, 10: 27, 11: 124, 12: 71, 13: 56, 14: 120, 15: 27, 16: 62, 17: 77, 18: 131, 19: 73, 20: 50, 21: 88, 22: 110, 23: 99, 24: 52}, 'CC12C=CC(=O)C(Cl)=C1CCC1C2CCC2(C)C1CCC2(C)O': {0: 51, 1: 114, 2: 50, 3: 43, 4: 95, 5: 54, 6: 89, 7: 111, 8: 91, 9: 58, 10: 51, 11: 74, 12: 55, 13: 67, 14: 68, 15: 130, 16: 67, 17: 59, 18: 57, 19: 42, 20: 136, 21: 69, 22: 25}, 'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)COP(=O)(O)O': {0: 72, 1: 83, 2: 74, 3: 87, 4: 108, 5: 87, 6: 86, 7: 128, 8: 68, 9: 132, 10: 82, 11: 56, 12: 71, 13: 165, 14: 76, 15: 172, 16: 168, 17: 104, 18: 38, 19: 99, 20: 177, 21: 101, 22: 187, 23: 41, 24: 125, 25: 103, 26: 109, 27: 84, 28: 80, 29: 109, 30: 45, 31: 51}, 'CC1CCC2C(C)C(OC(=O)CCC(=O)O)OC3OC4(C)CCC1C32OO4': {0: 53, 1: 70, 2: 60, 3: 74, 4: 89, 5: 82, 6: 70, 7: 76, 8: 84, 9: 106, 10: 85, 11: 81, 12: 70, 13: 106, 14: 105, 15: 42, 16: 78, 17: 69, 18: 77, 19: 152, 20: 78, 21: 83, 22: 89, 23: 107, 24: 160, 25: 72, 26: 50}, 'CC1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 47, 1: 65, 2: 53, 3: 12, 4: 44, 5: 59, 6: 56, 7: 42, 8: 64, 9: 67, 10: 73, 11: 100, 12: 65, 13: 68, 14: 45, 15: 115, 16: 70, 17: 42, 18: 78, 19: 120, 20: 118, 21: 115}, 'CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 38, 1: 66, 2: 62, 3: 51, 4: 113, 5: 129, 6: 27, 7: 62, 8: 46, 9: 22, 10: 63, 11: 53, 12: 71, 13: 127, 14: 137, 15: 71, 16: 133, 17: 124, 18: 61, 19: 122, 20: 94, 21: 104, 22: 44, 23: 93, 24: 62, 25: 131}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 45, 1: 39, 2: 92, 3: 80, 4: 54, 5: 34, 6: 26, 7: 40, 8: 60, 9: 75, 10: 52, 11: 14, 12: 90, 13: 57, 14: 20, 15: 82, 16: 58}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 37, 1: 51, 2: 52, 3: 41, 4: 105, 5: 45, 6: 31, 7: 36, 8: 65, 9: 99, 10: 55, 11: 64, 12: 55, 13: 106, 14: 52, 15: 99, 16: 109, 17: 114, 18: 19, 19: 107, 20: 118, 21: 58}, 'CCCC1CC(C(=O)NC(C(C)Cl)C2OC(SC)C(O)C(O)C2O)N(C)C1': {0: 67, 1: 82, 2: 83, 3: 92, 4: 85, 5: 95, 6: 129, 7: 97, 8: 51, 9: 128, 10: 102, 11: 92, 12: 148, 13: 88, 14: 101, 15: 92, 16: 38, 17: 104, 18: 57, 19: 38, 20: 73, 21: 40, 22: 72, 23: 50, 24: 42, 25: 115, 26: 107}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 33, 1: 53, 2: 55, 3: 64, 4: 67, 5: 72, 6: 61, 7: 64, 8: 115, 9: 70, 10: 68, 11: 119, 12: 86, 13: 85, 14: 130, 15: 42, 16: 60, 17: 26, 18: 66, 19: 32, 20: 74, 21: 76}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 109, 1: 105, 2: 123, 3: 141, 4: 27, 5: 213, 6: 135, 7: 146, 8: 216, 9: 194, 10: 173, 11: 146, 12: 157, 13: 133, 14: 131, 15: 103, 16: 98, 17: 122, 18: 85, 19: 68, 20: 86, 21: 72, 22: 93, 23: 128, 24: 108, 25: 115, 26: 135, 27: 117, 28: 122, 29: 141, 30: 130, 31: 134, 32: 148, 33: 136, 34: 133, 35: 149, 36: 116, 37: 113, 38: 143, 39: 139, 40: 171, 41: 164}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 37, 1: 62, 2: 59, 3: 80, 4: 129, 5: 81, 6: 141, 7: 68, 8: 64, 9: 64, 10: 85, 11: 149, 12: 146, 13: 105, 14: 75, 15: 144, 16: 76, 17: 139, 18: 153, 19: 155, 20: 62, 21: 79, 22: 90, 23: 20, 24: 76, 25: 72, 26: 83, 27: 79, 28: 154, 29: 167, 30: 82}, 'CCCSc1nc(NC2CC2c2ccc(F)c(F)c2)c2nnn(C3CC(OCCO)C(O)C3O)c2n1': {0: 58, 1: 78, 2: 75, 3: 81, 4: 170, 5: 122, 6: 169, 7: 44, 8: 113, 9: 82, 10: 92, 11: 159, 12: 94, 13: 80, 14: 168, 15: 166, 16: 178, 17: 176, 18: 97, 19: 191, 20: 91, 21: 136, 22: 137, 23: 113, 24: 104, 25: 103, 26: 87, 27: 96, 28: 94, 29: 29, 30: 71, 31: 43, 32: 108, 33: 46, 34: 206, 35: 139}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 42, 1: 46, 2: 21, 3: 52, 4: 50, 5: 49, 6: 63, 7: 25, 8: 86, 9: 60, 10: 101, 11: 65, 12: 105, 13: 106, 14: 104, 15: 11, 16: 53, 17: 103, 18: 50, 19: 68}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 46, 1: 45, 2: 19, 3: 51, 4: 54, 5: 61, 6: 57, 7: 51, 8: 83, 9: 55, 10: 96, 11: 52, 12: 40, 13: 95, 14: 9, 15: 46, 16: 58}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 89, 1: 107, 2: 53, 3: 211, 4: 134, 5: 192, 6: 199, 7: 117, 8: 113, 9: 190, 10: 118, 11: 42, 12: 93, 13: 61, 14: 83, 15: 67, 16: 101, 17: 119, 18: 129, 19: 137, 20: 219, 21: 193, 22: 122, 23: 49, 24: 130, 25: 218, 26: 194, 27: 122, 28: 128, 29: 202, 30: 116, 31: 50, 32: 226, 33: 119, 34: 216, 35: 124, 36: 144, 37: 109, 38: 86, 39: 87, 40: 92, 41: 117}, 'CCNC1CC(C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 38, 1: 44, 2: 18, 3: 52, 4: 47, 5: 52, 6: 48, 7: 66, 8: 59, 9: 65, 10: 93, 11: 82, 12: 84, 13: 58, 14: 25, 15: 66, 16: 72, 17: 69, 18: 102}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 74, 1: 61, 2: 83, 3: 119, 4: 89, 5: 25, 6: 142, 7: 82, 8: 90, 9: 139, 10: 143, 11: 99, 12: 52, 13: 130, 14: 87, 15: 93, 16: 25, 17: 78, 18: 72, 19: 85, 20: 79, 21: 164, 22: 89, 23: 58, 24: 60, 25: 72, 26: 154, 27: 83, 28: 83}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 66, 1: 65, 2: 82, 3: 103, 4: 82, 5: 140, 6: 126, 7: 79, 8: 28, 9: 133, 10: 68, 11: 50, 12: 50, 13: 56, 14: 75, 15: 56, 16: 79, 17: 146, 18: 88, 19: 141, 20: 155, 21: 156, 22: 25, 23: 138, 24: 83, 25: 38, 26: 72, 27: 78, 28: 152}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 70, 1: 32, 2: 76, 3: 126, 4: 88, 5: 85, 6: 83, 7: 118, 8: 94, 9: 82, 10: 145, 11: 80, 12: 68, 13: 146, 14: 77, 15: 121, 16: 94, 17: 153, 18: 74, 19: 91, 20: 155, 21: 23, 22: 147, 23: 22, 24: 21, 25: 99, 26: 80, 27: 74, 28: 86}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 56, 1: 24, 2: 62, 3: 59, 4: 64, 5: 63, 6: 26, 7: 112, 8: 70, 9: 40, 10: 43, 11: 57, 12: 109, 13: 60, 14: 66, 15: 117, 16: 63, 17: 49, 18: 44, 19: 76, 20: 126}, 'CN(C)c1ccc(O)c2c1CC1CC3C(N(C)C)C(O)=C(C(N)=O)C(=O)C3(O)C(O)=C1C2=O': {0: 72, 1: 30, 2: 78, 3: 159, 4: 75, 5: 79, 6: 154, 7: 35, 8: 160, 9: 158, 10: 84, 11: 91, 12: 84, 13: 73, 14: 105, 15: 54, 16: 80, 17: 86, 18: 147, 19: 62, 20: 158, 21: 142, 22: 35, 23: 99, 24: 119, 25: 110, 26: 195, 27: 41, 28: 152, 29: 60, 30: 145, 31: 144, 32: 100}, 'CN1CCc2cccc3c2C1Cc1ccc(O)c(O)c1-3': {0: 44, 1: 21, 2: 34, 3: 41, 4: 91, 5: 45, 6: 50, 7: 58, 8: 94, 9: 94, 10: 54, 11: 54, 12: 97, 13: 69, 14: 39, 15: 97, 16: 22, 17: 110, 18: 32, 19: 114}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 66, 1: 21, 2: 114, 3: 71, 4: 48, 5: 58, 6: 62, 7: 113, 8: 101, 9: 65, 10: 28, 11: 65, 12: 52, 13: 111, 14: 121, 15: 37, 16: 129, 17: 50, 18: 34, 19: 57, 20: 51, 21: 127, 22: 75}, 'CNC(=O)c1ccccc1Sc1ccc2c(C=Cc3ccccn3)n[nH]c2c1': {0: 71, 1: 27, 2: 118, 3: 78, 4: 145, 5: 72, 6: 76, 7: 60, 8: 92, 9: 137, 10: 35, 11: 141, 12: 106, 13: 66, 14: 144, 15: 143, 16: 54, 17: 51, 18: 154, 19: 57, 20: 45, 21: 54, 22: 95, 23: 48, 24: 92, 25: 48, 26: 141, 27: 86}, 'CNC(C)C(O)c1ccccc1': {0: 45, 1: 17, 2: 45, 3: 44, 4: 44, 5: 18, 6: 71, 7: 44, 8: 29, 9: 26, 10: 35, 11: 50}, 'CNCCC(Oc1ccccc1C)c1ccccc1': {0: 51, 1: 17, 2: 52, 3: 67, 4: 69, 5: 51, 6: 107, 7: 72, 8: 61, 9: 34, 10: 47, 11: 103, 12: 57, 13: 108, 14: 63, 15: 38, 16: 30, 17: 44, 18: 69}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 52, 1: 14, 2: 52, 3: 116, 4: 73, 5: 119, 6: 122, 7: 57, 8: 45, 9: 34, 10: 54, 11: 119, 12: 122, 13: 50, 14: 64, 15: 68, 16: 74, 17: 120, 18: 56, 19: 71, 20: 74, 21: 59, 22: 95, 23: 90}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 77, 1: 74, 2: 162, 3: 155, 4: 144, 5: 80, 6: 77, 7: 157, 8: 75, 9: 163, 10: 22, 11: 85, 12: 70, 13: 102, 14: 108, 15: 75, 16: 78, 17: 162, 18: 73, 19: 115, 20: 182, 21: 71, 22: 104, 23: 66, 24: 172, 25: 85, 26: 32, 27: 174, 28: 95, 29: 121, 30: 171, 31: 201, 32: 78, 33: 84, 34: 90}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 47, 1: 42, 2: 92, 3: 49, 4: 95, 5: 43, 6: 102, 7: 68, 8: 54, 9: 104, 10: 16, 11: 63, 12: 111, 13: 13, 14: 55, 15: 105, 16: 48, 17: 62, 18: 104, 19: 49, 20: 64}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 68, 1: 69, 2: 129, 3: 80, 4: 144, 5: 54, 6: 92, 7: 79, 8: 135, 9: 71, 10: 131, 11: 59, 12: 72, 13: 141, 14: 23, 15: 130, 16: 89, 17: 22, 18: 70, 19: 53, 20: 59, 21: 153, 22: 159, 23: 72, 24: 161, 25: 73, 26: 160, 27: 133, 28: 29, 29: 80}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 71, 1: 59, 2: 129, 3: 54, 4: 73, 5: 122, 6: 69, 7: 72, 8: 69, 9: 32, 10: 77, 11: 83, 12: 34, 13: 130, 14: 87, 15: 61, 16: 137, 17: 34, 18: 143, 19: 23, 20: 85, 21: 80, 22: 87, 23: 79, 24: 60}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 63, 1: 57, 2: 127, 3: 63, 4: 82, 5: 126, 6: 69, 7: 86, 8: 92, 9: 25, 10: 76, 11: 142, 12: 40, 13: 145, 14: 68, 15: 51, 16: 69, 17: 67, 18: 142, 19: 141, 20: 75, 21: 84, 22: 121, 23: 26, 24: 73, 25: 88, 26: 70}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 39, 1: 36, 2: 87, 3: 52, 4: 43, 5: 89, 6: 38, 7: 37, 8: 90, 9: 45, 10: 59, 11: 91, 12: 85, 13: 46, 14: 29, 15: 66, 16: 44, 17: 50}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 83, 1: 73, 2: 174, 3: 77, 4: 71, 5: 77, 6: 97, 7: 187, 8: 102, 9: 195, 10: 192, 11: 38, 12: 102, 13: 125, 14: 131, 15: 176, 16: 98, 17: 106, 18: 179, 19: 210, 20: 74, 21: 80, 22: 86, 23: 117, 24: 104, 25: 142, 26: 201, 27: 202, 28: 70, 29: 127, 30: 110, 31: 134, 32: 76, 33: 114, 34: 215, 35: 100, 36: 110, 37: 94, 38: 31}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 67, 1: 80, 2: 109, 3: 115, 4: 72, 5: 81, 6: 36, 7: 85, 8: 164, 9: 110, 10: 117, 11: 178, 12: 195, 13: 97, 14: 118, 15: 181, 16: 97, 17: 135, 18: 111, 19: 186, 20: 20, 21: 192, 22: 89, 23: 84, 24: 196, 25: 68, 26: 95, 27: 184, 28: 94, 29: 67, 30: 69, 31: 198, 32: 197, 33: 84, 34: 193, 35: 213, 36: 135, 37: 210, 38: 85, 39: 113}, 'Cc1cc(N2CCN(C3CNC(C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 92, 1: 155, 2: 103, 3: 158, 4: 40, 5: 95, 6: 72, 7: 45, 8: 108, 9: 92, 10: 39, 11: 106, 12: 138, 13: 98, 14: 51, 15: 93, 16: 80, 17: 61, 18: 109, 19: 101, 20: 86, 21: 111, 22: 100, 23: 171, 24: 87, 25: 62, 26: 72, 27: 68, 28: 94, 29: 103}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 59, 1: 93, 2: 73, 3: 114, 4: 110, 5: 88, 6: 20, 7: 116, 8: 56, 9: 42, 10: 50, 11: 65, 12: 116, 13: 40, 14: 103, 15: 31, 16: 65, 17: 52, 18: 22, 19: 70, 20: 59, 21: 74}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 57, 1: 137, 2: 68, 3: 74, 4: 151, 5: 75, 6: 74, 7: 75, 8: 81, 9: 82, 10: 158, 11: 142, 12: 85, 13: 39, 14: 84, 15: 78, 16: 32, 17: 151, 18: 77, 19: 162, 20: 88, 21: 153, 22: 166, 23: 93, 24: 73, 25: 162, 26: 113, 27: 97, 28: 76, 29: 100, 30: 80, 31: 85}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(O)cc3)cc2)cc1': {0: 66, 1: 132, 2: 72, 3: 82, 4: 143, 5: 78, 6: 89, 7: 95, 8: 25, 9: 156, 10: 89, 11: 62, 12: 144, 13: 114, 14: 74, 15: 56, 16: 47, 17: 154, 18: 62, 19: 54, 20: 148, 21: 29, 22: 60, 23: 68, 24: 68, 25: 97, 26: 92, 27: 80}, 'Cc1cccc(C)c1OCC(=O)NC(Cc1ccccc1)C(O)CC(Cc1ccccc1)NC(=O)C(C(C)C)N1CCCNC1=O': {0: 109, 1: 218, 2: 137, 3: 133, 4: 144, 5: 227, 6: 120, 7: 247, 8: 108, 9: 159, 10: 200, 11: 146, 12: 61, 13: 155, 14: 129, 15: 240, 16: 140, 17: 99, 18: 101, 19: 106, 20: 146, 21: 130, 22: 58, 23: 137, 24: 175, 25: 134, 26: 241, 27: 140, 28: 99, 29: 96, 30: 105, 31: 148, 32: 66, 33: 222, 34: 141, 35: 177, 36: 147, 37: 117, 38: 123, 39: 68, 40: 147, 41: 104, 42: 133, 43: 40, 44: 256, 45: 157}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {0: 92, 1: 104, 2: 55, 3: 46, 4: 101, 5: 63, 6: 70, 7: 47, 8: 44, 9: 50, 10: 74, 11: 69, 12: 22, 13: 64, 14: 60, 15: 48, 16: 66, 17: 72, 18: 52, 19: 61}, 'Clc1ccccc1CN1CCc2sccc2C1': {0: 84, 1: 87, 2: 47, 3: 27, 4: 34, 5: 41, 6: 82, 7: 41, 8: 12, 9: 40, 10: 49, 11: 84, 12: 57, 13: 44, 14: 49, 15: 90, 16: 50}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 36, 1: 24, 2: 65, 3: 39, 4: 65, 5: 67, 6: 34, 7: 48, 8: 18, 9: 41, 10: 31, 11: 39, 12: 82, 13: 41}, 'Cn1nnc(-c2ccc(-c3ccc(N4CC(CO)OC4=O)cc3F)cn2)n1': {0: 41, 1: 81, 2: 89, 3: 76, 4: 128, 5: 134, 6: 68, 7: 58, 8: 124, 9: 116, 10: 63, 11: 59, 12: 138, 13: 30, 14: 67, 15: 67, 16: 52, 17: 27, 18: 74, 19: 115, 20: 80, 21: 67, 22: 137, 23: 146, 24: 99, 25: 50, 26: 82}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 12, 1: 61, 2: 38, 3: 76, 4: 39, 5: 39, 6: 37, 7: 74, 8: 77, 9: 85, 10: 30, 11: 26, 12: 36, 13: 84, 14: 92, 15: 61, 16: 51}, 'NC(=O)c1nc(F)cnc1O': {0: 11, 1: 37, 2: 31, 3: 51, 4: 21, 5: 55, 6: 60, 7: 34, 8: 27, 9: 55, 10: 14}, 'NC(Cc1cc(O)c(O)cc1F)C(=O)O': {0: 19, 1: 39, 2: 38, 3: 64, 4: 43, 5: 69, 6: 19, 7: 74, 8: 15, 9: 34, 10: 77, 11: 82, 12: 62, 13: 54, 14: 31}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 17, 1: 99, 2: 23, 3: 38, 4: 98, 5: 73, 6: 101, 7: 68, 8: 29, 9: 62, 10: 66, 11: 102, 12: 26, 13: 43, 14: 56, 15: 36, 16: 81, 17: 87, 18: 65, 19: 90}, 'O=C(NC(CO)C(O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 58, 1: 83, 2: 23, 3: 63, 4: 45, 5: 22, 6: 48, 7: 28, 8: 93, 9: 59, 10: 51, 11: 102, 12: 36, 13: 71, 14: 77, 15: 57, 16: 67, 17: 63, 18: 104, 19: 110}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 72, 1: 90, 2: 24, 3: 66, 4: 46, 5: 34, 6: 22, 7: 117, 8: 62, 9: 73, 10: 119, 11: 79, 12: 70, 13: 82, 14: 77, 15: 116, 16: 25, 17: 123, 18: 56, 19: 44, 20: 111, 21: 126, 22: 51, 23: 131, 24: 134}, 'O=C(O)CCC(=O)OCC(NC(=O)C(Cl)Cl)C(O)c1ccc([N+](=O)[O-])cc1': {0: 101, 1: 96, 2: 39, 3: 65, 4: 75, 5: 103, 6: 78, 7: 67, 8: 70, 9: 81, 10: 30, 11: 112, 12: 77, 13: 82, 14: 145, 15: 151, 16: 82, 17: 29, 18: 134, 19: 72, 20: 61, 21: 139, 22: 44, 23: 92, 24: 98, 25: 67, 26: 78}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 285, 6: 100, 7: 283, 8: 264, 9: 195, 10: 170, 11: 176, 12: 273, 13: 204, 14: 283, 15: 246, 16: 261, 17: 134, 18: 178, 19: 306, 20: 106, 21: 306, 22: 234, 23: 186, 24: 319, 25: 311, 26: 156, 27: 209, 28: 178, 29: 142, 30: 132, 31: 44, 32: 124, 33: 56, 34: 139, 35: 64, 36: 152, 37: 88, 38: 173, 39: 175, 40: 199, 41: 279, 42: 285, 43: 207, 44: 185, 45: 187, 46: 329, 47: 162, 48: 225, 49: 184, 50: 148, 51: 148, 52: 50, 53: 131, 54: 62, 55: 146, 56: 70, 57: 158, 58: 94, 59: 345, 60: 256, 61: 192}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: 41, 7: 38, 8: 20, 9: 44, 10: 47, 11: 99, 12: 65, 13: 95, 14: 100, 15: 35, 16: 67, 17: 104, 18: 16}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6: 97, 7: 104, 8: 69, 9: 108, 10: 85, 11: 103, 12: 44, 13: 44, 14: 25, 15: 50, 16: 50, 17: 26, 18: 65, 19: 23}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: 51, 7: 22, 8: 42, 9: 40, 10: 25, 11: 47, 12: 51, 13: 79}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: 38, 7: 66, 8: 79, 9: 38, 10: 94, 11: 140, 12: 86, 13: 58, 14: 48, 15: 64, 16: 94, 17: 143, 18: 86, 19: 69, 20: 142, 21: 140, 22: 75, 23: 92, 24: 90, 25: 79}}

In [190]:
from rdkit import Chem
def canonicalsmiles_noisomeric(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [191]:
df_total = pd.read_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
xenosite_results = [result_new[canonicalsmiles_noisomeric(i)] for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total

,substrates,true_sites,gnn_results,smartcyp_results,somp_results,xenosite_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21..."
...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ..."

In [192]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

5. metapredictor

In [193]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [194]:
df = pd.read_csv('metapredictor_som.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict'].to_list()
predicts = [i.split('|') for i in predicts]

In [195]:
predicts

[['C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/[OH:1])CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/[C:1](=N/[OH:1])CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3C[CH2:1]C4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/[C:1](=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CC[C:1]4=[CH:1]/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=[N:1]/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
  'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3C[CH2:1][C@@:1]21CC',
  'C#C[C@@]1([O:1]C(C)=O)[C@@]2(CC)CC[C@H]3[C@@H](CCC4=C\\C(=N/O)CC[C@@H]43)[C@@H]2C1',
  'C#C[C@@]1([O:1]C(C)=O)[C@@]2(CC)CC[C@H]3[C@@H](CCC4=C\\C(=N\\O)CC[C@@H]43)[C@@H]2C1'],
 ['CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[CH3:1]',
  'CC(C)(O)c1cc[cH:1]cc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'C[C:1](O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[CH3:1]',
  'CC(C)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1)[OH:1]',
  'C[C:1](C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)[cH:1]1',
  'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3c[cH:1]c(Cl)cc3n2)c1',
  'CC(C)(O)c1c(CC[C@@H](SCC2(CC(=O)O)CC2)c2cccc(/C=C/c3ccc4ccc(Cl)cc4n3)c2)ccc[cH:1]1'],
 ['CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)cc1',
  'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CC[CH2:1]C2)cc1',
  'CC(CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]',
  'CC(C)C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'C[CH:1](C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C)[CH2:1]NCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]',
  'CC(C)CNCc1ccc(-c2cc[cH:1]cc2S(=O)(=O)N2CCCC2)cc1',
  'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)[N:1]2CCCC2)cc1',
  'C[CH:1](CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1)[CH3:1]'],
 ['CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C',
  'CC(CN1c2ccccc2Sc2cc[cH:1]cc21)N(C)C',
  'CC(CN1c2ccccc2[S:1]c2ccccc21)N(C)C',
  'CC(CN1c2cc[cH:1]cc2Sc2ccccc21)N(C)C',
  'CC(CN1c2ccccc2S[c:1]2[cH:1][cH:1][cH:1][cH:1][c:1]21)N(C)C',
  'CC(CN1c2ccccc2Sc2ccc[cH:1]c21)N(C)C',
  'CC(CN1c2ccccc2Sc2ccccc21)[N:1](C)C',
  'CC(CN1c2ccccc2Sc2c1ccc[cH:1]2)N(C)C',
  'CC(C[N:1]1c2ccccc2Sc2ccccc21)N(C)C',
  'CN(C)C(CN1c2ccccc2Sc2ccccc21)[CH3:1]'],
 ['CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)[cH:1]c2)C1',
  'CC1([CH3:1])CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)c[cH:1]2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH][cH:1]cc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)[CH2:1]1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc([NH:1]CC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c([O:1]c4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+:1](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(C[N:1]2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
  'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2cc[c:1](Cl)cc2)C1'],
 ['CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc([OH:1])cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1([CH3:1])S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H:1](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)[cH:1]c3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H]([NH:1]C(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)[OH:1]',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@@H](c3ccc(O)cc3)[NH2:1])C(=O)N2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)[N:1]2[C@H]1C(=O)O',
  'CC1(C)S[C@@H]2[C@H](NC(=O)[C@@H:1](c3ccc(O)cc3)[NH2:1])C(=O)N2[C@H]1C(=O)O',
  'C[C:1]1([CH3:1])S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O'],
 ['CCC1(c2ccccc2)C(=O)NC(=O)[NH:1]C1=O',
  'CCC1(c2cc[cH:1]cc2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)N[C:1]1=[O:1]',
  'CCC1(c2ccccc2)C(=O)[NH:1]C(=O)NC1=O',
  'O=C1NC(=O)C(C[CH3:1])(c2ccccc2)C(=O)N1',
  'C[CH2:1]C1(c2ccccc2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)[NH:1][C:1]1=[O:1]',
  'CCC1(c2ccc[cH:1]c2)C(=O)NC(=O)NC1=O',
  'CCC1(c2ccccc2)C(=O)NC(=O)[NH:1][C:1]1=O',
  'CCC1(c2ccccc2)C(=O)N[C:1](=[O:1])NC1=O'],
 ['CCC1C(C(=O)c2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c([OH:1])c(Br)c1',
  'CCC1Oc2ccccc2[CH:1]1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1C(C(=O)[c:1]2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'CCC1Oc2cc[cH:1]cc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)[c:1](Br)c1',
  'CCC1Oc2c[cH:1]ccc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CC[CH:1]1C(C(=O)c2cc(Br)c(O)c(Br)c2)c2ccccc2[O:1]1',
  'C[CH2:1]C1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
  'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)[cH:1]1'],
 ['CCCCCCCCc1ccc(CCC(N)(CO)C[OH:1])cc1',
  'CCCCCCCCc1ccc(CCC(CO)(CO)[NH2:1])cc1',
  'CCCCCCCCc1ccc(CCC(CO)(C[OH:1])[NH2:1])cc1',
  'C[CH2:1]CCCCCCc1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCC[CH2:1]c1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCCCc1ccc(CCC(N)(C[OH:1])C[OH:1])cc1',
  'CC[CH2:1]CCCCCc1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCC[CH2:1][CH2:1]c1ccc(CCC(N)(CO)CO)cc1',
  'CCCCCCCCc1ccc(CCC(N)(CO)[CH2:1]O)cc1',
  'CCCCCCCCc1ccc(CC[C:1](N)(CO)C[OH:1])cc1'],
 ['CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCC[O:1]C)cc1',
  'CCCC[NH:1]c1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCC[O:1]CCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCC[O:1]CCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)[O:1]CCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCC[O:1]CCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOC[CH2:1][O:1]C)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCC[O:1]CCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCC[O:1]CCOCCOCCOCCOCCOC)cc1',
  'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCO[CH3:1])cc1'],
 ['CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCC[N:1](CC)CC)c(I)c1',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c(CC[CH2:1]C)oc3ccccc23)cc1I',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)[cH:1]1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)[c:1](I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)C[CH3:1])c(I)c1',
  'CCCCc1oc2c[cH:1]ccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)[CH2:1]C)c(I)c1',
  'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OC[CH2:1]N(CC)CC)c(I)c1',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c(CCC[CH3:1])oc3ccccc23)cc1I',
  'CCN(CC)CCOc1c(I)cc(C(=O)c2c([CH2:1]CCC)oc3ccccc23)cc1I'],
 ['CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H]([O:1]CCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1]O)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1][OH:1])[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCC[OH:1])[C@@H](O)[C@H]3O)c2n1',
  'CCC[S:1]c1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'C[CH2:1]CSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nn[n:1]([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CC[CH2:1]Sc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc([NH:1][C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
  'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OC[CH2:1]O)[C@@H]([OH:1])[C@H]3O)c2n1'],
 ['CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H]([S:1]C)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)[N:1](C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H]([OH:1])[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2[OH:1])N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H]([OH:1])[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H]([C:1](=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)[CH2:1]1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](S[CH3:1])[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)[NH:1]C(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
  'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H:1](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1'],
 ['CCN(CC)CCNC(=O)c1cc(Cl)c([NH2:1])cc1OC',
  'CCN(CC)CCNC(=O)c1cc(Cl)c(N)[cH:1]c1OC',
  'CC[N:1](CC)CCNC(=O)c1cc(Cl)c(N)cc1OC',
  'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1[O:1]C',
  'CCN(CC)CC[NH:1]C(=O)c1cc(Cl)c(N)cc1OC',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1[O:1]C)CC',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1OC)[CH2:1]C',
  'CCN(CCNC(=O)c1cc(Cl)c(N)cc1OC)C[CH3:1]',
  'COc1cc(N)c(Cl)cc1C(=O)NCCN(C[CH3:1])CC',
  'CCN(CC)CCNC(=O)c1c(OC)cc(N)c(Cl)[cH:1]'],
 ['CCN(CC)CCOC(=O)c1ccc([NH2:1])cc1',
  'CC[N:1](CC)CCOC(=O)c1ccc(N)cc1',
  'CCN(CC)CC[O:1]C(=O)c1ccc(N)cc1',
  'CCN(CC)CCOC(=O)c1ccc(N)[cH:1]c1',
  'CCN(CC)C[CH2:1][O:1]C(=O)c1ccc(N)cc1',
  'CC[N:1](CC)CC[O:1]C(=O)c1ccc(N)cc1',
  'CCN(CC)[CH2:1]COC(=O)c1ccc(N)cc1',
  'CCN(CC)C[CH2:1]OC(=O)c1ccc(N)cc1',
  'CC[N:1](CC)CCOC(=O)c1cc[c:1](N)cc1',
  'CCN(CCOC(=O)c1ccc(N)cc1)[CH2:1]C'],
 ['CC[N:1](c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCO[CH2:1]C1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CC[O:1]CC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc([CH3:1])[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOC[CH2:1]3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc([CH2:1]N3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH:1]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CCO[CH2:1]C3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(C[N:1]3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
  'CCN(c1cc(-c2ccc(CN3CC[O:1][CH2:1]C3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1'],
 ['CC[NH:1][C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(=O)(=O)[NH2:1])cc21',
  'C[C@H]1C[C@H](N[CH2:1]C)c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'C[C@@H]1C[C@H](N[CH2:1]C)c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc([S:1](N)(=O)=O)cc21',
  'CCN[C@H]1C[C@H]([CH3:1])S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'CCN[C@H:1]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
  'C[C@H]1C[C@H](NC[CH3:1])c2cc(S(N)(=O)=O)sc2S1(=O)=O',
  'NS(=O)(=O)c1cc2c(s1)S(=O)(=O)[C@@H](C)C[C@@H]2N[CH2:1][CH3:1]',
  'C[CH2:1]N[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21'],
 ['CCOC(=O)Nc1ccc2c(c1)N(C(=O)C[N:1](CC)CC)c1ccccc1CC2',
  'CCOC(=O)[NH:1]c1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1cc[cH:1]cc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)C[CH3:1])c1ccccc1CC2',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1[CH2:1]C2',
  'CCOC(=O)Nc1cc2c(c[cH:1]1)CCc1ccccc1N2C(=O)CN(CC)CC',
  'CCN(CC)CC(=O)N1c2ccccc2CCc2ccc(NC(=O)[O:1]CC)cc21',
  'CCOC(=O)Nc1ccc2c(c1)[N:1](C(=O)CN(CC)CC)c1ccccc1CC2',
  'CCN(CC)CC(=O)N1c2ccccc2CCc2ccc(NC(=O)OC[CH3:1])cc21',
  'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccc[cH:1]c1CC2'],
 ['CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c([OH:1])c(CN(C)C)c12',
  'CCOC(=O)c1c(C[S:1]c2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CC[O:1]C(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(C[N:1](C)C)c12',
  'CCOC(=O)c1c([CH2:1]Sc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2cc[cH:1]cc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CC[O:1]C(=O)c1c(C[S:1]c2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)[n:1](C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2cccc[cH:1]2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
  'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)[CH3:1])c12'],
 ['CN(C)C(=O)C[O:1]C(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'C[N:1](C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)[C:1](=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)[C:1](=O)C[O:1]C(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(N[C:1](=[NH:1])[NH2:1])cc2)cc1',
  'CN(C)C(=O)COC(=O)Cc1ccc([O:1]C(=O)c2ccc(NC(=N)N)cc2)cc1',
  'CN(C)C(=O)COC(=O)[CH2:1]c1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
  'C[N:1](C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(N[C:1](=[NH:1])[NH2:1])cc2)cc1',
  'CN(C)[C:1](=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(N)=[NH:1])cc2)cc1',
  'CN(C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(N)=[NH:1])cc2)cc1)[CH3:1]'],
 ['C[N:1](C)CCCN1c2ccccc2CCc2ccccc21',
  'CN(C)CCCN1c2ccccc2CCc2c[cH:1]ccc21',
  'CN(C)CCCN1c2ccccc2C[CH2:1]c2ccccc21',
  'CN(C)CCCN1c2cc[cH:1]cc2CCc2ccccc21',
  'CN(C)[CH2:1]CCN1c2ccccc2CCc2ccccc21',
  'CN(C)CCCN1c2c[cH:1]ccc2CCc2ccccc21',
  'CN(C)CCCN1c2ccccc2[CH2:1]Cc2ccccc21',
  'CN(C)CCCN1c2ccccc2CC[c:1]2[cH:1][cH:1][cH:1][cH:1][c:1]21',
  'CN(C)CCCN1c2ccccc2CCc2cc[cH:1]cc21',
  'CN(C)CCCN1c2ccc[cH:1]c2CCc2ccccc21'],
 ['CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1c[cH:1]c(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc([OH:1])c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1c[cH:1]c(O)c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1[C:1]2=[O:1]',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1C2=O',
  'CN(C)c1ccc([OH:1])c2c1C[C@H]1C[C@H]3[C@H]([N:1](C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1[CH2:1][C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C([OH:1])=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
  'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)[C:1]([OH:1])=[C:1]1[C:1]2=O'],
 ['CN1CCc2cccc3c2[C@H]1Cc1ccc([OH:1])c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c([OH:1])c1-3',
  'C[N:1]1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1C[c:1]1[cH:1][cH:1][c:1]([OH:1])[c:1]([OH:1])[c:1]1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)[c:1](O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1cc[c:1](O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1Cc1c[cH:1]c(O)c(O)c1-3',
  'C[N:1]1[CH2:1][CH2:1][c:1]2cccc3[c:1]2[C@H:1]1Cc1ccc(O)c(O)c1-3',
  'CN1CCc2cccc3c2[C@H]1[CH2:1]c1ccc(O)c(O)c1-3',
  'CN1CCc2c[cH:1]cc3c2[C@H]1Cc1ccc(O)c(O)c1-3'],
 ['CN1c2ccccc2C(=O)N2CCc3c([nH]c4cc[cH:1]cc34)C21',
  'CN1c2ccccc2C(=O)N2CCc3c([nH]c4c[cH:1]ccc34)C21',
  'C[N:1]1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2ccccc2C(=O)N2C[CH2:1]c3c([nH]c4ccccc34)C21',
  'O=C1c2ccccc2N([CH3:1])C2c3[nH]c4ccccc4c3CCN12',
  'C[N:1]1[c:1]2cccc[c:1]2[C:1](=O)[N:1]2CCc3c([nH]c4ccccc34)[CH:1]21',
  'CN1c2c[cH:1]ccc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2cc[cH:1]cc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
  'CN1c2ccccc2C(=O)N2CCc3c([nH]c4c3ccc[cH:1]4)C21',
  'CN1c2ccccc2C(=O)[N:1]2CCc3c([nH]c4ccccc34)C21'],
 ['CNC(=O)c1ccccc1[S:1]c1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'C[NH:1]C(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'O=C(N[CH3:1])c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1c[cH:1]ccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CN[C:1](=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1cc[cH:1]cc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
  'CNC(=O)c1c(Sc2ccc3c(/C=C/c4ccccn4)n[nH]c3c2)ccc[cH:1]1',
  'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3cc[cH:1]cn3)n[nH]c2c1',
  'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH:1]c2c1',
  'C[NH:1][C:1](=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1'],
 ['CNCC[C@@H](Oc1ccc[cH:1]c1C)c1ccccc1',
  'CNCC[C@@H](Oc1ccccc1[CH3:1])c1ccccc1',
  'CNCC[C@@H](Oc1cc[cH:1]cc1C)c1ccccc1',
  'Cc1ccccc1O[C@H](CC[NH:1]C)c1ccccc1',
  'CNCC[C@@H:1](Oc1ccccc1C)c1ccccc1',
  'CNCC[C@@H](Oc1ccccc1C)c1cc[cH:1]cc1',
  'CNCC[C@H](c1ccccc1)[O:1]c1ccccc1C',
  'CNCC[C@@H](Oc1c[cH:1]ccc1C)c1ccccc1',
  'CN[CH2:1]C[C@@H](Oc1ccccc1C)c1ccccc1',
  'CNCC[C@H:1](c1ccccc1)[O:1]c1ccccc1C'],
 ['C[NH:1]Cc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'CN[CH2:1]c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'C[NH:1][CH2:1]c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2ccc[n:1]c2)c1',
  'O=S(=O)(c1cccnc1)n1cc(CN[CH3:1])cc1-c1ccccc1F',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)[cH:1]1',
  'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cc[cH:1]nc2)c1',
  'O=S(=O)(c1cccnc1)n1cc(C[NH:1][CH3:1])cc1-c1ccccc1F',
  'CNCc1cc(-c2cc[cH:1]cc2F)n(S(=O)(=O)c2cccnc2)c1',
  'C[NH:1]Cc1cc(-c2ccccc2F)[n:1](S(=O)(=O)c2cccnc2)c1'],
 ['C[C@@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@H:1](c1ccccc1)[OH:1]',
  'CN[C@@H](C)[C@@H:1](O)c1ccccc1',
  'CN[C@@H](C)[C@@H](O)c1cc[cH:1]cc1',
  'CN[C@@H](C)[C@H](c1ccccc1)[OH:1]',
  'C[C@@H](N[CH3:1])[C@@H](O)c1ccccc1',
  'CN[C@@H](C)[C@@H](O)c1ccc[cH:1]c1',
  'C[C@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'C[C@@H]([NH:1]C)[C@@H:1](O)c1ccccc1',
  'CN[C@@H:1](C)[C@@H](O)c1ccccc1'],
 ['CN[C@@H](C)[C@@H:1](c1ccccc1)[OH:1]',
  'C[C@@H]([C@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@@H](c1ccccc1)[OH:1]',
  'C[C@@H]([C@@H](O)c1ccccc1)[NH:1]C',
  'CN[C@@H](C)[C@H](O)c1cc[cH:1]cc1',
  'CN[C@@H](C)[C@H:1](O)c1ccccc1',
  'C[C@@H](N[CH3:1])[C@H](O)c1ccccc1',
  'CN[C@@H](C)[C@H](O)c1ccc[cH:1]c1',
  'C[C@@H]([NH:1]C)[C@@H:1](c1ccccc1)[OH:1]',
  'C[C@@H](N[CH3:1])[C@@H](c1ccccc1)[OH:1]'],
 ['COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)[CH3:1]',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2c[cH:1]c(=O)[nH]c2=O)cc1C(C)(C)C',
  'CC(C)(C)c1cc(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)c1[O:1]C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH:1]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-[n:1]2[cH:1][cH:1][c:1](=O)[nH:1][c:1]2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=[O:1])ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc([NH:1]S(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2cc3ccc(NS(C)(=O)=O)cc3c[cH:1]2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)[cH:1]c1C(C)(C)C',
  'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2cc[c:1](=[O:1])[nH]c2=O)cc1C(C)(C)C'],
 ['COc1cc(Cc2cnc(N)nc2N)cc([O:1]C)c1OC',
  'COc1cc(Cc2cnc(N)[n:1]c2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc([NH2:1])nc2N)cc(OC)c1OC',
  'COc1cc(Cc2c[n:1]c(N)nc2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2N)[cH:1]c(OC)c1OC',
  'COc1cc([CH2:1]c2cnc(N)nc2N)cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2[NH2:1])cc(OC)c1OC',
  'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1[O:1]C',
  'COc1cc(Cc2cnc(N)nc2N)cc(O[CH3:1])c1OC',
  'COc1cc(Cc2cnc(N)n[c:1]2N)cc(OC)c1OC'],
 ['COc1cc2c(cc1C(N)=O)c(Oc1ccc(NC(=O)NC3CC3)c(Cl)c1)cc[n:1]2',
  'C[O:1]c1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2n[cH:1]cc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4C[CH2:1]4)c(Cl)c3)c2cc1C(N)=O',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(=O)[NH2:1]',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1](N)=O',
  'COc1c(C(N)=O)cc2c(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)ccnc2[cH:1]1',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1]([NH2:1])=[O:1]',
  'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1[C:1](N)=[O:1]',
  'O=C(NC1CC1)Nc1ccc(Oc2ccnc3cc([O:1][CH3:1])c(C(=O)[NH2:1])cc23)cc1Cl'],

In [196]:
df = pd.read_csv('metapredictor_som.csv')
substrates = df['SMILES'].to_list()
predicts = df['predict'].to_list()
predicts = [i.split('|') for i in predicts]
atomidxs = []
for i in predicts:
    atomidxs_part = []
    for j in i:
        try:
            atomidx = get_reactive_atom_indices(j)
            atomidxs_part.append(atomidx)
        except:
            pass
    atomidxs.append(atomidxs_part)
df['atomidxs'] = atomidxs
df

[06:27:31] SMILES Parse Error: unclosed ring for input: 'CCN(CC)CCNC(=O)c1c(OC)cc(N)c(Cl)[cH:1]'
[06:27:31] SMILES Parse Error: unclosed ring for input: 'Cc1sc2c([cH:1]1)C(N1CCN(C)CC1)=Nc1ccccc1N'
[06:27:31] SMILES Parse Error: extra open parentheses for input: 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4c(ccc(Cl)[cH:1]4)o3)CCC2C'
[06:27:31] SMILES Parse Error: unclosed ring for input: 'O=C(O)[C@H](Cc1cc(O)c(O)cc13)[NH2:1]'
[06:27:31] SMILES Parse Error: extra open parentheses for input: 'Clc1ccc2c(c1)C(c1ccccc1)=NC([OH:1])[C:1](=[O:1]'
[06:27:31] SMILES Parse Error: extra open parentheses for input: 'Clc1ccc2c(c1)C(c1ccccc1)=NC(O)[C:1](=[O:1]'
[06:27:31] SMILES Parse Error: extra open parentheses for input: 'Clc1ccc2c(c1)C(c1ccccc1)=NC([OH:1])C(=[O:1]'

,SMILES,metabolite,predict,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,"[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,"[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)...,"[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C|CC(CN1c2cc...,"[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1CN=C(c2cc[cH:1]cc2)c2cc(Cl)ccc2N1|O=C1CN=C...,"[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1[OH:1]|O=C1Nc2...,"[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1([NH:1]CCCl)OCCCN1CCCl|O=P1(NCCCl)OCCC[N:1...,"[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|...,"[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [197]:
df.to_pickle('metapredictor_results.pickle')

In [198]:
df = pd.read_pickle('metapredictor_results.pickle')
df

,SMILES,metabolite,predict,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,"[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,"[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC[CH2:1]2)...,"[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1c2ccccc2Sc2c[cH:1]ccc21)N(C)C|CC(CN1c2cc...,"[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1CN=C(c2cc[cH:1]cc2)c2cc(Cl)ccc2N1|O=C1CN=C...,"[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1[OH:1]|O=C1Nc2...,"[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1([NH:1]CCCl)OCCCN1CCCl|O=P1(NCCCl)OCCC[N:1...,"[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|...,"[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [199]:
subs = df['SMILES'].to_list()
atomidxs = df['atomidxs'].to_list()
dict_sub2atomidxs = dict(zip(subs,atomidxs))
dict_sub2atomidxs

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [[3],
  [17],
  [15, 17],
  [12],
  [15],
  [13, 14],
  [16],
  [23, 24],
  [3],
  [3]],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [[6],
  [19],
  [40],
  [7],
  [1, 40],
  [40],
  [1],
  [40],
  [34],
  [40]],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [[23],
  [22],
  [25],
  [4],
  [1],
  [3],
  [3, 25],
  [13],
  [19],
  [1, 25]],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [[13],
  [14],
  [10],
  [7],
  [11, 12, 13, 14, 15, 16],
  [15],
  [17],
  [16],
  [3],
  [19]],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [[58],
  [2],
  [59],
  [45],
  [60],
  [25],
  [39],
  [34],
  [7],
  [56]],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [[15],
  [2],
  [9],
  [16],
  [6],
  [24],
  [17],
  [20],
  [9, 17],
  [1, 2]],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [[14],
  [6],
  [15, 16],
  [11],
  [7],
  [1],
  [14, 15, 16],
  [7],
  [14, 15],
  [12, 13]],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [[21],
  [18],
  [10],
  [6, 21],
  [7],
  [19],
  [6],
  [2, 21],
  [1],
  [21]],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [[19],
  [19],
  [18, 19],
  [1],
  [7],
  [17, 19],
  [2],
  [6, 7],
  [18],
  [14, 19]],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [[38],
  [4],
  [35],
  [32],
  [11],
  [29],
  [37, 38],
  [26],
  [23],
  [39]],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [[23],
  [19],
  [30],
  [28],
  [27],
  [8],
  [26],
  [22],
  [20],
  [17]],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [[26],
  [28],
  [28, 29],
  [29],
  [3],
  [1],
  [22],
  [2],
  [7],
  [28, 31]],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [[16],
  [24],
  [19],
  [23],
  [21],
  [6],
  [26],
  [17],
  [8],
  [15]],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [[15],
  [16],
  [2],
  [18],
  [7],
  [16],
  [18],
  [19],
  [17]],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [[14],
  [2],
  [7],
  [15],
  [6, 7],
  [2, 7],
  [5],
  [6],
  [2, 13],
  [15]],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [[2],
  [40],
  [39],
  [30],
  [16],
  [10],
  [31],
  [15],
  [11],
  [14, 15]],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [[2],
  [16],
  [5],
  [5],
  [13],
  [6],
  [3],
  [6],
  [17, 18],
  [1]],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [[16],
  [5],
  [24],
  [20],
  [27],
  [11],
  [24],
  [12],
  [26],
  [25]],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [[22],
  [8],
  [2],
  [25],
  [7],
  [12],
  [2, 8],
  [15],
  [14],
  [27]],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [[6],
  [1],
  [3],
  [3, 6],
  [22, 23, 24],
  [14],
  [9],
  [1, 22, 23, 24],
  [3, 24],
  [23, 28]],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [[1],
  [17],
  [14],
  [10],
  [3],
  [9],
  [13],
  [15, 16, 17, 18, 19, 20],
  [18],
  [11]],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [[15],
  [5],
  [7],
  [5, 15],
  [28, 29, 30, 31, 32],
  [28, 29, 30],
  [7, 15],
  [10],
  [19],
  [28, 29, 30, 31]],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [[16],
  [18],
  [1],
  [12, 13, 14, 15, 16, 17, 18, 19],
  [17],
  [15],
  [14],
  [1, 2, 3, 4, 9, 10],
  [11],
  [6]],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [[19],
  [18],
  [1],
  [12],
  [9],
  [1, 2, 7, 8, 10, 22],
  [4],
  [5],
  [21],
  [10]],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [[10],
  [1],
  [3],
  [6],
  [2],
  [7],
  [27],
  [21],
  [25],
  [1, 2]],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [[10],
  [12],
  [9],
  [11],
  [4],
  [16],
  [11],
  [8],
  [2],
  [4, 11]],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [[1],
  [2],
  [1, 2],
  [21],
  [14],
  [23],
  [20],
  [13, 14],
  [9],
  [1, 13]],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [[10],
  [4, 11],
  [4],
  [9],
  [11],
  [3],
  [10],
  [10],
  [2, 4],
  [2]],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [[4, 11],
  [10],
  [11],
  [10],
  [9],
  [4],
  [3],
  [10],
  [2, 4, 11],
  [3, 11]],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [[34],
  [23],
  [33],
  [26],
  [21, 22, 23, 24, 26, 27],
  [14],
  [10],
  [18],
  [29],
  [24, 25]],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [[16],
  [11],
  [10],
  [8],
  [14],
  [5],
  [13],
  [19],
  [17],
  [12]],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [[29],
  [1],
  [6],
  [20],
  [29],
  [27],
  [29],
  [27, 28, 29],
  [27, 29],
  [19, 20, 24]],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [[22],
  [17],
  [7],
  [19],
  [9],
  [21],
  [11],
  [11, 22],
  [20],
  [7, 22]],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [[16],
  [1],
  [22],
  [24],
  [15],
  [9],
  [15, 16, 17, 22, 23, 24],
  [22, 24],
  [22, 24],
  [24]],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [[7],
  [7],
  [4],
  [17],
  [14, 15],
  [17],
  [13],
  [5, 6, 7, 8, 10, 11],
  [5, 7],
  [13, 14, 15]],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [[35],
  [37],
  [27, 28, 29, 30, 31, 32],
  [38],
  [4],
  [37, 38],
  [30],
  [11],
  [26, 35],
  [35]],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [[6],
  [17],
  [7],
  [5],
  [6, 7],
  [26],
  [25],
  [30],
  [33],
  [38]],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [[13],
  [14],
  [9],
  [15],
  [25],
  [12, 15],
  [8],
  [11],
  [28],
  [29]],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [[8],
  [25, 26],
  [22],
  [6],
  [3],
  [25, 26],
  [15],
  [21],
  [12],
  [20]],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [[6],
  [7],
  [14],
  [7, 15],
  [11],
  [15],
  [12],
  [15],
  [2, 7],
  [6, 7]],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [[3],
  [21],
  [18],
  [17],
  [4],
  [21],
  [15, 16, 17, 18, 19, 21],
  [13],
  [14],
  [19]],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [[22],
  [9],
  [20],
  [20, 22],
  [19],
  [6],
  [10],
  [11],
  [12],
  [23]],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [[27],
  [6],
  [31],
  [22],
  [31],
  [22, 31],
  [26],
  [6, 7, 8],
  [7, 8],
  [9, 10]],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [[19],
  [22],
  [9],
  [20, 22],
  [20],
  [18],
  [16],
  [21, 22],
  [10],
  [6]],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [[17],
  [18],
  [26],
  [29],
  [12],
  [4],
  [27],
  [14],
  [1],
  [7]],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [[17],
  [9],
  [18],
  [10],
  [20],
  [19],
  [6],
  [9, 18],
  [1, 17]],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [[28],
  [23],
  [27],
  [8],
  [23],
  [29],
  [24],
  [31],
  [16]],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [[21],
  [22],
  [23],
  [27],
  [23],
  [26],
  [24],
  [25],
  [8],
  [15, 16]],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [[42],
  [6],
  [23],
  [3],
  [29],
  [18],
  [43],
  [38],
  [44],
  [32]],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [[12, 17],
  [16],
  [12],
  [15],
  [5],
  [7, 8],
  [17],
  [11],
  [7],
  [8]],
 'Clc1ccccc1CN1CCc2sccc2C1': [[13],
  [15],
  [11, 12, 13, 14, 15],
  [4],
  [11, 12, 13, 14, 15, 16],
  [7],
  [14],
  [8],
  [3],
  [16]],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [[8],
  [7],
  [9],
  [10],
  [8],
  [4],
  [11],
  [4, 5, 8],
  [6],
  [10]],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [[16],
  [17],
  [16, 17],
  [1],
  [13, 15, 18, 20],
  [13, 15, 18],
  [13, 18, 20],
  [13, 15, 20],
  [15, 18],
  [26]],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [[1],
  [11],
  [12],
  [1, 16],
  [16],
  [16],
  [16],
  [12, 13, 14],
  [15],
  [10]],
 'NC(=O)c1nc(F)cnc1O': [[7],
  [10],
  [9],
  [8],
  [10],
  [9, 10],
  [1],
  [1, 2, 3, 9, 10],
  [1, 10],
  [3, 4, 5, 7, 8, 9]],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [[8],
  [17],
  [11, 17],
  [7],
  [3],
  [11, 16, 17],
  [11, 12, 13],
  [13],
  [14, 17],
  [16, 19]],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [[7],
  [8],
  [7],
  [5],
  [7],
  [6],
  [1],
  [8],
  [9]],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [[5],
  [6],
  [5, 6],
  [9],
  [20],
  [22],
  [20],
  [12],
  [23, 24],
  [14]],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [[5],
  [12],
  [12, 14, 17],
  [17],
  [5],
  [12, 14],
  [16],
  [15],
  [6],
  [13]],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [[21],
  [26],
  [7],
  [16, 26],
  [22],
  [13],
  [6],
  [13, 26],
  [4],
  [26]],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [[30],
  [11],
  [10, 30],
  [30, 47],
  [11, 30],
  [47],
  [10],
  [29, 30],
  [27, 30],
  [26]],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [[8],
  [16],
  [15],
  [18],
  [18],
  [9],
  [16, 17, 18],
  [14, 18],
  [8, 9],
  [1, 2, 3, 4, 11, 17, 18]],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [[19],
  [14],
  [18],
  [15],
  [19],
  [18, 19],
  [5]],
 'O=P1(NCCCl)OCCCN1CCCl': [[2],
  [10],
  [12],
  [9],
  [4],
  [12, 13],
  [5],
  [2, 10],
  [8],
  [7]],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [[1],
  [6],
  [3],
  [20, 21],
  [21],
  [21],
  [22],
  [9],
  [18, 19, 20, 21, 22, 23],
  [23]]}

In [200]:
df_total_old = pd.read_csv('output_65_site_truth_correct.csv')
substrates_old = df_total_old['substrate'].to_list()
sites_old = df_total_old['site_truth'].to_list()
sites_old = [get_reactive_atom_indices(i) for i in sites_old]
df_total_old['sites_old'] = sites_old
df_total_old

,substrate,metabolite,mapped_rxn,pred_rxn,site_truth,sites_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,[CH:1]#[C:2][C@:3]1([OH:4])[CH2:8][CH2:9][C@H:...,C#C[C@]1([O:1]C(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=...,[3]
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)[OH:1])CC1...,[19]
2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,CC(O)(CO)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1c...,[CH3:1][C:2]([OH:4])([CH2:3]O)[c:5]1[cH:6][cH:...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[40]
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,CC(C)(O)c1ccccc1[C@H](O)C[C@@H](SCC1(CC(=O)O)C...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1[CH2:1]C[C@@H](SCC1(CC(=O)O)CC...,[10]
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[CH3:1][C:2]([CH3:3])([OH:4])[c:5]1[cH:6][cH:7...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,[32]
...,...,...,...,...,...,...
174,O=P1(NCCCl)OCCCN1CCCl,O=CCCl,O=CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:7]=[CH:8][CH2:5][Cl:6]>>O=P1(NC[CH2:5][Cl:6...,O=P1(NC[CH2:1]Cl)N(CCCl)CC[CH2:1][O:1]1,"[4, 12, 13]"
175,O=P1(NCCCl)OCCCN1CCCl,NP1(=O)OCCCN1CCCl,NP1(=O)OCCCN1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[NH2:3][P:2]1(=[O:1])[O:7][CH2:8][CH2:9][CH2:1...,O=P1([NH:1]CCCl)OCCCN1CCCl,[2]
176,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCCC(O)N1CCCl>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[O:7][...,O=P1(NCCCl)OCC[CH2:1]N1CCCl,[9]
177,O=P1(NCCCl)OCCCN1CCCl,O=P1(NCCCl)NCCCO1,O=P1(NCCCl)NCCCO1>>O=P1(NCCCl)OCCCN1CCCl,[O:1]=[P:2]1([NH:3][CH2:4][CH2:5][Cl:6])[NH:11...,O=P1(NCCCl)OCCC[N:1]1CCCl,[10]
178,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1>>O...,O=[C:2]([OH:1])[CH2:3][O:4][CH2:5][CH2:6][N:7]...,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1]

In [201]:
def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
dict_sub2site = group_by_column_to_dict(df_total_old,'substrate','sites_old')
for i in list(dict_sub2site.keys()):
    sitelist = dict_sub2site[i]
    sitelist = [i for k in sitelist for i in k]
    sitelist = list(set(sitelist))
    dict_sub2site[i] = sitelist
dict_sub2site

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [3],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [40,
  32,
  10,
  19],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [1, 4, 5, 22, 23, 25],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [10, 11, 12, 13, 14, 15, 16, 17],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [2,
  7,
  50,
  59,
  60],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [2,
  14,
  15,
  16,
  21],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [6],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [12, 13, 6],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [19],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [11],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [23],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [26,
  7],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [24,
  16],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [2, 15],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [2, 13, 7],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [2],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [2],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [16],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [8, 12, 21, 22, 25],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [6],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [1, 6, 17],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [25,
  5,
  15],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [1, 12, 13, 14, 15, 16, 17, 18, 19],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [19, 12],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [3, 10, 16, 17, 23],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [9, 11, 12],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [1, 2],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [10],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [10],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [34],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [5, 8, 11, 16, 19],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [1, 29],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [17, 19, 22, 7],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [1, 26, 20, 21],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [5, 6, 7, 8, 10, 11, 13, 14, 15, 17],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [35, 22],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [25,
  6],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [11],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [8],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [6, 7, 12, 14, 15],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [3, 4],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [9],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [27],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [21],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [17, 12],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [17, 10, 18, 6],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [30, 23],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [22, 23],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [42,
  45],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [17, 12],
 'Clc1ccccc1CN1CCc2sccc2C1': [8, 11, 12, 13, 14, 15, 16],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [8, 10, 7],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [1, 13, 15, 16, 17, 18],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [],
 'NC(=O)c1nc(F)cnc1O': [7],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [8],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [1],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [1, 2, 7, 15, 16, 20],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [17, 5, 15],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [7],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [30,
  47],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [16, 17, 18],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [16, 17, 18, 19],
 'O=P1(NCCCl)OCCCN1CCCl': [2, 4, 9, 10, 12, 13],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [1]}

In [202]:
df_total = pd.read_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
true_sites_old = [dict_sub2site[i] for i in substrates]
metapredictor_results_old = [dict_sub2atomidxs[i] for i in substrates]
df_total.insert(2, 'true_sites_old', true_sites_old)
df_total['metapredictor_results_old'] = metapredictor_results_old
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,somp_results,xenosite_results,metapredictor_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ...","[[3], [17], [15, 17], [12], [15], [13, 14], [1..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ...","[[6], [19], [40], [7], [1, 40], [40], [1], [40..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ...","[[23], [22], [25], [4], [1], [3], [3, 25], [13..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21...","[[58], [2], [59], [45], [60], [25], [39], [34]..."
...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28...","[[30], [11], [10, 30], [30, 47], [11, 30], [47..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ...","[[8], [16], [15], [18], [18], [9], [16, 17, 18..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:...","[[19], [14], [18], [15], [19], [18, 19], [5]]"
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ...","[[2], [10], [12], [9], [4], [12, 13], [5], [2,..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ...","[[1], [6], [3], [20, 21], [21], [21], [22], [9..."

In [203]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

7、整理全部结果

In [204]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [205]:
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

In [206]:
df = pd.read_pickle('ourmodel_results.pickle')
df

,SMILES,metabolite,predict_site,atomidxs
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...,CC(=O)O[C@@]1(C#C)CC[C@@H]2[C@]1(CC)CC[C@@H]1[...,"[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...,CC([CH3:1])(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O...,"[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCC[CH2:...,"[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...,CC(CN1C2=CC=CC=C2[S:1]C2=CC=CC=C12)N(C)C|CC(CN...,"[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,"[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...,C1=CC=C2C(=C1OC1C(O)C(O)C(O)C(CO)O1)C(=O)C1=C(...,"[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...,O=C1[CH2:1]N=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1|O...,"[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1[OH:1]|C...,"[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1(NCCCl)OCCCN1[...,"[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOC[CH2:1]N1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C...,"[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [207]:
subs = df['SMILES'].to_list()
atomidxs = df['atomidxs'].to_list()
dict_sub2atomidxs = dict(zip(subs,atomidxs))
dict_sub2atomidxs

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': [[17],
  [15],
  [6],
  [12],
  [4],
  [12],
  [4],
  [25],
  [26],
  [21],
  [4, 21],
  [12]],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': [[40],
  [37, 38],
  [19],
  [14],
  [32],
  [40],
  [21],
  [12],
  [8],
  [40],
  [38, 39],
  [21],
  [7]],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': [[23],
  [5],
  [1],
  [23],
  [5],
  [25],
  [22],
  [3],
  [4],
  [16],
  [4],
  [4],
  [4],
  [25],
  [25]],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': [[10],
  [10],
  [13],
  [10],
  [15],
  [14],
  [14, 15],
  [17],
  [17],
  [5],
  [13],
  [15, 16],
  [16],
  [13]],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': [[26],
  [6],
  [34],
  [2],
  [15],
  [40],
  [60],
  [60],
  [31],
  [32],
  [59],
  [60],
  [18],
  [34],
  [50],
  [51],
  [7],
  [7],
  [45, 46]],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': [[15],
  [18],
  [15],
  [2],
  [24],
  [9],
  [24],
  [22, 24],
  [9],
  [16],
  [15],
  [18],
  [9],
  [18],
  [7],
  [18],
  [18],
  [4]],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': [[6],
  [6, 7],
  [6],
  [6, 7],
  [7],
  [7],
  [6, 7],
  [7],
  [1],
  [7, 8],
  [15],
  [12],
  [7],
  [6, 7],
  [8],
  [14],
  [6],
  [6, 7],
  [7],
  [6, 7],
  [14],
  [15]],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': [[6],
  [7],
  [19],
  [21],
  [2],
  [18],
  [18],
  [1],
  [9],
  [7, 8],
  [8, 9],
  [10],
  [1],
  [8]],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': [[19],
  [1],
  [19],
  [7],
  [2],
  [19],
  [19],
  [3],
  [19],
  [4],
  [5],
  [6],
  [13],
  [14],
  [19],
  [3],
  [19],
  [2]],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': [[12],
  [3],
  [13],
  [15],
  [39],
  [36],
  [12],
  [40],
  [18],
  [30],
  [41],
  [16],
  [25],
  [24],
  [21],
  [33],
  [27],
  [19]],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': [[20],
  [10],
  [19],
  [23],
  [23],
  [8],
  [27],
  [9],
  [3],
  [10, 11],
  [18],
  [4],
  [26],
  [11],
  [22],
  [9, 10]],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': [[1],
  [29],
  [27],
  [27],
  [3],
  [23],
  [8],
  [33],
  [2],
  [27],
  [1],
  [33],
  [18],
  [29],
  [29],
  [1],
  [27],
  [33]],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': [[16],
  [16],
  [16],
  [21],
  [16],
  [16],
  [2],
  [12],
  [16],
  [16],
  [15],
  [21],
  [13],
  [16]],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': [[2],
  [2],
  [15],
  [19],
  [16],
  [15],
  [15],
  [18],
  [19],
  [5],
  [8],
  [5],
  [15],
  [12]],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1': [[14],
  [14],
  [15],
  [2],
  [2],
  [14],
  [14],
  [14],
  [14],
  [5],
  [6],
  [14],
  [14],
  [14],
  [14],
  [5],
  [16],
  [16]],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': [[24],
  [36],
  [15],
  [16],
  [16],
  [30],
  [41],
  [15],
  [40],
  [10],
  [41],
  [15],
  [15],
  [11],
  [11],
  [27],
  [28],
  [40],
  [40],
  [40]],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': [[6],
  [6],
  [13],
  [5],
  [16],
  [5],
  [16],
  [3],
  [12, 17],
  [18],
  [5],
  [2],
  [2],
  [16],
  [3]],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': [[27],
  [28],
  [13],
  [26],
  [24],
  [11],
  [20],
  [28],
  [11]],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': [[22],
  [22],
  [8],
  [22],
  [24],
  [25],
  [25],
  [8],
  [8],
  [12],
  [7],
  [22],
  [17],
  [7],
  [5, 20]],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': [[15],
  [3],
  [28],
  [3],
  [15],
  [27],
  [24],
  [28],
  [22]],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21': [[18, 19],
  [14],
  [18],
  [17],
  [19, 20],
  [14],
  [19],
  [1],
  [1],
  [20],
  [14],
  [18],
  [18],
  [18, 19],
  [14],
  [18],
  [18, 19]],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': [[7],
  [5],
  [7],
  [9],
  [21]],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': [[18],
  [16],
  [18],
  [16],
  [16],
  [18],
  [1],
  [1],
  [18],
  [18],
  [3],
  [16],
  [16],
  [7],
  [6],
  [14],
  [18],
  [17]],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': [[18],
  [21],
  [5],
  [19],
  [7],
  [4],
  [6, 7],
  [22],
  [19, 20],
  [8],
  [20],
  [20, 21],
  [12],
  [5, 6]],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': [[10],
  [10],
  [10],
  [21],
  [3],
  [2],
  [8],
  [23],
  [23],
  [9],
  [7],
  [23],
  [6],
  [1],
  [11],
  [21],
  [27]],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': [[9],
  [12],
  [12],
  [16],
  [10],
  [11],
  [11],
  [8],
  [9],
  [11],
  [12],
  [11],
  [12],
  [9]],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': [[2],
  [1],
  [2],
  [21],
  [21],
  [1],
  [14],
  [1],
  [9],
  [2],
  [1],
  [1],
  [8],
  [20],
  [20]],
 'CN[C@@H](C)[C@@H](O)c1ccccc1': [[11],
  [11],
  [11],
  [9],
  [9],
  [11],
  [11],
  [10],
  [11],
  [11],
  [10],
  [9]],
 'CN[C@@H](C)[C@H](O)c1ccccc1': [[11],
  [11],
  [11],
  [9],
  [9],
  [11],
  [11],
  [10],
  [11],
  [10],
  [11],
  [11],
  [11],
  [9]],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': [[34],
  [27, 28],
  [28],
  [16],
  [23],
  [28],
  [11, 17],
  [9],
  [28],
  [29],
  [23],
  [18]],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': [[8],
  [8],
  [11],
  [11],
  [13],
  [13],
  [5],
  [13],
  [9],
  [14],
  [12],
  [13],
  [10],
  [13],
  [13],
  [10],
  [12],
  [12],
  [8],
  [8],
  [8],
  [8]],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': [[15],
  [29],
  [29],
  [18],
  [18],
  [20],
  [6],
  [23],
  [15],
  [27],
  [22],
  [8],
  [7],
  [6],
  [29],
  [25],
  [23],
  [17]],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': [[17],
  [10],
  [22],
  [24],
  [17],
  [17],
  [21],
  [22],
  [18],
  [7],
  [22],
  [22]],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': [[16],
  [15],
  [26],
  [18],
  [22],
  [17],
  [24],
  [20],
  [25],
  [20],
  [24],
  [11, 19]],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': [[17],
  [17],
  [11],
  [14, 15],
  [7],
  [8],
  [4],
  [17],
  [14],
  [10, 11],
  [17],
  [7],
  [13],
  [14]],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': [[22],
  [12],
  [4],
  [37],
  [31],
  [24],
  [38],
  [5],
  [32],
  [32],
  [19, 22]],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': [[26],
  [17],
  [7],
  [5],
  [32, 33],
  [5],
  [7],
  [38],
  [38],
  [31],
  [33],
  [30],
  [17],
  [26],
  [35],
  [30, 31],
  [6],
  [6]],
 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': [[14],
  [13],
  [10],
  [18],
  [18],
  [29],
  [14],
  [13],
  [13],
  [15],
  [25],
  [13],
  [20],
  [16],
  [26, 27],
  [17],
  [27, 28],
  [15],
  [27]],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': [[10],
  [12],
  [12],
  [21],
  [8, 10]],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': [[6],
  [12],
  [14],
  [15],
  [15],
  [5],
  [6],
  [5],
  [4, 15],
  [5],
  [14, 15],
  [12],
  [5],
  [11]],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': [[17],
  [17],
  [4],
  [21],
  [4],
  [21],
  [3],
  [6],
  [1],
  [21],
  [18],
  [21],
  [14],
  [8],
  [3],
  [6],
  [5],
  [21],
  [21]],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': [[9],
  [9],
  [22],
  [11],
  [23],
  [22],
  [12],
  [12],
  [11],
  [23],
  [22],
  [25],
  [22],
  [22],
  [10],
  [6],
  [6],
  [9],
  [9]],
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': [[6],
  [31],
  [18],
  [6]],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': [[22],
  [19],
  [22],
  [3],
  [9],
  [19],
  [9],
  [19],
  [21],
  [22],
  [9],
  [18],
  [14],
  [18]],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': [[17],
  [12],
  [26],
  [18],
  [8],
  [18],
  [17],
  [17],
  [18],
  [18],
  [27],
  [17],
  [12],
  [18],
  [18],
  [28],
  [17],
  [18],
  [12],
  [17]],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': [[17],
  [17],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [18],
  [9],
  [9],
  [9],
  [18],
  [18],
  [10],
  [12],
  [10],
  [9],
  [10]],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': [[23],
  [23],
  [21],
  [25],
  [27],
  [11],
  [24],
  [28],
  [30],
  [15],
  [29],
  [17],
  [29],
  [17],
  [27],
  [8],
  [23, 24],
  [16],
  [16],
  [15]],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': [[21],
  [21],
  [23],
  [21],
  [22],
  [21],
  [21],
  [23],
  [25],
  [5],
  [21],
  [16],
  [27],
  [21],
  [21]],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': [[42],
  [45],
  [45],
  [45],
  [6],
  [10],
  [38],
  [41],
  [33],
  [18],
  [44],
  [3],
  [4],
  [42],
  [42],
  [45],
  [29],
  [44]],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': [[5],
  [12],
  [12],
  [17],
  [15],
  [11],
  [7],
  [16],
  [17],
  [6],
  [19],
  [11],
  [18],
  [9],
  [17],
  [9]],
 'Clc1ccccc1CN1CCc2sccc2C1': [[13],
  [13, 14],
  [8],
  [8],
  [14],
  [13],
  [15],
  [11, 15],
  [15],
  [15],
  [15],
  [7],
  [3],
  [13],
  [16],
  [16],
  [13],
  [16]],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': [[7],
  [7],
  [7],
  [7],
  [7],
  [7],
  [9],
  [9],
  [7],
  [10],
  [10],
  [11],
  [10, 11]],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': [[17],
  [16, 17],
  [20],
  [20],
  [19],
  [19],
  [20],
  [20],
  [23],
  [22],
  [16],
  [16],
  [25],
  [16],
  [16, 17]],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': [[1],
  [6],
  [13],
  [12],
  [3, 16],
  [11],
  [16],
  [16],
  [15],
  [16],
  [16],
  [15],
  [15],
  [11, 12],
  [6],
  [16],
  [16],
  [5],
  [16]],
 'NC(=O)c1nc(F)cnc1O': [[1],
  [7],
  [10],
  [10],
  [5],
  [7],
  [1],
  [7],
  [1],
  [10],
  [5],
  [9],
  [7],
  [7],
  [8],
  [8],
  [8],
  [9],
  [10],
  [8],
  [8]],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': [[8],
  [8],
  [8],
  [14],
  [7],
  [8],
  [9],
  [17],
  [8],
  [11],
  [10],
  [17],
  [8],
  [11],
  [4],
  [8],
  [8],
  [13]],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': [[6],
  [14],
  [6],
  [8],
  [8],
  [14],
  [6],
  [8],
  [6]],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': [[1],
  [13],
  [9],
  [24],
  [23],
  [14],
  [14],
  [4],
  [24],
  [20],
  [15],
  [13],
  [19],
  [23, 24],
  [13],
  [6]],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': [[5],
  [5],
  [5],
  [5],
  [16],
  [5],
  [5],
  [13],
  [5],
  [15],
  [12],
  [5],
  [5],
  [17]],
 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': [[6],
  [6],
  [26],
  [26],
  [6],
  [6],
  [22],
  [26],
  [26],
  [6],
  [6]],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': [[27],
  [27],
  [27],
  [27],
  [27],
  [29],
  [27],
  [27],
  [27],
  [30],
  [27],
  [27],
  [30]],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': [[18],
  [15],
  [4],
  [8],
  [1],
  [13],
  [16],
  [18],
  [9],
  [18],
  [18],
  [17],
  [15, 16],
  [1],
  [18],
  [1],
  [15],
  [4],
  [1, 4],
  [17]],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': [[19],
  [10],
  [19],
  [14],
  [19],
  [10],
  [1],
  [19],
  [10],
  [15],
  [19],
  [17],
  [1],
  [6],
  [9],
  [19]],
 'O=P1(NCCCl)OCCCN1CCCl': [[9],
  [11],
  [9],
  [9],
  [9],
  [9],
  [7],
  [4],
  [8],
  [10],
  [10],
  [1],
  [1],
  [7]],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': [[5],
  [10],
  [5],
  [1],
  [21],
  [6],
  [6],
  [22],
  [4],
  [23],
  [24],
  [4],
  [25],
  [9],
  [9],
  [25],
  [22]]}

In [208]:
df_total = pd.read_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
ourmodel_results_old = [dict_sub2atomidxs[i] for i in substrates]
df_total['ourmodel_results_old'] = ourmodel_results_old
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,somp_results,xenosite_results,metapredictor_results_old,ourmodel_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 97, 1: 156, 2: 140, 3: 143, 4: 93, 5: 93, ...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ...","[[3], [17], [15, 17], [12], [15], [13, 14], [1...","[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","[40, 32, 10, 19]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 94, 1: 112, 2: 100, 3: 178, 4: 221, 5: 98,...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ...","[[6], [19], [40], [7], [1, 40], [40], [1], [40...","[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","[1, 4, 5, 22, 23, 25]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 70, 1: 32, 2: 76, 3: 91, 4: 127, 5: 41, 6:...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ...","[[23], [22], [25], [4], [1], [3], [3, 25], [13...","[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","[10, 11, 12, 13, 14, 15, 16, 17]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 78, 1: 67, 2: 92, 3: 96, 4: 107, 5: 61, 6:...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1...","[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 126, 1: 214, 2: 132, 3: 54, 4: 97, 5: 160,...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21...","[[58], [2], [59], [45], [60], [25], [39], [34]...","[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","[30, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 208, 1: 162, 2: 276, 3: 272, 4: 115, 5: 20...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28...","[[30], [11], [10, 30], [30, 47], [11, 30], [47...","[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","[16, 17, 18]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 52, 1: 85, 2: 13, 3: 54, 4: 101, 5: 71, 6:...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ...","[[8], [16], [15], [18], [18], [9], [16, 17, 18...","[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","[16, 17, 18, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 54, 1: 94, 2: 95, 3: 97, 4: 55, 5: 35, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:...","[[19], [14], [18], [15], [19], [18, 19], [5]]","[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","[2, 4, 9, 10, 12, 13]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 49, 1: 75, 2: 55, 3: 24, 4: 61, 5: 39, 6: ...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ...","[[2], [10], [12], [9], [4], [12, 13], [5], [2,...","[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 117, 1: 30, 2: 17, 3: 122, 4: 38, 5: 24, 6...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ...","[[1], [6], [3], [20, 21], [21], [21], [22], [9...","[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [209]:
df_total.to_pickle('output_65_site_truth_correct_withatomidx_noenzyme.pickle')

In [210]:
gnn_results = df_total['gnn_results'].to_list()
smartcyp_results = df_total['smartcyp_results'].to_list()
xenosite_results = df_total['xenosite_results'].to_list()
somp_results = df_total['somp_results'].to_list()

gnn_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in gnn_results]
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in smartcyp_results]
xenosite_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in xenosite_results]
somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in somp_results]

df_total['gnn_results'] = gnn_sorted_atoms
df_total['smartcyp_results'] = smartcyp_sorted_atoms
df_total['xenosite_results'] = xenosite_sorted_atoms
df_total['somp_results'] = somp_sorted_atoms
df_total

,substrates,true_sites,true_sites_old,gnn_results,smartcyp_results,somp_results,xenosite_results,metapredictor_results_old,ourmodel_results_old
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],[3],"[3, 2, 17, 4, 16, 1, 7, 15, 0, 18, 19, 14, 6, ...","[5, 12, 18, 20, 7, 25, 19, 8, 14, 11, 23, 22, ...","[14, 20, 10, 27, 7, 29, 12, 30, 23, 18, 25, 21...","[16, 17, 19, 11, 8, 14, 0, 21, 18, 7, 5, 3, 12...","[[3], [17], [15, 17], [12], [15], [13, 14], [1...","[[17], [15], [6], [12], [4], [12], [4], [25], ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[40, 32, 10, 19]","[40, 32, 10, 19]","[3, 1, 13, 19, 39, 2, 0, 31, 17, 33, 36, 30, 8...","[13, 34, 12, 33, 14, 28, 6, 37, 27, 10, 16, 0,...","[14, 6, 7, 25, 35, 10, 13, 24, 21, 34, 22, 29,...","[13, 3, 19, 0, 7, 33, 2, 27, 28, 25, 39, 6, 11...","[[6], [19], [40], [7], [1, 40], [40], [1], [40...","[[40], [37, 38], [19], [14], [32], [40], [21],..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 4, 5, 22, 23, 25]","[1, 4, 5, 22, 23, 25]","[16, 4, 17, 18, 19, 5, 3, 23, 13, 14, 7, 15, 1...","[3, 21, 22, 5, 20, 23, 4, 13, 1, 12, 0, 2, 11,...","[20, 23, 1, 12, 13, 5, 16, 0, 2, 8, 7, 11, 24,...","[4, 0, 19, 2, 1, 13, 12, 21, 7, 20, 22, 5, 3, ...","[[23], [22], [25], [4], [1], [3], [3, 25], [13...","[[23], [5], [1], [23], [5], [25], [22], [3], [..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[10, 11, 12, 13, 14, 15, 16, 17]","[10, 11, 12, 13, 14, 15, 16, 17]","[17, 19, 18, 2, 3, 1, 10, 14, 15, 9, 6, 0, 5, ...","[18, 19, 10, 1, 7, 13, 6, 14, 2, 8, 12, 5, 15,...","[18, 19, 10, 7, 13, 6, 14, 5, 8, 1, 12, 15, 17...","[17, 3, 10, 6, 7, 14, 13, 0, 1, 18, 2, 5, 8, 1...","[[13], [14], [10], [7], [11, 12, 13, 14, 15, 1...","[[10], [10], [13], [10], [15], [14], [14, 15],..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","[2, 7, 50, 59, 60]","[34, 18, 8, 35, 36, 54, 51, 59, 25, 39, 40, 9,...","[26, 12, 49, 29, 31, 45, 9, 25, 50, 6, 23, 7, ...","[29, 31, 6, 3, 61, 45, 7, 26, 4, 28, 56, 32, 5...","[25, 7, 10, 17, 44, 29, 30, 31, 34, 8, 0, 42, ...","[[58], [2], [59], [45], [60], [25], [39], [34]...","[[26], [6], [34], [2], [15], [40], [60], [60],..."
...,...,...,...,...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 47]","[30, 47]","[5, 6, 19, 20, 47, 52, 1, 15, 3, 31, 46, 18, 2...","[30, 51, 27, 32, 48, 53, 29, 34, 50, 55, 36, 5...","[39, 44, 30, 51, 38, 45, 40, 43, 34, 32, 55, 5...","[31, 52, 33, 54, 35, 56, 37, 58, 6, 20, 32, 2,...","[[30], [11], [10, 30], [30, 47], [11, 30], [47...","[[27], [27], [27], [27], [27], [29], [27], [27..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[16, 17, 18]","[16, 17, 18]","[1, 3, 0, 18, 2, 4, 15, 9, 6, 8, 12, 16, 11, 1...","[2, 3, 8, 15, 7, 9, 6, 10, 16, 12, 18, 0, 1, 1...","[2, 7, 8, 9, 15, 6, 10, 0, 16, 3, 12, 5, 14, 1...","[18, 3, 8, 15, 7, 6, 9, 10, 0, 2, 12, 16, 4, 1...","[[8], [16], [15], [18], [18], [9], [16, 17, 18...","[[18], [15], [4], [8], [1], [13], [16], [18], ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[16, 17, 18, 19]","[16, 17, 18, 19]","[19, 17, 18, 2, 1, 0, 10, 7, 6, 3, 14, 9, 5, 1...","[18, 14, 17, 5, 13, 15, 12, 16, 4, 8, 2, 0, 1,...","[18, 13, 14, 15, 5, 12, 16, 0, 4, 19, 8, 7, 17...","[2, 19, 14, 17, 5, 12, 13, 15, 16, 0, 4, 18, 8...","[[19], [14], [18], [15], [19], [18, 19], [5]]","[[19], [10], [19], [14], [19], [10], [1], [19]..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 4, 9, 10, 12, 13]","[2, 4, 9, 10, 12, 13]","[2, 3, 10, 11, 9, 0, 12, 1, 13, 7, 4, 5, 6, 8]","[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]","[9, 11, 3, 13, 5, 7, 8, 0, 2, 12, 10, 4, 6, 1]","[7, 2, 10, 1, 9, 4, 8, 3, 11, 6, 12, 0, 5, 13]","[[2], [10], [12], [9], [4], [12, 13], [5], [2,...","[[9], [11], [9], [9], [9], [9], [7], [4], [8],..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],[1],"[0, 1, 8, 10, 24, 4, 25, 9, 21, 6, 3, 23, 14, ...","[5, 10, 7, 25, 1, 2, 8, 24, 6, 14, 9, 19, 22, ...","[2, 5, 1, 10, 4, 14, 6, 13, 15, 19, 22, 18, 12...","[0, 6, 9, 14, 13, 2, 15, 1, 7, 19, 3, 4, 22, 8...","[[1], [6], [3], [20, 21], [21], [21], [22], [9...","[[5], [10], [5], [1], [21], [6], [6], [22], [4..."

In [211]:
df_total.to_pickle('output_65_site_truth_correct_withrank_noenzyme.pickle')

In [212]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

# 示例使用
nums = [1, 2, 2, 3, 4, 3, 5, 1, 6]
n = 4
result = get_unique_numbers(nums, n)
print(result)  # 输出: [1, 2, 3, 4]

[1, 2, 3, 4]

In [213]:
df_total = pd.read_pickle('output_65_site_truth_correct_withrank_noenzyme.pickle')

metapredictor_results_old = df_total['metapredictor_results_old'].to_list()
ourmodel_results_old = df_total['ourmodel_results_old'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)
metapredictor_results_new = []
for i in metapredictor_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    metapredictor_results_new.append(list_part)

true_sites_old = df_total['true_sites_old'].to_list()
true_sites = df_total['true_sites'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

gnn_top1_acc = acc_top_n(1,gnn_sorted_atoms,true_sites)
gnn_top3_acc = acc_top_n(3,gnn_sorted_atoms,true_sites)
gnn_top5_acc = acc_top_n(5,gnn_sorted_atoms,true_sites)
gnn_topn = []
gnn_topn.append(gnn_top1_acc)
gnn_topn.append(gnn_top3_acc)
gnn_topn.append(gnn_top5_acc)

smartcyp_top1_acc = acc_top_n(1,smartcyp_sorted_atoms,true_sites)
smartcyp_top3_acc = acc_top_n(3,smartcyp_sorted_atoms,true_sites)
smartcyp_top5_acc = acc_top_n(5,smartcyp_sorted_atoms,true_sites)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

xenosite_top1_acc = acc_top_n(1,xenosite_sorted_atoms,true_sites)
xenosite_top3_acc = acc_top_n(3,xenosite_sorted_atoms,true_sites)
xenosite_top5_acc = acc_top_n(5,xenosite_sorted_atoms,true_sites)
xenosite_topn = []
xenosite_topn.append(xenosite_top1_acc)
xenosite_topn.append(xenosite_top3_acc)
xenosite_topn.append(xenosite_top5_acc)

somp_top1_acc = acc_top_n(1,somp_sorted_atoms,true_sites)
somp_top3_acc = acc_top_n(3,somp_sorted_atoms,true_sites)
somp_top5_acc = acc_top_n(5,somp_sorted_atoms,true_sites)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites_old)
metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites_old)
metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites_old)
metapredictor_topn = []
metapredictor_topn.append(metapredictor_top1_acc)
metapredictor_topn.append(metapredictor_top3_acc)
metapredictor_topn.append(metapredictor_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.26153846153846155
top 3 accuracy = 0.5076923076923077
top 5 accuracy = 0.676923076923077
top 1 accuracy = 0.16923076923076924
top 3 accuracy = 0.4
top 5 accuracy = 0.5384615384615384
top 1 accuracy = 0.3230769230769231
top 3 accuracy = 0.5538461538461539
top 5 accuracy = 0.6923076923076923
top 1 accuracy = 0.09230769230769231
top 3 accuracy = 0.3076923076923077
top 5 accuracy = 0.46153846153846156
top 1 accuracy = 0.7076923076923077
top 3 accuracy = 0.8923076923076924
top 5 accuracy = 0.9538461538461539
top 1 accuracy = 0.5230769230769231
top 3 accuracy = 0.7076923076923077
top 5 accuracy = 0.8

In [214]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['gnnsom_topn'] = gnn_topn
df['smartcyp_topn'] = smartcyp_topn
df['xenosite_topn'] = xenosite_topn
df['somp_topn'] = somp_topn
df['metapredictor_topn'] = metapredictor_topn
df['ourmodel_topn'] = ourmodel_topn
df

,top_n,gnnsom_topn,smartcyp_topn,xenosite_topn,somp_topn,metapredictor_topn,ourmodel_topn
0,top1_recall,0.261538,0.169231,0.323077,0.092308,0.707692,0.523077
1,top3_recall,0.507692,0.400000,0.553846,0.307692,0.892308,0.707692
2,top5_recall,0.676923,0.538462,0.692308,0.461538,0.953846,0.800000