In [21]:
import pandas as pd
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/predict_site_withec.csv')
substrates = df['SMILES'].to_list()

In [20]:
i = 1
filepath = f'SMARTCYP_results ({i}).csv'
df_part = pd.read_csv(filepath)
df_part

,Unnamed: 0,Molecule_Name,Molecule_Number,Atom_Number,Atom_Name,Atom,Span2end,Span2end_N_Correction,Span2end_CO_Correction,COO-Dist,...,Reactivity,Energy,3A4 Score,2D6 Score,2C9 Score,3A4 Ranking,2D6 Ranking,2C9 Ranking,N_ox,Similarity
0,0,Smiles,0,0,C,C.1,0,0.00,0.00,12,...,89.6,89.6,79.497889,87.497889,87.497889,23,8,5,0.0,0.333333
1,1,Smiles,0,1,C,C.2,1,6.70,5.90,11,...,999.0,999.0,991.467615,1005.697027,1004.897027,28,28,27,0.0,0.000000
2,2,Smiles,0,2,C,C.3,0,0.00,0.00,12,...,89.6,89.6,79.497889,87.497889,87.497889,23,8,5,0.0,0.333333
3,3,Smiles,0,3,O,O.4,0,0.00,0.00,12,...,999.0,999.0,991.000000,999.000000,999.000000,25,25,25,0.0,0.333333
4,4,Smiles,0,4,C,C.5,2,13.40,11.80,10,...,999.0,999.0,991.877460,1012.336283,1010.736283,30,30,29,0.0,0.000000
5,5,Smiles,0,5,C,C.6,1,6.70,5.90,11,...,86.3,86.3,77.792349,92.021761,91.221761,19,14,11,0.0,0.666667
6,6,Smiles,0,6,C,C.7,0,0.00,0.00,12,...,86.3,86.3,77.026032,85.026032,85.026032,17,6,3,0.0,1.000000
7,7,Smiles,0,7,C,C.8,1,6.70,5.90,11,...,86.3,86.3,77.430640,91.660052,90.860052,18,13,10,0.0,1.000000
8,8,Smiles,0,8,C,C.9,2,13.40,11.80,10,...,86.3,86.3,78.208654,98.667478,97.067478,20,16,13,0.0,0.666667
9,9,Smiles,0,9,C,C.10,3,20.10,17.70,9,...,999.0,999.0,992.318923,1019.007159,1016.607159,32,32,31,0.0,0.000000
10,10,Smiles,0,10,C,C.11,4,26.84,23.64,8,...,66.4,66.4,59.572804,92.530451,89.330451,6,15,9,0.0,0.400000
11,11,Smiles,0,11,C,C.12,5,26.85,23.65,7,...,75.9,75.9,69.636511,102.133570,104.833570,12,18,20,0.0,0.400000
12,12,Smiles,0,12,C,C.13,6,26.86,23.66,6,...,57.7,57.7,52.361601,84.398072,92.998072,3,5,12,0.0,0.400000
13,13,Smiles,0,13,S,S.14,5,26.85,23.65,5,...,26.3,26.3,19.600440,52.097499,66.597499,1,1,1,0.0,0.400000
14,14,Smiles,0,14,C,C.15,4,26.84,23.64,4,...,57.7,57.7,50.952085,83.909732,104.309732,2,4,19,0.0,0.400000
15,15,Smiles,0,15,C,C.16,3,20.10,17.70,3,...,999.0,999.0,992.396922,1019.085158,1046.185158,33,33,37,0.0,0.000000
16,16,Smiles,0,16,C,C.17,2,13.40,11.80,2,...,66.4,66.4,58.409622,78.868445,112.668445,4,3,24,0.0,0.400000
17,17,Smiles,0,17,C,C.18,1,6.70,5.90,1,...,999.0,999.0,991.175960,1005.405372,1045.905372,26,26,36,0.0,0.000000
18,18,Smiles,0,18,O,O.19,0,0.00,0.00,0,...,999.0,999.0,991.000000,999.000000,1046.200000,25,25,38,0.0,0.666667
19,19,Smiles,0,19,O,O.20,0,0.00,0.00,2,...,999.0,999.0,991.000000,999.000000,1034.400000,25,25,35,0.0,0.333333
20,20,Smiles,0,20,C,C.21,2,13.40,11.80,4,...,75.9,75.9,67.099041,87.557865,109.557865,9,9,23,0.0,0.333333
21,21,Smiles,0,21,C,C.22,2,13.40,11.80,4,...,75.9,75.9,67.099041,87.557865,109.557865,9,9,23,0.0,0.333333
22,22,Smiles,0,22,C,C.23,7,26.87,23.67,7,...,999.0,999.0,994.201961,1025.777844,1028.477844,35,36,34,0.0,0.000000
23,23,Smiles,0,23,C,C.24,6,26.86,23.66,8,...,80.8,80.8,74.558017,106.594488,103.394488,14,21,17,0.0,0.666667
24,24,Smiles,0,24,C,C.25,7,26.87,23.67,9,...,86.3,86.3,80.363786,111.939669,108.739669,24,23,21,0.0,1.000000
25,25,Smiles,0,25,C,C.26,7,26.87,23.67,10,...,80.8,80.8,74.905973,106.481856,103.281856,15,20,16,0.0,0.666667
26,26,Smiles,0,26,C,C.27,8,26.88,23.68,9,...,999.0,999.0,994.605647,1025.720941,1022.520941,36,35,33,0.0,0.000000
27,27,Smiles,0,27,C,C.28,7,26.87,23.67,10,...,65.6,65.6,60.081889,91.657772,88.457772,8,12,8,0.0,0.333333
28,28,Smiles,0,28,C,C.29,6,26.86,23.66,11,...,65.6,65.6,59.591181,91.627652,88.427652,7,11,7,0.0,0.333333
29,29,Smiles,0,29,C,C.30,5,26.85,23.65,12,...,999.0,999.0,993.146529,1025.643587,1022.443587,34,34,32,0.0,0.000000
30,30,Smiles,0,30,C,C.31,4,26.84,23.64,13,...,86.3,86.3,79.083706,112.041353,108.841353,22,24,22,0.0,0.666667
31,31,Smiles,0,31,C,C.32,3,20.10,17.70,14,...,86.3,86.3,78.636741,105.324977,102.924977,21,19,15,0.0,0.666667
32,32,Smiles,0,32,C,C.33,2,13.40,11.80,15,...,999.0,999.0,991.674676,1012.133499,1010.533499,29,29,28,0.0,0.000000
33,33,Smiles,0,33,C,C.34,1,6.70,5.90,16,...,80.8,80.8,72.162575,86.391986,85.591986,13,7,4,0.0,0.666667
34,34,Smiles,0,34,C,C.35,0,0.00,0.00,17,...,68.2,68.2,59.071167,67.071167,67.071167,5,2,2,0.0,0.666667
35,35,Smiles,0,35,C,C.36,1,6.70,5.90,16,...,999.0,999.0,991.247208,1005.476620,1004.676620,27,27,26,0.0,0.000000
36,36,Smiles,0,37,C,C.38,2,13.40,11.80,15,...,77.2,77.2,69.180522,89.639346,88.039346,11,10,6,0.0,0.333333
37,37,Smiles,0,38,C,C.39,3,20.10,17.70,14,...,999.0,999.0,992.123336,1018.811571,1016.411571,31,31,30,0.0,0.000000
38,38,Smiles,0,39,N,N.40,4,26.84,23.64,13,...,75.6,75.6,68.927639,101.885286,98.685286,10,17,14,0.0,0.333333
39,39,Smiles,0,40,C,C.41,8,26.88,23.68,8,...,80.8,80.8,75.727624,106.842918,103.642918,16,22,18,0.0,0.333333

In [24]:
df_new = pd.DataFrame(columns=['substrates','enzyme','scores'])
from rdkit import Chem

subs_new = []
enzymes_new = []
scores_new = []

for i in range(len(substrates)):
    sub = substrates[i]
    if i == 0:
        filepath = f'SMARTCYP_results.csv'
    else:
        filepath = f'SMARTCYP_results ({i}).csv'

    df_part = pd.read_csv(filepath)

    # 解析 SMILES
    molecule = Chem.MolFromSmiles(sub)
    # 获取原子数
    atom_count = molecule.GetNumAtoms()

    # try:
    atomidxs = df_part['Atom_Number'].to_list()
    # assert atom_count == max(atomidxs)+1

    ranks_3a4 = df_part['3A4 Ranking'].to_list()
    ranks_2d6 = df_part['2D6 Ranking'].to_list()
    ranks_2c9 = df_part['2C9 Ranking'].to_list()
    dict_atomidx2rank3a4 = dict(zip(atomidxs,ranks_3a4))
    dict_atomidx2rank2d6 = dict(zip(atomidxs,ranks_2d6))
    dict_atomidx2rank2c9 = dict(zip(atomidxs,ranks_2c9))

    subs_new.append(sub)
    subs_new.append(sub)
    subs_new.append(sub)

    enzymes_new.append('3A4')
    enzymes_new.append('2D6')
    enzymes_new.append('2C9')

    scores_new.append(dict_atomidx2rank3a4)
    scores_new.append(dict_atomidx2rank2d6)
    scores_new.append(dict_atomidx2rank2c9)

    # except:
    #     print(sub)
    #     print(len(df_part))
    #     print(atom_count)

df_new['substrates'] = subs_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = scores_new

df_new

,substrates,enzyme,scores
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,3A4,"{0: 17, 1: 22, 2: 24, 3: 23, 4: 20, 5: 3, 6: 1..."
1,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2D6,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
2,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2C9,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,3A4,"{0: 23, 1: 28, 2: 23, 3: 25, 4: 30, 5: 19, 6: ..."
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,2D6,"{0: 8, 1: 28, 2: 8, 3: 25, 4: 30, 5: 14, 6: 6,..."
...,...,...,...
190,O=P1(NCCCl)OCCCN1CCCl,2D6,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
191,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
192,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,3A4,"{0: 15, 1: 7, 2: 8, 3: 17, 4: 9, 5: 1, 6: 5, 7..."
193,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2D6,"{0: 15, 1: 1, 2: 2, 3: 17, 4: 10, 5: 4, 6: 11,..."
194,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2C9,"{0: 15, 1: 5, 2: 6, 3: 17, 4: 9, 5: 2, 6: 7, 7..."

In [25]:
df_new.to_pickle('smartcyp_results.pickle')

In [26]:
df = pd.read_pickle('smartcyp_results.pickle')
df

,substrates,enzyme,scores
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,3A4,"{0: 17, 1: 22, 2: 24, 3: 23, 4: 20, 5: 3, 6: 1..."
1,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2D6,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
2,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2C9,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1..."
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,3A4,"{0: 23, 1: 28, 2: 23, 3: 25, 4: 30, 5: 19, 6: ..."
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,2D6,"{0: 8, 1: 28, 2: 8, 3: 25, 4: 30, 5: 14, 6: 6,..."
...,...,...,...
190,O=P1(NCCCl)OCCCN1CCCl,2D6,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
191,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ..."
192,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,3A4,"{0: 15, 1: 7, 2: 8, 3: 17, 4: 9, 5: 1, 6: 5, 7..."
193,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2D6,"{0: 15, 1: 1, 2: 2, 3: 17, 4: 10, 5: 4, 6: 11,..."
194,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2C9,"{0: 15, 1: 5, 2: 6, 3: 17, 4: 9, 5: 2, 6: 7, 7..."

In [27]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC': {0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 53, 7: 15, 8: 27, 9: 42, 10: 43, 11: 31, 12: 6, 13: 75, 14: 29, 15: 63, 16: 56, 17: 53, 18: 9, 19: 24, 20: 10, 21: 40, 22: 35, 23: 34, 24: 78, 25: 18, 26: 40}, 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1': {0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: 26, 7: 41, 8: 49, 9: 95, 10: 30, 11: 50, 12: 20, 13: 3, 14: 25, 15: 103, 16: 31, 17: 88, 18: 88, 19: 85, 20: 41, 21: 41, 22: 105, 23: 52, 24: 68, 25: 51, 26: 104, 27: 28, 28: 25, 29: 100, 30: 68, 31: 55, 32: 86, 33: 24, 34: 9, 35: 80, 37: 27, 38: 92, 39: 41, 40: 56}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 53, 7: 36, 8: 33, 9: 55, 10: 55, 11: 28, 12: 24, 13: 18, 14: 33, 15: 54, 16: 51, 17: 47, 18: 47, 19: 34, 20: 13, 21: 12, 22: 12, 23: 13, 24: 33, 25: 36}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: 15, 7: 11, 8: 19, 9: 36, 10: 6, 11: 36, 12: 19, 13: 11, 14: 15, 15: 24, 16: 39, 17: 33, 18: 5, 19: 5}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6: 26, 7: 35, 8: 50, 9: 21, 10: 53, 11: 138, 12: 12, 13: 75, 14: 140, 15: 136, 16: 137, 17: 76, 18: 136, 19: 133, 20: 133, 21: 126, 22: 63, 23: 34, 24: 109, 25: 21, 26: 6, 27: 45, 28: 36, 29: 18, 30: 87, 31: 18, 32: 36, 33: 117, 34: 115, 35: 113, 36: 113, 37: 67, 38: 143, 39: 139, 40: 122, 41: 58, 42: 54, 43: 105, 44: 96, 45: 18, 46: 39, 47: 109, 48: 48, 49: 15, 50: 21, 51: 50, 52: 120, 53: 115, 54: 65, 55: 60, 56: 90, 58: 60, 59: 65, 60: 48}, 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O': {0: 21, 1: 48, 2: 21, 3: 6, 4: 14, 5: 19, 6: 32, 7: 56, 8: 53, 9: 7, 10: 14, 11: 53, 12: 23, 13: 17, 14: 42, 15: 38, 16: 17, 17: 23, 18: 54, 19: 50, 20: 29, 21: 16, 22: 47, 23: 45, 24: 41}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 15, 1: 8, 2: 36, 3: 29, 4: 11, 5: 7, 6: 4, 7: 7, 8: 11, 9: 30, 10: 26, 11: 18, 12: 25, 13: 25, 14: 18, 15: 30, 16: 26}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 23, 1: 14, 2: 5, 3: 42, 4: 36, 5: 13, 6: 13, 7: 5, 8: 24, 9: 45, 10: 14, 11: 52, 12: 53, 13: 48, 14: 24, 15: 39, 17: 33, 18: 30, 19: 39, 21: 24}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 19, 1: 9, 2: 13, 3: 20, 4: 25, 5: 28, 6: 31, 7: 14, 8: 51, 9: 39, 10: 39, 11: 51, 12: 22, 13: 31, 14: 50, 15: 12, 16: 13, 17: 46, 18: 13, 19: 46, 20: 39, 21: 39}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 50, 1: 30, 2: 58, 3: 4, 4: 10, 5: 72, 6: 18, 7: 65, 8: 79, 9: 78, 10: 87, 11: 90, 12: 62, 13: 46, 14: 93, 15: 43, 16: 46, 17: 96, 18: 51, 19: 54, 20: 99, 21: 54, 22: 51, 23: 96, 24: 46, 25: 43, 26: 93, 27: 39, 28: 36, 29: 90, 30: 33, 31: 30, 32: 82, 33: 27, 34: 24, 35: 79, 36: 16, 37: 11, 38: 69, 39: 6, 40: 65, 41: 18}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 24, 1: 12, 2: 19, 3: 7, 4: 55, 5: 48, 6: 45, 7: 29, 8: 16, 9: 26, 10: 23, 11: 51, 12: 59, 13: 65, 14: 65, 15: 65, 16: 35, 17: 69, 19: 63, 20: 69, 21: 23, 22: 14, 23: 42, 24: 11, 25: 34, 26: 11, 27: 34, 28: 69, 30: 35}, 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1': {0: 60, 1: 41, 2: 16, 3: 3, 4: 94, 5: 50, 6: 91, 7: 13, 8: 6, 9: 38, 10: 33, 11: 92, 12: 54, 13: 41, 14: 75, 16: 78, 18: 57, 19: 89, 20: 64, 21: 65, 22: 69, 23: 30, 24: 44, 25: 26, 26: 81, 27: 14, 28: 11, 29: 72, 30: 21, 31: 81, 32: 25, 33: 95, 34: 88, 35: 47}, 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1': {0: 42, 1: 35, 2: 42, 3: 50, 4: 51, 5: 18, 6: 77, 7: 76, 8: 60, 9: 40, 10: 51, 11: 52, 13: 35, 14: 72, 15: 19, 16: 3, 17: 12, 18: 18, 19: 63, 20: 23, 21: 66, 22: 26, 23: 69, 24: 28, 25: 11, 26: 14}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 22, 1: 6, 2: 30, 3: 6, 4: 22, 5: 10, 6: 20, 7: 27, 8: 49, 9: 49, 10: 46, 11: 21, 12: 36, 14: 33, 15: 6, 16: 12, 17: 42, 18: 39, 19: 11}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 18, 1: 5, 2: 24, 3: 5, 4: 18, 5: 9, 6: 19, 7: 39, 8: 34, 9: 34, 10: 31, 11: 17, 12: 10, 13: 27, 14: 6, 15: 10, 16: 17}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 57, 1: 9, 2: 35, 3: 101, 4: 28, 5: 103, 6: 99, 7: 55, 8: 59, 9: 93, 10: 21, 11: 26, 12: 15, 13: 28, 14: 77, 15: 28, 16: 15, 17: 59, 18: 55, 19: 28, 20: 98, 21: 87, 22: 98, 23: 60, 24: 32, 25: 86, 26: 77, 27: 23, 28: 46, 29: 68, 30: 16, 31: 33, 32: 74, 33: 71, 34: 93, 35: 38, 36: 13, 37: 47, 38: 24, 39: 80, 40: 24, 41: 47}, 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 20, 1: 3, 2: 11, 3: 7, 4: 19, 5: 19, 6: 22, 7: 42, 8: 37, 9: 37, 10: 46, 11: 16, 12: 43, 13: 41, 14: 22, 15: 35, 16: 35, 17: 26, 18: 50}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 16, 1: 9, 2: 54, 3: 57, 4: 54, 5: 41, 6: 66, 7: 34, 8: 39, 9: 72, 10: 76, 11: 43, 12: 48, 13: 73, 14: 67, 15: 11, 16: 51, 17: 5, 18: 30, 19: 5, 20: 30, 21: 68, 22: 34, 23: 24, 24: 18, 25: 27, 26: 61, 27: 12, 28: 17}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 28, 1: 23, 2: 53, 3: 60, 4: 53, 5: 67, 6: 67, 7: 17, 8: 5, 9: 48, 10: 22, 11: 25, 12: 13, 13: 25, 14: 22, 15: 36, 16: 22, 17: 60, 18: 23, 19: 48, 21: 47, 22: 43, 23: 59, 24: 14, 25: 39, 26: 6, 27: 6, 28: 66}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 9, 1: 24, 2: 9, 3: 41, 4: 38, 5: 17, 6: 54, 7: 47, 8: 54, 9: 10, 10: 57, 11: 28, 12: 23, 13: 56, 14: 64, 15: 57, 16: 59, 17: 58, 18: 26, 19: 31, 20: 53, 21: 17, 22: 46, 23: 8, 24: 5, 25: 31, 26: 26, 27: 23, 28: 28}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 5, 1: 33, 2: 5, 3: 10, 4: 23, 5: 17, 6: 30, 7: 39, 8: 25, 9: 17, 10: 9, 11: 20, 12: 36, 13: 9, 14: 9, 15: 36, 16: 20, 17: 9, 18: 17, 19: 25, 20: 39}, 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O': {0: 3, 1: 12, 2: 3, 3: 46, 4: 9, 5: 19, 6: 49, 7: 46, 8: 63, 9: 56, 10: 21, 11: 25, 12: 30, 13: 31, 14: 16, 15: 36, 16: 9, 17: 9, 18: 68, 19: 60, 20: 59, 21: 45, 22: 23, 23: 42, 24: 69, 25: 59, 26: 86, 27: 75, 28: 85, 29: 80, 30: 79, 31: 72, 32: 68}, 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3': {0: 3, 1: 11, 2: 6, 3: 16, 4: 46, 5: 25, 6: 30, 7: 32, 8: 60, 9: 53, 10: 10, 11: 23, 12: 54, 13: 23, 14: 19, 15: 39, 16: 36, 17: 47, 18: 42, 19: 55}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 4, 1: 30, 2: 63, 3: 9, 4: 31, 5: 5, 6: 35, 7: 51, 8: 60, 9: 54, 10: 42, 11: 37, 12: 18, 13: 66, 14: 69, 15: 57, 16: 45, 17: 17, 18: 16, 19: 22, 20: 25, 21: 48, 22: 24}, 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1': {0: 4, 1: 41, 2: 60, 3: 57, 4: 66, 5: 33, 6: 12, 7: 30, 8: 34, 9: 79, 10: 5, 11: 80, 12: 44, 13: 39, 14: 77, 15: 77, 16: 19, 17: 15, 18: 63, 19: 46, 20: 29, 21: 21, 22: 45, 23: 17, 24: 54, 25: 70, 26: 76, 27: 25}, 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1': {0: 5, 1: 16, 2: 11, 3: 31, 4: 24, 5: 49, 6: 43, 7: 24, 8: 24, 9: 12, 10: 27, 11: 40, 12: 10, 13: 46, 14: 35, 15: 28, 16: 19, 17: 28, 18: 35}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 5, 1: 18, 2: 12, 3: 56, 4: 23, 5: 63, 6: 57, 7: 29, 8: 22, 9: 11, 10: 25, 11: 48, 13: 45, 14: 64, 15: 58, 16: 58, 17: 53, 18: 33, 19: 26, 20: 26, 21: 12, 22: 39, 23: 34}, 'CN[C@@H](C)[C@@H](O)c1ccccc1': {0: 3, 1: 11, 2: 7, 3: 23, 4: 14, 5: 27, 6: 30, 7: 22, 8: 16, 9: 12, 10: 16, 11: 22}, 'CN[C@@H](C)[C@H](O)c1ccccc1': {0: 3, 1: 11, 2: 7, 3: 23, 4: 14, 5: 27, 6: 30, 7: 22, 8: 16, 9: 12, 10: 16, 11: 22}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 5, 1: 87, 2: 79, 3: 92, 4: 83, 5: 32, 6: 20, 7: 68, 8: 22, 9: 63, 10: 40, 11: 54, 12: 4, 13: 48, 14: 48, 15: 18, 16: 17, 17: 74, 18: 36, 19: 29, 20: 73, 21: 76, 22: 42, 23: 20, 24: 51, 25: 48, 26: 9, 27: 60, 28: 57, 29: 28, 30: 84, 31: 79, 32: 38, 33: 38, 34: 38}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 12, 1: 39, 2: 45, 3: 22, 4: 51, 5: 15, 6: 48, 7: 27, 8: 19, 9: 30, 10: 3, 11: 22, 12: 42, 13: 8, 14: 22, 15: 45, 16: 39, 17: 12, 18: 36, 19: 33, 20: 7}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 3, 1: 45, 2: 51, 3: 15, 4: 61, 5: 11, 6: 37, 7: 21, 8: 70, 9: 75, 10: 72, 11: 26, 12: 35, 13: 72, 14: 40, 15: 64, 16: 63, 17: 32, 18: 10, 19: 11, 20: 11, 21: 75, 23: 29, 24: 65, 25: 28, 26: 58, 27: 48, 28: 17, 29: 45}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 9, 1: 51, 2: 54, 3: 25, 4: 38, 5: 63, 6: 25, 7: 12, 8: 45, 9: 21, 10: 9, 11: 22, 12: 69, 13: 66, 14: 28, 15: 28, 16: 57, 17: 3, 18: 60, 19: 32, 20: 22, 21: 48, 22: 41, 23: 38, 24: 25}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 3, 1: 39, 2: 46, 3: 25, 4: 33, 5: 66, 6: 71, 7: 70, 8: 70, 9: 36, 10: 17, 11: 60, 12: 51, 13: 42, 14: 11, 15: 9, 16: 15, 17: 16, 18: 47, 19: 54, 20: 14, 21: 26, 22: 63, 23: 29, 24: 57, 25: 33, 26: 25}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 5, 1: 39, 2: 45, 3: 19, 4: 18, 5: 36, 6: 24, 7: 17, 8: 30, 9: 27, 10: 39, 11: 42, 12: 48, 13: 10, 14: 10, 15: 33, 16: 5, 17: 5}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 3, 1: 56, 2: 59, 3: 19, 4: 10, 5: 14, 6: 29, 7: 68, 8: 85, 9: 85, 10: 89, 11: 48, 12: 94, 13: 93, 14: 93, 15: 85, 16: 45, 17: 40, 18: 65, 19: 56, 20: 30, 21: 30, 22: 30, 23: 40, 24: 45, 25: 36, 26: 75, 27: 65, 28: 23, 29: 37, 30: 25, 31: 37, 32: 23, 33: 31, 34: 78, 35: 72, 36: 12, 37: 6, 38: 51}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 14, 1: 83, 2: 76, 3: 76, 4: 31, 5: 13, 6: 28, 7: 19, 8: 93, 9: 49, 10: 50, 11: 96, 12: 103, 13: 49, 14: 39, 15: 87, 16: 28, 17: 60, 18: 31, 19: 98, 20: 25, 21: 93, 22: 53, 23: 34, 24: 85, 25: 94, 26: 13, 27: 76, 28: 30, 29: 30, 30: 21, 31: 71, 33: 33, 34: 88, 36: 56, 37: 103, 38: 53, 39: 104}, 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 35, 1: 13, 2: 70, 3: 69, 4: 27, 5: 73, 6: 70, 7: 29, 8: 44, 9: 48, 10: 20, 11: 27, 12: 7, 13: 12, 14: 7, 15: 27, 16: 34, 17: 41, 18: 22, 19: 63, 20: 7, 21: 60, 22: 54, 24: 24, 25: 18, 26: 51, 28: 57}, 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4': {0: 26, 1: 16, 2: 19, 3: 28, 4: 33, 5: 36, 6: 43, 7: 36, 8: 71, 9: 71, 10: 66, 11: 24, 12: 18, 13: 58, 14: 58, 15: 54, 16: 69, 17: 3, 18: 64, 19: 55, 20: 33, 21: 9, 22: 12, 23: 24, 24: 61, 25: 58, 26: 52}, 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 24, 1: 4, 2: 10, 3: 31, 4: 18, 5: 18, 6: 18, 7: 39, 8: 36, 9: 32, 10: 14, 11: 14, 12: 7, 13: 27, 15: 17}, 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 36, 1: 25, 2: 8, 3: 14, 4: 5, 5: 24, 6: 21, 7: 42, 8: 60, 9: 54, 10: 54, 11: 57, 12: 32, 13: 27, 14: 15, 15: 48, 16: 29, 17: 11, 18: 26, 19: 45, 21: 51}, 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 22, 1: 14, 2: 14, 3: 51, 4: 57, 5: 52, 6: 22, 7: 9, 8: 17, 9: 11, 10: 4, 11: 17, 12: 9, 13: 54, 15: 25, 16: 52, 17: 48, 18: 43, 19: 45, 20: 41, 21: 43, 22: 37, 23: 27, 24: 56, 25: 52}, 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O': {0: 42, 1: 29, 2: 23, 3: 32, 4: 26, 5: 18, 6: 8, 7: 58, 8: 23, 9: 51, 10: 48, 11: 20, 12: 3, 13: 68, 14: 37, 15: 75, 17: 11, 18: 72, 19: 27, 20: 80, 21: 45, 22: 74, 23: 69, 24: 72, 25: 64, 26: 16, 27: 65, 28: 62, 29: 59, 30: 54, 31: 54}, 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O': {0: 42, 1: 63, 2: 3, 3: 23, 4: 48, 5: 45, 6: 54, 8: 60, 9: 8, 10: 29, 11: 32, 12: 36, 13: 29, 14: 20, 15: 57, 16: 29, 17: 23, 18: 13, 19: 7, 20: 51, 21: 21, 22: 45}, 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 24, 1: 68, 2: 40, 3: 76, 4: 41, 5: 16, 6: 41, 7: 27, 8: 27, 9: 16, 10: 36, 11: 14, 12: 76, 13: 69, 14: 58, 15: 36, 16: 14, 17: 3, 18: 19, 19: 55, 20: 41, 21: 16, 22: 61, 23: 71, 24: 46, 25: 39, 26: 24, 27: 39, 28: 46, 29: 56}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 9, 1: 48, 2: 37, 3: 57, 4: 54, 5: 22, 6: 25, 7: 45, 8: 33, 9: 13, 10: 18, 11: 30, 12: 51, 13: 39, 14: 60, 15: 31, 16: 14, 17: 23, 18: 15, 19: 6, 20: 23, 21: 14}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 9, 1: 63, 2: 24, 3: 36, 4: 72, 5: 50, 6: 36, 7: 14, 8: 14, 9: 36, 10: 79, 11: 80, 12: 82, 13: 53, 14: 37, 15: 6, 16: 20, 17: 77, 18: 57, 19: 69, 20: 18, 21: 60, 23: 17, 24: 30, 25: 66, 26: 82, 27: 3, 28: 34, 29: 40, 30: 49, 31: 37}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1': {0: 3, 1: 39, 2: 15, 3: 25, 4: 51, 5: 57, 6: 56, 7: 56, 8: 30, 9: 56, 10: 24, 11: 17, 12: 54, 13: 50, 14: 54, 15: 14, 16: 21, 17: 42, 18: 10, 19: 6, 20: 36, 21: 33, 22: 6, 23: 10, 24: 17, 25: 24, 26: 25, 27: 15}, 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O': {0: 6, 1: 85, 2: 32, 3: 14, 4: 32, 5: 85, 6: 6, 7: 88, 8: 98, 9: 10, 10: 95, 11: 103, 12: 70, 13: 20, 14: 26, 15: 100, 16: 63, 17: 57, 18: 48, 19: 57, 20: 63, 21: 15, 22: 108, 23: 46, 24: 24, 25: 27, 26: 94, 27: 60, 28: 51, 29: 41, 30: 51, 31: 60, 32: 76, 33: 103, 34: 101, 35: 54, 36: 47, 37: 60, 38: 60, 39: 71, 40: 37, 41: 28, 42: 10, 43: 60, 44: 93, 45: 92}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {1: 39, 2: 19, 3: 26, 4: 42, 5: 14, 6: 26, 7: 16, 8: 45, 9: 18, 10: 29, 11: 11, 12: 36, 13: 5, 14: 20, 15: 14, 16: 20, 17: 5, 18: 26, 19: 19}, 'Clc1ccccc1CN1CCc2sccc2C1': {1: 44, 2: 30, 3: 23, 4: 27, 5: 36, 6: 48, 7: 13, 8: 19, 9: 6, 10: 18, 11: 39, 12: 12, 13: 15, 14: 26, 15: 43, 16: 9}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 9, 1: 41, 2: 34, 3: 25, 4: 30, 5: 29, 6: 16, 7: 5, 8: 17, 9: 4, 10: 38, 11: 12, 12: 27, 13: 28}, 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1': {0: 5, 1: 35, 2: 27, 3: 36, 4: 64, 5: 67, 6: 35, 7: 34, 8: 71, 9: 72, 10: 21, 11: 24, 12: 66, 13: 35, 14: 11, 15: 9, 16: 5, 17: 51, 18: 54, 19: 57, 20: 54, 21: 27, 22: 65, 24: 44, 25: 21, 26: 39}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 10, 1: 30, 2: 27, 3: 33, 4: 12, 5: 24, 6: 7, 7: 39, 8: 36, 10: 10, 11: 6, 12: 10, 13: 36, 15: 21, 16: 18}, 'NC(=O)c1nc(F)cnc1O': {0: 9, 1: 24, 2: 20, 3: 27, 4: 8, 5: 18, 7: 10, 8: 3, 9: 21, 10: 15}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 8, 1: 42, 2: 8, 3: 24, 4: 47, 5: 32, 6: 48, 7: 16, 8: 4, 9: 15, 10: 21, 11: 49, 12: 11, 13: 45, 14: 45, 15: 25, 16: 39, 17: 39, 18: 24, 19: 18}, 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O': {0: 6, 1: 4, 2: 13, 3: 38, 4: 13, 5: 28, 6: 25, 7: 22, 8: 18, 9: 9, 10: 33, 12: 30, 13: 30, 14: 27}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 66, 1: 62, 2: 36, 3: 53, 4: 7, 5: 4, 6: 43, 7: 66, 8: 27, 9: 16, 10: 53, 11: 12, 12: 33, 13: 8, 14: 38, 15: 63, 16: 23, 17: 57, 18: 28, 19: 19, 20: 44, 22: 22, 23: 48}, 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 30, 1: 36, 2: 20, 3: 11, 4: 3, 5: 39, 6: 8, 7: 44, 8: 43, 9: 19, 10: 15, 11: 33, 12: 27, 13: 24, 14: 24, 15: 15, 16: 19, 17: 8}, 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1': {0: 41, 1: 41, 2: 37, 3: 10, 4: 13, 5: 50, 6: 45, 7: 56, 8: 18, 9: 10, 10: 27, 11: 46, 12: 49, 13: 16, 16: 5, 17: 54, 18: 49, 19: 21, 20: 15, 21: 38, 22: 35, 23: 30, 24: 30, 25: 15, 26: 21}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: 68, 7: 63, 8: 76, 9: 24, 10: 18, 11: 18, 12: 76, 13: 24, 14: 59, 15: 49, 16: 64, 17: 64, 18: 30, 19: 56, 20: 68, 21: 63, 22: 53, 23: 68, 24: 66, 25: 66, 26: 68, 27: 7, 28: 45, 29: 12, 30: 4, 31: 36, 32: 7, 33: 36, 34: 12, 35: 39, 36: 15, 37: 42, 38: 27, 39: 33, 40: 21, 41: 73, 42: 73, 43: 21, 44: 33, 45: 27, 46: 66, 47: 68, 48: 7, 49: 45, 50: 12, 51: 4, 52: 36, 53: 7, 54: 36, 55: 12, 56: 39, 57: 15, 58: 42, 59: 66, 60: 53, 61: 68}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19, 7: 17, 8: 8, 9: 17, 10: 19, 11: 45, 12: 22, 13: 36, 15: 11, 16: 20, 17: 39, 18: 27}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: 36, 8: 22, 9: 48, 10: 51, 11: 45, 12: 19, 13: 17, 14: 8, 15: 17, 16: 19, 17: 8, 18: 3, 19: 39}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 18, 8: 21, 9: 3, 10: 12, 11: 9, 12: 27}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 23, 7: 12, 8: 16, 9: 26, 10: 11, 11: 54, 12: 39, 13: 31, 14: 24, 15: 31, 16: 39, 17: 57, 18: 42, 19: 27, 20: 48, 22: 27, 23: 42, 24: 16, 25: 12}}

In [28]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()

,substrates,true_sites,gnn_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ..."
...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,..."