In [16]:
import pandas as pd
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/GNN-SOM-master/123_site_from_smiles.csv')
substrates = df['substrate'].to_list()

In [17]:
from rdkit import Chem

In [18]:
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [19]:
i = 1
filepath = f'SMARTCYP_results ({i}).csv'
df_part = pd.read_csv(filepath)
df_part

,Unnamed: 0,Molecule_Name,Molecule_Number,Atom_Number,Atom_Name,Atom,Span2end,Span2end_N_Correction,Span2end_CO_Correction,COO-Dist,...,Reactivity,Energy,3A4 Score,2D6 Score,2C9 Score,3A4 Ranking,2D6 Ranking,2C9 Ranking,N_ox,Similarity
0,0,Smiles,0,0,C,C.1,0,0.00,0.00,0,...,75.9,75.9,65.605338,73.605338,73.605338,3,2,2,0.0,1.000000
1,1,Smiles,0,1,C,C.2,1,6.70,5.90,0,...,999.0,999.0,991.500852,1005.400852,1004.600852,14,14,14,0.0,0.000000
2,2,Smiles,0,2,O,O.3,0,0.00,0.00,0,...,999.0,999.0,991.000000,999.000000,999.000000,13,13,13,0.0,1.000000
3,3,Smiles,0,3,N,N.4,2,13.40,11.80,0,...,89.6,89.6,82.614999,102.414999,100.814999,11,9,9,0.0,0.333333
4,4,Smiles,0,4,C,C.5,3,20.10,17.70,0,...,999.0,999.0,993.215443,1018.915443,1016.515443,18,18,18,0.0,0.000000
5,5,Smiles,0,5,C,C.6,2,13.40,11.80,0,...,80.8,80.8,73.352875,93.152875,91.552875,5,7,7,0.0,0.666667
6,6,Smiles,0,6,C,C.7,3,20.10,17.70,0,...,86.3,86.3,79.777699,105.477699,103.077699,10,10,10,0.0,1.000000
7,7,Smiles,0,7,C,C.8,4,26.84,23.64,0,...,999.0,999.0,994.035409,1025.675409,1022.475409,20,20,20,0.0,0.000000
8,8,Smiles,0,8,C,C.9,5,26.85,23.65,0,...,999.0,999.0,994.919983,1025.769983,1022.569983,22,22,22,0.0,0.000000
9,9,Smiles,0,9,C,C.10,4,26.84,23.64,0,...,80.8,80.8,75.339120,106.979120,103.779120,7,11,11,0.0,0.333333
10,10,Smiles,0,10,C,C.11,4,26.84,23.64,0,...,999.0,999.0,994.125597,1025.765597,1022.565597,21,21,21,0.0,0.000000
11,11,Smiles,0,11,C,C.12,3,20.10,17.70,0,...,999.0,999.0,993.315016,1019.015016,1016.615016,19,19,19,0.0,0.000000
12,12,Smiles,0,12,C,C.13,2,13.40,11.80,0,...,80.8,80.8,73.398100,93.198100,91.598100,6,8,8,0.0,0.666667
13,13,Smiles,0,13,C,C.14,1,6.70,5.90,0,...,84.1,84.1,75.593042,89.493042,88.693042,8,5,5,0.0,1.000000
14,14,Smiles,0,14,C,C.15,0,0.00,0.00,0,...,80.8,80.8,71.427062,79.427062,79.427062,4,3,4,0.0,1.000000
15,15,Smiles,0,15,C,C.16,1,6.70,5.90,0,...,84.1,84.1,75.771167,89.671167,88.871167,9,6,6,0.0,1.000000
16,16,Smiles,0,16,C,C.17,2,13.40,11.80,0,...,999.0,999.0,992.440265,1012.240265,1010.640265,17,17,17,0.0,0.000000
17,17,Smiles,0,18,N,N.19,3,20.10,17.70,0,...,61.9,61.9,55.814024,81.514024,79.114024,2,4,3,0.0,0.333333
18,18,Smiles,0,19,C,C.20,2,13.40,11.80,0,...,48.5,48.5,40.877832,60.677832,59.077832,1,1,1,0.0,0.333333
19,19,Smiles,0,20,C,C.21,2,13.40,11.80,0,...,999.0,999.0,992.321719,1012.121719,1010.521719,16,16,16,0.0,0.000000
20,20,Smiles,0,21,O,O.22,1,6.70,5.90,0,...,999.0,999.0,991.800000,1005.700000,1004.900000,15,15,15,0.0,0.333333
21,21,Smiles,0,22,N,N.23,3,20.10,17.70,0,...,89.6,89.6,83.385376,109.085376,106.685376,12,12,12,0.0,0.333333

In [20]:
df_new = pd.DataFrame(columns=['substrates','enzyme','scores'])
from rdkit import Chem

subs_new = []
enzymes_new = []
scores_new = []

for i in range(len(substrates)):
    sub = substrates[i]
    sub = canonicalsmiles(sub)
    if i == 0:
        filepath = f'SMARTCYP_results.csv'
    else:
        filepath = f'SMARTCYP_results ({i}).csv'

    df_part = pd.read_csv(filepath)

    # 解析 SMILES
    molecule = Chem.MolFromSmiles(sub)
    # 获取原子数
    atom_count = molecule.GetNumAtoms()

    # try:
    atomidxs = df_part['Atom_Number'].to_list()
    # assert atom_count == max(atomidxs)+1

    ranks_3a4 = df_part['3A4 Ranking'].to_list()
    ranks_2d6 = df_part['2D6 Ranking'].to_list()
    ranks_2c9 = df_part['2C9 Ranking'].to_list()
    dict_atomidx2rank3a4 = dict(zip(atomidxs,ranks_3a4))
    dict_atomidx2rank2d6 = dict(zip(atomidxs,ranks_2d6))
    dict_atomidx2rank2c9 = dict(zip(atomidxs,ranks_2c9))

    subs_new.append(sub)
    subs_new.append(sub)
    subs_new.append(sub)

    enzymes_new.append('3A4')
    enzymes_new.append('2D6')
    enzymes_new.append('2C9')

    scores_new.append(dict_atomidx2rank3a4)
    scores_new.append(dict_atomidx2rank2d6)
    scores_new.append(dict_atomidx2rank2c9)

    # except:
    #     print(sub)
    #     print(len(df_part))
    #     print(atom_count)

df_new['substrates'] = subs_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = scores_new

df_new

,substrates,enzyme,scores
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,3A4,"{0: 3, 1: 21, 2: 10, 3: 1, 4: 20, 5: 17, 6: 16..."
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2D6,"{0: 6, 1: 21, 2: 13, 3: 3, 4: 20, 5: 17, 6: 16..."
2,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2C9,"{0: 5, 1: 18, 2: 9, 3: 2, 4: 17, 5: 15, 6: 14,..."
3,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,3A4,"{0: 3, 1: 14, 2: 13, 3: 11, 4: 18, 5: 5, 6: 10..."
4,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,2D6,"{0: 2, 1: 14, 2: 13, 3: 9, 4: 18, 5: 7, 6: 10,..."
...,...,...,...
364,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2D6,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 4, 6: 19..."
365,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2C9,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 3, 6: 19..."
366,c1cnc(N2CCNCC2)nc1,3A4,"{0: 6, 1: 7, 2: 5, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."
367,c1cnc(N2CCNCC2)nc1,2D6,"{0: 1, 1: 5, 2: 4, 3: 8, 4: 7, 5: 2, 6: 6, 7: ..."
368,c1cnc(N2CCNCC2)nc1,2C9,"{0: 5, 1: 7, 2: 6, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."

In [21]:
df_new.to_pickle('smartcyp_results_drugbank.pickle')

In [22]:
df = pd.read_pickle('smartcyp_results_drugbank.pickle')
df

,substrates,enzyme,scores
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,3A4,"{0: 3, 1: 21, 2: 10, 3: 1, 4: 20, 5: 17, 6: 16..."
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2D6,"{0: 6, 1: 21, 2: 13, 3: 3, 4: 20, 5: 17, 6: 16..."
2,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2C9,"{0: 5, 1: 18, 2: 9, 3: 2, 4: 17, 5: 15, 6: 14,..."
3,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,3A4,"{0: 3, 1: 14, 2: 13, 3: 11, 4: 18, 5: 5, 6: 10..."
4,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,2D6,"{0: 2, 1: 14, 2: 13, 3: 9, 4: 18, 5: 7, 6: 10,..."
...,...,...,...
364,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2D6,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 4, 6: 19..."
365,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2C9,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 3, 6: 19..."
366,c1cnc(N2CCNCC2)nc1,3A4,"{0: 6, 1: 7, 2: 5, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."
367,c1cnc(N2CCNCC2)nc1,2D6,"{0: 1, 1: 5, 2: 4, 3: 8, 4: 7, 5: 2, 6: 6, 7: ..."
368,c1cnc(N2CCNCC2)nc1,2C9,"{0: 5, 1: 7, 2: 6, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."

In [23]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O': {0: 14, 1: 60, 2: 32, 3: 6, 4: 57, 5: 49, 6: 46, 7: 26, 8: 12, 9: 6, 10: 15, 11: 52, 12: 29, 13: 29, 14: 32, 15: 30, 16: 33, 17: 59, 18: 12, 19: 26, 20: 50, 21: 50, 22: 47}, 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 7, 1: 42, 2: 39, 3: 29, 4: 54, 5: 19, 6: 30, 7: 60, 8: 66, 9: 29, 10: 63, 11: 57, 12: 22, 13: 18, 14: 11, 15: 21, 16: 51, 18: 9, 19: 3, 20: 48, 21: 45, 22: 36}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 4, 1: 49, 2: 45, 3: 34, 4: 58, 5: 23, 6: 34, 7: 21, 8: 76, 9: 96, 10: 75, 11: 84, 12: 93, 13: 30, 14: 27, 15: 27, 16: 78, 17: 81, 18: 86, 19: 81, 20: 16, 21: 61, 22: 29, 23: 13, 24: 50, 26: 16, 27: 54, 29: 78, 30: 18, 31: 70, 32: 75, 33: 78, 34: 9, 35: 88, 36: 41}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 16, 1: 39, 2: 16, 3: 16, 4: 45, 5: 29, 6: 71, 7: 57, 8: 26, 9: 26, 10: 26, 11: 69, 12: 33, 13: 67, 14: 72, 15: 66, 16: 36, 17: 17, 18: 42, 19: 17, 20: 11, 21: 6, 22: 18, 23: 48, 24: 60, 25: 54, 26: 22, 27: 51, 28: 3}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 22, 1: 62, 2: 22, 3: 22, 4: 70, 5: 26, 6: 78, 7: 45, 8: 83, 9: 88, 10: 48, 11: 87, 12: 41, 13: 33, 14: 91, 15: 89, 16: 27, 17: 48, 18: 80, 19: 45, 20: 18, 21: 87, 22: 37, 23: 85, 24: 87, 25: 29, 26: 16, 27: 19, 28: 5, 29: 16, 30: 71, 31: 16, 32: 5, 33: 34, 34: 19, 35: 83, 36: 33, 37: 41, 38: 42, 39: 74}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 19, 1: 47, 2: 19, 3: 13, 4: 54, 5: 51, 6: 38, 7: 29, 8: 33, 9: 34, 10: 9, 11: 13, 12: 18, 13: 6, 14: 20, 15: 57, 16: 22, 17: 19, 18: 46, 19: 42, 20: 19, 21: 22, 22: 6, 23: 18, 24: 54, 25: 51, 26: 13}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 21, 1: 45, 2: 21, 3: 17, 4: 53, 5: 48, 6: 41, 7: 30, 8: 34, 9: 35, 10: 11, 11: 14, 12: 19, 13: 6, 14: 23, 15: 52, 16: 17, 17: 29, 18: 18, 19: 29, 20: 17, 21: 6, 22: 19, 23: 53, 24: 48, 25: 17}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 25, 1: 51, 2: 25, 3: 20, 4: 59, 5: 54, 6: 44, 7: 34, 8: 36, 9: 38, 10: 12, 11: 15, 12: 21, 13: 7, 14: 25, 15: 59, 16: 20, 17: 32, 18: 21, 19: 32, 20: 20, 21: 7, 22: 21, 23: 62, 24: 54, 25: 10, 26: 48}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O': {0: 5, 1: 47, 2: 55, 3: 28, 4: 28, 5: 58, 6: 13, 7: 29, 8: 27, 9: 29, 10: 57, 11: 12, 12: 23, 13: 48, 14: 48, 15: 45, 16: 50, 17: 24, 18: 24, 19: 12, 20: 4, 21: 44, 22: 39}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 27, 1: 17, 2: 69, 3: 66, 4: 48, 5: 29, 6: 32, 7: 9, 8: 12, 9: 82, 10: 41, 11: 54, 12: 38, 13: 76, 14: 79, 15: 6, 16: 21, 17: 81, 18: 51, 19: 21, 20: 60, 21: 57, 22: 72, 23: 63, 27: 45, 28: 3, 29: 24, 30: 35}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 29, 1: 20, 2: 66, 3: 60, 4: 49, 5: 29, 6: 35, 7: 10, 8: 14, 9: 79, 10: 44, 11: 55, 12: 41, 13: 76, 14: 82, 15: 9, 16: 22, 17: 81, 18: 56, 19: 32, 20: 63, 21: 60, 22: 7, 23: 72, 24: 69, 28: 50, 29: 5, 30: 25, 31: 38}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 49, 1: 34, 2: 50, 3: 63, 4: 80, 5: 75, 6: 28, 7: 84, 8: 108, 9: 73, 10: 24, 11: 111, 12: 37, 13: 15, 14: 19, 15: 38, 16: 109, 17: 13, 18: 52, 19: 105, 20: 117, 21: 26, 22: 29, 23: 23, 24: 109, 25: 106, 26: 33, 27: 72, 28: 3, 29: 57, 30: 21, 31: 63, 32: 103, 33: 60, 34: 47, 35: 87, 37: 50, 38: 90, 40: 113, 41: 52, 42: 13, 43: 19, 44: 15, 45: 24, 46: 73, 47: 104, 48: 103}, 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 31, 1: 13, 2: 24, 3: 31, 4: 26, 5: 59, 6: 60, 7: 42, 8: 4, 9: 15, 10: 20, 11: 64, 12: 9, 13: 59, 14: 64, 15: 12, 16: 41, 17: 40, 18: 40, 19: 40, 20: 37, 21: 21, 22: 59, 23: 58, 24: 56}, 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 31, 1: 10, 2: 23, 3: 28, 4: 8, 5: 59, 6: 60, 7: 11, 8: 39, 9: 42, 10: 20, 11: 64, 12: 8, 13: 59, 14: 64, 15: 15, 16: 39, 17: 38, 18: 38, 19: 38, 20: 35, 21: 21, 22: 59, 23: 58, 24: 56}, 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F': {0: 21, 1: 10, 2: 18, 3: 22, 4: 27, 5: 59, 6: 56, 7: 59, 8: 36, 9: 63, 10: 31, 11: 59, 12: 61, 13: 62, 14: 19, 15: 48, 16: 4, 17: 26, 18: 7, 19: 42, 20: 13, 21: 45, 22: 39, 23: 60}, 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 30, 1: 12, 2: 22, 3: 36, 4: 42, 5: 16, 6: 63, 7: 23, 8: 26, 9: 29, 10: 15, 11: 66, 12: 6, 13: 63, 14: 66, 15: 9, 16: 48, 17: 47, 18: 46, 19: 45, 20: 40, 21: 21, 22: 63, 23: 62, 24: 60}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 25, 1: 16, 2: 10, 3: 66, 4: 36, 5: 60, 6: 7, 7: 63, 8: 72, 9: 69, 10: 28, 11: 77, 12: 86, 13: 47, 14: 87, 15: 90, 16: 85, 17: 85, 18: 57, 19: 41, 20: 18, 21: 20, 22: 8, 23: 41, 24: 18, 25: 41, 26: 44, 27: 38, 28: 80, 29: 77, 30: 19, 31: 38, 32: 31, 33: 46}, 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN': {0: 15, 1: 9, 2: 28, 3: 9, 4: 15, 5: 36, 6: 33, 7: 42, 8: 39, 9: 25, 10: 18, 11: 11, 12: 18, 13: 25, 14: 20, 15: 23, 16: 6, 17: 10}, 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 29, 1: 5, 2: 18, 3: 11, 4: 30, 5: 39, 6: 24, 7: 21, 8: 10, 9: 45, 10: 7, 11: 60, 12: 56, 13: 56, 14: 61, 15: 57, 16: 29, 17: 51, 18: 47, 19: 25, 20: 43, 21: 43, 22: 25}, 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1': {0: 31, 1: 18, 2: 73, 3: 30, 4: 36, 5: 11, 6: 48, 7: 15, 8: 79, 9: 73, 10: 66, 11: 14, 12: 26, 13: 58, 14: 13, 15: 62, 16: 70, 17: 16, 18: 6, 19: 53, 20: 21, 21: 81, 22: 45, 23: 39, 24: 71, 25: 64, 26: 64, 27: 60, 28: 39, 29: 45, 30: 39}, 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 28, 1: 12, 2: 63, 3: 66, 4: 26, 5: 19, 6: 56, 7: 3, 8: 32, 9: 71, 10: 76, 11: 27, 12: 12, 13: 25, 14: 16, 15: 45, 16: 33, 17: 78, 18: 43, 19: 37, 20: 64, 21: 59, 22: 12, 23: 75, 24: 70, 25: 39, 26: 61, 27: 61, 28: 50}, 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C': {0: 21, 1: 18, 2: 15, 3: 39, 4: 12, 5: 36, 6: 33, 7: 9, 8: 36, 9: 33, 10: 12, 11: 23, 12: 26, 13: 7, 14: 30, 15: 4, 16: 4}, 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C': {0: 27, 1: 22, 2: 18, 3: 45, 4: 13, 5: 20, 6: 9, 7: 42, 8: 39, 9: 18, 10: 28, 11: 32, 12: 7, 13: 36, 14: 4, 15: 4}, 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C': {0: 24, 1: 18, 2: 14, 3: 39, 4: 36, 5: 42, 6: 22, 7: 28, 8: 11, 9: 45, 10: 11, 11: 28, 12: 3, 13: 33, 14: 6}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 33, 2: 3, 3: 7, 4: 17, 5: 23, 6: 58, 7: 53, 8: 25, 9: 17, 10: 42, 12: 17, 13: 25, 14: 59, 15: 8, 16: 48, 17: 20, 18: 45, 19: 39, 20: 36, 21: 17, 22: 28, 23: 52}, 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 33, 2: 3, 3: 7, 4: 17, 5: 23, 6: 58, 7: 53, 8: 25, 9: 17, 10: 42, 12: 17, 13: 25, 14: 59, 15: 8, 16: 48, 17: 20, 18: 45, 19: 39, 20: 36, 21: 17, 22: 28, 23: 52}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 8, 1: 42, 2: 8, 3: 15, 4: 25, 5: 57, 6: 16, 7: 46, 8: 52, 9: 28, 10: 47, 11: 3, 12: 56, 13: 20, 14: 36, 15: 11, 16: 27, 17: 18, 18: 31, 19: 35, 20: 57}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 5, 1: 42, 2: 5, 3: 13, 4: 23, 5: 56, 6: 13, 7: 45, 8: 49, 9: 26, 10: 25, 11: 51, 12: 17, 13: 36, 14: 8, 15: 26, 16: 16, 17: 30, 18: 35, 19: 54}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 3, 1: 21, 2: 36, 3: 30, 4: 8, 5: 48, 6: 45, 7: 27, 8: 54, 9: 23, 10: 11, 11: 33, 12: 30, 13: 11, 14: 23, 15: 51, 16: 18, 17: 39, 19: 8, 20: 16, 21: 42}, 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1': {0: 8, 1: 48, 2: 16, 3: 32, 4: 24, 5: 44, 6: 72, 7: 71, 8: 38, 9: 66, 10: 32, 11: 24, 12: 60, 13: 54, 14: 51, 15: 24, 16: 32, 17: 35, 18: 19, 19: 69, 20: 38, 21: 59, 22: 16, 23: 14, 24: 9, 25: 11, 26: 59, 27: 65}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 3, 1: 16, 2: 49, 3: 46, 4: 54, 5: 16, 6: 62, 7: 71, 8: 68, 9: 19, 10: 31, 11: 72, 12: 37, 13: 68, 14: 73, 15: 37, 16: 68, 17: 24, 18: 17, 19: 45, 21: 56, 22: 48, 26: 27, 27: 31, 28: 19, 29: 12, 30: 28, 31: 6}, 'CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@](O)(c2cc(F)ccc2F)[C@@H](C)c2nc(-c3ccc(C#N)cc3)cs2)c1': {0: 4, 1: 23, 2: 13, 3: 112, 4: 109, 5: 123, 6: 42, 7: 121, 8: 68, 9: 60, 10: 68, 11: 38, 12: 121, 13: 73, 14: 33, 15: 115, 16: 123, 17: 133, 18: 19, 19: 61, 20: 81, 21: 39, 22: 78, 23: 16, 24: 136, 25: 127, 26: 130, 27: 52, 28: 104, 30: 46, 31: 49, 32: 110, 34: 13, 35: 62, 36: 119, 37: 74, 38: 104, 39: 109, 40: 42, 41: 32, 42: 93, 43: 90, 44: 87, 45: 32, 46: 42, 47: 26, 48: 25, 49: 72, 50: 9}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 13, 2: 7, 3: 20, 4: 26, 5: 58, 6: 53, 7: 28, 8: 19, 9: 42, 11: 19, 12: 28, 13: 59, 14: 10, 15: 48, 16: 22, 17: 45, 18: 39, 19: 36, 20: 19, 21: 31, 22: 52}, 'CNCCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 13, 2: 7, 3: 20, 4: 26, 5: 58, 6: 53, 7: 28, 8: 19, 9: 42, 11: 19, 12: 28, 13: 59, 14: 10, 15: 48, 16: 22, 17: 45, 18: 39, 19: 36, 20: 19, 21: 31, 22: 52}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 21, 1: 88, 2: 88, 3: 85, 4: 86, 5: 29, 6: 40, 7: 10, 8: 9, 9: 4, 10: 16, 11: 57, 12: 16, 13: 4, 14: 38, 15: 40, 16: 77, 17: 84, 18: 43, 19: 71, 20: 53, 21: 71, 22: 77, 23: 65, 24: 50, 25: 32, 26: 60, 27: 8, 28: 32, 29: 50, 30: 50, 31: 30, 32: 16, 33: 24, 34: 66}, 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1': {0: 14, 1: 60, 2: 67, 3: 22, 4: 52, 5: 12, 6: 56, 7: 47, 8: 6, 9: 15, 10: 64, 11: 73, 12: 13, 13: 42, 14: 9, 15: 31, 16: 26, 17: 67, 18: 34, 19: 18, 20: 75, 21: 39, 22: 34, 23: 65, 24: 58, 25: 58, 26: 54, 27: 34, 28: 39}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 13, 1: 58, 2: 61, 3: 29, 4: 78, 5: 31, 6: 86, 7: 75, 8: 68, 9: 60, 10: 50, 11: 38, 12: 76, 13: 43, 14: 89, 15: 92, 16: 29, 17: 42, 18: 16, 19: 28, 20: 17, 21: 9, 22: 12, 23: 4, 24: 9, 25: 17, 26: 86, 27: 91, 28: 19, 29: 44, 30: 79, 31: 67, 33: 35, 34: 55}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 8, 1: 63, 2: 67, 3: 16, 4: 67, 5: 63, 6: 8, 7: 34, 8: 79, 9: 58, 10: 32, 11: 14, 12: 24, 13: 8, 14: 42, 15: 42, 16: 84, 17: 33, 18: 46, 19: 75, 20: 34, 21: 51, 22: 74, 23: 68, 24: 28, 25: 41, 26: 11, 27: 37, 28: 24, 29: 39, 30: 78, 31: 50, 32: 34}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1[C@@H](NC(C)=O)CC2': {0: 6, 1: 42, 2: 51, 3: 24, 4: 69, 5: 73, 6: 66, 7: 63, 8: 12, 9: 60, 10: 57, 11: 9, 12: 76, 13: 38, 14: 30, 15: 48, 16: 42, 17: 3, 18: 54, 19: 42, 20: 33, 21: 76, 22: 19, 23: 37, 24: 45, 25: 17, 26: 42, 27: 27, 28: 18}, 'COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2': {0: 6, 1: 48, 2: 51, 3: 34, 4: 63, 5: 66, 6: 40, 7: 57, 8: 54, 9: 12, 10: 14, 11: 38, 12: 22, 13: 60, 14: 33, 15: 25, 16: 18, 17: 26, 18: 26, 19: 10, 20: 45, 21: 9, 22: 28}, 'COc1ccc(C[C@@H](C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 9, 1: 52, 2: 57, 3: 32, 4: 38, 5: 69, 6: 27, 7: 13, 8: 39, 9: 22, 10: 9, 11: 23, 12: 65, 13: 60, 14: 25, 15: 16, 16: 11, 17: 19, 18: 54, 19: 49, 20: 44, 21: 66, 22: 63, 23: 33, 24: 54, 25: 54}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 4, 1: 42, 2: 45, 3: 24, 4: 26, 5: 56, 6: 36, 7: 65, 8: 9, 9: 68, 10: 22, 11: 64, 12: 29, 13: 33, 14: 39, 15: 10, 16: 48, 17: 42, 18: 7, 19: 51, 20: 15, 21: 57, 22: 59, 23: 19}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)CC3': {0: 8, 1: 37, 2: 40, 3: 15, 4: 24, 5: 23, 6: 62, 7: 51, 8: 62, 9: 51, 10: 72, 11: 74, 12: 3, 13: 66, 14: 67, 15: 78, 16: 3, 17: 72, 18: 62, 19: 67, 20: 16, 21: 46, 22: 41, 23: 38, 24: 33, 25: 7, 26: 30, 27: 24, 28: 15}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 16, 1: 60, 2: 68, 3: 35, 4: 33, 5: 34, 6: 68, 7: 80, 8: 87, 9: 79, 10: 96, 11: 98, 12: 7, 13: 101, 14: 96, 15: 96, 16: 4, 17: 92, 18: 75, 19: 67, 20: 34, 21: 87, 22: 73, 23: 70, 24: 63, 25: 17, 26: 56, 27: 47, 28: 36, 29: 94, 30: 22, 31: 40, 32: 13, 33: 23, 34: 25, 35: 68, 36: 29, 37: 44, 38: 83}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3': {0: 7, 1: 39, 2: 42, 3: 18, 4: 27, 5: 26, 6: 62, 7: 51, 8: 62, 9: 51, 10: 72, 11: 74, 12: 3, 13: 66, 14: 67, 15: 78, 16: 3, 17: 72, 18: 62, 19: 67, 20: 19, 21: 46, 22: 41, 23: 12, 24: 36, 25: 8, 26: 33, 27: 27, 28: 18}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 15, 1: 62, 2: 70, 3: 38, 4: 35, 5: 36, 6: 70, 7: 82, 8: 87, 9: 79, 10: 96, 11: 98, 12: 7, 13: 101, 14: 96, 15: 96, 16: 4, 17: 92, 18: 77, 19: 69, 20: 37, 21: 87, 22: 73, 23: 27, 24: 66, 25: 19, 26: 59, 27: 50, 28: 39, 29: 94, 30: 22, 31: 43, 32: 14, 33: 24, 34: 26, 35: 70, 36: 30, 37: 47, 38: 83}, 'COc1nc(N)nc2[nH]cnc12': {0: 9, 1: 33, 2: 36, 3: 15, 4: 27, 5: 3, 6: 12, 7: 24, 8: 30, 9: 18, 10: 6, 11: 21}, 'COc1nc(N)nc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O': {0: 6, 1: 39, 2: 45, 3: 20, 4: 42, 5: 3, 6: 27, 7: 57, 8: 51, 9: 30, 10: 16, 11: 33, 12: 23, 13: 54, 14: 13, 15: 10, 16: 36, 17: 13, 18: 39, 19: 17, 20: 48}, 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12': {0: 7, 1: 77, 2: 81, 3: 29, 4: 66, 5: 15, 6: 17, 7: 63, 9: 34, 10: 72, 11: 56, 12: 92, 13: 26, 14: 86, 15: 53, 16: 48, 17: 39, 18: 48, 19: 53, 20: 93, 21: 87, 22: 42, 23: 17, 24: 60, 25: 7, 26: 7, 27: 92, 28: 46, 29: 33, 30: 27, 31: 69, 32: 27, 33: 14, 34: 24, 35: 36, 36: 76}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 8, 1: 39, 2: 48, 3: 29, 4: 36, 5: 60, 6: 22, 7: 7, 8: 20, 9: 42, 10: 20, 11: 28, 12: 17, 13: 45, 14: 5, 15: 54, 16: 10, 17: 32, 18: 57, 19: 51}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 6, 1: 45, 2: 42, 3: 42, 4: 48, 5: 28, 6: 30, 7: 68, 8: 64, 9: 73, 10: 39, 11: 69, 12: 23, 13: 57, 14: 3, 15: 54, 17: 69, 18: 51, 19: 25, 20: 20, 21: 13, 22: 24, 23: 11, 24: 20, 25: 62, 27: 31}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 3, 1: 45, 2: 39, 3: 39, 4: 48, 5: 18, 6: 23, 7: 64, 8: 57, 9: 70, 10: 36, 11: 66, 12: 22, 13: 32, 14: 56, 16: 67, 17: 53, 18: 25, 19: 10, 20: 42, 21: 39, 22: 7, 23: 10, 24: 27, 25: 59, 27: 21}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 3, 1: 45, 2: 42, 3: 42, 4: 48, 5: 21, 6: 23, 7: 67, 8: 61, 9: 70, 10: 39, 11: 64, 12: 22, 13: 33, 14: 54, 16: 64, 17: 51, 18: 23, 19: 18, 20: 10, 21: 22, 22: 8, 23: 27, 24: 61, 26: 24}, 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12': {0: 27, 1: 12, 2: 57, 3: 24, 4: 66, 5: 62, 6: 48, 7: 81, 8: 75, 9: 71, 10: 71, 11: 85, 12: 9, 13: 27, 14: 8, 15: 25, 16: 12, 17: 87, 18: 88, 19: 54, 20: 79, 21: 36, 22: 36, 23: 16, 24: 70, 25: 61, 26: 57, 27: 57, 28: 39, 29: 43, 30: 22, 31: 45, 32: 30}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)O': {0: 48, 1: 35, 2: 30, 3: 40, 4: 34, 5: 27, 6: 12, 8: 68, 9: 28, 10: 57, 11: 54, 12: 25, 13: 6, 14: 80, 15: 39, 16: 88, 18: 18, 19: 85, 20: 35, 21: 94, 22: 51, 23: 89, 24: 83, 25: 73, 26: 67, 27: 64, 28: 17, 29: 11, 30: 3, 31: 61, 32: 84, 33: 83, 34: 78}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)SCF': {0: 54, 1: 38, 2: 33, 3: 46, 4: 42, 5: 33, 6: 19, 8: 78, 9: 36, 10: 63, 11: 60, 12: 33, 13: 11, 14: 90, 15: 51, 16: 99, 18: 22, 19: 93, 20: 39, 21: 102, 22: 57, 23: 96, 24: 87, 25: 75, 26: 72, 27: 69, 28: 20, 29: 17, 30: 5, 31: 66, 32: 84, 33: 81, 34: 4, 35: 10}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 56, 1: 47, 2: 34, 3: 21, 4: 71, 5: 70, 6: 67, 7: 46, 8: 34, 9: 33, 10: 44, 11: 10, 12: 70, 13: 70, 14: 6, 15: 25, 16: 17, 17: 4, 18: 63, 19: 14, 20: 20, 21: 73, 22: 51, 23: 36, 24: 36, 25: 39, 26: 78, 27: 57}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 59, 1: 49, 2: 33, 3: 21, 4: 73, 5: 72, 6: 69, 7: 48, 8: 34, 9: 33, 10: 47, 11: 41, 12: 9, 13: 71, 14: 27, 15: 22, 16: 13, 17: 3, 18: 66, 19: 10, 20: 17, 21: 74, 22: 54, 23: 36, 24: 36, 25: 41, 26: 78, 27: 60}, 'C[C@H](N)Cc1ccc(O)cc1': {0: 14, 1: 3, 2: 6, 3: 10, 4: 27, 5: 18, 6: 12, 7: 24, 8: 21, 9: 12, 10: 18}, 'C[C@H](N)Cc1ccccc1': {0: 18, 1: 3, 2: 7, 3: 11, 4: 24, 5: 20, 6: 15, 7: 10, 8: 15, 9: 20}, 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O': {0: 18, 1: 6, 2: 39, 3: 16, 4: 46, 5: 24, 6: 35, 8: 32, 9: 3, 10: 20, 11: 42, 12: 41, 13: 12, 14: 32, 15: 9, 16: 27}, 'C[C@H]1[C@@H](O)O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@]24OO3': {0: 32, 1: 21, 2: 9, 3: 15, 4: 32, 5: 24, 6: 37, 7: 3, 8: 42, 9: 51, 10: 6, 11: 51, 12: 45, 13: 29, 14: 12, 15: 18, 16: 35, 17: 54, 18: 51, 19: 48}, 'C[C@]12CC[C@H](O)CC1=CC[C@@H]1[C@@H]2CC[C@]2(C)C(c3cccnc3)=CC[C@@H]12': {0: 58, 1: 78, 2: 37, 3: 40, 4: 44, 5: 43, 6: 24, 7: 21, 8: 66, 9: 10, 10: 5, 11: 63, 12: 20, 13: 31, 14: 75, 15: 55, 16: 46, 17: 12, 18: 5, 19: 72, 20: 69, 21: 40, 22: 33, 23: 35, 24: 15, 25: 56}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 18, 1: 69, 2: 82, 3: 81, 4: 79, 5: 24, 6: 59, 7: 30, 8: 19, 9: 43, 11: 22, 12: 49, 14: 73, 15: 24, 16: 68, 17: 70, 18: 76, 19: 76, 20: 84, 21: 32, 22: 23, 23: 23, 24: 69, 25: 68, 26: 87, 27: 71, 28: 8, 29: 20, 30: 44, 31: 40, 32: 49, 33: 3, 34: 11}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1': {0: 19, 1: 77, 2: 73, 3: 62, 4: 8, 5: 55, 9: 29, 10: 45, 11: 37, 12: 82, 13: 22, 14: 4, 15: 88, 16: 80, 17: 48, 18: 73, 19: 30, 20: 41, 21: 83, 22: 87, 23: 12, 24: 77, 25: 24, 26: 68, 27: 67, 28: 64, 29: 14, 30: 61, 31: 23, 32: 67, 33: 24, 34: 68, 35: 28, 36: 76, 37: 73}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@+](O)c1nc2c(OS(=O)(=O)O)cccc2[nH]1': {0: 12, 1: 58, 2: 54, 3: 44, 4: 4, 5: 37, 9: 19, 10: 27, 11: 21, 12: 63, 13: 5, 14: 56, 15: 66, 16: 63, 17: 30, 18: 61, 19: 52, 20: 53, 21: 48, 22: 42, 23: 42, 24: 42, 25: 19, 26: 15, 27: 13, 28: 57, 29: 56}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1': {0: 15, 1: 63, 2: 59, 3: 52, 4: 6, 5: 42, 9: 25, 10: 30, 11: 26, 12: 67, 13: 19, 14: 3, 15: 68, 16: 58, 17: 33, 18: 45, 19: 16, 20: 15, 21: 39, 22: 36, 23: 10, 24: 48, 25: 53}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1': {0: 17, 1: 58, 2: 54, 3: 48, 4: 10, 5: 39, 9: 27, 10: 35, 11: 30, 12: 61, 13: 21, 14: 4, 15: 61, 16: 51, 17: 34, 18: 42, 19: 19, 20: 18, 21: 9, 22: 10, 23: 42, 24: 45}, 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1': {0: 23, 1: 79, 2: 39, 3: 85, 4: 33, 5: 80, 6: 53, 7: 38, 8: 80, 9: 73, 10: 80, 11: 50, 12: 68, 13: 65, 14: 12, 15: 28, 16: 18, 17: 31, 18: 62, 20: 26, 21: 53, 22: 86, 23: 32, 24: 15, 25: 29, 26: 18, 27: 9, 28: 20, 29: 67, 30: 29, 31: 15, 32: 43}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2': {0: 4, 1: 42, 2: 30, 3: 10, 4: 48, 5: 39, 6: 54, 7: 33, 8: 17, 9: 51, 11: 32, 12: 60, 13: 63, 14: 57, 15: 27, 16: 23, 17: 13, 18: 26, 19: 45, 21: 14, 22: 5}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O': {0: 4, 1: 42, 2: 30, 3: 10, 4: 51, 5: 39, 6: 57, 7: 33, 8: 17, 9: 48, 11: 32, 12: 63, 13: 66, 14: 60, 15: 27, 16: 23, 17: 13, 18: 26, 19: 45, 21: 14, 22: 5, 23: 54}, 'Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2': {1: 42, 2: 10, 3: 27, 4: 45, 5: 51, 6: 24, 7: 35, 8: 57, 9: 22, 10: 8, 11: 17, 12: 13, 13: 17, 14: 8, 15: 54, 16: 32, 17: 13, 18: 21, 19: 33, 20: 48, 21: 18}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N(CC(=O)O)CC(=O)O)cc3)n2)cc1': {0: 42, 1: 46, 2: 5, 3: 31, 4: 59, 5: 53, 6: 64, 7: 23, 8: 26, 9: 71, 10: 70, 11: 32, 12: 38, 13: 16, 14: 62, 15: 13, 16: 67, 17: 35, 18: 13, 19: 69, 20: 18, 21: 4, 22: 52, 23: 47, 24: 47, 25: 4, 26: 52, 27: 47, 28: 47, 29: 13, 30: 35, 31: 19, 32: 26, 33: 23}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1': {0: 45, 1: 50, 2: 8, 3: 35, 4: 59, 5: 54, 6: 67, 7: 27, 8: 30, 9: 73, 10: 73, 11: 36, 12: 42, 13: 21, 14: 62, 15: 18, 16: 64, 17: 37, 18

In [30]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
smartcyp_results = [result_new[i] for i in substrates]
df_total['smartcyp_results'] = smartcyp_results
df_total

,substrates,true_sites,gnn_results,smartcyp_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6..."
...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2..."

In [31]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')