In [119]:
import pandas as pd

In [120]:
df = pd.read_pickle('gnnsom_results_drugbank.pickle')
df

,substrate,ec,score
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,"(1, 14)","{0: 0.00403987243771553, 1: 0.0116602797061204..."
1,CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2,"(1, 14)","{0: 0.11337683349847794, 1: 0.4291064441204071..."
2,CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=C...,"(1, 14)","{0: 0.1749592274427414, 1: 0.48370441794395447..."
3,CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=...,"(1, 14)","{0: 0.19561421871185303, 1: 0.083653524518013,..."
4,CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=C...,"(1, 14)","{0: 0.23840060830116272, 1: 0.2645083367824554..."
...,...,...,...
118,OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=C...,"(1, 14)","{0: 0.8853639960289001, 1: 0.9299560785293579,..."
119,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC...,"(1, 14)","{0: 0.2678848206996918, 1: 0.15740716457366943..."
120,OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2,"(1, 14)","{0: 0.9624060988426208, 1: 0.9830583930015564,..."
121,OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=...,"(1, 14)","{0: 0.8271753191947937, 1: 0.5703520178794861,..."
122,C1=CN=C(N2CCNCC2)N=C1,"(1, 14)","{0: 0.3049726188182831, 1: 0.1364114135503769,..."

In [121]:
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

In [122]:
scores = df['score'].to_list()
scores = list(map(assign_ranks,scores))
scores

[{0: 23,
  1: 20,
  2: 21,
  3: 16,
  4: 11,
  5: 17,
  6: 1,
  7: 2,
  8: 9,
  9: 6,
  10: 12,
  11: 10,
  12: 3,
  13: 8,
  14: 22,
  15: 14,
  16: 13,
  17: 15,
  18: 18,
  19: 4,
  20: 5,
  21: 19,
  22: 7},
 {0: 13,
  1: 3,
  2: 17,
  3: 6,
  4: 14,
  5: 11,
  6: 20,
  7: 22,
  8: 19,
  9: 12,
  10: 8,
  11: 23,
  12: 21,
  13: 18,
  14: 9,
  15: 15,
  16: 16,
  17: 10,
  18: 2,
  19: 7,
  20: 1,
  21: 5,
  22: 4},
 {0: 11,
  1: 4,
  2: 19,
  3: 3,
  4: 20,
  5: 18,
  6: 17,
  7: 9,
  8: 22,
  9: 7,
  10: 26,
  11: 37,
  12: 23,
  13: 36,
  14: 30,
  15: 34,
  16: 31,
  17: 33,
  18: 32,
  19: 27,
  20: 6,
  21: 25,
  22: 10,
  23: 24,
  24: 16,
  25: 5,
  26: 35,
  27: 8,
  28: 12,
  29: 1,
  30: 2,
  31: 13,
  32: 21,
  33: 28,
  34: 15,
  35: 29,
  36: 14},
 {0: 8,
  1: 14,
  2: 16,
  3: 11,
  4: 6,
  5: 15,
  6: 19,
  7: 23,
  8: 12,
  9: 13,
  10: 22,
  11: 26,
  12: 2,
  13: 1,
  14: 3,
  15: 7,
  16: 21,
  17: 24,
  18: 29,
  19: 20,
  20: 18,
  21: 17,
  22: 10,
  23: 25,
  24: 27,
  25: 28,
  26: 9,
  27: 4,
  28: 5},
 {0: 12,
  1: 8,
  2: 11,
  3: 7,
  4: 28,
  5: 29,
  6: 40,
  7: 19,
  8: 6,
  9: 27,
  10: 15,
  11: 38,
  12: 35,
  13: 36,
  14: 39,
  15: 34,
  16: 13,
  17: 5,
  18: 31,
  19: 26,
  20: 20,
  21: 21,
  22: 32,
  23: 23,
  24: 16,
  25: 24,
  26: 30,
  27: 10,
  28: 3,
  29: 2,
  30: 9,
  31: 1,
  32: 4,
  33: 18,
  34: 17,
  35: 25,
  36: 37,
  37: 33,
  38: 14,
  39: 22},
 {0: 12,
  1: 14,
  2: 3,
  3: 18,
  4: 5,
  5: 15,
  6: 9,
  7: 27,
  8: 21,
  9: 22,
  10: 26,
  11: 8,
  12: 7,
  13: 16,
  14: 17,
  15: 24,
  16: 23,
  17: 13,
  18: 2,
  19: 1,
  20: 11,
  21: 25,
  22: 19,
  23: 6,
  24: 4,
  25: 10,
  26: 20},
 {0: 16,
  1: 23,
  2: 14,
  3: 21,
  4: 20,
  5: 12,
  6: 19,
  7: 26,
  8: 24,
  9: 13,
  10: 5,
  11: 3,
  12: 2,
  13: 15,
  14: 22,
  15: 25,
  16: 4,
  17: 6,
  18: 8,
  19: 9,
  20: 11,
  21: 10,
  22: 1,
  23: 7,
  24: 17,
  25: 18},
 {0: 21,
  1: 26,
  2: 17,
  3: 23,
  4: 15,
  5: 16,
  6: 19,
  7: 27,
  8: 22,
  9: 24,
  10: 12,
  11: 10,
  12: 6,
  13: 14,
  14: 11,
  15: 25,
  16: 7,
  17: 5,
  18: 3,
  19: 4,
  20: 8,
  21: 20,
  22: 9,
  23: 13,
  24: 18,
  25: 1,
  26: 2},
 {0: 3,
  1: 15,
  2: 21,
  3: 11,
  4: 9,
  5: 10,
  6: 22,
  7: 6,
  8: 12,
  9: 14,
  10: 17,
  11: 16,
  12: 8,
  13: 4,
  14: 13,
  15: 5,
  16: 20,
  17: 19,
  18: 18,
  19: 7,
  20: 1,
  21: 2},
 {0: 12,
  1: 23,
  2: 22,
  3: 17,
  4: 14,
  5: 10,
  6: 15,
  7: 19,
  8: 6,
  9: 7,
  10: 16,
  11: 20,
  12: 5,
  13: 4,
  14: 13,
  15: 9,
  16: 21,
  17: 18,
  18: 11,
  19: 8,
  20: 1,
  21: 2,
  22: 3},
 {0: 3,
  1: 8,
  2: 19,
  3: 9,
  4: 10,
  5: 20,
  6: 22,
  7: 15,
  8: 12,
  9: 16,
  10: 13,
  11: 14,
  12: 5,
  13: 4,
  14: 18,
  15: 7,
  16: 21,
  17: 11,
  18: 17,
  19: 6,
  20: 1,
  21: 2},
 {0: 3,
  1: 20,
  2: 16,
  3: 18,
  4: 12,
  5: 11,
  6: 21,
  7: 15,
  8: 9,
  9: 7,
  10: 19,
  11: 17,
  12: 6,
  13: 4,
  14: 14,
  15: 8,
  16: 22,
  17: 13,
  18: 10,
  19: 5,
  20: 1,
  21: 2},
 {0: 15,
  1: 6,
  2: 4,
  3: 14,
  4: 5,
  5: 13,
  6: 16,
  7: 11,
  8: 9,
  9: 28,
  10: 30,
  11: 18,
  12: 21,
  13: 25,
  14: 22,
  15: 12,
  16: 3,
  17: 7,
  18: 8,
  19: 20,
  20: 2,
  21: 1,
  22: 31,
  23: 10,
  24: 19,
  25: 23,
  26: 17,
  27: 27,
  28: 26,
  29: 29,
  30: 24},
 {0: 9,
  1: 7,
  2: 4,
  3: 10,
  4: 5,
  5: 15,
  6: 13,
  7: 16,
  8: 11,
  9: 27,
  10: 23,
  11: 18,
  12: 26,
  13: 32,
  14: 30,
  15: 6,
  16: 1,
  17: 12,
  18: 8,
  19: 17,
  20: 25,
  21: 3,
  22: 2,
  23: 28,
  24: 20,
  25: 21,
  26: 29,
  27: 19,
  28: 14,
  29: 22,
  30: 31,
  31: 24},
 {0: 17,
  1: 26,
  2: 20,
  3: 19,
  4: 5,
  5: 10,
  6: 13,
  7: 6,
  8: 36,
  9: 38,
  10: 11,
  11: 14,
  12: 25,
  13: 12,
  14: 8,
  15: 43,
  16: 35,
  17: 27,
  18: 28,
  19: 7,
  20: 1,
  21: 3,
  22: 39,
  23: 40,
  24: 46,
  25: 18,
  26: 4,
  27: 2,
  28: 22,
  29: 30,
  30: 37,
  31: 15,
  32: 41,
  33: 44,
  34: 42,
  35: 48,
  36: 33,
  37: 49,
  38: 45,
  39: 32,
  40: 47,
  41: 29,
  42: 24,
  43: 16,
  44: 23,
  45: 21,
  46: 31,
  47: 9,
  48: 34},
 {0: 6,
  1: 14,
  2: 19,
  3: 17,
  4: 15,
  5: 1,
  6: 8,
  7: 5,
  8: 11,
  9: 12,
  10: 3,
  11: 2,
  12: 9,
  13: 4,
  14: 7,
  15: 23,
  16: 25,
  17: 21,
  18: 24,
  19: 20,
  20: 22,
  21: 16,
  22: 10,
  23: 18,
  24: 13},
 {0: 9,
  1: 17,
  2: 15,
  3: 13,
  4: 8,
  5: 1,
  6: 4,
  7: 6,
  8: 11,
  9: 18,
  10: 3,
  11: 2,
  12: 10,
  13: 5,
  14: 7,
  15: 20,
  16: 25,
  17: 23,
  18: 24,
  19: 19,
  20: 22,
  21: 21,
  22: 14,
  23: 16,
  24: 12},
 {0: 7,
  1: 14,
  2: 13,
  3: 12,
  4: 3,
  5: 1,
  6: 2,
  7: 18,
  8: 5,
  9: 20,
  10: 25,
  11: 24,
  12: 22,
  13: 8,
  14: 15,
  15: 23,
  16: 17,
  17: 10,
  18: 11,
  19: 9,
  20: 6,
  21: 4,
  22: 16,
  23: 21,
  24: 19},
 {0: 5,
  1: 8,
  2: 17,
  3: 19,
  4: 12,
  5: 2,
  6: 1,
  7: 9,
  8: 16,
  9: 21,
  10: 3,
  11: 4,
  12: 7,
  13: 6,
  14: 10,
  15: 25,
  16: 24,
  17: 22,
  18: 23,
  19: 20,
  20: 15,
  21: 13,
  22: 14,
  23: 18,
  24: 11},
 {0: 27,
  1: 23,
  2: 20,
  3: 4,
  4: 26,
  5: 31,
  6: 22,
  7: 25,
  8: 29,
  9: 30,
  10: 24,
  11: 18,
  12: 33,
  13: 32,
  14: 28,
  15: 1,
  16: 2,
  17: 3,
  18: 13,
  19: 21,
  20: 16,
  21: 15,
  22: 11,
  23: 10,
  24: 12,
  25: 9,
  26: 19,
  27: 17,
  28: 8,
  29: 6,
  30: 5,
  31: 34,
  32: 7,
  33: 14},
 {0: 9,
  1: 8,
  2: 4,
  3: 6,
  4: 7,
  5: 1,
  6: 3,
  7: 16,
  8: 18,
  9: 12,
  10: 15,
  11: 17,
  12: 13,
  13: 10,
  14: 14,
  15: 11,
  16: 5,
  17: 2},
 {0: 20,
  1: 18,
  2: 13,
  3: 14,
  4: 9,
  5: 10,
  6: 16,
  7: 21,
  8: 11,
  9: 4,
  10: 1,
  11: 2,
  12: 5,
  13: 6,
  14: 19,
  15: 23,
  16: 22,
  17: 17,
  18: 3,
  19: 12,
  20: 7,
  21: 8,
  22: 15},
 {0: 12,
  1: 1,
  2: 6,
  3: 17,
  4: 30,
  5: 26,
  6: 4,
  7: 5,
  8: 7,
  9: 18,
  10: 3,
  11: 2,
  12: 29,
  13: 24,
  14: 25,
  15: 27,
  16: 21,
  17: 13,
  18: 16,
  19: 14,
  20: 8,
  21: 20,
  22: 10,
  23: 9,
  24: 11,
  25: 15,
  26: 31,
  27: 23,
  28: 22,
  29: 19,
  30: 28},
 {0: 13,
  1: 6,
  2: 7,
  3: 11,
  4: 24,
  5: 19,
  6: 3,
  7: 2,
  8: 22,
  9: 26,
  10: 12,
  11: 17,
  12: 28,
  13: 14,
  14: 16,
  15: 21,
  16: 27,
  17: 29,
  18: 20,
  19: 23,
  20: 15,
  21: 8,
  22: 9,
  23: 25,
  24: 1,
  25: 10,
  26: 4,
  27: 5,
  28: 18},
 {0: 11,
  1: 13,
  2: 12,
  3: 17,
  4: 14,
  5: 8,
  6: 6,
  7: 10,
  8: 5,
  9: 9,
  10: 16,
  11: 7,
  12: 15,
  13: 4,
  14: 1,
  15: 2,
  16: 3},
 {0: 10,
  1: 11,
  2: 8,
  3: 16,
  4: 12,
  5: 14,
  6: 9,
  7: 6,
  8: 4,
  9: 15,
  10: 7,
  11: 13,
  12: 5,
  13: 1,
  14: 3,
  15: 2},
 {0: 15,
  1: 11,
  2: 12,
  3: 3,
  4: 6,
  5: 8,
  6: 4,
  7: 9,
  8: 14,
  9: 13,
  10: 10,
  11: 7,
  12: 5,
  13: 1,
  14: 2},
 {0: 2,
  1: 1,
  2: 3,
  3: 4,
  4: 21,
  5: 18,
  6: 10,
  7: 22,
  8: 9,
  9: 8,
  10: 23,
  11: 5,
  12: 15,
  13: 6,
  14: 19,
  15: 17,
  16: 24,
  17: 13,
  18: 16,
  19: 11,
  20: 7,
  21: 12,
  22: 14,
  23: 20},
 {0: 3,
  1: 1,
  2: 2,
  3: 4,
  4: 23,
  5: 17,
  6: 12,
  7: 19,
  8: 9,
  9: 10,
  10: 20,
  11: 7,
  12: 6,
  13: 11,
  14: 24,
  15: 13,
  16: 22,
  17: 18,
  18: 14,
  19: 16,
  20: 15,
  21: 5,
  22: 8,
  23: 21},
 {0: 3,
  1: 1,
  2: 2,
  3: 8,
  4: 18,
  5: 19,
  6: 16,
  7: 11,
  8: 20,
  9: 14,
  10: 6,
  11: 4,
  12: 12,
  13: 7,
  14: 5,
  15: 9,
  16: 13,
  17: 15,
  18: 10,
  19: 17,
  20: 21},
 {0: 3,
  1: 1,
  2: 2,
  3: 6,
  4: 14,
  5: 20,
  6: 13,
  7: 10,
  8: 18,
  9: 12,
  10: 15,
  11: 16,
  12: 7,
  13: 4,
  14: 8,
  15: 9,
  16: 11,
  17: 5,
  18: 17,
  19: 19},
 {0: 8,
  1: 3,
  2: 4,
  3: 9,
  4: 11,
  5: 2,
  6: 7,
  7: 6,
  8: 18,
  9: 13,
  10: 12,
  11: 5,
  12: 1,
  13: 10,
  14: 16,
  15: 14,
  16: 20,
  17: 22,
  18: 17,
  19: 21,
  20: 15,
  21: 19},
 {0: 2,
  1: 1,
  2: 3,
  3: 7,
  4: 15,
  5: 12,
  6: 9,
  7: 26,
  8: 21,
  9: 28,
  10: 22,
  11: 25,
  12: 27,
  13: 8,
  14: 5,
  15: 23,
  16: 24,
  17: 16,
  18: 4,
  19: 20,
  20: 14,
  21: 19,
  22: 17,
  23: 6,
  24: 11,
  25: 10,
  26: 18,
  27: 13},
 {0: 4,
  1: 1,
  2: 11,
  3: 22,
  4: 32,
  5: 29,
  6: 14,
  7: 6,
  8: 20,
  9: 23,
  10: 26,
  11: 27,
  12: 5,
  13: 2,
  14: 8,
  15: 3,
  16: 18,
  17: 9,
  18: 17,
  19: 31,
  20: 12,
  21: 24,
  22: 10,
  23: 16,
  24: 19,
  25: 13,
  26: 7,
  27: 30,
  28: 21,
  29: 15,
  30: 28,
  31: 25},
 {0: 10,
  1: 7,
  2: 13,
  3: 21,
  4: 49,
  5: 11,
  6: 31,
  7: 50,
  8: 48,
  9: 44,
  10: 46,
  11: 43,
  12: 33,
  13: 15,
  14: 23,
  15: 4,
  16: 30,
  17: 3,
  18: 5,
  19: 40,
  20: 22,
  21: 14,
  22: 38,
  23: 12,
  24: 2,
  25: 1,
  26: 41,
  27: 42,
  28: 25,
  29: 17,
  30: 20,
  31: 16,
  32: 36,
  33: 39,
  34: 9,
  35: 37,
  36: 26,
  37: 24,
  38: 45,
  39: 51,
  40: 32,
  41: 27,
  42: 35,
  43: 6,
  44: 8,
  45: 29,
  46: 28,
  47: 18,
  48: 19,
  49: 47,
  50: 34},
 {0: 2,
  1: 1,
  2: 3,
  3: 17,
  4: 19,
  5: 13,
  6: 16,
  7: 8,
  8: 10,
  9: 21,
  10: 14,
  11: 15,
  12: 9,
  13: 20,
  14: 18,
  15: 23,
  16: 7,
  17: 6,
  18: 4,
  19: 5,
  20: 12,
  21: 11,
  22: 22},
 {0: 2,
  1: 1,
  2: 3,
  3: 14,
  4: 19,
  5: 15,
  6: 17,
  7: 5,
  8: 7,
  9: 22,
  10: 10,
  11: 6,
  12: 8,
  13: 21,
  14: 13,
  15: 23,
  16: 11,
  17: 4,
  18: 16,
  19: 18,
  20: 12,
  21: 9,
  22: 20},
 {0: 20,
  1: 15,
  2: 19,
  3: 14,
  4: 5,
  5: 3,
  6: 21,
  7: 22,
  8: 6,
  9: 8,
  10: 10,
  11: 30,
  12: 12,
  13: 7,
  14: 29,
  15: 9,
  16: 16,
  17: 32,
  18: 31,
  19: 26,
  20: 2,
  21: 1,
  22: 11,
  23: 4,
  24: 13,
  25: 27,
  26: 34,
  27: 23,
  28: 33,
  29: 18,
  30: 17,
  31: 24,
  32: 28,
  33: 25,
  34: 35},
 {0: 3,
  1: 6,
  2: 25,
  3: 24,
  4: 11,
  5: 21,
  6: 27,
  7: 15,
  8: 5,
  9: 10,
  10: 28,
  11: 26,
  12: 13,
  13: 4,
  14: 23,
  15: 20,
  16: 1,
  17: 2,
  18: 17,
  19: 22,
  20: 18,
  21: 9,
  22: 12,
  23: 7,
  24: 14,
  25: 29,
  26: 19,
  27: 8,
  28: 16},
 {0: 7,
  1: 3,
  2: 27,
  3: 20,
  4: 31,
  5: 2,
  6: 29,
  7: 25,
  8: 16,
  9: 24,
  10: 28,
  11: 26,
  12: 36,
  13: 23,
  14: 13,
  15: 1,
  16: 6,
  17: 14,
  18: 19,
  19: 12,
  20: 9,
  21: 5,
  22: 8,
  23: 4,
  24: 15,
  25: 10,
  26: 33,
  27: 32,
  28: 21,
  29: 30,
  30: 35,
  31: 18,
  32: 17,
  33: 34,
  34: 22,
  35: 11},
 {0: 4,
  1: 6,
  2: 11,
  3: 23,
  4: 19,
  5: 13,
  6: 10,
  7: 16,
  8: 9,
  9: 1,
  10: 14,
  11: 15,
  12: 5,
  13: 20,
  14: 25,
  15: 27,
  16: 17,
  17: 26,
  18: 30,
  19: 33,
  20: 24,
  21: 18,
  22: 29,
  23: 31,
  24: 12,
  25: 2,
  26: 3,
  27: 7,
  28: 22,
  29: 21,
  30: 32,
  31: 28,
  32: 8},
 {0: 2,
  1: 4,
  2: 11,
  3: 13,
  4: 14,
  5: 15,
  6: 12,
  7: 23,
  8: 21,
  9: 24,
  10: 19,
  11: 27,
  12: 6,
  13: 16,
  14: 26,
  15: 5,
  16: 18,
  17: 8,
  18: 1,
  19: 7,
  20: 25,
  21: 28,
  22: 10,
  23: 17,
  24: 20,
  25: 22,
  26: 29,
  27: 9,
  28: 3},
 {0: 13,
  1: 17,
  2: 20,
  3: 16,
  4: 15,
  5: 18,
  6: 14,
  7: 12,
  8: 5,
  9: 4,
  10: 10,
  11: 3,
  12: 1,
  13: 2,
  14: 11,
  15: 23,
  16: 22,
  17: 19,
  18: 21,
  19: 8,
  20: 6,
  21: 9,
  22: 7},
 {0: 6,
  1: 7,
  2: 16,
  3: 22,
  4: 21,
  5: 26,
  6: 17,
  7: 19,
  8: 15,
  9: 14,
  10: 25,
  11: 8,
  12: 4,
  13: 12,
  14: 23,
  15: 13,
  16: 24,
  17: 11,
  18: 10,
  19: 5,
  20: 20,
  21: 18,
  22: 1,
  23: 9,
  24: 3,
  25: 2},
 {0: 12,
  1: 17,
  2: 21,
  3: 11,
  4: 6,
  5: 23,
  6: 9,
  7: 20,
  8: 1,
  9: 2,
  10: 16,
  11: 22,
  12: 13,
  13: 8,
  14: 7,
  15: 5,
  16: 19,
  17: 4,
  18: 3,
  19: 14,
  20: 15,
  21: 10,
  22: 24,
  23: 18},
 {0: 19,
  1: 15,
  2: 14,
  3: 13,
  4: 16,
  5: 12,
  6: 17,
  7: 23,
  8: 20,
  9: 21,
  10: 10,
  11: 3,
  12: 6,
  13: 28,
  14: 29,
  15: 4,
  16: 7,
  17: 24,
  18: 18,
  19: 25,
  20: 11,
  21: 9,
  22: 8,
  23: 5,
  24: 22,
  25: 2,
  26: 1,
  27: 26,
  28: 27},
 {0: 25,
  1: 27,
  2: 24,
  3: 13,
  4: 9,
  5: 7,
  6: 5,
  7: 11,
  8: 12,
  9: 15,
  10: 18,
  11: 26,
  12: 19,
  13: 38,
  14: 39,
  15: 6,
  16: 4,
  17: 33,
  18: 22,
  19: 14,
  20: 30,
  21: 29,
  22: 28,
  23: 3,
  24: 17,
  25: 2,
  26: 1,
  27: 16,
  28: 20,
  29: 8,
  30: 10,
  31: 21,
  32: 37,
  33: 31,
  34: 32,
  35: 23,
  36: 34,
  37: 36,
  38: 35},
 {0: 18,
  1: 22,
  2: 25,
  3: 20,
  4: 10,
  5: 11,
  6: 13,
  7: 17,
  8: 16,
  9: 26,
  10: 23,
  11: 5,
  12: 6,
  13: 27,
  14: 29,
  15: 7,
  16: 9,
  17: 15,
  18: 21,
  19: 14,
  20: 24,
  21: 12,
  22: 8,
  23: 3,
  24: 4,
  25: 2,
  26: 1,
  27: 19,
  28: 28},
 {0: 19,
  1: 22,
  2: 26,
  3: 14,
  4: 6,
  5: 16,
  6: 13,
  7: 21,
  8: 5,
  9: 10,
  10: 12,
  11: 7,
  12: 17,
  13: 37,
  14: 38,
  15: 11,
  16: 20,
  17: 23,
  18: 27,
  19: 24,
  20: 34,
  21: 28,
  22: 29,
  23: 3,
  24: 4,
  25: 1,
  26: 2,
  27: 31,
  28: 15,
  29: 8,
  30: 18,
  31: 32,
  32: 33,
  33: 9,
  34: 30,
  35: 25,
  36: 35,
  37: 39,
  38: 36},
 {0: 1, 1: 2, 2: 4, 3: 7, 4: 11, 5: 6, 6: 10, 7: 9, 8: 12, 9: 5, 10: 8, 11: 3},
 {0: 1,
  1: 2,
  2: 6,
  3: 16,
  4: 19,
  5: 17,
  6: 13,
  7: 14,
  8: 18,
  9: 11,
  10: 12,
  11: 10,
  12: 7,
  13: 20,
  14: 21,
  15: 9,
  16: 5,
  17: 15,
  18: 8,
  19: 4,
  20: 3},
 {0: 6,
  1: 7,
  2: 10,
  3: 14,
  4: 33,
  5: 30,
  6: 24,
  7: 27,
  8: 12,
  9: 13,
  10: 25,
  11: 11,
  12: 15,
  13: 8,
  14: 35,
  15: 29,
  16: 34,
  17: 31,
  18: 32,
  19: 28,
  20: 5,
  21: 4,
  22: 16,
  23: 9,
  24: 1,
  25: 2,
  26: 3,
  27: 18,
  28: 20,
  29: 17,
  30: 26,
  31: 37,
  32: 19,
  33: 23,
  34: 22,
  35: 21,
  36: 36},
 {0: 1,
  1: 4,
  2: 11,
  3: 16,
  4: 3,
  5: 12,
  6: 2,
  7: 5,
  8: 14,
  9: 23,
  10: 9,
  11: 10,
  12: 15,
  13: 20,
  14: 8,
  15: 17,
  16: 6,
  17: 7,
  18: 22,
  19: 13,
  20: 18,
  21: 19,
  22: 21},
 {0: 17,
  1: 1,
  2: 5,
  3: 2,
  4: 26,
  5: 21,
  6: 18,
  7: 27,
  8: 6,
  9: 14,
  10: 7,
  11: 15,
  12: 12,
  13: 3,
  14: 4,
  15: 22,
  16: 19,
  17: 28,
  18: 24,
  19: 10,
  20: 8,
  21: 9,
  22: 11,
  23: 13,
  24: 16,
  25: 23,
  26: 20,
  27: 25},
 {0: 17,
  1: 1,
  2: 5,
  3: 4,
  4: 23,
  5: 19,
  6: 24,
  7: 28,
  8: 8,
  9: 22,
  10: 9,
  11: 12,
  12: 14,
  13: 18,
  14: 21,
  15: 20,
  16: 27,
  17: 25,
  18: 15,
  19: 6,
  20: 2,
  21: 3,
  22: 7,
  23: 10,
  24: 11,
  25: 26,
  26: 13,
  27: 16},
 {0: 15,
  1: 1,
  2: 2,
  3: 4,
  4: 14,
  5: 20,
  6: 22,
  7: 24,
  8: 3,
  9: 11,
  10: 5,
  11: 12,
  12: 17,
  13: 13,
  14: 21,
  15: 16,
  16: 25,
  17: 18,
  18: 8,
  19: 7,
  20: 6,
  21: 9,
  22: 10,
  23: 19,
  24: 26,
  25: 23,
  26: 27},
 {0: 17,
  1: 1,
  2: 2,
  3: 8,
  4: 28,
  5: 26,
  6: 12,
  7: 19,
  8: 32,
  9: 33,
  10: 31,
  11: 9,
  12: 3,
  13: 21,
  14: 24,
  15: 30,
  16: 20,
  17: 14,
  18: 27,
  19: 7,
  20: 15,
  21: 10,
  22: 13,
  23: 5,
  24: 4,
  25: 6,
  26: 23,
  27: 16,
  28: 11,
  29: 22,
  30: 29,
  31: 25,
  32: 18},
 {0: 4,
  1: 10,
  2: 9,
  3: 16,
  4: 18,
  5: 19,
  6: 20,
  7: 2,
  8: 1,
  9: 12,
  10: 5,
  11: 17,
  12: 3,
  13: 7,
  14: 6,
  15: 14,
  16: 15,
  17: 8,
  18: 11,
  19: 13},
 {0: 14,
  1: 30,
  2: 18,
  3: 19,
  4: 26,
  5: 11,
  6: 7,
  7: 6,
  8: 29,
  9: 25,
  10: 8,
  11: 9,
  12: 22,
  13: 23,
  14: 35,
  15: 27,
  16: 32,
  17: 28,
  18: 2,
  19: 1,
  20: 13,
  21: 31,
  22: 21,
  23: 10,
  24: 5,
  25: 4,
  26: 34,
  27: 17,
  28: 20,
  29: 15,
  30: 3,
  31: 16,
  32: 12,
  33: 33,
  34: 24},
 {0: 12,
  1: 26,
  2: 24,
  3: 17,
  4: 27,
  5: 15,
  6: 4,
  7: 3,
  8: 36,
  9: 25,
  10: 5,
  11: 10,
  12: 20,
  13: 37,
  14: 34,
  15: 33,
  16: 28,
  17: 31,
  18: 2,
  19: 1,
  20: 19,
  21: 23,
  22: 13,
  23: 14,
  24: 11,
  25: 9,
  26: 21,
  27: 30,
  28: 16,
  29: 18,
  30: 6,
  31: 22,
  32: 7,
  33: 29,
  34: 8,
  35: 32,
  36: 35},
 {0: 22,
  1: 20,
  2: 10,
  3: 19,
  4: 6,
  5: 18,
  6: 7,
  7: 26,
  8: 14,
  9: 13,
  10: 28,
  11: 16,
  12: 2,
  13: 5,
  14: 1,
  15: 3,
  16: 8,
  17: 11,
  18: 15,
  19: 23,
  20: 24,
  21: 21,
  22: 12,
  23: 27,
  24: 9,
  25: 4,
  26: 25,
  27: 17},
 {0: 18,
  1: 12,
  2: 16,
  3: 24,
  4: 9,
  5: 19,
  6: 5,
  7: 22,
  8: 15,
  9: 10,
  10: 27,
  11: 26,
  12: 3,
  13: 1,
  14: 2,
  15: 11,
  16: 13,
  17: 8,
  18: 21,
  19: 17,
  20: 20,
  21: 28,
  22: 23,
  23: 25,
  24: 6,
  25: 4,
  26: 14,
  27: 7},
 {0: 4, 1: 2, 2: 1, 3: 8, 4: 9, 5: 11, 6: 5, 7: 7, 8: 3, 9: 6, 10: 10},
 {0: 3, 1: 2, 2: 1, 3: 4, 4: 10, 5: 5, 6: 9, 7: 7, 8: 8, 9: 6},
 {0: 12,
  1: 13,
  2: 14,
  3: 7,
  4: 3,
  5: 8,
  6: 1,
  7: 2,
  8: 11,
  9: 4,
  10: 15,
  11: 17,
  12: 16,
  13: 5,
  14: 6,
  15: 10,
  16: 9},
 {0: 20,
  1: 22,
  2: 21,
  3: 17,
  4: 25,
  5: 16,
  6: 1,
  7: 15,
  8: 23,
  9: 18,
  10: 10,
  11: 9,
  12: 14,
  13: 19,
  14: 24,
  15: 26,
  16: 12,
  17: 4,
  18: 11,
  19: 13,
  20: 7,
  21: 5,
  22: 8,
  23: 2,
  24: 6,
  25: 3},
 {0: 21,
  1: 20,
  2: 28,
  3: 17,
  4: 27,
  5: 7,
  6: 25,
  7: 19,
  8: 23,
  9: 18,
  10: 6,
  11: 34,
  12: 16,
  13: 13,
  14: 1,
  15: 2,
  16: 11,
  17: 22,
  18: 26,
  19: 24,
  20: 30,
  21: 35,
  22: 33,
  23: 32,
  24: 29,
  25: 31,
  26: 10,
  27: 15,
  28: 9,
  29: 8,
  30: 3,
  31: 4,
  32: 12,
  33: 5,
  34: 14},
 {0: 11,
  1: 37,
  2: 9,
  3: 4,
  4: 6,
  5: 34,
  6: 26,
  7: 31,
  8: 22,
  9: 8,
  10: 15,
  11: 10,
  12: 25,
  13: 7,
  14: 1,
  15: 2,
  16: 30,
  17: 21,
  18: 38,
  19: 32,
  20: 24,
  21: 13,
  22: 3,
  23: 5,
  24: 33,
  25: 36,
  26: 35,
  27: 29,
  28: 23,
  29: 28,
  30: 18,
  31: 20,
  32: 17,
  33: 14,
  34: 12,
  35: 19,
  36: 27,
  37: 16},
 {0: 21,
  1: 23,
  2: 7,
  3: 3,
  4: 5,
  5: 29,
  6: 24,
  7: 26,
  8: 25,
  9: 13,
  10: 12,
  11: 18,
  12: 27,
  13: 6,
  14: 2,
  15: 8,
  16: 17,
  17: 16,
  18: 19,
  19: 10,
  20: 1,
  21: 4,
  22: 30,
  23: 22,
  24: 28,
  25: 9,
  26: 14,
  27: 15,
  28: 20,
  29: 11},
 {0: 25,
  1: 23,
  2: 12,
  3: 4,
  4: 5,
  5: 13,
  6: 11,
  7: 17,
  8: 16,
  9: 14,
  10: 19,
  11: 20,
  12: 22,
  13: 8,
  14: 1,
  15: 2,
  16: 9,
  17: 7,
  18: 24,
  19: 18,
  20: 10,
  21: 6,
  22: 3,
  23: 21,
  24: 26,
  25: 15},
 {0: 22,
  1: 25,
  2: 6,
  3: 3,
  4: 4,
  5: 12,
  6: 20,
  7: 19,
  8: 21,
  9: 10,
  10: 17,
  11: 7,
  12: 15,
  13: 5,
  14: 1,
  15: 2,
  16: 16,
  17: 9,
  18: 24,
  19: 8,
  20: 18,
  21: 13,
  22: 11,
  23: 23,
  24: 14},
 {0: 21,
  1: 28,
  2: 33,
  3: 22,
  4: 6,
  5: 19,
  6: 23,
  7: 29,
  8: 25,
  9: 8,
  10: 20,
  11: 13,
  12: 31,
  13: 15,
  14: 9,
  15: 3,
  16: 17,
  17: 16,
  18: 27,
  19: 18,
  20: 32,
  21: 5,
  22: 26,
  23: 10,
  24: 4,
  25: 12,
  26: 24,
  27: 11,
  28: 2,
  29: 1,
  30: 14,
  31: 7,
  32: 30},
 {0: 16,
  1: 8,
  2: 4,
  3: 5,
  4: 2,
  5: 1,
  6: 20,
  7: 11,
  8: 13,
  9: 23,
  10: 21,
  11: 17,
  12: 15,
  13: 18,
  14: 22,
  15: 9,
  16: 6,
  17: 10,
  18: 12,
  19: 14,
  20: 19,
  21: 3,
  22: 7},
 {0: 6,
  1: 9,
  2: 8,
  3: 12,
  4: 4,
  5: 5,
  6: 21,
  7: 20,
  8: 17,
  9: 16,
  10: 14,
  11: 24,
  12: 15,
  13: 13,
  14: 19,
  15: 10,
  16: 7,
  17: 11,
  18: 18,
  19: 22,
  20: 23,
  21: 3,
  22: 1,
  23: 2},
 {0: 13,
  1: 20,
  2: 16,
  3: 12,
  4: 10,
  5: 17,
  6: 15,
  7: 8,
  8: 6,
  9: 1,
  10: 4,
  11: 9,
  12: 3,
  13: 7,
  14: 5,
  15: 22,
  16: 18,
  17: 14,
  18: 11,
  19: 19,
  20: 21,
  21: 2},
 {0: 5,
  1: 6,
  2: 12,
  3: 16,
  4: 10,
  5: 18,
  6: 33,
  7: 26,
  8: 27,
  9: 34,
  10: 29,
  11: 13,
  12: 17,
  13: 21,
  14: 24,
  15: 7,
  16: 15,
  17: 11,
  18: 14,
  19: 4,
  20: 1,
  21: 2,
  22: 23,
  23: 28,
  24: 31,
  25: 3,
  26: 19,
  27: 30,
  28: 32,
  29: 9,
  30: 8,
  31: 20,
  32: 25,
  33: 22},
 {0: 4,
  1: 9,
  2: 19,
  3: 17,
  4: 21,
  5: 26,
  6: 31,
  7: 30,
  8: 27,
  9: 28,
  10: 25,
  11: 12,
  12: 2,
  13: 11,
  14: 16,
  15: 1,
  16: 20,
  17: 15,
  18: 10,
  19: 14,
  20: 6,
  21: 7,
  22: 5,
  23: 23,
  24: 8,
  25: 3,
  26: 13,
  27: 18,
  28: 24,
  29: 22,
  30: 29},
 {0: 1,
  1: 2,
  2: 12,
  3: 19,
  4: 20,
  5: 21,
  6: 32,
  7: 30,
  8: 28,
  9: 31,
  10: 25,
  11: 14,
  12: 8,
  13: 9,
  14: 16,
  15: 3,
  16: 24,
  17: 22,
  18: 17,
  19: 23,
  20: 4,
  21: 7,
  22: 11,
  23: 15,
  24: 5,
  25: 6,
  26: 10,
  27: 18,
  28: 26,
  29: 13,
  30: 27,
  31: 29},
 {0: 4,
  1: 3,
  2: 5,
  3: 11,
  4: 9,
  5: 18,
  6: 29,
  7: 23,
  8: 22,
  9: 28,
  10: 26,
  11: 7,
  12: 8,
  13: 10,
  14: 27,
  15: 12,
  16: 21,
  17: 15,
  18: 16,

In [123]:
df['score'] = scores

In [124]:
df

,substrate,ec,score
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,"(1, 14)","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ..."
1,CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2,"(1, 14)","{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20..."
2,CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=C...,"(1, 14)","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17..."
3,CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=...,"(1, 14)","{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19..."
4,CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=C...,"(1, 14)","{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40..."
...,...,...,...
118,OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=C...,"(1, 14)","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23..."
119,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC...,"(1, 14)","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12..."
120,OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2,"(1, 14)","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7..."
121,OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=...,"(1, 14)","{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ..."
122,C1=CN=C(N2CCNCC2)N=C1,"(1, 14)","{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7..."

In [125]:
df.to_pickle('gnnsom_results_drugbank_rank.pickle')

In [126]:
df = pd.read_pickle('gnnsom_results_drugbank_rank.pickle')
from rdkit import Chem
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new
smiles = df['substrate'].to_list()
smiles = list(map(canonicalsmiles,smiles))
df['substrate'] = smiles
df

,substrate,ec,score
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,"(1, 14)","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,"(1, 14)","{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,"(1, 14)","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,"(1, 14)","{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,"(1, 14)","{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40..."
...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,"(1, 14)","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,"(1, 14)","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,"(1, 14)","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,"(1, 14)","{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ..."
122,c1cnc(N2CCNCC2)nc1,"(1, 14)","{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7..."

In [127]:
df.to_pickle('gnnsom_results_drugbank_rank.pickle')

In [128]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrate', 'score')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O': {0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: 1, 7: 2, 8: 9, 9: 6, 10: 12, 11: 10, 12: 3, 13: 8, 14: 22, 15: 14, 16: 13, 17: 15, 18: 18, 19: 4, 20: 5, 21: 19, 22: 7}, 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20, 7: 22, 8: 19, 9: 12, 10: 8, 11: 23, 12: 21, 13: 18, 14: 9, 15: 15, 16: 16, 17: 10, 18: 2, 19: 7, 20: 1, 21: 5, 22: 4}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17, 7: 9, 8: 22, 9: 7, 10: 26, 11: 37, 12: 23, 13: 36, 14: 30, 15: 34, 16: 31, 17: 33, 18: 32, 19: 27, 20: 6, 21: 25, 22: 10, 23: 24, 24: 16, 25: 5, 26: 35, 27: 8, 28: 12, 29: 1, 30: 2, 31: 13, 32: 21, 33: 28, 34: 15, 35: 29, 36: 14}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19, 7: 23, 8: 12, 9: 13, 10: 22, 11: 26, 12: 2, 13: 1, 14: 3, 15: 7, 16: 21, 17: 24, 18: 29, 19: 20, 20: 18, 21: 17, 22: 10, 23: 25, 24: 27, 25: 28, 26: 9, 27: 4, 28: 5}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40, 7: 19, 8: 6, 9: 27, 10: 15, 11: 38, 12: 35, 13: 36, 14: 39, 15: 34, 16: 13, 17: 5, 18: 31, 19: 26, 20: 20, 21: 21, 22: 32, 23: 23, 24: 16, 25: 24, 26: 30, 27: 10, 28: 3, 29: 2, 30: 9, 31: 1, 32: 4, 33: 18, 34: 17, 35: 25, 36: 37, 37: 33, 38: 14, 39: 22}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 12, 1: 14, 2: 3, 3: 18, 4: 5, 5: 15, 6: 9, 7: 27, 8: 21, 9: 22, 10: 26, 11: 8, 12: 7, 13: 16, 14: 17, 15: 24, 16: 23, 17: 13, 18: 2, 19: 1, 20: 11, 21: 25, 22: 19, 23: 6, 24: 4, 25: 10, 26: 20}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 16, 1: 23, 2: 14, 3: 21, 4: 20, 5: 12, 6: 19, 7: 26, 8: 24, 9: 13, 10: 5, 11: 3, 12: 2, 13: 15, 14: 22, 15: 25, 16: 4, 17: 6, 18: 8, 19: 9, 20: 11, 21: 10, 22: 1, 23: 7, 24: 17, 25: 18}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 21, 1: 26, 2: 17, 3: 23, 4: 15, 5: 16, 6: 19, 7: 27, 8: 22, 9: 24, 10: 12, 11: 10, 12: 6, 13: 14, 14: 11, 15: 25, 16: 7, 17: 5, 18: 3, 19: 4, 20: 8, 21: 20, 22: 9, 23: 13, 24: 18, 25: 1, 26: 2}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1': {0: 3, 1: 15, 2: 21, 3: 11, 4: 9, 5: 10, 6: 22, 7: 6, 8: 12, 9: 14, 10: 17, 11: 16, 12: 8, 13: 4, 14: 13, 15: 5, 16: 20, 17: 19, 18: 18, 19: 7, 20: 1, 21: 2}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O': {0: 12, 1: 23, 2: 22, 3: 17, 4: 14, 5: 10, 6: 15, 7: 19, 8: 6, 9: 7, 10: 16, 11: 20, 12: 5, 13: 4, 14: 13, 15: 9, 16: 21, 17: 18, 18: 11, 19: 8, 20: 1, 21: 2, 22: 3}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 8, 2: 19, 3: 9, 4: 10, 5: 20, 6: 22, 7: 15, 8: 12, 9: 16, 10: 13, 11: 14, 12: 5, 13: 4, 14: 18, 15: 7, 16: 21, 17: 11, 18: 17, 19: 6, 20: 1, 21: 2}, 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 20, 2: 16, 3: 18, 4: 12, 5: 11, 6: 21, 7: 15, 8: 9, 9: 7, 10: 19, 11: 17, 12: 6, 13: 4, 14: 14, 15: 8, 16: 22, 17: 13, 18: 10, 19: 5, 20: 1, 21: 2}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 15, 1: 6, 2: 4, 3: 14, 4: 5, 5: 13, 6: 16, 7: 11, 8: 9, 9: 28, 10: 30, 11: 18, 12: 21, 13: 25, 14: 22, 15: 12, 16: 3, 17: 7, 18: 8, 19: 20, 20: 2, 21: 1, 22: 31, 23: 10, 24: 19, 25: 23, 26: 17, 27: 27, 28: 26, 29: 29, 30: 24}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 9, 1: 7, 2: 4, 3: 10, 4: 5, 5: 15, 6: 13, 7: 16, 8: 11, 9: 27, 10: 23, 11: 18, 12: 26, 13: 32, 14: 30, 15: 6, 16: 1, 17: 12, 18: 8, 19: 17, 20: 25, 21: 3, 22: 2, 23: 28, 24: 20, 25: 21, 26: 29, 27: 19, 28: 14, 29: 22, 30: 31, 31: 24}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 17, 1: 26, 2: 20, 3: 19, 4: 5, 5: 10, 6: 13, 7: 6, 8: 36, 9: 38, 10: 11, 11: 14, 12: 25, 13: 12, 14: 8, 15: 43, 16: 35, 17: 27, 18: 28, 19: 7, 20: 1, 21: 3, 22: 39, 23: 40, 24: 46, 25: 18, 26: 4, 27: 2, 28: 22, 29: 30, 30: 37, 31: 15, 32: 41, 33: 44, 34: 42, 35: 48, 36: 33, 37: 49, 38: 45, 39: 32, 40: 47, 41: 29, 42: 24, 43: 16, 44: 23, 45: 21, 46: 31, 47: 9, 48: 34}, 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 6, 1: 14, 2: 19, 3: 17, 4: 15, 5: 1, 6: 8, 7: 5, 8: 11, 9: 12, 10: 3, 11: 2, 12: 9, 13: 4, 14: 7, 15: 23, 16: 25, 17: 21, 18: 24, 19: 20, 20: 22, 21: 16, 22: 10, 23: 18, 24: 13}, 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 9, 1: 17, 2: 15, 3: 13, 4: 8, 5: 1, 6: 4, 7: 6, 8: 11, 9: 18, 10: 3, 11: 2, 12: 10, 13: 5, 14: 7, 15: 20, 16: 25, 17: 23, 18: 24, 19: 19, 20: 22, 21: 21, 22: 14, 23: 16, 24: 12}, 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F': {0: 7, 1: 14, 2: 13, 3: 12, 4: 3, 5: 1, 6: 2, 7: 18, 8: 5, 9: 20, 10: 25, 11: 24, 12: 22, 13: 8, 14: 15, 15: 23, 16: 17, 17: 10, 18: 11, 19: 9, 20: 6, 21: 4, 22: 16, 23: 21, 24: 19}, 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 5, 1: 8, 2: 17, 3: 19, 4: 12, 5: 2, 6: 1, 7: 9, 8: 16, 9: 21, 10: 3, 11: 4, 12: 7, 13: 6, 14: 10, 15: 25, 16: 24, 17: 22, 18: 23, 19: 20, 20: 15, 21: 13, 22: 14, 23: 18, 24: 11}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 27, 1: 23, 2: 20, 3: 4, 4: 26, 5: 31, 6: 22, 7: 25, 8: 29, 9: 30, 10: 24, 11: 18, 12: 33, 13: 32, 14: 28, 15: 1, 16: 2, 17: 3, 18: 13, 19: 21, 20: 16, 21: 15, 22: 11, 23: 10, 24: 12, 25: 9, 26: 19, 27: 17, 28: 8, 29: 6, 30: 5, 31: 34, 32: 7, 33: 14}, 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN': {0: 9, 1: 8, 2: 4, 3: 6, 4: 7, 5: 1, 6: 3, 7: 16, 8: 18, 9: 12, 10: 15, 11: 17, 12: 13, 13: 10, 14: 14, 15: 11, 16: 5, 17: 2}, 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 20, 1: 18, 2: 13, 3: 14, 4: 9, 5: 10, 6: 16, 7: 21, 8: 11, 9: 4, 10: 1, 11: 2, 12: 5, 13: 6, 14: 19, 15: 23, 16: 22, 17: 17, 18: 3, 19: 12, 20: 7, 21: 8, 22: 15}, 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1': {0: 12, 1: 1, 2: 6, 3: 17, 4: 30, 5: 26, 6: 4, 7: 5, 8: 7, 9: 18, 10: 3, 11: 2, 12: 29, 13: 24, 14: 25, 15: 27, 16: 21, 17: 13, 18: 16, 19: 14, 20: 8, 21: 20, 22: 10, 23: 9, 24: 11, 25: 15, 26: 31, 27: 23, 28: 22, 29: 19, 30: 28}, 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 13, 1: 6, 2: 7, 3: 11, 4: 24, 5: 19, 6: 3, 7: 2, 8: 22, 9: 26, 10: 12, 11: 17, 12: 28, 13: 14, 14: 16, 15: 21, 16: 27, 17: 29, 18: 20, 19: 23, 20: 15, 21: 8, 22: 9, 23: 25, 24: 1, 25: 10, 26: 4, 27: 5, 28: 18}, 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C': {0: 11, 1: 13, 2: 12, 3: 17, 4: 14, 5: 8, 6: 6, 7: 10, 8: 5, 9: 9, 10: 16, 11: 7, 12: 15, 13: 4, 14: 1, 15: 2, 16: 3}, 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C': {0: 10, 1: 11, 2: 8, 3: 16, 4: 12, 5: 14, 6: 9, 7: 6, 8: 4, 9: 15, 10: 7, 11: 13, 12: 5, 13: 1, 14: 3, 15: 2}, 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C': {0: 15, 1: 11, 2: 12, 3: 3, 4: 6, 5: 8, 6: 4, 7: 9, 8: 14, 9: 13, 10: 10, 11: 7, 12: 5, 13: 1, 14: 2}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 2, 1: 1, 2: 3, 3: 4, 4: 21, 5: 18, 6: 10, 7: 22, 8: 9, 9: 8, 10: 23, 11: 5, 12: 15, 13: 6, 14: 19, 15: 17, 16: 24, 17: 13, 18: 16, 19: 11, 20: 7, 21: 12, 22: 14, 23: 20}, 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 1, 2: 2, 3: 4, 4: 23, 5: 17, 6: 12, 7: 19, 8: 9, 9: 10, 10: 20, 11: 7, 12: 6, 13: 11, 14: 24, 15: 13, 16: 22, 17: 18, 18: 14, 19: 16, 20: 15, 21: 5, 22: 8, 23: 21}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 3, 1: 1, 2: 2, 3: 8, 4: 18, 5: 19, 6: 16, 7: 11, 8: 20, 9: 14, 10: 6, 11: 4, 12: 12, 13: 7, 14: 5, 15: 9, 16: 13, 17: 15, 18: 10, 19: 17, 20: 21}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 3, 1: 1, 2: 2, 3: 6, 4: 14, 5: 20, 6: 13, 7: 10, 8: 18, 9: 12, 10: 15, 11: 16, 12: 7, 13: 4, 14: 8, 15: 9, 16: 11, 17: 5, 18: 17, 19: 19}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 8, 1: 3, 2: 4, 3: 9, 4: 11, 5: 2, 6: 7, 7: 6, 8: 18, 9: 13, 10: 12, 11: 5, 12: 1, 13: 10, 14: 16, 15: 14, 16: 20, 17: 22, 18: 17, 19: 21, 20: 15, 21: 19}, 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1': {0: 2, 1: 1, 2: 3, 3: 7, 4: 15, 5: 12, 6: 9, 7: 26, 8: 21, 9: 28, 10: 22, 11: 25, 12: 27, 13: 8, 14: 5, 15: 23, 16: 24, 17: 16, 18: 4, 19: 20, 20: 14, 21: 19, 22: 17, 23: 6, 24: 11, 25: 10, 26: 18, 27: 13}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 4, 1: 1, 2: 11, 3: 22, 4: 32, 5: 29, 6: 14, 7: 6, 8: 20, 9: 23, 10: 26, 11: 27, 12: 5, 13: 2, 14: 8, 15: 3, 16: 18, 17: 9, 18: 17, 19: 31, 20: 12, 21: 24, 22: 10, 23: 16, 24: 19, 25: 13, 26: 7, 27: 30, 28: 21, 29: 15, 30: 28, 31: 25}, 'CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@](O)(c2cc(F)ccc2F)[C@@H](C)c2nc(-c3ccc(C#N)cc3)cs2)c1': {0: 10, 1: 7, 2: 13, 3: 21, 4: 49, 5: 11, 6: 31, 7: 50, 8: 48, 9: 44, 10: 46, 11: 43, 12: 33, 13: 15, 14: 23, 15: 4, 16: 30, 17: 3, 18: 5, 19: 40, 20: 22, 21: 14, 22: 38, 23: 12, 24: 2, 25: 1, 26: 41, 27: 42, 28: 25, 29: 17, 30: 20, 31: 16, 32: 36, 33: 39, 34: 9, 35: 37, 36: 26, 37: 24, 38: 45, 39: 51, 40: 32, 41: 27, 42: 35, 43: 6, 44: 8, 45: 29, 46: 28, 47: 18, 48: 19, 49: 47, 50: 34}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 2, 1: 1, 2: 3, 3: 17, 4: 19, 5: 13, 6: 16, 7: 8, 8: 10, 9: 21, 10: 14, 11: 15, 12: 9, 13: 20, 14: 18, 15: 23, 16: 7, 17: 6, 18: 4, 19: 5, 20: 12, 21: 11, 22: 22}, 'CNCCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 2, 1: 1, 2: 3, 3: 14, 4: 19, 5: 15, 6: 17, 7: 5, 8: 7, 9: 22, 10: 10, 11: 6, 12: 8, 13: 21, 14: 13, 15: 23, 16: 11, 17: 4, 18: 16, 19: 18, 20: 12, 21: 9, 22: 20}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 20, 1: 15, 2: 19, 3: 14, 4: 5, 5: 3, 6: 21, 7: 22, 8: 6, 9: 8, 10: 10, 11: 30, 12: 12, 13: 7, 14: 29, 15: 9, 16: 16, 17: 32, 18: 31, 19: 26, 20: 2, 21: 1, 22: 11, 23: 4, 24: 13, 25: 27, 26: 34, 27: 23, 28: 33, 29: 18, 30: 17, 31: 24, 32: 28, 33: 25, 34: 35}, 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1': {0: 3, 1: 6, 2: 25, 3: 24, 4: 11, 5: 21, 6: 27, 7: 15, 8: 5, 9: 10, 10: 28, 11: 26, 12: 13, 13: 4, 14: 23, 15: 20, 16: 1, 17: 2, 18: 17, 19: 22, 20: 18, 21: 9, 22: 12, 23: 7, 24: 14, 25: 29, 26: 19, 27: 8, 28: 16}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 7, 1: 3, 2: 27, 3: 20, 4: 31, 5: 2, 6: 29, 7: 25, 8: 16, 9: 24, 10: 28, 11: 26, 12: 36, 13: 23, 14: 13, 15: 1, 16: 6, 17: 14, 18: 19, 19: 12, 20: 9, 21: 5, 22: 8, 23: 4, 24: 15, 25: 10, 26: 33, 27: 32, 28: 21, 29: 30, 30: 35, 31: 18, 32: 17, 33: 34, 34: 22, 35: 11}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 4, 1: 6, 2: 11, 3: 23, 4: 19, 5: 13, 6: 10, 7: 16, 8: 9, 9: 1, 10: 14, 11: 15, 12: 5, 13: 20, 14: 25, 15: 27, 16: 17, 17: 26, 18: 30, 19: 33, 20: 24, 21: 18, 22: 29, 23: 31, 24: 12, 25: 2, 26: 3, 27: 7, 28: 22, 29: 21, 30: 32, 31: 28, 32: 8}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1[C@@H](NC(C)=O)CC2': {0: 2, 1: 4, 2: 11, 3: 13, 4: 14, 5: 15, 6: 12, 7: 23, 8: 21, 9: 24, 10: 19, 11: 27, 12: 6, 13: 16, 14: 26, 15: 5, 16: 18, 17: 8, 18: 1, 19: 7, 20: 25, 21: 28, 22: 10, 23: 17, 24: 20, 25: 22, 26: 29, 27: 9, 28: 3}, 'COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2': {0: 13, 1: 17, 2: 20, 3: 16, 4: 15, 5: 18, 6: 14, 7: 12, 8: 5, 9: 4, 10: 10, 11: 3, 12: 1, 13: 2, 14: 11, 15: 23, 16: 22, 17: 19, 18: 21, 19: 8, 20: 6, 21: 9, 22: 7}, 'COc1ccc(C[C@@H](C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 6, 1: 7, 2: 16, 3: 22, 4: 21, 5: 26, 6: 17, 7: 19, 8: 15, 9: 14, 10: 25, 11: 8, 12: 4, 13: 12, 14: 23, 15: 13, 16: 24, 17: 11, 18: 10, 19: 5, 20: 20, 21: 18, 22: 1, 23: 9, 24: 3, 25: 2}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 12, 1: 17, 2: 21, 3: 11, 4: 6, 5: 23, 6: 9, 7: 20, 8: 1, 9: 2, 10: 16, 11: 22, 12: 13, 13: 8, 14: 7, 15: 5, 16: 19, 17: 4, 18: 3, 19: 14, 20: 15, 21: 10, 22: 24, 23: 18}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)CC3': {0: 19, 1: 15, 2: 14, 3: 13, 4: 16, 5: 12, 6: 17, 7: 23, 8: 20, 9: 21, 10: 10, 11: 3, 12: 6, 13: 28, 14: 29, 15: 4, 16: 7, 17: 24, 18: 18, 19: 25, 20: 11, 21: 9, 22: 8, 23: 5, 24: 22, 25: 2, 26: 1, 27: 26, 28: 27}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 25, 1: 27, 2: 24, 3: 13, 4: 9, 5: 7, 6: 5, 7: 11, 8: 12, 9: 15, 10: 18, 11: 26, 12: 19, 13: 38, 14: 39, 15: 6, 16: 4, 17: 33, 18: 22, 19: 14, 20: 30, 21: 29, 22: 28, 23: 3, 24: 17, 25: 2, 26: 1, 27: 16, 28: 20, 29: 8, 30: 10, 31: 21, 32: 37, 33: 31, 34: 32, 35: 23, 36: 34, 37: 36, 38: 35}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3': {0: 18, 1: 22, 2: 25, 3: 20, 4: 10, 5: 11, 6: 13, 7: 17, 8: 16, 9: 26, 10: 23, 11: 5, 12: 6, 13: 27, 14: 29, 15: 7, 16: 9, 17: 15, 18: 21, 19: 14, 20: 24, 21: 12, 22: 8, 23: 3, 24: 4, 25: 2, 26: 1, 27: 19, 28: 28}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 19, 1: 22, 2: 26, 3: 14, 4: 6, 5: 16, 6: 13, 7: 21, 8: 5, 9: 10, 10: 12, 11: 7, 12: 17, 13: 37, 14: 38, 15: 11, 16: 20, 17: 23, 18: 27, 19: 24, 20: 34, 21: 28, 22: 29, 23: 3, 24: 4, 25: 1, 26: 2, 27: 31, 28: 15, 29: 8, 30: 18, 31: 32, 32: 33, 33: 9, 34: 30, 35: 25, 36: 35, 37: 39, 38: 36}, 'COc1nc(N)nc2[nH]cnc12': {0: 1, 1: 2, 2: 4, 3: 7, 4: 11, 5: 6, 6: 10, 7: 9, 8: 12, 9: 5, 10: 8, 11: 3}, 'COc1nc(N)nc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O': {0: 1, 1: 2, 2: 6, 3: 16, 4: 19, 5: 17, 6: 13, 7: 14, 8: 18, 9: 11, 10: 12, 11: 10, 12: 7, 13: 20, 14: 21, 15: 9, 16: 5, 17: 15, 18: 8, 19: 4, 20: 3}, 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12': {0: 6, 1: 7, 2: 10, 3: 14, 4: 33, 5: 30, 6: 24, 7: 27, 8: 12, 9: 13, 10: 25, 11: 11, 12: 15, 13: 8, 14: 35, 15: 29, 16: 34, 17: 31, 18: 32, 19: 28, 20: 5, 21: 4, 22: 16, 23: 9, 24: 1, 25: 2, 26: 3, 27: 18, 28: 20, 29: 17, 30: 26, 31: 37, 32: 19, 33: 23, 34: 22, 35: 21, 36: 36}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 1, 1: 4, 2: 11, 3: 16, 4: 3, 5: 12, 6: 2, 7: 5, 8: 14, 9: 23, 10: 9, 11: 10, 12: 15, 13: 20, 14: 8, 15: 17, 16: 6, 17: 7, 18: 22, 19: 13, 20: 18, 21: 19, 22: 21}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 17, 1: 1, 2: 5, 3: 2, 4: 26, 5: 21, 6: 18, 7: 27, 8: 6, 9: 14, 10: 7, 11: 15, 12: 12, 13: 3, 14: 4, 15: 22, 16: 19, 17: 28, 18: 24, 19: 10, 20: 8, 21: 9, 22: 11, 23: 13, 24: 16, 25: 23, 26: 20, 27: 25}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 17, 1: 1, 2: 5, 3: 4, 4: 23, 5: 19, 6: 24, 7: 28, 8: 8, 9: 22, 10: 9, 11: 12, 12: 14, 13: 18, 14: 21, 15: 20, 16: 27, 17: 25, 18: 15, 19: 6, 20: 2, 21: 3, 22: 7, 23: 10, 24: 11, 25: 26, 26: 13, 27: 16}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 15, 1: 1, 2: 2, 3: 4, 4: 14, 5: 20, 6: 22, 7: 24, 8: 3, 9: 11, 10: 5, 11: 12, 12: 17, 13: 13, 14: 21, 15: 16, 16: 25, 17: 18, 18: 8, 19: 7, 20: 6, 21: 9, 22: 10, 23: 19, 24: 26, 25: 23, 26: 27}, 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12': {0: 17, 1: 1, 2: 2, 3: 8, 4: 28, 5: 26, 6: 12, 7: 19, 8: 32, 9: 33, 10: 31, 11: 9, 12: 3, 13: 21, 14: 24, 15: 30, 16: 20, 17: 14, 18: 27, 19: 7, 20: 15, 21: 10, 22: 13, 23: 5, 24: 4, 25: 6, 26: 23, 27: 16, 28: 11, 29: 22, 30: 29, 31: 25, 32: 18}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)O': {0: 14, 1: 30, 2: 18, 3: 19, 4: 26, 5: 11, 6: 7, 7: 6, 8: 29, 9: 25, 10: 8, 11: 9, 12: 22, 13: 23, 14: 35, 15: 27, 16: 32, 17: 28, 18: 2, 19: 1, 20: 13, 21: 31, 22: 21, 23: 10, 24: 5, 25: 4, 26: 34, 27: 17, 28: 20, 29: 15, 30: 3, 31: 16, 32: 12, 33: 33, 34: 24}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)SCF': {0: 12, 1: 26, 2: 24, 3: 17, 4: 27, 5: 15, 6: 4, 7: 3, 8: 36, 9: 25, 10: 5, 11: 10, 12: 20, 13: 37, 14: 34, 15: 33, 16: 28, 17: 31, 18: 2, 19: 1, 20: 19, 21: 23, 22: 13, 23: 14, 24: 11, 25: 9, 26: 21, 27: 30, 28: 16, 29: 18, 30: 6, 31: 22, 32: 7, 33: 29, 34: 8, 35: 32, 36: 35}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 22, 1: 20, 2: 10, 3: 19, 4: 6, 5: 18, 6: 7, 7: 26, 8: 14, 9: 13, 10: 28, 11: 16, 12: 2, 13: 5, 14: 1, 15: 3, 16: 8, 17: 11, 18: 15, 19: 23, 20: 24, 21: 21, 22: 12, 23: 27, 24: 9, 25: 4, 26: 25, 27: 17}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 18, 1: 12, 2: 16, 3: 24, 4: 9, 5: 19, 6: 5, 7: 22, 8: 15, 9: 10, 10: 27, 11: 26, 12: 3, 13: 1, 14: 2, 15: 11, 16: 13, 17: 8, 18: 21, 19: 17, 20: 20, 21: 28, 22: 23, 23: 25, 24: 6, 25: 4, 26: 14, 27: 7}, 'C[C@H](N)Cc1ccc(O)cc1': {0: 4, 1: 2, 2: 1, 3: 8, 4: 9, 5: 11, 6: 5, 7: 7, 8: 3, 9: 6, 10: 10}, 'C[C@H](N)Cc1ccccc1': {0: 3, 1: 2, 2: 1, 3: 4, 4: 10, 5: 5, 6: 9, 7: 7, 8: 8, 9: 6}, 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O': {0: 12, 1: 13, 2: 14, 3: 7, 4: 3, 5: 8, 6: 1, 7: 2, 8: 11, 9: 4, 10: 15, 11: 17, 12: 16, 13: 5, 14: 6, 15: 10, 16: 9}, 'C[C@H]1[C@@H](O)O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@]24OO3': {0: 4, 1: 10, 2: 9, 3: 16, 4: 18, 5: 19, 6: 20, 7: 2, 8: 1, 9: 12, 10: 5, 11: 17, 12: 3, 13: 7, 14: 6, 15: 14, 16: 15, 17: 8, 18: 11, 19: 13}, 'C[C@]12CC[C@H](O)CC1=CC[C@@H]1[C@@H]2CC[C@]2(C)C(c3cccnc3)=CC[C@@H]12': {0: 20, 1: 22, 2: 21, 3: 17, 4: 25, 5: 16, 6: 1, 7: 15, 8: 23, 9: 18, 10: 10, 11: 9, 12: 14, 13: 19, 14: 24, 15: 26, 16: 12, 17: 4, 18: 11, 19: 13, 20: 7, 21: 5, 22: 8, 23: 2, 24: 6, 25: 3}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 21, 1: 20, 2: 28, 3: 17, 4: 27, 5: 7, 6: 25, 7: 19, 8: 23, 9: 18, 10: 6, 11: 34, 12: 16, 13: 13, 14: 1, 15: 2, 16: 11, 17: 22, 18: 26, 19: 24, 20: 30, 21: 35, 22: 33, 23: 32, 24: 29, 25: 31, 26: 10, 27: 15, 28: 9, 29: 8, 30: 3, 31: 4, 32: 12, 33: 5, 34: 14}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1': {0: 11, 1: 37, 2: 9, 3: 4, 4: 6, 5: 34, 6: 26, 7: 31, 8: 22, 9: 8, 10: 15, 11: 10, 12: 25, 13: 7, 14: 1, 15: 2, 16: 30, 17: 21, 18: 38, 19: 32, 20: 24, 21: 13, 22: 3, 23: 5, 24: 33, 25: 36, 26: 35, 27: 29, 28: 23, 29: 28, 30: 18, 31: 20, 32: 17, 33: 14, 34: 12, 35: 19, 36: 27, 37: 16}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@+](O)c1nc2c(OS(=O)(=O)O)cccc2[nH]1': {0: 21, 1: 23, 2: 7, 3: 3, 4: 5, 5: 29, 6: 24, 7: 26, 8: 25, 9: 13, 10: 12, 11: 18, 12: 27, 13: 6, 14: 2, 15: 8, 16: 17, 17: 16, 18: 19, 19: 10, 20: 1, 21: 4, 22: 30, 23: 22, 24: 28, 25: 9, 26: 14, 27: 15, 28: 20, 29: 11}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1': {0: 25, 1: 23, 2: 12, 3: 4, 4: 5, 5: 13, 6: 11, 7: 17, 8: 16, 9: 14, 10: 19, 11: 20, 12: 22, 13: 8, 14: 1, 15: 2, 16: 9, 17: 7, 18: 24, 19: 18, 20: 10, 21: 6, 22: 3, 23: 21, 24: 26, 25: 15}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1': {0: 22, 1: 25, 2: 6, 3: 3, 4: 4, 5: 12, 6: 20, 7: 19, 8: 21, 9: 10, 10: 17, 11: 7, 12: 15, 13: 5, 14: 1, 15: 2, 16: 16, 17: 9, 18: 24, 19: 8, 20: 18, 21: 13, 22: 11, 23: 23, 24: 14}, 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1': {0: 21, 1: 28, 2: 33, 3: 22, 4: 6, 5: 19, 6: 23, 7: 29, 8: 25, 9: 8, 10: 20, 11: 13, 12: 31, 13: 15, 14: 9, 15: 3, 16: 17, 17: 16, 18: 27, 19: 18, 20: 32, 21: 5, 22: 26, 23: 10, 24: 4, 25: 12, 26: 24, 27: 11, 28: 2, 29: 1, 30: 14, 31: 7, 32: 30}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2': {0: 16, 1: 8, 2: 4, 3: 5, 4: 2, 5: 1, 6: 20, 7: 11, 8: 13, 9: 23, 10: 21, 11: 17, 12: 15, 13: 18, 14: 22, 15: 9, 16: 6, 17: 10, 18: 12, 19: 14, 20: 19, 21: 3, 22: 7}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O': {0: 6, 1: 9, 2: 8, 3: 12, 4: 4, 5: 5, 6: 21, 7: 20, 8: 17, 9: 16, 10: 14, 11: 24, 12: 15, 13: 13, 14: 19, 15: 10, 16: 7, 17: 11, 18: 18, 19: 22, 20: 23, 21: 3, 22: 1, 23: 2}, 'Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2': {0: 13, 1: 20, 2: 16, 3: 12, 4: 10, 5: 17, 6: 15, 7: 8, 8: 6, 9: 1, 10: 4, 11: 9, 12: 3, 13: 7, 14: 5, 15: 22, 16: 18, 17: 14, 18: 11, 19: 19, 20: 21, 21: 2}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N(CC(=O)O)CC(=O)O)cc3)n2)cc1': {0: 5, 1: 6, 2: 12, 3: 16, 4: 10, 5: 18, 6: 33, 7: 26, 8: 27, 9: 34, 10: 29, 11: 13, 12: 17, 13: 21, 14: 24, 15: 7, 16: 15, 17: 11, 18: 14, 19: 4, 20: 1, 21: 2, 22: 23, 23: 28, 24: 31, 25: 3, 26: 19, 27: 30, 28: 32, 29: 9, 30: 8, 31: 20, 32: 25, 33: 22}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1': {0: 4, 1: 9, 2: 19, 3: 17, 4: 21, 5: 26, 6: 31, 7: 30, 8: 27, 9: 28, 10: 25, 11: 12, 12: 2, 13: 11, 14: 16, 15: 1, 16: 20, 17: 15, 18: 10, 19: 14, 20: 6, 21: 7, 22: 5, 23: 23, 24: 8, 25: 3, 26: 13, 2

In [129]:
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [130]:
import pickle
with open('dict_sub2site.pickle', 'rb') as file:
    dict_sub2site = pickle.load(file)

In [131]:
df_total = pd.read_csv('123_site_from_smiles.csv')
subs = df_total['substrate'].to_list()
subs = list(map(canonicalsmiles,subs))
metas = df_total['metabolite'].to_list()
atomidxs = [dict_sub2site[i] for i in subs]
# sites = df_total['site_truth'].to_list()
# sites = [i.split('|') for i in sites]
# atomidxs = list(map(get_reactive_atom_indices,sites))
df_total['substrate'] = subs
df_total['sites'] = atomidxs
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]"
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19]
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]"
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10]
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39]
...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]"
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]"
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]"
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26]
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11]

In [132]:
# df_new = pd.DataFrame()
# df_new['substrates'] = list(dict_sub2site.keys())
# df_new['true_sites'] = [dict_sub2site[i] for i in list(dict_sub2site.keys())]
df_total['gnn_results'] = [result_new.get(i,'None') for i in subs]
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40..."
...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ..."
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7..."

In [133]:
df_total.to_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')

2. smartcyp

In [134]:
df = pd.read_pickle('smartcyp_results_drugbank.pickle')
df

,substrates,enzyme,scores
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,3A4,"{0: 3, 1: 21, 2: 10, 3: 1, 4: 20, 5: 17, 6: 16..."
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2D6,"{0: 6, 1: 21, 2: 13, 3: 3, 4: 20, 5: 17, 6: 16..."
2,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2C9,"{0: 5, 1: 18, 2: 9, 3: 2, 4: 17, 5: 15, 6: 14,..."
3,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,3A4,"{0: 3, 1: 14, 2: 13, 3: 11, 4: 18, 5: 5, 6: 10..."
4,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,2D6,"{0: 2, 1: 14, 2: 13, 3: 9, 4: 18, 5: 7, 6: 10,..."
...,...,...,...
364,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2D6,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 4, 6: 19..."
365,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2C9,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 3, 6: 19..."
366,c1cnc(N2CCNCC2)nc1,3A4,"{0: 6, 1: 7, 2: 5, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."
367,c1cnc(N2CCNCC2)nc1,2D6,"{0: 1, 1: 5, 2: 4, 3: 8, 4: 7, 5: 2, 6: 6, 7: ..."
368,c1cnc(N2CCNCC2)nc1,2C9,"{0: 5, 1: 7, 2: 6, 3: 8, 4: 4, 5: 1, 6: 3, 7: ..."

In [135]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O': {0: 14, 1: 60, 2: 32, 3: 6, 4: 57, 5: 49, 6: 46, 7: 26, 8: 12, 9: 6, 10: 15, 11: 52, 12: 29, 13: 29, 14: 32, 15: 30, 16: 33, 17: 59, 18: 12, 19: 26, 20: 50, 21: 50, 22: 47}, 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 7, 1: 42, 2: 39, 3: 29, 4: 54, 5: 19, 6: 30, 7: 60, 8: 66, 9: 29, 10: 63, 11: 57, 12: 22, 13: 18, 14: 11, 15: 21, 16: 51, 18: 9, 19: 3, 20: 48, 21: 45, 22: 36}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 4, 1: 49, 2: 45, 3: 34, 4: 58, 5: 23, 6: 34, 7: 21, 8: 76, 9: 96, 10: 75, 11: 84, 12: 93, 13: 30, 14: 27, 15: 27, 16: 78, 17: 81, 18: 86, 19: 81, 20: 16, 21: 61, 22: 29, 23: 13, 24: 50, 26: 16, 27: 54, 29: 78, 30: 18, 31: 70, 32: 75, 33: 78, 34: 9, 35: 88, 36: 41}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 16, 1: 39, 2: 16, 3: 16, 4: 45, 5: 29, 6: 71, 7: 57, 8: 26, 9: 26, 10: 26, 11: 69, 12: 33, 13: 67, 14: 72, 15: 66, 16: 36, 17: 17, 18: 42, 19: 17, 20: 11, 21: 6, 22: 18, 23: 48, 24: 60, 25: 54, 26: 22, 27: 51, 28: 3}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 22, 1: 62, 2: 22, 3: 22, 4: 70, 5: 26, 6: 78, 7: 45, 8: 83, 9: 88, 10: 48, 11: 87, 12: 41, 13: 33, 14: 91, 15: 89, 16: 27, 17: 48, 18: 80, 19: 45, 20: 18, 21: 87, 22: 37, 23: 85, 24: 87, 25: 29, 26: 16, 27: 19, 28: 5, 29: 16, 30: 71, 31: 16, 32: 5, 33: 34, 34: 19, 35: 83, 36: 33, 37: 41, 38: 42, 39: 74}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 19, 1: 47, 2: 19, 3: 13, 4: 54, 5: 51, 6: 38, 7: 29, 8: 33, 9: 34, 10: 9, 11: 13, 12: 18, 13: 6, 14: 20, 15: 57, 16: 22, 17: 19, 18: 46, 19: 42, 20: 19, 21: 22, 22: 6, 23: 18, 24: 54, 25: 51, 26: 13}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 21, 1: 45, 2: 21, 3: 17, 4: 53, 5: 48, 6: 41, 7: 30, 8: 34, 9: 35, 10: 11, 11: 14, 12: 19, 13: 6, 14: 23, 15: 52, 16: 17, 17: 29, 18: 18, 19: 29, 20: 17, 21: 6, 22: 19, 23: 53, 24: 48, 25: 17}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 25, 1: 51, 2: 25, 3: 20, 4: 59, 5: 54, 6: 44, 7: 34, 8: 36, 9: 38, 10: 12, 11: 15, 12: 21, 13: 7, 14: 25, 15: 59, 16: 20, 17: 32, 18: 21, 19: 32, 20: 20, 21: 7, 22: 21, 23: 62, 24: 54, 25: 10, 26: 48}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O': {0: 5, 1: 47, 2: 55, 3: 28, 4: 28, 5: 58, 6: 13, 7: 29, 8: 27, 9: 29, 10: 57, 11: 12, 12: 23, 13: 48, 14: 48, 15: 45, 16: 50, 17: 24, 18: 24, 19: 12, 20: 4, 21: 44, 22: 39}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 3, 1: 46, 2: 54, 3: 31, 4: 31, 5: 57, 6: 15, 7: 32, 8: 30, 9: 32, 10: 56, 11: 14, 12: 26, 13: 49, 14: 49, 15: 46, 16: 49, 17: 27, 18: 27, 19: 15, 20: 11, 21: 6}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 27, 1: 17, 2: 69, 3: 66, 4: 48, 5: 29, 6: 32, 7: 9, 8: 12, 9: 82, 10: 41, 11: 54, 12: 38, 13: 76, 14: 79, 15: 6, 16: 21, 17: 81, 18: 51, 19: 21, 20: 60, 21: 57, 22: 72, 23: 63, 27: 45, 28: 3, 29: 24, 30: 35}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 29, 1: 20, 2: 66, 3: 60, 4: 49, 5: 29, 6: 35, 7: 10, 8: 14, 9: 79, 10: 44, 11: 55, 12: 41, 13: 76, 14: 82, 15: 9, 16: 22, 17: 81, 18: 56, 19: 32, 20: 63, 21: 60, 22: 7, 23: 72, 24: 69, 28: 50, 29: 5, 30: 25, 31: 38}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 49, 1: 34, 2: 50, 3: 63, 4: 80, 5: 75, 6: 28, 7: 84, 8: 108, 9: 73, 10: 24, 11: 111, 12: 37, 13: 15, 14: 19, 15: 38, 16: 109, 17: 13, 18: 52, 19: 105, 20: 117, 21: 26, 22: 29, 23: 23, 24: 109, 25: 106, 26: 33, 27: 72, 28: 3, 29: 57, 30: 21, 31: 63, 32: 103, 33: 60, 34: 47, 35: 87, 37: 50, 38: 90, 40: 113, 41: 52, 42: 13, 43: 19, 44: 15, 45: 24, 46: 73, 47: 104, 48: 103}, 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 31, 1: 13, 2: 24, 3: 31, 4: 26, 5: 59, 6: 60, 7: 42, 8: 4, 9: 15, 10: 20, 11: 64, 12: 9, 13: 59, 14: 64, 15: 12, 16: 41, 17: 40, 18: 40, 19: 40, 20: 37, 21: 21, 22: 59, 23: 58, 24: 56}, 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 31, 1: 10, 2: 23, 3: 28, 4: 8, 5: 59, 6: 60, 7: 11, 8: 39, 9: 42, 10: 20, 11: 64, 12: 8, 13: 59, 14: 64, 15: 15, 16: 39, 17: 38, 18: 38, 19: 38, 20: 35, 21: 21, 22: 59, 23: 58, 24: 56}, 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F': {0: 21, 1: 10, 2: 18, 3: 22, 4: 27, 5: 59, 6: 56, 7: 59, 8: 36, 9: 63, 10: 31, 11: 59, 12: 61, 13: 62, 14: 19, 15: 48, 16: 4, 17: 26, 18: 7, 19: 42, 20: 13, 21: 45, 22: 39, 23: 60}, 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 30, 1: 12, 2: 22, 3: 36, 4: 42, 5: 16, 6: 63, 7: 23, 8: 26, 9: 29, 10: 15, 11: 66, 12: 6, 13: 63, 14: 66, 15: 9, 16: 48, 17: 47, 18: 46, 19: 45, 20: 40, 21: 21, 22: 63, 23: 62, 24: 60}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 25, 1: 16, 2: 10, 3: 66, 4: 36, 5: 60, 6: 7, 7: 63, 8: 72, 9: 69, 10: 28, 11: 77, 12: 86, 13: 47, 14: 87, 15: 90, 16: 85, 17: 85, 18: 57, 19: 41, 20: 18, 21: 20, 22: 8, 23: 41, 24: 18, 25: 41, 26: 44, 27: 38, 28: 80, 29: 77, 30: 19, 31: 38, 32: 31, 33: 46}, 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN': {0: 15, 1: 9, 2: 28, 3: 9, 4: 15, 5: 36, 6: 33, 7: 42, 8: 39, 9: 25, 10: 18, 11: 11, 12: 18, 13: 25, 14: 20, 15: 23, 16: 6, 17: 10}, 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 29, 1: 5, 2: 18, 3: 11, 4: 30, 5: 39, 6: 24, 7: 21, 8: 10, 9: 45, 10: 7, 11: 60, 12: 56, 13: 56, 14: 61, 15: 57, 16: 29, 17: 51, 18: 47, 19: 25, 20: 43, 21: 43, 22: 25}, 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1': {0: 31, 1: 18, 2: 73, 3: 30, 4: 36, 5: 11, 6: 48, 7: 15, 8: 79, 9: 73, 10: 66, 11: 14, 12: 26, 13: 58, 14: 13, 15: 62, 16: 70, 17: 16, 18: 6, 19: 53, 20: 21, 21: 81, 22: 45, 23: 39, 24: 71, 25: 64, 26: 64, 27: 60, 28: 39, 29: 45, 30: 39}, 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 28, 1: 12, 2: 63, 3: 66, 4: 26, 5: 19, 6: 56, 7: 3, 8: 32, 9: 71, 10: 76, 11: 27, 12: 12, 13: 25, 14: 16, 15: 45, 16: 33, 17: 78, 18: 43, 19: 37, 20: 64, 21: 59, 22: 12, 23: 75, 24: 70, 25: 39, 26: 61, 27: 61, 28: 50}, 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C': {0: 21, 1: 18, 2: 15, 3: 39, 4: 12, 5: 36, 6: 33, 7: 9, 8: 36, 9: 33, 10: 12, 11: 23, 12: 26, 13: 7, 14: 30, 15: 4, 16: 4}, 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C': {0: 27, 1: 22, 2: 18, 3: 45, 4: 13, 5: 20, 6: 9, 7: 42, 8: 39, 9: 18, 10: 28, 11: 32, 12: 7, 13: 36, 14: 4, 15: 4}, 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C': {0: 24, 1: 18, 2: 14, 3: 39, 4: 36, 5: 42, 6: 22, 7: 28, 8: 11, 9: 45, 10: 11, 11: 28, 12: 3, 13: 33, 14: 6}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 33, 2: 3, 3: 7, 4: 17, 5: 23, 6: 58, 7: 53, 8: 25, 9: 17, 10: 42, 12: 17, 13: 25, 14: 59, 15: 8, 16: 48, 17: 20, 18: 45, 19: 39, 20: 36, 21: 17, 22: 28, 23: 52}, 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 33, 2: 3, 3: 7, 4: 17, 5: 23, 6: 58, 7: 53, 8: 25, 9: 17, 10: 42, 12: 17, 13: 25, 14: 59, 15: 8, 16: 48, 17: 20, 18: 45, 19: 39, 20: 36, 21: 17, 22: 28, 23: 52}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 8, 1: 42, 2: 8, 3: 15, 4: 25, 5: 57, 6: 16, 7: 46, 8: 52, 9: 28, 10: 47, 11: 3, 12: 56, 13: 20, 14: 36, 15: 11, 16: 27, 17: 18, 18: 31, 19: 35, 20: 57}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 5, 1: 42, 2: 5, 3: 13, 4: 23, 5: 56, 6: 13, 7: 45, 8: 49, 9: 26, 10: 25, 11: 51, 12: 17, 13: 36, 14: 8, 15: 26, 16: 16, 17: 30, 18: 35, 19: 54}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 3, 1: 21, 2: 36, 3: 30, 4: 8, 5: 48, 6: 45, 7: 27, 8: 54, 9: 23, 10: 11, 11: 33, 12: 30, 13: 11, 14: 23, 15: 51, 16: 18, 17: 39, 19: 8, 20: 16, 21: 42}, 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1': {0: 8, 1: 48, 2: 16, 3: 32, 4: 24, 5: 44, 6: 72, 7: 71, 8: 38, 9: 66, 10: 32, 11: 24, 12: 60, 13: 54, 14: 51, 15: 24, 16: 32, 17: 35, 18: 19, 19: 69, 20: 38, 21: 59, 22: 16, 23: 14, 24: 9, 25: 11, 26: 59, 27: 65}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 3, 1: 16, 2: 49, 3: 46, 4: 54, 5: 16, 6: 62, 7: 71, 8: 68, 9: 19, 10: 31, 11: 72, 12: 37, 13: 68, 14: 73, 15: 37, 16: 68, 17: 24, 18: 17, 19: 45, 21: 56, 22: 48, 26: 27, 27: 31, 28: 19, 29: 12, 30: 28, 31: 6}, 'CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@](O)(c2cc(F)ccc2F)[C@@H](C)c2nc(-c3ccc(C#N)cc3)cs2)c1': {0: 4, 1: 23, 2: 13, 3: 112, 4: 109, 5: 123, 6: 42, 7: 121, 8: 68, 9: 60, 10: 68, 11: 38, 12: 121, 13: 73, 14: 33, 15: 115, 16: 123, 17: 133, 18: 19, 19: 61, 20: 81, 21: 39, 22: 78, 23: 16, 24: 136, 25: 127, 26: 130, 27: 52, 28: 104, 30: 46, 31: 49, 32: 110, 34: 13, 35: 62, 36: 119, 37: 74, 38: 104, 39: 109, 40: 42, 41: 32, 42: 93, 43: 90, 44: 87, 45: 32, 46: 42, 47: 26, 48: 25, 49: 72, 50: 9}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 13, 2: 7, 3: 20, 4: 26, 5: 58, 6: 53, 7: 28, 8: 19, 9: 42, 11: 19, 12: 28, 13: 59, 14: 10, 15: 48, 16: 22, 17: 45, 18: 39, 19: 36, 20: 19, 21: 31, 22: 52}, 'CNCCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 3, 1: 13, 2: 7, 3: 20, 4: 26, 5: 58, 6: 53, 7: 28, 8: 19, 9: 42, 11: 19, 12: 28, 13: 59, 14: 10, 15: 48, 16: 22, 17: 45, 18: 39, 19: 36, 20: 19, 21: 31, 22: 52}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 21, 1: 88, 2: 88, 3: 85, 4: 86, 5: 29, 6: 40, 7: 10, 8: 9, 9: 4, 10: 16, 11: 57, 12: 16, 13: 4, 14: 38, 15: 40, 16: 77, 17: 84, 18: 43, 19: 71, 20: 53, 21: 71, 22: 77, 23: 65, 24: 50, 25: 32, 26: 60, 27: 8, 28: 32, 29: 50, 30: 50, 31: 30, 32: 16, 33: 24, 34: 66}, 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1': {0: 14, 1: 60, 2: 67, 3: 22, 4: 52, 5: 12, 6: 56, 7: 47, 8: 6, 9: 15, 10: 64, 11: 73, 12: 13, 13: 42, 14: 9, 15: 31, 16: 26, 17: 67, 18: 34, 19: 18, 20: 75, 21: 39, 22: 34, 23: 65, 24: 58, 25: 58, 26: 54, 27: 34, 28: 39}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 13, 1: 58, 2: 61, 3: 29, 4: 78, 5: 31, 6: 86, 7: 75, 8: 68, 9: 60, 10: 50, 11: 38, 12: 76, 13: 43, 14: 89, 15: 92, 16: 29, 17: 42, 18: 16, 19: 28, 20: 17, 21: 9, 22: 12, 23: 4, 24: 9, 25: 17, 26: 86, 27: 91, 28: 19, 29: 44, 30: 79, 31: 67, 33: 35, 34: 55}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 8, 1: 63, 2: 67, 3: 16, 4: 67, 5: 63, 6: 8, 7: 34, 8: 79, 9: 58, 10: 32, 11: 14, 12: 24, 13: 8, 14: 42, 15: 42, 16: 84, 17: 33, 18: 46, 19: 75, 20: 34, 21: 51, 22: 74, 23: 68, 24: 28, 25: 41, 26: 11, 27: 37, 28: 24, 29: 39, 30: 78, 31: 50, 32: 34}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1[C@@H](NC(C)=O)CC2': {0: 6, 1: 42, 2: 51, 3: 24, 4: 69, 5: 73, 6: 66, 7: 63, 8: 12, 9: 60, 10: 57, 11: 9, 12: 76, 13: 38, 14: 30, 15: 48, 16: 42, 17: 3, 18: 54, 19: 42, 20: 33, 21: 76, 22: 19, 23: 37, 24: 45, 25: 17, 26: 42, 27: 27, 28: 18}, 'COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2': {0: 6, 1: 48, 2: 51, 3: 34, 4: 63, 5: 66, 6: 40, 7: 57, 8: 54, 9: 12, 10: 14, 11: 38, 12: 22, 13: 60, 14: 33, 15: 25, 16: 18, 17: 26, 18: 26, 19: 10, 20: 45, 21: 9, 22: 28}, 'COc1ccc(C[C@@H](C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 9, 1: 52, 2: 57, 3: 32, 4: 38, 5: 69, 6: 27, 7: 13, 8: 39, 9: 22, 10: 9, 11: 23, 12: 65, 13: 60, 14: 25, 15: 16, 16: 11, 17: 19, 18: 54, 19: 49, 20: 44, 21: 66, 22: 63, 23: 33, 24: 54, 25: 54}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 4, 1: 42, 2: 45, 3: 24, 4: 26, 5: 56, 6: 36, 7: 65, 8: 9, 9: 68, 10: 22, 11: 64, 12: 29, 13: 33, 14: 39, 15: 10, 16: 48, 17: 42, 18: 7, 19: 51, 20: 15, 21: 57, 22: 59, 23: 19}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)CC3': {0: 8, 1: 37, 2: 40, 3: 15, 4: 24, 5: 23, 6: 62, 7: 51, 8: 62, 9: 51, 10: 72, 11: 74, 12: 3, 13: 66, 14: 67, 15: 78, 16: 3, 17: 72, 18: 62, 19: 67, 20: 16, 21: 46, 22: 41, 23: 38, 24: 33, 25: 7, 26: 30, 27: 24, 28: 15}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 16, 1: 60, 2: 68, 3: 35, 4: 33, 5: 34, 6: 68, 7: 80, 8: 87, 9: 79, 10: 96, 11: 98, 12: 7, 13: 101, 14: 96, 15: 96, 16: 4, 17: 92, 18: 75, 19: 67, 20: 34, 21: 87, 22: 73, 23: 70, 24: 63, 25: 17, 26: 56, 27: 47, 28: 36, 29: 94, 30: 22, 31: 40, 32: 13, 33: 23, 34: 25, 35: 68, 36: 29, 37: 44, 38: 83}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3': {0: 7, 1: 39, 2: 42, 3: 18, 4: 27, 5: 26, 6: 62, 7: 51, 8: 62, 9: 51, 10: 72, 11: 74, 12: 3, 13: 66, 14: 67, 15: 78, 16: 3, 17: 72, 18: 62, 19: 67, 20: 19, 21: 46, 22: 41, 23: 12, 24: 36, 25: 8, 26: 33, 27: 27, 28: 18}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 15, 1: 62, 2: 70, 3: 38, 4: 35, 5: 36, 6: 70, 7: 82, 8: 87, 9: 79, 10: 96, 11: 98, 12: 7, 13: 101, 14: 96, 15: 96, 16: 4, 17: 92, 18: 77, 19: 69, 20: 37, 21: 87, 22: 73, 23: 27, 24: 66, 25: 19, 26: 59, 27: 50, 28: 39, 29: 94, 30: 22, 31: 43, 32: 14, 33: 24, 34: 26, 35: 70, 36: 30, 37: 47, 38: 83}, 'COc1nc(N)nc2[nH]cnc12': {0: 9, 1: 33, 2: 36, 3: 15, 4: 27, 5: 3, 6: 12, 7: 24, 8: 30, 9: 18, 10: 6, 11: 21}, 'COc1nc(N)nc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O': {0: 6, 1: 39, 2: 45, 3: 20, 4: 42, 5: 3, 6: 27, 7: 57, 8: 51, 9: 30, 10: 16, 11: 33, 12: 23, 13: 54, 14: 13, 15: 10, 16: 36, 17: 13, 18: 39, 19: 17, 20: 48}, 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12': {0: 7, 1: 77, 2: 81, 3: 29, 4: 66, 5: 15, 6: 17, 7: 63, 9: 34, 10: 72, 11: 56, 12: 92, 13: 26, 14: 86, 15: 53, 16: 48, 17: 39, 18: 48, 19: 53, 20: 93, 21: 87, 22: 42, 23: 17, 24: 60, 25: 7, 26: 7, 27: 92, 28: 46, 29: 33, 30: 27, 31: 69, 32: 27, 33: 14, 34: 24, 35: 36, 36: 76}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 8, 1: 39, 2: 48, 3: 29, 4: 36, 5: 60, 6: 22, 7: 7, 8: 20, 9: 42, 10: 20, 11: 28, 12: 17, 13: 45, 14: 5, 15: 54, 16: 10, 17: 32, 18: 57, 19: 51}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 6, 1: 45, 2: 42, 3: 42, 4: 48, 5: 28, 6: 30, 7: 68, 8: 64, 9: 73, 10: 39, 11: 69, 12: 23, 13: 57, 14: 3, 15: 54, 17: 69, 18: 51, 19: 25, 20: 20, 21: 13, 22: 24, 23: 11, 24: 20, 25: 62, 27: 31}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 3, 1: 45, 2: 39, 3: 39, 4: 48, 5: 18, 6: 23, 7: 64, 8: 57, 9: 70, 10: 36, 11: 66, 12: 22, 13: 32, 14: 56, 16: 67, 17: 53, 18: 25, 19: 10, 20: 42, 21: 39, 22: 7, 23: 10, 24: 27, 25: 59, 27: 21}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 3, 1: 45, 2: 42, 3: 42, 4: 48, 5: 21, 6: 23, 7: 67, 8: 61, 9: 70, 10: 39, 11: 64, 12: 22, 13: 33, 14: 54, 16: 64, 17: 51, 18: 23, 19: 18, 20: 10, 21: 22, 22: 8, 23: 27, 24: 61, 26: 24}, 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12': {0: 27, 1: 12, 2: 57, 3: 24, 4: 66, 5: 62, 6: 48, 7: 81, 8: 75, 9: 71, 10: 71, 11: 85, 12: 9, 13: 27, 14: 8, 15: 25, 16: 12, 17: 87, 18: 88, 19: 54, 20: 79, 21: 36, 22: 36, 23: 16, 24: 70, 25: 61, 26: 57, 27: 57, 28: 39, 29: 43, 30: 22, 31: 45, 32: 30}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)O': {0: 48, 1: 35, 2: 30, 3: 40, 4: 34, 5: 27, 6: 12, 8: 68, 9: 28, 10: 57, 11: 54, 12: 25, 13: 6, 14: 80, 15: 39, 16: 88, 18: 18, 19: 85, 20: 35, 21: 94, 22: 51, 23: 89, 24: 83, 25: 73, 26: 67, 27: 64, 28: 17, 29: 11, 30: 3, 31: 61, 32: 84, 33: 83, 34: 78}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)SCF': {0: 54, 1: 38, 2: 33, 3: 46, 4: 42, 5: 33, 6: 19, 8: 78, 9: 36, 10: 63, 11: 60, 12: 33, 13: 11, 14: 90, 15: 51, 16: 99, 18: 22, 19: 93, 20: 39, 21: 102, 22: 57, 23: 96, 24: 87, 25: 75, 26: 72, 27: 69, 28: 20, 29: 17, 30: 5, 31: 66, 32: 84, 33: 81, 34: 4, 35: 10}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 56, 1: 47, 2: 34, 3: 21, 4: 71, 5: 70, 6: 67, 7: 46, 8: 34, 9: 33, 10: 44, 11: 10, 12: 70, 13: 70, 14: 6, 15: 25, 16: 17, 17: 4, 18: 63, 19: 14, 20: 20, 21: 73, 22: 51, 23: 36, 24: 36, 25: 39, 26: 78, 27: 57}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 59, 1: 49, 2: 33, 3: 21, 4: 73, 5: 72, 6: 69, 7: 48, 8: 34, 9: 33, 10: 47, 11: 41, 12: 9, 13: 71, 14: 27, 15: 22, 16: 13, 17: 3, 18: 66, 19: 10, 20: 17, 21: 74, 22: 54, 23: 36, 24: 36, 25: 41, 26: 78, 27: 60}, 'C[C@H](N)Cc1ccc(O)cc1': {0: 14, 1: 3, 2: 6, 3: 10, 4: 27, 5: 18, 6: 12, 7: 24, 8: 21, 9: 12, 10: 18}, 'C[C@H](N)Cc1ccccc1': {0: 18, 1: 3, 2: 7, 3: 11, 4: 24, 5: 20, 6: 15, 7: 10, 8: 15, 9: 20}, 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O': {0: 18, 1: 6, 2: 39, 3: 16, 4: 46, 5: 24, 6: 35, 8: 32, 9: 3, 10: 20, 11: 42, 12: 41, 13: 12, 14: 32, 15: 9, 16: 27}, 'C[C@H]1[C@@H](O)O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@]24OO3': {0: 32, 1: 21, 2: 9, 3: 15, 4: 32, 5: 24, 6: 37, 7: 3, 8: 42, 9: 51, 10: 6, 11: 51, 12: 45, 13: 29, 14: 12, 15: 18, 16: 35, 17: 54, 18: 51, 19: 48}, 'C[C@]12CC[C@H](O)CC1=CC[C@@H]1[C@@H]2CC[C@]2(C)C(c3cccnc3)=CC[C@@H]12': {0: 58, 1: 78, 2: 37, 3: 40, 4: 44, 5: 43, 6: 24, 7: 21, 8: 66, 9: 10, 10: 5, 11: 63, 12: 20, 13: 31, 14: 75, 15: 55, 16: 46, 17: 12, 18: 5, 19: 72, 20: 69, 21: 40, 22: 33, 23: 35, 24: 15, 25: 56}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 18, 1: 69, 2: 82, 3: 81, 4: 79, 5: 24, 6: 59, 7: 30, 8: 19, 9: 43, 11: 22, 12: 49, 14: 73, 15: 24, 16: 68, 17: 70, 18: 76, 19: 76, 20: 84, 21: 32, 22: 23, 23: 23, 24: 69, 25: 68, 26: 87, 27: 71, 28: 8, 29: 20, 30: 44, 31: 40, 32: 49, 33: 3, 34: 11}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1': {0: 19, 1: 77, 2: 73, 3: 62, 4: 8, 5: 55, 9: 29, 10: 45, 11: 37, 12: 82, 13: 22, 14: 4, 15: 88, 16: 80, 17: 48, 18: 73, 19: 30, 20: 41, 21: 83, 22: 87, 23: 12, 24: 77, 25: 24, 26: 68, 27: 67, 28: 64, 29: 14, 30: 61, 31: 23, 32: 67, 33: 24, 34: 68, 35: 28, 36: 76, 37: 73}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@+](O)c1nc2c(OS(=O)(=O)O)cccc2[nH]1': {0: 12, 1: 58, 2: 54, 3: 44, 4: 4, 5: 37, 9: 19, 10: 27, 11: 21, 12: 63, 13: 5, 14: 56, 15: 66, 16: 63, 17: 30, 18: 61, 19: 52, 20: 53, 21: 48, 22: 42, 23: 42, 24: 42, 25: 19, 26: 15, 27: 13, 28: 57, 29: 56}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1': {0: 15, 1: 63, 2: 59, 3: 52, 4: 6, 5: 42, 9: 25, 10: 30, 11: 26, 12: 67, 13: 19, 14: 3, 15: 68, 16: 58, 17: 33, 18: 45, 19: 16, 20: 15, 21: 39, 22: 36, 23: 10, 24: 48, 25: 53}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1': {0: 17, 1: 58, 2: 54, 3: 48, 4: 10, 5: 39, 9: 27, 10: 35, 11: 30, 12: 61, 13: 21, 14: 4, 15: 61, 16: 51, 17: 34, 18: 42, 19: 19, 20: 18, 21: 9, 22: 10, 23: 42, 24: 45}, 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1': {0: 23, 1: 79, 2: 39, 3: 85, 4: 33, 5: 80, 6: 53, 7: 38, 8: 80, 9: 73, 10: 80, 11: 50, 12: 68, 13: 65, 14: 12, 15: 28, 16: 18, 17: 31, 18: 62, 20: 26, 21: 53, 22: 86, 23: 32, 24: 15, 25: 29, 26: 18, 27: 9, 28: 20, 29: 67, 30: 29, 31: 15, 32: 43}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2': {0: 4, 1: 42, 2: 30, 3: 10, 4: 48, 5: 39, 6: 54, 7: 33, 8: 17, 9: 51, 11: 32, 12: 60, 13: 63, 14: 57, 15: 27, 16: 23, 17: 13, 18: 26, 19: 45, 21: 14, 22: 5}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O': {0: 4, 1: 42, 2: 30, 3: 10, 4: 51, 5: 39, 6: 57, 7: 33, 8: 17, 9: 48, 11: 32, 12: 63, 13: 66, 14: 60, 15: 27, 16: 23, 17: 13, 18: 26, 19: 45, 21: 14, 22: 5, 23: 54}, 'Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2': {1: 42, 2: 10, 3: 27, 4: 45, 5: 51, 6: 24, 7: 35, 8: 57, 9: 22, 10: 8, 11: 17, 12: 13, 13: 17, 14: 8, 15: 54, 16: 32, 17: 13, 18: 21, 19: 33, 20: 48, 21: 18}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N(CC(=O)O)CC(=O)O)cc3)n2)cc1': {0: 42, 1: 46, 2: 5, 3: 31, 4: 59, 5: 53, 6: 64, 7: 23, 8: 26, 9: 71, 10: 70, 11: 32, 12: 38, 13: 16, 14: 62, 15: 13, 16: 67, 17: 35, 18: 13, 19: 69, 20: 18, 21: 4, 22: 52, 23: 47, 24: 47, 25: 4, 26: 52, 27: 47, 28: 47, 29: 13, 30: 35, 31: 19, 32: 26, 33: 23}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1': {0: 45, 1: 50, 2: 8, 3: 35, 4: 59, 5: 54, 6: 67, 7: 27, 8: 30, 9: 73, 10: 73, 11: 36, 12: 42, 13: 21, 14: 62, 15: 18, 16: 64, 17: 37, 18

In [136]:
df_total = pd.read_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
smartcyp_results = [result_new[i] for i in substrates]
df_total['smartcyp_results'] = smartcyp_results
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,smartcyp_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ...","{0: 14, 1: 60, 2: 32, 3: 6, 4: 57, 5: 49, 6: 4..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20...","{0: 7, 1: 42, 2: 39, 3: 29, 4: 54, 5: 19, 6: 3..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17...","{0: 4, 1: 49, 2: 45, 3: 34, 4: 58, 5: 23, 6: 3..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19...","{0: 16, 1: 39, 2: 16, 3: 16, 4: 45, 5: 29, 6: ..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40...","{0: 22, 1: 62, 2: 22, 3: 22, 4: 70, 5: 26, 6: ..."
...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23...","{0: 42, 1: 47, 2: 39, 3: 31, 4: 24, 5: 14, 6: ..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12...","{0: 48, 1: 3, 2: 15, 3: 57, 4: 29, 5: 68, 6: 4..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7...","{0: 42, 1: 4, 2: 48, 3: 32, 4: 12, 5: 51, 6: 3..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ...","{0: 36, 1: 39, 2: 18, 3: 33, 4: 48, 5: 10, 6: ..."
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7...","{0: 12, 1: 19, 2: 15, 3: 24, 4: 15, 5: 4, 6: 1..."

In [137]:
df_total.to_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')

3. somp

In [138]:
df = pd.read_pickle('somp_results_drugbank.pickle')
df

,substrates,enzyme,scores
0,C[C@H](N)Cc1ccccc1,2C9,"{0: 8, 1: 1, 2: 3, 3: 7, 4: 6, 5: 11, 6: 9, 7:..."
1,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,2D6,"{0: 11, 1: 8, 2: 17, 3: 6, 4: 7, 5: 20, 6: 19,..."
2,c1cnc(N2CCNCC2)nc1,1A2,"{0: 1, 1: 7, 2: 9, 3: 12, 4: 11, 5: 5, 6: 3, 7..."
3,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,2D6,"{0: 2, 1: 26, 2: 17, 3: 19, 4: 22, 5: 21, 6: 1..."
4,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C9,"{0: 13, 1: 23, 2: 19, 3: 18, 4: 10, 5: 11, 6: ..."
...,...,...,...
697,O=C(C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2...,UGT,"{0: 7, 1: 16, 2: 21, 3: 25, 4: 9, 5: 2, 6: 17,..."
698,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,3A4,"{0: 14, 1: 21, 2: 1, 3: 13, 4: 24, 5: 23, 6: 6..."
699,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,UGT,"{0: 9, 1: 7, 2: 27, 3: 19, 4: 15, 5: 17, 6: 28..."
700,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C19,"{0: 8, 1: 18, 2: 21, 3: 14, 4: 5, 5: 3, 6: 16,..."
701,N#Cc1ccc2c(c1)COC2(CCC=O)c1ccc(F)cc1,UGT,"{0: 5, 1: 15, 2: 22, 3: 19, 4: 14, 5: 18, 6: 2..."

In [139]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O': {0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: 65, 7: 35, 8: 25, 9: 29, 10: 35, 11: 89, 12: 41, 13: 47, 14: 99, 15: 53, 16: 103, 17: 104, 18: 71, 19: 115, 20: 105, 21: 112, 22: 116}, 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6: 55, 7: 102, 8: 131, 9: 62, 10: 130, 11: 116, 12: 59, 13: 32, 14: 25, 15: 46, 16: 108, 17: 85, 18: 65, 19: 13, 20: 96, 21: 60, 22: 100}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, 6: 69, 7: 77, 8: 166, 9: 153, 10: 173, 11: 121, 12: 149, 13: 104, 14: 101, 15: 107, 16: 138, 17: 149, 18: 95, 19: 164, 20: 129, 21: 183, 22: 75, 23: 73, 24: 77, 25: 93, 26: 83, 27: 189, 28: 124, 29: 91, 30: 15, 31: 108, 32: 115, 33: 81, 34: 25, 35: 142, 36: 108}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6: 109, 7: 68, 8: 34, 9: 40, 10: 46, 11: 159, 12: 117, 13: 92, 14: 96, 15: 150, 16: 118, 17: 129, 18: 163, 19: 74, 20: 47, 21: 41, 22: 64, 23: 148, 24: 135, 25: 86, 26: 54, 27: 133, 28: 123}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6: 171, 7: 196, 8: 144, 9: 180, 10: 163, 11: 192, 12: 83, 13: 109, 14: 163, 15: 155, 16: 124, 17: 139, 18: 121, 19: 131, 20: 19, 21: 207, 22: 119, 23: 174, 24: 204, 25: 63, 26: 53, 27: 92, 28: 91, 29: 69, 30: 179, 31: 75, 32: 97, 33: 99, 34: 119, 35: 181, 36: 115, 37: 89, 38: 166, 39: 164}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 59, 1: 94, 2: 65, 3: 23, 4: 124, 5: 97, 6: 106, 7: 47, 8: 84, 9: 72, 10: 36, 11: 30, 12: 82, 13: 80, 14: 98, 15: 127, 16: 115, 17: 102, 18: 41, 19: 121, 20: 108, 21: 121, 22: 86, 23: 88, 24: 130, 25: 103, 26: 29}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 56, 1: 87, 2: 62, 3: 19, 4: 122, 5: 96, 6: 104, 7: 51, 8: 83, 9: 72, 10: 37, 11: 31, 12: 79, 13: 77, 14: 98, 15: 129, 16: 105, 17: 113, 18: 32, 19: 119, 20: 111, 21: 83, 22: 85, 23: 128, 24: 102, 25: 25}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 71, 1: 136, 2: 77, 3: 34, 4: 145, 5: 98, 6: 117, 7: 47, 8: 72, 9: 66, 10: 27, 11: 29, 12: 72, 13: 72, 14: 83, 15: 113, 16: 90, 17: 105, 18: 22, 19: 111, 20: 96, 21: 78, 22: 78, 23: 145, 24: 100, 25: 55, 26: 129}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O': {0: 13, 1: 72, 2: 53, 3: 54, 4: 74, 5: 54, 6: 57, 7: 88, 8: 41, 9: 93, 10: 94, 11: 64, 12: 109, 13: 95, 14: 108, 15: 116, 16: 117, 17: 53, 18: 59, 19: 56, 20: 49, 21: 37, 22: 100}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 30, 1: 42, 2: 60, 3: 87, 4: 64, 5: 43, 6: 90, 7: 112, 8: 46, 9: 152, 10: 141, 11: 96, 12: 93, 13: 74, 14: 147, 15: 166, 16: 53, 17: 85, 18: 158, 19: 122, 20: 73, 21: 149, 22: 123, 23: 163, 24: 136, 25: 118, 26: 124, 27: 130, 28: 87, 29: 61, 30: 72, 31: 71}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 36, 1: 48, 2: 66, 3: 93, 4: 68, 5: 47, 6: 94, 7: 117, 8: 51, 9: 156, 10: 143, 11: 98, 12: 95, 13: 77, 14: 151, 15: 164, 16: 59, 17: 86, 18: 157, 19: 125, 20: 82, 21: 178, 22: 145, 23: 23, 24: 168, 25: 141, 26: 123, 27: 129, 28: 135, 29: 90, 30: 67, 31: 78, 32: 76}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 47, 1: 72, 2: 84, 3: 98, 4: 191, 5: 166, 6: 178, 7: 215, 8: 151, 9: 127, 10: 160, 11: 144, 12: 141, 13: 174, 14: 180, 15: 147, 16: 202, 17: 159, 18: 102, 19: 125, 20: 215, 21: 35, 22: 200, 23: 52, 24: 144, 25: 220, 26: 229, 27: 49, 28: 113, 29: 127, 30: 137, 31: 180, 32: 153, 33: 216, 34: 96, 35: 80, 36: 241, 37: 228, 38: 103, 39: 258, 40: 189, 41: 220, 42: 108, 43: 165, 44: 186, 45: 192, 46: 166, 47: 133, 48: 208, 49: 144}, 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 21, 1: 23, 2: 42, 3: 41, 4: 46, 5: 95, 6: 107, 7: 74, 8: 86, 9: 131, 10: 63, 11: 95, 12: 69, 13: 130, 14: 96, 15: 141, 16: 118, 17: 141, 18: 75, 19: 56, 20: 49, 21: 46, 22: 82, 23: 87, 24: 116, 25: 127, 26: 137, 27: 142}, 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 21, 1: 25, 2: 43, 3: 43, 4: 49, 5: 109, 6: 110, 7: 66, 8: 75, 9: 136, 10: 61, 11: 96, 12: 67, 13: 130, 14: 100, 15: 141, 16: 117, 17: 140, 18: 73, 19: 56, 20: 51, 21: 46, 22: 78, 23: 85, 24: 114, 25: 126, 26: 136, 27: 142}, 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F': {0: 37, 1: 29, 2: 66, 3: 59, 4: 43, 5: 140, 6: 49, 7: 102, 8: 128, 9: 126, 10: 117, 11: 126, 12: 113, 13: 138, 14: 87, 15: 42, 16: 143, 17: 94, 18: 48, 19: 52, 20: 70, 21: 54, 22: 122, 23: 112, 24: 60, 25: 116, 26: 110, 27: 128, 28: 99}, 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 24, 1: 25, 2: 42, 3: 43, 4: 67, 5: 69, 6: 59, 7: 137, 8: 109, 9: 106, 10: 137, 11: 65, 12: 94, 13: 71, 14: 131, 15: 101, 16: 145, 17: 118, 18: 146, 19: 77, 20: 55, 21: 48, 22: 45, 23: 79, 24: 86, 25: 116, 26: 127, 27: 140, 28: 148}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 44, 1: 59, 2: 44, 3: 133, 4: 100, 5: 128, 6: 41, 7: 114, 8: 148, 9: 115, 10: 126, 11: 185, 12: 163, 13: 117, 14: 184, 15: 62, 16: 113, 17: 119, 18: 115, 19: 79, 20: 96, 21: 72, 22: 32, 23: 63, 24: 102, 25: 85, 26: 114, 27: 94, 28: 178, 29: 170, 30: 38, 31: 64, 32: 135, 33: 138}, 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN': {0: 52, 1: 13, 2: 81, 3: 19, 4: 58, 5: 77, 6: 84, 7: 110, 8: 93, 9: 63, 10: 39, 11: 23, 12: 45, 13: 69, 14: 66, 15: 90, 16: 36, 17: 54, 18: 68}, 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 72, 1: 30, 2: 100, 3: 94, 4: 39, 5: 56, 6: 81, 7: 39, 8: 71, 9: 41, 10: 121, 11: 28, 12: 64, 13: 64, 14: 70, 15: 96, 16: 108, 17: 68, 18: 119, 19: 109, 20: 103, 21: 92, 22: 98, 23: 37}, 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1': {0: 53, 1: 25, 2: 152, 3: 73, 4: 43, 5: 65, 6: 46, 7: 63, 8: 36, 9: 178, 10: 162, 11: 157, 12: 22, 13: 86, 14: 154, 15: 30, 16: 161, 17: 185, 18: 98, 19: 122, 20: 138, 21: 127, 22: 49, 23: 134, 24: 81, 25: 93, 26: 135, 27: 109, 28: 122, 29: 149, 30: 99, 31: 87, 32: 132}, 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 51, 1: 21, 2: 141, 3: 122, 4: 79, 5: 48, 6: 103, 7: 126, 8: 59, 9: 131, 10: 148, 11: 45, 12: 50, 13: 119, 14: 46, 15: 46, 16: 103, 17: 107, 18: 157, 19: 87, 20: 64, 21: 120, 22: 132, 23: 23, 24: 147, 25: 97, 26: 115, 27: 93, 28: 99, 29: 111}, 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C': {0: 38, 1: 49, 2: 59, 3: 54, 4: 94, 5: 68, 6: 91, 7: 88, 8: 40, 9: 97, 10: 94, 11: 74, 12: 54, 13: 60, 14: 60, 15: 39, 16: 53, 17: 11, 18: 17}, 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C': {0: 36, 1: 47, 2: 57, 3: 55, 4: 98, 5: 80, 6: 68, 7: 43, 8: 94, 9: 90, 10: 70, 11: 54, 12: 61, 13: 57, 14: 36, 15: 54, 16: 10, 17: 16}, 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C': {0: 33, 1: 27, 2: 74, 3: 31, 4: 85, 5: 67, 6: 88, 7: 43, 8: 75, 9: 37, 10: 42, 11: 77, 12: 76, 13: 38, 14: 57, 15: 54, 16: 14}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 11, 1: 26, 2: 17, 3: 26, 4: 73, 5: 88, 6: 129, 7: 105, 8: 44, 9: 43, 10: 80, 11: 84, 12: 49, 13: 50, 14: 117, 15: 75, 16: 127, 17: 105, 18: 123, 19: 80, 20: 81, 21: 68, 22: 66, 23: 133}, 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 11, 1: 26, 2: 17, 3: 26, 4: 73, 5: 88, 6: 129, 7: 105, 8: 44, 9: 43, 10: 80, 11: 84, 12: 49, 13: 50, 14: 117, 15: 75, 16: 127, 17: 105, 18: 123, 19: 80, 20: 81, 21: 68, 22: 66, 23: 133}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 16, 1: 24, 2: 22, 3: 34, 4: 73, 5: 108, 6: 93, 7: 103, 8: 122, 9: 51, 10: 78, 11: 85, 12: 74, 13: 39, 14: 46, 15: 52, 16: 55, 17: 64, 18: 64, 19: 66, 20: 117}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 15, 1: 24, 2: 21, 3: 32, 4: 74, 5: 105, 6: 90, 7: 96, 8: 110, 9: 56, 10: 53, 11: 75, 12: 34, 13: 46, 14: 53, 15: 55, 16: 65, 17: 64, 18: 75, 19: 117}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 15, 1: 71, 2: 94, 3: 69, 4: 25, 5: 89, 6: 64, 7: 103, 8: 78, 9: 61, 10: 33, 11: 54, 12: 104, 13: 39, 14: 67, 15: 118, 16: 63, 17: 72, 18: 97, 19: 38, 20: 49, 21: 115}, 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1': {0: 18, 1: 58, 2: 42, 3: 65, 4: 77, 5: 42, 6: 122, 7: 46, 8: 110, 9: 101, 10: 114, 11: 69, 12: 107, 13: 139, 14: 119, 15: 123, 16: 113, 17: 75, 18: 68, 19: 88, 20: 48, 21: 171, 22: 135, 23: 167, 24: 104, 25: 35, 26: 35, 27: 93, 28: 165, 29: 141}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 18, 1: 116, 2: 128, 3: 96, 4: 180, 5: 129, 6: 159, 7: 143, 8: 84, 9: 65, 10: 52, 11: 105, 12: 96, 13: 61, 14: 89, 15: 89, 16: 138, 17: 42, 18: 49, 19: 158, 20: 123, 21: 158, 22: 143, 23: 71, 24: 77, 25: 83, 26: 82, 27: 58, 28: 71, 29: 73, 30: 136, 31: 96}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 12, 1: 68, 2: 33, 3: 73, 4: 66, 5: 120, 6: 100, 7: 32, 8: 33, 9: 73, 10: 76, 11: 39, 12: 38, 13: 112, 14: 63, 15: 121, 16: 98, 17: 117, 18: 67, 19: 73, 20: 58, 21: 56, 22: 128}, 'CNCCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 12, 1: 68, 2: 33, 3: 73, 4: 66, 5: 120, 6: 100, 7: 32, 8: 33, 9: 73, 10: 76, 11: 39, 12: 38, 13: 112, 14: 63, 15: 121, 16: 98, 17: 117, 18: 67, 19: 73, 20: 58, 21: 56, 22: 128}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 25, 1: 159, 2: 195, 3: 154, 4: 178, 5: 35, 6: 95, 7: 32, 8: 49, 9: 63, 10: 58, 11: 115, 12: 64, 13: 69, 14: 89, 15: 123, 16: 177, 17: 194, 18: 112, 19: 160, 20: 129, 21: 54, 22: 104, 23: 109, 24: 126, 25: 85, 26: 144, 27: 72, 28: 91, 29: 132, 30: 158, 31: 63, 32: 82, 33: 115, 34: 170}, 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1': {0: 19, 1: 149, 2: 153, 3: 78, 4: 144, 5: 26, 6: 150, 7: 128, 8: 112, 9: 87, 10: 174, 11: 166, 12: 31, 13: 58, 14: 38, 15: 51, 16: 53, 17: 37, 18: 140, 19: 116, 20: 113, 21: 43, 22: 123, 23: 69, 24: 83, 25: 127, 26: 98, 27: 112, 28: 134, 29: 89, 30: 75}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 38, 1: 162, 2: 121, 3: 104, 4: 147, 5: 137, 6: 150, 7: 193, 8: 76, 9: 101, 10: 136, 11: 95, 12: 181, 13: 146, 14: 165, 15: 182, 16: 37, 17: 80, 18: 31, 19: 39, 20: 88, 21: 82, 22: 27, 23: 17, 24: 88, 25: 96, 26: 169, 27: 177, 28: 29, 29: 90, 30: 185, 31: 167, 32: 114, 33: 63, 34: 166, 35: 117}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 22, 1: 161, 2: 152, 3: 74, 4: 158, 5: 167, 6: 28, 7: 111, 8: 87, 9: 91, 10: 60, 11: 59, 12: 145, 13: 45, 14: 121, 15: 127, 16: 74, 17: 61, 18: 123, 19: 182, 20: 120, 21: 137, 22: 147, 23: 55, 24: 62, 25: 67, 26: 29, 27: 96, 28: 76, 29: 116, 30: 185, 31: 111, 32: 117}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1[C@@H](NC(C)=O)CC2': {0: 17, 1: 142, 2: 128, 3: 84, 4: 126, 5: 152, 6: 130, 7: 128, 8: 27, 9: 95, 10: 134, 11: 26, 12: 124, 13: 75, 14: 58, 15: 98, 16: 147, 17: 23, 18: 113, 19: 90, 20: 80, 21: 157, 22: 102, 23: 44, 24: 123, 25: 50, 26: 70, 27: 118, 28: 81, 29: 48}, 'COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2': {0: 16, 1: 120, 2: 116, 3: 96, 4: 136, 5: 152, 6: 101, 7: 126, 8: 126, 9: 22, 10: 115, 11: 49, 12: 110, 13: 81, 14: 55, 15: 116, 16: 73, 17: 61, 18: 56, 19: 30, 20: 51, 21: 57, 22: 66, 23: 58, 24: 58, 25: 59}, 'COc1ccc(C[C@@H](C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 18, 1: 121, 2: 109, 3: 58, 4: 81, 5: 143, 6: 99, 7: 38, 8: 43, 9: 97, 10: 106, 11: 45, 12: 38, 13: 134, 14: 104, 15: 65, 16: 42, 17: 45, 18: 47, 19: 103, 20: 119, 21: 102, 22: 136, 23: 85, 24: 106, 25: 89, 26: 95}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 25, 1: 81, 2: 60, 3: 54, 4: 60, 5: 108, 6: 94, 7: 130, 8: 10, 9: 60, 10: 108, 11: 123, 12: 59, 13: 73, 14: 81, 15: 26, 16: 90, 17: 98, 18: 27, 19: 99, 20: 33, 21: 117, 22: 119, 23: 65}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)CC3': {0: 14, 1: 147, 2: 137, 3: 46, 4: 46, 5: 55, 6: 162, 7: 160, 8: 91, 9: 83, 10: 82, 11: 96, 12: 111, 13: 86, 14: 72, 15: 82, 16: 117, 17: 100, 18: 121, 19: 106, 20: 60, 21: 119, 22: 113, 23: 101, 24: 70, 25: 22, 26: 122, 27: 53, 28: 36}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 23, 1: 226, 2: 206, 3: 67, 4: 78, 5: 93, 6: 243, 7: 240, 8: 164, 9: 139, 10: 178, 11: 136, 12: 165, 13: 128, 14: 104, 15: 156, 16: 176, 17: 158, 18: 198, 19: 180, 20: 86, 21: 151, 22: 165, 23: 152, 24: 135, 25: 35, 26: 193, 27: 106, 28: 86, 29: 50, 30: 197, 31: 142, 32: 56, 33: 164, 34: 143, 35: 62, 36: 106, 37: 111, 38: 68, 39: 192, 40: 144, 41: 74, 42: 56, 43: 208}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3': {0: 14, 1: 147, 2: 137, 3: 53, 4: 51, 5: 58, 6: 160, 7: 160, 8: 91, 9: 80, 10: 87, 11: 92, 12: 107, 13: 87, 14: 74, 15: 82, 16: 113, 17: 99, 18: 119, 19: 107, 20: 61, 21: 128, 22: 108, 23: 47, 24: 116, 25: 26, 26: 113, 27: 54, 28: 39}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 24, 1: 233, 2: 209, 3: 75, 4: 85, 5: 99, 6: 247, 7: 244, 8: 170, 9: 141, 10: 181, 11: 143, 12: 167, 13: 138, 14: 111, 15: 162, 16: 179, 17: 163, 18: 202, 19: 186, 20: 84, 21: 173, 22: 168, 23: 59, 24: 57, 25: 184, 26: 40, 27: 191, 28: 104, 29: 95, 30: 63, 31: 205, 32: 147, 33: 69, 34: 170, 35: 146, 36: 75, 37: 112, 38: 115, 39: 81, 40: 199, 41: 149, 42: 87, 43: 64, 44: 214}, 'COc1nc(N)nc2[nH]cnc12': {0: 15, 1: 43, 2: 49, 3: 36, 4: 48, 5: 25, 6: 52, 7: 50, 8: 57, 9: 25, 10: 27, 11: 41}, 'COc1nc(N)nc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O': {0: 22, 1: 112, 2: 123, 3: 105, 4: 114, 5: 71, 6: 121, 7: 110, 8: 128, 9: 77, 10: 58, 11: 106, 12: 60, 13: 31, 14: 94, 15: 84, 16: 37, 17: 27, 18: 79, 19: 56, 20: 43, 21: 86, 22: 65, 23: 49, 24: 92}, 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12': {0: 23, 1: 160, 2: 159, 3: 152, 4: 218, 5: 150, 6: 163, 7: 165, 8: 160, 9: 169, 10: 218, 11: 97, 12: 187, 13: 129, 14: 69, 15: 162, 16: 119, 17: 65, 18: 50, 19: 71, 20: 125, 21: 126, 22: 154, 23: 120, 24: 33, 25: 55, 26: 12, 27: 18, 28: 192, 29: 97, 30: 47, 31: 83, 32: 170, 33: 94, 34: 49, 35: 75, 36: 111, 37: 199}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 17, 1: 99, 2: 120, 3: 42, 4: 74, 5: 102, 6: 52, 7: 39, 8: 45, 9: 100, 10: 45, 11: 58, 12: 62, 13: 104, 14: 65, 15: 116, 16: 34, 17: 54, 18: 116, 19: 84, 20: 70, 21: 76, 22: 82}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 105, 1: 23, 2: 82, 3: 88, 4: 158, 5: 49, 6: 66, 7: 113, 8: 77, 9: 78, 10: 112, 11: 152, 12: 26, 13: 97, 14: 110, 15: 113, 16: 70, 17: 151, 18: 155, 19: 68, 20: 41, 21: 35, 22: 105, 23: 71, 24: 47, 25: 121, 26: 67, 27: 56}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 102, 1: 21, 2: 79, 3: 85, 4: 154, 5: 49, 6: 66, 7: 115, 8: 76, 9: 78, 10: 86, 11: 154, 12: 31, 13: 52, 14: 124, 15: 97, 16: 155, 17: 162, 18: 68, 19: 31, 20: 72, 21: 121, 22: 73, 23: 83, 24: 53, 25: 123, 26: 69, 27: 57}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 101, 1: 18, 2: 78, 3: 84, 4: 146, 5: 51, 6: 67, 7: 109, 8: 75, 9: 78, 10: 85, 11: 148, 12: 30, 13: 53, 14: 122, 15: 97, 16: 152, 17: 158, 18: 71, 19: 41, 20: 33, 21: 100, 22: 72, 23: 55, 24: 120, 25: 66, 26: 58}, 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12': {0: 78, 1: 40, 2: 44, 3: 176, 4: 174, 5: 50, 6: 121, 7: 128, 8: 130, 9: 162, 10: 150, 11: 161, 12: 176, 13: 143, 14: 24, 15: 124, 16: 56, 17: 73, 18: 142, 19: 151, 20: 62, 21: 175, 22: 159, 23: 138, 24: 219, 25: 51, 26: 84, 27: 113, 28: 228, 29: 163, 30: 171, 31: 189, 32: 127, 33: 116, 34: 125, 35: 68, 36: 42, 37: 73, 38: 74}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)O': {0: 39, 1: 110, 2: 37, 3: 96, 4: 175, 5: 43, 6: 183, 7: 49, 8: 127, 9: 100, 10: 55, 11: 132, 12: 215, 13: 98, 14: 195, 15: 173, 16: 85, 17: 123, 18: 193, 19: 54, 20: 217, 21: 125, 22: 96, 23: 61, 24: 184, 25: 119, 26: 204, 27: 89, 28: 209, 29: 142, 30: 113, 31: 113, 32: 143, 33: 72, 34: 107, 35: 36, 36: 172, 37: 143, 38: 131, 39: 162}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)SCF': {0: 47, 1: 120, 2: 40, 3: 115, 4: 196, 5: 46, 6: 199, 7: 52, 8: 139, 9: 110, 10: 58, 11: 145, 12: 232, 13: 113, 14: 211, 15: 184, 16: 101, 17: 148, 18: 213, 19: 65, 20: 233, 21: 139, 22: 117, 23: 64, 24: 197, 25: 141, 26: 217, 27: 101, 28: 180, 29: 162, 30: 141, 31: 139, 32: 174, 33: 81, 34: 127, 35: 43, 36: 190, 37: 130, 38: 95, 39: 17, 40: 95, 41: 101}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 71, 1: 61, 2: 37, 3: 138, 4: 128, 5: 154, 6: 170, 7: 176, 8: 158, 9: 43, 10: 58, 11: 72, 12: 165, 13: 49, 14: 154, 15: 55, 16: 139, 17: 128, 18: 98, 19: 139, 20: 61, 21: 123, 22: 49, 23: 67, 24: 169, 25: 60, 26: 101, 27: 169, 28: 101, 29: 174, 30: 73, 31: 57, 32: 78, 33: 192, 34: 113}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 74, 1: 64, 2: 38, 3: 145, 4: 128, 5: 155, 6: 172, 7: 183, 8: 157, 9: 44, 10: 61, 11: 81, 12: 174, 13: 50, 14: 161, 15: 56, 16: 89, 17: 62, 18: 165, 19: 112, 20: 146, 21: 68, 22: 135, 23: 63, 24: 74, 25: 172, 26: 64, 27: 101, 28: 167, 29: 109, 30: 183, 31: 80, 32: 71, 33: 82, 34: 190, 35: 120}, 'C[C@H](N)Cc1ccc(O)cc1': {0: 45, 1: 24, 2: 20, 3: 53, 4: 37, 5: 62, 6: 43, 7: 14, 8: 44, 9: 57, 10: 20, 11: 49}, 'C[C@H](N)Cc1ccccc1': {0: 49, 1: 25, 2: 20, 3: 51, 4: 40, 5: 60, 6: 43, 7: 21, 8: 11, 9: 27, 10: 49}, 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O': {0: 28, 1: 61, 2: 17, 3: 103, 4: 57, 5: 23, 6: 102, 7: 75, 8: 102, 9: 71, 10: 97, 11: 41, 12: 87, 13: 92, 14: 82, 15: 74, 16: 29, 17: 82, 18: 43, 19: 35, 20: 85}, 'C[C@H]1[C@@H](O)O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@]24OO3': {0: 33, 1: 112, 2: 46, 3: 56, 4: 43, 5: 111, 6: 52, 7: 117, 8: 58, 9: 33, 10: 84, 11: 64, 12: 125, 13: 120, 14: 115, 15: 70, 16: 127, 17: 69, 18: 43, 19: 41, 20: 37, 21: 134, 22: 76, 23: 128, 24: 110, 25: 102}, 'C[C@]12CC[C@H](O)CC1=CC[C@@H]1[C@@H]2CC[C@]2(C)C(c3cccnc3)=CC[C@@H]12': {0: 86, 1: 155, 2: 58, 3: 51, 4: 171, 5: 40, 6: 146, 7: 46, 8: 68, 9: 63, 10: 150, 11: 42, 12: 76, 13: 52, 14: 139, 15: 41, 16: 91, 17: 164, 18: 92, 19: 157, 20: 58, 21: 52, 22: 58, 23: 148, 24: 132, 25: 108, 26: 49, 27: 120, 28: 46, 29: 131}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 26, 1: 70, 2: 131, 3: 81, 4: 159, 5: 129, 6: 177, 7: 64, 8: 65, 9: 69, 10: 83, 11: 73, 12: 178, 13: 114, 14: 82, 15: 17, 16: 96, 17: 102, 18: 129, 19: 141, 20: 146, 21: 91, 22: 91, 23: 97, 24: 163, 25: 114, 26: 148, 27: 132, 28: 100, 29: 62, 30: 134, 31: 172, 32: 177, 33: 67, 34: 100}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1': {0: 55, 1: 218, 2: 195, 3: 205, 4: 40, 5: 145, 6: 127, 7: 133, 8: 139, 9: 101, 10: 152, 11: 141, 12: 236, 13: 211, 14: 21, 15: 160, 16: 234, 17: 186, 18: 210, 19: 124, 20: 78, 21: 112, 22: 159, 23: 119, 24: 34, 25: 149, 26: 140, 27: 40, 28: 109, 29: 112, 30: 140, 31: 83, 32: 46, 33: 137, 34: 82, 35: 52, 36: 141, 37: 114, 38: 58, 39: 143, 40: 148, 41: 233, 42: 214}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1': {0: 28, 1: 122, 2: 102, 3: 119, 4: 30, 5: 69, 6: 54, 7: 60, 8: 66, 9: 58, 10: 77, 11: 69, 12: 139, 13: 116, 14: 11, 15: 75, 16: 138, 17: 97, 18: 114, 19: 65, 20: 41, 21: 63, 22: 85, 23: 50, 24: 132, 25: 126}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1': {0: 31, 1: 122, 2: 103, 3: 119, 4: 30, 5: 69, 6: 56, 7: 62, 8: 68, 9: 64, 10: 76, 11: 68, 12: 134, 13: 111, 14: 10, 15: 74, 16: 132, 17: 95, 18: 108, 19: 53, 20: 38, 21: 34, 22: 60, 23: 12

In [140]:
df_total = pd.read_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
somp_results = [result_new.get(i,'None') for i in substrates]
df_total['somp_results'] = somp_results
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,smartcyp_results,somp_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ...","{0: 14, 1: 60, 2: 32, 3: 6, 4: 57, 5: 49, 6: 4...","{0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: ..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20...","{0: 7, 1: 42, 2: 39, 3: 29, 4: 54, 5: 19, 6: 3...","{0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6:..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17...","{0: 4, 1: 49, 2: 45, 3: 34, 4: 58, 5: 23, 6: 3...","{0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, ..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19...","{0: 16, 1: 39, 2: 16, 3: 16, 4: 45, 5: 29, 6: ...","{0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6:..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40...","{0: 22, 1: 62, 2: 22, 3: 22, 4: 70, 5: 26, 6: ...","{0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6:..."
...,...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23...","{0: 42, 1: 47, 2: 39, 3: 31, 4: 24, 5: 14, 6: ...",None
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12...","{0: 48, 1: 3, 2: 15, 3: 57, 4: 29, 5: 68, 6: 4...","{0: 149, 1: 31, 2: 140, 3: 62, 4: 160, 5: 157,..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7...","{0: 42, 1: 4, 2: 48, 3: 32, 4: 12, 5: 51, 6: 3...","{0: 61, 1: 13, 2: 82, 3: 46, 4: 64, 5: 99, 6: ..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ...","{0: 36, 1: 39, 2: 18, 3: 33, 4: 48, 5: 10, 6: ...",None
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7...","{0: 12, 1: 19, 2: 15, 3: 24, 4: 15, 5: 4, 6: 1...","{0: 13, 1: 48, 2: 43, 3: 58, 4: 52, 5: 25, 6: ..."

In [141]:
df_total.to_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')

4. xenosite

In [142]:
df =  pd.read_pickle('xenosite_results_drugbank.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 42, 1: 63, 2: 57, 3: 15, 4: 95, 5: 38, 6: 48, 7: 101, 8: 96, 9: 51, 10: 81, 11: 91, 12: 40, 13: 42, 14: 28, 15: 47, 16: 85, 17: 113, 18: 20, 19: 59, 20: 92, 21: 58, 22: 18}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 71, 1: 119, 2: 88, 3: 19, 4: 157, 5: 76, 6: 65, 7: 93, 8: 151, 9: 91, 10: 173, 11: 104, 12: 73, 13: 82, 14: 68, 15: 74, 16: 166, 17: 100, 18: 176, 19: 168, 20: 23, 21: 171, 22: 67, 23: 56, 24: 156, 25: 182, 26: 86, 27: 170, 28: 191, 29: 81, 30: 92, 31: 190, 32: 88, 33: 185, 34: 83, 35: 163, 36: 120}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 47, 1: 145, 2: 54, 3: 60, 4: 133, 5: 87, 6: 135, 7: 155, 8: 63, 9: 69, 10: 75, 11: 143, 12: 24, 13: 101, 14: 75, 15: 142, 16: 90, 17: 37, 18: 145, 19: 53, 20: 47, 21: 64, 22: 56, 23: 141, 24: 133, 25: 71, 26: 81, 27: 152, 28: 32}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 12, 1: 40, 2: 13, 3: 14, 4: 37, 5: 36, 6: 35, 7: 1, 8: 34, 9: 8, 10: 4, 11: 38, 12: 27, 13: 25, 14: 39, 15: 22, 16: 21, 17: 7, 18: 16, 19: 5, 20: 33, 21: 24, 22: 32, 23: 31, 24: 15, 25: 17, 26: 20, 27: 6, 28: 18, 29: 9, 30: 2, 31: 10, 32: 19, 33: 23, 34: 30, 35: 29, 36: 26, 37: 28, 38: 3, 39: 11}, 'CC(C=CC12OC1(C)CCCC2(C)C)=CC=CC(C)=CC(=O)O': {0: 49, 1: 91, 2: 68, 3: 67, 4: 115, 5: 48, 6: 124, 7: 71, 8: 63, 9: 61, 10: 69, 11: 134, 12: 66, 13: 72, 14: 42, 15: 51, 16: 48, 17: 89, 18: 64, 19: 34, 20: 98, 21: 91, 22: 41}, 'CC(C=CC1=C(C)C(=O)CCC1(C)C)=CC=CC(C)=CC(=O)O': {0: 53, 1: 91, 2: 57, 3: 70, 4: 100, 5: 98, 6: 67, 7: 103, 8: 64, 9: 63, 10: 53, 11: 133, 12: 57, 13: 63, 14: 42, 15: 51, 16: 47, 17: 93, 18: 64, 19: 31, 20: 97, 21: 112, 22: 47}, 'CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CC(=O)O': {0: 51, 1: 88, 2: 56, 3: 70, 4: 101, 5: 100, 6: 66, 7: 60, 8: 54, 9: 60, 10: 128, 11: 58, 12: 64, 13: 40, 14: 49, 15: 47, 16: 90, 17: 66, 18: 31, 19: 97, 20: 96, 21: 46}, 'CC(CCC(=O)O)C1CCC2C3C(=O)CC4CC(O)CCC4(C)C3CCC12C': {0: 63, 1: 93, 2: 69, 3: 69, 4: 107, 5: 111, 6: 52, 7: 80, 8: 64, 9: 69, 10: 64, 11: 103, 12: 135, 13: 84, 14: 105, 15: 76, 16: 75, 17: 40, 18: 28, 19: 63, 20: 87, 21: 159, 22: 93, 23: 97, 24: 102, 25: 89, 26: 163, 27: 96}, 'CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C': {0: 7, 1: 27, 2: 15, 3: 20, 4: 18, 5: 4, 6: 3, 7: 21, 8: 8, 9: 5, 10: 12, 11: 25, 12: 26, 13: 1, 14: 17, 15: 22, 16: 16, 17: 19, 18: 2, 19: 13, 20: 11, 21: 28, 22: 10, 23: 24, 24: 14, 25: 9, 26: 23, 27: 6}, 'CC(N)Cc1ccc(O)cc1': {0: 30, 1: 35, 2: 14, 3: 36, 4: 60, 5: 41, 6: 23, 7: 65, 8: 16, 9: 29, 10: 47}, 'CC(N)Cc1ccccc1': {0: 33, 1: 37, 2: 10, 3: 39, 4: 60, 5: 37, 6: 23, 7: 19, 8: 29, 9: 43}, 'CC(O)C1C(=O)N2C(C(=O)O)=C(SC3CNC(C(=O)Nc4cccc(C(=O)O)c4)C3)C(C)C12': {0: 82, 1: 74, 2: 33, 3: 112, 4: 154, 5: 109, 6: 69, 7: 153, 8: 151, 9: 142, 10: 72, 11: 138, 12: 48, 13: 102, 14: 94, 15: 31, 16: 98, 17: 140, 18: 107, 19: 41, 20: 180, 21: 81, 22: 73, 23: 78, 24: 159, 25: 137, 26: 133, 27: 67, 28: 87, 29: 83, 30: 114, 31: 93, 32: 131}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 58, 1: 141, 2: 65, 3: 71, 4: 122, 5: 82, 6: 58, 7: 85, 8: 75, 9: 78, 10: 82, 11: 27, 12: 67, 13: 74, 14: 38, 15: 147, 16: 80, 17: 79, 18: 146, 19: 37, 20: 86, 21: 88, 22: 84, 23: 79, 24: 140, 25: 88, 26: 91}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 62, 1: 138, 2: 69, 3: 71, 4: 121, 5: 81, 6: 45, 7: 84, 8: 73, 9: 75, 10: 76, 11: 26, 12: 69, 13: 75, 14: 35, 15: 143, 16: 70, 17: 76, 18: 75, 19: 83, 20: 76, 21: 85, 22: 81, 23: 139, 24: 87, 25: 91}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 65, 1: 143, 2: 72, 3: 78, 4: 129, 5: 88, 6: 50, 7: 92, 8: 79, 9: 83, 10: 84, 11: 30, 12: 79, 13: 82, 14: 37, 15: 149, 16: 75, 17: 77, 18: 81, 19: 84, 20: 81, 21: 92, 22: 91, 23: 135, 24: 94, 25: 85, 26: 33}, 'CC12CCC(O)CC1=CCC1C2CCC2(C)C(c3cccnc3)=CCC12': {0: 70, 1: 139, 2: 66, 3: 50, 4: 44, 5: 30, 6: 76, 7: 120, 8: 65, 9: 83, 10: 85, 11: 90, 12: 83, 13: 69, 14: 145, 15: 77, 16: 111, 17: 145, 18: 59, 19: 55, 20: 80, 21: 57, 22: 103, 23: 64, 24: 79, 25: 61}, 'CC1CC2C3CC(F)C4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(OC(=O)c1ccco1)C(=O)O': {0: 62, 1: 85, 2: 72, 3: 85, 4: 112, 5: 89, 6: 109, 7: 157, 8: 130, 9: 68, 10: 126, 11: 68, 12: 45, 13: 62, 14: 177, 15: 73, 16: 182, 17: 182, 18: 105, 19: 32, 20: 97, 21: 182, 22: 95, 23: 189, 24: 99, 25: 126, 26: 94, 27: 169, 28: 74, 29: 81, 30: 95, 31: 103, 32: 132, 33: 156, 34: 67}, 'CC1CC2C3CC(F)C4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(OC(=O)c1ccco1)C(=O)SCF': {0: 9, 1: 30, 2: 3, 3: 10, 4: 25, 5: 15, 6: 32, 7: 21, 8: 34, 9: 22, 10: 19, 11: 2, 12: 13, 13: 29, 14: 36, 15: 11, 16: 35, 17: 27, 18: 28, 19: 1, 20: 8, 21: 26, 22: 6, 23: 24, 24: 16, 25: 31, 26: 4, 27: 37, 28: 20, 29: 12, 30: 18, 31: 7, 32: 33, 33: 5, 34: 17, 35: 23, 36: 14}, 'CC1CCC2C(C)C(O)OC3OC4(C)CCC1C32OO4': {0: 36, 1: 43, 2: 41, 3: 54, 4: 56, 5: 36, 6: 45, 7: 30, 8: 19, 9: 49, 10: 45, 11: 64, 12: 92, 13: 50, 14: 49, 15: 70, 16: 72, 17: 100, 18: 57, 19: 42}, 'CC1OC(n2cc(F)c(N)nc2=O)C(O)C1O': {0: 48, 1: 36, 2: 52, 3: 49, 4: 49, 5: 64, 6: 89, 7: 89, 8: 85, 9: 22, 10: 55, 11: 95, 12: 60, 13: 44, 14: 24, 15: 35, 16: 22}, 'CCC(=O)N1CCC(Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 48, 1: 65, 2: 101, 3: 81, 4: 44, 5: 59, 6: 50, 7: 72, 8: 36, 9: 138, 10: 87, 11: 102, 12: 72, 13: 136, 14: 139, 15: 77, 16: 43, 17: 154, 18: 100, 19: 55, 20: 152, 21: 44, 22: 141, 23: 166, 24: 159, 25: 165, 26: 171, 27: 78, 28: 80, 29: 78, 30: 83}, 'CCC(=O)N1CCC(Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 48, 1: 67, 2: 103, 3: 83, 4: 38, 5: 61, 6: 55, 7: 76, 8: 33, 9: 146, 10: 87, 11: 105, 12: 83, 13: 136, 14: 140, 15: 82, 16: 36, 17: 156, 18: 104, 19: 59, 20: 162, 21: 74, 22: 79, 23: 148, 24: 171, 25: 161, 26: 167, 27: 173, 28: 79, 29: 85, 30: 84, 31: 87}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OCC5COC(Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 71, 1: 84, 2: 99, 3: 78, 4: 112, 5: 134, 6: 173, 7: 108, 8: 227, 9: 146, 10: 126, 11: 238, 12: 29, 13: 111, 14: 102, 15: 18, 16: 236, 17: 127, 18: 106, 19: 234, 20: 97, 21: 133, 22: 134, 23: 115, 24: 97, 25: 248, 26: 134, 27: 144, 28: 175, 29: 127, 30: 175, 31: 160, 32: 235, 33: 167, 34: 140, 35: 225, 36: 245, 37: 158, 38: 253, 39: 259, 40: 104, 41: 112, 42: 152, 43: 130, 44: 141, 45: 160, 46: 181, 47: 257, 48: 133}, 'CCC(c1cc(O)cc(O)c1)C(C)CN(C)C': {0: 37, 1: 44, 2: 58, 3: 90, 4: 51, 5: 89, 6: 20, 7: 38, 8: 95, 9: 26, 10: 57, 11: 54, 12: 58, 13: 61, 14: 30, 15: 52, 16: 58}, 'CCC(c1cccc(O)c1)C(C)CN(C)C': {0: 38, 1: 46, 2: 50, 3: 89, 4: 56, 5: 44, 6: 33, 7: 88, 8: 20, 9: 54, 10: 54, 11: 56, 12: 60, 13: 20, 14: 51, 15: 57}, 'CCC1C(=O)OCC1Cc1cncn1C': {0: 34, 1: 35, 2: 44, 3: 63, 4: 49, 5: 45, 6: 49, 7: 37, 8: 47, 9: 85, 10: 59, 11: 31, 12: 59, 13: 36, 14: 47}, 'CCCCCC(=O)C=CC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 48, 1: 54, 2: 75, 3: 62, 4: 92, 5: 103, 6: 77, 7: 71, 8: 74, 9: 60, 10: 65, 11: 32, 12: 76, 13: 126, 14: 85, 15: 75, 16: 85, 17: 93, 18: 87, 19: 86, 20: 66, 21: 78, 22: 110, 23: 112, 24: 58}, 'CCCCCC(=O)CCC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 39, 1: 45, 2: 67, 3: 58, 4: 91, 5: 101, 6: 81, 7: 108, 8: 85, 9: 51, 10: 74, 11: 30, 12: 81, 13: 112, 14: 85, 15: 86, 16: 84, 17: 94, 18: 79, 19: 83, 20: 67, 21: 74, 22: 108, 23: 108, 24: 59}, 'CCCCCC(O)C=CC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 6, 1: 10, 2: 16, 3: 11, 4: 21, 5: 24, 6: 1, 7: 13, 8: 23, 9: 14, 10: 22, 11: 2, 12: 8, 13: 25, 14: 4, 15: 15, 16: 9, 17: 17, 18: 18, 19: 19, 20: 7, 21: 20, 22: 12, 23: 5, 24: 3}, 'CCCCCOC(=O)Nc1nc(=O)n(C2OC(C)C(O)C2O)cc1F': {0: 49, 1: 57, 2: 64, 3: 73, 4: 69, 5: 77, 6: 108, 7: 84, 8: 31, 9: 121, 10: 89, 11: 132, 12: 90, 13: 71, 14: 74, 15: 73, 16: 61, 17: 78, 18: 48, 19: 29, 20: 63, 21: 31, 22: 105, 23: 137, 24: 136}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 60, 1: 54, 2: 75, 3: 153, 4: 84, 5: 152, 6: 87, 7: 176, 8: 166, 9: 91, 10: 104, 11: 173, 12: 170, 13: 111, 14: 164, 15: 94, 16: 105, 17: 111, 18: 43, 19: 87, 20: 84, 21: 30, 22: 78, 23: 79, 24: 92, 25: 97, 26: 96, 27: 122, 28: 179, 29: 70, 30: 96, 31: 92, 32: 71, 33: 124}, 'CCN(CC)C(=O)C1(c2ccccc2)CC1CN': {0: 40, 1: 52, 2: 29, 3: 58, 4: 48, 5: 91, 6: 58, 7: 103, 8: 98, 9: 63, 10: 40, 11: 33, 12: 46, 13: 69, 14: 62, 15: 56, 16: 67, 17: 13}, 'CCNC1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 54, 1: 57, 2: 22, 3: 71, 4: 58, 5: 35, 6: 62, 7: 64, 8: 38, 9: 46, 10: 51, 11: 79, 12: 86, 13: 92, 14: 118, 15: 105, 16: 107, 17: 72, 18: 30, 19: 84, 20: 90, 21: 105, 22: 130}, 'CCOC1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)C(c2ccc(C(=O)O)cc2)C1': {0: 57, 1: 48, 2: 59, 3: 79, 4: 73, 5: 76, 6: 29, 7: 95, 8: 152, 9: 161, 10: 71, 11: 86, 12: 79, 13: 152, 14: 80, 15: 166, 16: 34, 17: 107, 18: 77, 19: 167, 20: 93, 21: 166, 22: 87, 23: 70, 24: 154, 25: 121, 26: 122, 27: 50, 28: 76, 29: 94, 30: 95}, 'CCOc1ccc(O)cc1OCCNC(C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 68, 1: 72, 2: 59, 3: 140, 4: 79, 5: 61, 6: 145, 7: 32, 8: 71, 9: 147, 10: 72, 11: 84, 12: 85, 13: 23, 14: 75, 15: 70, 16: 80, 17: 152, 18: 97, 19: 84, 20: 154, 21: 70, 22: 86, 23: 143, 24: 94, 25: 42, 26: 109, 27: 115, 28: 101}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 37, 1: 15, 2: 43, 3: 57, 4: 63, 5: 63, 6: 113, 7: 114, 8: 65, 9: 37, 10: 112, 11: 118, 12: 43, 13: 71, 14: 41, 15: 50, 16: 119, 17: 82, 18: 118, 19: 107, 20: 38, 21: 78, 22: 97, 23: 119}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 8, 1: 7, 2: 9, 3: 11, 4: 10, 5: 20, 6: 16, 7: 3, 8: 18, 9: 17, 10: 19, 11: 1, 12: 21, 13: 5, 14: 6, 15: 13, 16: 2, 17: 12, 18: 4, 19: 15, 20: 14}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 35, 1: 18, 2: 41, 3: 53, 4: 51, 5: 98, 6: 68, 7: 27, 8: 107, 9: 48, 10: 50, 11: 108, 12: 54, 13: 53, 14: 76, 15: 55, 16: 74, 17: 73, 18: 61, 19: 110}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 52, 1: 25, 2: 91, 3: 56, 4: 53, 5: 92, 6: 64, 7: 27, 8: 109, 9: 58, 10: 35, 11: 98, 12: 21, 13: 41, 14: 64, 15: 117, 16: 72, 17: 103, 18: 118, 19: 45, 20: 52, 21: 125}, 'CN1CCC(NC(=O)Nc2ccc(C#N)cc2)CC1c1nc2ccccc2[nH]1': {0: 82, 1: 31, 2: 72, 3: 68, 4: 87, 5: 33, 6: 133, 7: 94, 8: 31, 9: 139, 10: 91, 11: 70, 12: 135, 13: 122, 14: 57, 15: 76, 16: 99, 17: 74, 18: 90, 19: 149, 20: 69, 21: 156, 22: 58, 23: 80, 24: 74, 25: 59, 26: 157, 27: 50}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 66, 1: 24, 2: 111, 3: 75, 4: 141, 5: 75, 6: 138, 7: 69, 8: 138, 9: 51, 10: 61, 11: 141, 12: 26, 13: 129, 14: 88, 15: 28, 16: 143, 17: 72, 18: 62, 19: 139, 20: 145, 21: 134, 22: 174, 23: 158, 24: 164, 25: 170, 26: 74, 27: 67, 28: 57, 29: 90, 30: 106, 31: 52}, 'CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(CC(O)(c2cc(F)ccc2F)C(C)c2nc(-c3ccc(C#N)cc3)cs2)c1': {0: 63, 1: 35, 2: 69, 3: 119, 4: 123, 5: 115, 6: 88, 7: 176, 8: 79, 9: 73, 10: 103, 11: 116, 12: 194, 13: 51, 14: 106, 15: 154, 16: 151, 17: 124, 18: 102, 19: 79, 20: 105, 21: 145, 22: 134, 23: 127, 24: 99, 25: 216, 26: 52, 27: 193, 28: 120, 29: 200, 30: 227, 31: 87, 32: 102, 33: 211, 34: 237, 35: 103, 36: 96, 37: 205, 38: 136, 39: 208, 40: 204, 41: 99, 42: 106, 43: 206, 44: 166, 45: 65, 46: 113, 47: 108, 48: 120, 49: 151, 50: 169}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 39, 1: 14, 2: 53, 3: 56, 4: 60, 5: 113, 6: 104, 7: 63, 8: 33, 9: 107, 10: 111, 11: 39, 12: 71, 13: 39, 14: 46, 15: 114, 16: 74, 17: 112, 18: 100, 19: 37, 20: 67, 21: 89, 22: 115}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 89, 1: 77, 2: 162, 3: 161, 4: 92, 5: 87, 6: 90, 7: 84, 8: 36, 9: 80, 10: 56, 11: 68, 12: 62, 13: 88, 14: 112, 15: 102, 16: 172, 17: 166, 18: 122, 19: 183, 20: 45, 21: 145, 22: 134, 23: 185, 24: 113, 25: 115, 26: 184, 27: 23, 28: 122, 29: 122, 30: 90, 31: 85, 32: 103, 33: 31, 34: 194}, 'COc1cc(C)c2[nH]ccc2c1CN1CCC(O)CC1c1ccc(C(=O)O)cc1': {0: 72, 1: 66, 2: 145, 3: 70, 4: 132, 5: 69, 6: 150, 7: 35, 8: 92, 9: 81, 10: 157, 11: 147, 12: 94, 13: 28, 14: 79, 15: 58, 16: 53, 17: 28, 18: 80, 19: 84, 20: 151, 21: 78, 22: 68, 23: 146, 24: 110, 25: 129, 26: 48, 27: 74, 28: 86}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 73, 1: 68, 2: 140, 3: 73, 4: 162, 5: 16, 6: 153, 7: 164, 8: 136, 9: 68, 10: 107, 11: 88, 12: 163, 13: 103, 14: 153, 15: 79, 16: 85, 17: 90, 18: 88, 19: 33, 20: 87, 21: 82, 22: 31, 23: 89, 24: 89, 25: 96, 26: 172, 27: 71, 28: 104, 29: 115, 30: 187, 31: 182, 32: 183, 33: 109, 34: 168, 35: 189}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 73, 1: 65, 2: 151, 3: 74, 4: 157, 5: 71, 6: 81, 7: 85, 8: 168, 9: 49, 10: 90, 11: 80, 12: 27, 13: 69, 14: 57, 15: 63, 16: 173, 17: 96, 18: 74, 19: 175, 20: 57, 21: 129, 22: 169, 23: 168, 24: 118, 25: 113, 26: 110, 27: 82, 28: 101, 29: 85, 30: 181, 31: 84, 32: 91}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1C(NC(C)=O)CC2': {0: 7, 1: 9, 2: 27, 3: 20, 4: 23, 5: 19, 6: 28, 7: 13, 8: 5, 9: 29, 10: 12, 11: 6, 12: 14, 13: 21, 14: 17, 15: 25, 16: 10, 17: 8, 18: 24, 19: 3, 20: 22, 21: 18, 22: 15, 23: 2, 24: 26, 25: 16, 26: 1, 27: 11, 28: 4}, 'COc1cc2c(cc1OC)C1CC(O)C(CC(C)C)CN1CC2': {0: 58, 1: 54, 2: 114, 3: 75, 4: 112, 5: 117, 6: 84, 7: 121, 8: 61, 9: 66, 10: 74, 11: 69, 12: 65, 13: 24, 14: 64, 15: 67, 16: 67, 17: 57, 18: 63, 19: 80, 20: 32, 21: 61, 22: 71}, 'COc1ccc(CC(C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 5, 1: 11, 2: 24, 3: 19, 4: 18, 5: 25, 6: 12, 7: 13, 8: 7, 9: 2, 10: 15, 11: 10, 12: 4, 13: 23, 14: 14, 15: 8, 16: 6, 17: 9, 18: 22, 19: 1, 20: 21, 21: 26, 22: 20, 23: 3, 24: 16, 25: 17}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 47, 1: 48, 2: 103, 3: 49, 4: 56, 5: 120, 6: 45, 7: 104, 8: 55, 9: 66, 10: 53, 11: 116, 12: 52, 13: 76, 14: 116, 15: 59, 16: 115, 17: 55, 18: 66, 19: 122, 20: 65, 21: 30, 22: 130, 23: 52}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3': {0: 59, 1: 60, 2: 135, 3: 57, 4: 65, 5: 69, 6: 121, 7: 132, 8: 102, 9: 82, 10: 145, 11: 136, 12: 40, 13: 121, 14: 137, 15: 144, 16: 46, 17: 121, 18: 104, 19: 80, 20: 73, 21: 171, 22: 25, 23: 69, 24: 81, 25: 75, 26: 19, 27: 68, 28: 73}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1': {0: 10, 1: 11, 2: 30, 3: 15, 4: 14, 5: 21, 6: 27, 7: 31, 8: 28, 9: 7, 10: 38, 11: 32, 12: 3, 13: 35, 14: 34, 15: 37, 16: 2, 17: 36, 18: 26, 19: 6, 20: 18, 21: 39, 22: 5, 23: 29, 24: 8, 25: 16, 26: 1, 27: 19, 28: 23, 29: 17, 30: 25, 31: 20, 32: 22, 33: 9, 34: 33, 35: 4, 36: 24, 37: 13, 38: 12}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(O)CO)CC3': {0: 63, 1: 64, 2: 138, 3: 65, 4: 70, 5: 69, 6: 123, 7: 126, 8: 103, 9: 87, 10: 146, 11: 137, 12: 47, 13: 117, 14: 135, 15: 144, 16: 51, 17: 130, 18: 108, 19: 83, 20: 79, 21: 171, 22: 29, 23: 64, 24: 25, 25: 74, 26: 18, 27: 71, 28: 73}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(O)CO)CC3OC1CC(N)C(O)C(C)O1': {0: 101, 1: 93, 2: 181, 3: 90, 4: 98, 5: 109, 6: 168, 7: 180, 8: 160, 9: 125, 10: 195, 11: 199, 12: 72, 13: 181, 14: 192, 15: 208, 16: 65, 17: 198, 18: 161, 19: 119, 20: 116, 21: 229, 22: 47, 23: 94, 24: 38, 25: 100, 26: 30, 27: 119, 28: 121, 29: 110, 30: 83, 31: 98, 32: 115, 33: 55, 34: 93, 35: 36, 36: 83, 37: 112, 38: 106}, 'COc1nc(N)nc2[nH]cnc12': {0: 26, 1: 27, 2: 45, 3: 32, 4: 51, 5: 6, 6: 29, 7: 49, 8: 16, 9: 35, 10: 16, 11: 58}, 'COc1nc(N)nc2c1ncn2C1OC(CO)C(O)C1O': {0: 56, 1: 64, 2: 103, 3: 72, 4: 108, 5: 27, 6: 82, 7: 114, 8: 119, 9: 57, 10: 93, 11: 60, 12: 71, 13: 64, 14: 47, 15: 64, 16: 19, 17: 45, 18: 31, 19: 57, 20: 33}, 'COc1nc2ccc(Br)cc2cc1C(c1ccccc1)C(O)(CCN(C)C)c1cccc2ccccc12': {0: 80, 1: 80, 2: 176, 3: 93, 4: 182, 5: 84, 6: 63, 7: 175, 8: 173, 9: 76, 10: 179, 11: 138, 12: 187, 13: 97, 14: 173, 15: 108, 16: 67, 17: 53, 18: 73, 19: 114, 20: 194, 21: 42, 22: 101, 23: 92, 24: 33, 25: 81, 26: 87, 27: 192, 28: 150, 29: 109, 30: 66, 31: 182, 32: 70, 33: 65, 34: 84, 35: 100, 36: 199}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 41, 1: 47, 2: 99, 3: 37, 4: 61, 5: 97, 6: 19, 7: 42, 8: 43, 9: 91, 10: 47, 11: 65, 12: 54, 13: 104, 14: 15, 15: 100, 16: 54, 17: 50, 18: 99, 19: 122, 20: 117, 21: 123, 22: 129}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 54, 1: 53, 2: 73, 3: 79, 4: 117, 5: 67, 6: 59, 7: 128, 8: 99, 9: 69, 10: 18, 11: 139, 12: 61, 13: 132, 14: 30, 15: 136, 16: 142, 17: 127, 18: 140, 19: 60, 20: 40, 21: 41, 22: 84, 23: 50, 24: 67, 25: 138, 26: 152, 27: 81}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 52, 1: 51, 2: 71, 3: 77, 4: 116, 5: 64, 6: 58, 7: 129, 8: 100, 9: 69, 10: 19, 11: 123, 12: 53, 13: 69, 14: 129, 15: 139, 16: 131, 17: 140, 18: 59, 19: 37, 20: 136, 21: 29, 22: 84, 23: 51, 24: 78, 25: 141, 26: 151, 27: 80}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 7, 1: 15, 2: 5, 3: 6, 4: 22, 5: 14, 6: 16, 7: 26, 8: 21, 9: 3, 10: 2, 11: 20, 12: 17, 13: 13, 14: 23, 15: 10, 16: 27, 17: 24, 18: 12, 19: 4, 20: 9, 21: 8, 22: 1, 23: 19, 24: 25, 25: 11, 26: 18}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 58, 1: 142, 2: 149, 3: 79, 4: 81, 5: 72, 6: 147, 7: 29, 8: 155, 9: 67, 10: 59, 11: 135, 12: 160, 13: 59, 14: 153, 15: 168, 16: 164, 17: 153, 18: 92, 19: 74, 20: 83, 21: 72, 22: 78, 23: 175, 24: 111, 25: 85, 26: 171, 27: 106, 28: 61, 29: 177, 30: 31, 31: 164, 32: 19, 33: 86, 34: 165}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O)cc2[nH]1': {0: 48, 1: 106, 2: 106, 3: 48, 4: 64, 5: 133, 6: 122, 7: 128, 8: 134, 9: 58, 10: 79, 11: 51, 12: 115, 13: 56, 14: 67, 15: 62, 16: 116, 17: 50, 18: 130, 19: 50, 20: 45, 21: 112, 22: 24, 23: 46, 24: 125, 25: 31}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(OC3OC(C(=O)O)C(O)C(O)C3O)cc2[nH]1': {0: 8, 1: 37, 2: 31, 3: 11, 4: 22, 5: 38, 6: 14, 7: 15, 8: 16, 9: 17, 10: 20, 11: 10, 12: 34, 13: 21, 14: 26, 15: 6, 16: 23, 17: 9, 18: 36, 19: 24, 20: 18, 21: 32, 22: 13, 23: 30, 24: 12, 25: 29, 26: 19, 27: 5, 28: 3, 29: 27, 30: 1, 31: 28, 32: 2, 33: 33, 34: 4, 35: 25, 36: 35, 37: 7}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccccc2[nH]1': {0: 49, 1: 105, 2: 105, 3: 47, 4: 63, 5: 128, 6: 118, 7: 124, 8: 130, 9: 60, 10: 81, 11: 50, 12: 111, 13: 55, 14: 65, 15: 61, 16: 113, 17: 45, 18: 121, 19: 43, 20: 42, 21: 41, 22: 45, 23: 120, 24: 28}, 'Cc1c(OCC(F)(F)F)ccnc1C[S+](O)c1nc2c(OS(=O)(=O)O)cccc2[nH]1': {0: 59, 1: 126, 2: 129, 3: 57, 4: 85, 5: 154, 6: 137, 7: 143, 8: 149, 9: 73, 10: 98, 11: 59, 12: 138, 13: 77, 14: 41, 15: 37, 16: 137, 17: 64, 18: 147, 19: 136, 20: 67, 21: 70, 22: 90, 23: 96, 24: 37, 25: 67, 26: 62, 27: 63, 28: 154, 29: 38}, 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1': {0: 77, 1: 148, 2: 96, 3: 147, 4: 33, 5: 146, 6: 98, 7: 112, 8: 139, 9: 131, 10: 99, 11: 34, 12: 161, 13: 156, 14: 87, 15: 65, 16: 61, 17: 74, 18: 164, 19: 169, 20: 115, 21: 101, 22: 182, 23: 44, 24: 91, 25: 77, 26: 35, 27: 96, 28: 91, 29: 34, 30: 85, 31: 101, 32: 117}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2': {0: 6, 1: 20, 2: 1, 3: 11, 4: 19, 5: 3, 6: 15, 7: 18, 8: 10, 9: 21, 10: 7, 11: 17, 12: 16, 13: 13, 14: 23, 15: 14, 16: 9, 17: 5, 18: 12, 19: 22, 20: 8, 21: 2, 22: 4}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O': {0: 36, 1: 106, 2: 57, 3: 74, 4: 111, 5: 51, 6: 111, 7: 78, 8: 42, 9: 112, 10: 115, 11: 68, 12: 118, 13: 90, 14: 124, 15: 48, 16: 39, 17: 25, 18: 47, 19: 113, 20: 128, 21: 19, 22: 65, 23: 23}, 'Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2': {0: 5, 1: 22, 2: 12, 3: 16, 4: 19, 5: 20, 6: 17, 7: 3, 8: 15, 9: 4, 10: 6, 11: 8, 12: 2, 13: 9, 14: 7, 15: 21, 16: 13, 17: 10, 18: 11, 19: 14, 20: 18, 21: 1}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N(CC(=O)O)CC(=O)O)cc3)n2)cc1': {0: 62, 1: 130, 2: 80, 3: 31, 4: 133, 5: 101, 6: 152, 7: 78, 8: 89, 9: 163, 10: 159, 11: 97, 12: 111, 13: 100, 14: 183, 15: 35, 16: 169, 17: 85, 18: 65, 19: 186, 20: 44, 21: 103, 22: 138, 23: 120, 24: 45, 25: 110, 26: 145, 27: 126, 28: 51, 29: 71, 30: 96, 31: 101, 32: 110, 33: 101}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1': {0: 8, 1: 24, 2: 11, 3: 3, 4: 27, 5: 7, 6: 30, 7: 12, 8: 20, 9: 31, 10: 28, 11: 23, 12: 22, 13: 2, 14: 25, 15: 1, 16: 26, 17: 14, 18: 18, 19: 29, 20: 6, 21: 16, 22: 9, 23: 5, 24: 10, 25: 17, 26: 19, 27: 15, 28: 4, 29: 21, 30: 13}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)n2)cc1': {0: 55, 1: 123, 2: 78, 3: 30, 4: 131, 5: 95, 6: 151, 7: 72, 8: 87, 9: 157, 10: 152, 11: 94, 12: 111, 13: 101, 14: 169, 15: 30, 16: 165, 17: 84, 18: 88, 19: 174, 20: 40, 21: 89, 22: 63, 23: 56, 24: 70, 25: 143, 26: 100, 27: 99, 28: 97, 29: 77, 30: 109,

In [143]:
from rdkit import Chem
def canonicalsmiles_noisomeric(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [144]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
xenosite_results = [result_new[canonicalsmiles_noisomeric(i)] for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,somp_results,xenosite_results,smartcyp_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ...","{0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: ...","{0: 49, 1: 91, 2: 68, 3: 67, 4: 115, 5: 48, 6:...","{0: 14, 1: 60, 2: 32, 3: 6, 4: 57, 5: 49, 6: 4..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20...","{0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6:...","{0: 42, 1: 63, 2: 57, 3: 15, 4: 95, 5: 38, 6: ...","{0: 7, 1: 42, 2: 39, 3: 29, 4: 54, 5: 19, 6: 3..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17...","{0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, ...","{0: 71, 1: 119, 2: 88, 3: 19, 4: 157, 5: 76, 6...","{0: 4, 1: 49, 2: 45, 3: 34, 4: 58, 5: 23, 6: 3..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19...","{0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6:...","{0: 47, 1: 145, 2: 54, 3: 60, 4: 133, 5: 87, 6...","{0: 16, 1: 39, 2: 16, 3: 16, 4: 45, 5: 29, 6: ..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40...","{0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6:...","{0: 12, 1: 40, 2: 13, 3: 14, 4: 37, 5: 36, 6: ...","{0: 22, 1: 62, 2: 22, 3: 22, 4: 70, 5: 26, 6: ..."
...,...,...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23...",None,"{0: 1, 1: 28, 2: 31, 3: 19, 4: 3, 5: 12, 6: 4,...","{0: 42, 1: 47, 2: 39, 3: 31, 4: 24, 5: 14, 6: ..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12...","{0: 149, 1: 31, 2: 140, 3: 62, 4: 160, 5: 157,...","{0: 35, 1: 76, 2: 81, 3: 104, 4: 99, 5: 162, 6...","{0: 48, 1: 3, 2: 15, 3: 57, 4: 29, 5: 68, 6: 4..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7...","{0: 61, 1: 13, 2: 82, 3: 46, 4: 64, 5: 99, 6: ...","{0: 19, 1: 40, 2: 107, 3: 52, 4: 72, 5: 113, 6...","{0: 42, 1: 4, 2: 48, 3: 32, 4: 12, 5: 51, 6: 3..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ...",None,"{0: 36, 1: 167, 2: 70, 3: 95, 4: 160, 5: 87, 6...","{0: 36, 1: 39, 2: 18, 3: 33, 4: 48, 5: 10, 6: ..."
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7...","{0: 13, 1: 48, 2: 43, 3: 58, 4: 52, 5: 25, 6: ...","{0: 36, 1: 38, 2: 41, 3: 67, 4: 24, 5: 39, 6: ...","{0: 12, 1: 19, 2: 15, 3: 24, 4: 15, 5: 4, 6: 1..."

In [145]:
df_total.to_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')

5-6. metapredictor和our model

In [146]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

def df_col_getatomindices(dfname,col_old,flat=False):
    preds = dfname[col_old].to_list()
    preds = [i.split('|') for i in preds]
    try:
        preds = [list(map(standardize_smiles_with_atom_map,i)) for i in preds]
        ranks = [list(map(get_reactive_atom_indices,i)) for i in preds]
    except:
        ranks = []
        for k in preds:
            preds_part = []
            for x in k:
                try:
                    x = standardize_smiles_with_atom_map(x)
                    x_new = get_reactive_atom_indices(x)
                except:
                    x_new = []
                preds_part.append(x_new)
            ranks.append(preds_part)
    if flat == True:
        ranks_new = []
        for i in ranks:
            list_part = []
            for j in i:
                list_part = list_part + j
            ranks_new.append(list_part)
        return ranks_new
    else:
        return ranks
    
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [147]:
df = pd.read_csv('all_123.csv')
substrate = df['substrate'].to_list()
substrate = list(map(canonicalsmiles,substrate))
sites_true = df_col_getatomindices(df,'site_truth',flat=True)
metapredictor_predict = df_col_getatomindices(df,'metapredictor_predict',flat=False)
our_predict = df_col_getatomindices(df,'our_predict',flat=False)
df['substrate'] = substrate
df['sites'] = sites_true
df['metapredictor_ranks'] = metapredictor_predict
df['ourmodel_ranks'] = our_predict
df

[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] SMILES Parse Error: extra open parentheses for input: 'CCOc1cc(OCCN[C@H](C)Cc2ccc(OC)c(S(N)(=O)=O)c2)cc([OH:1]'
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:25] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] SMILES Parse Error: extra open parentheses for input: 'CN(C(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(C[C@](O)(c2cc(F)ccc2F)[C@@H](C)c2nc(-c3ccc(C#N)cc3)[cH:1]s2)c1'
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] SMILES Parse Error: extra open parentheses for input: 'CN(C(=O)OCc1cccnc1N(C)C(=O)[O:1]C(C)[n+]1cnn(C[C@](O)(c2cc(F)ccc2F)[C@@H](C)c2nc(-c3ccc(C#N)cc3)cs2)c1'
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] SMILES Parse Error: unclosed ring for input: 'Cc1cc([O:1]C)c(CN2CC[C@H](O)C[C@H]2c2ccc(C(=O)O)cc2)c2cc[nH]c1'
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger

[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] SMILES Parse Error: extra open parentheses for input: 'O=[N+]([O-])c1ccc2c(c1)C(c1ccccc1Cl)=NC(O)[C:1](=[O:1]'
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] SMILES Parse Error: syntax error while parsing: Error:
[06:18:26] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:26] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] SMILES Parse Error: syntax error while parsing: Error:
[06:18:27] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger
[06:18:27] Running Uncharger

,substrate,metapredictor_predict,site_truth,site_count,our_predict,sites,metapredictor_ranks,ourmodel_ranks
0,c1cnc(N2CCNCC2)nc1,c1nc(N2CCNCC2)nc[cH:1]1|c1nc(N2CCNCC2)n[cH:1]c...,c1nc(N2CCNCC2)nc[cH:1]1,1,[CH:1]1=CN=C(N2CCNCC2)N=C1|C1=CN=C(N2CCN[CH2:1...,[11],"[[11], [2], [8], [7], [2, 11], [3, 5, 6, 7], [...","[[11], [8], [7], [7], [9], [8], [9], [7], [2],..."
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/[C:1]12O[C:1]1(C)CCCC2(C)C)=C\C=C\C(C)...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,1,C12(/C=C/C(C)=C/C=C/C(C)=C/C([OH:1])=O)OC1(C)C...,"[20, 22]","[[4, 6], [22], [9], [10], [13], [4, 11, 13], [...","[[22], [4], [4], [8], [10], [9], [22], [22], [..."
2,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=N[CH2:1]C(=O)N2,1,CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=N[CH2:1]...,[19],"[[3], [19], [14], [20, 21, 22], [20, 22], [9, ...","[[19], [18], [14], [20], [19], [13], [15], [18..."
3,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,2,CC(=O)NC1=[CH:1]C=CC(N2C(=O)N(C3CC3)C(=O)C3=C(...,"[3, 2, 3, 36]","[[3], [29], [20], [24], [30], [34], [26], [15]...","[[36], [27], [28], [34], [7], [34], [35], [23]..."
4,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,1,CC(C)([CH3:1])C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=...,[10],"[[12], [7], [26], [12], [17], [7, 11, 12, 27, ...","[[10], [10], [12], [21], [12], [20], [23], [13..."
...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OC(c1ccccc1)(c1ccccc1)C12CC[N+:1](CCOCc3ccccc3...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3cc[cH:1]...,2,OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCO[CH2:...,"[25, 20]","[[17], [20], [17, 20], [11], [25], [11], [19],...","[[21], [17], [11], [31], [25], [30], [12], [21..."
119,OC(Cl)(Cl)C(c1ccc(Cl)cc1)c1ccccc1Cl,O[C:1](Cl)(Cl)C(c1ccc(Cl)cc1)c1ccccc1Cl|Clc1cc...,Clc1ccc(C(c2ccccc2Cl)[C:1](Cl)(Cl)[OH:1])cc1,1,OC(Cl)(Cl)C(C1=CC=C(Cl)C=C1)C1=CC=[CH:1]C=C1Cl...,"[13, 16]","[[1], [16], [15], [4], [18], [1, 18], [1, 4], ...","[[15], [14], [15], [4], [16], [14], [1], [10],..."
120,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4cc[cH:1]c...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccc([OH:...,1,OC1=CC=C([CH2:1]OCC[N+]23CCC(C(O)(C4=CC=CC=C4)...,[26],"[[24], [30], [9], [26], [24], [6], [32], [26],...","[[5], [32], [30], [26], [26], [9], [24], [31],..."
121,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,Fc1ccccc1C1=NCc2cnc(C[OH:1])n2-c2ccc(Cl)cc21|O...,Fc1ccccc1C1=NCc2cnc(C[OH:1])n2-c2ccc(Cl)cc21|O...,3,OCC1=NC=C2N1C1=CC=C(Cl)C=C1[C:1](C1=CC=CC=C1F)...,"[15, 6, 23]","[[15], [1], [14, 15], [6], [15, 20], [9, 15], ...","[[14], [14, 23], [15], [23], [14], [14, 23], [..."
122,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,4,C1C(OC[CH2:1]OC2=CC=C(CC3=C(Cl)C=CC([C@H]4[C@H...,"[28, 29, 19, 18, 19, 11]","[[27], [29], [29], [19], [16], [28, 29], [18, ...","[[17], [22], [29], [18], [24], [18], [25], [11..."

In [148]:
dict_sub2sitetrue = dict(zip(substrate,sites_true))
dict_sub2metarank = dict(zip(substrate,metapredictor_predict))
print(len(list(dict_sub2sitetrue.keys())))

123

In [149]:
df = pd.read_csv('predict_site_123_top6_seed_2024.csv')
substrate = df['substrate'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['substrate'] = substrate
sites_true = [dict_sub2sitetrue[i] for i in substrate]
metapredictor_predict = [dict_sub2metarank[i] for i in substrate]
df['site_truth'] = sites_true
# sites_true = df_col_getatomindices(df,'site_truth',flat=True)
# metapredictor_predict = df_col_getatomindices(df,'metapredictor_predict',flat=False)
our_predict = df_col_getatomindices(df,'pred_site',flat=False)
df['sites'] = sites_true
df['metapredictor_ranks'] = metapredictor_predict
df['ourmodel_ranks'] = our_predict
df

[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:30] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger
[06:18:31] Running Uncharger

,Unnamed: 0,substrate,predict,pred_site,site_truth,sites,metapredictor_ranks,ourmodel_ranks
0,0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","[20, 22]","[[4, 6], [22], [9], [10], [13], [4, 11, 13], [...","[[20, 22], [11, 13], [20, 22], [10], [20, 22],..."
1,1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],[19],"[[3], [19], [14], [20, 21, 22], [20, 22], [9, ...","[[3], [19], [18], [3, 10, 18], [3, 10, 18, 19]..."
2,2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","[3, 2, 3, 36]","[[3], [29], [20], [24], [30], [34], [26], [15]...","[[3], [36], [29], [7], [28], [34], [23], [35],..."
3,3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(NC(=O)C2=CNC3=CC=CC...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(NC(=O)c2c[nH]c3c...,[10],[10],"[[12], [7], [26], [12], [17], [7, 11, 12, 27, ...","[[10], [11, 12], [10], [12], [21], [20], [11, ..."
4,4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],[39],"[[39], [32], [7], [1, 39], [27], [39], [27, 32...","[[39], [30, 31], [26, 30], [32], [24], [4, 5, ..."
...,...,...,...,...,...,...,...,...
118,118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","[25, 20]","[[17], [20], [17, 20], [11], [25], [11], [19],...","[[20], [17], [25], [11], [25], [30], [31], [18..."
119,119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,O=C(O)C1OC(O[C@@H]2[C@@H](O)[C@H](C3=CC=C(Cl)C...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,"[28, 29, 19, 18, 19, 11]","[28, 29, 19, 18, 19, 11]","[[27], [29], [29], [19], [16], [28, 29], [18, ...","[[28, 29], [16], [19], [22], [24], [18, 19], [..."
120,120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","[15, 6, 23]","[[15], [1], [14, 15], [6], [15, 20], [9, 15], ...","[[23], [14, 15], [2], [23], [15], [1], [2, 5, ..."
121,121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],[26],"[[24], [30], [9], [26], [24], [6], [32], [26],...","[[6], [1, 17, 26], [30], [32], [10, 11, 12, 13..."
122,122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|ON1CCN(C2=NC=CC=N2)CC1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CC[NH:1]CC2)nc...,[11],[11],"[[11], [2], [8], [7], [2, 11], [3, 5, 6, 7], [...","[[11], [7], [8], [7], [7, 8], [9], [7], [9], [..."

In [150]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

In [151]:
metapredictor_results_old = df['metapredictor_ranks'].to_list()
ourmodel_results_old = df['ourmodel_ranks'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)
metapredictor_results_new = []
for i in metapredictor_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    metapredictor_results_new.append(list_part)

true_sites = df['sites'].to_list()

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites)
metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites)
metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites)
metapredictor_topn = []
metapredictor_topn.append(metapredictor_top1_acc)
metapredictor_topn.append(metapredictor_top3_acc)
metapredictor_topn.append(metapredictor_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.5609756097560976
top 3 accuracy = 0.8373983739837398
top 5 accuracy = 0.8861788617886179
top 1 accuracy = 0.5528455284552846
top 3 accuracy = 0.8617886178861789
top 5 accuracy = 0.9349593495934959

In [152]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['metapredictor_topn'] = metapredictor_topn
df['ourmodel_topn'] = ourmodel_topn
df

         top_n  metapredictor_topn  ourmodel_topn
0  top1_recall            0.560976       0.552846
1  top3_recall            0.837398       0.861789
2  top5_recall            0.886179       0.934959

7. 整理全部结果

In [153]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [154]:
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

In [155]:
import pandas as pd
df_total = pd.read_pickle('output_123_site_truth_correct_withatomidx_noenzyme.pickle')

In [156]:
gnn_results = df_total['gnn_results'].to_list()
smartcyp_results = df_total['smartcyp_results'].to_list()
xenosite_results = df_total['xenosite_results'].to_list()
somp_results = df_total['somp_results'].to_list()

gnn_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in gnn_results]
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in smartcyp_results]
xenosite_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in xenosite_results]
somp_sorted_atoms = []
for i in somp_results:
    try:
        sub_result = [k for k, v in sorted(i.items(), key=lambda item: item[1])]
    except:
        sub_result = ['None']
    somp_sorted_atoms.append(sub_result)
# somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in somp_results]

df_total['gnn_results'] = gnn_sorted_atoms
df_total['smartcyp_results'] = smartcyp_sorted_atoms
df_total['xenosite_results'] = xenosite_sorted_atoms
df_total['somp_results'] = somp_sorted_atoms
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,somp_results,xenosite_results,smartcyp_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","[6, 7, 12, 19, 20, 9, 22, 13, 8, 11, 4, 10, 16...","[8, 9, 7, 10, 12, 13, 15, 4, 3, 5, 0, 6, 18, 2...","[19, 22, 14, 5, 16, 0, 15, 9, 8, 18, 12, 3, 2,...","[3, 9, 8, 18, 0, 10, 7, 19, 12, 13, 15, 2, 14,..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"[20, 18, 1, 22, 21, 3, 19, 10, 14, 17, 5, 9, 0...","[19, 14, 5, 13, 0, 3, 15, 6, 12, 21, 9, 1, 18,...","[3, 22, 18, 14, 5, 12, 0, 13, 15, 6, 9, 2, 21,...","[19, 0, 18, 14, 13, 5, 15, 12, 3, 9, 6, 22, 2,..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","[29, 30, 3, 1, 25, 20, 9, 27, 7, 22, 0, 28, 31...","[30, 34, 5, 6, 23, 0, 22, 7, 24, 33, 26, 3, 29...","[3, 20, 23, 6, 22, 14, 0, 12, 15, 5, 29, 13, 3...","[0, 34, 23, 20, 26, 30, 7, 5, 14, 15, 22, 13, ..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"[13, 12, 14, 27, 28, 4, 15, 0, 26, 22, 3, 8, 9...","[0, 8, 2, 9, 21, 3, 10, 20, 26, 22, 7, 1, 19, ...","[12, 28, 17, 0, 20, 19, 2, 22, 3, 8, 21, 9, 25...","[28, 21, 20, 0, 2, 3, 17, 19, 22, 26, 8, 9, 10..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"[31, 29, 28, 32, 17, 8, 3, 1, 30, 27, 2, 0, 16...","[20, 1, 26, 0, 2, 25, 3, 29, 31, 12, 5, 37, 28...","[7, 30, 38, 10, 19, 27, 17, 9, 29, 31, 39, 0, ...","[28, 32, 26, 29, 31, 20, 27, 34, 0, 2, 3, 5, 1..."
...,...,...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","[1, 0, 19, 21, 20, 17, 16, 18, 30, 28, 25, 9, ...",[None],"[0, 20, 4, 6, 10, 12, 30, 17, 31, 16, 28, 5, 1...","[18, 17, 21, 5, 11, 19, 25, 16, 28, 30, 24, 26..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","[27, 0, 15, 26, 16, 1, 14, 28, 13, 17, 18, 6, ...","[19, 1, 23, 24, 20, 3, 9, 6, 13, 29, 32, 35, 2...","[0, 29, 31, 27, 20, 30, 1, 14, 2, 19, 11, 21, ...","[1, 20, 30, 2, 28, 18, 21, 22, 11, 26, 17, 4, ..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","[1, 0, 2, 22, 6, 16, 18, 3, 17, 5, 23, 19, 14,...","[1, 23, 18, 9, 17, 3, 8, 16, 19, 0, 4, 12, 2, ...","[0, 22, 18, 17, 1, 9, 16, 19, 6, 3, 23, 12, 4,...","[1, 23, 18, 4, 22, 17, 9, 19, 16, 3, 12, 8, 6,..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"[13, 14, 0, 6, 1, 7, 5, 9, 10, 28, 30, 19, 2, ...",[None],"[0, 14, 17, 18, 9, 19, 24, 23, 2, 25, 32, 6, 5...","[8, 9, 5, 7, 18, 24, 2, 32, 10, 28, 30, 17, 19..."
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"[4, 5, 6, 10, 8, 2, 9, 3, 7, 0, 11, 1]","[0, 5, 7, 6, 9, 8, 2, 1, 10, 4, 11, 3]","[7, 4, 6, 8, 0, 1, 5, 2, 9, 10, 11, 3]","[5, 9, 7, 0, 6, 8, 2, 4, 10, 1, 11, 3]"

In [157]:
df_total.to_pickle('output_123_site_truth_correct_withrank_noenzyme.pickle')

In [158]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

# 示例使用
nums = [1, 2, 2, 3, 4, 3, 5, 1, 6]
n = 4
result = get_unique_numbers(nums, n)
print(result)  # 输出: [1, 2, 3, 4]

[1, 2, 3, 4]

In [159]:
df_total = pd.read_pickle('output_123_site_truth_correct_withrank_noenzyme.pickle')

# metapredictor_results_old = df_total['metapredictor_results_old'].to_list()
# ourmodel_results_old = df_total['ourmodel_results_old'].to_list()
# ourmodel_results_new = []
# for i in ourmodel_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     ourmodel_results_new.append(list_part)
# metapredictor_results_new = []
# for i in metapredictor_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     metapredictor_results_new.append(list_part)

# true_sites_old = df_total['true_sites_old'].to_list()
true_sites = df_total['sites'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

# def acc_top_n_old(n,modelresults,true_sites):
#     total_num = len(true_sites)
#     correct_num = 0
#     for idx,i in enumerate(true_sites):
#         modelresult = modelresults[idx]
#         modelresult = get_unique_numbers(modelresult, n)
#         modelresult = set(modelresult)
#         i = set(i)
#         intersection = i & modelresult
#         if len(intersection) > 0:
#             correct_num = correct_num + 1
#     acc = correct_num/total_num
#     print(f'top {n} accuracy = {acc}')
#     return acc

gnn_top1_acc = acc_top_n(1,gnn_sorted_atoms,true_sites)
gnn_top3_acc = acc_top_n(3,gnn_sorted_atoms,true_sites)
gnn_top5_acc = acc_top_n(5,gnn_sorted_atoms,true_sites)
gnn_topn = []
gnn_topn.append(gnn_top1_acc)
gnn_topn.append(gnn_top3_acc)
gnn_topn.append(gnn_top5_acc)

smartcyp_top1_acc = acc_top_n(1,smartcyp_sorted_atoms,true_sites)
smartcyp_top3_acc = acc_top_n(3,smartcyp_sorted_atoms,true_sites)
smartcyp_top5_acc = acc_top_n(5,smartcyp_sorted_atoms,true_sites)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

xenosite_top1_acc = acc_top_n(1,xenosite_sorted_atoms,true_sites)
xenosite_top3_acc = acc_top_n(3,xenosite_sorted_atoms,true_sites)
xenosite_top5_acc = acc_top_n(5,xenosite_sorted_atoms,true_sites)
xenosite_topn = []
xenosite_topn.append(xenosite_top1_acc)
xenosite_topn.append(xenosite_top3_acc)
xenosite_topn.append(xenosite_top5_acc)

somp_top1_acc = acc_top_n(1,somp_sorted_atoms,true_sites)
somp_top3_acc = acc_top_n(3,somp_sorted_atoms,true_sites)
somp_top5_acc = acc_top_n(5,somp_sorted_atoms,true_sites)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

# metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites_old)
# metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites_old)
# metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites_old)
# metapredictor_topn = []
# metapredictor_topn.append(metapredictor_top1_acc)
# metapredictor_topn.append(metapredictor_top3_acc)
# metapredictor_topn.append(metapredictor_top5_acc)

# ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
# ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
# ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
# ourmodel_topn = []
# ourmodel_topn.append(ourmodel_top1_acc)
# ourmodel_topn.append(ourmodel_top3_acc)
# ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.13821138211382114
top 3 accuracy = 0.43089430894308944
top 5 accuracy = 0.6097560975609756
top 1 accuracy = 0.10569105691056911
top 3 accuracy = 0.3008130081300813
top 5 accuracy = 0.45528455284552843
top 1 accuracy = 0.2682926829268293
top 3 accuracy = 0.5040650406504065
top 5 accuracy = 0.6341463414634146
top 1 accuracy = 0.15447154471544716
top 3 accuracy = 0.35772357723577236
top 5 accuracy = 0.43089430894308944

In [160]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['gnnsom_topn'] = gnn_topn
df['smartcyp_topn'] = smartcyp_topn
df['xenosite_topn'] = xenosite_topn
df['somp_topn'] = somp_topn
df['metapredictor_topn'] = metapredictor_topn
df['ourmodel_topn'] = ourmodel_topn
# df['metapredictor_topn'] = metapredictor_topn
# df['ourmodel_topn'] = ourmodel_topn
df

         top_n  gnnsom_topn  smartcyp_topn  xenosite_topn  somp_topn
0  top1_recall     0.138211       0.105691       0.268293   0.154472
1  top3_recall     0.430894       0.300813       0.504065   0.357724
2  top5_recall     0.609756       0.455285       0.634146   0.430894