In [11]:
import pandas as pd
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
data=pd.read_csv("origin_128_argu10.csv")

In [12]:
def kekulize_smiles(smi):
    smi = smi.replace(' ','')
    mol = Chem.MolFromSmiles(smi)
    Chem.Kekulize(mol, clearAromaticFlags = True)
    smi = Chem.MolToSmiles(mol, canonical = False, kekuleSmiles = True)
    return smi

In [13]:
data['substrate']=data['substrate'].apply(kekulize_smiles)

In [14]:
data

                                              substrate
0       CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O
1     CC(/C=C/C=C(C)/C=C/C12C(C)(O1)CCCC2(C)C)=C\C(O)=O
2       O=C(O)/C=C(/C=C/C=C(C)/C=C/C12OC1(C)CCCC2(C)C)C
3       OC(/C=C(/C=C/C=C(/C=C/C12OC1(C)CCCC2(C)C)C)C)=O
4     C(/C=C(/C=C/C12OC1(C)CCCC2(C)C)C)=C\C(C)=C\C(O)=O
...                                                 ...
1275                              N1=C(N2CCNCC2)N=CC=C1
1276                              C1(N2CCNCC2)=NC=CC=N1
1277                              C1CN(C2=NC=CC=N2)CCN1
1278                              C1CN(C2=NC=CC=N2)CCN1
1279                              C1=NC(N2CCNCC2)=NC=C1

[1280 rows x 1 columns]

In [15]:
data=data['substrate'].to_list()

In [16]:
def space_out_letters(text):
    # 对字符串中的每个字符进行处理，用空格分隔
    # sections = text.split('|')
    # sections[0]
    return ' '.join(list(text))+" | <unk>"

data1=list(map(space_out_letters,data))

In [17]:
len(data1)

1280

In [18]:
result=pd.DataFrame(data1)

In [19]:
result

                                                      0
0     C C ( / C = C / C 1 2 O C 1 ( C ) C C C C 2 ( ...
1     C C ( / C = C / C = C ( C ) / C = C / C 1 2 C ...
2     O = C ( O ) / C = C ( / C = C / C = C ( C ) / ...
3     O C ( / C = C ( / C = C / C = C ( / C = C / C ...
4     C ( / C = C ( / C = C / C 1 2 O C 1 ( C ) C C ...
...                                                 ...
1275  N 1 = C ( N 2 C C N C C 2 ) N = C C = C 1 | <unk>
1276  C 1 ( N 2 C C N C C 2 ) = N C = C C = N 1 | <unk>
1277  C 1 C N ( C 2 = N C = C C = N 2 ) C C N 1 | <unk>
1278  C 1 C N ( C 2 = N C = C C = N 2 ) C C N 1 | <unk>
1279  C 1 = N C ( N 2 C C N C C 2 ) = N C = C 1 | <unk>

[1280 rows x 1 columns]

In [20]:
result.to_csv("test_128_input.txt",index=False,header=None)