In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("neutral_origin_test.csv")

In [3]:
data

,substrate,metabolite
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...
1,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O|CC(=O)CC1(CC(C...
2,CC(=O)Nc1ccc(O)cc1,CC(=O)N(c1ccc(O)cc1)[C@@H]1OC(C(=O)O)[C@@H](O)...
3,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,CC(C(=O)O)c1ccc(CC2CCC[C@H]2O)cc1|CC(C(=O)O)c1...
4,CC(C)(N)Cc1ccccc1,CC(C)(Cc1ccccc1)N=O|CC(C)(Cc1ccccc1)NO|CC(C)(N...
...,...,...
79,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,NC(CCC(=O)NC(CSc1c(O)ccc2c(C(=O)c3ccc(OCCN4CCC...
80,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...
81,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...
82,O=P1(NCCCl)OCCCN1CCCl,NP1(=O)OCCCN1CCCl|N[P@@]1(=O)OCCCN1CCCl|N[P@]1...
83,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,Clc1ccc(C(c2ccccc2)N2CCNCC2)cc1|O=C(O)COCCN1CC...

In [80]:
def explode(df, name):
    # 将 NaN 替换为 '<unk>'
    # df[name] = df[name].fillna('<unk>')
    # 确保列是字符串类型，按 '|' 分割字符串
    df[name] = df[name].astype(str).str.split(' ')
    # 展开为新的行
    df = df.explode(name)
    # df = df.reset_index(drop=True)
    return df
df=explode(data,'metabolite')

/tmp/ipykernel_28762/215985304.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].astype(str).str.split(' ')

In [81]:
df

,substrate,metabolite
0,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O
0,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,CC(C)CC1(CC(O)CO)C(=O)NC(=O)NC1=O
0,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,
1,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,CC(C(=O)O)c1ccc(CC2CCC[C@H]2O)cc1
1,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,C[C@H](C(=O)O)c1ccc(C[C@H]2CCC[C@@H]2O)cc1
...,...,...
64,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CO)n(C)c2cc(Br)c(O)c(CN(C)C)c12
64,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CS(=O)c2ccccc2)n(C)c2cc(Br)c(O)c(C...
64,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(OC3O[C@H]...
64,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CS(=O)(=O)c2ccccc2)n(C)c2cc(Br)c(O...
64,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,

In [22]:
# data['metabolite'] = data['metabolite'].replace(" ", "|", regex=True)

/tmp/ipykernel_28762/3054229044.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['metabolite'] = data['metabolite'].replace(" ", "|", regex=True)

In [16]:
# data.to_csv("origin_84.csv",index=False)

,substrate,metabolite
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2c(c1CC=C(C)C)OC(O)C(CC(=O)O)=C2|CC(C)=...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,O=C(O)c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|N...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,CC1CCN(c2nc3cc(Cl)ccc3o2)CCN1C(=O)c1cc(CO)ccc1...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)c(O)c...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1C[N+]([O-])=CCCN1S(=O)(=O)c1cccc2cncc(F...
...,...,...
79,CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)...,Cc1cc(C)c(CNC(=O)c2cc(-c3ccc(CN4CCOCC4)cc3)cc(...
80,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(OS(=O)(=O...
81,CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc...,N=C(N)Nc1ccc(C(=O)Oc2ccc(CC(=O)O)cc2)cc1|
82,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,NCCc1cc(O)c(O)cc1[18F]|
83,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...

In [82]:
from rdkit import Chem
from neutral import NeutraliseCharges
from multiprocessing import Pool
from rdkit import RDLogger
import pandas as pd
from rdkit.Chem.MolStandardize import rdMolStandardize
RDLogger.DisableLog('rdApp.*')

def canonicalize_smiles(smiles):
    if len(smiles)==0:
        return 'invalid'
    mol = Chem.MolFromSmiles(smiles)
    # lfc = MolStandardize.fragment.LargestFragmentChooser()
    
    if mol is not None:
        # mol2 = lfc.choose(mol)
        smi2=Chem.MolToSmiles(mol, isomericSmiles=True)
        smi,_=NeutraliseCharges(smi2)
        return smi 
    else:
        return 'invalid'
df['substrate']=df['substrate'].apply(canonicalize_smiles)

In [83]:

df['metabolite']=df['metabolite'].apply(canonicalize_smiles)

In [84]:
data=df.loc[(df['substrate']!='invalid') & (df['metabolite']!='invalid')]

In [28]:
def explode(df, name):
    # 将 NaN 替换为 '<unk>'
    # df[name] = df[name].fillna('<unk>')
    # 确保列是字符串类型，按 '|' 分割字符串
    df[name] = df[name].astype(str).str.split('|')
    # 展开为新的行
    df = df.explode(name)
    # df = df.reset_index(drop=True)
    return df
df=explode(data,'metabolite')

/tmp/ipykernel_28762/3262777790.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].astype(str).str.split('|')

In [47]:
df['metabolite']=df['metabolite'].apply(canonicalize_smiles)

In [48]:
df

,substrate,metabolite
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2c(c1CC=C(C)C)OC(O)C(CC(=O)O)=C2
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,CC(C)=CCc1c(O)ccc2ccc(=O)oc12
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2ccc(=O)oc2c1C/C=C(\C)CO
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,C=C(C)/C=C/c1c(OC)ccc2ccc(=O)oc12
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2cc(O)c(=O)oc2c1CC=C(C)C
...,...,...
81,CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc...,
82,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,NCCc1cc(O)c(O)cc1[18F]
82,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,
83,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...
83,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,

In [85]:
df=data.copy()
val_df = df.groupby('substrate')['metabolite'].apply(lambda x: '|'.join(x)).reset_index()
# val_df['metabolite'] = val_df['metabolite'].apply(lambda x: '|'.join(sorted(x.split('|'))))

In [86]:
val_df

,substrate,metabolite
0,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O|CC(C)CC1(CC(O)...
1,CC(=O)Nc1ccc(O)cc1,CC(=O)Nc1ccc(O[C@@H]2O[C@H](C(=O)O)[C@@H](O)[C...
2,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,CC(C(=O)O)c1ccc(CC2CCC[C@H]2O)cc1|C[C@H](C(=O)...
3,CC(C)(N)Cc1ccccc1,CC(C)(N)Cc1ccc(O)cc1|CC(C)(Cc1ccccc1)NO
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...
...,...,...
60,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(OC3C(O)[C...
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1

In [87]:
val_df.to_csv("origin_65.csv",index=False)

In [39]:
val_df

,substrate,metabolite
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...
1,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O|CC(C)CC1(CC(O)...
2,CC(=O)Nc1ccc(O)cc1,CC(=O)Nc1ccc(O[C@@H]2O[C@H](C(=O)O)[C@@H](O)[C...
3,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,CC(C(=O)O)c1ccc(CC2CCC[C@H]2O)cc1|C[C@H](C(=O)...
4,CC(C)(N)Cc1ccccc1,CC(C)(N)Cc1ccc(O)cc1|CC(C)(Cc1ccccc1)NO|
...,...,...
79,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(OC3C(O)[C...
80,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...
81,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...
82,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...
83,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|

In [10]:
import rdkit
from rdkit import Chem
from rdkit.Chem import Draw, AllChem
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, display
IPythonConsole.ipython_useSVG = True
print('rdkit version:', rdkit.__version__)

rdkit version: 2022.03.2

In [11]:
def kekulize_smiles(smi):
    smi = smi.replace(' ','')
    mol = Chem.MolFromSmiles(smi)
    Chem.Kekulize(mol, clearAromaticFlags = True)
    smi = Chem.MolToSmiles(mol, canonical = False, kekuleSmiles = True)
    return smi

In [12]:
import pandas as pd
import os

def process_and_space_out_letters(file_path, src_output_path):
    def space_out_letters(text):
        # 对字符串中的每个字符进行处理，用空格分隔
        # sections = text.split('|')
        # sections[0]
        return ' '.join(list(kekulize_smiles(text)))+" | <unk>"
    
    # 读取CSV文件
    df = pd.read_csv(file_path)
    
    # 确保输出文件夹存在
    os.makedirs(os.path.dirname(src_output_path), exist_ok=True)
    
    # 处理substrate列，用空格分隔每个字母，然后写入src_output_path
    df['substrate'].apply(space_out_letters).to_csv(src_output_path, index=False, header=False)
    
    # # 处理metabolite列，用空格分隔每个字母，然后写入tgt_output_path
    # df['metabolite'].apply(space_out_letters).to_csv(tgt_output_path, index=False, header=False)

# 定义文件路径和输出路径，假设CSV文件位于当前工作目录中
datasets = [
    ("neutral_origin_test.csv", "./origin_test_84_unk.txt"),
    # ("multi_form_train.csv", "enzyme_unknown/src-train.txt"),
    # ("multi_form_val.csv", "enzyme_unknown/src-valid.txt")
]

# 循环处理每个数据集
for file_path, src_output_path  in datasets:
    full_file_path = os.path.join("./", file_path)  # 调整为实际CSV文件所在的目录
    process_and_space_out_letters(full_file_path, src_output_path)

In [7]:
import pandas as pd
import os

def process_and_space_out_letters(file_path, src_output_path):
    def space_out_letters(text):
        # 对字符串中的每个字符进行处理，用空格分隔
        # sections = text.split('|')
        # sections[0]
        return ' '.join(list(text))
    
    # 读取CSV文件
    df = pd.read_csv(file_path)
    
    # 确保输出文件夹存在
    os.makedirs(os.path.dirname(src_output_path), exist_ok=True)
    
    # 处理substrate列，用空格分隔每个字母，然后写入src_output_path
    df['substrate'].apply(space_out_letters).to_csv(src_output_path, index=False, header=False)
    
    # # 处理metabolite列，用空格分隔每个字母，然后写入tgt_output_path
    # df['metabolite'].apply(space_out_letters).to_csv(tgt_output_path, index=False, header=False)

# 定义文件路径和输出路径，假设CSV文件位于当前工作目录中
datasets = [
    ("neutral_origin_test.csv", "./origin_test_84.txt"),
    # ("multi_form_train.csv", "enzyme_unknown/src-train.txt"),
    # ("multi_form_val.csv", "enzyme_unknown/src-valid.txt")
]

# 循环处理每个数据集
for file_path, src_output_path  in datasets:
    full_file_path = os.path.join("./", file_path)  # 调整为实际CSV文件所在的目录
    process_and_space_out_letters(full_file_path, src_output_path)

In [89]:
import pandas as pd
import os

def process_and_space_out_letters(file_path, src_output_path):
    def space_out_letters(text):
        # 对字符串中的每个字符进行处理，用空格分隔
        # sections = text.split('|')
        # sections[0]
        return ' '.join(list(text))
    
    # 读取CSV文件
    df = pd.read_csv(file_path)
    
    # 确保输出文件夹存在
    os.makedirs(os.path.dirname(src_output_path), exist_ok=True)
    
    # 处理substrate列，用空格分隔每个字母，然后写入src_output_path
    df['substrate'].apply(space_out_letters).to_csv(src_output_path, index=False, header=False)
    
    # # 处理metabolite列，用空格分隔每个字母，然后写入tgt_output_path
    # df['metabolite'].apply(space_out_letters).to_csv(tgt_output_path, index=False, header=False)

# 定义文件路径和输出路径，假设CSV文件位于当前工作目录中
datasets = [
    ("origin_65.csv", "./origin_paper_substrate_65_blank.txt"),
    # ("multi_form_train.csv", "enzyme_unknown/src-train.txt"),
    # ("multi_form_val.csv", "enzyme_unknown/src-valid.txt")
]

# 循环处理每个数据集
for file_path, src_output_path  in datasets:
    full_file_path = os.path.join("./", file_path)  # 调整为实际CSV文件所在的目录
    process_and_space_out_letters(full_file_path, src_output_path)