In [1]:
import pandas as pd
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
data=pd.read_csv("origin_65_true.csv")

In [2]:
def kekulize_smiles(smi):
    smi = smi.replace(' ','')
    mol = Chem.MolFromSmiles(smi)
    Chem.Kekulize(mol, clearAromaticFlags = True)
    smi = Chem.MolToSmiles(mol, canonical = False, kekuleSmiles = True)
    return smi

In [3]:
data['substrate']=data['substrate'].apply(kekulize_smiles)

In [4]:
data

,substrate,metabolite
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...
1,CC(C)(O)C1=CC=CC=C1CC[C@@H](SCC1(CC(=O)O)CC1)C...,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)OC2O[C@H](...
2,CC(C)CNCC1=CC=C(C2=CC=CC=C2S(=O)(=O)N2CCCC2)C=C1,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2O)cc1|N...
3,CC(CN1C2=CC=CC=C2SC2=CC=CC=C12)N(C)C,CC(CN1c2ccccc2S(=O)c2ccccc21)N(C)C|CNC(C)CN1c2...
4,CC1(C)CCC(CN2CCN(C3=CC=C(C(=O)NS(=O)(=O)C4=CC=...,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...
...,...,...
60,O=C(O)C1=CC(O)=C2C(=C1)C(C1C3=CC(C(=O)O)=CC(O)...,O=C(O)c1cc(O)c2c(c1)C(C1c3cccc(O)c3C(=O)c3c(O)...
61,O=C1CN=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...
62,O=C1NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...
63,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...
64,OCCOCCN1CCN(C(C2=CC=CC=C2)C2=CC=C(Cl)C=C2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1

In [5]:
data=data['substrate'].to_list()

In [6]:
def space_out_letters(text):
    # 对字符串中的每个字符进行处理，用空格分隔
    # sections = text.split('|')
    # sections[0]
    return ' '.join(list(text))+" | <unk>"

data1=list(map(space_out_letters,data))

In [7]:
len(data1)

65

In [8]:
result=pd.DataFrame(data1)

In [9]:
result

                                                    0
0   C # C [ C @ ] 1 ( O C ( C ) = O ) C C [ C @ H ...
1   C C ( C ) ( O ) C 1 = C C = C C = C 1 C C [ C ...
2   C C ( C ) C N C C 1 = C C = C ( C 2 = C C = C ...
3   C C ( C N 1 C 2 = C C = C C = C 2 S C 2 = C C ...
4   C C 1 ( C ) C C C ( C N 2 C C N ( C 3 = C C = ...
..                                                ...
60  O = C ( O ) C 1 = C C ( O ) = C 2 C ( = C 1 ) ...
61  O = C 1 C N = C ( C 2 = C C = C C = C 2 ) C 2 ...
62  O = C 1 N C 2 = C C = C ( C l ) C = C 2 C ( C ...
63  O = P 1 ( N C C C l ) O C C C N 1 C C C l | <unk>
64  O C C O C C N 1 C C N ( C ( C 2 = C C = C C = ...

[65 rows x 1 columns]

In [10]:
result.to_csv("test_65_input_origin.txt",index=False,header=None)