In [1]:
import pandas as pd

df = pd.read_csv("origin_paper_84.csv")

In [2]:
df

,substrate,metabolite
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@...
1,C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O,C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O|CC(C)CC1(CC(O)...
2,CC(=O)Nc1ccc(O)cc1,CC(=O)Nc1ccc(O[C@@H]2O[C@H](C(=O)O)[C@@H](O)[C...
3,CC(C(=O)O)c1ccc(CC2CCCC2=O)cc1,CC(C(=O)O)c1ccc(CC2CCC[C@H]2O)cc1|C[C@H](C(=O)...
4,CC(C)(N)Cc1ccccc1,CC(C)(N)Cc1ccc(O)cc1|CC(C)(Cc1ccccc1)NO
...,...,...
79,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(OC3C(O)[C...
80,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,O=C(O)[C@H]1OC(OC2CN=C(c3ccccc3)c3cc(Cl)ccc3N2...
81,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C(O)[C@H]1O[C@@H](OC2N=C(c3ccccc3)c3cc(Cl)cc...
82,O=P1(NCCCl)OCCCN1CCCl,O=CCCl|NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1C...
83,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1

In [3]:
glory=pd.read_csv("metatrans.csv")

In [4]:
glory=glory[['substrate','all_predictions']]

In [5]:
glory

,substrate,all_predictions
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1cc2c(cc1C/C=C(\C)CO)OC(=O)CC2|COc1ccc(C(=O...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,CNC(=O)c1c[nH]c(-c2ccccc2F)c1|O=S(=O)(c1cccnc1...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,Cc1ccc(-n2nccn2)c(C(=O)N2CCNCC2C)c1|Cc1ccc(-n2...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(OC4O[C@H]...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1CN(S(=O)(=O)c2cccc3cncc(F)c23)CCCN1S(=O...
...,...,...
79,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)[O-]|[NH3+]CCc1...
80,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,CC1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](...
81,CC(C)OC(=O)CCC/C=C\C[C@H]1[C@@H](O)C[C@@H](O)[...,O=C(O)CCC/C=C\CC1C(O)CC(O)C1/C=C/C(O)COc1cccc(...
82,CC1(C)O[C@@H]2CO[C@@]3(COS(N)(=O)=O)OC(C)(C)O[...,CC1(C)O[C@@H]2[C@@H](CO[C@@]3(COS(N)(=O)=O)OC(...
83,C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)...,CC1C(O)OC2OC3(C)CCC4[C@H](C)CCC1[C@@]24OO3|C[C...

In [6]:
from rdkit import Chem
from neutral import NeutraliseCharges
from multiprocessing import Pool
from rdkit import RDLogger
import pandas as pd
from rdkit.Chem.MolStandardize import rdMolStandardize
RDLogger.DisableLog('rdApp.*')

def canonicalize_smiles(smiles):
    if len(smiles)==0:
        return 'invalid'
    mol = Chem.MolFromSmiles(smiles)
    # lfc = MolStandardize.fragment.LargestFragmentChooser()
    
    if mol is not None:
        # mol2 = lfc.choose(mol)
        smi2=Chem.MolToSmiles(mol, isomericSmiles=True)
        smi,_=NeutraliseCharges(smi2)
        return smi 
    else:
        return 'invalid'
glory['substrate']=glory['substrate'].apply(canonicalize_smiles)

In [7]:
glory

,substrate,all_predictions
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1cc2c(cc1C/C=C(\C)CO)OC(=O)CC2|COc1ccc(C(=O...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,CNC(=O)c1c[nH]c(-c2ccccc2F)c1|O=S(=O)(c1cccnc1...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,Cc1ccc(-n2nccn2)c(C(=O)N2CCNCC2C)c1|Cc1ccc(-n2...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(OC4O[C@H]...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1CN(S(=O)(=O)c2cccc3cncc(F)c23)CCCN1S(=O...
...,...,...
79,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)[O-]|[NH3+]CCc1...
80,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,CC1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](...
81,CC(C)OC(=O)CCC/C=C\C[C@H]1[C@@H](O)C[C@@H](O)[...,O=C(O)CCC/C=C\CC1C(O)CC(O)C1/C=C/C(O)COc1cccc(...
82,CC1(C)O[C@@H]2CO[C@@]3(COS(N)(=O)=O)OC(C)(C)O[...,CC1(C)O[C@@H]2[C@@H](CO[C@@]3(COS(N)(=O)=O)OC(...
83,C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)...,CC1C(O)OC2OC3(C)CCC4[C@H](C)CCC1[C@@]24OO3|C[C...

In [8]:
import pandas as pd
from rdkit import Chem, DataStructs

def get_similarity(pred, true_metabolites):
    """
    get the similarity between the prediction and the true metabolites
    : param pred: a list of prediction smiles
    : param true_metabolites: a list of true metabolites smiles
    : return: the maxinum similarity between the prediction and the true metabolites
    """
    max_similarity = -5
    for metabolite in true_metabolites:
        metabolite_mol = Chem.MolFromSmiles(metabolite)
        metabolite_fgp = Chem.RDKFingerprint(metabolite_mol)
        prediction_mol = Chem.MolFromSmiles(pred)
        prediction_fgp = Chem.RDKFingerprint(prediction_mol)

        sim = DataStructs.FingerprintSimilarity(metabolite_fgp, prediction_fgp)
        if sim > max_similarity:
            max_similarity = sim
            
    return max_similarity

In [9]:
def extract_fields(line):
    elements = line.split('|')
    top_1 = elements[0] if len(elements) > 0 else ""
    top_5 = '|'.join(elements[:5]) if len(elements) >= 5 else '|'.join(elements)
    top_10 = '|'.join(elements[:10]) if len(elements) >= 10 else '|'.join(elements)
    top_13 = '|'.join(elements[:13]) if len(elements) >= 13 else '|'.join(elements)
    top_20 = '|'.join(elements[:20]) if len(elements) >= 20 else '|'.join(elements)
    return top_1, top_5, top_10, top_13, top_20

In [ ]:
extracted_data = [extract_fields(line) for line in grouped_lines]

In [230]:
corr = 0 
at_least_one, at_least_half, all_metabolites = 0, 0, 0
len_preds, len_corr_preds, len_actual_metabolites, invaild = 0, 0, 0, 0

df=merged.copy()
def extract_top(predictions, n):
    """
    分割字符串并提取前n个元素。
    参数:
    predictions: 字符串，使用'|'分隔的多个预测结果。
    n: 需要提取的元素数量。

    返回:
    返回一个由前n个元素组成的字符串，元素之间用'|'分隔。如果输入的元素少于n个，则返回所有元素。
    """
    split_predictions = predictions.split('|')[:n]
    return '|'.join(split_predictions)
df['top_5'] = df['all_predictions'].apply(lambda x: extract_top(x, 20))
for i in range(len(df)):
    substrate = df.iloc[i]['substrate']
    true_metabolites = df.iloc[i]['metabolite'].strip().split('|')
    # original_preds = df.iloc[i]['all_predictions'].strip().split('|')
    original_preds = df.iloc[i]['top_5'].strip().split('|')
    original_preds = list(set(original_preds))
    len_preds += len(original_preds)

    corr_preds = []
    for pred in original_preds:
        try:
            pred = Chem.MolToSmiles(Chem.MolFromSmiles(pred))
        except:
            invaild += 1
            continue

    
        # if pred in true_metabolites:
        #     corr_preds.append(pred)

        if get_similarity(pred, true_metabolites) == 1:
            corr_preds.append(pred)

    if len(corr_preds) > 0:
        at_least_one += 1
    if len(corr_preds) >= len(true_metabolites)/2:
        at_least_half += 1
    if len(corr_preds) == len(true_metabolites):
        all_metabolites += 1
        print(substrate)
        print(corr_preds)

    len_corr_preds += len(corr_preds)
    len_actual_metabolites += len(true_metabolites)

C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl
['Nc1ncc(-c2cnn(C3CCNCC3)c2)cc1O']
CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2
['CCNCC(=O)N1c2ccccc2CCc2ccc(NC(=O)OCC)cc21']
COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C
['COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)CO']
C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O
['CC12C=CC(=O)C(Cl)=C1CCC1C2C(O)CC2(C)C1CCC2(C)O']
CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21
['CN1c2ccccc2C(=O)N2CC(O)c3c([nH]c4ccccc34)C21', 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccc(O)cc34)C21']
C=CCC1(CC(C)C)C(=O)NC(=O)NC1=O
['CC(C)CC1(CC(O)CO)C(=O)NC(=O)NC1=O', 'C=CCC1(CC(C)CO)C(=O)NC(=O)NC1=O']
COc1cc2nc(N3CCN(C(=O)C4CCCO4)CC3)nc(N)c2cc1OC
['COc1cc2nc(N3CCNCC3)nc(N)c2cc1OC', 'COc1cc2nc(N3CCN(C(=O)C4CCCO4)CC3)nc(N)c2cc1O', 'COc1cc2c(N)nc(N3CCN(C(=O)C4CCCO4)CC3)nc2cc1O']
Cn1cc(S(C)=O)c(=O)c2ccc(F)cc21
['Cn1cc(S(C)(=O)=O)c(=O)c2ccc(F)cc21']
CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3
['CN1CCc2cccc3c2[C@H]1Cc1ccc(OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c(O)c1-3', 'CN1CCc2cccc3c2C1Cc1ccc(OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c(O)c1-3', 'CN1CCc2cccc3c2C1Cc1ccc(OC2OC(C(=O)O)C(O)C(O)C2O)c(O)c1-3', 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c1-3', 'COc1ccc2c(c1O)-c1cccc3c1C(C2)N(C)CC3', 'COc1ccc2c(c1O)-c1cccc3c1[C@@H](C2)N(C)CC3']
CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1
['CCCCNc1ccc(C(=O)O)cc1']
CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1
['CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCNCC)c(I)c1']
CCC1(c2ccccc2)C(=O)NC(=O)NC1=O
['CCC1(c2ccc(O)cc2)C(=O)NC(=O)NC1=O']
NC(=O)c1nc(F)cnc1O
['NC(=O)c1nc(F)c(O)nc1O']
CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1
['Cc1cc(C)c(CNC(=O)c2cc(-c3ccc(CN4CCOCC4)cc3)cc(NC3CCOCC3)c2C)c(=O)[nH]1']

In [153]:
original_preds

['C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(O)CO',
 'C[C@@H]1CC2C3C[C@@H](O)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO',
 'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(=O)CC2(C)C1=O',
 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)[C@H](O)CO',
 'CC1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO']

In [56]:
original_preds

['CC1(C)O[C@@H]2[C@H](O1)C(C)(C)O[C@@H]2COS(N)(=O)=O',
 'CC1(C)OC2OC(C)(C)O[C@H](CO)C2O1',
 'CC1(C)O[C@H]2[C@@H](COS(N)(=O)=O)OC(C)(C)[C@@H]2O1',
 'CC1(C)O[C@H](CO)[C@H]2OC(C)(C)O[C@H]2O1',
 'CC1(C)OC2CO[C@@]3(CO)OC(C)(C)O[C@H]3[C@@H]2O1',
 'CC1(C)O[C@@H]2CO[C@@]3(CO)OC(C)(C)O[C@H]3[C@@H]2O1',
 'CC1(C)O[C@H]2CO[C@@]3(CO)OC(C)(C)O[C@H]3[C@@H]2O1',
 'CC1(C)O[C@H]2CO[C@@]3(COS(N)(=O)=O)OC(C)(C)O[C@H]([C@H]2O1)[C@@H]3O',
 'CC1(C)O[C@@H]2[C@@H](CO[C@@]3(COS(N)(=O)=O)OC(C)(C)O[C@H]3[C@@H]2O)O1',
 'CC1(C)O[C@@H]2[C@@H]3OC(C)(C)O[C@]3(CO)OC[C@H]2O1']

In [231]:
print('at least one: {:.2%}'.format(at_least_one/len(df)))
print('at least half: {:.2%}'.format(at_least_half/len(df)))
print('all metabolites: {:.2%}'.format(all_metabolites/len(df)))
print('precision: {:.2%}'.format(len_corr_preds/len_preds))
print('recall: {:.2%}'.format(len_corr_preds/len_actual_metabolites))
print('invalid: {:.2%}'.format(invaild/len_preds))

at least one: 86.15%
at least half: 75.38%
all metabolites: 21.54%
precision: 17.52%
recall: 79.10%
invalid: 0.00%

In [152]:
df

,substrate,all_predictions,metabolites,top_5
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1cc2c(cc1C/C=C(\C)CO)OC(=O)CC2|COc1ccc(C(=O...,COc1ccc2c(c1CC=C(C)C)OC(O)C(CC(=O)O)=C2|CC(C)=...,COc1cc2c(cc1C/C=C(\C)CO)OC(=O)CC2|COc1ccc(C(=O...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,CNC(=O)c1c[nH]c(-c2ccccc2F)c1|O=S(=O)(c1cccnc1...,O=C(O)c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|N...,CNC(=O)c1c[nH]c(-c2ccccc2F)c1|O=S(=O)(c1cccnc1...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,Cc1ccc(-n2nccn2)c(C(=O)N2CCNCC2C)c1|Cc1ccc(-n2...,CC1CCN(c2nc3cc(Cl)ccc3o2)CCN1C(=O)c1cc(CO)ccc1...,Cc1ccc(-n2nccn2)c(C(=O)N2CCNCC2C)c1|Cc1ccc(-n2...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(OC4O[C@H]...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)c(O)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(OC4O[C@H]...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1CN(S(=O)(=O)c2cccc3cncc(F)c23)CCCN1S(=O...,C[C@H]1C[N+]([O-])=CCCN1S(=O)(=O)c1cccc2cncc(F...,C[C@H]1CN(S(=O)(=O)c2cccc3cncc(F)c23)CCCN1S(=O...
...,...,...,...,...
59,CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)...,CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCC2=C(C...,Cc1cc(C)c(CNC(=O)c2cc(-c3ccc(CN4CCOCC4)cc3)cc(...,CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCC2=C(C...
60,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,CCOC(=O)c1c(CS(=O)c2ccccc2)n(C)c2cc(Br)c(O)c(C...,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(OS(=O)(=O...,CCOC(=O)c1c(CS(=O)c2ccccc2)n(C)c2cc(Br)c(O)c(C...
61,CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc...,CN(CO)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)c...,N=C(N)Nc1ccc(C(=O)Oc2ccc(CC(=O)O)cc2)cc1,CN(CO)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)c...
62,N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)[O-]|[NH3+]CCc1...,NCCc1cc(O)c(O)cc1[18F],N[C@@H](Cc1c[nH]c2ccccc12)C(=O)[O-]|[NH3+]CCc1...
63,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,CC1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](...,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@...,CC1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](...

In [59]:
print('at least one: {:.2%}'.format(at_least_one/len(df)))
print('at least half: {:.2%}'.format(at_least_half/len(df)))
print('all metabolites: {:.2%}'.format(all_metabolites/len(df)))
print('precision: {:.2%}'.format(len_corr_preds/len_preds))
print('recall: {:.2%}'.format(len_corr_preds/len_actual_metabolites))
print('invalid: {:.2%}'.format(invaild/len_preds))

at least one: 89.23%
at least half: 56.92%
all metabolites: 20.00%
precision: 20.53%
recall: 54.67%
invalid: 0.00%

In [7]:
df = df[['SMILES', 'Metabolites']]
df.columns = ['substrate', 'metabolite']
df.head()

,substrate,metabolite
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2c(c1CC=C(C)C)OC(O)C(CC(=O)O)=C2 CC(C)=...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,O=C(O)c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1 N...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,CC1CCN(c2nc3cc(Cl)ccc3o2)CCN1C(=O)c1cc(CO)ccc1...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)c(O)c...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1C[N+]([O-])=CCCN1S(=O)(=O)c1cccc2cncc(F...

In [8]:
from rdkit import Chem

# canonicalize SMILES
df['substrate'] = df['substrate'].apply(lambda x: Chem.MolToSmiles(Chem.MolFromSmiles(x)))
metabolites = df['metabolite'].tolist()
new_metabolites = []
for metabolite in metabolites:
    mols = metabolite.strip().split(' ')
    new_mols = []
    for mol in mols:
        new_mols.append(Chem.MolToSmiles(Chem.MolFromSmiles(mol), isomericSmiles=True))
    new_metabolites.append('|'.join(new_mols))

df['metabolite'] = new_metabolites
df.head()

,substrate,metabolite
0,COc1ccc2ccc(=O)oc2c1CC=C(C)C,COc1ccc2c(c1CC=C(C)C)OC(O)C(CC(=O)O)=C2|CC(C)=...
1,CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1,O=C(O)c1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|N...
2,Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3...,CC1CCN(c2nc3cc(Cl)ccc3o2)CCN1C(=O)c1cc(CO)ccc1...
3,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)c...,Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)c(O)c...
4,C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12,C[C@H]1C[N+]([O-])=CCCN1S(=O)(=O)c1cccc2cncc(F...

In [9]:
df.to_csv('datasets/test_reactions_reference.csv', index=False, encoding='utf-8')