In [126]:
import pandas as pd

In [127]:
df = pd.read_pickle('gnnsom_results_30.pickle')
df

,substrate,ec,score
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,"(1, 14)","{0: 0.06620190292596817, 1: 0.1898989975452423..."
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,"(1, 14)","{0: 0.004156974609941244, 1: 0.026069363579154..."
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,"(1, 14)","{0: 0.29619577527046204, 1: 0.2986163496971130..."
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,"(1, 14)","{0: 0.052477654069662094, 1: 0.565950572490692..."
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,"(1, 14)","{0: 0.0910082533955574, 1: 0.02117333933711052..."
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,"(1, 14)","{0: 0.4648127555847168, 1: 0.41543275117874146..."
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,"(1, 14)","{0: 0.027508947998285294, 1: 0.010729714296758..."
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,"(1, 14)","{0: 0.05575377866625786, 1: 0.0035735636483877..."
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,"(1, 14)","{0: 0.1326913833618164, 1: 0.43272143602371216..."
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,"(1, 14)","{0: 0.12559056282043457, 1: 0.2717109620571136..."
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,"(1, 14)","{0: 0.019783781841397285, 1: 0.238463521003723..."
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,"(1, 14)","{0: 0.6923989057540894, 1: 0.5843725204467773,..."
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,"(1, 14)","{0: 0.0021558667067438364, 1: 0.00115818507038..."
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,"(1, 14)","{0: 0.0648232102394104, 1: 0.1600409746170044,..."
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,"(1, 14)","{0: 0.29971858859062195, 1: 0.2584117650985718..."
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,"(1, 14)","{0: 0.014025367796421051, 1: 0.014437950216233..."
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,"(1, 14)","{0: 0.10323450714349747, 1: 0.2670384645462036..."
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,"(1, 14)","{0: 0.08858180791139603, 1: 0.0308590363711118..."
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,"(1, 14)","{0: 0.5535970330238342, 1: 0.586530864238739, ..."
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,"(1, 14)","{0: 0.08562661707401276, 1: 0.1668726652860641..."
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,"(1, 14)","{0: 0.25789812207221985, 1: 0.2590750753879547..."
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,"(1, 14)","{0: 0.45536327362060547, 1: 0.6482680439949036..."
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,"(1, 14)","{0: 0.2948805093765259, 1: 0.2430124580860138,..."
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,"(1, 14)","{0: 0.04335489496588707, 1: 0.0325113795697689..."
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,"(1, 14)","{0: 0.13892222940921783, 1: 0.4218060672283172..."
25,CNC(C)Cc1ccc2c(c1)OCO2,"(1, 14)","{0: 0.6047694087028503, 1: 0.8651612401008606,..."
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,"(1, 14)","{0: 0.24049727618694305, 1: 0.1554280370473861..."
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,"(1, 14)","{0: 0.0004770357336383313, 1: 0.00010865528747..."
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,"(1, 14)","{0: 0.13844427466392517, 1: 0.4628036022186279..."
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,"(1, 14)","{0: 0.13005469739437103, 1: 0.3995654284954071..."

In [128]:
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

In [129]:
scores = df['score'].to_list()
scores = list(map(assign_ranks,scores))
scores

[{0: 20,
  1: 3,
  2: 7,
  3: 11,
  4: 19,
  5: 8,
  6: 1,
  7: 15,
  8: 36,
  9: 25,
  10: 28,
  11: 26,
  12: 14,
  13: 12,
  14: 33,
  15: 24,
  16: 18,
  17: 31,
  18: 34,
  19: 22,
  20: 35,
  21: 27,
  22: 30,
  23: 2,
  24: 9,
  25: 32,
  26: 17,
  27: 13,
  28: 23,
  29: 16,
  30: 21,
  31: 29,
  32: 4,
  33: 10,
  34: 6,
  35: 5},
 {0: 41,
  1: 37,
  2: 12,
  3: 1,
  4: 27,
  5: 3,
  6: 17,
  7: 6,
  8: 28,
  9: 36,
  10: 4,
  11: 15,
  12: 20,
  13: 35,
  14: 26,
  15: 32,
  16: 13,
  17: 18,
  18: 21,
  19: 29,
  20: 25,
  21: 39,
  22: 40,
  23: 24,
  24: 11,
  25: 19,
  26: 22,
  27: 34,
  28: 30,
  29: 2,
  30: 23,
  31: 31,
  32: 9,
  33: 16,
  34: 10,
  35: 14,
  36: 33,
  37: 7,
  38: 38,
  39: 8,
  40: 5},
 {0: 5,
  1: 4,
  2: 9,
  3: 11,
  4: 14,
  5: 23,
  6: 3,
  7: 1,
  8: 2,
  9: 15,
  10: 19,
  11: 10,
  12: 20,
  13: 7,
  14: 6,
  15: 8,
  16: 16,
  17: 21,
  18: 17,
  19: 12,
  20: 18,
  21: 13,
  22: 22},
 {0: 18,
  1: 4,
  2: 16,
  3: 3,
  4: 21,
  5: 17,
  6: 22,
  7: 26,
  8: 19,
  9: 25,
  10: 1,
  11: 8,
  12: 2,
  13: 5,
  14: 9,
  15: 15,
  16: 6,
  17: 12,
  18: 13,
  19: 24,
  20: 11,
  21: 14,
  22: 7,
  23: 10,
  24: 23,
  25: 20},
 {0: 17,
  1: 21,
  2: 18,
  3: 9,
  4: 8,
  5: 2,
  6: 13,
  7: 19,
  8: 3,
  9: 10,
  10: 1,
  11: 4,
  12: 14,
  13: 23,
  14: 12,
  15: 15,
  16: 16,
  17: 20,
  18: 6,
  19: 11,
  20: 5,
  21: 7,
  22: 22},
 {0: 1,
  1: 3,
  2: 25,
  3: 22,
  4: 2,
  5: 28,
  6: 12,
  7: 17,
  8: 21,
  9: 20,
  10: 18,
  11: 8,
  12: 13,
  13: 15,
  14: 16,
  15: 11,
  16: 6,
  17: 27,
  18: 4,
  19: 5,
  20: 7,
  21: 24,
  22: 10,
  23: 19,
  24: 9,
  25: 26,
  26: 23,
  27: 14},
 {0: 30,
  1: 38,
  2: 19,
  3: 43,
  4: 13,
  5: 33,
  6: 41,
  7: 35,
  8: 15,
  9: 39,
  10: 17,
  11: 20,
  12: 14,
  13: 1,
  14: 23,
  15: 4,
  16: 11,
  17: 31,
  18: 37,
  19: 40,
  20: 34,
  21: 27,
  22: 9,
  23: 8,
  24: 42,
  25: 29,
  26: 22,
  27: 25,
  28: 21,
  29: 36,
  30: 28,
  31: 24,
  32: 12,
  33: 10,
  34: 32,
  35: 26,
  36: 7,
  37: 6,
  38: 18,
  39: 16,
  40: 2,
  41: 3,
  42: 5},
 {0: 24,
  1: 31,
  2: 27,
  3: 21,
  4: 20,
  5: 22,
  6: 29,
  7: 30,
  8: 17,
  9: 8,
  10: 25,
  11: 14,
  12: 10,
  13: 7,
  14: 6,
  15: 2,
  16: 11,
  17: 28,
  18: 18,
  19: 9,
  20: 13,
  21: 3,
  22: 16,
  23: 23,
  24: 5,
  25: 12,
  26: 19,
  27: 26,
  28: 15,
  29: 4,
  30: 1},
 {0: 10,
  1: 1,
  2: 7,
  3: 30,
  4: 18,
  5: 11,
  6: 14,
  7: 13,
  8: 19,
  9: 20,
  10: 22,
  11: 26,
  12: 9,
  13: 17,
  14: 31,
  15: 25,
  16: 27,
  17: 16,
  18: 24,
  19: 4,
  20: 21,
  21: 23,
  22: 5,
  23: 15,
  24: 12,
  25: 28,
  26: 6,
  27: 8,
  28: 2,
  29: 3,
  30: 29},
 {0: 12,
  1: 6,
  2: 2,
  3: 10,
  4: 4,
  5: 13,
  6: 16,
  7: 5,
  8: 1,
  9: 30,
  10: 11,
  11: 21,
  12: 28,
  13: 15,
  14: 19,
  15: 7,
  16: 24,
  17: 14,
  18: 9,
  19: 29,
  20: 20,
  21: 25,
  22: 22,
  23: 23,
  24: 3,
  25: 8,
  26: 18,
  27: 27,
  28: 17,
  29: 26},
 {0: 25,
  1: 6,
  2: 9,
  3: 15,
  4: 18,
  5: 27,
  6: 30,
  7: 8,
  8: 3,
  9: 5,
  10: 2,
  11: 10,
  12: 4,
  13: 1,
  14: 7,
  15: 24,
  16: 22,
  17: 21,
  18: 12,
  19: 17,
  20: 13,
  21: 23,
  22: 26,
  23: 11,
  24: 29,
  25: 14,
  26: 20,
  27: 16,
  28: 28,
  29: 19},
 {0: 3,
  1: 5,
  2: 6,
  3: 8,
  4: 9,
  5: 26,
  6: 13,
  7: 10,
  8: 21,
  9: 18,
  10: 23,
  11: 29,
  12: 28,
  13: 4,
  14: 16,
  15: 1,
  16: 2,
  17: 14,
  18: 19,
  19: 22,
  20: 24,
  21: 15,
  22: 27,
  23: 20,
  24: 11,
  25: 17,
  26: 12,
  27: 25,
  28: 7},
 {0: 25,
  1: 30,
  2: 23,
  3: 20,
  4: 12,
  5: 16,
  6: 8,
  7: 5,
  8: 3,
  9: 18,
  10: 28,
  11: 29,
  12: 34,
  13: 14,
  14: 2,
  15: 1,
  16: 24,
  17: 32,
  18: 39,
  19: 37,
  20: 17,
  21: 9,
  22: 22,
  23: 38,
  24: 33,
  25: 11,
  26: 4,
  27: 26,
  28: 21,
  29: 10,
  30: 6,
  31: 13,
  32: 7,
  33: 35,
  34: 31,
  35: 27,
  36: 15,
  37: 36,
  38: 19},
 {0: 19,
  1: 15,
  2: 18,
  3: 21,
  4: 8,
  5: 1,
  6: 3,
  7: 2,
  8: 7,
  9: 10,
  10: 20,
  11: 25,
  12: 24,
  13: 9,
  14: 4,
  15: 6,
  16: 22,
  17: 14,
  18: 16,
  19: 23,
  20: 17,
  21: 12,
  22: 13,
  23: 11,
  24: 5},
 {0: 1,
  1: 4,
  2: 6,
  3: 5,
  4: 7,
  5: 13,
  6: 22,
  7: 18,
  8: 21,
  9: 12,
  10: 11,
  11: 9,
  12: 24,
  13: 23,
  14: 14,
  15: 8,
  16: 20,
  17: 16,
  18: 19,
  19: 15,
  20: 17,
  21: 10,
  22: 3,
  23: 2},
 {0: 27,
  1: 26,
  2: 25,
  3: 32,
  4: 28,
  5: 14,
  6: 3,
  7: 19,
  8: 24,
  9: 30,
  10: 29,
  11: 7,
  12: 21,
  13: 13,
  14: 1,
  15: 15,
  16: 11,
  17: 2,
  18: 9,
  19: 4,
  20: 23,
  21: 33,
  22: 31,
  23: 8,
  24: 10,
  25: 6,
  26: 5,
  27: 22,
  28: 20,
  29: 18,
  30: 16,
  31: 17,
  32: 12},
 {0: 18,
  1: 12,
  2: 28,
  3: 29,
  4: 23,
  5: 3,
  6: 6,
  7: 9,
  8: 53,
  9: 5,
  10: 2,
  11: 30,
  12: 31,
  13: 26,
  14: 33,
  15: 19,
  16: 24,
  17: 50,
  18: 52,
  19: 43,
  20: 48,
  21: 45,
  22: 36,
  23: 22,
  24: 42,
  25: 35,
  26: 11,
  27: 10,
  28: 13,
  29: 46,
  30: 51,
  31: 44,
  32: 54,
  33: 37,
  34: 15,
  35: 16,
  36: 4,
  37: 7,
  38: 40,
  39: 38,
  40: 14,
  41: 8,
  42: 1,
  43: 41,
  44: 20,
  45: 21,
  46: 27,
  47: 32,
  48: 25,
  49: 39,
  50: 47,
  51: 49,
  52: 34,
  53: 17},
 {0: 15,
  1: 22,
  2: 14,
  3: 21,
  4: 1,
  5: 3,
  6: 13,
  7: 4,
  8: 5,
  9: 23,
  10: 10,
  11: 2,
  12: 27,
  13: 6,
  14: 28,
  15: 20,
  16: 16,
  17: 12,
  18: 8,
  19: 9,
  20: 24,
  21: 17,
  22: 18,
  23: 19,
  24: 26,
  25: 25,
  26: 7,
  27: 11},
 {0: 2,
  1: 1,
  2: 4,
  3: 12,
  4: 35,
  5: 63,
  6: 52,
  7: 55,
  8: 31,
  9: 11,
  10: 5,
  11: 39,
  12: 56,
  13: 61,
  14: 57,
  15: 64,
  16: 48,
  17: 45,
  18: 28,
  19: 36,
  20: 62,
  21: 3,
  22: 34,
  23: 10,
  24: 38,
  25: 51,
  26: 37,
  27: 60,
  28: 15,
  29: 21,
  30: 22,
  31: 14,
  32: 19,
  33: 24,
  34: 54,
  35: 44,
  36: 53,
  37: 46,
  38: 65,
  39: 13,
  40: 23,
  41: 16,
  42: 7,
  43: 33,
  44: 26,
  45: 27,
  46: 58,
  47: 50,
  48: 41,
  49: 40,
  50: 42,
  51: 9,
  52: 30,
  53: 43,
  54: 47,
  55: 25,
  56: 59,
  57: 49,
  58: 20,
  59: 8,
  60: 6,
  61: 32,
  62: 18,
  63: 29,
  64: 17},
 {0: 13,
  1: 8,
  2: 2,
  3: 9,
  4: 17,
  5: 1,
  6: 3,
  7: 7,
  8: 28,
  9: 23,
  10: 29,
  11: 15,
  12: 11,
  13: 20,
  14: 18,
  15: 26,
  16: 27,
  17: 14,
  18: 12,
  19: 10,
  20: 16,
  21: 21,
  22: 19,
  23: 25,
  24: 24,
  25: 22,
  26: 4,
  27: 5,
  28: 6},
 {0: 5,
  1: 4,
  2: 16,
  3: 17,
  4: 9,
  5: 14,
  6: 2,
  7: 30,
  8: 1,
  9: 26,
  10: 12,
  11: 18,
  12: 21,
  13: 32,
  14: 6,
  15: 10,
  16: 3,
  17: 23,
  18: 25,
  19: 27,
  20: 33,
  21: 28,
  22: 29,
  23: 31,
  24: 19,
  25: 7,
  26: 11,
  27: 8,
  28: 15,
  29: 13,
  30: 22,
  31: 24,
  32: 20},
 {0: 6,
  1: 2,
  2: 7,
  3: 3,
  4: 5,
  5: 10,
  6: 13,
  7: 16,
  8: 20,
  9: 14,
  10: 18,
  11: 12,
  12: 11,
  13: 9,
  14: 8,
  15: 1,
  16: 4,
  17: 15,
  18: 19,
  19: 17},
 {0: 6,
  1: 7,
  2: 13,
  3: 22,
  4: 14,
  5: 1,
  6: 4,
  7: 5,
  8: 28,
  9: 33,
  10: 35,
  11: 34,
  12: 30,
  13: 11,
  14: 16,
  15: 20,
  16: 17,
  17: 8,
  18: 9,
  19: 24,
  20: 3,
  21: 29,
  22: 2,
  23: 18,
  24: 32,
  25: 15,
  26: 23,
  27: 21,
  28: 12,
  29: 19,
  30: 26,
  31: 25,
  32: 10,
  33: 27,
  34: 36,
  35: 31},
 {0: 14,
  1: 18,
  2: 22,
  3: 26,
  4: 30,
  5: 5,
  6: 6,
  7: 4,
  8: 27,
  9: 35,
  10: 28,
  11: 3,
  12: 7,
  13: 20,
  14: 12,
  15: 29,
  16: 38,
  17: 40,
  18: 13,
  19: 9,
  20: 16,
  21: 33,
  22: 11,
  23: 41,
  24: 25,
  25: 39,
  26: 34,
  27: 42,
  28: 32,
  29: 31,
  30: 24,
  31: 2,
  32: 1,
  33: 10,
  34: 15,
  35: 8,
  36: 21,
  37: 17,
  38: 23,
  39: 36,
  40: 37,
  41: 19},
 {0: 17,
  1: 6,
  2: 5,
  3: 14,
  4: 12,
  5: 8,
  6: 9,
  7: 28,
  8: 16,
  9: 1,
  10: 2,
  11: 26,
  12: 22,
  13: 19,
  14: 20,
  15: 10,
  16: 3,
  17: 4,
  18: 11,
  19: 21,
  20: 15,
  21: 7,
  22: 13,
  23: 24,
  24: 32,
  25: 33,
  26: 29,
  27: 30,
  28: 18,
  29: 25,
  30: 23,
  31: 31,
  32: 27},
 {0: 2,
  1: 1,
  2: 3,
  3: 5,
  4: 4,
  5: 8,
  6: 7,
  7: 6,
  8: 14,
  9: 10,
  10: 9,
  11: 12,
  12: 11,
  13: 13},
 {0: 6,
  1: 10,
  2: 26,
  3: 15,
  4: 28,
  5: 5,
  6: 2,
  7: 1,
  8: 3,
  9: 8,
  10: 23,
  11: 29,
  12: 19,
  13: 7,
  14: 14,
  15: 4,
  16: 17,
  17: 11,
  18: 13,
  19: 27,
  20: 24,
  21: 12,
  22: 9,
  23: 20,
  24: 16,
  25: 21,
  26: 22,
  27: 18,
  28: 25},
 {0: 80,
  1: 83,
  2: 84,
  3: 71,
  4: 75,
  5: 70,
  6: 66,
  7: 18,
  8: 14,
  9: 69,
  10: 19,
  11: 46,
  12: 35,
  13: 36,
  14: 23,
  15: 21,
  16: 63,
  17: 56,
  18: 64,
  19: 33,
  20: 17,
  21: 43,
  22: 55,
  23: 27,
  24: 29,
  25: 5,
  26: 7,
  27: 40,
  28: 25,
  29: 38,
  30: 82,
  31: 79,
  32: 34,
  33: 15,
  34: 68,
  35: 41,
  36: 74,
  37: 32,
  38: 44,
  39: 28,
  40: 52,
  41: 6,
  42: 8,
  43: 2,
  44: 1,
  45: 57,
  46: 60,
  47: 51,
  48: 65,
  49: 49,
  50: 53,
  51: 39,
  52: 24,
  53: 4,
  54: 3,
  55: 85,
  56: 73,
  57: 54,
  58: 26,
  59: 48,
  60: 47,
  61: 59,
  62: 61,
  63: 72,
  64: 42,
  65: 81,
  66: 77,
  67: 78,
  68: 76,
  69: 67,
  70: 37,
  71: 20,
  72: 62,
  73: 50,
  74: 31,
  75: 30,
  76: 22,
  77: 12,
  78: 11,
  79: 16,
  80: 10,
  81: 13,
  82: 9,
  83: 58,
  84: 45},
 {0: 22,
  1: 4,
  2: 19,
  3: 16,
  4: 11,
  5: 5,
  6: 12,
  7: 26,
  8: 25,
  9: 24,
  10: 18,
  11: 15,
  12: 7,
  13: 23,
  14: 3,
  15: 17,
  16: 9,
  17: 2,
  18: 1,
  19: 27,
  20: 28,
  21: 6,
  22: 21,
  23: 8,
  24: 13,
  25: 14,
  26: 10,
  27: 20},
 {0: 10,
  1: 2,
  2: 13,
  3: 22,
  4: 15,
  5: 19,
  6: 20,
  7: 14,
  8: 3,
  9: 5,
  10: 4,
  11: 7,
  12: 11,
  13: 6,
  14: 21,
  15: 12,
  16: 9,
  17: 17,
  18: 16,
  19: 18,
  20: 1,
  21: 8}]

In [130]:
df['score'] = scores

In [131]:
df

,substrate,ec,score
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,"(1, 14)","{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ..."
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,"(1, 14)","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17..."
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,"(1, 14)","{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ..."
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,"(1, 14)","{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22..."
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,"(1, 14)","{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,..."
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,"(1, 14)","{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,..."
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,"(1, 14)","{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ..."
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,"(1, 14)","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ..."
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,"(1, 14)","{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14..."
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,"(1, 14)","{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,..."
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,"(1, 14)","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30..."
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,"(1, 14)","{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7..."
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,"(1, 14)","{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ..."
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,"(1, 14)","{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,..."
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,"(1, 14)","{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7..."
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,"(1, 14)","{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ..."
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,"(1, 14)","{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6..."
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,"(1, 14)","{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13..."
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,"(1, 14)","{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,..."
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,"(1, 14)","{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7..."
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,"(1, 14)","{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ..."
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,"(1, 14)","{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7..."
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,"(1, 14)","{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ..."
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,"(1, 14)","{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6..."
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,"(1, 14)","{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ..."
25,CNC(C)Cc1ccc2c(c1)OCO2,"(1, 14)","{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ..."
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,"(1, 14)","{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,..."
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,"(1, 14)","{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ..."
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,"(1, 14)","{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12..."
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,"(1, 14)","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2..."

In [132]:
df.to_pickle('gnnsom_results_30_rank.pickle')

In [133]:
df = pd.read_pickle('gnnsom_results_30_rank.pickle')
from rdkit import Chem
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new
smiles = df['substrate'].to_list()
smiles = list(map(canonicalsmiles,smiles))
df['substrate'] = smiles
df

,substrate,ec,score
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,"(1, 14)","{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ..."
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,"(1, 14)","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17..."
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,"(1, 14)","{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ..."
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,"(1, 14)","{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22..."
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,"(1, 14)","{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,..."
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,"(1, 14)","{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,..."
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,"(1, 14)","{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ..."
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,"(1, 14)","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ..."
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,"(1, 14)","{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14..."
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,"(1, 14)","{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,..."
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,"(1, 14)","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30..."
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,"(1, 14)","{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7..."
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,"(1, 14)","{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ..."
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,"(1, 14)","{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,..."
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,"(1, 14)","{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7..."
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,"(1, 14)","{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ..."
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,"(1, 14)","{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6..."
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,"(1, 14)","{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13..."
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,"(1, 14)","{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,..."
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,"(1, 14)","{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7..."
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,"(1, 14)","{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ..."
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,"(1, 14)","{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7..."
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,"(1, 14)","{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ..."
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,"(1, 14)","{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6..."
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,"(1, 14)","{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ..."
25,CNC(C)Cc1ccc2c(c1)OCO2,"(1, 14)","{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ..."
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,"(1, 14)","{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,..."
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,"(1, 14)","{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ..."
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,"(1, 14)","{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12..."
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,"(1, 14)","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2..."

In [134]:
df.to_pickle('gnnsom_results_30_rank.pickle')

In [135]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrate', 'score')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: 8, 7: 5, 8: 3, 9: 18, 10: 28, 11: 29, 12: 34, 13: 14, 14: 2, 15: 1, 16: 24, 17: 32, 18: 39, 19: 37, 20: 17, 21: 9, 22: 22, 23: 38, 24: 33, 25: 11, 26: 4, 27: 26, 28: 21, 29: 10, 30: 6, 31: 13, 32: 7, 33: 35, 34: 31, 35: 27, 36: 15, 37: 36, 38: 19}, 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: 41, 7: 35, 8: 15, 9: 39, 10: 17, 11: 20, 12: 14, 13: 1, 14: 23, 15: 4, 16: 11, 17: 31, 18: 37, 19: 40, 20: 34, 21: 27, 22: 9, 23: 8, 24: 42, 25: 29, 26: 22, 27: 25, 28: 21, 29: 36, 30: 28, 31: 24, 32: 12, 33: 10, 34: 32, 35: 26, 36: 7, 37: 6, 38: 18, 39: 16, 40: 2, 41: 3, 42: 5}, 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': {0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22, 7: 26, 8: 19, 9: 25, 10: 1, 11: 8, 12: 2, 13: 5, 14: 9, 15: 15, 16: 6, 17: 12, 18: 13, 19: 24, 20: 11, 21: 14, 22: 7, 23: 10, 24: 23, 25: 20}, 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': {0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, 7: 15, 8: 36, 9: 25, 10: 28, 11: 26, 12: 14, 13: 12, 14: 33, 15: 24, 16: 18, 17: 31, 18: 34, 19: 22, 20: 35, 21: 27, 22: 30, 23: 2, 24: 9, 25: 32, 26: 17, 27: 13, 28: 23, 29: 16, 30: 21, 31: 29, 32: 4, 33: 10, 34: 6, 35: 5}, 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': {0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: 66, 7: 18, 8: 14, 9: 69, 10: 19, 11: 46, 12: 35, 13: 36, 14: 23, 15: 21, 16: 63, 17: 56, 18: 64, 19: 33, 20: 17, 21: 43, 22: 55, 23: 27, 24: 29, 25: 5, 26: 7, 27: 40, 28: 25, 29: 38, 30: 82, 31: 79, 32: 34, 33: 15, 34: 68, 35: 41, 36: 74, 37: 32, 38: 44, 39: 28, 40: 52, 41: 6, 42: 8, 43: 2, 44: 1, 45: 57, 46: 60, 47: 51, 48: 65, 49: 49, 50: 53, 51: 39, 52: 24, 53: 4, 54: 3, 55: 85, 56: 73, 57: 54, 58: 26, 59: 48, 60: 47, 61: 59, 62: 61, 63: 72, 64: 42, 65: 81, 66: 77, 67: 78, 68: 76, 69: 67, 70: 37, 71: 20, 72: 62, 73: 50, 74: 31, 75: 30, 76: 22, 77: 12, 78: 11, 79: 16, 80: 10, 81: 13, 82: 9, 83: 58, 84: 45}, 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': {0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6, 7: 4, 8: 27, 9: 35, 10: 28, 11: 3, 12: 7, 13: 20, 14: 12, 15: 29, 16: 38, 17: 40, 18: 13, 19: 9, 20: 16, 21: 33, 22: 11, 23: 41, 24: 25, 25: 39, 26: 34, 27: 42, 28: 32, 29: 31, 30: 24, 31: 2, 32: 1, 33: 10, 34: 15, 35: 8, 36: 21, 37: 17, 38: 23, 39: 36, 40: 37, 41: 19}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, 7: 1, 8: 2, 9: 15, 10: 19, 11: 10, 12: 20, 13: 7, 14: 6, 15: 8, 16: 16, 17: 21, 18: 17, 19: 12, 20: 18, 21: 13, 22: 22}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7: 7, 8: 28, 9: 23, 10: 29, 11: 15, 12: 11, 13: 20, 14: 18, 15: 26, 16: 27, 17: 14, 18: 12, 19: 10, 20: 16, 21: 21, 22: 19, 23: 25, 24: 24, 25: 22, 26: 4, 27: 5, 28: 6}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7: 16, 8: 20, 9: 14, 10: 18, 11: 12, 12: 11, 13: 9, 14: 8, 15: 1, 16: 4, 17: 15, 18: 19, 19: 17}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30, 7: 8, 8: 3, 9: 5, 10: 2, 11: 10, 12: 4, 13: 1, 14: 7, 15: 24, 16: 22, 17: 21, 18: 12, 19: 17, 20: 13, 21: 23, 22: 26, 23: 11, 24: 29, 25: 14, 26: 20, 27: 16, 28: 28, 29: 19}, 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17, 7: 6, 8: 28, 9: 36, 10: 4, 11: 15, 12: 20, 13: 35, 14: 26, 15: 32, 16: 13, 17: 18, 18: 21, 19: 29, 20: 25, 21: 39, 22: 40, 23: 24, 24: 11, 25: 19, 26: 22, 27: 34, 28: 30, 29: 2, 30: 23, 31: 31, 32: 9, 33: 16, 34: 10, 35: 14, 36: 33, 37: 7, 38: 38, 39: 8, 40: 5}, 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13, 7: 4, 8: 5, 9: 23, 10: 10, 11: 2, 12: 27, 13: 6, 14: 28, 15: 20, 16: 16, 17: 12, 18: 8, 19: 9, 20: 24, 21: 17, 22: 18, 23: 19, 24: 26, 25: 25, 26: 7, 27: 11}, 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': {0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52, 7: 55, 8: 31, 9: 11, 10: 5, 11: 39, 12: 56, 13: 61, 14: 57, 15: 64, 16: 48, 17: 45, 18: 28, 19: 36, 20: 62, 21: 3, 22: 34, 23: 10, 24: 38, 25: 51, 26: 37, 27: 60, 28: 15, 29: 21, 30: 22, 31: 14, 32: 19, 33: 24, 34: 54, 35: 44, 36: 53, 37: 46, 38: 65, 39: 13, 40: 23, 41: 16, 42: 7, 43: 33, 44: 26, 45: 27, 46: 58, 47: 50, 48: 41, 49: 40, 50: 42, 51: 9, 52: 30, 53: 43, 54: 47, 55: 25, 56: 59, 57: 49, 58: 20, 59: 8, 60: 6, 61: 32, 62: 18, 63: 29, 64: 17}, 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6, 7: 9, 8: 53, 9: 5, 10: 2, 11: 30, 12: 31, 13: 26, 14: 33, 15: 19, 16: 24, 17: 50, 18: 52, 19: 43, 20: 48, 21: 45, 22: 36, 23: 22, 24: 42, 25: 35, 26: 11, 27: 10, 28: 13, 29: 46, 30: 51, 31: 44, 32: 54, 33: 37, 34: 15, 35: 16, 36: 4, 37: 7, 38: 40, 39: 38, 40: 14, 41: 8, 42: 1, 43: 41, 44: 20, 45: 21, 46: 27, 47: 32, 48: 25, 49: 39, 50: 47, 51: 49, 52: 34, 53: 17}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: 6, 8: 14, 9: 10, 10: 9, 11: 12, 12: 11, 13: 13}, 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': {0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, 7: 30, 8: 1, 9: 26, 10: 12, 11: 18, 12: 21, 13: 32, 14: 6, 15: 10, 16: 3, 17: 23, 18: 25, 19: 27, 20: 33, 21: 28, 22: 29, 23: 31, 24: 19, 25: 7, 26: 11, 27: 8, 28: 15, 29: 13, 30: 22, 31: 24, 32: 20}, 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': {0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7: 18, 8: 21, 9: 12, 10: 11, 11: 9, 12: 24, 13: 23, 14: 14, 15: 8, 16: 20, 17: 16, 18: 19, 19: 15, 20: 17, 21: 10, 22: 3, 23: 2}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7: 10, 8: 21, 9: 18, 10: 23, 11: 29, 12: 28, 13: 4, 14: 16, 15: 1, 16: 2, 17: 14, 18: 19, 19: 22, 20: 24, 21: 15, 22: 27, 23: 20, 24: 11, 25: 17, 26: 12, 27: 25, 28: 7}, 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': {0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13, 7: 19, 8: 3, 9: 10, 10: 1, 11: 4, 12: 14, 13: 23, 14: 12, 15: 15, 16: 16, 17: 20, 18: 6, 19: 11, 20: 5, 21: 7, 22: 22}, 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: 29, 7: 30, 8: 17, 9: 8, 10: 25, 11: 14, 12: 10, 13: 7, 14: 6, 15: 2, 16: 11, 17: 28, 18: 18, 19: 9, 20: 13, 21: 3, 22: 16, 23: 23, 24: 5, 25: 12, 26: 19, 27: 26, 28: 15, 29: 4, 30: 1}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3, 7: 2, 8: 7, 9: 10, 10: 20, 11: 25, 12: 24, 13: 9, 14: 4, 15: 6, 16: 22, 17: 14, 18: 16, 19: 23, 20: 17, 21: 12, 22: 13, 23: 11, 24: 5}, 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': {0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12, 7: 17, 8: 21, 9: 20, 10: 18, 11: 8, 12: 13, 13: 15, 14: 16, 15: 11, 16: 6, 17: 27, 18: 4, 19: 5, 20: 7, 21: 24, 22: 10, 23: 19, 24: 9, 25: 26, 26: 23, 27: 14}, 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2, 7: 1, 8: 3, 9: 8, 10: 23, 11: 29, 12: 19, 13: 7, 14: 14, 15: 4, 16: 17, 17: 11, 18: 13, 19: 27, 20: 24, 21: 12, 22: 9, 23: 20, 24: 16, 25: 21, 26: 22, 27: 18, 28: 25}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, 7: 5, 8: 28, 9: 33, 10: 35, 11: 34, 12: 30, 13: 11, 14: 16, 15: 20, 16: 17, 17: 8, 18: 9, 19: 24, 20: 3, 21: 29, 22: 2, 23: 18, 24: 32, 25: 15, 26: 23, 27: 21, 28: 12, 29: 19, 30: 26, 31: 25, 32: 10, 33: 27, 34: 36, 35: 31}, 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16, 7: 5, 8: 1, 9: 30, 10: 11, 11: 21, 12: 28, 13: 15, 14: 19, 15: 7, 16: 24, 17: 14, 18: 9, 19: 29, 20: 20, 21: 25, 22: 22, 23: 23, 24: 3, 25: 8, 26: 18, 27: 27, 28: 17, 29: 26}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 20, 7: 14, 8: 3, 9: 5, 10: 4, 11: 7, 12: 11, 13: 6, 14: 21, 15: 12, 16: 9, 17: 17, 18: 16, 19: 18, 20: 1, 21: 8}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14, 7: 13, 8: 19, 9: 20, 10: 22, 11: 26, 12: 9, 13: 17, 14: 31, 15: 25, 16: 27, 17: 16, 18: 24, 19: 4, 20: 21, 21: 23, 22: 5, 23: 15, 24: 12, 25: 28, 26: 6, 27: 8, 28: 2, 29: 3, 30: 29}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: 3, 7: 19, 8: 24, 9: 30, 10: 29, 11: 7, 12: 21, 13: 13, 14: 1, 15: 15, 16: 11, 17: 2, 18: 9, 19: 4, 20: 23, 21: 33, 22: 31, 23: 8, 24: 10, 25: 6, 26: 5, 27: 22, 28: 20, 29: 18, 30: 16, 31: 17, 32: 12}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12, 7: 26, 8: 25, 9: 24, 10: 18, 11: 15, 12: 7, 13: 23, 14: 3, 15: 17, 16: 9, 17: 2, 18: 1, 19: 27, 20: 28, 21: 6, 22: 21, 23: 8, 24: 13, 25: 14, 26: 10, 27: 20}, 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, 7: 28, 8: 16, 9: 1, 10: 2, 11: 26, 12: 22, 13: 19, 14: 20, 15: 10, 16: 3, 17: 4, 18: 11, 19: 21, 20: 15, 21: 7, 22: 13, 23: 24, 24: 32, 25: 33, 26: 29, 27: 30, 28: 18, 29: 25, 30: 23, 31: 31, 32: 27}}

In [136]:
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

In [137]:
import pickle
with open('dict_sub2site.pickle', 'rb') as file:
    dict_sub2site = pickle.load(file)

In [138]:
df_total = pd.read_csv('pred_results_score_new.csv')
subs = df_total['substrate'].to_list()
subs = list(map(canonicalsmiles,subs))
metas = df_total['predict'].to_list()
atomidxs = [dict_sub2site[i] for i in subs]
# sites = df_total['site_truth'].to_list()
# sites = [i.split('|') for i in sites]
# atomidxs = list(map(get_reactive_atom_indices,sites))
df_total['substrate'] = subs
df_total['sites'] = atomidxs
df_total

,name,substrate,predict,top_n,sites
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30]
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]"
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20]
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3]
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3]
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4]
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40]
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]"
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23]
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8]
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]"
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16]
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21]
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7]
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1]
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6]
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6]
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27]
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[]
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18]
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11]
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15]
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4]
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6]
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21]
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12]
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6]
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28]
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25]
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]"

In [139]:
# df_new = pd.DataFrame()
# df_new['substrates'] = list(dict_sub2site.keys())
# df_new['true_sites'] = [dict_sub2site[i] for i in list(dict_sub2site.keys())]
df_total['gnn_results'] = [result_new.get(i,'None') for i in subs]
df_total

,name,substrate,predict,top_n,sites,gnn_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2..."

In [140]:
df_total.to_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')

2. smartcyp

In [141]:
df = pd.read_pickle('smartcyp_results_30.pickle')
df

,substrates,enzyme,scores
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,3A4,"{0: 21, 1: 22, 2: 14, 3: 6, 4: 24, 5: 13, 6: 1..."
1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2D6,"{0: 20, 1: 22, 2: 14, 3: 9, 4: 24, 5: 11, 6: 1..."
2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2C9,"{0: 20, 1: 22, 2: 14, 3: 8, 4: 24, 5: 13, 6: 1..."
3,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,3A4,"{1: 25, 2: 8, 3: 28, 4: 31, 5: 13, 6: 35, 7: 3..."
4,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,2D6,"{1: 25, 2: 10, 3: 31, 4: 32, 5: 15, 6: 27, 7: ..."
...,...,...,...
85,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2D6,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
86,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2C9,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
87,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,3A4,"{0: 11, 1: 12, 2: 6, 3: 5, 4: 4, 5: 13, 6: 4, ..."
88,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."
89,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2C9,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."

In [142]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: 87, 7: 28, 8: 93, 9: 50, 10: 58, 11: 54, 12: 59, 13: 63, 14: 22, 15: 73, 16: 102, 17: 14, 18: 99, 19: 46, 20: 34, 21: 90, 22: 11, 23: 79, 24: 21, 25: 7, 26: 66, 27: 11, 28: 66, 29: 21, 30: 69, 31: 28, 32: 73, 33: 37, 34: 90, 35: 41, 36: 93, 37: 45, 38: 96}, 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: 66, 7: 111, 8: 43, 9: 101, 10: 52, 11: 69, 12: 98, 13: 87, 14: 81, 15: 81, 16: 28, 17: 45, 18: 45, 19: 106, 20: 103, 21: 46, 22: 63, 23: 16, 24: 78, 25: 22, 26: 21, 27: 31, 28: 34, 29: 84, 30: 55, 31: 110, 32: 114, 33: 29, 34: 37, 35: 114, 36: 46, 37: 15, 38: 26, 39: 22, 40: 75, 41: 10, 42: 10}, 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': {0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 36, 7: 63, 8: 7, 9: 69, 10: 69, 11: 74, 12: 45, 13: 14, 14: 41, 15: 70, 16: 30, 17: 21, 18: 16, 19: 54, 20: 16, 21: 8, 22: 13, 23: 27, 24: 57, 25: 37}, 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': {0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: 37, 7: 37, 8: 78, 9: 48, 10: 33, 11: 81, 12: 8, 13: 11, 14: 11, 15: 8, 16: 36, 17: 4, 18: 79, 19: 45, 20: 16, 21: 29, 22: 23, 23: 17, 24: 8, 25: 28, 26: 55, 27: 52, 28: 69, 29: 59, 30: 86, 31: 81, 32: 58}, 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': {0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175, 6: 97, 7: 115, 8: 87, 9: 84, 10: 184, 11: 193, 12: 186, 13: 102, 14: 96, 15: 132, 16: 112, 17: 81, 18: 206, 19: 109, 20: 98, 21: 185, 22: 124, 23: 109, 24: 90, 25: 124, 26: 185, 27: 210, 28: 116, 29: 78, 30: 197, 31: 22, 32: 65, 33: 60, 34: 68, 35: 57, 36: 125, 37: 181, 38: 163, 39: 19, 40: 50, 41: 156, 42: 59, 43: 153, 44: 6, 45: 144, 46: 18, 47: 8, 48: 147, 49: 138, 50: 14, 51: 138, 52: 141, 53: 43, 54: 150, 55: 34, 56: 159, 57: 168, 58: 172, 59: 71, 60: 190, 61: 56, 62: 181, 63: 45, 64: 200, 65: 203, 66: 197, 67: 131, 68: 133, 69: 42, 70: 156, 71: 42, 72: 156, 73: 156, 74: 16, 75: 34, 76: 147, 77: 150, 78: 31, 79: 11, 80: 138, 81: 21, 82: 31, 83: 141, 84: 138}, 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': {0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6: 23, 7: 29, 8: 98, 9: 89, 10: 75, 11: 70, 12: 82, 13: 30, 14: 19, 15: 70, 16: 67, 17: 4, 18: 17, 19: 54, 20: 33, 21: 61, 22: 25, 23: 85, 24: 24, 25: 94, 26: 101, 27: 85, 28: 52, 29: 55, 30: 40, 31: 55, 32: 52, 33: 80, 34: 85, 35: 85, 36: 46, 37: 43, 38: 23, 39: 38, 40: 23, 41: 38}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 37, 7: 56, 8: 60, 9: 57, 10: 53, 11: 40, 12: 60, 13: 48, 14: 45, 15: 45, 16: 30, 17: 11, 18: 5, 19: 15, 20: 30, 21: 24, 22: 11}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 45, 7: 23, 8: 28, 9: 23, 10: 28, 11: 16, 12: 76, 13: 77, 14: 43, 15: 32, 16: 20, 17: 66, 18: 68, 19: 71, 20: 36, 21: 49, 22: 57, 23: 54, 24: 9, 25: 16, 26: 16, 27: 26, 28: 35}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 14, 7: 16, 8: 45, 9: 51, 10: 54, 11: 19, 12: 11, 13: 30, 14: 5, 15: 26, 16: 5, 17: 26, 18: 12, 19: 41}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: 77, 7: 35, 8: 82, 9: 14, 10: 28, 11: 5, 12: 22, 13: 81, 14: 9, 15: 78, 16: 47, 17: 66, 18: 35, 19: 51, 20: 9, 21: 26, 22: 54, 23: 13, 24: 57, 25: 34, 26: 72, 27: 69, 28: 46, 29: 39}, 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: 108, 8: 21, 9: 93, 10: 100, 11: 3, 12: 18, 13: 86, 14: 49, 15: 78, 16: 31, 17: 17, 18: 69, 19: 72, 21: 34, 22: 60, 23: 16, 24: 57, 25: 95, 26: 14, 27: 46, 28: 104, 29: 14, 30: 39, 31: 85, 32: 54, 33: 43, 34: 34, 35: 9, 36: 66, 37: 63}, 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33, 7: 15, 8: 20, 9: 11, 10: 38, 11: 61, 12: 63, 13: 35, 14: 59, 15: 26, 16: 21, 17: 50, 18: 46, 19: 42, 23: 55, 25: 29, 26: 20, 27: 15}, 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': {0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6: 20, 7: 130, 8: 10, 9: 7, 10: 115, 11: 166, 12: 177, 13: 9, 14: 82, 15: 76, 16: 81, 17: 119, 18: 175, 19: 186, 20: 56, 21: 94, 22: 89, 23: 14, 24: 40, 25: 151, 26: 35, 27: 32, 28: 124, 29: 175, 30: 181, 31: 186, 32: 111, 33: 61, 34: 161, 35: 105, 36: 102, 37: 99, 38: 102, 39: 105, 40: 124, 41: 166, 42: 172, 43: 94, 44: 47, 45: 154, 46: 19, 47: 131, 48: 135, 49: 33, 50: 36, 51: 54, 52: 57, 53: 141, 54: 118, 55: 68, 56: 151, 57: 144, 58: 67, 59: 138, 60: 61, 61: 50, 62: 30, 63: 38, 64: 108}, 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6: 139, 7: 115, 8: 58, 9: 76, 10: 47, 11: 128, 12: 133, 13: 123, 14: 79, 15: 67, 16: 51, 17: 67, 18: 79, 19: 130, 20: 115, 21: 124, 22: 41, 23: 9, 24: 87, 25: 3, 26: 6, 27: 25, 28: 32, 29: 124, 30: 61, 31: 126, 32: 68, 33: 79, 34: 120, 35: 13, 36: 18, 37: 14, 38: 27, 39: 120, 40: 105, 41: 70, 42: 56, 43: 92, 44: 36, 45: 91, 46: 102, 47: 99, 48: 96, 49: 44, 50: 43, 51: 130, 52: 79, 53: 68}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18, 7: 18, 8: 33, 9: 39, 10: 25, 11: 36, 12: 6, 13: 30}, 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': {0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 75, 7: 80, 8: 42, 9: 69, 10: 28, 11: 31, 12: 9, 13: 54, 14: 48, 15: 19, 16: 45, 17: 31, 18: 80, 19: 74, 20: 35, 21: 66, 25: 20, 26: 38, 27: 23, 28: 10, 29: 51, 31: 57}, 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': {0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 24, 7: 33, 8: 30, 9: 21, 10: 57, 11: 9, 12: 51, 13: 15, 14: 7, 15: 39, 16: 10, 17: 39, 18: 15, 19: 42, 20: 18, 21: 48, 22: 36, 23: 27}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 60, 7: 66, 8: 63, 9: 27, 10: 33, 11: 64, 12: 59, 13: 54, 14: 52, 15: 28, 16: 45, 17: 15, 18: 6, 19: 41, 20: 6, 21: 15, 22: 33, 23: 27, 24: 21, 25: 32, 26: 11, 27: 52, 28: 14}, 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': {0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11, 7: 57, 8: 63, 9: 60, 10: 42, 11: 21, 12: 39, 13: 66, 14: 35, 15: 29, 16: 22, 17: 48, 18: 22, 19: 16, 20: 19, 21: 32, 22: 54}, 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: 60, 7: 9, 8: 3, 9: 48, 10: 6, 11: 48, 12: 9, 13: 54, 14: 13, 15: 57, 16: 45, 17: 76, 18: 14, 19: 73, 20: 34, 21: 31, 22: 68, 23: 63, 24: 31, 25: 30, 26: 51, 28: 30, 29: 31, 30: 24}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 42, 7: 28, 8: 31, 9: 17, 10: 58, 11: 30, 12: 31, 13: 24, 14: 10, 15: 20, 16: 45, 17: 8, 18: 50, 20: 31, 21: 28, 22: 58, 23: 58, 24: 17}, 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': {0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 35, 7: 51, 8: 43, 9: 69, 10: 18, 11: 9, 12: 10, 13: 32, 14: 32, 15: 10, 16: 9, 17: 47, 18: 63, 19: 57, 20: 17, 21: 10, 22: 54, 25: 40, 26: 23, 27: 33}, 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 66, 7: 45, 8: 70, 9: 12, 10: 15, 11: 73, 12: 19, 13: 30, 14: 67, 15: 34, 16: 27, 17: 51, 18: 27, 19: 34, 21: 42, 22: 77, 23: 54, 24: 48, 25: 27, 26: 3, 27: 33, 28: 7}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 42, 7: 78, 8: 78, 9: 29, 10: 38, 11: 32, 12: 74, 13: 78, 14: 48, 15: 18, 16: 7, 17: 18, 18: 56, 19: 52, 20: 76, 21: 76, 22: 36, 23: 81, 24: 37, 25: 8, 26: 64, 27: 33, 28: 25, 29: 33, 30: 25, 31: 59, 32: 55}, 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: 34, 7: 14, 8: 59, 9: 66, 10: 38, 11: 29, 12: 53, 14: 29, 15: 38, 16: 38, 17: 8, 18: 24, 19: 63, 20: 22, 21: 33, 22: 14, 23: 52, 24: 58, 25: 13, 26: 4, 27: 48, 28: 8, 29: 38}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: 14, 7: 13, 8: 3, 9: 30, 10: 25, 14: 25, 15: 33, 16: 9, 17: 6, 18: 22}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: 60, 7: 54, 8: 48, 12: 28, 13: 41, 14: 76, 15: 69, 16: 9, 17: 3, 18: 69, 19: 38, 20: 38, 21: 16, 22: 51, 23: 19, 24: 16, 25: 7, 26: 25, 27: 57, 28: 32, 29: 20, 30: 23}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73, 7: 73, 8: 23, 9: 58, 10: 56, 11: 54, 12: 63, 13: 27, 14: 57, 15: 58, 16: 22, 17: 18, 18: 33, 19: 30, 20: 18, 21: 22, 22: 75, 23: 63, 24: 69, 25: 67, 26: 63, 27: 15, 28: 42, 29: 11, 30: 39, 31: 4, 32: 30}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: 13, 7: 51, 8: 48, 9: 25, 10: 24, 11: 4, 12: 24, 13: 25, 14: 42, 15: 23, 16: 24, 17: 62, 18: 58, 19: 8, 20: 45, 21: 22, 22: 14, 23: 10, 24: 14, 25: 22, 26: 24, 27: 23}, 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: 36, 7: 31, 8: 77, 9: 83, 10: 18, 11: 78, 12: 43, 13: 44, 14: 75, 15: 17, 16: 18, 17: 7, 18: 18, 19: 60, 20: 18, 21: 7, 22: 44, 23: 43, 24: 64, 25: 73, 26: 20, 27: 17, 28: 54, 29: 51, 30: 34, 31: 60, 32: 57}}

In [143]:
df_total = pd.read_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
smartcyp_results = [result_new[i] for i in substrates]
df_total['smartcyp_results'] = smartcyp_results
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ..."

In [144]:
df_total.to_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')

3. somp

In [145]:
df = pd.read_pickle('somp_results_30.pickle')
df

,substrates,enzyme,scores
0,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3A4,"{0: 57, 1: 46, 2: 31, 3: 16, 4: 29, 5: 34, 6: ..."
1,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,1A2,"{0: 13, 1: 14, 2: 15, 3: 16, 4: 1, 5: 39, 6: 3..."
2,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,2D6,"{0: 6, 1: 20, 2: 32, 3: 10, 4: 23, 5: 24, 6: 1..."
3,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,2C19,"{0: 29, 1: 36, 2: 19, 3: 3, 4: 21, 5: 11, 6: 8..."
4,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,2C19,"{0: 3, 1: 20, 2: 5, 3: 16, 4: 6, 5: 15, 6: 17,..."
...,...,...,...
175,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,UGT,"{0: 9, 1: 11, 2: 5, 3: 14, 4: 15, 5: 13, 6: 6,..."
176,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 15, 1: 5, 2: 11, 3: 2, 4: 7, 5: 6, 6: 8, 7..."
177,CNC(C)Cc1ccc2c(c1)OCO2,2C19,"{0: 2, 1: 4, 2: 5, 3: 6, 4: 20, 5: 3, 6: 14, 7..."
178,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,UGT,"{0: 9, 1: 19, 2: 5, 3: 2, 4: 23, 5: 24, 6: 22,..."
179,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,2D6,"{0: 1, 1: 29, 2: 19, 3: 14, 4: 13, 5: 26, 6: 2..."

In [146]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, 6: 119, 7: 93, 8: 174, 9: 86, 10: 50, 11: 46, 12: 81, 13: 95, 14: 34, 15: 170, 16: 158, 17: 126, 18: 175, 19: 135, 20: 48, 21: 170, 22: 139, 23: 178, 24: 151, 25: 56, 26: 167, 27: 99, 28: 161, 29: 91, 30: 168, 31: 128, 32: 171, 33: 104, 34: 175, 35: 97, 36: 183, 37: 131, 38: 186}, 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211, 6: 118, 7: 202, 8: 174, 9: 221, 10: 136, 11: 173, 12: 226, 13: 130, 14: 143, 15: 186, 16: 56, 17: 79, 18: 85, 19: 207, 20: 217, 21: 164, 22: 126, 23: 32, 24: 220, 25: 128, 26: 100, 27: 79, 28: 128, 29: 240, 30: 166, 31: 185, 32: 208, 33: 40, 34: 118, 35: 160, 36: 109, 37: 38, 38: 67, 39: 74, 40: 68, 41: 23, 42: 29}, 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': {0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6: 85, 7: 117, 8: 14, 9: 138, 10: 119, 11: 99, 12: 136, 13: 69, 14: 35, 15: 88, 16: 148, 17: 74, 18: 20, 19: 48, 20: 115, 21: 58, 22: 27, 23: 42, 24: 78, 25: 131, 26: 100}, 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': {0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120, 6: 44, 7: 50, 8: 56, 9: 194, 10: 165, 11: 47, 12: 98, 13: 12, 14: 168, 15: 174, 16: 18, 17: 113, 18: 173, 19: 52, 20: 226, 21: 207, 22: 105, 23: 58, 24: 121, 25: 134, 26: 64, 27: 133, 28: 83, 29: 130, 30: 214, 31: 151, 32: 192, 33: 127, 34: 197, 35: 138, 36: 187, 37: 127, 38: 133, 39: 139}, 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': {0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 411, 6: 272, 7: 374, 8: 199, 9: 287, 10: 153, 11: 202, 12: 369, 13: 316, 14: 371, 15: 131, 16: 131, 17: 139, 18: 106, 19: 152, 20: 147, 21: 277, 22: 201, 23: 60, 24: 330, 25: 201, 26: 62, 27: 290, 28: 207, 29: 319, 30: 343, 31: 272, 32: 270, 33: 413, 34: 364, 35: 310, 36: 249, 37: 242, 38: 337, 39: 146, 40: 433, 41: 419, 42: 297, 43: 290, 44: 384, 45: 193, 46: 343, 47: 282, 48: 413, 49: 172, 50: 57, 51: 367, 52: 363, 53: 85, 54: 332, 55: 323, 56: 197, 57: 370, 58: 80, 59: 419, 60: 376, 61: 400, 62: 166, 63: 357, 64: 165, 65: 387, 66: 73, 67: 351, 68: 260, 69: 408, 70: 125, 71: 141, 72: 67, 73: 341, 74: 73, 75: 347, 76: 414, 77: 323, 78: 320, 79: 409, 80: 439, 81: 333, 82: 92, 83: 366, 84: 205, 85: 194, 86: 399, 87: 394}, 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': {0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129, 6: 155, 7: 45, 8: 152, 9: 82, 10: 189, 11: 240, 12: 186, 13: 172, 14: 154, 15: 124, 16: 147, 17: 190, 18: 257, 19: 150, 20: 153, 21: 201, 22: 195, 23: 135, 24: 129, 25: 88, 26: 212, 27: 121, 28: 94, 29: 220, 30: 193, 31: 192, 32: 125, 33: 109, 34: 68, 35: 115, 36: 131, 37: 239, 38: 167, 39: 215, 40: 59, 41: 94, 42: 78, 43: 58, 44: 84, 45: 64}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6: 66, 7: 101, 8: 101, 9: 128, 10: 115, 11: 80, 12: 106, 13: 102, 14: 59, 15: 65, 16: 112, 17: 50, 18: 47, 19: 58, 20: 37, 21: 79, 22: 112}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6: 99, 7: 24, 8: 61, 9: 30, 10: 67, 11: 90, 12: 167, 13: 161, 14: 76, 15: 44, 16: 72, 17: 140, 18: 165, 19: 100, 20: 115, 21: 121, 22: 69, 23: 95, 24: 79, 25: 62, 26: 68, 27: 139, 28: 130}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: 37, 7: 58, 8: 107, 9: 116, 10: 105, 11: 79, 12: 30, 13: 45, 14: 14, 15: 49, 16: 20, 17: 55, 18: 88, 19: 93}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6: 171, 7: 124, 8: 88, 9: 165, 10: 127, 11: 45, 12: 27, 13: 121, 14: 51, 15: 59, 16: 179, 17: 42, 18: 165, 19: 161, 20: 198, 21: 162, 22: 178, 23: 43, 24: 85, 25: 91, 26: 97, 27: 146, 28: 206, 29: 47, 30: 103, 31: 109, 32: 115, 33: 222, 34: 196, 35: 209, 36: 176, 37: 94, 38: 130}, 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61, 6: 135, 7: 142, 8: 108, 9: 128, 10: 211, 11: 24, 12: 64, 13: 44, 14: 183, 15: 67, 16: 208, 17: 71, 18: 108, 19: 188, 20: 223, 21: 155, 22: 100, 23: 153, 24: 134, 25: 137, 26: 137, 27: 55, 28: 47, 29: 125, 30: 73, 31: 87, 32: 175, 33: 129, 34: 100, 35: 96, 36: 90, 37: 139, 38: 166, 39: 123, 40: 129, 41: 135}, 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: 89, 7: 73, 8: 50, 9: 78, 10: 92, 11: 144, 12: 52, 13: 127, 14: 123, 15: 153, 16: 77, 17: 86, 18: 114, 19: 138, 20: 71, 21: 111, 22: 117, 23: 123, 24: 151, 25: 101, 26: 95, 27: 84, 28: 56}, 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': {0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195, 6: 60, 7: 281, 8: 241, 9: 244, 10: 219, 11: 335, 12: 355, 13: 292, 14: 301, 15: 104, 16: 242, 17: 146, 18: 113, 19: 261, 20: 263, 21: 207, 22: 139, 23: 110, 24: 171, 25: 169, 26: 67, 27: 287, 28: 247, 29: 251, 30: 226, 31: 272, 32: 192, 33: 223, 34: 186, 35: 68, 36: 74, 37: 264, 38: 207, 39: 108, 40: 85, 41: 114, 42: 213, 43: 293, 44: 292, 45: 221, 46: 80, 47: 116, 48: 275, 49: 364, 50: 351, 51: 341, 52: 402, 53: 200, 54: 99, 55: 84, 56: 216, 57: 413, 58: 200, 59: 31, 60: 152, 61: 238, 62: 147, 63: 353, 64: 237, 65: 280, 66: 206, 67: 119, 68: 193}, 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39, 6: 284, 7: 254, 8: 123, 9: 102, 10: 137, 11: 285, 12: 197, 13: 237, 14: 135, 15: 76, 16: 51, 17: 82, 18: 141, 19: 228, 20: 235, 21: 258, 22: 96, 23: 89, 24: 174, 25: 75, 26: 23, 27: 96, 28: 95, 29: 138, 30: 185, 31: 178, 32: 227, 33: 200, 34: 166, 35: 223, 36: 70, 37: 231, 38: 110, 39: 119, 40: 95, 41: 306, 42: 291, 43: 187, 44: 113, 45: 261, 46: 270, 47: 230, 48: 262, 49: 210, 50: 217, 51: 66, 52: 167, 53: 240, 54: 172, 55: 206}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: 82, 7: 38, 8: 44, 9: 50, 10: 79, 11: 106, 12: 70, 13: 68, 14: 94, 15: 101, 16: 87, 17: 95, 18: 17, 19: 95}, 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': {0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, 6: 72, 7: 80, 8: 96, 9: 132, 10: 187, 11: 51, 12: 169, 13: 111, 14: 203, 15: 176, 16: 129, 17: 138, 18: 81, 19: 130, 20: 130, 21: 50, 22: 146, 23: 89, 24: 95, 25: 101, 26: 104, 27: 44, 28: 32, 29: 62, 30: 63, 31: 151, 32: 118, 33: 170, 34: 84}, 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': {0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136, 6: 44, 7: 49, 8: 67, 9: 23, 10: 131, 11: 97, 12: 119, 13: 108, 14: 33, 15: 111, 16: 73, 17: 51, 18: 113, 19: 64, 20: 57, 21: 116, 22: 87, 23: 63, 24: 121, 25: 107, 26: 68}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, 6: 140, 7: 136, 8: 92, 9: 72, 10: 70, 11: 93, 12: 113, 13: 110, 14: 73, 15: 53, 16: 86, 17: 45, 18: 21, 19: 102, 20: 27, 21: 51, 22: 76, 23: 78, 24: 60, 25: 113, 26: 119, 27: 148, 28: 127}, 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': {0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6: 79, 7: 127, 8: 109, 9: 88, 10: 122, 11: 70, 12: 41, 13: 79, 14: 130, 15: 68, 16: 21, 17: 47, 18: 102, 19: 55, 20: 29, 21: 44, 22: 72, 23: 116}, 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, 6: 52, 7: 156, 8: 133, 9: 58, 10: 27, 11: 158, 12: 87, 13: 64, 14: 161, 15: 80, 16: 70, 17: 163, 18: 86, 19: 76, 20: 167, 21: 114, 22: 162, 23: 101, 24: 179, 25: 92, 26: 117, 27: 180, 28: 169, 29: 95, 30: 61, 31: 160, 32: 177, 33: 67, 34: 101, 35: 19}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6: 72, 7: 27, 8: 105, 9: 126, 10: 105, 11: 77, 12: 65, 13: 92, 14: 65, 15: 73, 16: 74, 17: 53, 18: 145, 19: 117, 20: 111, 21: 33, 22: 94, 23: 100, 24: 13}, 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': {0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177, 6: 119, 7: 148, 8: 99, 9: 173, 10: 119, 11: 121, 12: 66, 13: 26, 14: 51, 15: 57, 16: 72, 17: 32, 18: 127, 19: 120, 20: 110, 21: 119, 22: 84, 23: 38, 24: 58, 25: 100, 26: 62, 27: 68, 28: 159, 29: 112, 30: 110}, 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, 6: 99, 7: 83, 8: 126, 9: 79, 10: 49, 11: 70, 12: 156, 13: 115, 14: 55, 15: 85, 16: 116, 17: 86, 18: 59, 19: 143, 20: 65, 21: 92, 22: 145, 23: 100, 24: 105, 25: 123, 26: 147, 27: 96, 28: 66, 29: 87, 30: 21}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61, 6: 39, 7: 147, 8: 76, 9: 157, 10: 74, 11: 52, 12: 86, 13: 190, 14: 53, 15: 109, 16: 39, 17: 93, 18: 45, 19: 115, 20: 100, 21: 113, 22: 119, 23: 135, 24: 101, 25: 186, 26: 59, 27: 176, 28: 96, 29: 132, 30: 102, 31: 138, 32: 153, 33: 149, 34: 147, 35: 153, 36: 159}, 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6: 42, 7: 79, 8: 24, 9: 136, 10: 142, 11: 82, 12: 57, 13: 142, 14: 139, 15: 63, 16: 88, 17: 55, 18: 73, 19: 98, 20: 174, 21: 100, 22: 96, 23: 70, 24: 154, 25: 145, 26: 102, 27: 95, 28: 112, 29: 79, 30: 61}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: 55, 7: 37, 8: 56, 9: 108, 10: 122, 11: 92, 12: 98, 13: 104, 14: 87, 15: 89, 16: 43, 17: 25, 18: 64, 19: 70, 20: 76, 21: 82}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6: 103, 7: 139, 8: 64, 9: 88, 10: 94, 11: 100, 12: 79, 13: 52, 14: 146, 15: 128, 16: 103, 17: 25, 18: 174, 19: 90, 20: 138, 21: 108, 22: 177, 23: 89, 24: 48, 25: 35, 26: 81, 27: 186, 28: 96, 29: 61, 30: 30}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, 6: 142, 7: 75, 8: 51, 9: 169, 10: 151, 11: 132, 12: 105, 13: 69, 14: 156, 15: 124, 16: 62, 17: 26, 18: 74, 19: 138, 20: 32, 21: 68, 22: 158, 23: 121, 24: 133, 25: 92, 26: 129, 27: 78, 28: 132, 29: 49, 30: 122, 31: 52, 32: 122}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, 6: 84, 7: 154, 8: 154, 9: 89, 10: 128, 11: 44, 12: 134, 13: 95, 14: 87, 15: 39, 16: 58, 17: 108, 18: 119, 19: 48, 20: 108, 21: 76, 22: 42, 23: 24, 24: 48, 25: 82, 26: 64, 27: 45}, 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161, 6: 90, 7: 43, 8: 69, 9: 154, 10: 133, 11: 28, 12: 120, 13: 88, 14: 113, 15: 153, 16: 35, 17: 40, 18: 62, 19: 46, 20: 108, 21: 52, 22: 68, 23: 119, 24: 94, 25: 169, 26: 131, 27: 106, 28: 66, 29: 136, 30: 135, 31: 159, 32: 178, 33: 143}}

In [147]:
df_total = pd.read_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
somp_results = [result_new.get(i,'None') for i in substrates]
df_total['somp_results'] = somp_results
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,somp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ...","{0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120,..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ...","{0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3...","{0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6:..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3...","{0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11...","{0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3...","{0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177,..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ...","{0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ...","{0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ...","{0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ...","{0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ...","{0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6:..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6...","{0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, ..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ...","{0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4...","{0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6:..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2...","{0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136,..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73...","{0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6...","{0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39,..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33...","{0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: ..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:...","{0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4...","{0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6:..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7...","{0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, ..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1...","{0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: ..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4...","{0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61,..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:...","{0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129,..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ...","{0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161,..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18...","{0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: ..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6...","{0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, ..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,...","{0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 41..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ...","{0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, ..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ...","{0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: ..."

In [148]:
df_total.to_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')

4. xenosite

In [149]:
df =  pd.read_pickle('xenosite_results_30.pickle')
df

,substrates,enzyme,atomscores,bondscores
0,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.stable_oxygenation,"[0.04688301682472229, 5.322694778442383e-05, 0...","[5.91278076171875e-05, 0.0018117129802703857, ..."
1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.unstable_oxygenation,"[1.5467405319213867e-05, 2.682209014892578e-07...","[0.006465315818786621, 0.007032662630081177, 0..."
2,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.dehydrogenation,"[0.0017002522945404053, 8.940696716308594e-08,...","[5.960464477539063e-08, 8.58306884765625e-06, ..."
3,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.hydrolysis,"[2.8908252716064453e-06, 2.2351741790771484e-0...","[6.285309791564941e-05, 0.002713918685913086, ..."
4,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.reduction,"[0, 0, 0, 0, 0, 0, 3.5762786865234375e-07, 3.5...","[0, 5.364418029785156e-07, 1.823902130126953e-..."
...,...,...,...,...
123,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.stable_oxygenation,"[0.032869696617126465, 0.04651036858558655, 0....","[4.088878631591797e-05, 5.111098289489746e-05,..."
124,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.unstable_oxygenation,"[1.576542854309082e-05, 1.4960765838623047e-05...","[0.005626857280731201, 0.005427330732345581, 0..."
125,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.dehydrogenation,"[0.001680523157119751, 0.0021561086177825928, ...","[6.258487701416016e-07, 5.066394805908203e-07,..."
126,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.hydrolysis,"[3.844499588012695e-06, 3.1888484954833984e-06...","[1.5050172805786133e-05, 8.52048397064209e-05,..."
127,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.reduction,"[0, 0, 0, 0, 0, 0, 1.2367963790893555e-05, 0, ...","[0, 2.9802322387695312e-08, 2.9802322387695312..."

In [150]:
df =  pd.read_pickle('xenosite_results_30.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 52, 1: 73, 2: 167, 3: 118, 4: 37, 5: 198, 6: 137, 7: 188, 8: 34, 9: 207, 10: 130, 11: 156, 12: 221, 13: 148, 14: 139, 15: 122, 16: 104, 17: 87, 18: 93, 19: 207, 20: 210, 21: 150, 22: 83, 23: 113, 24: 220, 25: 93, 26: 83, 27: 114, 28: 102, 29: 212, 30: 155, 31: 231, 32: 96, 33: 122, 34: 155, 35: 243, 36: 37, 37: 136, 38: 128, 39: 105, 40: 40, 41: 112, 42: 118}, 'CC(=O)Nc1ccc(C)c(C(=O)NC(C)c2cccc3ccccc23)c1': {0: 59, 1: 103, 2: 71, 3: 23, 4: 138, 5: 61, 6: 72, 7: 123, 8: 66, 9: 140, 10: 112, 11: 73, 12: 24, 13: 79, 14: 64, 15: 131, 16: 84, 17: 78, 18: 42, 19: 137, 20: 43, 21: 50, 22: 57, 23: 69, 24: 139, 25: 68}, 'CC(C)(C)C(NC(=O)C(F)(F)F)C(=O)N1CC2(CC1C(=O)NC(C#N)CC1CCNC1=O)SCCS2': {0: 13, 1: 36, 2: 14, 3: 15, 4: 29, 5: 3, 6: 31, 7: 2, 8: 35, 9: 17, 10: 18, 11: 19, 12: 33, 13: 10, 14: 11, 15: 12, 16: 23, 17: 7, 18: 26, 19: 32, 20: 6, 21: 5, 22: 28, 23: 34, 24: 16, 25: 22, 26: 27, 27: 21, 28: 20, 29: 1, 30: 30, 31: 4, 32: 8, 33: 24, 34: 25, 35: 9}, 'CC=CC#CC#CC(O)C(C=CCCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 112, 1: 94, 2: 98, 3: 186, 4: 189, 5: 205, 6: 182, 7: 129, 8: 63, 9: 152, 10: 108, 11: 97, 12: 143, 13: 114, 14: 91, 15: 32, 16: 127, 17: 140, 18: 167, 19: 148, 20: 144, 21: 145, 22: 119, 23: 157, 24: 131, 25: 128, 26: 46, 27: 117, 28: 64, 29: 133, 30: 71, 31: 114, 32: 91, 33: 130, 34: 77, 35: 148, 36: 74, 37: 122, 38: 92}, 'CCC(C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {0: 50, 1: 54, 2: 76, 3: 123, 4: 94, 5: 22, 6: 170, 7: 75, 8: 67, 9: 159, 10: 129, 11: 24, 12: 90, 13: 152, 14: 175, 15: 93, 16: 51, 17: 118, 18: 176, 19: 67, 20: 82, 21: 165, 22: 178, 23: 106, 24: 171, 25: 190, 26: 87, 27: 102, 28: 192, 29: 100, 30: 111, 31: 195, 32: 216, 33: 203, 34: 209, 35: 215, 36: 120, 37: 132, 38: 126, 39: 211, 40: 90}, 'CCC(C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 57, 1: 58, 2: 64, 3: 56, 4: 100, 5: 74, 6: 38, 7: 61, 8: 51, 9: 65, 10: 30, 11: 113, 12: 76, 13: 27, 14: 129, 15: 81, 16: 67, 17: 130, 18: 72, 19: 144, 20: 132, 21: 138, 22: 144, 23: 127, 24: 154, 25: 98, 26: 69, 27: 81}, 'CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N)ncnn23)C(O)C1O)Oc1ccccc1': {0: 66, 1: 78, 2: 97, 3: 85, 4: 75, 5: 113, 6: 129, 7: 166, 8: 126, 9: 143, 10: 111, 11: 61, 12: 120, 13: 177, 14: 134, 15: 101, 16: 127, 17: 102, 18: 225, 19: 181, 20: 109, 21: 210, 22: 151, 23: 125, 24: 224, 25: 208, 26: 31, 27: 129, 28: 161, 29: 159, 30: 165, 31: 116, 32: 49, 33: 130, 34: 47, 35: 139, 36: 217, 37: 132, 38: 120, 39: 111, 40: 127, 41: 141}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 31, 1: 34, 2: 47, 3: 49, 4: 60, 5: 109, 6: 70, 7: 115, 8: 34, 9: 114, 10: 121, 11: 80, 12: 57, 13: 130, 14: 66, 15: 72, 16: 70, 17: 72, 18: 58, 19: 50, 20: 57, 21: 72, 22: 88}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 48, 1: 66, 2: 36, 3: 72, 4: 56, 5: 125, 6: 91, 7: 93, 8: 66, 9: 122, 10: 140, 11: 100, 12: 76, 13: 77, 14: 155, 15: 147, 16: 150, 17: 115, 18: 63, 19: 121, 20: 81, 21: 94, 22: 57, 23: 63, 24: 87, 25: 92, 26: 40, 27: 95, 28: 82}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 38, 1: 42, 2: 17, 3: 48, 4: 46, 5: 57, 6: 56, 7: 95, 8: 80, 9: 28, 10: 109, 11: 46, 12: 44, 13: 58, 14: 108, 15: 55, 16: 85, 17: 73, 18: 60, 19: 115}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 17, 1: 8, 2: 7, 3: 23, 4: 14, 5: 19, 6: 28, 7: 3, 8: 22, 9: 5, 10: 16, 11: 11, 12: 10, 13: 1, 14: 6, 15: 30, 16: 21, 17: 27, 18: 18, 19: 26, 20: 13, 21: 12, 22: 29, 23: 9, 24: 24, 25: 2, 26: 25, 27: 4, 28: 20, 29: 15}, 'CN(C(=O)Cc1cccs1)C(Cc1c[nH]c2ccccc12)C(=O)NC(C)(Cc1ccccc1)C(=O)NC(CCCNC(=N)N)C(=O)N1CCCC1C(=O)NC(CCCNC(=N)N)C(N)=O': {0: 33, 1: 36, 2: 53, 3: 14, 4: 43, 5: 63, 6: 51, 7: 49, 8: 45, 9: 32, 10: 47, 11: 29, 12: 65, 13: 52, 14: 7, 15: 61, 16: 42, 17: 13, 18: 21, 19: 40, 20: 64, 21: 54, 22: 11, 23: 15, 24: 57, 25: 26, 26: 30, 27: 62, 28: 38, 29: 22, 30: 24, 31: 23, 32: 39, 33: 60, 34: 18, 35: 17, 36: 46, 37: 25, 38: 34, 39: 31, 40: 8, 41: 59, 42: 4, 43: 2, 44: 58, 45: 16, 46: 28, 47: 19, 48: 27, 49: 20, 50: 48, 51: 56, 52: 12, 53: 10, 54: 44, 55: 35, 56: 41, 57: 37, 58: 6, 59: 50, 60: 3, 61: 1, 62: 55, 63: 5, 64: 9}, 'CN1CCCC(OC(=O)C(O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNCC(O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 17, 1: 9, 2: 13, 3: 11, 4: 24, 5: 27, 6: 23, 7: 42, 8: 18, 9: 47, 10: 2, 11: 51, 12: 29, 13: 21, 14: 19, 15: 22, 16: 30, 17: 50, 18: 37, 19: 32, 20: 35, 21: 49, 22: 14, 23: 15, 24: 25, 25: 10, 26: 8, 27: 43, 28: 7, 29: 54, 30: 40, 31: 38, 32: 53, 33: 12, 34: 5, 35: 20, 36: 33, 37: 3, 38: 52, 39: 34, 40: 26, 41: 45, 42: 1, 43: 46, 44: 4, 45: 36, 46: 6, 47: 28, 48: 31, 49: 48, 50: 39, 51: 41, 52: 44, 53: 16}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 6, 1: 1, 2: 9, 3: 7, 4: 5, 5: 12, 6: 10, 7: 8, 8: 13, 9: 14, 10: 11, 11: 4, 12: 2, 13: 3}, 'COc1c(C2C(C(=O)Nc3ccnc(C(N)=O)c3)OC(C)(C(F)(F)F)C2C)ccc(F)c1F': {0: 7, 1: 9, 2: 30, 3: 32, 4: 13, 5: 14, 6: 24, 7: 6, 8: 3, 9: 27, 10: 20, 11: 15, 12: 1, 13: 28, 14: 25, 15: 2, 16: 4, 17: 23, 18: 5, 19: 26, 20: 10, 21: 33, 22: 16, 23: 17, 24: 18, 25: 21, 26: 8, 27: 22, 28: 19, 29: 29, 30: 11, 31: 31, 32: 12}, 'COc1ccc(CCCCOC2OC(CO)C(O)C(O)C2O)cc1': {0: 90, 1: 61, 2: 132, 3: 71, 4: 90, 5: 131, 6: 77, 7: 79, 8: 77, 9: 85, 10: 78, 11: 70, 12: 89, 13: 68, 14: 79, 15: 25, 16: 63, 17: 35, 18: 75, 19: 38, 20: 64, 21: 49, 22: 96, 23: 78}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 52, 1: 65, 2: 136, 3: 71, 4: 68, 5: 144, 6: 133, 7: 67, 8: 130, 9: 65, 10: 88, 11: 138, 12: 160, 13: 115, 14: 87, 15: 29, 16: 49, 17: 65, 18: 57, 19: 47, 20: 63, 21: 73, 22: 101, 23: 71, 24: 92, 25: 108, 26: 97, 27: 161, 28: 78}, 'Cc1ccc(C2OC(CO)C(O)C(O)C2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 82, 1: 143, 2: 83, 3: 103, 4: 156, 5: 84, 6: 94, 7: 71, 8: 74, 9: 32, 10: 56, 11: 42, 12: 69, 13: 41, 14: 69, 15: 49, 16: 114, 17: 154, 18: 71, 19: 145, 20: 118, 21: 111, 22: 154, 23: 159, 24: 62, 25: 70, 26: 155, 27: 164, 28: 76, 29: 68, 30: 107}, 'Cc1ccc(N)cc1C(=O)NC(C)c1cccc2ccccc12': {0: 55, 1: 104, 2: 63, 3: 30, 4: 116, 5: 12, 6: 54, 7: 118, 8: 109, 9: 63, 10: 26, 11: 64, 12: 57, 13: 117, 14: 76, 15: 86, 16: 42, 17: 122, 18: 48, 19: 45, 20: 54, 21: 66, 22: 129}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 33, 1: 84, 2: 52, 3: 63, 4: 63, 5: 37, 6: 65, 7: 70, 8: 27, 9: 47, 10: 41, 11: 46, 12: 95, 13: 62, 14: 71, 15: 56, 16: 70, 17: 49, 18: 110, 19: 54, 20: 104, 21: 122, 22: 57, 23: 65, 24: 82}, 'Cn1cc(Nc2nccc(N3CC4CCC(C3)N4C(=O)C3CC3(F)F)n2)cn1': {0: 62, 1: 46, 2: 72, 3: 128, 4: 29, 5: 133, 6: 81, 7: 85, 8: 85, 9: 133, 10: 34, 11: 75, 12: 81, 13: 55, 14: 61, 15: 89, 16: 85, 17: 43, 18: 121, 19: 78, 20: 86, 21: 59, 22: 153, 23: 146, 24: 152, 25: 102, 26: 103, 27: 59}, 'Cn1cnc2ncn(Cc3nc(C4COC(c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 13, 1: 6, 2: 20, 3: 2, 4: 24, 5: 1, 6: 22, 7: 11, 8: 12, 9: 25, 10: 3, 11: 19, 12: 23, 13: 7, 14: 10, 15: 21, 16: 28, 17: 17, 18: 15, 19: 26, 20: 14, 21: 16, 22: 18, 23: 9, 24: 4, 25: 8, 26: 27, 27: 5, 28: 29}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCCC3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 60, 1: 128, 2: 96, 3: 85, 4: 51, 5: 80, 6: 119, 7: 125, 8: 155, 9: 97, 10: 98, 11: 96, 12: 172, 13: 151, 14: 108, 15: 27, 16: 88, 17: 66, 18: 60, 19: 106, 20: 147, 21: 94, 22: 33, 23: 111, 24: 169, 25: 70, 26: 88, 27: 169, 28: 199, 29: 181, 30: 187, 31: 193, 32: 99, 33: 76, 34: 101, 35: 111}, 'NC1(C(=O)NC(CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 44, 1: 148, 2: 119, 3: 87, 4: 45, 5: 94, 6: 73, 7: 55, 8: 30, 9: 143, 10: 65, 11: 65, 12: 135, 13: 151, 14: 71, 15: 71, 16: 71, 17: 89, 18: 48, 19: 157, 20: 105, 21: 115, 22: 84, 23: 158, 24: 44, 25: 95, 26: 72, 27: 168, 28: 102, 29: 86}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 44, 1: 65, 2: 46, 3: 40, 4: 85, 5: 77, 6: 83, 7: 89, 8: 23, 9: 44, 10: 41, 11: 103, 12: 48, 13: 53, 14: 52, 15: 78, 16: 117, 17: 113, 18: 119, 19: 125, 20: 26, 21: 47}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 80, 1: 102, 2: 27, 3: 140, 4: 77, 5: 51, 6: 141, 7: 71, 8: 152, 9: 139, 10: 145, 11: 151, 12: 57, 13: 88, 14: 122, 15: 56, 16: 87, 17: 93, 18: 150, 19: 23, 20: 82, 21: 140, 22: 77, 23: 107, 24: 45, 25: 162, 26: 63, 27: 46, 28: 84, 29: 69, 30: 149}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 9, 1: 15, 2: 3, 3: 30, 4: 14, 5: 31, 6: 11, 7: 27, 8: 21, 9: 22, 10: 10, 11: 29, 12: 32, 13: 18, 14: 12, 15: 16, 16: 1, 17: 13, 18: 19, 19: 17, 20: 25, 21: 8, 22: 23, 23: 24, 24: 4, 25: 20, 26: 2, 27: 33, 28: 7, 29: 28, 30: 6, 31: 26, 32: 5}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 7, 1: 24, 2: 28, 3: 22, 4: 21, 5: 17, 6: 3, 7: 26, 8: 27, 9: 18, 10: 11, 11: 2, 12: 12, 13: 19, 14: 6, 15: 4, 16: 13, 17: 23, 18: 1, 19: 20, 20: 25, 21: 15, 22: 9, 23: 8, 24: 10, 25: 16, 26: 14, 27: 5}, 'O=C1CCC(N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 91, 1: 137, 2: 79, 3: 59, 4: 110, 5: 43, 6: 90, 7: 163, 8: 175, 9: 68, 10: 92, 11: 157, 12: 87, 13: 95, 14: 166, 15: 100, 16: 30, 17: 79, 18: 61, 19: 64, 20: 67, 21: 87, 22: 107, 23: 93, 24: 99, 25: 123, 26: 93, 27: 184, 28: 168, 29: 106, 30: 163, 31: 95, 32: 35}}

In [151]:
from rdkit import Chem
def canonicalsmiles_noisomeric(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [152]:
df_total = pd.read_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
xenosite_results = [result_new.get(canonicalsmiles_noisomeric(i),'None') for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,somp_results,xenosite_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ...","{0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120,...","{0: 13, 1: 36, 2: 14, 3: 15, 4: 29, 5: 3, 6: 3..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ...","{0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61...","{0: 50, 1: 54, 2: 76, 3: 123, 4: 94, 5: 22, 6:..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3...","{0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6:...","{0: 31, 1: 34, 2: 47, 3: 49, 4: 60, 5: 109, 6:..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3...","{0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6...","{0: 59, 1: 103, 2: 71, 3: 23, 4: 138, 5: 61, 6..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11...","{0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6...","{0: 55, 1: 104, 2: 63, 3: 30, 4: 116, 5: 12, 6..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3...","{0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177,...","{0: 62, 1: 46, 2: 72, 3: 128, 4: 29, 5: 133, 6..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ...","{0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211...","{0: 52, 1: 73, 2: 167, 3: 118, 4: 37, 5: 198, ..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ...","{0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, ...","{0: 82, 1: 143, 2: 83, 3: 103, 4: 156, 5: 84, ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ...","{0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6...","{0: 80, 1: 102, 2: 27, 3: 140, 4: 77, 5: 51, 6..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ...","{0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6...","{0: 44, 1: 148, 2: 119, 3: 87, 4: 45, 5: 94, 6..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ...","{0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6:...","{0: 17, 1: 8, 2: 7, 3: 23, 4: 14, 5: 19, 6: 28..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6...","{0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, ...","{0: 52, 1: 65, 2: 136, 3: 71, 4: 68, 5: 144, 6..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ...","{0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, ...","{0: 112, 1: 94, 2: 98, 3: 186, 4: 189, 5: 205,..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4...","{0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6:...","{0: 33, 1: 84, 2: 52, 3: 63, 4: 63, 5: 37, 6: ..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2...","{0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136,...","{0: 90, 1: 61, 2: 132, 3: 71, 4: 90, 5: 131, 6..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73...","{0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, ...","{0: 9, 1: 15, 2: 3, 3: 30, 4: 14, 5: 31, 6: 11..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6...","{0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39,...","{0: 17, 1: 9, 2: 13, 3: 11, 4: 24, 5: 27, 6: 2..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33...","{0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: ...","{0: 57, 1: 58, 2: 64, 3: 56, 4: 100, 5: 74, 6:..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:...","{0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195...","{0: 33, 1: 36, 2: 53, 3: 14, 4: 43, 5: 63, 6: ..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4...","{0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6:...","{0: 48, 1: 66, 2: 36, 3: 72, 4: 56, 5: 125, 6:..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7...","{0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, ...","{0: 7, 1: 9, 2: 30, 3: 32, 4: 13, 5: 14, 6: 24..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1...","{0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: ...","{0: 38, 1: 42, 2: 17, 3: 48, 4: 46, 5: 57, 6: ..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4...","{0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61,...","{0: 60, 1: 128, 2: 96, 3: 85, 4: 51, 5: 80, 6:..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:...","{0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129,...","{0: 66, 1: 78, 2: 97, 3: 85, 4: 75, 5: 113, 6:..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ...","{0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161,...","{0: 91, 1: 137, 2: 79, 3: 59, 4: 110, 5: 43, 6..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18...","{0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: ...","{0: 6, 1: 1, 2: 9, 3: 7, 4: 5, 5: 12, 6: 10, 7..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6...","{0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, ...","{0: 13, 1: 6, 2: 20, 3: 2, 4: 24, 5: 1, 6: 22,..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,...","{0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 41...",None
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ...","{0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, ...","{0: 7, 1: 24, 2: 28, 3: 22, 4: 21, 5: 17, 6: 3..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ...","{0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: ...","{0: 44, 1: 65, 2: 46, 3: 40, 4: 85, 5: 77, 6: ..."

In [153]:
df_total.to_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')

7. 整理全部结果

In [154]:
import pandas as pd
from rdkit import Chem

def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

df = pd.read_csv('30_main_true.csv')
substrate = df['substrate'].to_list()
truth = df['truth'].to_list()
site_truth = df['site_truth'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['substrate'] = substrate
df.to_csv('30_main_true.csv',index=None)

In [155]:
df = pd.read_csv('predict_site.csv')
substrate = df['substrate'].to_list()
# truth = df['truth'].to_list()
# site_truth = df['site_truth'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['substrate'] = substrate
df.to_csv('predict_site.csv',index=None)

In [156]:
df = pd.read_csv('pred_results_score_new.csv')
substrate = df['substrate'].to_list()
# truth = df['truth'].to_list()
# site_truth = df['site_truth'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['substrate'] = substrate
df.to_csv('pred_results_score_new.csv',index=None)

In [157]:
df = pd.read_csv('metapredictor_som_main30.csv')
substrate = df['truth'].to_list()
# truth = df['truth'].to_list()
# site_truth = df['site_truth'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['truth'] = substrate
df.to_csv('metapredictor_som_main30.csv',index=None)

In [158]:
df = pd.read_csv('predict_site_our.csv')
substrate = df['substrate'].to_list()
# truth = df['truth'].to_list()
# site_truth = df['site_truth'].to_list()
substrate = list(map(canonicalsmiles,substrate))
df['substrate'] = substrate
df.to_csv('predict_site_our.csv',index=None)

In [159]:
df_total = pd.DataFrame()

df = pd.read_csv('30_main_true.csv')
substrate = df['substrate'].to_list()
truth = df['truth'].to_list()
site_truth = df['site_truth'].to_list()

df_total['substrate'] = substrate
df_total['metabolite'] = truth
df_total['site_true'] = site_truth

df_metapredictor = pd.read_csv('metapredictor_som_main30.csv')
metapredictor_predict = df_metapredictor['grouped'].to_list()
df_total['metapredictor_predict'] = metapredictor_predict

df_our = pd.read_csv('from_smiles_extract.csv')
our_predict = df_our['pred_site'].to_list()
df_total['our_predict'] = our_predict
df_total

,substrate,metabolite,site_true,metapredictor_predict,our_predict
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,CC[C@H](n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)...,CC[C@@H](C(=O)NC1=C[CH:1]=[C:1](C(N)=O)C(F)=C1...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC([CH3:1])CC21,CCCCCC1=CC(O)=C2C(=C1)OC(C)([CH3:1])C1CCC(C)CC...,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC([CH3:1])CC21|...
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)[NH:1]c1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccc...,CC(=O)NC1=CC=C([CH3:1])C(C(=O)N[C@H](C)/C2=C/C...,CC(=O)[NH:1]c1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccc...
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1c[cH:1]c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC1=CC=C(N)C=C1C(=O)N[C@H](C)/C1=C/C=C\C2=C[CH...,Cc1ccc([NH2:1])cc1C(=O)N[C@H](C)c1cccc2ccccc12...
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,Cn1cc([NH:1]c2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O...,CN1C=C(N[C:1]2=[N:1][CH:1]=[CH:1][C:1](N3C[C@@...,C[n:1]1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)...
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(/C3=C/N(...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[n:1](C...
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H:1]([OH:1...,CC1=CC=C([C@@H]2O[C@H](C[OH:1])[C@@H](O)[C@H](...,OC[C@H]1O[C@@H](c2ccc([CH3:1])c(Cc3ccc(-c4ccc(...
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1c[cH:1]nc2...,O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C([NH:1]C/C2=C/...,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1[NH:1]Cc1ccnc2...
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,NC1(C(=O)N[C@@H](CC[OH:1])c2ccc(Cl)cc2)CCN(c2n...,NC1(C(=O)N[C@@H](CC[OH:1])C2=CC=C(Cl)C=C2)CCN(...,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncn[c:...
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,CCOc1ccc([NH:1][C:1](=S)N(CC[OH:1])Cc2cc3cc(C)...,CCOC1=CC=C(NC(=S)N(CCO)C/C2=C/C3=CC(C)=CC(C)=C...,CC[O:1]c1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH...
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,COc1ccc2c(Oc3ccc(C4(C(=O)N[OH:1])CCOCC4)cc3)cc...,COC1=C\C=C2\C([O:1]C3=CC=C(C4(C(=O)NO)CCOCC4)C...,COc1ccc2c(Oc3ccc(C4(C(=O)[NH:1]O)CCOCC4)cc3)cc...
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,O=S(=O)(c1cnc([CH3:1])s1)N1CCC(c2cn3ncnc3cc2Cl...,CC1=NC=C(S(=O)(=O)[N:1]2CCC(C3=C/N4N=CN=C4/C=C...,O=S(=O)(c1cnc([CH3:1])s1)N1CCC(c2cn3ncnc3cc2Cl...
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,C[O:1]c1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H...,COC1=CC=C(CCCC[O:1]C2OC(CO)[C@@H](O)[C@H](O)[C...,C[O:1]c1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H...
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,O=C(O)C1OC([O:1]c2cc3oc(-c4ccc(O)cc4)cc(=O)c3c...,O=C1C=C(C2=CC=C(O)C=C2)OC2=C1C(O)=C(O)C([O:1]C...,O=C(O)C1OC([O:1]c2cc3oc(-c4ccc(O)cc4)cc(=O)c3c...
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(c2ccccc2)c2cccc...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(C2=CC=CC=C2)C2=...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(c2ccccc2)c2cccc...
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,CC[C@@H](C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F...,CC[C@H](C)C(=O)N1CCC(NC(=O)N[C:1]2=[CH:1][CH:1...,C[C@@H](C[CH3:1])C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)...
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)CC1=CC=CS1)[C@@H](C/C1=C/NC2=CC=CC=C21...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,CCN(CC)C(=O)C1C=C2c3cccc4c3c(c[n:1]4C(=O)C3CC3...,CCN(CC)C(=O)C1/C=C2/C3=CC=CC4=C3C(=C[N:1]4C(=O...,CC[N:1](CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3...
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,C[C@H]1[C@@H](c2ccc(F)c(F)c2[O:1]C)C(C(=O)Nc2c...,COC1=C([C@H]2C(C(=O)NC3=CC=NC(C(N)=O)=C3)O[C@@...,COc1c([C@H]2C([C:1](=O)Nc3ccnc(C(N)=[O:1])c3)O...
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12,CCN(CC)CCc1c[nH]c2cccc([O:1]C(C)=O)c12,CCN(CC)CCC1=CNC2=C1C([O:1]C(C)=O)=CC=C2|CC[N:1...,CCN(CC)CCc1c[nH]c2cccc([O:1]C(C)=O)c12|CCN(CC)...
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,N#CC1C[N:1](S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C...,N#CC1CN(S(=O)(=O)C2=CC(C(=O)N3CCC[C@@H]3C(=O)N...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOC[CH2:1]5)cc...,[H][C@@]1(N2CC3=C(C=CC=C3OCC3=CC=C(CN4CCOCC4)C...,O=C1CC[C@@H](N2Cc3c(cccc3[O:1]Cc3ccc(CN4CCOCC4...
25,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2,CC(Cc1ccc2c(c1)OCO2)[NH:1]C,CNC(C)CC1=CC=C2O[CH2:1][O:1]C2=C1|CNC(C)CC1=CC...,CC(Cc1ccc2c(c1)OCO2)[NH:1]C|CN[CH:1](C)Cc1ccc2...
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,Cn1cnc2n[cH:1]n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl...,CN1C=NC2=C1C(=O)N(CC1=NC([C@@H]3CO[C@@H]([C:1]...,C[n:1]1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)...
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,O=C(c1cccnc1-c1ccncc1)N1CCC(Cc2ccccc2)([OH:1])CC1,O=C(C1=CC=CN=C1C1=CC=NC=C1)N1CCC(O)(C[C:1]2=[C...,O=C(c1cccnc1-c1cc[n:1]cc1)N1CCC(O)(Cc2ccccc2)C...
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,O=[C:1](N1CCC2(CC1)[CH2:1][C:1]([C:1](F)(F)F)=...,O=C(CCC(F)(F)F)[N:1]1CCC2(CC1)CC(C(F)(F)F)=NO2...,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=[N:1][O...

In [160]:
df_total.to_csv('30_results.csv',index=None)

In [161]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

def df_col_getatomindices(dfname,col_old,flat=False):
    preds = dfname[col_old].to_list()
    preds = [i.split('|') for i in preds]
    try:
        preds = [list(map(standardize_smiles_with_atom_map,i)) for i in preds]
        ranks = [list(map(get_reactive_atom_indices,i)) for i in preds]
    except:
        ranks = []
        for k in preds:
            preds_part = []
            for x in k:
                try:
                    x = standardize_smiles_with_atom_map(x)
                    x_new = get_reactive_atom_indices(x)
                except:
                    x_new = []
                preds_part.append(x_new)
            ranks.append(preds_part)
    if flat == True:
        ranks_new = []
        for i in ranks:
            list_part = []
            for j in i:
                list_part = list_part + j
            ranks_new.append(list_part)
        return ranks_new
    else:
        return ranks

In [162]:
df = pd.read_csv('30_results.csv')
df.fillna('None', inplace=True)
sites_true = df_col_getatomindices(df,'site_true',flat=True)
metapredictor_predict = df_col_getatomindices(df,'metapredictor_predict',flat=False)
our_predict = df_col_getatomindices(df,'our_predict',flat=False)
df['sites'] = sites_true
df['metapredictor_ranks'] = metapredictor_predict
df['ourmodel_ranks'] = our_predict
df

[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Explicit valence for atom # 20 C, 5, is greater than permitted
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Explicit valence for atom # 18 C, 5, is greater than permitted
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:37] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] SMILES Parse Error: syntax error while parsing: Error:
[06:45:38] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] SMILES Parse Error: syntax error while parsing: Error:
[06:45:38] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:45:38] SMILES Parse Error: syntax error while parsing: Error:
[06:45:38] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] SMILES Parse Error: syntax error while parsing: Error:
[06:45:38] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:45:38] SMILES Parse Error: syntax error while parsing: Error:
[06:45:38] SMILES Parse Error: Failed parsing SMILES 'Error:' for input: 'Error:'
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger
[06:45:38] Running Uncharger

,substrate,metabolite,site_true,metapredictor_predict,our_predict,sites,metapredictor_ranks,ourmodel_ranks
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,[30],"[[35], [35], [29], [29], [28], [26], [34], [12...","[[35], [35], [29], [28], [30], [19, 31], [34, ..."
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,CC[C@H](n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)...,CC[C@@H](C(=O)NC1=C[CH:1]=[C:1](C(N)=O)C(F)=C1...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,"[28, 37]","[[10, 14], [19], [22, 37], [29, 30, 31, 36, 37...","[[], [28, 37], [], [7], [19], [19], [14], [16]..."
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC([CH3:1])CC21,CCCCCC1=CC(O)=C2C(=C1)OC(C)([CH3:1])C1CCC(C)CC...,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC([CH3:1])CC21|...,[20],"[[15], [19], [10], [20], [18], [18, 19], [9, 1...","[[20], [19], [15], [9, 10], [18], [16], [3], [..."
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)[NH:1]c1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccc...,CC(=O)NC1=CC=C([CH3:1])C(C(=O)N[C@H](C)/C2=C/C...,CC(=O)[NH:1]c1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccc...,[3],"[[8], [15, 24], [3], [21, 22], [4, 5, 6, 7, 9,...","[[3], [5, 6, 16], [18], [10, 11, 12], [12], [3..."
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1c[cH:1]c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC1=CC=C(N)C=C1C(=O)N[C@H](C)/C1=C/C=C\C2=C[CH...,Cc1ccc([NH2:1])cc1C(=O)N[C@H](C)c1cccc2ccccc12...,[3],"[[19, 20], [13, 22], [15, 16], [5], [21], [10]...","[[5], [3], [], [16], [1, 4, 5, 7, 14, 15, 18, ..."
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,Cn1cc([NH:1]c2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O...,CN1C=C(N[C:1]2=[N:1][CH:1]=[CH:1][C:1](N3C[C@@...,C[n:1]1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)...,[4],"[[5, 6, 7, 8, 9, 25], [1, 2, 3, 26, 27], [26, ...","[[1], [27], [8], [17], [4], [24], [10, 24], [1..."
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(/C3=C/N(...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[n:1](C...,[40],"[[40], [36], [15], [39], [9, 10, 11, 12, 19, 3...","[[22], [7, 15], [40], [15], [4], [36], [36], [..."
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H:1]([OH:1...,CC1=CC=C([C@@H]2O[C@H](C[OH:1])[C@@H](O)[C@H](...,OC[C@H]1O[C@@H](c2ccc([CH3:1])c(Cc3ccc(-c4ccc(...,"[12, 13]","[[9], [18], [11], [15], [13], [1, 2, 3, 4, 16,...","[[9], [18], [30], [4], [3], [8, 9], [19, 20, 2..."
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1c[cH:1]nc2...,O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C([NH:1]C/C2=C/...,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1[NH:1]Cc1ccnc2...,[23],"[[19], [21, 30], [16, 17], [3, 4, 5, 6, 12, 13...","[[19], [7], [24], [23], [23], [12], [16], [13]..."
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,NC1(C(=O)N[C@@H](CC[OH:1])c2ccc(Cl)cc2)CCN(c2n...,NC1(C(=O)N[C@@H](CC[OH:1])C2=CC=C(Cl)C=C2)CCN(...,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncn[c:...,[8],"[[8], [19, 20, 21, 22, 23, 27], [7], [27], [21...","[[23, 24, 25, 26, 27], [8], [7, 8], [8], [23, ..."
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,CCOc1ccc([NH:1][C:1](=S)N(CC[OH:1])Cc2cc3cc(C)...,CCOC1=CC=C(NC(=S)N(CCO)C/C2=C/C3=CC(C)=CC(C)=C...,CC[O:1]c1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH...,"[7, 8, 13]","[[28, 29], [13], [10], [20], [2], [29], [25], ...","[[2], [10], [20], [], [26, 27], [7, 8, 27], [1..."
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,COc1ccc2c(Oc3ccc(C4(C(=O)N[OH:1])CCOCC4)cc3)cc...,COC1=C\C=C2\C([O:1]C3=CC=C(C4(C(=O)NO)CCOCC4)C...,COc1ccc2c(Oc3ccc(C4(C(=O)[NH:1]O)CCOCC4)cc3)cc...,[16],"[[7], [16], [15], [8, 9, 10, 11, 22, 23], [], ...","[[15], [1], [13, 16], [15, 16], [19, 20], [21]..."
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(C[O:1]C2OC(C...,[21],"[[21], [16], [14, 15], [14], [15], [26], [14, ...","[[21], [9, 33, 34, 35, 36, 37, 38], [14, 15], ..."
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,O=S(=O)(c1cnc([CH3:1])s1)N1CCC(c2cn3ncnc3cc2Cl...,CC1=NC=C(S(=O)(=O)[N:1]2CCC(C3=C/N4N=CN=C4/C=C...,O=S(=O)(c1cnc([CH3:1])s1)N1CCC(c2cn3ncnc3cc2Cl...,[7],"[[8], [14, 15, 16, 17, 18], [12, 21], [17, 18]...","[[7], [16], [8, 23], [23], [24], [22], [16], [..."
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,C[O:1]c1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H...,COC1=CC=C(CCCC[O:1]C2OC(CO)[C@@H](O)[C@H](O)[C...,C[O:1]c1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H...,[1],"[[10], [22, 23], [2, 3, 4, 5, 22, 23], [15], [...","[[1], [15], [10], [6], [23], [1], [15], [22], ..."
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,O=C(O)C1OC([O:1]c2cc3oc(-c4ccc(O)cc4)cc(=O)c3c...,O=C1C=C(C2=CC=C(O)C=C2)OC2=C1C(O)=C(O)C([O:1]C...,O=C(O)C1OC([O:1]c2cc3oc(-c4ccc(O)cc4)cc(=O)c3c...,[6],"[[6], [26], [5], [28], [], [17], [12, 18], [19...","[[6], [16], [16], [5, 6, 24], [26], [24], [5, ..."
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(c2ccccc2)c2cccc...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(C2=CC=CC=C2)C2=...,CN1CCC[C@@H]([O:1]C(=O)[C@](O)(c2ccccc2)c2cccc...,[6],"[[6], [1], [9], [51, 52], [50, 51], [42], [29,...","[[6], [34], [1], [25, 46], [33, 46], [32, 36, ..."
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,CC[C@@H](C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F...,CC[C@H](C)C(=O)N1CCC(NC(=O)N[C:1]2=[CH:1][CH:1...,C[C@@H](C[CH3:1])C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)...,[27],"[[14, 15, 16, 17, 23, 25], [26], [27], [10], [...","[[3], [18], [27], [], [26], [25], [26], [4, 27..."
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)CC1=CC=CS1)[C@@H](C/C1=C/NC2=CC=CC=C21...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,[],"[[49], [7, 8], [62], [61], [17, 18], [48], [57...","[[23], [51, 64], [18], [23], [51, 64], [], [23..."
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,CCN(CC)C(=O)C1C=C2c3cccc4c3c(c[n:1]4C(=O)C3CC3...,CCN(CC)C(=O)C1/C=C2/C3=CC=CC4=C3C(=C[N:1]4C(=O...,CC[N:1](CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3...,[18],"[[18], [26], [2], [12, 13], [21], [23], [7], [...","[[2], [26], [18], [4], [23], [24], [26], [28],..."
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,C[C@H]1[C@@H](c2ccc(F)c(F)c2[O:1]C)C(C(=O)Nc2c...,COC1=C([C@H]2C(C(=O)NC3=CC=NC(C(N)=O)=C3)O[C@@...,COc1c([C@H]2C([C:1](=O)Nc3ccnc(C(N)=[O:1])c3)O...,[11],"[[], [32], [15, 16], [29, 31], [7, 8], [4], [1...","[[6, 16], [], [11], [12], [6, 16], [16], [8], ..."
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12,CCN(CC)CCc1c[nH]c2cccc([O:1]C(C)=O)c12,CCN(CC)CCC1=CNC2=C1C([O:1]C(C)=O)=CC=C2|CC[N:1...,CCN(CC)CCc1c[nH]c2cccc([O:1]C(C)=O)c12|CCN(CC)...,[15],"[[15], [2], [7, 8, 9, 10, 19], [18, 19], [12],...","[[15], [13], [2], [2], [19], [12], [2, 15], [5..."
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,N#CC1C[N:1](S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C...,N#CC1CN(S(=O)(=O)C2=CC(C(=O)N3CCC[C@@H]3C(=O)N...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,[4],"[[33, 34], [8, 9, 10, 11, 12, 34], [35], [34],...","[[22], [1], [4, 35], [4, 35], [], [32, 33], [1..."
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...,CCC(CC)C[O:1]C(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[...,[6],"[[6], [35], [6, 35], [34], [11], [9], [40, 41]...","[[6], [11, 41], [41], [21], [39], [9], [7, 41]..."
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOC[CH2:1]5)cc...,[H][C@@]1(N2CC3=C(C=CC=C3OCC3=CC=C(CN4CCOCC4)C...,O=C1CC[C@@H](N2Cc3c(cccc3[O:1]Cc3ccc(CN4CCOCC4...,[21],"[[30], [4], [10], [21], [5], [], [16], [30, 31...","[[13], [28, 30], [15, 19], [19, 20], [16, 19, ..."
25,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2,CC(Cc1ccc2c(c1)OCO2)[NH:1]C,CNC(C)CC1=CC=C2O[CH2:1][O:1]C2=C1|CNC(C)CC1=CC...,CC(Cc1ccc2c(c1)OCO2)[NH:1]C|CN[CH:1](C)Cc1ccc2...,[12],"[[11, 12], [12], [9, 10, 11], [11, 13], [5, 6,...","[[12], [2], [12], [11, 13], [12], [], [], [4],..."
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,Cn1cnc2n[cH:1]n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl...,CN1C=NC2=C1C(=O)N(CC1=NC([C@@H]3CO[C@@H]([C:1]...,C[n:1]1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)...,[6],"[[16, 17, 18, 19, 21, 22], [1], [6], [9, 25], ...","[[1], [8, 27], [9, 10, 11, 24, 25], [9, 10, 11..."
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,[28],"[[28], [66], [4], [4, 28], [70], [13], [44], [...","[[23], [66], [28], [23, 48], [13], [66], [23, ..."
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,O=C(c1cccnc1-c1ccncc1)N1CCC(Cc2ccccc2)([OH:1])CC1,O=C(C1=CC=CN=C1C1=CC=NC=C1)N1CCC(O)(C[C:1]2=[C...,O=C(c1cccnc1-c1cc[n:1]cc1)N1CCC(O)(Cc2ccccc2)C...,[25],"[[20, 21, 22, 23, 24, 25], [23, 24], [24, 25],...","[[11], [23], [25], [27], [4], [19], [5, 6, 12,..."
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,O=[C:1](N1CCC2(CC1)[CH2:1][C:1]([C:1](F)(F)F)=...,O=C(CCC(F)(F)F)[N:1]1CCC2(CC1)CC(C(F)(F)F)=NO2...,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=[N:1][O...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","[[8], [15, 20], [21], [15], [15, 21], [21], [1...","[[20, 21], [21], [21], [20], [8], [3], [11, 20..."

In [163]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

In [164]:
metapredictor_results_old = df['metapredictor_ranks'].to_list()
ourmodel_results_old = df['ourmodel_ranks'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)
metapredictor_results_new = []
for i in metapredictor_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    metapredictor_results_new.append(list_part)

true_sites = df['sites'].to_list()

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites)
metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites)
metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites)
metapredictor_topn = []
metapredictor_topn.append(metapredictor_top1_acc)
metapredictor_topn.append(metapredictor_top3_acc)
metapredictor_topn.append(metapredictor_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.3333333333333333
top 3 accuracy = 0.43333333333333335
top 5 accuracy = 0.6
top 1 accuracy = 0.36666666666666664
top 3 accuracy = 0.6333333333333333
top 5 accuracy = 0.8

In [165]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['metapredictor_topn'] = metapredictor_topn
df['ourmodel_topn'] = ourmodel_topn
df

         top_n  metapredictor_topn  ourmodel_topn
0  top1_recall            0.333333       0.366667
1  top3_recall            0.433333       0.633333
2  top5_recall            0.600000       0.800000

In [168]:
import pandas as pd
df_total = pd.read_pickle('output_30_site_truth_correct_withatomidx_noenzyme.pickle')

In [169]:
gnn_results = df_total['gnn_results'].to_list()
smartcyp_results = df_total['smartcyp_results'].to_list()
xenosite_results = df_total['xenosite_results'].to_list()
somp_results = df_total['somp_results'].to_list()

gnn_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in gnn_results]
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in smartcyp_results]
# xenosite_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in xenosite_results]
xenosite_sorted_atoms = []
for i in xenosite_results:
    try:
        sub_result = [k for k, v in sorted(i.items(), key=lambda item: item[1])]
    except:
        sub_result = ['None']
    xenosite_sorted_atoms.append(sub_result)
somp_sorted_atoms = []
for i in somp_results:
    try:
        sub_result = [k for k, v in sorted(i.items(), key=lambda item: item[1])]
    except:
        sub_result = ['None']
    somp_sorted_atoms.append(sub_result)
# somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in somp_results]

df_total['gnn_results'] = gnn_sorted_atoms
df_total['smartcyp_results'] = smartcyp_sorted_atoms
df_total['xenosite_results'] = xenosite_sorted_atoms
df_total['somp_results'] = somp_sorted_atoms
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,somp_results,xenosite_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"[6, 23, 1, 32, 35, 34, 2, 5, 24, 33, 3, 13, 27...","[17, 12, 15, 24, 13, 14, 20, 23, 3, 22, 25, 21...","[13, 16, 6, 4, 11, 7, 19, 8, 23, 26, 28, 3, 12...","[29, 7, 5, 31, 21, 20, 17, 32, 35, 13, 14, 15,..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","[3, 29, 5, 10, 40, 7, 37, 39, 32, 34, 24, 2, 1...","[11, 35, 26, 29, 23, 17, 12, 8, 2, 16, 21, 34,...","[11, 13, 28, 27, 5, 12, 15, 17, 30, 31, 36, 35...","[5, 11, 0, 16, 1, 8, 19, 7, 2, 20, 26, 12, 40,..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"[7, 8, 6, 1, 0, 14, 13, 15, 2, 11, 3, 19, 21, ...","[18, 1, 17, 22, 19, 2, 4, 21, 0, 16, 20, 3, 6,...","[1, 0, 4, 3, 2, 20, 18, 17, 19, 14, 15, 6, 21,...","[0, 1, 8, 2, 3, 19, 12, 20, 18, 4, 14, 6, 16, ..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"[10, 12, 3, 1, 13, 16, 22, 11, 14, 23, 20, 17,...","[0, 8, 21, 22, 13, 18, 20, 17, 5, 23, 16, 3, 6...","[8, 18, 22, 14, 23, 19, 5, 21, 3, 0, 13, 17, 2...","[3, 12, 18, 20, 21, 22, 0, 5, 14, 8, 25, 23, 2..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"[10, 5, 8, 11, 20, 18, 21, 4, 3, 9, 19, 14, 6,...","[5, 3, 0, 6, 19, 20, 11, 16, 18, 15, 2, 21, 14...","[0, 16, 20, 3, 5, 12, 21, 17, 19, 15, 11, 22, ...","[5, 10, 3, 16, 19, 18, 6, 20, 0, 12, 2, 9, 11,..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"[0, 4, 1, 18, 19, 16, 20, 11, 24, 22, 15, 6, 1...","[0, 11, 16, 12, 15, 21, 20, 10, 26, 4, 2, 13, ...","[0, 13, 17, 23, 14, 15, 24, 26, 12, 27, 16, 1,...","[4, 10, 17, 1, 13, 21, 27, 14, 0, 2, 11, 19, 6..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"[13, 40, 41, 15, 42, 37, 36, 23, 22, 33, 16, 3...","[0, 41, 42, 37, 23, 26, 25, 39, 38, 16, 33, 27...","[41, 42, 23, 37, 33, 16, 38, 40, 39, 17, 27, 1...","[8, 4, 36, 40, 0, 1, 22, 26, 17, 18, 25, 32, 2..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","[30, 15, 21, 29, 24, 14, 13, 9, 19, 12, 16, 25...","[8, 10, 7, 12, 14, 18, 5, 0, 30, 25, 28, 21, 2...","[35, 0, 10, 6, 9, 30, 13, 33, 16, 19, 2, 15, 1...","[9, 13, 11, 15, 10, 24, 29, 12, 14, 25, 7, 18,..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"[1, 28, 29, 19, 22, 26, 2, 27, 12, 0, 5, 24, 7...","[17, 25, 16, 21, 24, 23, 29, 30, 26, 5, 12, 28...","[17, 30, 25, 4, 24, 13, 29, 8, 5, 12, 26, 9, 2...","[19, 2, 24, 27, 5, 15, 12, 26, 29, 7, 4, 22, 0..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"[8, 2, 24, 4, 7, 1, 15, 25, 18, 3, 10, 0, 5, 1...","[26, 17, 28, 25, 7, 22, 0, 20, 5, 18, 11, 14, ...","[8, 6, 5, 17, 12, 30, 15, 0, 23, 18, 7, 29, 11...","[8, 0, 24, 4, 18, 7, 10, 11, 14, 15, 16, 26, 6..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","[13, 10, 8, 12, 9, 1, 14, 7, 2, 11, 23, 18, 20...","[11, 14, 20, 23, 9, 1, 12, 21, 10, 0, 25, 7, 1...","[12, 4, 17, 23, 11, 29, 14, 15, 1, 2, 3, 24, 8...","[13, 25, 7, 27, 9, 14, 2, 1, 23, 12, 11, 21, 2..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"[15, 16, 0, 13, 1, 2, 28, 3, 4, 7, 24, 26, 6, ...","[0, 18, 20, 26, 28, 17, 21, 3, 24, 4, 9, 23, 1...","[0, 18, 20, 17, 21, 15, 24, 10, 9, 14, 22, 23,...","[15, 19, 16, 0, 18, 20, 1, 9, 17, 7, 4, 3, 23,..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"[15, 14, 8, 26, 7, 30, 32, 6, 21, 29, 25, 4, 3...","[25, 0, 22, 27, 17, 1, 24, 29, 14, 7, 31, 2, 2...","[14, 11, 20, 10, 1, 0, 25, 2, 12, 9, 29, 7, 13...","[15, 26, 8, 28, 30, 36, 34, 14, 32, 38, 1, 11,..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"[5, 7, 6, 14, 24, 15, 8, 4, 13, 9, 23, 21, 22,...","[0, 17, 14, 9, 24, 15, 3, 13, 7, 21, 11, 8, 12...","[24, 7, 21, 0, 17, 2, 3, 12, 14, 1, 6, 15, 16,...","[8, 0, 5, 10, 11, 9, 17, 2, 19, 15, 22, 13, 3,..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"[0, 23, 22, 1, 3, 2, 4, 15, 11, 21, 10, 9, 5, ...","[0, 14, 11, 16, 13, 18, 20, 9, 6, 3, 23, 8, 7,...","[0, 9, 14, 6, 7, 17, 20, 3, 23, 19, 8, 26, 16,...","[15, 17, 19, 21, 1, 16, 20, 13, 11, 3, 18, 6, ..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"[14, 17, 6, 19, 26, 25, 11, 23, 18, 24, 16, 32...","[31, 5, 3, 29, 27, 17, 20, 16, 21, 8, 13, 0, 2...","[17, 20, 29, 8, 31, 16, 1, 21, 13, 18, 7, 27, ...","[16, 26, 2, 24, 32, 30, 28, 21, 0, 10, 6, 14, ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"[42, 10, 5, 36, 9, 6, 37, 41, 7, 27, 26, 1, 28...","[25, 26, 23, 35, 37, 36, 5, 27, 38, 3, 28, 44,...","[26, 5, 16, 51, 36, 25, 15, 3, 17, 23, 28, 40,...","[42, 10, 37, 44, 34, 46, 28, 26, 1, 25, 3, 33,..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"[4, 11, 5, 7, 8, 13, 26, 18, 19, 10, 27, 17, 6...","[1, 2, 9, 0, 7, 27, 3, 8, 26, 16, 15, 25, 6, 1...","[0, 2, 1, 8, 12, 3, 4, 28, 20, 7, 16, 9, 5, 27...","[13, 10, 6, 8, 3, 0, 1, 7, 2, 9, 16, 26, 18, 5..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"[1, 0, 21, 2, 10, 60, 42, 59, 51, 23, 9, 3, 39...","[9, 5, 13, 8, 23, 46, 6, 62, 27, 49, 26, 50, 6...","[59, 6, 26, 35, 36, 46, 55, 40, 3, 54, 15, 39,...","[61, 43, 60, 42, 63, 58, 14, 40, 64, 53, 22, 5..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"[5, 2, 6, 26, 27, 28, 7, 1, 3, 19, 12, 18, 0, ...","[0, 24, 2, 11, 25, 26, 1, 16, 7, 9, 27, 8, 10,...","[0, 7, 9, 2, 15, 8, 25, 10, 26, 4, 22, 16, 14,...","[2, 26, 0, 4, 22, 18, 23, 1, 8, 3, 12, 13, 20,..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"[8, 6, 16, 1, 0, 14, 25, 27, 4, 15, 26, 10, 29...","[0, 12, 28, 5, 4, 15, 25, 27, 10, 11, 17, 20, ...","[0, 28, 5, 27, 21, 11, 29, 30, 6, 7, 18, 34, 2...","[12, 15, 8, 16, 18, 7, 0, 26, 1, 20, 30, 32, 4..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"[15, 1, 3, 16, 4, 0, 2, 14, 13, 5, 12, 11, 6, ...","[14, 16, 0, 12, 18, 6, 7, 11, 5, 15, 17, 13, 2...","[14, 16, 12, 5, 6, 0, 13, 15, 17, 1, 7, 2, 4, ...","[2, 9, 0, 1, 12, 4, 11, 3, 15, 6, 5, 13, 18, 1..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"[5, 22, 20, 6, 7, 0, 1, 17, 18, 32, 13, 28, 2,...","[2, 16, 25, 4, 3, 15, 17, 5, 28, 30, 9, 11, 27...","[3, 6, 16, 18, 11, 14, 26, 5, 10, 8, 12, 17, 2...","[15, 22, 4, 0, 18, 17, 25, 33, 5, 3, 16, 26, 2..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"[32, 31, 11, 7, 5, 6, 12, 35, 19, 33, 22, 14, ...","[17, 1, 2, 18, 14, 6, 38, 40, 24, 22, 7, 13, 2...","[7, 1, 43, 40, 45, 34, 2, 42, 9, 44, 25, 28, 4...","[26, 34, 32, 11, 0, 4, 1, 3, 2, 15, 17, 20, 10..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"[9, 10, 16, 17, 2, 1, 21, 5, 6, 15, 18, 4, 22,...","[17, 21, 2, 15, 27, 10, 16, 18, 20, 5, 26, 0, ...","[11, 16, 17, 7, 0, 19, 21, 18, 28, 22, 8, 3, 1...","[16, 32, 5, 3, 18, 19, 20, 9, 2, 17, 12, 21, 6..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"[1, 0, 2, 4, 3, 7, 6, 5, 10, 9, 12, 11, 13, 8]","[0, 12, 2, 1, 4, 6, 7, 10, 3, 13, 8, 11, 9, 5]","[18, 0, 1, 2, 3, 7, 8, 5, 9, 13, 12, 10, 6, 16...","[1, 12, 13, 11, 4, 0, 3, 7, 2, 6, 10, 5, 8, 9]"
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"[7, 6, 8, 15, 5, 0, 13, 9, 22, 1, 17, 21, 18, ...","[26, 28, 5, 9, 10, 12, 4, 16, 18, 25, 13, 27, ...","[30, 5, 10, 14, 18, 20, 28, 11, 3, 9, 7, 4, 15...","[5, 3, 10, 24, 27, 1, 13, 25, 23, 14, 7, 8, 0,..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"[44, 43, 54, 53, 25, 41, 26, 42, 82, 80, 78, 7...","[44, 47, 79, 50, 74, 46, 39, 81, 31, 78, 82, 5...","[50, 23, 26, 72, 66, 74, 58, 53, 82, 18, 70, 1...",[None]
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"[18, 17, 14, 1, 5, 21, 12, 23, 16, 26, 4, 6, 2...","[11, 19, 23, 6, 22, 24, 21, 25, 15, 27, 10, 12...","[23, 4, 15, 22, 11, 27, 19, 24, 16, 26, 1, 21,...","[18, 11, 6, 15, 27, 14, 0, 23, 22, 24, 10, 12,..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","[20, 1, 8, 10, 9, 13, 11, 21, 16, 0, 12, 15, 2...","[8, 17, 16, 3, 7, 4, 6, 2, 18, 10, 14, 9, 0, 1...","[17, 3, 7, 16, 2, 5, 1, 4, 6, 8, 18, 19, 20, 2...","[8, 20, 3, 10, 0, 9, 2, 21, 12, 14, 13, 1, 5, ..."

In [170]:
df_total.to_pickle('output_30_site_truth_correct_withrank_noenzyme.pickle')

In [172]:
df_total = pd.read_pickle('output_30_site_truth_correct_withrank_noenzyme.pickle')

# metapredictor_results_old = df_total['metapredictor_results_old'].to_list()
# ourmodel_results_old = df_total['ourmodel_results_old'].to_list()
# ourmodel_results_new = []
# for i in ourmodel_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     ourmodel_results_new.append(list_part)
# metapredictor_results_new = []
# for i in metapredictor_results_old:
#     list_part = []
#     for j in i:
#         list_part = list_part + j
#     metapredictor_results_new.append(list_part)

# true_sites_old = df_total['true_sites_old'].to_list()
true_sites = df_total['sites'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

# def acc_top_n_old(n,modelresults,true_sites):
#     total_num = len(true_sites)
#     correct_num = 0
#     for idx,i in enumerate(true_sites):
#         modelresult = modelresults[idx]
#         modelresult = get_unique_numbers(modelresult, n)
#         modelresult = set(modelresult)
#         i = set(i)
#         intersection = i & modelresult
#         if len(intersection) > 0:
#             correct_num = correct_num + 1
#     acc = correct_num/total_num
#     print(f'top {n} accuracy = {acc}')
#     return acc

gnn_top1_acc = acc_top_n(1,gnn_sorted_atoms,true_sites)
gnn_top3_acc = acc_top_n(3,gnn_sorted_atoms,true_sites)
gnn_top5_acc = acc_top_n(5,gnn_sorted_atoms,true_sites)
gnn_topn = []
gnn_topn.append(gnn_top1_acc)
gnn_topn.append(gnn_top3_acc)
gnn_topn.append(gnn_top5_acc)

smartcyp_top1_acc = acc_top_n(1,smartcyp_sorted_atoms,true_sites)
smartcyp_top3_acc = acc_top_n(3,smartcyp_sorted_atoms,true_sites)
smartcyp_top5_acc = acc_top_n(5,smartcyp_sorted_atoms,true_sites)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

xenosite_top1_acc = acc_top_n(1,xenosite_sorted_atoms,true_sites)
xenosite_top3_acc = acc_top_n(3,xenosite_sorted_atoms,true_sites)
xenosite_top5_acc = acc_top_n(5,xenosite_sorted_atoms,true_sites)
xenosite_topn = []
xenosite_topn.append(xenosite_top1_acc)
xenosite_topn.append(xenosite_top3_acc)
xenosite_topn.append(xenosite_top5_acc)

somp_top1_acc = acc_top_n(1,somp_sorted_atoms,true_sites)
somp_top3_acc = acc_top_n(3,somp_sorted_atoms,true_sites)
somp_top5_acc = acc_top_n(5,somp_sorted_atoms,true_sites)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

# metapredictor_top1_acc = acc_top_n_old(1,metapredictor_results_new,true_sites_old)
# metapredictor_top3_acc = acc_top_n_old(3,metapredictor_results_new,true_sites_old)
# metapredictor_top5_acc = acc_top_n_old(5,metapredictor_results_new,true_sites_old)
# metapredictor_topn = []
# metapredictor_topn.append(metapredictor_top1_acc)
# metapredictor_topn.append(metapredictor_top3_acc)
# metapredictor_topn.append(metapredictor_top5_acc)

# ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
# ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
# ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
# ourmodel_topn = []
# ourmodel_topn.append(ourmodel_top1_acc)
# ourmodel_topn.append(ourmodel_top3_acc)
# ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.1
top 3 accuracy = 0.36666666666666664
top 5 accuracy = 0.4
top 1 accuracy = 0.03333333333333333
top 3 accuracy = 0.13333333333333333
top 5 accuracy = 0.2
top 1 accuracy = 0.16666666666666666
top 3 accuracy = 0.3333333333333333
top 5 accuracy = 0.4
top 1 accuracy = 0.06666666666666667
top 3 accuracy = 0.13333333333333333
top 5 accuracy = 0.16666666666666666

In [173]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['gnnsom_topn'] = gnn_topn
df['smartcyp_topn'] = smartcyp_topn
df['xenosite_topn'] = xenosite_topn
df['somp_topn'] = somp_topn
df['metapredictor_topn'] = metapredictor_topn
df['ourmodel_topn'] = ourmodel_topn
df

,top_n,gnnsom_topn,smartcyp_topn,xenosite_topn,somp_topn,metapredictor_topn,ourmodel_topn
0,top1_recall,0.100000,0.033333,0.166667,0.066667,0.333333,0.366667
1,top3_recall,0.366667,0.133333,0.333333,0.133333,0.433333,0.633333
2,top5_recall,0.400000,0.200000,0.400000,0.166667,0.600000,0.800000