In [1]:
import pandas as pd
import os
from rdkit import Chem

In [2]:
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [3]:
df_substrates = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/main_cases/pred_results_score_new.csv')
substrates = df_substrates['substrate'].to_list()
dict_idx2sub = dict(zip(list(range(len(substrates))),substrates))
dict_idx2sub

{0: 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2',
 1: 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O',
 2: 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21',
 3: 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1',
 4: 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12',
 5: 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1',
 6: 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C',
 7: 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1',
 8: 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12',
 9: 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1',
 10: 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1',
 11: 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1',
 12: 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
 13: 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1',
 14: 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1',
 15: 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O',
 16: 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1',
 17: 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1',
 18: 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O',
 19: 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1',
 20: 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F',
 21: 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12',
 22: 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1',
 23: 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1',
 24: 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1',
 25: 'CNC(C)Cc1ccc2c(c1)OCO2',
 26: 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21',
 27: 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O',
 28: 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1',
 29: 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2'}

In [4]:
dirpath = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/30_main_cases'
filepathlist = os.listdir(dirpath)
substrates_new = []
enzymes_new = []
dicts_new = []

for filepath in filepathlist:
    idx = int(filepath.split('_')[0])
    substrates_new.append(dict_idx2sub[idx])
    enzyme = filepath.split('_')[1].split('.')[0]
    enzymes_new.append(enzyme)
    filepathfull = dirpath + '/' + filepath
    df = pd.read_csv(filepathfull)
    atomnums = df['Atom number'].to_list()
    ranks = df['Rang'].to_list()
    dict_atomidx2rank = dict(zip(atomnums,ranks))
    dict_atomidx2rank = {k: dict_atomidx2rank[k] for k in sorted(dict_atomidx2rank)}
    dict_atomidx2rank = {k - 1: v for k, v in dict_atomidx2rank.items()}
    dicts_new.append(dict_atomidx2rank)
substrates_new = list(map(canonicalsmiles,substrates_new))


df_new = pd.DataFrame()
df_new['substrates'] = substrates_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = dicts_new
df_new

,substrates,enzyme,scores
0,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3A4,"{0: 57, 1: 46, 2: 31, 3: 16, 4: 29, 5: 34, 6: ..."
1,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,1A2,"{0: 13, 1: 14, 2: 15, 3: 16, 4: 1, 5: 39, 6: 3..."
2,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,2D6,"{0: 6, 1: 20, 2: 32, 3: 10, 4: 23, 5: 24, 6: 1..."
3,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,2C19,"{0: 29, 1: 36, 2: 19, 3: 3, 4: 21, 5: 11, 6: 8..."
4,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,2C19,"{0: 3, 1: 20, 2: 5, 3: 16, 4: 6, 5: 15, 6: 17,..."
...,...,...,...
175,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,UGT,"{0: 9, 1: 11, 2: 5, 3: 14, 4: 15, 5: 13, 6: 6,..."
176,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 15, 1: 5, 2: 11, 3: 2, 4: 7, 5: 6, 6: 8, 7..."
177,CNC(C)Cc1ccc2c(c1)OCO2,2C19,"{0: 2, 1: 4, 2: 5, 3: 6, 4: 20, 5: 3, 6: 14, 7..."
178,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,UGT,"{0: 9, 1: 19, 2: 5, 3: 2, 4: 23, 5: 24, 6: 22,..."
179,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,2D6,"{0: 1, 1: 29, 2: 19, 3: 14, 4: 13, 5: 26, 6: 2..."

In [5]:
df_new.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/somp_results_30.pickle')

In [6]:
df = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/somp_results_30.pickle')
df

,substrates,enzyme,scores
0,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3A4,"{0: 57, 1: 46, 2: 31, 3: 16, 4: 29, 5: 34, 6: ..."
1,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,1A2,"{0: 13, 1: 14, 2: 15, 3: 16, 4: 1, 5: 39, 6: 3..."
2,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,2D6,"{0: 6, 1: 20, 2: 32, 3: 10, 4: 23, 5: 24, 6: 1..."
3,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,2C19,"{0: 29, 1: 36, 2: 19, 3: 3, 4: 21, 5: 11, 6: 8..."
4,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,2C19,"{0: 3, 1: 20, 2: 5, 3: 16, 4: 6, 5: 15, 6: 17,..."
...,...,...,...
175,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,UGT,"{0: 9, 1: 11, 2: 5, 3: 14, 4: 15, 5: 13, 6: 6,..."
176,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 15, 1: 5, 2: 11, 3: 2, 4: 7, 5: 6, 6: 8, 7..."
177,CNC(C)Cc1ccc2c(c1)OCO2,2C19,"{0: 2, 1: 4, 2: 5, 3: 6, 4: 20, 5: 3, 6: 14, 7..."
178,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,UGT,"{0: 9, 1: 19, 2: 5, 3: 2, 4: 23, 5: 24, 6: 22,..."
179,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,2D6,"{0: 1, 1: 29, 2: 19, 3: 14, 4: 13, 5: 26, 6: 2..."

In [7]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, 6: 119, 7: 93, 8: 174, 9: 86, 10: 50, 11: 46, 12: 81, 13: 95, 14: 34, 15: 170, 16: 158, 17: 126, 18: 175, 19: 135, 20: 48, 21: 170, 22: 139, 23: 178, 24: 151, 25: 56, 26: 167, 27: 99, 28: 161, 29: 91, 30: 168, 31: 128, 32: 171, 33: 104, 34: 175, 35: 97, 36: 183, 37: 131, 38: 186}, 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211, 6: 118, 7: 202, 8: 174, 9: 221, 10: 136, 11: 173, 12: 226, 13: 130, 14: 143, 15: 186, 16: 56, 17: 79, 18: 85, 19: 207, 20: 217, 21: 164, 22: 126, 23: 32, 24: 220, 25: 128, 26: 100, 27: 79, 28: 128, 29: 240, 30: 166, 31: 185, 32: 208, 33: 40, 34: 118, 35: 160, 36: 109, 37: 38, 38: 67, 39: 74, 40: 68, 41: 23, 42: 29}, 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': {0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6: 85, 7: 117, 8: 14, 9: 138, 10: 119, 11: 99, 12: 136, 13: 69, 14: 35, 15: 88, 16: 148, 17: 74, 18: 20, 19: 48, 20: 115, 21: 58, 22: 27, 23: 42, 24: 78, 25: 131, 26: 100}, 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': {0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120, 6: 44, 7: 50, 8: 56, 9: 194, 10: 165, 11: 47, 12: 98, 13: 12, 14: 168, 15: 174, 16: 18, 17: 113, 18: 173, 19: 52, 20: 226, 21: 207, 22: 105, 23: 58, 24: 121, 25: 134, 26: 64, 27: 133, 28: 83, 29: 130, 30: 214, 31: 151, 32: 192, 33: 127, 34: 197, 35: 138, 36: 187, 37: 127, 38: 133, 39: 139}, 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': {0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 411, 6: 272, 7: 374, 8: 199, 9: 287, 10: 153, 11: 202, 12: 369, 13: 316, 14: 371, 15: 131, 16: 131, 17: 139, 18: 106, 19: 152, 20: 147, 21: 277, 22: 201, 23: 60, 24: 330, 25: 201, 26: 62, 27: 290, 28: 207, 29: 319, 30: 343, 31: 272, 32: 270, 33: 413, 34: 364, 35: 310, 36: 249, 37: 242, 38: 337, 39: 146, 40: 433, 41: 419, 42: 297, 43: 290, 44: 384, 45: 193, 46: 343, 47: 282, 48: 413, 49: 172, 50: 57, 51: 367, 52: 363, 53: 85, 54: 332, 55: 323, 56: 197, 57: 370, 58: 80, 59: 419, 60: 376, 61: 400, 62: 166, 63: 357, 64: 165, 65: 387, 66: 73, 67: 351, 68: 260, 69: 408, 70: 125, 71: 141, 72: 67, 73: 341, 74: 73, 75: 347, 76: 414, 77: 323, 78: 320, 79: 409, 80: 439, 81: 333, 82: 92, 83: 366, 84: 205, 85: 194, 86: 399, 87: 394}, 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': {0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129, 6: 155, 7: 45, 8: 152, 9: 82, 10: 189, 11: 240, 12: 186, 13: 172, 14: 154, 15: 124, 16: 147, 17: 190, 18: 257, 19: 150, 20: 153, 21: 201, 22: 195, 23: 135, 24: 129, 25: 88, 26: 212, 27: 121, 28: 94, 29: 220, 30: 193, 31: 192, 32: 125, 33: 109, 34: 68, 35: 115, 36: 131, 37: 239, 38: 167, 39: 215, 40: 59, 41: 94, 42: 78, 43: 58, 44: 84, 45: 64}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6: 66, 7: 101, 8: 101, 9: 128, 10: 115, 11: 80, 12: 106, 13: 102, 14: 59, 15: 65, 16: 112, 17: 50, 18: 47, 19: 58, 20: 37, 21: 79, 22: 112}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6: 99, 7: 24, 8: 61, 9: 30, 10: 67, 11: 90, 12: 167, 13: 161, 14: 76, 15: 44, 16: 72, 17: 140, 18: 165, 19: 100, 20: 115, 21: 121, 22: 69, 23: 95, 24: 79, 25: 62, 26: 68, 27: 139, 28: 130}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: 37, 7: 58, 8: 107, 9: 116, 10: 105, 11: 79, 12: 30, 13: 45, 14: 14, 15: 49, 16: 20, 17: 55, 18: 88, 19: 93}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6: 171, 7: 124, 8: 88, 9: 165, 10: 127, 11: 45, 12: 27, 13: 121, 14: 51, 15: 59, 16: 179, 17: 42, 18: 165, 19: 161, 20: 198, 21: 162, 22: 178, 23: 43, 24: 85, 25: 91, 26: 97, 27: 146, 28: 206, 29: 47, 30: 103, 31: 109, 32: 115, 33: 222, 34: 196, 35: 209, 36: 176, 37: 94, 38: 130}, 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61, 6: 135, 7: 142, 8: 108, 9: 128, 10: 211, 11: 24, 12: 64, 13: 44, 14: 183, 15: 67, 16: 208, 17: 71, 18: 108, 19: 188, 20: 223, 21: 155, 22: 100, 23: 153, 24: 134, 25: 137, 26: 137, 27: 55, 28: 47, 29: 125, 30: 73, 31: 87, 32: 175, 33: 129, 34: 100, 35: 96, 36: 90, 37: 139, 38: 166, 39: 123, 40: 129, 41: 135}, 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: 89, 7: 73, 8: 50, 9: 78, 10: 92, 11: 144, 12: 52, 13: 127, 14: 123, 15: 153, 16: 77, 17: 86, 18: 114, 19: 138, 20: 71, 21: 111, 22: 117, 23: 123, 24: 151, 25: 101, 26: 95, 27: 84, 28: 56}, 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': {0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195, 6: 60, 7: 281, 8: 241, 9: 244, 10: 219, 11: 335, 12: 355, 13: 292, 14: 301, 15: 104, 16: 242, 17: 146, 18: 113, 19: 261, 20: 263, 21: 207, 22: 139, 23: 110, 24: 171, 25: 169, 26: 67, 27: 287, 28: 247, 29: 251, 30: 226, 31: 272, 32: 192, 33: 223, 34: 186, 35: 68, 36: 74, 37: 264, 38: 207, 39: 108, 40: 85, 41: 114, 42: 213, 43: 293, 44: 292, 45: 221, 46: 80, 47: 116, 48: 275, 49: 364, 50: 351, 51: 341, 52: 402, 53: 200, 54: 99, 55: 84, 56: 216, 57: 413, 58: 200, 59: 31, 60: 152, 61: 238, 62: 147, 63: 353, 64: 237, 65: 280, 66: 206, 67: 119, 68: 193}, 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39, 6: 284, 7: 254, 8: 123, 9: 102, 10: 137, 11: 285, 12: 197, 13: 237, 14: 135, 15: 76, 16: 51, 17: 82, 18: 141, 19: 228, 20: 235, 21: 258, 22: 96, 23: 89, 24: 174, 25: 75, 26: 23, 27: 96, 28: 95, 29: 138, 30: 185, 31: 178, 32: 227, 33: 200, 34: 166, 35: 223, 36: 70, 37: 231, 38: 110, 39: 119, 40: 95, 41: 306, 42: 291, 43: 187, 44: 113, 45: 261, 46: 270, 47: 230, 48: 262, 49: 210, 50: 217, 51: 66, 52: 167, 53: 240, 54: 172, 55: 206}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: 82, 7: 38, 8: 44, 9: 50, 10: 79, 11: 106, 12: 70, 13: 68, 14: 94, 15: 101, 16: 87, 17: 95, 18: 17, 19: 95}, 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': {0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, 6: 72, 7: 80, 8: 96, 9: 132, 10: 187, 11: 51, 12: 169, 13: 111, 14: 203, 15: 176, 16: 129, 17: 138, 18: 81, 19: 130, 20: 130, 21: 50, 22: 146, 23: 89, 24: 95, 25: 101, 26: 104, 27: 44, 28: 32, 29: 62, 30: 63, 31: 151, 32: 118, 33: 170, 34: 84}, 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': {0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136, 6: 44, 7: 49, 8: 67, 9: 23, 10: 131, 11: 97, 12: 119, 13: 108, 14: 33, 15: 111, 16: 73, 17: 51, 18: 113, 19: 64, 20: 57, 21: 116, 22: 87, 23: 63, 24: 121, 25: 107, 26: 68}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, 6: 140, 7: 136, 8: 92, 9: 72, 10: 70, 11: 93, 12: 113, 13: 110, 14: 73, 15: 53, 16: 86, 17: 45, 18: 21, 19: 102, 20: 27, 21: 51, 22: 76, 23: 78, 24: 60, 25: 113, 26: 119, 27: 148, 28: 127}, 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': {0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6: 79, 7: 127, 8: 109, 9: 88, 10: 122, 11: 70, 12: 41, 13: 79, 14: 130, 15: 68, 16: 21, 17: 47, 18: 102, 19: 55, 20: 29, 21: 44, 22: 72, 23: 116}, 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, 6: 52, 7: 156, 8: 133, 9: 58, 10: 27, 11: 158, 12: 87, 13: 64, 14: 161, 15: 80, 16: 70, 17: 163, 18: 86, 19: 76, 20: 167, 21: 114, 22: 162, 23: 101, 24: 179, 25: 92, 26: 117, 27: 180, 28: 169, 29: 95, 30: 61, 31: 160, 32: 177, 33: 67, 34: 101, 35: 19}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6: 72, 7: 27, 8: 105, 9: 126, 10: 105, 11: 77, 12: 65, 13: 92, 14: 65, 15: 73, 16: 74, 17: 53, 18: 145, 19: 117, 20: 111, 21: 33, 22: 94, 23: 100, 24: 13}, 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': {0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177, 6: 119, 7: 148, 8: 99, 9: 173, 10: 119, 11: 121, 12: 66, 13: 26, 14: 51, 15: 57, 16: 72, 17: 32, 18: 127, 19: 120, 20: 110, 21: 119, 22: 84, 23: 38, 24: 58, 25: 100, 26: 62, 27: 68, 28: 159, 29: 112, 30: 110}, 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, 6: 99, 7: 83, 8: 126, 9: 79, 10: 49, 11: 70, 12: 156, 13: 115, 14: 55, 15: 85, 16: 116, 17: 86, 18: 59, 19: 143, 20: 65, 21: 92, 22: 145, 23: 100, 24: 105, 25: 123, 26: 147, 27: 96, 28: 66, 29: 87, 30: 21}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61, 6: 39, 7: 147, 8: 76, 9: 157, 10: 74, 11: 52, 12: 86, 13: 190, 14: 53, 15: 109, 16: 39, 17: 93, 18: 45, 19: 115, 20: 100, 21: 113, 22: 119, 23: 135, 24: 101, 25: 186, 26: 59, 27: 176, 28: 96, 29: 132, 30: 102, 31: 138, 32: 153, 33: 149, 34: 147, 35: 153, 36: 159}, 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6: 42, 7: 79, 8: 24, 9: 136, 10: 142, 11: 82, 12: 57, 13: 142, 14: 139, 15: 63, 16: 88, 17: 55, 18: 73, 19: 98, 20: 174, 21: 100, 22: 96, 23: 70, 24: 154, 25: 145, 26: 102, 27: 95, 28: 112, 29: 79, 30: 61}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: 55, 7: 37, 8: 56, 9: 108, 10: 122, 11: 92, 12: 98, 13: 104, 14: 87, 15: 89, 16: 43, 17: 25, 18: 64, 19: 70, 20: 76, 21: 82}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6: 103, 7: 139, 8: 64, 9: 88, 10: 94, 11: 100, 12: 79, 13: 52, 14: 146, 15: 128, 16: 103, 17: 25, 18: 174, 19: 90, 20: 138, 21: 108, 22: 177, 23: 89, 24: 48, 25: 35, 26: 81, 27: 186, 28: 96, 29: 61, 30: 30}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, 6: 142, 7: 75, 8: 51, 9: 169, 10: 151, 11: 132, 12: 105, 13: 69, 14: 156, 15: 124, 16: 62, 17: 26, 18: 74, 19: 138, 20: 32, 21: 68, 22: 158, 23: 121, 24: 133, 25: 92, 26: 129, 27: 78, 28: 132, 29: 49, 30: 122, 31: 52, 32: 122}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, 6: 84, 7: 154, 8: 154, 9: 89, 10: 128, 11: 44, 12: 134, 13: 95, 14: 87, 15: 39, 16: 58, 17: 108, 18: 119, 19: 48, 20: 108, 21: 76, 22: 42, 23: 24, 24: 48, 25: 82, 26: 64, 27: 45}, 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161, 6: 90, 7: 43, 8: 69, 9: 154, 10: 133, 11: 28, 12: 120, 13: 88, 14: 113, 15: 153, 16: 35, 17: 40, 18: 62, 19: 46, 20: 108, 21: 52, 22: 68, 23: 119, 24: 94, 25: 169, 26: 131, 27: 106, 28: 66, 29: 136, 30: 135, 31: 159, 32: 178, 33: 143}}

In [8]:
len(list(result_new.keys()))

30

In [9]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
somp_results = [result_new.get(i,'None') for i in substrates]
df_total['somp_results'] = somp_results
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results,xenosite_results,somp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ...","{0: 13, 1: 36, 2: 14, 3: 15, 4: 29, 5: 3, 6: 3...","{0: 153, 1: 116, 2: 171, 3: 84, 4: 46, 5: 120,..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ...","{0: 50, 1: 54, 2: 76, 3: 123, 4: 94, 5: 22, 6:...","{0: 216, 1: 196, 2: 112, 3: 227, 4: 217, 5: 61..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3...","{0: 31, 1: 34, 2: 47, 3: 49, 4: 60, 5: 109, 6:...","{0: 16, 1: 13, 2: 36, 3: 31, 4: 29, 5: 113, 6:..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3...","{0: 59, 1: 103, 2: 71, 3: 23, 4: 138, 5: 61, 6...","{0: 64, 1: 97, 2: 108, 3: 61, 4: 146, 5: 51, 6..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11...","{0: 55, 1: 104, 2: 63, 3: 30, 4: 116, 5: 12, 6...","{0: 14, 1: 104, 2: 81, 3: 40, 4: 121, 5: 41, 6..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3...","{0: 62, 1: 46, 2: 72, 3: 128, 4: 29, 5: 133, 6...","{0: 20, 1: 73, 2: 102, 3: 119, 4: 135, 5: 177,..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ...","{0: 52, 1: 73, 2: 167, 3: 118, 4: 37, 5: 198, ...","{0: 86, 1: 102, 2: 119, 3: 164, 4: 139, 5: 211..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ...","{0: 82, 1: 143, 2: 83, 3: 103, 4: 156, 5: 84, ...","{0: 27, 1: 153, 2: 79, 3: 99, 4: 161, 5: 145, ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ...","{0: 80, 1: 102, 2: 27, 3: 140, 4: 77, 5: 51, 6...","{0: 106, 1: 92, 2: 97, 3: 128, 4: 46, 5: 73, 6..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ...","{0: 44, 1: 148, 2: 119, 3: 87, 4: 45, 5: 94, 6...","{0: 64, 1: 122, 2: 91, 3: 98, 4: 148, 5: 45, 6..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ...","{0: 17, 1: 8, 2: 7, 3: 23, 4: 14, 5: 19, 6: 28...","{0: 97, 1: 67, 2: 73, 3: 79, 4: 39, 5: 193, 6:..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6...","{0: 52, 1: 65, 2: 136, 3: 71, 4: 68, 5: 144, 6...","{0: 21, 1: 136, 2: 121, 3: 80, 4: 79, 5: 168, ..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ...","{0: 112, 1: 94, 2: 98, 3: 186, 4: 189, 5: 205,...","{0: 56, 1: 53, 2: 73, 3: 113, 4: 126, 5: 114, ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4...","{0: 33, 1: 84, 2: 52, 3: 63, 4: 63, 5: 37, 6: ...","{0: 34, 1: 68, 2: 56, 3: 60, 4: 100, 5: 85, 6:..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2...","{0: 90, 1: 61, 2: 132, 3: 71, 4: 90, 5: 131, 6...","{0: 17, 1: 140, 2: 110, 3: 62, 4: 101, 5: 136,..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73...","{0: 9, 1: 15, 2: 3, 3: 30, 4: 14, 5: 31, 6: 11...","{0: 88, 1: 64, 2: 136, 3: 112, 4: 121, 5: 83, ..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6...","{0: 17, 1: 9, 2: 13, 3: 11, 4: 24, 5: 27, 6: 2...","{0: 234, 1: 188, 2: 249, 3: 78, 4: 175, 5: 39,..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33...","{0: 57, 1: 58, 2: 64, 3: 56, 4: 100, 5: 74, 6:...","{0: 35, 1: 42, 2: 37, 3: 54, 4: 54, 5: 83, 6: ..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:...","{0: 33, 1: 36, 2: 53, 3: 14, 4: 43, 5: 63, 6: ...","{0: 336, 1: 240, 2: 192, 3: 98, 4: 189, 5: 195..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4...","{0: 48, 1: 66, 2: 36, 3: 72, 4: 56, 5: 125, 6:...","{0: 21, 1: 90, 2: 41, 3: 118, 4: 69, 5: 97, 6:..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7...","{0: 7, 1: 9, 2: 30, 3: 32, 4: 13, 5: 14, 6: 24...","{0: 23, 1: 166, 2: 128, 3: 142, 4: 90, 5: 37, ..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1...","{0: 38, 1: 42, 2: 17, 3: 48, 4: 46, 5: 57, 6: ...","{0: 42, 1: 58, 2: 70, 3: 83, 4: 78, 5: 33, 6: ..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4...","{0: 60, 1: 128, 2: 96, 3: 85, 4: 51, 5: 80, 6:...","{0: 158, 1: 206, 2: 147, 3: 34, 4: 119, 5: 61,..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:...","{0: 66, 1: 78, 2: 97, 3: 85, 4: 75, 5: 113, 6:...","{0: 127, 1: 46, 2: 75, 3: 180, 4: 147, 5: 129,..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ...","{0: 91, 1: 137, 2: 79, 3: 59, 4: 110, 5: 43, 6...","{0: 46, 1: 146, 2: 139, 3: 84, 4: 156, 5: 161,..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18...","{0: 6, 1: 1, 2: 9, 3: 7, 4: 5, 5: 12, 6: 10, 7...","{0: 19, 1: 20, 2: 26, 3: 32, 4: 90, 5: 47, 6: ..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6...","{0: 13, 1: 6, 2: 20, 3: 2, 4: 24, 5: 1, 6: 22,...","{0: 135, 1: 158, 2: 112, 3: 79, 4: 84, 5: 40, ..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,...",None,"{0: 382, 1: 195, 2: 135, 3: 246, 4: 141, 5: 41..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ...","{0: 7, 1: 24, 2: 28, 3: 22, 4: 21, 5: 17, 6: 3...","{0: 109, 1: 75, 2: 165, 3: 97, 4: 35, 5: 125, ..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ...","{0: 44, 1: 65, 2: 46, 3: 40, 4: 85, 5: 77, 6: ...","{0: 90, 1: 48, 2: 45, 3: 31, 4: 49, 5: 47, 6: ..."

In [17]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')