In [8]:
import pandas as pd
import os
from rdkit import Chem

In [9]:
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [10]:
df_substrates = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/GNN-SOM-master/123_site_from_smiles.csv')
substrates = df_substrates['substrate'].to_list()
dict_idx2sub = dict(zip(list(range(len(substrates))),substrates))
dict_idx2sub

{0: 'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O',
 1: 'CC(=O)NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2',
 2: 'CC(=O)NC1=CC=CC(N2C(=O)N(C3CC3)C(=O)C3=C(NC4=CC=C(I)C=C4F)N(C)C(=O)C(C)=C23)=C1',
 3: 'CC(C)(C)C1=CC(C(C)(C)C)=C(NC(=O)C2=CNC3=CC=CC=C3C2=O)C=C1O',
 4: 'CC(C)(C)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=CC(OCCN5CCOCC5)=CC=C43)C=C2)=NO1',
 5: 'CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=C(O)C=N3)CC2)C(=O)C1',
 6: 'CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1',
 7: 'CC1(C)CC(=O)N(CCCCN2CCN(C3=NC=CC=N3)CC2)C(=O)C1O',
 8: 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1',
 9: 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O',
 10: 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1',
 11: 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1',
 12: 'CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(O)C(C(F)(F)F)=C2)CC3)C1',
 13: 'CCC(=O)N1CC[C@H](NC2=NC=NC3=C2CN(C2=CN=C(OC)C(C(F)(F)F)=C2)CC3)C1',
 14: 'CCC(C)N1N=CN(C2=CC=C(N3CCN(C4=CC=C(OC[C@H]5CO[C@](CN6C=NC=N6)(C6=CC=C(Cl)C=C6Cl)O5)C=C4)CC3)C=C2)C1=O',
 15: 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O',
 16: 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O',
 17: 'CCCCCOC(=O)NC1=NC(=O)N([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)C=C1F',
 18: 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O',
 19: 'CCCC1=NC(C)=C2C(=O)N=C(C3=CC(S(=O)(=O)N4CCN(CC)CC4)=CC=C3OCC)NN12',
 20: 'CCN(CC)C(=O)[C@@]1(C2=CC=CC=C2)C[C@H]1CN',
 21: 'CCN[C@H]1CN(CCCOC)S(=O)(=O)C2=C1C=C(S(N)(=O)=O)S2',
 22: 'CCO[C@H]1CCN(CC2=C(OC)C=C(C)C3=C2C=CN3)[C@H](C2=CC=C(C(=O)O)C=C2)C1',
 23: 'CCOC1=CC=C(O)C=C1OCCN[C@H](C)CC1=CC=C(OC)C(S(N)(=O)=O)=C1',
 24: 'CC[C@@H](C1=CC(O)=CC(O)=C1)[C@@H](C)CN(C)C',
 25: 'CC[C@@H](C1=CC=CC(O)=C1)[C@@H](C)CN(C)C',
 26: 'CC[C@@H]1C(=O)OC[C@@H]1CC1=CN=CN1C',
 27: 'CN(C)CCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12',
 28: 'CN(C)CCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12',
 29: 'CN(C)CCC1=CNC2=CC(O)=C(CN3C=NC=N3)C=C12',
 30: 'CN(C)CCC1=CNC2=CC=C(CN3C=NC=N3)C=C12',
 31: 'CN1C(=O)CC(=O)N(C2=CC=C(O)C=C2)C2=CC(Cl)=CC=C12',
 32: 'CN1CC[C@@H](NC(=O)NC2=CC=C(C#N)C=C2)C[C@@H]1C1=NC2=CC=CC=C2N1',
 33: 'CNC(=O)C1=CC(OC2=CC=C(NC(=O)NC3=CC=C(Cl)C(C(F)(F)F)=C3)C=C2)=CC=N1',
 34: 'CNCC(=O)OCC1=CC=CN=C1N(C)C(=O)OC(C)[N+]1=CN(C[C@](O)(C2=CC(F)=CC=C2F)[C@@H](C)C2=NC(C3=CC=C(C#N)C=C3)=CS2)N=C1',
 35: 'CNCCCC1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12',
 36: 'CNCCC[C@@]1(C2=CC=C(F)C=C2)OCC2=CC(C#N)=CC=C12',
 37: 'COC1=C(OCCCN2CCOCC2)C=CC2=C1N=C(NC(=O)C1=CN=C(N)N=C1)N1CCN=C21',
 38: 'COC1=CC(C)=C2NC=CC2=C1CN1CC[C@H](O)C[C@H]1C1=CC=C(C(=O)O)C=C1',
 39: 'COC1=CC(NC2=C(C#N)C=NC3=CC(OCCCN4CCN(C)CC4)=C(OC)C=C23)=C(Cl)C=C1Cl',
 40: 'COC1=CC(OC)=CC(N(CCNC(C)C)C2=CC=C3N=CC(C4=CN(C)N=C4)=NC3=C2)=C1',
 41: 'COC1=CC2=C(C(OC)=C1OC)C1=CC=C(OC)C(=O)C=C1[C@@H](NC(C)=O)CC2',
 42: 'COC1=CC2=C(C=C1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2',
 43: 'COC1=CC=C(C[C@@H](C)NCCOC2=CC=CC=C2O)C=C1S(N)(=O)=O',
 44: 'COC1=CC=C2N=C(S(=O)CC3=NC=C(C)C(OC)=C3C)NC2=C1',
 45: 'COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)CC3',
 46: 'COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1',
 47: 'COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)(C(O)CO)CC3',
 48: 'COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C(O)=C1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1',
 49: 'COC1=NC(N)=NC2=C1N=CN2',
 50: 'COC1=NC(N)=NC2=C1N=CN2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O',
 51: 'COC1=NC2=CC=C(Br)C=C2C=C1[C@@H](C1=CC=CC=C1)[C@@](O)(CCN(C)C)C1=CC=CC2=CC=CC=C12',
 52: 'COC1=NC=C(N2CCC3=NC=NC(N)=C3C2)C=C1C(F)(F)F',
 53: 'CS(=O)(=O)C1=CC=C(C(=O)NC2=CC(O)=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1',
 54: 'CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=C(O)C=N3)=C2)C(Cl)=C1',
 55: 'CS(=O)(=O)C1=CC=C(C(=O)NC2=CC=C(Cl)C(C3=CC=CC=N3)=C2)C(Cl)=C1',
 56: 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)NC4=CC=CC(C(=O)O)=C4)C3)[C@H](C)[C@H]12',
 57: 'C[C@@H]1CC[C@H]2[C@@H](C)[C@@H](O)O[C@@H]3O[C@]4(C)CC[C@@H]1[C@]23OO4',
 58: 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)O',
 59: 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)C1=CC=CO1)C(=O)SCF',
 60: 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C',
 61: 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C',
 62: 'C[C@H](N)CC1=CC=C(O)C=C1',
 63: 'C[C@H](N)CC1=CC=CC=C1',
 64: 'C[C@H]1O[C@@H](N2C=C(F)C(N)=NC2=O)[C@H](O)[C@@H]1O',
 65: 'C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CC=C2C1=CC=CN=C1',
 66: 'CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1CC1)C(=O)N2C1=CC=C(O)C(N)=C1',
 67: 'CC1=C(OCC(F)(F)F)C=CN=C1CS(=O)C1=NC2=CC=C(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)C=C2N1',
 68: 'CC1=C(OCC(F)(F)F)C=CN=C1C[S@+](O)C1=NC2=C(OS(=O)(=O)O)C=CC=C2N1',
 69: 'CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=C(O)C=C2N1',
 70: 'CC1=C(OCC(F)(F)F)C=CN=C1C[S@@](=O)C1=NC2=CC=CC=C2N1',
 71: 'CC1=NC(NC2=NC=C(C(=O)NC3=C(C)C=CC=C3Cl)S2)=CC(N2CCN(CCO)CC2)=N1',
 72: 'CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2',
 73: 'CC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2O',
 74: 'ClC1=CC=C2C(=C1)N=C(N1CCNCC1)C1=CC=CC=C1N2',
 75: 'N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N(CC(=O)O)CC(=O)O)C=C3)=N2)C=C1',
 76: 'N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1',
 77: 'N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1',
 78: 'N#CCNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(NCCO)C=C3)=N2)C=C1',
 79: 'N#CC1=CC=C2C(=C1)COC2(CCC=O)C1=CC=C(F)C=C1',
 80: 'N#CC1=CC=C2C(=C1)COC2(CCCN)C1=CC=C(F)C=C1',
 81: 'N#CC1=CC=C2C(=C1)CO[C@@]2(CCC=O)C1=CC=C(F)C=C1',
 82: 'N#CC1=CC=C2C(=C1)CO[C@@]2(CCCN)C1=CC=C(F)C=C1',
 83: 'N#CC1=NC=C(N2C(=O)C3(CCC3)N(C3=CC=C(C(N)=O)C(F)=C3)C2=S)C=C1C(F)(F)F',
 84: 'NC(=O)CNC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1',
 85: 'NC(=O)NCC(F)C(=O)O',
 86: 'NC(=O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4=O)C=C3)=N2)C=C1',
 87: 'NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2',
 88: 'NC1=NC(=O)C2=C(N=CN2)N1',
 89: 'NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](CO)[C@@H](O)[C@@H]2O)C(=O)N1',
 90: 'NC1=NC2=C(N=[C]N2[C@@H]2O[C@H](COP(=O)(O)O)[C@@H](O)[C@@H]2O)C(=O)N1',
 91: 'O=C(C1CCCCC1)N1CC(=O)N2CCC3=CC=CC=C3C2C1',
 92: 'O=C(C[C@H](O)C[C@H](O)/C=C/C1=C(C2=CC=C(F)C=C2)C2=CC=CC=C2N=C1C1CC1)OC1OC(C(=O)O)C(O)C(O)C1O',
 93: 'O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O',
 94: 'O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([C@H]2CC[C@H](O)CC2)C1O',
 95: 'O=C(O)C[C@H](O)C[C@H](O)/C=C/C1=C(C2CC2)N=C2C=CC=CC2=C1C1=CC=C(F)C=C1',
 96: 'O=C(O)C1=CC(/N=N/C2=CC=C(O)C(C(=O)O)=C2)=CC=C1O',
 97: 'O=C(O)C1=CC=C(C2=CC=NC(NC3=CC=C(N4CCOCC4)C=C3)=N2)C=C1',
 98: 'O=C1CC(=O)N(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1',
 99: 'O=C1CC(O)CC(/C=C/C2=C(C3=CC=C(F)C=C3)C3=CC=CC=C3N=C2C2CC2)O1',
 100: 'O=C1CN=C(C2=CC=CC=C2)C2=CC(Cl)=CC=C2N1',
 101: 'O=C1CN=C(C2=CC=CC=C2Cl)C2=CC([N+](=O)[O-])=CC=C2N1',
 102: 'O=C1CN=C(C2=CC=CC=C2F)C2=CC(Cl)=CC=C2N1CC(F)(F)F',
 103: 'O=C1NCC(F)C(=O)N1',
 104: 'O=C1NC2=CC=C([N+](=O)[O-])C=C2C(C2=CC=CC=C2Cl)=NC1O',
 105: 'O=C1C2=CC=CC(O)=C2C(=O)C2=C(O)C3=C(C(O)=C12)C[C@@](O)(C(O)CO)CC3',
 106: 'O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1',
 107: 'O=S1(=O)CCNCN1',
 108: 'O=C1NC(=O)C2=C(N=CN2)N1',
 109: 'O=C1NC(=O)N(C2CC(O)C(CO)O2)C=C1F',
 110: 'O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)O)O2)C=C1F',
 111: 'O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)O)O2)C=C1F',
 112: 'O=C1NC(=O)N(C2CC(O)C(COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O2)C=C1F',
 113: 'O=C1NC(=O)N(C2OC(CO)C(O)C2O)C=C1F',
 114: 'O=C1NC(=O)N(C2OC(COP(=O)(O)O)C(O)C2O)C=C1F',
 115: 'O=C1NC(=O)N(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)C=C1F',
 116: 'O=C1NC=C(F)C(=O)N1',
 117: 'OC(Cl)(Cl)C(C1=CC=C(Cl)C=C1)C1=CC=CC=C1Cl',
 118: 'OC(C1=CC=CC=C1)(C1=CC=CC=C1)C12CC[N+](CCOCC3=CC=CC=C3)(CC1)CC2',
 119: 'OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(OCCOC4CC4)C=C3)=C2)[C@H](O)[C@@H](O)[C@@H]1O',
 120: 'OCC1=NC=C2N1C1=CC=C(Cl)C=C1C(C1=CC=CC=C1F)=NC2',
 121: 'OC1=CC=C(COCC[N+]23CCC(C(O)(C4=CC=CC=C4)C4=CC=CC=C4)(CC2)CC3)C=C1',
 122: 'C1=CN=C(N2CCNCC2)N=C1'}

In [11]:
dirpath = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/drugbank'
filepathlist = os.listdir(dirpath)
substrates_new = []
enzymes_new = []
dicts_new = []

for filepath in filepathlist:
    idx = int(filepath.split('_')[0])
    substrates_new.append(dict_idx2sub[idx])
    enzyme = filepath.split('_')[1].split('.')[0]
    enzymes_new.append(enzyme)
    filepathfull = dirpath + '/' + filepath
    df = pd.read_csv(filepathfull)
    atomnums = df['Atom number'].to_list()
    ranks = df['Rang'].to_list()
    dict_atomidx2rank = dict(zip(atomnums,ranks))
    dict_atomidx2rank = {k: dict_atomidx2rank[k] for k in sorted(dict_atomidx2rank)}
    dict_atomidx2rank = {k - 1: v for k, v in dict_atomidx2rank.items()}
    dicts_new.append(dict_atomidx2rank)
substrates_new = list(map(canonicalsmiles,substrates_new))


df_new = pd.DataFrame()
df_new['substrates'] = substrates_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = dicts_new
df_new

,substrates,enzyme,scores
0,C[C@H](N)Cc1ccccc1,2C9,"{0: 8, 1: 1, 2: 3, 3: 7, 4: 6, 5: 11, 6: 9, 7:..."
1,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,2D6,"{0: 11, 1: 8, 2: 17, 3: 6, 4: 7, 5: 20, 6: 19,..."
2,c1cnc(N2CCNCC2)nc1,1A2,"{0: 1, 1: 7, 2: 9, 3: 12, 4: 11, 5: 5, 6: 3, 7..."
3,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,2D6,"{0: 2, 1: 26, 2: 17, 3: 19, 4: 22, 5: 21, 6: 1..."
4,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C9,"{0: 13, 1: 23, 2: 19, 3: 18, 4: 10, 5: 11, 6: ..."
...,...,...,...
697,O=C(C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2...,UGT,"{0: 7, 1: 16, 2: 21, 3: 25, 4: 9, 5: 2, 6: 17,..."
698,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,3A4,"{0: 14, 1: 21, 2: 1, 3: 13, 4: 24, 5: 23, 6: 6..."
699,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,UGT,"{0: 9, 1: 7, 2: 27, 3: 19, 4: 15, 5: 17, 6: 28..."
700,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C19,"{0: 8, 1: 18, 2: 21, 3: 14, 4: 5, 5: 3, 6: 16,..."
701,N#Cc1ccc2c(c1)COC2(CCC=O)c1ccc(F)cc1,UGT,"{0: 5, 1: 15, 2: 22, 3: 19, 4: 14, 5: 18, 6: 2..."

In [12]:
df_new.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/somp_results_drugbank.pickle')

In [13]:
df = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/somp_results_drugbank.pickle')
df

,substrates,enzyme,scores
0,C[C@H](N)Cc1ccccc1,2C9,"{0: 8, 1: 1, 2: 3, 3: 7, 4: 6, 5: 11, 6: 9, 7:..."
1,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,2D6,"{0: 11, 1: 8, 2: 17, 3: 6, 4: 7, 5: 20, 6: 19,..."
2,c1cnc(N2CCNCC2)nc1,1A2,"{0: 1, 1: 7, 2: 9, 3: 12, 4: 11, 5: 5, 6: 3, 7..."
3,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,2D6,"{0: 2, 1: 26, 2: 17, 3: 19, 4: 22, 5: 21, 6: 1..."
4,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C9,"{0: 13, 1: 23, 2: 19, 3: 18, 4: 10, 5: 11, 6: ..."
...,...,...,...
697,O=C(C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2...,UGT,"{0: 7, 1: 16, 2: 21, 3: 25, 4: 9, 5: 2, 6: 17,..."
698,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,3A4,"{0: 14, 1: 21, 2: 1, 3: 13, 4: 24, 5: 23, 6: 6..."
699,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,UGT,"{0: 9, 1: 7, 2: 27, 3: 19, 4: 15, 5: 17, 6: 28..."
700,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C19,"{0: 8, 1: 18, 2: 21, 3: 14, 4: 5, 5: 3, 6: 16,..."
701,N#Cc1ccc2c(c1)COC2(CCC=O)c1ccc(F)cc1,UGT,"{0: 5, 1: 15, 2: 22, 3: 19, 4: 14, 5: 18, 6: 2..."

In [14]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O': {0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: 65, 7: 35, 8: 25, 9: 29, 10: 35, 11: 89, 12: 41, 13: 47, 14: 99, 15: 53, 16: 103, 17: 104, 18: 71, 19: 115, 20: 105, 21: 112, 22: 116}, 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6: 55, 7: 102, 8: 131, 9: 62, 10: 130, 11: 116, 12: 59, 13: 32, 14: 25, 15: 46, 16: 108, 17: 85, 18: 65, 19: 13, 20: 96, 21: 60, 22: 100}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, 6: 69, 7: 77, 8: 166, 9: 153, 10: 173, 11: 121, 12: 149, 13: 104, 14: 101, 15: 107, 16: 138, 17: 149, 18: 95, 19: 164, 20: 129, 21: 183, 22: 75, 23: 73, 24: 77, 25: 93, 26: 83, 27: 189, 28: 124, 29: 91, 30: 15, 31: 108, 32: 115, 33: 81, 34: 25, 35: 142, 36: 108}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6: 109, 7: 68, 8: 34, 9: 40, 10: 46, 11: 159, 12: 117, 13: 92, 14: 96, 15: 150, 16: 118, 17: 129, 18: 163, 19: 74, 20: 47, 21: 41, 22: 64, 23: 148, 24: 135, 25: 86, 26: 54, 27: 133, 28: 123}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6: 171, 7: 196, 8: 144, 9: 180, 10: 163, 11: 192, 12: 83, 13: 109, 14: 163, 15: 155, 16: 124, 17: 139, 18: 121, 19: 131, 20: 19, 21: 207, 22: 119, 23: 174, 24: 204, 25: 63, 26: 53, 27: 92, 28: 91, 29: 69, 30: 179, 31: 75, 32: 97, 33: 99, 34: 119, 35: 181, 36: 115, 37: 89, 38: 166, 39: 164}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 59, 1: 94, 2: 65, 3: 23, 4: 124, 5: 97, 6: 106, 7: 47, 8: 84, 9: 72, 10: 36, 11: 30, 12: 82, 13: 80, 14: 98, 15: 127, 16: 115, 17: 102, 18: 41, 19: 121, 20: 108, 21: 121, 22: 86, 23: 88, 24: 130, 25: 103, 26: 29}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 56, 1: 87, 2: 62, 3: 19, 4: 122, 5: 96, 6: 104, 7: 51, 8: 83, 9: 72, 10: 37, 11: 31, 12: 79, 13: 77, 14: 98, 15: 129, 16: 105, 17: 113, 18: 32, 19: 119, 20: 111, 21: 83, 22: 85, 23: 128, 24: 102, 25: 25}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 71, 1: 136, 2: 77, 3: 34, 4: 145, 5: 98, 6: 117, 7: 47, 8: 72, 9: 66, 10: 27, 11: 29, 12: 72, 13: 72, 14: 83, 15: 113, 16: 90, 17: 105, 18: 22, 19: 111, 20: 96, 21: 78, 22: 78, 23: 145, 24: 100, 25: 55, 26: 129}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O': {0: 13, 1: 72, 2: 53, 3: 54, 4: 74, 5: 54, 6: 57, 7: 88, 8: 41, 9: 93, 10: 94, 11: 64, 12: 109, 13: 95, 14: 108, 15: 116, 16: 117, 17: 53, 18: 59, 19: 56, 20: 49, 21: 37, 22: 100}, 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1': {0: 17, 1: 52, 2: 53, 3: 73, 4: 76, 5: 56, 6: 58, 7: 88, 8: 44, 9: 92, 10: 95, 11: 62, 12: 107, 13: 98, 14: 107, 15: 111, 16: 103, 17: 55, 18: 61, 19: 44, 20: 44, 21: 22}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 30, 1: 42, 2: 60, 3: 87, 4: 64, 5: 43, 6: 90, 7: 112, 8: 46, 9: 152, 10: 141, 11: 96, 12: 93, 13: 74, 14: 147, 15: 166, 16: 53, 17: 85, 18: 158, 19: 122, 20: 73, 21: 149, 22: 123, 23: 163, 24: 136, 25: 118, 26: 124, 27: 130, 28: 87, 29: 61, 30: 72, 31: 71}, 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 36, 1: 48, 2: 66, 3: 93, 4: 68, 5: 47, 6: 94, 7: 117, 8: 51, 9: 156, 10: 143, 11: 98, 12: 95, 13: 77, 14: 151, 15: 164, 16: 59, 17: 86, 18: 157, 19: 125, 20: 82, 21: 178, 22: 145, 23: 23, 24: 168, 25: 141, 26: 123, 27: 129, 28: 135, 29: 90, 30: 67, 31: 78, 32: 76}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 47, 1: 72, 2: 84, 3: 98, 4: 191, 5: 166, 6: 178, 7: 215, 8: 151, 9: 127, 10: 160, 11: 144, 12: 141, 13: 174, 14: 180, 15: 147, 16: 202, 17: 159, 18: 102, 19: 125, 20: 215, 21: 35, 22: 200, 23: 52, 24: 144, 25: 220, 26: 229, 27: 49, 28: 113, 29: 127, 30: 137, 31: 180, 32: 153, 33: 216, 34: 96, 35: 80, 36: 241, 37: 228, 38: 103, 39: 258, 40: 189, 41: 220, 42: 108, 43: 165, 44: 186, 45: 192, 46: 166, 47: 133, 48: 208, 49: 144}, 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 21, 1: 23, 2: 42, 3: 41, 4: 46, 5: 95, 6: 107, 7: 74, 8: 86, 9: 131, 10: 63, 11: 95, 12: 69, 13: 130, 14: 96, 15: 141, 16: 118, 17: 141, 18: 75, 19: 56, 20: 49, 21: 46, 22: 82, 23: 87, 24: 116, 25: 127, 26: 137, 27: 142}, 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 21, 1: 25, 2: 43, 3: 43, 4: 49, 5: 109, 6: 110, 7: 66, 8: 75, 9: 136, 10: 61, 11: 96, 12: 67, 13: 130, 14: 100, 15: 141, 16: 117, 17: 140, 18: 73, 19: 56, 20: 51, 21: 46, 22: 78, 23: 85, 24: 114, 25: 126, 26: 136, 27: 142}, 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F': {0: 37, 1: 29, 2: 66, 3: 59, 4: 43, 5: 140, 6: 49, 7: 102, 8: 128, 9: 126, 10: 117, 11: 126, 12: 113, 13: 138, 14: 87, 15: 42, 16: 143, 17: 94, 18: 48, 19: 52, 20: 70, 21: 54, 22: 122, 23: 112, 24: 60, 25: 116, 26: 110, 27: 128, 28: 99}, 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O': {0: 24, 1: 25, 2: 42, 3: 43, 4: 67, 5: 69, 6: 59, 7: 137, 8: 109, 9: 106, 10: 137, 11: 65, 12: 94, 13: 71, 14: 131, 15: 101, 16: 145, 17: 118, 18: 146, 19: 77, 20: 55, 21: 48, 22: 45, 23: 79, 24: 86, 25: 116, 26: 127, 27: 140, 28: 148}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 44, 1: 59, 2: 44, 3: 133, 4: 100, 5: 128, 6: 41, 7: 114, 8: 148, 9: 115, 10: 126, 11: 185, 12: 163, 13: 117, 14: 184, 15: 62, 16: 113, 17: 119, 18: 115, 19: 79, 20: 96, 21: 72, 22: 32, 23: 63, 24: 102, 25: 85, 26: 114, 27: 94, 28: 178, 29: 170, 30: 38, 31: 64, 32: 135, 33: 138}, 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN': {0: 52, 1: 13, 2: 81, 3: 19, 4: 58, 5: 77, 6: 84, 7: 110, 8: 93, 9: 63, 10: 39, 11: 23, 12: 45, 13: 69, 14: 66, 15: 90, 16: 36, 17: 54, 18: 68}, 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 72, 1: 30, 2: 100, 3: 94, 4: 39, 5: 56, 6: 81, 7: 39, 8: 71, 9: 41, 10: 121, 11: 28, 12: 64, 13: 64, 14: 70, 15: 96, 16: 108, 17: 68, 18: 119, 19: 109, 20: 103, 21: 92, 22: 98, 23: 37}, 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1': {0: 53, 1: 25, 2: 152, 3: 73, 4: 43, 5: 65, 6: 46, 7: 63, 8: 36, 9: 178, 10: 162, 11: 157, 12: 22, 13: 86, 14: 154, 15: 30, 16: 161, 17: 185, 18: 98, 19: 122, 20: 138, 21: 127, 22: 49, 23: 134, 24: 81, 25: 93, 26: 135, 27: 109, 28: 122, 29: 149, 30: 99, 31: 87, 32: 132}, 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 51, 1: 21, 2: 141, 3: 122, 4: 79, 5: 48, 6: 103, 7: 126, 8: 59, 9: 131, 10: 148, 11: 45, 12: 50, 13: 119, 14: 46, 15: 46, 16: 103, 17: 107, 18: 157, 19: 87, 20: 64, 21: 120, 22: 132, 23: 23, 24: 147, 25: 97, 26: 115, 27: 93, 28: 99, 29: 111}, 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C': {0: 38, 1: 49, 2: 59, 3: 54, 4: 94, 5: 68, 6: 91, 7: 88, 8: 40, 9: 97, 10: 94, 11: 74, 12: 54, 13: 60, 14: 60, 15: 39, 16: 53, 17: 11, 18: 17}, 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C': {0: 36, 1: 47, 2: 57, 3: 55, 4: 98, 5: 80, 6: 68, 7: 43, 8: 94, 9: 90, 10: 70, 11: 54, 12: 61, 13: 57, 14: 36, 15: 54, 16: 10, 17: 16}, 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C': {0: 33, 1: 27, 2: 74, 3: 31, 4: 85, 5: 67, 6: 88, 7: 43, 8: 75, 9: 37, 10: 42, 11: 77, 12: 76, 13: 38, 14: 57, 15: 54, 16: 14}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 11, 1: 26, 2: 17, 3: 26, 4: 73, 5: 88, 6: 129, 7: 105, 8: 44, 9: 43, 10: 80, 11: 84, 12: 49, 13: 50, 14: 117, 15: 75, 16: 127, 17: 105, 18: 123, 19: 80, 20: 81, 21: 68, 22: 66, 23: 133}, 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 11, 1: 26, 2: 17, 3: 26, 4: 73, 5: 88, 6: 129, 7: 105, 8: 44, 9: 43, 10: 80, 11: 84, 12: 49, 13: 50, 14: 117, 15: 75, 16: 127, 17: 105, 18: 123, 19: 80, 20: 81, 21: 68, 22: 66, 23: 133}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 16, 1: 24, 2: 22, 3: 34, 4: 73, 5: 108, 6: 93, 7: 103, 8: 122, 9: 51, 10: 78, 11: 85, 12: 74, 13: 39, 14: 46, 15: 52, 16: 55, 17: 64, 18: 64, 19: 66, 20: 117}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 15, 1: 24, 2: 21, 3: 32, 4: 74, 5: 105, 6: 90, 7: 96, 8: 110, 9: 56, 10: 53, 11: 75, 12: 34, 13: 46, 14: 53, 15: 55, 16: 65, 17: 64, 18: 75, 19: 117}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 15, 1: 71, 2: 94, 3: 69, 4: 25, 5: 89, 6: 64, 7: 103, 8: 78, 9: 61, 10: 33, 11: 54, 12: 104, 13: 39, 14: 67, 15: 118, 16: 63, 17: 72, 18: 97, 19: 38, 20: 49, 21: 115}, 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1': {0: 18, 1: 58, 2: 42, 3: 65, 4: 77, 5: 42, 6: 122, 7: 46, 8: 110, 9: 101, 10: 114, 11: 69, 12: 107, 13: 139, 14: 119, 15: 123, 16: 113, 17: 75, 18: 68, 19: 88, 20: 48, 21: 171, 22: 135, 23: 167, 24: 104, 25: 35, 26: 35, 27: 93, 28: 165, 29: 141}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 18, 1: 116, 2: 128, 3: 96, 4: 180, 5: 129, 6: 159, 7: 143, 8: 84, 9: 65, 10: 52, 11: 105, 12: 96, 13: 61, 14: 89, 15: 89, 16: 138, 17: 42, 18: 49, 19: 158, 20: 123, 21: 158, 22: 143, 23: 71, 24: 77, 25: 83, 26: 82, 27: 58, 28: 71, 29: 73, 30: 136, 31: 96}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 12, 1: 68, 2: 33, 3: 73, 4: 66, 5: 120, 6: 100, 7: 32, 8: 33, 9: 73, 10: 76, 11: 39, 12: 38, 13: 112, 14: 63, 15: 121, 16: 98, 17: 117, 18: 67, 19: 73, 20: 58, 21: 56, 22: 128}, 'CNCCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 12, 1: 68, 2: 33, 3: 73, 4: 66, 5: 120, 6: 100, 7: 32, 8: 33, 9: 73, 10: 76, 11: 39, 12: 38, 13: 112, 14: 63, 15: 121, 16: 98, 17: 117, 18: 67, 19: 73, 20: 58, 21: 56, 22: 128}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 25, 1: 159, 2: 195, 3: 154, 4: 178, 5: 35, 6: 95, 7: 32, 8: 49, 9: 63, 10: 58, 11: 115, 12: 64, 13: 69, 14: 89, 15: 123, 16: 177, 17: 194, 18: 112, 19: 160, 20: 129, 21: 54, 22: 104, 23: 109, 24: 126, 25: 85, 26: 144, 27: 72, 28: 91, 29: 132, 30: 158, 31: 63, 32: 82, 33: 115, 34: 170}, 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1': {0: 19, 1: 149, 2: 153, 3: 78, 4: 144, 5: 26, 6: 150, 7: 128, 8: 112, 9: 87, 10: 174, 11: 166, 12: 31, 13: 58, 14: 38, 15: 51, 16: 53, 17: 37, 18: 140, 19: 116, 20: 113, 21: 43, 22: 123, 23: 69, 24: 83, 25: 127, 26: 98, 27: 112, 28: 134, 29: 89, 30: 75}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 38, 1: 162, 2: 121, 3: 104, 4: 147, 5: 137, 6: 150, 7: 193, 8: 76, 9: 101, 10: 136, 11: 95, 12: 181, 13: 146, 14: 165, 15: 182, 16: 37, 17: 80, 18: 31, 19: 39, 20: 88, 21: 82, 22: 27, 23: 17, 24: 88, 25: 96, 26: 169, 27: 177, 28: 29, 29: 90, 30: 185, 31: 167, 32: 114, 33: 63, 34: 166, 35: 117}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 22, 1: 161, 2: 152, 3: 74, 4: 158, 5: 167, 6: 28, 7: 111, 8: 87, 9: 91, 10: 60, 11: 59, 12: 145, 13: 45, 14: 121, 15: 127, 16: 74, 17: 61, 18: 123, 19: 182, 20: 120, 21: 137, 22: 147, 23: 55, 24: 62, 25: 67, 26: 29, 27: 96, 28: 76, 29: 116, 30: 185, 31: 111, 32: 117}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1[C@@H](NC(C)=O)CC2': {0: 17, 1: 142, 2: 128, 3: 84, 4: 126, 5: 152, 6: 130, 7: 128, 8: 27, 9: 95, 10: 134, 11: 26, 12: 124, 13: 75, 14: 58, 15: 98, 16: 147, 17: 23, 18: 113, 19: 90, 20: 80, 21: 157, 22: 102, 23: 44, 24: 123, 25: 50, 26: 70, 27: 118, 28: 81, 29: 48}, 'COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN1CC2': {0: 16, 1: 120, 2: 116, 3: 96, 4: 136, 5: 152, 6: 101, 7: 126, 8: 126, 9: 22, 10: 115, 11: 49, 12: 110, 13: 81, 14: 55, 15: 116, 16: 73, 17: 61, 18: 56, 19: 30, 20: 51, 21: 57, 22: 66, 23: 58, 24: 58, 25: 59}, 'COc1ccc(C[C@@H](C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 18, 1: 121, 2: 109, 3: 58, 4: 81, 5: 143, 6: 99, 7: 38, 8: 43, 9: 97, 10: 106, 11: 45, 12: 38, 13: 134, 14: 104, 15: 65, 16: 42, 17: 45, 18: 47, 19: 103, 20: 119, 21: 102, 22: 136, 23: 85, 24: 106, 25: 89, 26: 95}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 25, 1: 81, 2: 60, 3: 54, 4: 60, 5: 108, 6: 94, 7: 130, 8: 10, 9: 60, 10: 108, 11: 123, 12: 59, 13: 73, 14: 81, 15: 26, 16: 90, 17: 98, 18: 27, 19: 99, 20: 33, 21: 117, 22: 119, 23: 65}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)CC3': {0: 14, 1: 147, 2: 137, 3: 46, 4: 46, 5: 55, 6: 162, 7: 160, 8: 91, 9: 83, 10: 82, 11: 96, 12: 111, 13: 86, 14: 72, 15: 82, 16: 117, 17: 100, 18: 121, 19: 106, 20: 60, 21: 119, 22: 113, 23: 101, 24: 70, 25: 22, 26: 122, 27: 53, 28: 36}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 23, 1: 226, 2: 206, 3: 67, 4: 78, 5: 93, 6: 243, 7: 240, 8: 164, 9: 139, 10: 178, 11: 136, 12: 165, 13: 128, 14: 104, 15: 156, 16: 176, 17: 158, 18: 198, 19: 180, 20: 86, 21: 151, 22: 165, 23: 152, 24: 135, 25: 35, 26: 193, 27: 106, 28: 86, 29: 50, 30: 197, 31: 142, 32: 56, 33: 164, 34: 143, 35: 62, 36: 106, 37: 111, 38: 68, 39: 192, 40: 144, 41: 74, 42: 56, 43: 208}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3': {0: 14, 1: 147, 2: 137, 3: 53, 4: 51, 5: 58, 6: 160, 7: 160, 8: 91, 9: 80, 10: 87, 11: 92, 12: 107, 13: 87, 14: 74, 15: 82, 16: 113, 17: 99, 18: 119, 19: 107, 20: 61, 21: 128, 22: 108, 23: 47, 24: 116, 25: 26, 26: 113, 27: 54, 28: 39}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1': {0: 24, 1: 233, 2: 209, 3: 75, 4: 85, 5: 99, 6: 247, 7: 244, 8: 170, 9: 141, 10: 181, 11: 143, 12: 167, 13: 138, 14: 111, 15: 162, 16: 179, 17: 163, 18: 202, 19: 186, 20: 84, 21: 173, 22: 168, 23: 59, 24: 57, 25: 184, 26: 40, 27: 191, 28: 104, 29: 95, 30: 63, 31: 205, 32: 147, 33: 69, 34: 170, 35: 146, 36: 75, 37: 112, 38: 115, 39: 81, 40: 199, 41: 149, 42: 87, 43: 64, 44: 214}, 'COc1nc(N)nc2[nH]cnc12': {0: 15, 1: 43, 2: 49, 3: 36, 4: 48, 5: 25, 6: 52, 7: 50, 8: 57, 9: 25, 10: 27, 11: 41}, 'COc1nc(N)nc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1O': {0: 22, 1: 112, 2: 123, 3: 105, 4: 114, 5: 71, 6: 121, 7: 110, 8: 128, 9: 77, 10: 58, 11: 106, 12: 60, 13: 31, 14: 94, 15: 84, 16: 37, 17: 27, 18: 79, 19: 56, 20: 43, 21: 86, 22: 65, 23: 49, 24: 92}, 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12': {0: 23, 1: 160, 2: 159, 3: 152, 4: 218, 5: 150, 6: 163, 7: 165, 8: 160, 9: 169, 10: 218, 11: 97, 12: 187, 13: 129, 14: 69, 15: 162, 16: 119, 17: 65, 18: 50, 19: 71, 20: 125, 21: 126, 22: 154, 23: 120, 24: 33, 25: 55, 26: 12, 27: 18, 28: 192, 29: 97, 30: 47, 31: 83, 32: 170, 33: 94, 34: 49, 35: 75, 36: 111, 37: 199}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 17, 1: 99, 2: 120, 3: 42, 4: 74, 5: 102, 6: 52, 7: 39, 8: 45, 9: 100, 10: 45, 11: 58, 12: 62, 13: 104, 14: 65, 15: 116, 16: 34, 17: 54, 18: 116, 19: 84, 20: 70, 21: 76, 22: 82}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 105, 1: 23, 2: 82, 3: 88, 4: 158, 5: 49, 6: 66, 7: 113, 8: 77, 9: 78, 10: 112, 11: 152, 12: 26, 13: 97, 14: 110, 15: 113, 16: 70, 17: 151, 18: 155, 19: 68, 20: 41, 21: 35, 22: 105, 23: 71, 24: 47, 25: 121, 26: 67, 27: 56}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 102, 1: 21, 2: 79, 3: 85, 4: 154, 5: 49, 6: 66, 7: 115, 8: 76, 9: 78, 10: 86, 11: 154, 12: 31, 13: 52, 14: 124, 15: 97, 16: 155, 17: 162, 18: 68, 19: 31, 20: 72, 21: 121, 22: 73, 23: 83, 24: 53, 25: 123, 26: 69, 27: 57}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 101, 1: 18, 2: 78, 3: 84, 4: 146, 5: 51, 6: 67, 7: 109, 8: 75, 9: 78, 10: 85, 11: 148, 12: 30, 13: 53, 14: 122, 15: 97, 16: 152, 17: 158, 18: 71, 19: 41, 20: 33, 21: 100, 22: 72, 23: 55, 24: 120, 25: 66, 26: 58}, 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12': {0: 78, 1: 40, 2: 44, 3: 176, 4: 174, 5: 50, 6: 121, 7: 128, 8: 130, 9: 162, 10: 150, 11: 161, 12: 176, 13: 143, 14: 24, 15: 124, 16: 56, 17: 73, 18: 142, 19: 151, 20: 62, 21: 175, 22: 159, 23: 138, 24: 219, 25: 51, 26: 84, 27: 113, 28: 228, 29: 163, 30: 171, 31: 189, 32: 127, 33: 116, 34: 125, 35: 68, 36: 42, 37: 73, 38: 74}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)O': {0: 39, 1: 110, 2: 37, 3: 96, 4: 175, 5: 43, 6: 183, 7: 49, 8: 127, 9: 100, 10: 55, 11: 132, 12: 215, 13: 98, 14: 195, 15: 173, 16: 85, 17: 123, 18: 193, 19: 54, 20: 217, 21: 125, 22: 96, 23: 61, 24: 184, 25: 119, 26: 204, 27: 89, 28: 209, 29: 142, 30: 113, 31: 113, 32: 143, 33: 72, 34: 107, 35: 36, 36: 172, 37: 143, 38: 131, 39: 162}, 'C[C@@H]1C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)SCF': {0: 47, 1: 120, 2: 40, 3: 115, 4: 196, 5: 46, 6: 199, 7: 52, 8: 139, 9: 110, 10: 58, 11: 145, 12: 232, 13: 113, 14: 211, 15: 184, 16: 101, 17: 148, 18: 213, 19: 65, 20: 233, 21: 139, 22: 117, 23: 64, 24: 197, 25: 141, 26: 217, 27: 101, 28: 180, 29: 162, 30: 141, 31: 139, 32: 174, 33: 81, 34: 127, 35: 43, 36: 190, 37: 130, 38: 95, 39: 17, 40: 95, 41: 101}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 71, 1: 61, 2: 37, 3: 138, 4: 128, 5: 154, 6: 170, 7: 176, 8: 158, 9: 43, 10: 58, 11: 72, 12: 165, 13: 49, 14: 154, 15: 55, 16: 139, 17: 128, 18: 98, 19: 139, 20: 61, 21: 123, 22: 49, 23: 67, 24: 169, 25: 60, 26: 101, 27: 169, 28: 101, 29: 174, 30: 73, 31: 57, 32: 78, 33: 192, 34: 113}, 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C': {0: 74, 1: 64, 2: 38, 3: 145, 4: 128, 5: 155, 6: 172, 7: 183, 8: 157, 9: 44, 10: 61, 11: 81, 12: 174, 13: 50, 14: 161, 15: 56, 16: 89, 17: 62, 18: 165, 19: 112, 20: 146, 21: 68, 22: 135, 23: 63, 24: 74, 25: 172, 26: 64, 27: 101, 28: 167, 29: 109, 30: 183, 31: 80, 32: 71, 33: 82, 34: 190, 35: 120}, 'C[C@H](N)Cc1ccc(O)cc1': {0: 45, 1: 24, 2: 20, 3: 53, 4: 37, 5: 62, 6: 43, 7: 14, 8: 44, 9: 57, 10: 20, 11: 49}, 'C[C@H](N)Cc1ccccc1': {0: 49, 1: 25, 2: 20, 3: 51, 4: 40, 5: 60, 6: 43, 7: 21, 8: 11, 9: 27, 10: 49}, 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O': {0: 28, 1: 61, 2: 17, 3: 103, 4: 57, 5: 23, 6: 102, 7: 75, 8: 102, 9: 71, 10: 97, 11: 41, 12: 87, 13: 92, 14: 82, 15: 74, 16: 29, 17: 82, 18: 43, 19: 35, 20: 85}, 'C[C@H]1[C@@H](O)O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]1[C@]24OO3': {0: 33, 1: 112, 2: 46, 3: 56, 4: 43, 5: 111, 6: 52, 7: 117, 8: 58, 9: 33, 10: 84, 11: 64, 12: 125, 13: 120, 14: 115, 15: 70, 16: 127, 17: 69, 18: 43, 19: 41, 20: 37, 21: 134, 22: 76, 23: 128, 24: 110, 25: 102}, 'C[C@]12CC[C@H](O)CC1=CC[C@@H]1[C@@H]2CC[C@]2(C)C(c3cccnc3)=CC[C@@H]12': {0: 86, 1: 155, 2: 58, 3: 51, 4: 171, 5: 40, 6: 146, 7: 46, 8: 68, 9: 63, 10: 150, 11: 42, 12: 76, 13: 52, 14: 139, 15: 41, 16: 91, 17: 164, 18: 92, 19: 157, 20: 58, 21: 52, 22: 58, 23: 148, 24: 132, 25: 108, 26: 49, 27: 120, 28: 46, 29: 131}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 26, 1: 70, 2: 131, 3: 81, 4: 159, 5: 129, 6: 177, 7: 64, 8: 65, 9: 69, 10: 83, 11: 73, 12: 178, 13: 114, 14: 82, 15: 17, 16: 96, 17: 102, 18: 129, 19: 141, 20: 146, 21: 91, 22: 91, 23: 97, 24: 163, 25: 114, 26: 148, 27: 132, 28: 100, 29: 62, 30: 134, 31: 172, 32: 177, 33: 67, 34: 100}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1': {0: 55, 1: 218, 2: 195, 3: 205, 4: 40, 5: 145, 6: 127, 7: 133, 8: 139, 9: 101, 10: 152, 11: 141, 12: 236, 13: 211, 14: 21, 15: 160, 16: 234, 17: 186, 18: 210, 19: 124, 20: 78, 21: 112, 22: 159, 23: 119, 24: 34, 25: 149, 26: 140, 27: 40, 28: 109, 29: 112, 30: 140, 31: 83, 32: 46, 33: 137, 34: 82, 35: 52, 36: 141, 37: 114, 38: 58, 39: 143, 40: 148, 41: 233, 42: 214}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1': {0: 28, 1: 122, 2: 102, 3: 119, 4: 30, 5: 69, 6: 54, 7: 60, 8: 66, 9: 58, 10: 77, 11: 69, 12: 139, 13: 116, 14: 11, 15: 75, 16: 138, 17: 97, 18: 114, 19: 65, 20: 41, 21: 63, 22: 85, 23: 50, 24: 132, 25: 126}, 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1': {0: 31, 1: 122, 2: 103, 3: 119, 4: 30, 5: 69, 6: 56, 7: 62, 8: 68, 9: 64, 10: 76, 11: 68, 12: 134, 13: 111, 14: 10, 15: 74, 16: 132, 17: 95, 18: 108, 19: 53, 20: 38, 21: 34, 22: 60, 23: 12

In [15]:
len(list(result_new.keys()))

117

In [16]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
somp_results = [result_new.get(i,'None') for i in substrates]
df_total['somp_results'] = somp_results
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,somp_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ...","{0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: ..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20...","{0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6:..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17...","{0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, ..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19...","{0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6:..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40...","{0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6:..."
...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23...",None
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12...","{0: 149, 1: 31, 2: 140, 3: 62, 4: 160, 5: 157,..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7...","{0: 61, 1: 13, 2: 82, 3: 46, 4: 64, 5: 99, 6: ..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ...",None
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7...","{0: 13, 1: 48, 2: 43, 3: 58, 4: 52, 5: 25, 6: ..."

In [17]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')