In [10]:
from rdkit import Chem
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [11]:
import pandas as pd
df = pd.read_pickle('pred_results_substrate_truemains.pickle')
true_mains = df['true_mains'].to_list()
substrate_old = df['substrate'].to_list()
substrate_old = list(map(canonicalsmiles,substrate_old))
dict_sub2true = dict(zip(substrate_old,true_mains))
dict_sub2true

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': ['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2'],
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': ['CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O'],
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': ['CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21'],
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': ['Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12'],
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': ['Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12'],
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': ['Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2(F)F)n1'],
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': ['C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC'],
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': ['Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1'],
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': ['O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]c2ccccc12'],
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': ['NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1'],
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': ['Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1'],
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': ['COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]5O)CCOCC4)cc3)ccnc2n1'],
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': ['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O'],
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': ['O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1'],
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': ['OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O'],
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': ['O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12'],
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': ['O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1ccc(CNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)cc1'],
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': ['CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1'],
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': ['CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(=O)O'],
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': ['CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1'],
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': ['C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)O[C@@]1(C)C(F)(F)F'],
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': ['CCN(CC)CCc1c[nH]c2cccc(O)c12'],
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': ['NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc(C(F)(F)F)cc2)c1'],
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': ['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1)C(=O)O'],
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': ['O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cccc3C2=O)C(=O)N1'],
 'CNC(C)Cc1ccc2c(c1)OCO2': ['CC(N)Cc1ccc2c(c1)OCO2'],
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': ['Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21'],
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': ['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O'],
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': ['O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)[C@@H](O)[C@@H]1O'],
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': ['O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)C(O)[C@@H]1O']}

In [12]:
df_metareact_8079 = pd.read_csv('MetaReact_seed8079.csv')
predict = df_metareact_8079['predict'].to_list()
substrate = df_metareact_8079['substrate'].to_list()
substrate = list(map(canonicalsmiles,substrate))
predict = [i.split('|') for i in predict]
dict_sub2predict = dict(zip(substrate,predict))
dict_sub2predict

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': ['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O',
  'CC(C)(CO)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2',
  'CC(C)(C)[C@H](N)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CC(O)NC1=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC(S)(SCC=O)C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(N)=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCC(O)S2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@H]1CC(O)NC1=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@]2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@H]1CCNC1=O)SCCS2=O',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@@]2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1C(=O)NCC1O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)CCC(=O)NCC=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2',
  'CC(C)(CO)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)NC(C#N)C[C@@H]1CCNC1=O)SCCS2',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2',
  'CC(C)(C)C(NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O',
  'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(N)=O)SCCS2'],
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': ['CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(O)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CN([C@@H](CCO)C(=O)NC2=CC=C(C(N)=O)C(F)=C2)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(O)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CN([C@H](C(=O)NC2=CC=C(C(N)=O)C(F)=C2)C(C)O)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@H](C(=O)NC1=CC(O)=C(C(N)=O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CNC(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@H](C(N)=O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC(F)=C(C(N)=O)C=C1O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CN([C@H](C(=O)NC2=CC=C(C(N)=O)C(F)=C2)[C@@H](C)O)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CN([C@H](C(=O)NC2=CC=C(C(N)=O)C(F)=C2)[C@H](C)O)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C(O)=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC(F)=C(C(N)=O)C2OC12)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'COC1=CN(CC(=O)NC2=CC=C(C(N)=O)C(F)=C2)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1',
  'CC[C@@](O)(C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)[N+]([O-])=N2)=CC1=O',
  'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2N=NC(C(F)(F)F)=C2O)=CC1=O'],
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': ['CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)(O)CC21',
  'CC(O)CCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCCCCC1=CC(OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CC(O)C(C)CC21',
  'CC1CCC2C(C1)C1=C(O)C=C(CCCCCO)C=C1OC2(C)C',
  'CCCC(O)CC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCC(O)CCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCCCC(O)C1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)[C@@H]1CCC(C)(O)C[C@@H]21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)C(O)C21',
  'CCCCCC1=CC2=C(C(OS(=O)(=O)O)=C1)C1CC(C)CCC1C(C)(C)O2',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)[C@@H]1C[C@@H](O)[C@H](C)C[C@@H]21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1C(O)CC(C)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)[C@@H]1CCC(C)(O)C[C@H]21',
  'CCCCCC1=CC(OC2OC(C(=O)O)C(O)C(O)C2O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(CO)C1CCC(C)CC21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)[C@@H]1CC[C@@](C)(O)C[C@@H]21',
  'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)[C@H]1CCC(C)(O)C[C@@H]21',
  'CCCCCC1=CC(OC2OC(C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21'],
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': ['CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'C[C@@H](N)C1=CC=CC2=CC=CC=C12',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=C(O)C3=CC=CC=C23)=C1',
  'CC(=O)NC1=CC=C(C)C(/C(=N/[C@H](C)C2=CC=CC3=CC=CC=C23)OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C1',
  'CC(=O)NC1=CC=C(C)C(C(N)=O)=C1',
  'CC1=CC=C(N)C=C1C(=O)NC(C)C1=CC=CC2=CC=CC=C12',
  'CC(=O)NC1=CC=C(CO)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=C2C=CC2OC32)=C1',
  'CC(=O)NC1=CC=C(C)C(/C(=N\\[C@H](C)C2=CC=CC3=CC=CC=C23)OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C1',
  'CC(=O)NC1=CC(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C(C)C=C1O',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC3OC3C3=CC=CC=C23)=C1',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@@H](CO)C2=CC=CC3=CC=CC=C23)=C1',
  'CC(N)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(NC(=O)CO)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@@H](C)C1=CC=CC2=CC=CC=C12',
  'CC(=O)NC1=CC(O)=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=C2C2OC2C=C3)=C1',
  'CC(=O)N(O)C1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1',
  'CC(=O)NC1=CC(C(=O)NC(C)C2=CC=CC3=CC=CC=C23)=C(C)C=C1O',
  'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](CO)C2=CC=CC3=CC=CC=C23)=C1'],
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': ['CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1',
  'CC1=CC(O)=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(O)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=C(O)C2=CC=CC=C12',
  'CC(=O)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(NO)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=C1C1OC1C=C2',
  'C[C@@H](NC(=O)C1=CC(N)=CC=C1CO)C1=CC=CC2=CC=CC=C12',
  'C[C@@H](N)C1=CC=CC2=CC=CC=C12',
  'CC1=C(O)C=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=C(O)C=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@@H](CO)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC(O)=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC2OC2C2=CC=CC=C12',
  'CC1=CC=C(N)C(O)=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'C=C1C=CC(=N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=C(O)C=CC2=CC=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=C(O)C=CC=C12',
  'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=C1C=CC1OC21',
  'CC1=CC=C(N)C=C1C(=O)NCC1=CC=CC2=CC=CC=C12'],
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': ['O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=NC(NC3=CNN=C3)=N1)C2',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=[N+]1C1O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]1O',
  'CN1C=C(NC2=NC=C(O)C(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4)=N2)C=N1',
  'NC1=NC=CC(N2C[C@@H]3CC[C@H](C2)N3C(=O)[C@@H]2CC2(F)F)=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3C(O)C3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(NC[C@@H]3CC[C@H](C=O)N3C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(NC[C@H]3CC[C@@H](C=O)N3C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)CC(F)(F)CO)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC(O)[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)[N+]4([O-])C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC(O)=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)CC(F)(F)C=O)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C(O)=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3[C@@H](O)C3(F)F)=N2)C=N1',
  'O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=NC(O)=N1)C2',
  'CN1C=C(NC2=NC=CC(N3C[C@H]4C(O)C[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@H]4CC[C@@H](C3O)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1',
  'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3O)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1'],
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': ['C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCN(C)C',
  'C=CC(=O)NC1=CC(O)=C(OC)C=C1N(C)CCN(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCNC',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)O)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCN(C)C',
  'COC1=CC(N(C)CCN(C)C)=C(N)C=C1NC1=NC=C(C(=O)OC(C)C)C(C2=CN(C)C3=CC=CC=C23)=N1',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1NC',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1NCCN(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CC[N+](C)(C)[O-]',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)CO)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCN(C)C',
  'CC(C)OC(=O)C1=CN=C(N)N=C1C1=CN(C)C2=CC=CC=C12',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(O)C=C1N(C)CCN(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CC=O',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1O',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCO',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)C(O)CN(C)C',
  'C=CC(=O)NC1=CC(N)=C(OC)C=C1N(C)CCN(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(CO)CCN(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CC(O)N(C)C',
  'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN=C4C=CC=CC34)=N2)=C(OC)C=C1N(C)CCN(C)C',
  'COC1=CC(N(C)CCN(C)C)=C(NC=O)C=C1NC1=NC=C(C(=O)OC(C)C)C(C2=CN(C)C3=CC=CC=C23)=N1'],
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': ['OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1C(O)C1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=C(O)C=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=CC=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC(O)=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2OC(C=O)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1=O',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=C(O)C=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C(O)=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](C=O)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'OCC1=CC=C(C2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC(O)=C(C2=CC=C(F)C=C2)S1',
  'CC1=CC=C([C@@H]2OC(C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=C(CC2=CC=C(C3=CC=C(F)C=C3)S2)C=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C2OC12',
  'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3OC(C(=O)O)C(O)C(O)C3O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)C2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'OCC1=CC=C(C2OC(CO)C(O)C(O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1',
  'CC1=C(O)C=C(C2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1'],
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': ['NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1',
  'O=C(NC1=CC=C(O)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=[N+]([O-])C3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC(O)=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC(=O)NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C(O)=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C=C(O)S1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1O)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=C(O)C=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C(O)=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1=O',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=C3C=CC=CC3=NC3OC23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C2OC2S1',
  'O=C(O)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=C(O)C=NC3=CC=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=C2C=CC2OC32)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC(O)=CC=C23)C=CS1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NC(O)C2=CC=NC3=CC=CC=C23)C=CS1',
  'O=C1CC(NCC2=CC=NC3=CC=CC=C23)=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)S1',
  'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=NC3=CC=CC(O)=C23)C=CS1'],
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': ['NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2CC(=O)N3)CC1',
  'NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CC=O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCOC2OC(C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C2OC2N3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=C(O)N3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2O)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCOS(=O)(=O)O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'CC(=O)NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC(O)=NC3=C2C=CN3)CC1',
  'NC(=O)C1(N)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCOP(=O)(O)O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C(O)=CN3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)C(O)C1',
  'NC1(C(=O)N[C@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2CC(=O)N3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3C2OC(C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3C2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)CC1',
  'NC1(C(=O)N[C@@H](C2=CC=C(Cl)C=C2)C(O)CO)CCN(C2=NC=NC3=C2C=CN3)CC1',
  'NC1(C(=O)NC(CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2CC(=O)N3)CC1',
  'NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1O'],
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': ['CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=C3)=CC2=C1',
  'CCOC1=CC=C(NC(=S)NCC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(CO)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=O)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CC=O)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(/N=C(/SO)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1O',
  'CCOC1=CC=C(NC(=S)NCCO)C=C1',
  'CC1=CC(C)=C2NC(=O)C(CNCCO)=CC2=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=CC(CO)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C(O)=C1',
  'CCOC1=CC=C(NC(=S)N(CCOS(=O)(=O)O)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(/N=C(\\SO)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(S)=NCC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=CC(C)=C3N=C2OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C=C1',
  'CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=O)S)=CC2=C1',
  'CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(OCCO)C=C3)=CC2=C1',
  'CCOC1=CC=C(N=C(SO)N(CCO)CC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1',
  'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=C(O)C(C)=C3NC2=O)C=C1'],
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': ['COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=CC=NC2=N1',
  'O=C(NO)C1(C2=CC=C(OC3=CC=NC4=NC(O)=CC=C34)C=C2)CCOCC1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)O)CCOCC4)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)N=O)CCOCC4)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C(CC=O)(CCO)C(=O)NO)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4O)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)=CC=[N+]([O-])C2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NOC5OC(C(=O)O)C(O)C(O)C5O)CCOCC4)C=C3)=CC=NC2=N1',
  'COC1=NC2=NC=CC(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)=C2C=C1O',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)=CC(O)=NC2=N1',
  'CO',
  'COC1=CC=C2C(OC3=CC=C(C(CCOCC=O)C(=O)NO)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)=CC=NC2=[N+]1[O-]',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOC(O)C4)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3O)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4O)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NOC(C)=O)CCOCC4)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)=C(O)C=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(CNO)CCOCC4)C=C3)=CC=NC2=N1',
  'COC1=CC=C2C(OC3=CC=C(C4(C(=O)NO)C=COCC4)C=C3)=CC=NC2=N1'],
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': ['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)O)C(=O)NCC(=O)O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(/C=C/CCC=O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(CCCCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'OCC1OC(OCC2OC(O)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C\\C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)O)C(=O)NCC(=O)O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'OC[C@H]1O[C@H](OC[C@H]2O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]2O)[C@H](O)[C@@H](O)[C@@H]1O',
  'C/C=C/C#CC#CC(O)C(/C=C/CCC=O)OC1OC(COC2O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(CSC[C@H](NC(C)=O)C(=O)NCC(=O)O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(=CSC[C@H](NC(=O)CCC(N)C(=O)O)C(=O)NCC(=O)O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(O)/C=C/CCCO',
  'CCCC#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(CCCCCO)OC1OC(COC2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C(O)C(O)C1O',
  'OC[C@H]1O[C@@H](OC[C@H]2O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]2O)[C@@H](O)[C@@H](O)[C@@H]1O',
  'C/C=C/C#CC#CC(O)C(/C=C/CCC=O)OC1OC(COC2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(OC1O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]1O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'OC[C@H]1O[C@H](OC[C@H]2O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]2O)[C@@H](O)[C@@H](O)[C@@H]1O',
  'C/C=C/C#CC#C[C@H](O)C(/C=C/CCC=O)O[C@H]1O[C@H](CO[C@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]2O)[C@@H](O)[C@H](O)[C@@H]1O',
  'C/C=C/C#CC#CC(O)COC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O',
  'C/C=C/C#CC#CC(O)C(CSC[C@H](NC(C)=O)C(=O)O)O[C@H]1O[C@@H](CO[C@H]2O[C@H](CO)[C@@H](O)[C@@H](O)[C@H]2O)[C@H](O)[C@H](O)[C@H]1O'],
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': ['O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2Cl)CC1',

In [13]:
df['predict_8079'] = [dict_sub2predict[i] for i in substrate_old]
df

,name,substrate,predict,top_n,true_mains,predict_8079
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,[CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(O...
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],"[CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21, ..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],[CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=...
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],[CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC...
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC...,[O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=...
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,[C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4...
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,[OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[...
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,"[NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1, O=C..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,[NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=N...
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],[CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=...
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,[COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=C...
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],[O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2...
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,[OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[...
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],[O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12...
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,[O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)...
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,[C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F...
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,[C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=...
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],[CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC...
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,[COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H...
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],"[CCN(CC)CCC1=CNC2=CC=CC(O)=C12, CCN(CC)CCC1=CN..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,[N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(...
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3...
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,"[O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1, N..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],"[CC(N)CC1=CC=C2C(=C1)OCO2, CC(=O)CC1=CC=C2C(=C..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,[O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3...
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,[O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(...
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,[O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3...,"[N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F, O..."

In [14]:
import pandas as pd
from rdkit import Chem
from rdkit.DataStructs import TanimotoSimilarity
from rdkit.Chem import AllChem

def get_similarity(smiles1, smiles2):
    mol1 = Chem.MolFromSmiles(smiles1)
    mol2 = Chem.MolFromSmiles(smiles2)
    if mol1 and mol2:
        fp1 = AllChem.GetMorganFingerprintAsBitVect(mol1, 2, nBits=2048)
        fp2 = AllChem.GetMorganFingerprintAsBitVect(mol2, 2, nBits=2048)
        return TanimotoSimilarity(fp1, fp2)
    return 0

In [18]:
true_mains = df['true_mains'].to_list()
predict_8079 = df['predict_8079'].to_list()
top_num = 5
correct_num = 0
dict_true2top = {}
for i in range(len(predict_8079)):
    true_main = true_mains[i]
    true_main = '|'.join(true_main)

    predict_8079_i = predict_8079[i]
    predict_8079_i_topn = predict_8079_i[:top_num]
    predict_8079_i_topn = list(map(canonicalsmiles,predict_8079_i_topn))

    for idx,j in enumerate(predict_8079_i_topn):
        if get_similarity(true_main,j) == 1:
            correct_num = correct_num + 1
            dict_true2top[true_main] = idx + 1
            print(f'{i}: top{idx}')
            break
correct_num/len(predict_8079)

0: top4
1: top1
2: top0
3: top0
4: top1
5: top4
6: top2
8: top4
9: top1
12: top0
13: top0
14: top0
15: top0
16: top0
19: top2
20: top2
21: top0
23: top0
25: top0
27: top2
28: top2

0.7

In [20]:
true_mains = ['|'.join(i) for i in true_mains]
df['rank'] = [dict_true2top.get(i,0) for i in true_mains]
df

,name,substrate,predict,top_n,true_mains,predict_8079,rank
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,5
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,[CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(O...,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],"[CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21, ...",1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],[CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=...,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],[CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC...,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC...,[O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=...,5
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,[C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4...,3
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,[OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[...,0
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,"[NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1, O=C...",5
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,[NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=N...,2
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],[CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=...,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,[COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=C...,0
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,1
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],[O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2...,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,[OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[...,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],[O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12...,1
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,[O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)...,1
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,[C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F...,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,[C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=...,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],[CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC...,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,[COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H...,3
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],"[CCN(CC)CCC1=CNC2=CC=CC(O)=C12, CCN(CC)CCC1=CN...",1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,[N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3...,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,"[O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1, N...",0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],"[CC(N)CC1=CC=C2C(=C1)OCO2, CC(=O)CC1=CC=C2C(=C...",1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,[O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3...,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,3
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,[O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(...,3
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,[O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3...,"[N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F, O...",0

In [21]:
df_total = pd.read_csv('results_mainproduct_top5_similaritybased_new30_nolist.csv')
substrate = df['substrate'].to_list()
substrate_8079 = df_total['substrate'].to_list()
true_rank_metareactseed8079 = df_total['true_rank_metareactseed8079'].to_list()
dict_sub2rank8079 = dict(zip(substrate_8079,true_rank_metareactseed8079))
true_rank_metareactseed8079_new = []

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079,true_rank_metapredictor,true_rank_metatrans,true_rank_ourmodel
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0,0,5,0,0,2
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,5,2,2,0,0,3
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,0,2,1,1,4,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,2,1,1,5,4,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,0,5,2,0,3,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,0,3,5,0,0,4
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2,3,3,0,0,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,0,2,0,4,2,3
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,0,4,5,0,0,2
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,5,3,2,3,0,1
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,0,1,4,0,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,3,4,0,5,3,4
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,0,4,1,3,4,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,2,1,1,0,3,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,2,1,1,0,2,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,5,1,1,1,4,2
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,3,1,1,0,0,2
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,0,4,0,0,0,3
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3,0,0,3,0,5
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,0,3,3,2,0,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,3,1,3,0,1,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12,2,1,1,5,3,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,0,0,0,0,4,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,2,1,1,3,3,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,0,3,0,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2,2,4,1,0,3,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,0,1,3,1,0,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0,2,5,0,0,1
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,2,2,3,0,0,4
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,0,3,3,0,0,4