1. 把真实的主要代谢物smiles放进pred_results_score.csv

In [35]:
import pandas as pd
from rdkit import Chem
from tqdm import tqdm

In [36]:
import pandas as pd
from rdkit import Chem
from rdkit.DataStructs import TanimotoSimilarity
from rdkit.Chem import AllChem

def get_similarity(smiles1, smiles2):
    mol1 = Chem.MolFromSmiles(smiles1)
    mol2 = Chem.MolFromSmiles(smiles2)
    if mol1 and mol2:
        fp1 = AllChem.GetMorganFingerprintAsBitVect(mol1, 2, nBits=2048)
        fp2 = AllChem.GetMorganFingerprintAsBitVect(mol2, 2, nBits=2048)
        return TanimotoSimilarity(fp1, fp2)
    return 0

In [37]:
# 提取出正确的主要代谢物放到true_mains列
df = pd.read_csv('pred_results_score_new.csv')
true_mains = []
for i in tqdm(range(len(df))):
    predicts = df.iloc[i,2]
    try:
        predicts = predicts.split('|')
    except:
        predicts = ['None']
    top_n = df.iloc[i,3]
    if len(top_n) == 1:
        top_n = int(top_n)
        true_main = predicts[top_n-1].split(' ')[0]
        true_main = [true_main]
    else:
        true_main = top_n.split(',')
    true_main = '|'.join(true_main)
    true_mains.append(true_main)
df['true_mains'] = true_mains
df

100%|██████████| 30/30 [00:00<00:00, 15110.98it/s]

,name,substrate,predict,top_n,true_mains
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@@H]3CC[C@H](C2)N3C(=O)[C@@H]2CC2...
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...

In [38]:
# 将substrate和true_mains列的smiles标准化
def canonical_smiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

substrates = df['substrate'].to_list()
true_mains = df['true_mains'].to_list()
substrates_cano = [canonical_smiles(i) for i in substrates]
true_mains_cano = [canonical_smiles(i) for i in true_mains]

df['substrate'] = substrates_cano
df['true_mains'] = true_mains_cano

df

,name,substrate,predict,top_n,true_mains
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...

In [39]:
df.to_csv('pred_results_substrate_truemains.csv',index=None)

In [6]:
# df.to_pickle('pred_results_substrate_truemains.pickle')

In [40]:
# 建立一个真实的dict_sub2main
df = pd.read_csv('pred_results_substrate_truemains.csv')
substrate_cano = df['substrate'].to_list()
true_mains_cano = df['true_mains'].to_list()

dict_sub2main = dict(zip(substrate_cano,true_mains_cano))
dict_sub2main

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2',
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 'CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O',
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21',
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12',
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 'Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12',
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 'Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2(F)F)n1',
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC',
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1',
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]c2ccccc12',
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 'NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1',
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 'Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1',
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 'COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]5O)CCOCC4)cc3)ccnc2n1',
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O',
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 'O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1',
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 'OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O',
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 'O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12',
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 'O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1ccc(CNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)cc1',
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 'CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1',
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(=O)O',
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 'CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1',
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 'C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)O[C@@]1(C)C(F)(F)F',
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 'CCN(CC)CCc1c[nH]c2cccc(O)c12',
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 'NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc(C(F)(F)F)cc2)c1',
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 'C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1)C(=O)O',
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cccc3C2=O)C(=O)N1',
 'CNC(C)Cc1ccc2c(c1)OCO2': 'CC(N)Cc1ccc2c(c1)OCO2',
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 'Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21',
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O',
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 'O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)[C@@H](O)[C@@H]1O',
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 'O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)C(O)[C@@H]1O'}

2. 整理 SyGMa 的结果

In [44]:
# 找到SyGMa_main.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_sygma_sub2truerank存放
df_sygma = pd.read_csv('SyGMa_predict.csv')
dict_sub2truerank = {}
for i in tqdm(range(len(df_sygma))):
    substrate = df_sygma.iloc[i,0]
    predicts = df_sygma.iloc[i,1]
    predicts = predicts.split('|')

    # 底物要能对应上
    substrate = canonical_smiles(substrate)
    true_mains_sygma = dict_sub2main[substrate]

    # 每个底物只看sygma预测出的top_5
    predicts_top_5 = predicts[:5]
    predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


    # for j in range(len(predicts_top_5)):
    #     predict_top_5 = predicts_top_5[j]
    #     for x in true_mains_sygma:
    #         if get_similarity(predict_top_5,x) == 1:
    #             true_rank.append(j+1)

    for j, predict_top_5_new in enumerate(predicts_top_5):
        # 检查 predict_top_5 是否与任何 true_mains_sygma 匹配
        if get_similarity(predict_top_5_new, true_mains_sygma) == 1:
            dict_sub2truerank[substrate] = j+1
            # true_rank.append(j+1)
            break

substrates_sygma = df_sygma['smi'].to_list()
substrates_sygma_cano = list(map(canonical_smiles,substrates_sygma))
sygma_ranks = [dict_sub2truerank.get(i,0) for i in substrates_sygma_cano]
df_sygma['smi'] = substrates_sygma_cano
df_sygma['sygma_rank'] = sygma_ranks
df_sygma
# dict_sygma_sub2truerank = dict(zip(substrates_sygma_cano,true_rank))
# dict_sygma_sub2truerank

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 234.66it/s]

,smi,extracted_strings,sygma_rank
0,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3
1,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,0
2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2
4,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12|CCN(CC)CCc1...,2
5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12|CC(=O...,0
6,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,0
7,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1|O...,2
8,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21|CCCCCc...,0
9,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,0
10,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,Cn1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@...,0
11,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,0
12,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,3
13,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)...,2
14,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1...,3
15,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,2
16,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,5
17,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,5
18,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1|O...,2
19,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,0
20,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2|O=C...,0
21,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc...,0
22,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,3
23,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0
24,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,5
25,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,0
26,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0
27,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,0
28,CNC(C)Cc1ccc2c(c1)OCO2,CNC(C)Cc1ccc2c(c1)OCO2|CC(N)Cc1ccc2c(c1)OCO2|C...,2
29,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,0

In [45]:
dict_sygma_sub2truerank = pd.Series(df_sygma.sygma_rank.values, index=df_sygma.smi).to_dict()
dict_sygma_sub2truerank

{'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 3,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 2,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 2,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 2,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 2,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 0,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 3,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 2,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 3,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 2,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 5,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 5,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 2,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 3,
 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 5,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 2,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0}

In [46]:
# 在df中增加一列存放true_rank_sygma
df = pd.read_csv('pred_results_substrate_truemains.csv')
substrate_cano = df['substrate'].to_list()
true_rank_sygma = [dict_sygma_sub2truerank[i] for i in substrates_cano]
df['true_rank_sygma'] = true_rank_sygma
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,5
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,0
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,2
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,0
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,0
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,5
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,3
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,0
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,2
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,2
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,5
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,3
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,0
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,3
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12,2
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,2
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2,2
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,2
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,0

3. 整理 MetaReact 的结果

In [53]:
# 找到MetaReact_main.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metareact_sub2truerank存放
df_metareact = pd.read_csv('MetaReact_seed42.csv')
dict_metareact_sub2truerank = {}
for i in tqdm(range(len(df_metareact))):
    substrate = df_metareact.iloc[i,1]
    predicts = df_metareact.iloc[i,2]
    predicts = predicts.split('|')

    # 底物要能对应上
    substrate = canonical_smiles(substrate)
    true_mains_metareact = dict_sub2main[substrate]

    # 每个底物只看sygma预测出的top_5
    predicts_top_5 = predicts[:5]
    predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


    for j, predict_top_5_new in enumerate(predicts_top_5):
        # 检查 predict_top_5 是否与任何 true_mains_sygma 匹配
        if get_similarity(predict_top_5_new, true_mains_metareact) == 1:
            dict_metareact_sub2truerank[substrate] = j+1
            break

substrates_metareact = df_metareact['substrate'].to_list()
substrates_metareact_cano = list(map(canonical_smiles,substrates_metareact))
metareact_rank = [dict_metareact_sub2truerank.get(i,0) for i in substrates_metareact_cano]
df_metareact['substrate'] = substrates_metareact_cano
df_metareact['metareact_rank'] = metareact_rank
df_metareact

100%|██████████| 30/30 [00:00<00:00, 285.35it/s]

,name,substrate,predict,metareact_rank
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC...,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CC(O)CCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21|...,2
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C...,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=...,3
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=N...,3
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)O)C(C3=CN(C)C4=CC...,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C...,4
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1|O=C(N...,3
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOC1=CC=C(NC(=O)N(CCO)CC2=CC3=CC(C)=CC(C)=C3N...,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COC1=CC=C2C(OC3=CC=C(C4(C(=O)O)CCOCC4)C=C3)=CC...,4
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C...,1
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2C...,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[C...,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COC1=C(O)C(O[C@@H]2O[C@H](C(=O)O)[C@H](O)[C@H]...,0
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)=...,1
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)...,4
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)CC1=CC=CS1=O)[C@@H](CC1=CNC2=CC=CC=C12...,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2...,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](C2=CC=C(F)C(F)=C2O)C(C(=O)NC2=CC...,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCC1=CNC2=CC=CC(O)=C12|CCN(CC)CCC1=CNC2...,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(N...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C...,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1|NC(...,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)CC1=CC=C2C(=C1)OCO2|C[C@H](N)CC1=CC=C2C(=...,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3=...,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1(C)CC[C@@]2(C(=O)OC3OCC(O)C(O)C3O)C(C1)C1=C...,2
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(C...,3
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F|O=C...,0

In [54]:
dict_metareact_sub2truerank = pd.Series(df_metareact.metareact_rank.values, index=df_metareact.substrate).to_dict()
dict_metareact_sub2truerank

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 2,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 2,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 1,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 3,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 3,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 2,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 4,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 3,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 1,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 4,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 1,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 1,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 1,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 0,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 1,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 4,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 3,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 1,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 1,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 1,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 1,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 2,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 3,
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 0}

In [55]:
# 在df中增加一列存放true_rank_metareact
substrate_cano = df['substrate'].to_list()
true_rank_metareact = [dict_metareact_sub2truerank[i] for i in substrates_cano]
df['true_rank_metareactseed42'] = true_rank_metareact
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,5,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,0,2
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,2,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,0,3
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,0,3
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,0,4
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,0,3
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,5,1
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,3,4
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,0,1
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,2,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,2,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,5,0
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,3,1
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,0,4
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,0,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,3,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12,2,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,0,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,2,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2,2,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,0,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0,2
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,2,3
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,0,0

In [58]:
# 找到MetaReact_main.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metareact_sub2truerank存放
df_metareact8079 = pd.read_csv('MetaReact_seed8079.csv')
dict_metareact8079_sub2truerank = {}
for i in tqdm(range(len(df_metareact8079))):
    substrate = df_metareact8079.iloc[i,1]
    predicts = df_metareact8079.iloc[i,2]
    predicts = predicts.split('|')

    # 底物要能对应上
    substrate = canonical_smiles(substrate)
    true_mains_metareact8079 = dict_sub2main[substrate]

    # 每个底物只看sygma预测出的top_5
    predicts_top_5 = predicts[:5]
    predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


    for j, predict_top_5_new in enumerate(predicts_top_5):
        # 检查 predict_top_5 是否与任何 true_mains_sygma 匹配
        if get_similarity(predict_top_5_new, true_mains_metareact8079) == 1:
            dict_metareact8079_sub2truerank[substrate] = j+1
            break

substrates_metareact8079 = df_metareact8079['substrate'].to_list()
substrates_metareact8079_cano = list(map(canonical_smiles,substrates_metareact8079))
metareact8079_rank = [dict_metareact8079_sub2truerank.get(i,0) for i in substrates_metareact8079_cano]
df_metareact8079['substrate'] = substrates_metareact8079_cano
df_metareact8079['metareact_rank'] = metareact8079_rank
df_metareact8079

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 266.06it/s]

,name,substrate,predict,metareact_rank
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,5
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC...,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21|CC...,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C...,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=...,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=N...,5
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4=...,3
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C...,0
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1|O=C(N...,5
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC...,2
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=C...,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=CC...,0
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C...,1
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2C...,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[C...,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12|...,1
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)=...,1
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)...,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=C...,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2...,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H]...,3
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCC1=CNC2=CC=CC(O)=C12|CCN(CC)CCC1=CNC2...,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(N...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C...,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1|NC(...,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)CC1=CC=C2C(=C1)OCO2|CC(=O)CC1=CC=C2C(=C1)...,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3=...,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@]...,3
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(C...,3
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F|O=C...,0

In [59]:
dict_metareact8079_sub2truerank = pd.Series(df_metareact8079.metareact_rank.values, index=df_metareact8079.substrate).to_dict()
dict_metareact8079_sub2truerank

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 5,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 2,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 1,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 1,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 2,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 5,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 3,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 5,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 2,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 0,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 1,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 1,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 1,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 1,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 1,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 3,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 3,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 1,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 1,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 1,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 3,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 3,
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 0}

In [60]:
# 在df中增加一列存放true_rank_metareact
substrate_cano = df['substrate'].to_list()
true_rank_metareact8079 = [dict_metareact8079_sub2truerank[i] for i in substrates_cano]
df['true_rank_metareactseed8079'] = true_rank_metareact8079
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0,0,5
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,5,2,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,0,2,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,2,1,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,0,3,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,0,3,5
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2,2,3
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,0,4,0
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,0,3,5
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,5,1,2
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,0,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,3,4,0
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,0,1,1
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,2,1,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,2,1,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,5,0,1
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,3,1,1
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,0,4,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3,0,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,0,3,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,3,1,3
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12,2,1,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,0,0,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,2,1,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2,2,1,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,0,0,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0,2,3
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,2,3,3
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,0,0,0

4. 整理 metapredictor 的结果

In [67]:
# 找到meta_predictor.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metapredictor_sub2truerank存放
df_metapredictor = pd.read_csv('MetaPredictor.csv')
dict_metapredictor_sub2truerank = {}
for i in tqdm(range(len(df_metapredictor))):
    try:
        substrate = df_metapredictor.iloc[i,1]
        predicts = df_metapredictor.iloc[i,2]
        predicts = predicts.split(' ')
        

        # 底物要能对应上
        substrate = canonical_smiles(substrate)
        true_mains_metapredictor = dict_sub2main[substrate]

        # 每个底物只看sygma预测出的top_5
        predicts_top_5 = predicts[:5]
        predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


        for j, predict_top_5_new in enumerate(predicts_top_5):
            # 检查 predict_top_5 是否与任何 true_mains_sygma 匹配
            if get_similarity(predict_top_5_new, true_mains_metapredictor) == 1:
                dict_metapredictor_sub2truerank[substrate] = j+1
                break
    except:
        substrate = df_metapredictor.iloc[i,1]
        substrate = canonical_smiles(substrate)
        dict_metapredictor_sub2truerank[substrate] = 0


substrates_metapredictor = df_metapredictor['SMILES'].to_list()
substrates_metapredictor_cano = list(map(canonical_smiles,substrates_metapredictor))

metapredictor_rank = [dict_metapredictor_sub2truerank.get(i,0) for i in substrates_metapredictor_cano]
df_metapredictor['SMILES'] = substrates_metapredictor_cano
df_metapredictor['metapredictor_rank'] = metapredictor_rank
df_metapredictor

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 229.77it/s]

,Name,SMILES,predictions,metapredictor_rank
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](N)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](...,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(OC...,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21 CC...,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,CC(=O)NC1=CC=C(CO)C(C(=O)N[C@H](C)/C2=C/C=C\C3...,5
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC2OC2C2=CC=CC...,0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[...,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)...,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,CC1=CC=C([C@@H]2O[C@H](COC3OC(C(=O)O)C(O)C(O)C...,4
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2(O)CC=NC3...,0
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC...,3
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(C)=CC(C)=C3N...,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COC1=CC=C2C(OC3=CC=C(C4(C(=O)N(O)O)CCOCC4)C=C3...,5
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,OCC1OC(OCC2OC(O)C(O)C(O)C2O)C(O)C(O)C1O C/C=C/...,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,CC1=NC=C(S(=O)(=O)N2CCC(C3(O)CN4N=CN=C4C=C3Cl)...,0
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,COC1=CC=C(CCCCO)C=C1 COC1=CC=C(CCCCOC2OC(CO)C(...,0
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=C1C=C(C2=CC=C(O)C=C2)OC2=C1C(O)=C(O)C(O)=C2 ...,1
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C1C=CC2=C(C=CC(=O)NCCCOC3=CC=CC([C@@](O)(C(=...,0
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC(O)[C@@H](C)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(...,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)CC1=CC=CS1)[C@@H](C/C1=C/NC2=CC=CC=C21...,3
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1/C=C2/C3=CC=CC4=C3C(=CN4C(=O)C3(...,2
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,COC1=C([C@H]2C(C(=O)NC3=CC=NC(C(N)=O)=C3)O[C@@...,0
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCNCCC1=CNC2=C1C(OC(C)=O)=CC=C2 CCN(CC)CCc1c[n...,5
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)C2=CC(C(=O)N3CCC[C@@H]3C(=O)N...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@@](=O)(O)OC[C@H]1O[C@@](C#N)(/C2=C/...,3
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,NaN,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CNC(C)CC1=CC=C2OC(O)OC2=C1 CNC(C)CC1=CC=C(OCO)...,0
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,CN1C=NC2=C1C(=O)N(CC1=NC([C@@H]3CO[C@@H](C4=CC...,1
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(C1=CC=CN=C1C1=CC=NC=C1)N1CCC(O)(CC2=CC=CCC...,0
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(CCC(F)(F)F)N1CCC(O)(CC(=O)C(F)(F)F)CC1 FC(...,0

In [68]:
dict_metapredictor_sub2truerank = pd.Series(df_metapredictor.metapredictor_rank.values, index=df_metapredictor.SMILES).to_dict()
dict_metapredictor_sub2truerank

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 0,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 1,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 5,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 0,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 4,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 3,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 5,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 3,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 0,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 1,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 3,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 2,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 0,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 5,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 3,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 0,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 1,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 0,
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 0}

In [69]:
# 在df中增加一列存放true_rank_metareact
substrate_cano = df['substrate'].to_list()
true_rank_metapredictor = [dict_metapredictor_sub2truerank[i] for i in substrates_cano]
df['true_rank_metapredictor'] = true_rank_metapredictor
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079,true_rank_metapredictor
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,0,0,5,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,5,2,2,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,0,2,1,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,2,1,1,5
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,0,3,2,0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,0,3,5,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,2,2,3,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,0,4,0,4
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,0,3,5,0
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,5,1,2,3
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,0,0,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,3,4,0,5
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,0,1,1,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,2,1,1,0
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,2,1,1,0
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,5,0,1,1
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,3,1,1,0
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,0,4,0,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,3,0,0,3
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,0,3,3,2
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,3,1,3,0
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,CCN(CC)CCc1c[nH]c2cccc(O)c12,2,1,1,5
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,0,0,0,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,2,1,1,3
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,0,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,CC(N)Cc1ccc2c(c1)OCO2,2,1,1,0
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,0,0,0,1
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,0,2,3,0
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,2,3,3,0
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,0,0,0,0

5. 整理 metatrans 的结果

In [70]:
# 找到main_predict_metatrans.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metatrans_sub2truerank存放
df_metatrans = pd.read_csv('metatrans.csv')
dict_metatrans_sub2truerank = {}
for i in tqdm(range(len(df_metatrans))):
    substrate = df_metatrans.iloc[i,1]
    predicts = df_metatrans.iloc[i,2]
    try:
        predicts = predicts.split(' ')
        

        # 底物要能对应上
        substrate = canonical_smiles(substrate)
        true_mains_metatrans = dict_sub2main[substrate]

        # 每个底物只看sygma预测出的top_5
        predicts_top_5 = predicts[:5]
        predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


        for j, predict_top_5_new in enumerate(predicts_top_5):
            # 检查 predict_top_5 是否与任何 true_mains_sygma 匹配
            if get_similarity(predict_top_5_new, true_mains_metatrans) == 1:
                dict_metatrans_sub2truerank[substrate] = j+1
                break
    except:
        substrate = canonical_smiles(substrate)
        dict_metatrans_sub2truerank[substrate] = 0

substrates_metatrans = df_metatrans['SMILES'].to_list()
substrates_metatrans_cano = list(map(canonical_smiles,substrates_metatrans))

metatrans_rank = [dict_metatrans_sub2truerank.get(i,0) for i in substrates_metatrans_cano]
df_metatrans['SMILES'] = substrates_metatrans_cano
df_metatrans['metatrans_rank'] = metatrans_rank
df_metatrans

 63%|██████▎   | 19/30 [00:00<00:00, 184.30it/s]

100%|██████████| 30/30 [00:00<00:00, 207.29it/s]

,Molecule ID,SMILES,Metabolites,metatrans_rank
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(CCS2)C...,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(=O)O)c(F)c1)n1cc(OC)c(-...,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCCCC21 CCCCCc1cc...,4
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,CC(=O)Nc1ccc(CO)c(C(=O)N[C@H](C)c2cccc3ccccc23...,4
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1ccc(NC=O)cc1C(=O)N[C@H](C)c1cccc2ccccc12 CC...,3
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,Cn1cc(Nc2nccc(N3CC4CC[C@@H](C3)N4C(=O)C3(F)CC3...,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OC[C@H]1O[C@@H](c2ccc(Cc3ccc(-c4ccc(F)cc4)s3)c...,2
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(O)c1sccc1NCc1ccnc2ccccc12 Nc1ccsc1C(=O)Nc1...,0
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CC=O)c2ccc(Cl)cc2)CCN(c2ncnc3...,0
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=S)NCc2cc3cc(C)cc(C)c3[nH]c2=O)cc1...,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,O=C(NO)C1(c2ccc(Oc3ccnc4nc(O)ccc34)cc2)CCOCC1 ...,3
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCC=O)OC1OC(COC2OC(CO)C...,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)C(O)C2)s...,2
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,COc1ccc(CCCCOC2OC(CO)C(O)C(OS(=O)(=O)[O-])C2O)...,0
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=C(O)C1OC(OC2C(O)C(O)C(O)C(O)C2O)C(O)C(O)C1O ...,4
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,C[N+]1([O-])CCC[C@@H](OC(=O)[C@@](O)(c2ccccc2)...,0
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC(O)[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)C(Cc1c[nH]c2ccccc12)C(=O)NC(C...,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1=CC2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,0
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,CC1C(c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)...,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CC[N+]([O-])(CC)CCc1c[nH]c2cccc(O)c12 CC[N+](C...,3
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@H]3C(=O)N...,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,CCC(CC)COC(=O)[C@H](C)N[P@@](=O)(O)OC[C@H]1O[C...,0
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CCC(N2Cc3c(O)cccc3C2=O)C(O)=N1 O=C1N=C(O)C...,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,C[C@@H](N)[C@@H](O)c1ccc2c(c1)OC2 NC(CO)Cc1ccc...,3
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1nc[nH]c2c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1CC(O)C(O)C(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=...,0
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccc(O)cc2)CC...,0
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(CCC(F)(F)F)N1CCC(O)(C(F)(F)F)CC1 O=C(O)N1C...,0

In [71]:
dict_metatrans_sub2truerank = pd.Series(df_metatrans.metatrans_rank.values, index=df_metatrans.SMILES).to_dict()
dict_metatrans_sub2truerank

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 0,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 4,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 4,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 3,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 2,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 0,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 3,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 3,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 2,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 4,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 0,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 1,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 3,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 0,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 3,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 0,
 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': 0}

In [56]:
# 在df中增加一列存放true_rank_metatrans
substrate_cano = df['substrate'].to_list()
true_rank_metatrans = [dict_metatrans_sub2truerank[i] for i in substrates_cano]
df['true_rank_metatrans'] = true_rank_metatrans
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079,true_rank_metapredictor,true_rank_metatrans
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,0,5,0,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,2,0,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,2,1,1,4
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,1,5,4
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,5,2,0,3
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC...,0,3,5,0,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,3,0,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,2,0,4,2
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,4,5,0,0
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,5,3,2,3,0
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,1,4,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,3,4,0,5,3
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,4,1,3,4
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,1,0,3
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,1,0,2
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,1,1,4
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,1,0,0
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,4,0,0,0
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,0,3,0
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3,2,0
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,1,3,0,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,1,5,3
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0,0,4
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,1,3,3
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,3,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,4,1,0,3
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,1,3,1,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,2,5,0,0
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,2,2,3,0,0
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,[O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3...,0,3,3,0,0

6. 整理全部结果

In [57]:
# 将我们的结果也整理进来放在true_rank_ourmodel列
top_ns = df['top_n'].to_list()
true_rank_ourmodel = [int(x) if len(x)==1 else 0 for x in top_ns]
df['true_rank_ourmodel'] = true_rank_ourmodel
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079,true_rank_metapredictor,true_rank_metatrans,true_rank_ourmodel
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,0,5,0,0,2
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,2,0,0,3
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,2,1,1,4,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,1,5,4,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,5,2,0,3,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC...,0,3,5,0,0,4
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,3,0,0,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,2,0,4,2,3
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,4,5,0,0,2
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,5,3,2,3,0,1
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,1,4,0,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,3,4,0,5,3,4
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,4,1,3,4,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,1,0,3,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,1,0,2,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,1,1,4,2
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,1,0,0,2
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,4,0,0,0,3
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,0,3,0,5
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3,2,0,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,1,3,0,1,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,1,5,3,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0,0,4,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,1,3,3,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,3,0,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,4,1,0,3,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,1,3,1,0,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,2,5,0,0,1
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,2,2,3,0,0,4
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,[O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3...,0,3,3,0,0,0

In [58]:
df.iloc[-1,-1] = 4
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareactseed42,true_rank_metareactseed8079,true_rank_metapredictor,true_rank_metatrans,true_rank_ourmodel
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,0,5,0,0,2
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,2,0,0,3
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,2,1,1,4,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,1,5,4,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,5,2,0,3,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC...,0,3,5,0,0,4
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,3,0,0,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,2,0,4,2,3
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,4,5,0,0,2
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,5,3,2,3,0,1
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,1,4,0,0,0
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,3,4,0,5,3,4
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,4,1,3,4,3
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,1,0,3,1
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,1,0,2,1
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,1,1,4,2
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,1,0,0,2
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,4,0,0,0,3
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,0,3,0,5
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3,2,0,3
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,1,3,0,1,1
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,1,5,3,1
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0,0,4,0
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,1,3,3,1
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,3,0,0,0,0
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,4,1,0,3,1
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,1,3,1,0,0
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,2,5,0,0,1
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,2,2,3,0,0,4
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,[O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3...,0,3,3,0,0,4

In [59]:
# 将全部结果导出为 results_mainproduct_top5.csv
df.to_csv('results_mainproduct_top5_similaritybased_new30.csv',index=None)

In [60]:
# 为了保留df中的list，将全部结果导出为 results_mainproduct_top5.parquet
df.to_parquet('results_mainproduct_top5_similaritybased_new30.parquet')

5. 将results_mainproduct_top5_similaritybased_new30.csv的列表改成竖线隔开的格式

In [11]:
df = pd.read_parquet('results_mainproduct_top5_similaritybased_new30.parquet')
true_mains = df['true_mains'].to_list()
true_mains = ['|'.join(i) for i in true_mains]
df['true_mains'] = true_mains
df.to_csv('results_mainproduct_top5_similaritybased_new30_nolist.csv',index=None)