1. 把真实的主要代谢物smiles放进pred_results_score.csv

In [3]:
import pandas as pd
from rdkit import Chem
from tqdm import tqdm

In [15]:
# 提取出正确的主要代谢物放到true_mains列
df = pd.read_csv('pred_results_score.csv')
true_mains = []
for i in tqdm(range(len(df))):
    predicts = df.iloc[i,2]
    predicts = predicts.split('|')
    top_n = df.iloc[i,3]
    if len(top_n) == 1:
        top_n = int(top_n)
        true_main = predicts[top_n-1].split(' ')[0]
        true_main = [true_main]
    else:
        true_main = top_n.split(',')
    true_mains.append(true_main)
df['true_mains'] = true_mains
df

100%|██████████| 30/30 [00:00<00:00, 8498.52it/s]

,name,substrate,predict,top_n,true_mains
0,1,O=C(N[C@@H](C(C)(C)C)C(N1CC2(SCCS2)C[C@H]1C(N[...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...
1,2,ClC(C=C1C2=CC(N(C=C2OC)[C@H](C(NC3=CC=C(C(F)=C...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...
2,3,CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21]
3,4,CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)/C2=C/C=C\C3=...,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12]
4,5,CC1=CC=C(N)C=C1C(=O)N[C@H](C)/C1=C/C=C\C2=CC=C...,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12]
5,6,CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@...
6,7,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(/C3=C/N(...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...
7,8,CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...
8,9,COC1CCC(N2/C([C@@]3(C)CCC(=O)N3C3=CC=C(F)C(F)=...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C...
9,10,O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NC/C2=C/C=N\C...,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...
10,11,NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(/C2=N...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...
11,12,[CH3]COC1=CC=C(NC(=S)N(CCO)C/C2=C/C3=CC([CH3])...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O]
12,13,COC1=C\C=C2\C(OC3=CC=C(C4(C(=O)NO)CCOCC4)C=C3)...,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...
14,15,CC1=NC=C(S(N2CCC(C3=C/N4N=CN=C4/C=C\3Cl)CC2)(=...,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1]
15,16,COC1=CC=C(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2...,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...
16,17,O=C(O)C1OC(OC2=C/C3=C(C(=O)C=C(C4=CC=C(O)C=C4)...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12]
17,18,O=C(NCCCOC1=CC=CC([C@](C2=CC=CC=C2)(O)C(O[C@H]...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)F)...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...
19,20,C(=O)([C@H](CCCNC(=N)N)NC(=O)[C@@H]1CCCN1C(=O)...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...
20,21,CN1CC(C(=O)N(CC)CC)/C=C2/C3=CC=CC4=C3C(=CN4C(=...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1]
21,22,COC1=C([C@H]2C(C(=O)NC3=CC=NC(C(N)=O)=C3)O[C@@...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...
22,23,CC(=O)O/C1=C/C=C\C2=C1C(CCN(CC)CC)=CN2,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12]
23,24,O=C([C@H]1CCCN1C(C2=CC=CC(S(N3CC(C3)C#N)(=O)=O...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)N...
24,25,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(/C2=C/C=C...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...
25,26,[H][C@@]1(N2CC3=C(C=CC=C3OCC3=CC=C(CN4CCOCC4)C...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC...
26,27,[CH3]NC([CH3])CC1=CC=C2C(=C1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2]
27,28,O=C(N(C=N1)CC2=NC([C@@H]3CO[C@H](C3)C4=CC=C(C=...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](...
28,29,O[C@@H]1[C@@H](C(C2[C@](C1)(C3CC=C4[C@]([C@@]3...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...
29,30,O=C(C1=CC=CN=C1C1=CC=NC=C1)N1CCC(O)(CC2=CC=CC=...,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...

In [18]:
# 将substrate和true_mains列的smiles标准化
def canonical_smiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

substrates = df['substrate'].to_list()
true_mains = df['true_mains'].to_list()
substrates_cano = [canonical_smiles(i) for i in substrates]
true_mains_cano = [list(map(canonical_smiles,i)) for i in true_mains]

df['substrate'] = substrates_cano
df['true_mains'] = true_mains_cano

df

,name,substrate,predict,top_n,true_mains
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21]
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12]
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12]
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1]
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1]
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12]
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1]
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12]
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2]
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...

2. 整理 SyGMa 的结果

In [29]:
# 建立一个真实的dict_sub2main
dict_sub2main = {}
for i in range(len(substrates_cano)):
    dict_sub2main[substrates_cano[i]] = true_mains_cano[i]
dict_sub2main

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': ['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2'],
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': ['CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O'],
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': ['CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21'],
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': ['Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12'],
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': ['Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12'],
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': ['Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)c1O'],
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': ['C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC'],
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': ['Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1'],
 'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1': ['COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1',
  'COC1CCC(n2c([C@@]3(C)C(O)CC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1',
  'COC1CCC(n2c([C@@]3(CO)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1',
  'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3cc(F)c(F)cc3O)nc3cc(-c4c(C)noc4C)ccc32)CC1',
  'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3cc(O)c(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1',
  'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3cc(O)c(F)c(F)c3O)nc3cc(-c4c(C)noc4C)ccc32)CC1'],
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': ['O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]c2ccccc12'],
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': ['NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1'],
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': ['Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1'],
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': ['COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]5O)CCOCC4)cc3)ccnc2n1'],
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': ['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O'],
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': ['O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1'],
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': ['OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O'],
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': ['O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12'],
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': ['O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1ccc(CNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)cc1'],
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': ['CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1'],
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': ['CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(=O)O'],
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': ['CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1'],
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': ['C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)O[C@@]1(C)C(F)(F)F'],
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': ['CCN(CC)CCc1c[nH]c2cccc(O)c12'],
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': ['NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc(C(F)(F)F)cc2)c1'],
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': ['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1)C(=O)O'],
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': ['O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cccc3C2=O)C(=O)N1'],
 'CNC(C)Cc1ccc2c(c1)OCO2': ['CC(N)Cc1ccc2c(c1)OCO2'],
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': ['Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21'],
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': ['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O'],
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': ['O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)[C@@H](O)[C@@H]1O']}

In [39]:
# 找到SyGMa_main.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_sygma_sub2truerank存放
df_sygma = pd.read_csv('SyGMa_main.csv')
true_rank = []
for i in tqdm(range(len(df_sygma))):
    substrate = df_sygma.iloc[i,0]
    predicts = df_sygma.iloc[i,1]
    predicts = predicts.split('|')

    # 底物要能对应上
    substrate = canonical_smiles(substrate)
    true_mains_sygma = dict_sub2main[substrate]

    # 每个底物只看sygma预测出的top_5
    predicts_top_5 = predicts[:5]
    predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


    for j in range(len(predicts_top_5)):
        predict_top_5 = predicts_top_5[j]
        if predict_top_5 in true_mains_sygma:
            true_rank.append(j+1)
    if len(true_rank) < i+1:
        true_rank.append(0)
substrates_sygma = df_sygma['smi'].to_list()
substrates_sygma_cano = list(map(canonical_smiles,substrates_sygma))
dict_sygma_sub2truerank = dict(zip(substrates_sygma_cano,true_rank))
dict_sygma_sub2truerank

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 571.12it/s]

{'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 3,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 2,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 2,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 2,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 2,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 0,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 3,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 2,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 0,
 'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 2,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 5,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 0,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 0,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 3,
 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 5,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 2,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0}

In [40]:
# 在df中增加一列存放true_rank_sygma
true_rank_sygma = [dict_sygma_sub2truerank[i] for i in substrates_cano]
df['true_rank_sygma'] = true_rank_sygma
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...,0
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,0
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,0
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,0

3. 整理 MetaReact 的结果

In [41]:
# 找到MetaReact_main.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metareact_sub2truerank存放
df_metareact = pd.read_csv('MetaReact_main.csv')
true_rank = []
for i in tqdm(range(len(df_metareact))):
    substrate = df_metareact.iloc[i,1]
    predicts = df_metareact.iloc[i,2]
    predicts = predicts.split('|')

    # 底物要能对应上
    substrate = canonical_smiles(substrate)
    true_mains_metareact = dict_sub2main[substrate]

    # 每个底物只看sygma预测出的top_5
    predicts_top_5 = predicts[:5]
    predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


    for j in range(len(predicts_top_5)):
        predict_top_5 = predicts_top_5[j]
        if predict_top_5 in true_mains_metareact:
            true_rank.append(j+1)
    if len(true_rank) < i+1:
        true_rank.append(0)
substrates_metareact = df_metareact['substrate'].to_list()
substrates_metareact_cano = list(map(canonical_smiles,substrates_metareact))
dict_metareact_sub2truerank = dict(zip(substrates_metareact_cano,true_rank))
dict_metareact_sub2truerank

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 506.93it/s]

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 5,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 2,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 1,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 1,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 2,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 3,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 5,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 2,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 0,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 1,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 1,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 1,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 1,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 1,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 3,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 3,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 1,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 1,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 1,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 3,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 3}

In [42]:
# 在df中增加一列存放true_rank_metareact
true_rank_metareact = [dict_metareact_sub2truerank[i] for i in substrates_cano]
df['true_rank_metareact'] = true_rank_metareact
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareact
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,5
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...,0,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,0
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...,0,0
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,5
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,0,2
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,0
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,0,0
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,1
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,0
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,3
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,0
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,1
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,0
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,3
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,0,3

4. 整理 metapredictor 的结果

In [47]:
# 找到meta_predictor.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metapredictor_sub2truerank存放
df_metapredictor = pd.read_csv('meta_predictor.csv')
true_rank = []
for i in tqdm(range(len(df_metapredictor))):
    substrate = df_metapredictor.iloc[i,1]
    predicts = df_metapredictor.iloc[i,2]
    try:
        predicts = predicts.split(' ')
        

        # 底物要能对应上
        substrate = canonical_smiles(substrate)
        true_mains_metapredictor = dict_sub2main[substrate]

        # 每个底物只看sygma预测出的top_5
        predicts_top_5 = predicts[:5]
        predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


        for j in range(len(predicts_top_5)):
            predict_top_5 = predicts_top_5[j]
            if predict_top_5 in true_mains_metapredictor:
                true_rank.append(j+1)
        if len(true_rank) < i+1:
            true_rank.append(0)
    except:
        true_rank.append(0)
substrates_metapredictor = df_metapredictor['SMILES'].to_list()
substrates_metapredictor_cano = list(map(canonical_smiles,substrates_metapredictor))
dict_metapredictor_sub2truerank = dict(zip(substrates_metapredictor_cano,true_rank))
dict_metapredictor_sub2truerank

  0%|          | 0/30 [00:00<?, ?it/s]

100%|██████████| 30/30 [00:00<00:00, 326.50it/s]

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 0,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 5,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 4,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 0,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 0,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 0,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 3,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 0,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 4,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 5,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 3,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 0,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 4,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 3,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 0,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 3,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 0}

In [48]:
# 在df中增加一列存放true_rank_metapredictor
true_rank_metapredictor = [dict_metapredictor_sub2truerank[i] for i in substrates_cano]
df['true_rank_metapredictor'] = true_rank_metapredictor
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareact,true_rank_metapredictor
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,5,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,1,5
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,4
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,2,0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...,0,0,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,0,0
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...,0,0,0
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,5,0
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,0,2,0
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,0,0
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,0,0,0
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,1,3
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,0
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,0
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,4
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,0
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,0,0
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,5
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,3,0
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,4
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,3
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,0,0
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,1,0
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,0,3
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,3,0
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,0,3,0

5. 整理 metatrans 的结果

In [52]:
# 找到main_predict_metatrans.csv中每个底物对应的预测值正确的序号true_rank，并建立一个dict_metatrans_sub2truerank存放
df_metatrans = pd.read_csv('main_predict_metatrans.csv')
true_rank = []
for i in tqdm(range(len(df_metatrans))):
    substrate = df_metatrans.iloc[i,1]
    predicts = df_metatrans.iloc[i,2]
    try:
        predicts = predicts.split(' ')
        

        # 底物要能对应上
        substrate = canonical_smiles(substrate)
        true_mains_metatrans = dict_sub2main[substrate]

        # 每个底物只看sygma预测出的top_5
        predicts_top_5 = predicts[:5]
        predicts_top_5 = list(map(canonical_smiles,predicts_top_5))


        for j in range(len(predicts_top_5)):
            predict_top_5 = predicts_top_5[j]
            if predict_top_5 in true_mains_metatrans:
                true_rank.append(j+1)
        if len(true_rank) < i+1:
            true_rank.append(0)
    except:
        true_rank.append(0)
substrates_metatrans = df_metatrans['SMILES'].to_list()
substrates_metatrans_cano = list(map(canonical_smiles,substrates_metatrans))
dict_metatrans_sub2truerank = dict(zip(substrates_metatrans_cano,true_rank))
dict_metatrans_sub2truerank

100%|██████████| 30/30 [00:00<00:00, 256.47it/s]

{'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': 0,
 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': 0,
 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': 1,
 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': 0,
 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': 0,
 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': 0,
 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': 0,
 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': 0,
 'COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)nc3cc(-c4c(C)noc4C)ccc32)CC1': 0,
 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': 0,
 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': 0,
 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': 0,
 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': 1,
 'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': 1,
 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': 0,
 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': 0,
 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': 4,
 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': 0,
 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': 0,
 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': 0,
 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': 0,
 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': 0,
 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': 1,
 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': 0,
 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': 0,
 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': 0,
 'CNC(C)Cc1ccc2c(c1)OCO2': 0,
 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': 0,
 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': 0,
 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': 0}

In [53]:
# 在df中增加一列存放true_rank_metatrans
true_rank_metatrans = [dict_metatrans_sub2truerank[i] for i in substrates_cano]
df['true_rank_metatrans'] = true_rank_metatrans
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareact,true_rank_metapredictor,true_rank_metatrans
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,5,0,0
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,0,0
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,1,5,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,4,0
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,2,0,0
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...,0,0,0,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,0,0
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,0,0,0
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...,0,0,0,0
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,5,0,0
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,0,2,0,0
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,0,0,0
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,0,0,0,1
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,1,3,1
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,0,0
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,0,0
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,4,4
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,0,0
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,0,0,0
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,5,0
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3,0
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,3,0,0
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,4,1
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0,0
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,3,0
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,0,0,0
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,1,0,0
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,0,3,0
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,3,0,0
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,0,3,0,0

6. 整理全部结果

In [57]:
# 将我们的结果也整理进来放在true_rank_ourmodel列
top_ns = df['top_n'].to_list()
true_rank_ourmodel = [int(x) if len(x)==1 else 0 for x in top_ns]
df['true_rank_ourmodel'] = true_rank_ourmodel
df

,name,substrate,predict,top_n,true_mains,true_rank_sygma,true_rank_metareact,true_rank_metapredictor,true_rank_metatrans,true_rank_ourmodel
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H...,0,5,0,0,2
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,[CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(...,5,2,0,0,3
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21],0,1,5,1,1
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],2,1,4,0,1
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12],0,2,0,0,2
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,CN1N=CC(NC2=NC=CC(N3C[C@@H]4CC[C@@H](N4C([C@@H...,[Cn1ncc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C...,0,0,0,0,0
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4...,2,3,0,0,2
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,[Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C...,0,0,0,0,3
8,9,COC1CCC(n2c([C@@]3(C)CCC(=O)N3c3ccc(F)c(F)c3)n...,Cc1noc(C)c1-c1ccc2c(c1)nc([C@@]1(C)CCC(=O)N1c1...,COC1CCC(CC1)N2C([C@]3(CC(O)C(N3C4=CC=C(C(F)=C4...,[COC1CCC(n2c([C@@]3(C)CC(O)C(=O)N3c3ccc(F)c(F)...,0,0,0,0,0
9,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH...,0,5,0,0,2
10,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)...,0,2,0,0,1
11,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,[Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1],0,0,0,0,0
12,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C...,0,0,0,1,4
13,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)...,0,1,3,1,3
14,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1],2,1,0,0,1
15,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@...,2,1,0,0,1
16,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12],5,1,4,4,2
17,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1...,3,1,0,0,2
18,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F...,0,0,0,0,3
19,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=...,3,0,5,0,5
20,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1],0,3,3,0,3
21,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(...,3,3,0,0,1
22,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[CCN(CC)CCc1c[nH]c2cccc(O)c12],2,1,4,1,1
23,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2cc...,0,0,0,0,0
24,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(...,2,1,3,0,1
25,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)c...,0,0,0,0,0
26,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[CC(N)Cc1ccc2c(c1)OCO2],2,1,0,0,1
27,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc...,0,0,3,0,0
28,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@...,0,3,0,0,1
29,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc...,0,3,0,0,4

In [58]:
# 将全部结果导出为 results_mainproduct_top5.csv
df.to_csv('results_mainproduct_top5.csv',index=None)

In [59]:
# 为了保留df中的list，将全部结果导出为 results_mainproduct_top5.parquet
df.to_parquet('results_mainproduct_top5.parquet')