In [127]:
import pandas as pd

In [128]:
from rdkit import Chem
# from neutral import NeutraliseCharges
from multiprocessing import Pool
from rdkit import RDLogger
import pandas as pd
from rdkit.Chem.MolStandardize import rdMolStandardize
RDLogger.DisableLog('rdApp.*')

def canonicalize_smiles(smiles):
    if len(smiles)==0:
        return ''
    mol = Chem.MolFromSmiles(smiles)
    # lfc = MolStandardize.fragment.LargestFragmentChooser()
    
    if mol is not None:
        # mol2 = lfc.choose(mol)
        smi=Chem.MolToSmiles(mol, isomericSmiles=True)
        # smi,_=NeutraliseCharges(smi2)
        return smi 
    else:
        return 'invalid'

In [132]:
truth=pd.read_csv("30_main_true.csv")[['substrate','truth']]

In [133]:
truth

,substrate,truth
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
5,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...
25,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...

In [118]:
eval(truth['true_mains'].iloc[0])[0]

'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2'

In [134]:
truth['substrate']=truth['substrate'].map(canonicalize_smiles)
# truth['substrate']=truth['substrate'].map(canonicalize_smiles)

In [135]:
pred=pd.read_csv("MetaReact_seed8079.csv")

In [136]:
pred['substrate']=pred['substrate'].map(canonicalize_smiles)

In [137]:
df=pd.merge(truth,pred,on='substrate',how="inner")

In [139]:
df

,substrate,truth,name,predict
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...
1,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C...,2,CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC...
2,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21,3,CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21|CC...
3,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,4,CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C...
4,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,5,CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=...
5,Cn1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@...,Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2...,6,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=N...
6,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,7,C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4=...
7,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@...,8,OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C...
8,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]...,10,NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1|O=C(N...
9,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,11,NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC...
10,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1,12,CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=C...
11,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@...,13,COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=CC...
12,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C...
13,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1,15,O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2C...
14,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O,16,OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[C...
15,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12,17,O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12|...
16,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1c...,18,O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)=...
17,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)...,19,C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)...
18,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,20,C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=C...
19,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1,21,CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2...
20,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,22,COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H]...
21,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12,23,CCN(CC)CCC1=CNC2=CC=CC(O)=C12|CCN(CC)CCC1=CNC2...
22,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc...,24,N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(N...
23,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,25,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C...
24,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cc...,26,O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1|NC(...
25,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2,27,CC(N)CC1=CC=C2C(=C1)OCO2|CC(=O)CC1=CC=C2C(=C1)...
26,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(...,28,O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3=...
27,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@]...
28,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3...,30,O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(C...
29,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3c...,31,N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F|O=C...

In [140]:
df.shape

(30, 4)

In [145]:

from rdkit import Chem
from rdkit.DataStructs import TanimotoSimilarity
from rdkit.Chem import AllChem

def get_similarity(smiles1, smiles2):
    mol1 = Chem.MolFromSmiles(smiles1)
    mol2 = Chem.MolFromSmiles(smiles2)
    if mol1 and mol2:
        fp1 = AllChem.GetMorganFingerprintAsBitVect(mol1, 2, nBits=2048)
        fp2 = AllChem.GetMorganFingerprintAsBitVect(mol2, 2, nBits=2048)
        return TanimotoSimilarity(fp1, fp2)
    return 0

top=[1,3,5]#:,3,5]
for top_i in top:
    corr = 0 
    at_least_one, at_least_half, all_metabolites = 0, 0, 0
    len_preds, len_corr_preds, len_actual_metabolites, invalid = 0, 0, 0, 0

    # 定义相似度函数
    def get_similarity(smiles1, smiles2):
        mol1 = Chem.MolFromSmiles(smiles1)
        mol2 = Chem.MolFromSmiles(smiles2)
        if mol1 and mol2:
            fp1 = AllChem.GetMorganFingerprintAsBitVect(mol1, 2, nBits=2048)
            fp2 = AllChem.GetMorganFingerprintAsBitVect(mol2, 2, nBits=2048)
            return TanimotoSimilarity(fp1, fp2)
        return 0

    # 遍历每一行
    for i in range(len(df)):
        substrate = df.iloc[i]['substrate']
        print(substrate)
        # true_metabolites = eval(truth['truth'].iloc[i])
        true_metabolites = df.iloc[i]['truth'].strip().split('|')

        print(true_metabolites)
        original_preds = df.iloc[i]['predict'].strip().split('|')[:top_i]
        print(original_preds)
        # original_preds = df.iloc[i][f"{top}_new"].strip().split('|')
        expanded_preds = []
        for pred in original_preds:
            expanded_preds.extend(pred.split('.'))
        original_preds = expanded_preds
        
        unique_preds = list(set(original_preds))

        original_preds = unique_preds  # 去重后的预测值
        len_preds += len(original_preds)

        corr_preds = []
        preds_to_remove = []
        
        for true_metabolite in true_metabolites:
            for pred in original_preds:
                try:
                    pred = Chem.MolToSmiles(Chem.MolFromSmiles(pred))
                except:
                    print(pred)
                    invalid += 1
                    continue
                if get_similarity(pred, true_metabolite) == 1:
                    corr_preds.append(pred)
                    preds_to_remove.append(pred)
                    break  # 跳出内层循环，防止同一预测值多次计入

        # 移除已匹配的预测值，确保每个预测值只匹配一次
        original_preds = [pred for pred in original_preds if pred not in preds_to_remove]
        
        if len(corr_preds) > 0:
            at_least_one += 1
        if len(corr_preds) >= len(true_metabolites) / 2:
            at_least_half += 1
        if len(corr_preds) == len(true_metabolites):
            all_metabolites += 1

        len_corr_preds += len(corr_preds)
        len_actual_metabolites += len(true_metabolites)

    with open("results.log", 'a') as f:
        f.write(
            ",".join([
                str("top"+str(top_i)), 
                # "{:.2%}".format(at_least_one / len(df)), # at_least_one_metabolite
                # "{:.2%}".format(at_least_half / len(df)), # at_least_half_metabolites
                # "{:.2%}".format(all_metabolites / len(df)), # all_metabolites
                # str(len_corr_preds),  # correct_predictions
                # str(len_preds),  # total_predictions
                # str(len_actual_metabolites),
                # "{:.2%}".format(len_corr_preds / len_preds), # precision
                "{:.2%}".format(len_corr_preds / len_actual_metabolites), # recall
            ]) + "\n"
        )

CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2']
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O']
CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O
['CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O']
['CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O']
CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21
['CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21']
['CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21']
CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
['Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12']
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
['Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1']
Cn1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1
['Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2(F)F)n1']
['O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=NC(NC3=CNN=C3)=N1)C2']
C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C
['C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC']
['C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCN(C)C']
Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1
['Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1']
['OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1']
O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12
['O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]c2ccccc12']
['NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1']
NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1
['NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1']
['NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2CC(=O)N3)CC1']
CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1
['Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1']
['CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=C3)=CC2=C1']
COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1
['COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]5O)CCOCC4)cc3)ccnc2n1']
['COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=CC=NC2=N1']
C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O
['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O']
['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O']
Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1
['O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1']
['O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2Cl)CC1']
COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1
['OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O']
['OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[C@@H]1O']
O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O
['O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12']
['O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12']
CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1
['O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1ccc(CNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)cc1']
['O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)=C1)C1=CC=C(CNC[C@H](O)C2=CC=C(O)C3=C2C=CC(=O)N3)C=C1']
CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1
['CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1']
['C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)F)C(F)=C2)CC1']
CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O
['CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(=O)O']
['C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=CC=C12)NC(=O)CC1=CC=CS1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O']
CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1
['CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1']
['CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2N(C)C1']
COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F
['C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)O[C@@]1(C)C(F)(F)F']
['COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H]2C)C=CC(F)=C1F']
CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12
['CCN(CC)CCc1c[nH]c2cccc(O)c12']
['CCN(CC)CCC1=CNC2=CC=CC(O)=C12']
N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1
['NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc(C(F)(F)F)cc2)c1']
['N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(N)=O)=C2)C1']
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1
['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1)C(=O)O']
['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C(N)=NC=NN23)[C@H](O)[C@@H]1O)OC1=CC=CC=C1)C(=O)O']
O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1
['O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cccc3C2=O)C(=O)N1']
['O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1']
CNC(C)Cc1ccc2c(c1)OCO2
['CC(N)Cc1ccc2c(c1)OCO2']
['CC(N)CC1=CC=C2C(=C1)OCO2']
Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21
['Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21']
['O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3=CC=C(Cl)C=C3)C2)=NO1']
CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O
['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O']
['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@]6(CO)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O']
O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1
['O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)[C@@H](O)[C@@H]1O']
['O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(CC2=CC=CC=C2)CC1']
O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2
['O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)C(O)[C@@H]1O']
['N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F']
CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2']
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O', 'CC(C)(CO)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2', 'CC(C)(C)[C@H](N)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2']
CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O
['CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O']
['CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O', 'CC[C@@H](C(=O)O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O', 'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(O)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O']
CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21
['CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21']
['CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21', 'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)(O)CC21', 'CC(O)CCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21']
CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
['Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12', 'C[C@@H](N)C1=CC=CC2=CC=CC=C12', 'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=C(O)C3=CC=CC=C23)=C1']
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
['Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1', 'CC1=CC(O)=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12', 'CC1=CC=C(O)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12']
Cn1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1
['Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2(F)F)n1']
['O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=NC(NC3=CNN=C3)=N1)C2', 'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=[N+]1C1O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]1O', 'CN1C=C(NC2=NC=C(O)C(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1']
C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C
['C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC']
['C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CNC4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCN(C)C', 'C=CC(=O)NC1=CC(O)=C(OC)C=C1N(C)CCN(C)C', 'C=CC(=O)NC1=CC(NC2=NC=C(C(=O)OC(C)C)C(C3=CN(C)C4=CC=CC=C34)=N2)=C(OC)C=C1N(C)CCNC']
Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1
['Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](OC3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1']
['OCC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1', 'CC1=CC=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1C(O)C1=CC=C(C2=CC=C(F)C=C2)S1', 'CC1=C(O)C=C([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)C=C1CC1=CC=C(C2=CC=C(F)C=C2)S1']
O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12
['O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1cc(=O)[nH]c2ccccc12']
['NC1=C(C(=O)NC2=CC=C(OC(F)(F)F)C=C2)SC=C1', 'O=C(NC1=CC=C(O)C=C1)C1=C(NCC2=CC=NC3=CC=CC=C23)C=CS1', 'O=C(NC1=CC=C(OC(F)(F)F)C=C1)C1=C(NCC2=CC=[N+]([O-])C3=CC=CC=C23)C=CS1']
NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1
['NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1']
['NC1(C(=O)N[C@@H](CCO)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2CC(=O)N3)CC1', 'NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1', 'NC1(C(=O)N[C@@H](CC=O)C2=CC=C(Cl)C=C2)CCN(C2=NC=NC3=C2C=CN3)CC1']
CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1
['Cc1cc(C)c2[nH]c(=O)c(CN3CCOC3=N)cc2c1']
['CC1=CC(C)=C2NC(=O)C(CN(CCO)C(=S)NC3=CC=C(O)C=C3)=CC2=C1', 'CCOC1=CC=C(NC(=S)NCC2=CC3=CC(C)=CC(C)=C3NC2=O)C=C1', 'CCOC1=CC=C(NC(=S)N(CCO)CC2=CC3=CC(CO)=CC(C)=C3NC2=O)C=C1']
COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1
['COc1ccc2c(Oc3ccc(C4(C(=O)NOC5O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]5O)CCOCC4)cc3)ccnc2n1']
['COC1=CC=C2C(OC3=CC=C(C4(C(N)=O)CCOCC4)C=C3)=CC=NC2=N1', 'O=C(NO)C1(C2=CC=C(OC3=CC=NC4=NC(O)=CC=C34)C=C2)CCOCC1', 'COC1=CC=C2C(OC3=CC=C(C4(C(=O)O)CCOCC4)C=C3)=CC=NC2=N1']
C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O
['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O']
['C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(CO)C(O)C(O)C1O', 'C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)O)C(=O)NCC(=O)O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O', 'C/C=C/C#CC#CC(O)C(/C=C/CCC=O)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O']
Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1
['O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1']
['O=S(=O)(C1=CN=C(CO)S1)N1CCC(C2=CN3N=CN=C3C=C2Cl)CC1', 'CC1=NC=C(S(=O)(=O)N2CCC(C3=CN4N=C(O)N=C4C=C3Cl)CC2)S1', 'CC1=NC=C(S(=O)(=O)NCCC(CC=O)C2=CN3N=CN=C3C=C2Cl)S1']
COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1
['OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H]1O']
['OCC1OC(OCCCCC2=CC=C(O)C=C2)[C@H](O)[C@@H](O)[C@@H]1O', 'COC1=CC=C(CCCCOC2OC(COP(=O)(O)O)[C@@H](O)[C@H](O)[C@H]2O)C=C1', 'COC1=CC=C(CCCCO)C=C1']
O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O
['O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(O)c(O)c12']
['O=C1C=C(C2=CC=C(O)C=C2)OC2=CC(O)=C(O)C(O)=C12', 'O=C(O)[C@H]1O[C@H](OC2=CC3=C(C(=O)C=C(C4=CC=C(OS(=O)(=O)O)C=C4)O3)C(O)=C2O)[C@H](O)[C@H](O)[C@H]1O', 'O=C(O)[C@H]1O[C@@H](OC2=CC3=C(C(=O)C=C(C4=CC=C(OS(=O)(=O)O)C=C4)O3)C(O)=C2O)[C@H](O)[C@@H](O)[C@@H]1O']
CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1
['O=C(NCCCOc1cccc([C@](O)(C(=O)O)c2ccccc2)c1)c1ccc(CNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)cc1']
['O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O)C2=CC=CC=C2)=C1)C1=CC=C(CNC[C@H](O)C2=CC=C(O)C3=C2C=CC(=O)N3)C=C1', 'CN1CCC[C@@H](OC(=O)[C@](O)(C2=CC=CC=C2)C2=CC=CC(OCCCNC(=O)C3=CC=C(CN)C=C3)=C2)C1', 'O=C(NCCCOC1=CC=CC([C@](O)(C(=O)O[C@@H]2CCCNC2)C2=CC=CC=C2)=C1)C1=CC=C(CNC[C@H](O)C2=CC=C(O)C3=C2C=CC(=O)N3)C=C1']
CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1
['CC[C@@H](CO)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1']
['C[C@@H](CCO)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)F)C(F)=C2)CC1', 'CC[C@H](C)C(=O)N1CCC(NC(=O)NC2=CC=C(O)C(F)=C2)CC1', 'CC[C@H](C)C(=O)N1CCC(NC(=O)NC2=CC=C(OC(F)(F)F)C(F)=C2)CC1O']
CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O
['CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(=O)O']
['C[C@@](CC1=CC=CC=C1)(NC(=O)[C@H](CC1=CNC2=CC=CC=C12)NC(=O)CC1=CC=CS1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O', 'CN(C(=O)CC1=CC=CS1)[C@@H](CC1=CNC2=CC=CC=C12)C(=O)N[C@@](C)(CC1=CC=CC=C1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)O', 'CN(C(=O)CC1=CC=CS1)[C@@H](CC1=CNC2=CC=C(O)C=C12)C(=O)N[C@@](C)(CC1=CC=CC=C1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O']
CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1
['CCN(CC)C(=O)C1C=C2c3cccc4[nH]cc(c34)CC2N(C)C1']
['CCNC(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2N(C)C1', 'CCN(CC)C(=O)C1C=C2C3=CC=CC4=C3C(=CN4C(=O)C3CC3)CC2NC1', 'CCN(CC)C(=O)C1C=C2C3=CC=CC4=C3C(=CN4)CC2N(C)C1']
COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F
['C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C(N)=O)c2)O[C@@]1(C)C(F)(F)F']
['COC1=C([C@H]2C(C(=O)O)O[C@@](C)(C(F)(F)F)[C@H]2C)C=CC(F)=C1F', 'COC1=C([C@H]2C(C(=O)NC3=CC=NC(C(=O)O)=C3)O[C@@](C)(C(F)(F)F)[C@H]2C)C=CC(F)=C1F', 'C[C@H]1[C@@H](C2=CC=C(F)C(F)=C2O)C(C(=O)NC2=CC=NC(C(N)=O)=C2)O[C@@]1(C)C(F)(F)F']
CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12
['CCN(CC)CCc1c[nH]c2cccc(O)c12']
['CCN(CC)CCC1=CNC2=CC=CC(O)=C12', 'CCN(CC)CCC1=CNC2=CC=C(O)C(OC(C)=O)=C12', 'CCNCCC1=CNC2=CC=CC(OC(C)=O)=C12']
N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1
['NS(=O)(=O)c1cccc(C(=O)N2CCC[C@@H]2C(=O)NCc2ccc(C(F)(F)F)cc2)c1']
['N#CC1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(N)=O)=C2)C1', 'O=C(O)C1CN(S(=O)(=O)C2=CC=CC(C(=O)N3CCC[C@@H]3C(=O)NCC3=CC=C(C(F)(F)F)C=C3)=C2)C1', 'N#CC(CO)CNS(=O)(=O)C1=CC=CC(C(=O)N2CCC[C@@H]2C(=O)NCC2=CC=C(C(F)(F)F)C=C2)=C1']
CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1
['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1)C(=O)O']
['C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C(N)=NC=NN23)[C@H](O)[C@@H]1O)OC1=CC=CC=C1)C(=O)O', 'N#C[C@@]1(C2=CC=C3C(N)=NC=NN23)O[C@H](CO[P@](=O)(O)OC2=CC=CC=C2)[C@@H](O)[C@H]1O', 'CCC(CCO)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(C2=CC=C3C(N)=NC=NN23)[C@H](O)[C@@H]1O)OC1=CC=CC=C1']
O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1
['O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5=O)cc4)cccc3C2=O)C(=O)N1']
['O=C1CC[C@@H](N2CC3=C(O)C=CC=C3C2=O)C(=O)N1', 'NC(=O)[C@@H](CCC(=O)O)N1CC2=C(OCC3=CC=C(CN4CCOCC4)C=C3)C=CC=C2C1=O', 'O=CC1=CC=C(COC2=CC=CC3=C2CN([C@@H]2CCC(=O)NC2=O)C3=O)C=C1']
CNC(C)Cc1ccc2c(c1)OCO2
['CC(N)Cc1ccc2c(c1)OCO2']
['CC(N)CC1=CC=C2C(=C1)OCO2', 'CC(=O)CC1=CC=C2C(=C1)OCO2', 'C[C@@H](N)CC1=CC=C2C(=C1)OCO2']
Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21
['Cn1cnc2[nH]c(=O)n(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21']
['O=C1C2=C(N=CN2)N=CN1CC1=NC([C@@H]2CO[C@@H](C3=CC=C(Cl)C=C3)C2)=NO1', 'O=CC1=NC([C@@H]2CO[C@@H](C3=CC=C(Cl)C=C3)C2)=NO1', 'CN1C=NC2=C1C(=O)N(CC(O)=NC(=N)[C@@H]1CO[C@@H](C3=CC=C(Cl)C=C3)C1)C=N2']
CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O
['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O']
['CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@]6(CO)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O', 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1O', 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O']
O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1
['O=C(O)[C@H]1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)[C@@H](O)[C@@H]1O']
['O=C(C1=CC=CN=C1C1=CC=[N+]([O-])C=C1)N1CCC(O)(CC2=CC=CC=C2)CC1', 'O=C(C1=CC=CN=C1C1=CC=NC=C1)N1CCC(O)(CC2=CC=C(O)C=C2)CC1', 'O=C(O)[C@H]1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=C3C3=CC=NC=C3)CC2)[C@H](O)[C@@H](O)[C@@H]1O']
O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2
['O=C(O)C1OC(OC2(Cc3ccccc3)CCN(C(=O)c3cccnc3-c3ccncc3)CC2)[C@H](O)C(O)[C@@H]1O']
['N=C(CC1(O)CCN(C(=O)CCC(F)(F)F)CC1)C(F)(F)F', 'O=C(CCC(F)(F)F)N1CCC2(CC1)ON=C(C(F)(F)F)C2O', 'O=C(CCC(F)(F)F)N1CCC2(CC(C(F)(F)F)=NO2)CC1O']
CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2']
['CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2=O', 'CC(C)(CO)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2', 'CC(C)(C)[C@H](N)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2', 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CC(O)NC1=O)SCCS2', 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)O)SCCS2']
CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O
['CC[C@@H](C(=O)O)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O']
['CC[C@@H](C(=O)NC1=CC=C(C(=O)O)C(F)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O', 'CC[C@@H](C(=O)O)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O', 'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(O)=C1)N1C=C(OC)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O', 'COC1=CN([C@@H](CCO)C(=O)NC2=CC=C(C(N)=O)C(F)=C2)C(=O)C=C1C1=CC(Cl)=CC=C1N1C=C(C(F)(F)F)N=N1', 'CC[C@@H](C(=O)NC1=CC=C(C(N)=O)C(F)=C1)N1C=C(O)C(C2=CC(Cl)=CC=C2N2C=C(C(F)(F)F)N=N2)=CC1=O']
CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21
['CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21']
['CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(CO)CC21', 'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)(O)CC21', 'CC(O)CCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21', 'CCCCCC1=CC(OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C2C(=C1)OC(C)(C)C1CCC(C)CC21', 'CCCCCC1=CC(O)=C2C(=C1)OC(C)(C)C1CC(O)C(C)CC21']
CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1
['Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12', 'C[C@@H](N)C1=CC=CC2=CC=CC=C12', 'CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=C(O)C3=CC=CC=C23)=C1', 'CC(=O)NC1=CC=C(C)C(/C(=N/[C@H](C)C2=CC=CC3=CC=CC=C23)OC2O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]2O)=C1', 'CC(=O)NC1=CC=C(C)C(C(N)=O)=C1']
Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12
['Cc1cc(O)c(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12']
['CC(=O)NC1=CC=C(C)C(C(=O)N[C@H](C)C2=CC=CC3=CC=CC=C23)=C1', 'CC1=CC(O)=C(N)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12', 'CC1=CC=C(O)C=C1C(=O)N[C@H](C)C1=CC=CC2=CC=CC=C12', 'CC1=CC=C(N)C=C1C(=O)N[C@H](C)C1=CC=C(O)C2=CC=CC=C12', 'CC(=O)C1=CC=CC2=CC=CC=C12']
Cn1cc(Nc2nccc(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1
['Nc1nccc(N2C[C@H]3CC[C@@H](C2)N3C(=O)[C@@H]2CC2(F)F)n1']
['O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(C1=CC=NC(NC3=CNN=C3)=N1)C2', 'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=[N+]1C1O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]1O', 'CN1C=C(NC2=NC=C(O)C(N3C[C@@H]4CC[C@H](C3)N4C(=O)[C@@H]3CC3(F)F)=N2)C=N1', 'CN1C=C(NC2=NC=CC(N3C[C@@H]4CC[C@H](C3)N4)=N2)C=N1', 'NC1=NC=CC(N2C[C@@H]3CC[C@H](C2)N3C(=O)[C@@H]2CC2(F)F)=N1']
C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C
['C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCNC']