1. metareact

In [21]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

def df_col_getatomindices(dfname,col_old,flat=False):
    preds = dfname[col_old].to_list()
    preds = [i.split('|') for i in preds]
    try:
        preds = [list(map(standardize_smiles_with_atom_map,i)) for i in preds]
        ranks = [list(map(get_reactive_atom_indices,i)) for i in preds]
    except:
        ranks = []
        for k in preds:
            preds_part = []
            for x in k:
                try:
                    x = standardize_smiles_with_atom_map(x)
                    x_new = get_reactive_atom_indices(x)
                except:
                    x_new = []
                preds_part.append(x_new)
            ranks.append(preds_part)
    if flat == True:
        ranks_new = []
        for i in ranks:
            list_part = []
            for j in i:
                list_part = list_part + j
            ranks_new.append(list_part)
        return ranks_new
    else:
        return ranks
    
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [22]:
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

In [23]:
df = pd.read_csv('pred_results_metatrans_has_cyp_enzyme.csv')
site_truth = df_col_getatomindices(df,'site_truth',flat=True) 
predict_site = df_col_getatomindices(df,'predict_site') 
df['site_truth_atomidx'] = site_truth
df['predict_site_atomidx'] = predict_site
df['sub_enz'] = df['substrate']+'|' + df['Enzyme']
df

[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger

[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:30] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger
[11:30:31] Running Uncharger

,Unnamed: 0,substrate,Enzyme,truth,site_truth,predict_site,site_truth_atomidx,predict_site_atomidx,sub_enz
0,0,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP1A2,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[32],"[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
1,1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP2C9,CC(C)(O)c1cc(O)ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,"[6, 32, 10, 40]","[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
2,2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP2D6,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[32],"[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
3,3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP3A4,CC(C)(O)c1cc(O)ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,"[6, 32, 10, 40]","[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
4,4,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CYP2D6,CC(C)C=O|CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CC[CH2:1]C2)...,CC(C)C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)c...,"[22, 5, 6, 7, 23, 25]","[[4], [1], [25], [4], [23], [5], [22], [19, 23...",CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CY...
...,...,...,...,...,...,...,...,...,...
69,69,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,CYP1A2,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1|O=C1CN=...,[18],"[[18], [15], [10, 17, 18], [16], [8], [3, 4], ...",O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP1A2
70,70,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,CYP3A4,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1|O=C1CN=...,[18],"[[18], [15], [10, 17, 18], [16], [8], [3, 4], ...",O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP3A4
71,71,O=P1(NCCCl)OCCCN1CCCl,CYP2C9,NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1([NH:1]CCCl)OC...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1([NH:1]CCCl)OCCC...,"[9, 2]","[[10], [2], [9], [10], [9], [8], [1, 12, 13], ...",O=P1(NCCCl)OCCCN1CCCl|CYP2C9
72,72,O=P1(NCCCl)OCCCN1CCCl,CYP3A4,NP1(=O)OCCCN1CCCl|N[P@@]1(=O)OCCCN1CCCl|O=P1(N...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1(NCCCl)OCC[CH2:1...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1([NH:1]CCCl)OCCC...,"[10, 9, 2]","[[10], [2], [9], [10], [9], [8], [1, 12, 13], ...",O=P1(NCCCl)OCCCN1CCCl|CYP3A4
73,73,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,CYP3A4,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOCC[N:1]1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|OC...,[1],"[[6], [3, 5, 10], [3], [9], [18, 20, 21], [20,...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP3A4

In [24]:
df.to_pickle('./predict_site_65_has_enzyme.pickle')

2. smartcyp

In [25]:
df_smartcyp = pd.read_pickle('/home/datahouse1/wangyitian/MetaPred/30_main_products/save_code/65/smartcyp_results.pickle')
substrates = df_smartcyp['substrates'].to_list()
substrates = list(map(canonicalsmiles,substrates))
df_smartcyp['substrates'] = substrates
df_smartcyp['sub_enz'] = df_smartcyp['substrates'] + '|CYP' + df_smartcyp['enzyme']
df_smartcyp

,substrates,enzyme,scores,sub_enz
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,3A4,"{0: 17, 1: 22, 2: 24, 3: 23, 4: 20, 5: 3, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...
1,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2D6,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...
2,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2C9,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,3A4,"{0: 23, 1: 28, 2: 23, 3: 25, 4: 30, 5: 19, 6: ...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,2D6,"{0: 8, 1: 28, 2: 8, 3: 25, 4: 30, 5: 14, 6: 6,...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...
...,...,...,...,...
190,O=P1(NCCCl)OCCCN1CCCl,2D6,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ...",O=P1(NCCCl)OCCCN1CCCl|CYP2D6
191,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ...",O=P1(NCCCl)OCCCN1CCCl|CYP2C9
192,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,3A4,"{0: 15, 1: 7, 2: 8, 3: 17, 4: 9, 5: 1, 6: 5, 7...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP3A4
193,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2D6,"{0: 15, 1: 1, 2: 2, 3: 17, 4: 10, 5: 4, 6: 11,...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2D6
194,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2C9,"{0: 15, 1: 5, 2: 6, 3: 17, 4: 9, 5: 2, 6: 7, 7...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2C9

In [26]:
scores_smartcyp = df_smartcyp['scores'].to_list()
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in scores_smartcyp]
df_smartcyp['rank'] = smartcyp_sorted_atoms
df_smartcyp

,substrates,enzyme,scores,sub_enz,rank
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,3A4,"{0: 17, 1: 22, 2: 24, 3: 23, 4: 20, 5: 3, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"[12, 20, 5, 18, 7, 25, 19, 8, 23, 11, 9, 22, 2..."
1,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2D6,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"[5, 18, 12, 20, 7, 25, 14, 26, 19, 8, 11, 22, ..."
2,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,2C9,"{0: 18, 1: 22, 2: 24, 3: 23, 4: 20, 5: 1, 6: 1...",C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,"[5, 12, 18, 20, 7, 25, 14, 19, 8, 11, 22, 23, ..."
3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,3A4,"{0: 23, 1: 28, 2: 23, 3: 25, 4: 30, 5: 19, 6: ...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[13, 14, 12, 16, 34, 10, 28, 27, 20, 21, 39, 3..."
4,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,2D6,"{0: 8, 1: 28, 2: 8, 3: 25, 4: 30, 5: 14, 6: 6,...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[13, 34, 16, 14, 12, 6, 33, 0, 2, 20, 21, 37, ..."
...,...,...,...,...,...
190,O=P1(NCCCl)OCCCN1CCCl,2D6,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ...",O=P1(NCCCl)OCCCN1CCCl|CYP2D6,"[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]"
191,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 10, 1: 11, 2: 5, 3: 2, 4: 8, 6: 10, 7: 6, ...",O=P1(NCCCl)OCCCN1CCCl|CYP2C9,"[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]"
192,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,3A4,"{0: 15, 1: 7, 2: 8, 3: 17, 4: 9, 5: 1, 6: 5, 7...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP3A4,"[5, 10, 7, 25, 8, 24, 6, 9, 1, 2, 4, 19, 22, 1..."
193,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2D6,"{0: 15, 1: 1, 2: 2, 3: 17, 4: 10, 5: 4, 6: 11,...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2D6,"[1, 2, 14, 5, 10, 19, 22, 13, 15, 7, 25, 8, 24..."
194,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,2C9,"{0: 15, 1: 5, 2: 6, 3: 17, 4: 9, 5: 2, 6: 7, 7...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2C9,"[7, 25, 5, 8, 24, 10, 1, 2, 6, 9, 4, 14, 19, 2..."

In [27]:
dict_smartcyp_sub2rank = dict(zip(df_smartcyp['sub_enz'].to_list(),smartcyp_sorted_atoms))
dict_smartcyp_sub2rank

{'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC|CYP3A4': [12,
  20,
  5,
  18,
  7,
  25,
  19,
  8,
  23,
  11,
  9,
  22,
  21,
  10,
  14,
  26,
  0,
  16,
  6,
  17,
  4,
  15,
  1,
  3,
  2,
  13,
  24],
 'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC|CYP2D6': [5,
  18,
  12,
  20,
  7,
  25,
  14,
  26,
  19,
  8,
  11,
  22,
  23,
  21,
  10,
  9,
  6,
  17,
  0,
  16,
  4,
  15,
  1,
  3,
  2,
  13,
  24],
 'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC|CYP2C9': [5,
  12,
  18,
  20,
  7,
  25,
  14,
  19,
  8,
  11,
  22,
  23,
  21,
  10,
  9,
  26,
  6,
  17,
  0,
  16,
  4,
  15,
  1,
  3,
  2,
  13,
  24],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1|CYP3A4': [13,
  14,
  12,
  16,
  34,
  10,
  28,
  27,
  20,
  21,
  39,
  37,
  11,
  33,
  23,
  25,
  40,
  6,
  7,
  5,
  8,
  31,
  30,
  0,
  2,
  24,
  3,
  18,
  19,
  17,
  35,
  1,
  32,
  4,
  38,
  9,
  15,
  29,
  22,
  26],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1|CYP2D6': [13,
  34,
  16,
  14,
  12,
  6,
  33,
  0,
  2,
  20,
  21,
  37,
  28,
  27,
  7,
  5,
  10,
  8,
  39,
  11,
  31,
  25,
  23,
  40,
  24,
  30,
  3,
  18,
  19,
  17,
  35,
  1,
  32,
  4,
  38,
  9,
  15,
  29,
  26,
  22],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1|CYP2C9': [13,
  34,
  6,
  33,
  0,
  2,
  37,
  28,
  27,
  10,
  7,
  5,
  12,
  8,
  39,
  31,
  25,
  23,
  40,
  14,
  11,
  24,
  30,
  20,
  21,
  16,
  3,
  35,
  1,
  32,
  4,
  38,
  9,
  29,
  26,
  22,
  19,
  17,
  15,
  18],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CYP3A4': [3,
  5,
  4,
  20,
  23,
  21,
  22,
  1,
  13,
  11,
  8,
  24,
  12,
  0,
  2,
  7,
  25,
  14,
  19,
  17,
  18,
  16,
  15,
  6,
  10,
  9],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CYP2D6': [21,
  22,
  20,
  23,
  13,
  3,
  12,
  19,
  14,
  11,
  5,
  0,
  2,
  1,
  4,
  8,
  24,
  7,
  25,
  17,
  18,
  16,
  15,
  10,
  9,
  6],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CYP2C9': [3,
  5,
  4,
  1,
  0,
  2,
  21,
  22,
  20,
  23,
  13,
  12,
  7,
  25,
  8,
  24,
  11,
  14,
  19,
  6,
  9,
  17,
  18,
  10,
  16,
  15],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP3A4': [18,
  19,
  1,
  10,
  2,
  7,
  13,
  6,
  14,
  8,
  12,
  5,
  15,
  0,
  3,
  17,
  9,
  11,
  4,
  16],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP2D6': [10,
  7,
  13,
  18,
  19,
  6,
  14,
  8,
  12,
  1,
  5,
  15,
  2,
  0,
  3,
  17,
  9,
  11,
  4,
  16],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP2C9': [18,
  19,
  10,
  1,
  7,
  13,
  6,
  14,
  2,
  8,
  12,
  0,
  5,
  15,
  3,
  17,
  9,
  11,
  4,
  16],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1|CYP3A4': [12,
  49,
  26,
  6,
  9,
  50,
  7,
  45,
  25,
  4,
  23,
  29,
  31,
  8,
  51,
  60,
  10,
  46,
  28,
  32,
  3,
  48,
  27,
  42,
  41,
  54,
  59,
  22,
  37,
  55,
  58,
  13,
  0,
  2,
  17,
  30,
  56,
  1,
  53,
  44,
  52,
  35,
  36,
  24,
  34,
  5,
  33,
  43,
  21,
  47,
  19,
  20,
  18,
  16,
  40,
  11,
  15,
  14,
  39,
  38],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1|CYP2D6': [26,
  29,
  31,
  45,
  25,
  12,
  49,
  23,
  28,
  32,
  46,
  27,
  48,
  42,
  41,
  22,
  9,
  50,
  37,
  55,
  58,
  0,
  2,
  6,
  17,
  60,
  4,
  54,
  59,
  13,
  7,
  10,
  3,
  8,
  51,
  30,
  56,
  44,
  43,
  47,
  24,
  33,
  40,
  34,
  15,
  21,
  35,
  36,
  18,
  19,
  20,
  16,
  14,
  39,
  1,
  38,
  53,
  11,
  52,
  5],
 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1|CYP2C9': [9,
  50,
  26,
  6,
  7,
  29,
  31,
  12,
  49,
  45,
  25,
  8,
  51,
  4,
  28,
  32,
  10,
  60,
  46,
  27,
  23,
  55,
  58,
  48,
  54,
  59,
  3,
  42,
  0,
  2,
  41,
  13,
  22,
  37,
  17,
  30,
  56,
  1,
  44,
  43,
  47,
  53,
  52,
  5,
  35,
  36,
  24,
  40,
  34,
  11,
  33,
  39,
  38,
  21,
  14,
  19,
  20,
  16,
  15,
  18],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O|CYP3A4': [9,
  3,
  10,
  4,
  5,
  21,
  13,
  16,
  12,
  17,
  0,
  2,
  20,
  6,
  15,
  23,
  24,
  14,
  22,
  1,
  19,
  18,
  11,
  8,
  7],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O|CYP2D6': [3,
  21,
  0,
  2,
  4,
  9,
  13,
  16,
  5,
  20,
  10,
  12,
  17,
  6,
  23,
  24,
  22,
  15,
  1,
  14,
  19,
  18,
  8,
  7,
  11],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O|CYP2C9': [9,
  10,
  3,
  13,
  16,
  12,
  17,
  4,
  5,
  21,
  0,
  2,
  6,
  20,
  15,
  14,
  11,
  8,
  7,
  19,
  24,
  1,
  18,
  22,
  23],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP3A4': [1,
  6,
  5,
  7,
  4,
  8,
  0,
  11,
  14,
  13,
  12,
  10,
  16,
  9,
  15,
  3,
  2],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP2D6': [6,
  5,
  7,
  1,
  4,
  8,
  0,
  11,
  14,
  13,
  12,
  10,
  16,
  9,
  15,
  3,
  2],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP2C9': [6,
  5,
  7,
  4,
  8,
  1,
  0,
  11,
  14,
  3,
  10,
  16,
  12,
  9,
  15,
  13,
  2],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP3A4': [2,
  10,
  7,
  1,
  5,
  14,
  21,
  6,
  8,
  0,
  18,
  17,
  4,
  15,
  19,
  3,
  9,
  13,
  12,
  11],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP2D6': [7,
  2,
  6,
  5,
  1,
  10,
  0,
  8,
  14,
  21,
  18,
  17,
  4,
  15,
  19,
  3,
  9,
  13,
  11,
  12],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP2C9': [7,
  2,
  6,
  5,
  1,
  10,
  0,
  8,
  14,
  21,
  18,
  17,
  4,
  15,
  19,
  3,
  9,
  13,
  11,
  12],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1|CYP3A4': [15,
  16,
  18,
  12,
  7,
  1,
  2,
  3,
  13,
  4,
  5,
  6,
  0,
  10,
  20,
  9,
  21,
  17,
  19,
  14,
  11,
  8],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1|CYP2D6': [1,
  0,
  2,
  7,
  3,
  4,
  5,
  6,
  16,
  18,
  15,
  9,
  21,
  12,
  10,
  20,
  13,
  8,
  17,
  19,
  11,
  14],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1|CYP2C9': [15,
  16,
  18,
  1,
  2,
  0,
  7,
  12,
  3,
  13,
  4,
  5,
  6,
  10,
  20,
  9,
  21,
  17,
  19,
  14,
  11,
  8],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1|CYP3A4': [3,
  4,
  39,
  6,
  41,
  37,
  36,
  34,
  33,
  31,
  30,
  28,
  27,
  13,
  15,
  25,
  16,
  24,
  18,
  22,
  19,
  21,
  1,
  2,
  12,
  7,
  40,
  0,
  38,
  5,
  35,
  32,
  8,
  9,
  10,
  11,
  29,
  14,
  26,
  17,
  23,
  20],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1|CYP2D6': [39,
  3,
  37,
  4,
  36,
  1,
  6,
  41,
  0,
  34,
  33,
  31,
  30,
  28,
  27,
  15,
  25,
  16,
  24,
  13,
  18,
  22,
  19,
  21,
  2,
  12,
  7,
  40,
  38,
  5,
  9,
  8,
  35,
  32,
  10,
  11,
  29,
  14,
  26,
  17,
  23,
  20],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1|CYP2C9': [3,
  39,
  37,
  4,
  36,
  1,
  6,
  41,
  34,
  33,
  31,
  30,
  28,
  27,
  15,
  25,
  16,
  24,
  13,
  18,
  22,
  19,
  21,
  2,
  0,
  12,
  7,
  40,
  38,
  5,
  9,
  8,
  35,
  32,
  10,
  11,
  29,
  14,
  26,
  17,
  23,
  20],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1|CYP3A4': [24,
  26,
  22,
  3,
  21,
  10,
  1,
  2,
  8,
  9,
  7,
  16,
  30,
  0,
  25,
  27,
  23,
  6,
  5,
  11,
  4,
  12,
  14,
  20,
  19,
  13,
  15,
  17,
  28],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1|CYP2D6': [3,
  1,
  8,
  0,
  2,
  9,
  7,
  10,
  24,
  26,
  22,
  16,
  30,
  25,
  27,
  21,
  23,
  6,
  5,
  11,
  4,
  12,
  13,
  14,
  15,
  17,
  28,
  19,
  20],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1|CYP2C9': [24,
  26,
  22,
  3,
  1,
  8,
  21,
  2,
  0,
  25,
  27,
  10,
  9,
  7,
  16,
  30,
  23,
  6,
  5,
  11,
  19,
  4,
  15,
  12,
  17,
  28,
  13,
  14,
  20],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1|CYP3A4': [3,
  8,
  7,
  2,
  28,
  27,
  30,
  25,
  32,
  23,
  10,
  9,
  1,
  24,
  35,
  5,
  13,
  12,
  18,
  0,
  21,
  20,
  22,
  29,
  14,
  16,
  26,
  31,
  11,
  33,
  34,
  6,
  4,
  19],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1|CYP2D6': [3,
  8,
  28,
  27,
  7,
  2,
  30,
  32,
  25,
  23,
  10,
  13,
  9,
  1,
  24,
  35,
  5,
  12,
  18,
  0,
  20,
  21,
  22,
  29,
  14,
  16,
  26,
  31,
  19,
  34,
  6,
  4,
  11,
  33],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1|CYP2C9': [3,
  8,
  28,
  27,
  7,
  2,
  30,
  32,
  25,
  23,
  10,
  13,
  9,
  1,
  24,
  35,
  5,
  12,
  18,
  0,
  20,
  21,
  22,
  29,
  14,
  16,
  26,
  31,
  19,
  34,
  6,
  4,
  11,
  33],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1|CYP3A4': [16,
  25,
  26,
  5,
  24,
  17,
  15,
  18,
  20,
  22,
  13,
  9,
  1,
  2,
  4,
  3,
  10,
  0,
  11,
  8,
  19,
  21,
  23,
  14,
  7,
  6],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1|CYP2D6': [16,
  17,
  18,
  15,
  20,
  22,
  25,
  26,
  5,
  0,
  1,
  13,
  9,
  11,
  2,
  10,
  24,
  3,
  4,
  8,
  19,
  21,
  23,
  14,
  7,
  6],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1|CYP2C9': [16,
  25,
  26,
  17,
  5,
  24,
  18,
  15,
  20,
  22,
  1,
  13,
  2,
  0,
  9,
  3,
  4,
  10,
  11,
  8,
  19,
  21,
  23,
  14,
  6,
  7],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP3A4': [1,
  3,
  5,
  15,
  16,
  19,
  6,
  11,
  0,
  4,
  7,
  2,
  14,
  12,
  18,
  17,
  10,
  9,
  8],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP2D6': [15,
  19,
  16,
  1,
  3,
  5,
  11,
  0,
  4,
  6,
  7,
  2,
  14,
  12,
  18,
  17,
  10,
  9,
  8],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP2C9': [1,
  3,
  15,
  5,
  19,
  16,
  6,
  0,
  4,
  11,
  7,
  2,
  14,
  12,
  18,
  17,
  8,
  10,
  9],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1|CYP3A4': [1,
  3,
  5,
  14,
  12,
  15,
  6,
  11,
  16,
  0,
  4,
  2,
  13,
  10,
  9,
  8,
  7],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1|CYP2D6': [14,
  12,
  15,
  1,
  3,
  5,
  11,
  16,
  0,
  4,
  6,
  2,
  13,
  10,
  9,
  8,
  7],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1|CYP2C9': [1,
  3,
  14,
  5,
  12,
  15,
  0,
  4,
  11,
  16,
  6,
  2,
  13,
  8,
  10,
  9,
  7],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1|CYP3A4': [12,
  16,
  10,
  1,
  36,
  11,
  13,
  15,
  4,
  38,
  40,
  19,
  30,
  27,
  24,
  2,
  35,
  31,
  37,
  41,
  7,
  18,
  28,
  8,
  17,
  0,
  23,
  14,
  29,
  33,
  32,
  26,
  39,
  25,
  9,
  22,
  21,
  34,
  6,
  20,
  3,
  5],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1|CYP2D6': [30,
  1,
  36,
  27,
  38,
  40,
  31,
  24,
  2,
  35,
  19,
  4,
  28,
  12,
  16,
  37,
  41,
  13,
  15,
  10,
  0,
  23,
  11,
  7,
  18,
  8,
  17,
  29,
  33,
  32,
  26,
  39,
  21,
  25,
  34,
  20,
  3,
  22,
  14,
  5,
  6,
  9],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1|CYP2C9': [12,
  16,
  11,
  10,
  1,
  30,
  36,
  13,
  15,
  27,
  19,
  4,
  38,
  40,
  31,
  24,
  2,
  35,
  28,
  37,
  41,
  7,
  18,
  8,
  17,
  0,
  23,
  14,
  29,
  33,
  32,
  26,
  39,
  9,
  21,
  25,
  6,
  34,
  5,
  20,
  3,
  22],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP3A4': [1,
  3,
  2,
  11,
  4,
  5,
  17,
  0,
  6,
  14,
  15,
  16,
  13,
  8,
  9,
  12,
  7,
  10,
  18],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP2D6': [1,
  14,
  3,
  11,
  2,
  6,
  5,
  0,
  4,
  17,
  15,
  16,
  13,
  8,
  9,
  12,
  7,
  10,
  18],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP2C9': [1,
  3,
  2,
  0,
  4,
  5,
  6,
  11,
  17,
  14,
  8,
  9,
  7,
  15,
  16,
  10,
  12,
  18,
  13],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2|CYP3A4': [17,
  19,
  15,
  27,
  28,
  1,
  24,
  23,
  25,
  0,
  18,
  20,
  22,
  7,
  8,
  11,
  5,
  12,
  16,
  2,
  4,
  3,
  26,
  14,
  21,
  13,
  6,
  9,
  10],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2|CYP2D6': [1,
  0,
  17,
  19,
  24,
  27,
  28,
  15,
  23,
  25,
  7,
  5,
  22,
  8,
  18,
  20,
  11,
  12,
  16,
  2,
  4,
  3,
  6,
  26,
  9,
  21,
  10,
  14,
  13],
 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2|CYP2C9': [17,
  19,
  15,
  1,
  27,
  0,
  18,
  20,
  28,
  24,
  23,
  25,
  22,
  7,
  8,
  11,
  5,
  12,
  16,
  2,
  4,
  3,
  26,
  14,
  6,
  21,
  13,
  9,
  10],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12|CYP3A4': [8,
  26,
  27,
  24,
  7,
  16,
  18,
  12,
  1,
  10,
  14,
  11,
  13,
  0,
  15,
  25,
  22,
  21,
  19,
  9,
  23,
  2,
  4,
  17,
  3,
  28,
  5,
  6],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12|CYP2D6': [8,
  12,
  26,
  27,
  10,
  14,
  11,
  13,
  0,
  1,
  7,
  24,
  16,
  18,
  15,
  25,
  9,
  2,
  4,
  22,
  19,
  21,
  3,
  6,
  17,
  5,
  28,
  23],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12|CYP2C9': [26,
  27,
  24,
  8,
  12,
  7,
  18,
  16,
  1,
  10,
  14,
  11,
  13,
  0,
  15,
  25,
  22,
  21,
  19,
  9,
  23,
  2,
  4,
  17,
  3,
  28,
  5,
  6],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP3A4': [24,
  23,
  9,
  21,
  0,
  2,
  5,
  18,
  26,
  12,
  27,
  19,
  25,
  11,
  28,
  1,
  22,
  4,
  3,
  20,
  6,
  8,
  7,
  17,
  16,
  15,
  10,
  14,
  13],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP2D6': [0,
  2,
  9,
  24,
  23,
  5,
  1,
  12,
  27,
  11,
  28,
  21,
  18,
  26,
  19,
  25,
  4,
  3,
  7,
  13,
  10,
  6,
  8,
  16,
  14,
  15,
  17,
  22,
  20],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP2C9': [24,
  23,
  0,
  2,
  21,
  9,
  5,
  1,
  12,
  27,
  18,
  26,
  11,
  28,
  19,
  25,
  22,
  4,
  3,
  20,
  7,
  15,
  13,
  17,
  10,
  6,
  8,
  16,
  14],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21|CYP3A4': [0,
  2,
  3,
  13,
  14,
  5,
  10,
  17,
  4,
  9,
  18,
  11,
  16,
  8,
  19,
  6,
  1,
  12,
  15,
  7,
  20],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21|CYP2D6': [10,
  17,
  13,
  14,
  0,
  2,
  9,
  18,
  11,
  16,
  3,
  8,
  19,
  5,
  4,
  6,
  1,
  12,
  15,
  7,
  20],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21|CYP2C9': [0,
  2,
  3,
  10,
  17,
  13,
  14,
  5,
  9,
  18,
  11,
  16,
  4,
  8,
  19,
  6,
  1,
  12,
  15,
  7,
  20],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O|CYP3A4': [0,
  2,
  16,
  17,
  14,
  4,
  1,
  10,
  11,
  5,
  13,
  12,
  22,
  15,
  23,
  21,
  20,
  3,
  7,
  19,
  25,
  6,
  18,
  9,
  24,
  27,
  8,
  29,
  32,
  26,
  31,
  28,
  30],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O|CYP2D6': [0,
  2,
  4,
  1,
  5,
  16,
  17,
  22,
  10,
  14,
  11,
  12,
  13,
  15,
  7,
  6,
  3,
  23,
  21,
  9,
  8,
  25,
  32,
  31,
  24,
  20,
  30,
  27,
  19,
  29,
  28,
  18,
  26],
 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O|CYP2C9': [0,
  2,
  16,
  17,
  4,
  1,
  14,
  22,
  5,
  10,
  11,
  12,
  13,
  15,
  23,
  21,
  3,
  7,
  19,
  6,
  9,
  18,
  20,
  8,
  25,
  32,
  31,
  24,
  30,
  27,
  29,
  28,
  26],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3|CYP3A4': [0,
  2,
  10,
  1,
  3,
  11,
  13,
  14,
  5,
  7,
  6,
  16,
  15,
  18,
  4,
  17,
  9,
  12,
  19,
  8],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3|CYP2D6': [0,
  2,
  10,
  1,
  14,
  3,
  5,
  13,
  6,
  11,
  7,
  16,
  15,
  18,
  17,
  4,
  19,
  12,
  9,
  8],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3|CYP2C9': [0,
  2,
  1,
  10,
  3,
  14,
  11,
  13,
  5,
  6,
  7,
  16,
  15,
  18,
  4,
  17,
  9,
  12,
  19,
  8],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21|CYP3A4': [0,
  5,
  3,
  12,
  22,
  1,
  17,
  18,
  20,
  19,
  11,
  4,
  6,
  10,
  16,
  21,
  7,
  9,
  15,
  8,
  2,
  13,
  14],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21|CYP2D6': [5,
  0,
  3,
  18,
  17,
  19,
  12,
  20,
  4,
  22,
  6,
  1,
  11,
  10,
  16,
  21,
  7,
  9,
  15,
  8,
  2,
  13,
  14],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21|CYP2C9': [0,
  5,
  3,
  18,
  17,
  19,
  12,
  20,
  22,
  4,
  6,
  1,
  11,
  10,
  16,
  21,
  7,
  9,
  15,
  8,
  2,
  13,
  14],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP3A4': [10,
  0,
  17,
  16,
  27,
  6,
  23,
  13,
  8,
  12,
  7,
  5,
  21,
  20,
  19,
  1,
  22,
  24,
  3,
  2,
  18,
  4,
  9,
  25,
  15,
  11,
  14,
  26],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP2D6': [0,
  10,
  6,
  21,
  23,
  17,
  20,
  16,
  7,
  5,
  27,
  1,
  8,
  22,
  19,
  13,
  12,
  24,
  3,
  2,
  18,
  4,
  25,
  26,
  14,
  15,
  11,
  9],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP2C9': [0,
  10,
  6,
  21,
  23,
  17,
  16,
  20,
  27,
  7,
  5,
  8,
  1,
  22,
  13,
  19,
  12,
  24,
  3,
  2,
  18,
  4,
  25,
  26,
  14,
  15,
  11,
  9],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1|CYP3A4': [0,
  2,
  1,
  12,
  4,
  9,
  3,
  7,
  16,
  8,
  15,
  17,
  10,
  14,
  18,
  11,
  6,
  13,
  5],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1|CYP2D6': [9,
  12,
  0,
  16,
  8,
  10,
  2,
  7,
  15,
  17,
  1,
  14,
  18,
  4,
  3,
  11,
  6,
  13,
  5],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1|CYP2C9': [0,
  2,
  1,
  12,
  9,
  16,
  4,
  7,
  8,
  15,
  17,
  10,
  3,
  14,
  18,
  11,
  6,
  13,
  5],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|CYP3A4': [0,
  2,
  1,
  4,
  21,
  9,
  23,
  7,
  8,
  10,
  19,
  18,
  20,
  22,
  13,
  11,
  3,
  17,
  6,
  15,
  16,
  5,
  14],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|CYP2D6': [9,
  21,
  0,
  20,
  19,
  8,
  10,
  2,
  18,
  7,
  22,
  1,
  4,
  23,
  13,
  11,
  17,
  15,
  16,
  6,
  14,
  5,
  3],
 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1|CYP2C9': [0,
  2,
  1,
  9,
  21,
  4,
  8,
  10,
  20,
  19,
  7,
  18,
  23,
  22,
  13,
  11,
  3,
  17,
  6,
  15,
  16,
  5,
  14],
 'CN[C@@H](C)[C@@H](O)c1ccccc1|CYP3A4': [0, 2, 1, 4, 9, 8, 10, 7, 11, 3, 5, 6],
 'CN[C@@H](C)[C@@H](O)c1ccccc1|CYP2D6': [0, 9, 2, 8, 10, 1, 4, 7, 11, 3, 5, 6],
 'CN[C@@H](C)[C@@H](O)c1ccccc1|CYP2C9': [0, 2, 1, 4, 9, 8, 10, 3, 7, 11, 5, 6],
 'CN[C@@H](C)[C@H](O)c1ccccc1|CYP3A4': [0, 2, 1, 4, 9, 8, 10, 7, 11, 3, 5, 6],
 'CN[C@@H](C)[C@H](O)c1ccccc1|CYP2D6': [0, 9, 2, 8, 10, 1, 4, 7, 11, 3, 5, 6],
 'CN[C@@H](C)[C@H](O)c1ccccc1|CYP2C9': [0, 2, 1, 4, 9, 8, 10, 3, 7, 11, 5, 6],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C|CYP3A4': [0,
  12,
  26,
  15,
  8,
  29,
  16,
  6,
  19,
  5,
  18,
  23,
  32,
  33,
  34,
  22,
  10,
  13,
  14,
  25,
  24,
  11,
  28,
  27,
  9,
  21,
  31,
  7,
  20,
  30,
  1,
  17,
  2,
  3,
  4],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C|CYP2D6': [12,
  0,
  26,
  23,
  16,
  6,
  15,
  5,
  8,
  18,
  19,
  29,
  10,
  32,
  33,
  34,
  22,
  13,
  14,
  25,
  24,
  11,
  28,
  27,
  9,
  7,
  17,
  20,
  2,
  4,
  21,
  31,
  30,
  1,
  3],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C|CYP2C9': [12,
  0,
  26,
  23,
  16,
  6,
  15,
  8,
  19,
  29,
  32,
  33,
  34,
  10,
  22,
  5,
  18,
  13,
  14,
  25,
  24,
  11,
  28,
  27,
  9,
  7,
  17,
  20,
  2,
  4,
  21,
  31,
  30,
  1,
  3],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC|CYP3A4': [10,
  13,
  20,
  0,
  17,
  5,
  3,
  14,
  8,
  11,
  7,
  9,
  19,
  18,
  1,
  16,
  12,
  2,
  15,
  6,
  4],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC|CYP2D6': [10,
  20,
  13,
  0,
  17,
  5,
  8,
  11,
  3,
  14,
  7,
  9,
  19,
  18,
  1,
  16,
  12,
  2,
  15,
  6,
  4],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC|CYP2C9': [10,
  20,
  13,
  0,
  17,
  5,
  8,
  11,
  3,
  14,
  7,
  9,
  19,
  18,
  1,
  16,
  12,
  2,
  15,
  6,
  4],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O|CYP3A4': [0,
  18,
  19,
  20,
  5,
  3,
  7,
  11,
  23,
  25,
  28,
  12,
  17,
  14,
  6,
  1,
  29,
  27,
  2,
  16,
  15,
  26,
  4,
  24,
  13,
  8,
  21,
  9,
  10],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O|CYP2D6': [0,
  18,
  19,
  20,
  28,
  5,
  3,
  17,
  7,
  11,
  23,
  25,
  12,
  14,
  6,
  1,
  29,
  27,
  2,
  16,
  15,
  26,
  4,
  10,
  24,
  13,
  8,
  21,
  9],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O|CYP2C9': [0,
  5,
  28,
  3,
  19,
  20,
  18,
  7,
  25,

In [28]:
df_smartcyp.to_pickle('./smartcyp_cyp.pickle')

3. somp

In [29]:
df_somp = pd.read_pickle('/home/datahouse1/wangyitian/MetaPred/30_main_products/save_code/65/somp_results.pickle')
df_somp = df_somp[df_somp['enzyme']!='UGT']
substrates_somp = df_somp['substrates'].to_list()
substrates_somp = list(map(canonicalsmiles,substrates_somp))
df_somp['substrates'] = substrates_somp
df_somp['sub_enz'] = df_somp['substrates'] + '|CYP' + df_somp['enzyme']
scores_somp = df_somp['scores'].to_list()
somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in scores_somp]
df_somp['rank'] = somp_sorted_atoms
df_somp

,substrates,enzyme,scores,sub_enz,rank
0,O=P1(NCCCl)OCCCN1CCCl,2C9,"{0: 6, 1: 12, 2: 7, 3: 3, 4: 14, 5: 8, 6: 10, ...",O=P1(NCCCl)OCCCN1CCCl|CYP2C9,"[9, 11, 3, 10, 13, 0, 2, 5, 8, 6, 7, 1, 12, 4]"
2,Cn1c(=O)c2c(ncn2C)n(C)c1=O,3A4,"{0: 3, 1: 11, 2: 12, 3: 6, 4: 13, 5: 14, 6: 9,...",Cn1c(=O)c2c(ncn2C)n(C)c1=O|CYP3A4,"[7, 11, 0, 9, 13, 3, 8, 12, 6, 10, 1, 2, 4, 5]"
3,Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)...,2C9,"{0: 5, 1: 48, 2: 28, 3: 7, 4: 29, 5: 49, 6: 6,...",Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)...,"[38, 43, 9, 40, 0, 6, 3, 26, 41, 42, 19, 32, 1..."
4,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,1A2,"{0: 45, 1: 27, 2: 55, 3: 41, 4: 13, 5: 21, 6: ...",O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[30, 51, 39, 44, 38, 45, 32, 53, 40, 43, 34, 5..."
5,CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,3A4,"{0: 8, 1: 4, 2: 29, 3: 22, 4: 27, 5: 28, 6: 26...",CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...,"[8, 26, 27, 1, 16, 24, 12, 0, 11, 13, 18, 25, ..."
...,...,...,...,...,...
383,COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=...,2D6,"{0: 1, 1: 29, 2: 30, 3: 25, 4: 21, 5: 5, 6: 6,...",COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=...,"[0, 33, 34, 35, 5, 6, 15, 18, 27, 11, 16, 32, ..."
384,CNCC[C@@H](Oc1ccccc1C)c1ccccc1,2C19,"{0: 1, 1: 16, 2: 11, 3: 17, 4: 2, 5: 6, 6: 20,...",CNCC[C@@H](Oc1ccccc1C)c1ccccc1|CYP2C19,"[0, 4, 10, 13, 17, 5, 9, 16, 18, 8, 2, 11, 15,..."
386,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,3A4,"{0: 13, 1: 1, 2: 6, 3: 31, 4: 23, 5: 7, 6: 11,...",C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,"[1, 19, 13, 15, 25, 2, 5, 17, 26, 7, 6, 8, 0, ..."
387,CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([...,2D6,"{0: 4, 1: 5, 2: 28, 3: 2, 4: 33, 5: 34, 6: 35,...",CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([...,"[31, 3, 32, 0, 1, 9, 12, 26, 29, 35, 38, 15, 3..."
388,NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1,3A4,"{0: 18, 1: 16, 2: 19, 3: 17, 4: 14, 5: 12, 6: ...",NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1|CYP3A4,"[8, 19, 7, 14, 10, 16, 17, 9, 11, 13, 12, 5, 1..."

In [30]:
df_somp.to_pickle('./somp_cyp.pickle')

In [31]:
dict_somp_sub2rank = dict(zip(df_somp['sub_enz'].to_list(),somp_sorted_atoms))
dict_somp_sub2rank

{'O=P1(NCCCl)OCCCN1CCCl|CYP2C9': [9,
  11,
  3,
  10,
  13,
  0,
  2,
  5,
  8,
  6,
  7,
  1,
  12,
  4],
 'Cn1c(=O)c2c(ncn2C)n(C)c1=O|CYP3A4': [7,
  11,
  0,
  9,
  13,
  3,
  8,
  12,
  6,
  10,
  1,
  2,
  4,
  5],
 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O|CYP2C9': [38,
  43,
  9,
  40,
  0,
  6,
  3,
  26,
  41,
  42,
  19,
  32,
  14,
  23,
  27,
  39,
  18,
  20,
  31,
  33,
  45,
  44,
  28,
  13,
  11,
  37,
  15,
  2,
  4,
  46,
  47,
  17,
  21,
  30,
  34,
  35,
  49,
  12,
  7,
  22,
  10,
  29,
  36,
  25,
  8,
  16,
  24,
  1,
  5,
  48],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O|CYP1A2': [30,
  51,
  39,
  44,
  38,
  45,
  32,
  53,
  40,
  43,
  34,
  55,
  4,
  18,
  25,
  46,
  36,
  57,
  10,
  11,
  5,
  19,
  22,
  60,
  29,
  50,
  1,
  15,
  24,
  59,
  9,
  13,
  27,
  48,
  7,
  21,
  23,
  61,
  41,
  42,
  3,
  14,
  8,
  12,
  0,
  16,
  31,
  33,
  52,
  54,
  6,
  20,
  35,
  56,
  2,
  17,
  26,
  28,
  37,
  47,
  49,
  58],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12|CYP3A4': [8,
  26,
  27,
  1,
  16,
  24,
  12,
  0,
  11,
  13,
  18,
  25,
  10,
  14,
  17,
  19,
  15,
  20,
  7,
  21,
  23,
  3,
  28,
  9,
  22,
  6,
  4,
  5,
  2],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1|CYP1A2': [24,
  26,
  1,
  22,
  8,
  0,
  9,
  2,
  3,
  21,
  10,
  7,
  25,
  27,
  23,
  16,
  30,
  18,
  29,
  6,
  11,
  19,
  15,
  14,
  4,
  17,
  28,
  20,
  13,
  5,
  12],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP3A4': [2,
  15,
  7,
  9,
  8,
  6,
  10,
  16,
  12,
  3,
  0,
  13,
  5,
  14,
  17,
  1,
  18,
  4,
  11],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP2D6': [0,
  10,
  6,
  7,
  21,
  26,
  13,
  8,
  5,
  12,
  28,
  16,
  20,
  17,
  22,
  2,
  19,
  11,
  3,
  14,
  27,
  15,
  24,
  9,
  4,
  25,
  23,
  1,
  18],
 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO|CYP2C9': [0,
  20,
  21,
  22,
  30,
  36,
  37,
  4,
  5,
  19,
  12,
  3,
  25,
  33,
  16,
  24,
  17,
  23,
  6,
  28,
  32,
  8,
  18,
  35,
  13,
  14,
  27,
  29,
  31,
  7,
  2,
  38,
  26,
  1,
  15,
  9,
  11,
  34,
  10],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3|CYP2C19': [0,
  6,
  3,
  11,
  15,
  2,
  7,
  5,
  12,
  10,
  14,
  16,
  18,
  8,
  1,
  20,
  13,
  4,
  19,
  17,
  9],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2C19': [10,
  2,
  5,
  1,
  14,
  4,
  13,
  15,
  6,
  19,
  22,
  12,
  16,
  7,
  25,
  18,
  23,
  8,
  24,
  21,
  20,
  9,
  0,
  3,
  11,
  17],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1|CYP2C9': [19,
  7,
  16,
  4,
  28,
  0,
  20,
  9,
  13,
  17,
  11,
  27,
  29,
  15,
  6,
  22,
  18,
  8,
  24,
  2,
  10,
  12,
  21,
  26,
  30,
  14,
  5,
  23,
  31,
  1,
  25,
  3],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1|CYP2D6': [0,
  23,
  4,
  27,
  11,
  15,
  3,
  2,
  30,
  7,
  8,
  20,
  14,
  24,
  6,
  9,
  31,
  16,
  5,
  28,
  17,
  1,
  12,
  29,
  25,
  21,
  10,
  13,
  18,
  19,
  26,
  22],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP2C19': [0,
  2,
  5,
  12,
  27,
  15,
  9,
  3,
  19,
  25,
  1,
  18,
  26,
  13,
  22,
  11,
  28,
  7,
  16,
  17,
  4,
  20,
  24,
  8,
  21,
  10,
  23,
  14,
  6],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4|CYP3A4': [10,
  27,
  0,
  3,
  9,
  2,
  6,
  8,
  11,
  22,
  29,
  4,
  13,
  1,
  26,
  16,
  15,
  25,
  7,
  14,
  17,
  5,
  18,
  24,
  28,
  19,
  21,
  12,
  31,
  20,
  32,
  30,
  23],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4|CYP2D6': [25,
  26,
  27,
  4,
  9,
  24,
  2,
  6,
  8,
  11,
  22,
  29,
  0,
  21,
  32,
  3,
  31,
  10,
  23,
  20,
  5,
  13,
  15,
  30,
  1,
  14,
  16,
  28,
  7,
  12,
  17,
  18,
  19],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP2C9': [1,
  6,
  7,
  0,
  5,
  8,
  16,
  20,
  12,
  4,
  11,
  18,
  3,
  2,
  13,
  9,
  14,
  21,
  17,
  15,
  19,
  10],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP2D6': [0,
  2,
  5,
  19,
  25,
  12,
  27,
  15,
  9,
  1,
  3,
  13,
  7,
  20,
  11,
  28,
  18,
  26,
  21,
  8,
  4,
  22,
  16,
  10,
  17,
  24,
  23,
  6,
  14],
 'Clc1ccc(CCCOCCCN2CCCCC2)cc1|CYP2D6': [9,
  7,
  11,
  2,
  19,
  5,
  13,
  17,
  15,
  6,
  14,
  16,
  10,
  3,
  18,
  12,
  1,
  4,
  8,
  0],
 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1|CYP2C9': [0,
  2,
  5,
  1,
  12,
  27,
  15,
  24,
  23,
  21,
  19,
  25,
  9,
  4,
  3,
  13,
  18,
  26,
  16,
  11,
  28,
  8,
  20,
  22,
  7,
  17,
  6,
  10,
  14],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP1A2': [18,
  19,
  10,
  7,
  13,
  6,
  14,
  5,
  15,
  8,
  12,
  1,
  0,
  2,
  9,
  11,
  17,
  4,
  16,
  3],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4|CYP1A2': [26,
  27,
  4,
  25,
  9,
  3,
  0,
  30,
  24,
  2,
  6,
  8,
  11,
  22,
  29,
  5,
  32,
  7,
  31,
  1,
  28,
  21,
  10,
  13,
  15,
  16,
  17,
  20,
  23,
  14,
  12,
  18,
  19],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O|CYP2C19': [1,
  3,
  2,
  10,
  5,
  14,
  12,
  8,
  6,
  0,
  9,
  15,
  13,
  7,
  4,
  11],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP2D6': [10,
  2,
  5,
  1,
  14,
  19,
  22,
  4,
  13,
  15,
  18,
  23,
  6,
  12,
  16,
  7,
  25,
  8,
  24,
  20,
  21,
  9,
  0,
  3,
  11,
  17],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F|CYP2C19': [4,
  5,
  12,
  18,
  8,
  19,
  7,
  22,
  9,
  20,
  21,
  15,
  13,
  10,
  0,
  24,
  17,
  16,
  1,
  14,
  23,
  2,
  11,
  3,
  6],
 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1|CYP3A4': [0,
  23,
  27,
  15,
  11,
  14,
  2,
  3,
  7,
  8,
  29,
  16,
  6,
  9,
  24,
  30,
  31,
  28,
  20,
  13,
  5,
  1,
  17,
  18,
  12,
  4,
  19,
  25,
  10,
  26,
  22,
  21],
 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12|CYP2D6': [26,
  27,
  8,
  1,
  16,
  24,
  12,
  11,
  13,
  0,
  18,
  10,
  14,
  7,
  25,
  19,
  17,
  20,
  15,
  21,
  3,
  9,
  28,
  23,
  22,
  4,
  6,
  5,
  2],
 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1|CYP3A4': [24,
  26,
  22,
  1,
  0,
  2,
  3,
  8,
  9,
  25,
  27,
  21,
  10,
  23,
  7,
  18,
  29,
  16,
  30,
  19,
  6,
  14,
  15,
  17,
  28,
  20,
  4,
  11,
  13,
  5,
  12],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP2C9': [1,
  3,
  19,
  15,
  5,
  2,
  6,
  0,
  4,
  7,
  16,
  13,
  9,
  11,
  12,
  18,
  10,
  14,
  8,
  17],
 'O=P1(NCCCl)OCCCN1CCCl|CYP1A2': [9,
  11,
  3,
  7,
  8,
  13,
  5,
  12,
  4,
  0,
  2,
  6,
  10,
  1],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1|CYP3A4': [10,
  1,
  39,
  41,
  27,
  28,
  12,
  16,
  13,
  15,
  7,
  18,
  38,
  42,
  30,
  0,
  36,
  37,
  24,
  32,
  11,
  4,
  8,
  17,
  29,
  19,
  26,
  3,
  33,
  34,
  40,
  35,
  14,
  31,
  6,
  2,
  9,
  20,
  25,
  5,
  21,
  22,
  23],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1|CYP2D6': [0,
  17,
  16,
  6,
  7,
  14,
  10,
  11,
  15,
  26,
  20,
  9,
  1,
  27,
  2,
  21,
  25,
  12,
  3,
  8,
  5,
  22,
  18,
  19,
  4,
  24,
  23,
  13],
 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1|CYP3A4': [5,
  6,
  7,
  12,
  13,
  2,
  1,
  4,
  0,
  11,
  16,
  15,
  14,
  9,
  8,
  10,
  3],
 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3|CYP2C9': [1,
  0,
  2,
  3,
  6,
  11,
  7,
  5,
  15,
  12,
  14,
  10,
  4,
  19,
  16,
  13,
  18,
  8,
  17,
  20,
  9],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O|CYP2C9': [30,
  51,
  39,
  44,
  34,
  55,
  38,
  45,
  32,
  53,
  40,
  43,
  36,
  57,
  27,
  48,
  23,
  61,
  29,
  50,
  26,
  28,
  31,
  47,
  49,
  52,
  1,
  15,
  4,
  18,
  0,
  16,
  9,
  13,
  10,
  11,
  25,
  46,
  24,
  59,
  6,
  20,
  33,
  35,
  37,
  54,
  56,
  58,
  22,
  60,
  41,
  42,
  2,
  17,
  5,
  19,
  7,
  21,
  8,
  12,
  3,
  14],
 'NC(=O)c1nc(F)cnc1O|CYP2D6': [7, 6, 4, 5, 8, 9, 2, 3, 1, 0, 10],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1|CYP2D6': [20,
  32,
  0,
  2,
  1,
  13,
  11,
  4,
  7,
  16,
  19,
  23,
  26,
  29,
  12,
  25,
  14,
  28,
  22,
  15,
  33,
  18,
  21,
  17,
  6,
  9,
  8,
  5,
  24,
  27,
  30,
  31,
  3,
  10],
 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O|CYP3A4': [18,
  5,
  13,
  15,
  14,
  12,
  16,
  4,
  8,
  0,
  6,
  17,
  11,
  3,
  7,
  19,
  2,
  10,
  1,
  9],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP2C9': [10,
  18,
  19,
  7,
  13,
  6,
  14,
  17,
  1,
  5,
  15,
  8,
  12,
  3,
  0,
  2,
  9,
  11,
  4,
  16],
 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O|CYP1A2': [16,
  19,
  3,
  0,
  2,
  5,
  7,
  12,
  25,
  6,
  4,
  15,
  20,
  1,
  24,
  11,
  23,
  26,
  21,
  8,
  22,
  10,
  9,
  17,
  13,
  27,
  14,
  28,
  18],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP2C9': [10,
  0,
  25,
  21,
  7,
  6,
  26,
  8,
  12,
  13,
  28,
  5,
  24,
  11,
  17,
  20,
  16,
  1,
  19,
  14,
  2,
  3,
  9,
  4,
  27,
  15,
  22,
  23,
  18],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1|CYP3A4': [3,
  39,
  12,
  15,
  16,
  18,
  19,
  21,
  22,
  24,
  25,
  27,
  28,
  30,
  31,
  33,
  34,
  13,
  36,
  1,
  0,
  2,
  37,
  6,
  41,
  9,
  7,
  40,
  5,
  4,
  14,
  17,
  20,
  23,
  26,
  29,
  32,
  35,
  8,
  10,
  38,
  11],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F|CYP3A4': [4,
  5,
  9,
  2,
  22,
  8,
  20,
  19,
  18,
  12,
  13,
  21,
  1,
  0,
  7,
  10,
  24,
  11,
  15,
  3,
  17,
  23,
  16,
  14,
  6],
 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1|CYP2C9': [20,
  31,
  32,
  0,
  2,
  13,
  25,
  1,
  33,
  4,
  7,
  16,
  19,
  23,
  26,
  29,
  28,
  22,
  11,
  12,
  14,
  18,
  21,
  15,
  9,
  6,
  17,
  3,
  10,
  5,
  24,
  27,
  30,
  8],
 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP3A4': [10,
  5,
  2,
  4,
  1,
  14,
  19,
  22,
  13,
  15,
  6,
  7,
  25,
  18,
  23,
  12,
  16,
  8,
  24,
  9,
  20,
  21,
  3,
  0,
  11,
  17],
 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1|CYP2C9': [39,
  12,
  1,
  3,
  15,
  16,
  18,
  19,
  21,
  22,
  24,
  25,
  27,
  28,
  30,
  31,
  33,
  34,
  36,
  13,
  37,
  0,
  2,
  4,
  6,
  41,
  10,
  7,
  40,
  9,
  14,
  17,
  20,
  23,
  26,
  29,
  32,
  35,
  5,
  8,
  11,
  38],
 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C|CYP2C19': [18,
  19,
  10,
  7,
  13,
  1,
  6,
  14,
  8,
  12,
  5,
  15,
  9,
  11,
  0,
  2,
  17,
  4,
  16,
  3],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C|CYP2C19': [0,
  16,
  17,
  13,
  15,
  3,
  14,
  4,
  6,
  7,
  8,
  2,
  5,
  9,
  12,
  11,
  1,
  10],
 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CYP2D6': [20,
  23,
  12,
  13,
  8,
  24,
  11,
  5,
  14,
  7,
  25,
  1,
  16,
  21,
  22,
  3,
  9,
  0,
  2,
  17,
  18,
  6,
  10,
  15,
  19,
  4],
 'CCN(CC)CCOC(=O)c1ccc(N)cc1|CYP3A4': [1,
  3,
  5,
  6,
  12,
  15,
  0,
  4,
  14,
  11,
  16,
  2,
  13,
  8,
  10,
  9,
  7],
 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O|CYP3A4': [6,
  2,
  3,
  8,
  10,
  1,
  5,
  0,
  12,
  14,
  9,
  4,
  13,
  7,
  15,
  11],
 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC|CYP2C19': [0,
  17,
  20,
  5,
  13,
  12,
  6,
  3,
  14,
  7,
  10,
  9,
  8,
  4,
  18,
  11,
  2,
  15,
  19,
  1,
  16],
 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1|CYP2D6': [0,
  19,
  22,
  13,
  16,
  15,
  2,
  10,
  25,
  27,
  11,
  24,
  20,
  1,
  18,
  23,
  3,
  26,
  12,
  14,
  17,
  5,
  9,
  6,
  7,
  21,
  4,
  8],
 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1|CYP3A4': [14,
  10,
  35,
  28,
  29,
  6,
  7,
  34,
  32,
  25,
  24,
  13,
  21,
  22,
  0,
  2,
  12,
  11,
  31,
  5,
  8,
  1,
  26,
  38,
  17,
  41,
  18,
  9,
  40,
  16,
  30,
  15,
  23,
  19,
  27,
  37,
  36,
  39,
  33,
  3,
  4,
  20],
 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1|CYP2C9': [0,
  6,
  17,
  16,
  9,
  13,
  21,
  7,
  8,
  18,
  3,
  27,
  15,
  10,
  24,
  4,
  26,
  25,
  2,
  22,
  20,
  5,
  12,
  1,
  11,
  23,
  14,
  19],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP2C19': [1,
  3,
  19,
  5,
  0,
  4,
  6,
  15,
  16,
  2,
  13,
  11,
  9,
  8,
  14,
  12,
  18,
  7,
  17,
  10],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP2D6': [6,
  5,
  7,
  0,
  1,
  4,
  8,
  10,
  16,
  13,
  12,
  3,
  2,
  9,
  15,
  11,
  14],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1|CYP1A2': [19,
  10,
  9,
  18,
  0,
  11,
  8,
  5,
  16,
  21,
  17,
  20,
  2,
  15,
  1,
  7,
  13,
  12,
  6,
  14,
  4,
  3],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP2C19': [1,
  6,
  7,
  5,
  0,
  8,
  11,
  10,
  2,
  4,
  12,
  13,
  9,
  14,
  21,
  16,
  20,
  15,
  19,
  3,
  17,
  18],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21|CYP3A4': [0,
  12,
  5,
  20,
  23,
  4,
  19,
  21,
  18,
  16,
  11,
  3,
  6,
  1,
  14,
  13,
  17,
  10,
  2,
  8,
  15,
  9,
  22,
  7],
 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23|CYP1A2': [11,
  10,
  2,
  21,
  0,
  3,
  8,
  13,
  16,
  9,
  12,
  24,
  7,
  1,
  15,
  26,
  17,
  6,
  22,
  19,
  4,
  5,
  25,
  14,
  23,
  20,
  18],
 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12|CYP2C19': [7,
  18,
  14,
  1,
  9,
  2,
  0,
  15,
  13,
  5,
  6,
  16,
  3,
  10,
  11,
  22,
  17,
  19,
  21,
  20,
  4,
  12,
  8],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21|CYP3A4': [0,
  2,
  3,
  5,
  10,
  17,
  1,
  9,
  18,
  13,
  14,
  11,
  16,
  8,
  19,
  4,
  7,
  20,
  12,
  15,
  6],
 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl|CYP1A2': [7,
  5,
  3,
  4,
  8,
  11,
  18,
  20,
  21,
  12,
  17,
  19,
  1,
  10,
  0,
  6,
  15,
  16,
  2,
  13,
  14,
  9],
 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1|CYP2C9': [19,
  8,
  18,
  14,
  15,
  12,
  10,
  0,
  2,
  16,
  17,
  13,
  9,
  5,
  4,
  7,
  11,
  3,
  1,
  6],
 'COc1ccc2ccc(=O)oc2c1CC=C(C)C|CYP2C9': [0,
  13,
  15,
  16,
  17,
  14,
  3,
  4,
  9,
  6,
  10,
  7,
  2,
  5,
  8,
  1,
  11,
  12],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1|CYP2C19': [26,
  1,
  29,
  18,
  30,
  9,
  23,
  5,
  16,
  28,
  22,
  33,
  10,
  14,
  7,
  2,
  3,
  0,
  38,
  36,
  27,
  24,
  13,
  17,
  15,
  19,
  35,
  25,
  37,
  21,
  4,
  8,
  34,
  32,
  12,
  20,
  6,
  31,
  39,
  11],
 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1|CYP3A4': [19,
  28,
  7,
  27,
  29,
  6,
  9,
  13,
  22,
  12,
  0,
  5,
  23,
  8,
  10,
  17,
  26,
  30,
  2,
  4,
  18,
  20,
  21,
  11,
  15,
  25,
  1,
  3,
  16,
  14,
  31,
  24],
 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21|CYP2C19': [0,
  20,
  19,
  5,
  16,
  4,
  12,
  11,
  21,
  3,
  18,
  1,
  6,
  10,
  23,
  9,
  7,
  2,
  13,
  8,
  14,
  17,
  22,
  15],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP2C9': [6,
  5,
  7,
  0,
  1,
  4,
  8,
  10,
  16,
  13,
  12,
  3,
  11,
  14,
  9,
  15,
  2],
 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1|CYP2C19': [19,
  5,
  9,
  18,
  10,
  0,
  17,
  20,
  2,
  1,
  8,
  16,
  21,
  11,
  15,
  3,
  14,
  4,
  7,
  12,
  6,
  13],
 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1|CYP3A4': [17,
  26,
  7,
  14,
  6,
  16,
  0,
  10,
  11,
  15,
  9,
  25,
  20,
  21,
  8,
  12,
  22,
  13,
  5,
  19,
  24,
  18,
  23,
  3,
  1,
  27,
  2,
  4],
 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC|CYP1A2': [1,
  3,
  19,
  5,
  6,
  0,
  4,
  2,
  15,
  11,
  16,
  9,
  7,
  8,
  10,
  13,
  17,
  18,
  12,
  14],
 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O|CYP1A2': [9,
  22,
  10,
  15,
  21,
  3,
  24,
  12,
  14,
  20,
  16,
  0,
  18,
  2,
  11,
  17,
  7,
  4,
  6,
  19,
  1,
  8,
  13,
  23,
  5,
  25],
 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1|CYP1A2': [1,
  7,
  6,
  0,
  8,
  5,
  4,
  16,
  20,
  11,
  15,
  19,
  10,
  17,
  18,
  14,
  21,
  2,
  9,
  13,
  3,
  12],
 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F|CYP1A2': [4,
  5,
  9,
  8,
  20,
  19,
  18,
  13,
  22,
  2,
  21,
  12,
  7,
  1,
  0,
  10,
  24,
  11,
  15,
  23,
  17,
  16,
  3,
  6,
  14],
 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1|CYP2D6': [0,
  10,
  7,
  15,
  3,
  24,
  2,
  11,
  20,
  14,
  4,
  23,
  16,
  21,
  18,
  6,
  22,
  5,
  1,
  8,
  17,
  19,
  13,
  12,
  9],
 'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC|CYP1A2': [14,
  13,
  20,
  7,
  26,
  8,
  29,
  30,
  18,
  27,
  21,
  10,
  12,
  23,
  25,
  16,
  5,
  4,
  22,
  17,
  11,
  0,
  19,
  15,
  24,
  9,
  2,
  6,
  1,
  3,
  28],
 'CN[C@@H](C)[C@H](O)c1ccccc1|CYP2C19': [0,
  2,
  11,
  5,
  3,
  6,
  10,
  12,
  9,
  13,
  4,
  8,
  7,
  1],
 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O|CYP2C19': [6,
  5,
  7,
  1,
  0,
  4,
  8,
  13,
  10,
  16,
  12,
  3,
  2,
  9,
  15,
  11,
  14],
 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1|CYP1A2': [6,
  11,
  10,
  12,
  4,
  5,
  15,
  16,
  9,
  14,
  7,
  8,
  13,
  0,
  3,
  2,
  1],
 'CN(C)CCCN1c2ccccc2CCc2ccccc21|CYP2D6': [0,
  2,
  3,
  10,
  17,
  5,
  9,
  18,
  13,
  14,
  11,
  16,
  1,
  8,
  19,
  4,
  12,
  15,
  7,
  20,
  6],
 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O|CYP1A2': [0,
  15,
  19,
  20,
  18,
  11,
  7,
  12,
  23,
  10,
  3,
  25,
  5,
  16,
  6,
  22,
  28,
  13,
  14,
  29,
  8,
  17,
  2,
  21,
  26,
  9,
  4,
  1,
  27,
  24],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1|CYP2C19': [1,
  0,
  16,
  18,
  12,
  7,
  4,
  3,
  2,
  14,
  6,
  13,
  5,
  9,
  10,
  20,
  21,
  15,
  11,
  8,
  17,
  19],
 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O|CYP2D6': [39,
  44,
  30,
  51,
  38,
  45,
  40,
  43,
  4,
  18,
  34,
  55,
  32,
  53,
  25,
  46,
  27,
  48,
  36,
  57,
  9,
  13,
  22,
  60,
  29,
  50,
  23,
  61,
  1,
  15,
  5,
  19,
  7,
  21,
  24,
  59,
  10,
  11,
  0,
  16,
  31,
  33,
  35,
  52,
  54,
  56,
  3,
  14,
  6,
  20,
  26,
  28,
  37,
  47,
  49,
  58,
  41,
  42,
  2,
  17,
  8,
  12],
 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1|CYP3A4': [16,
  18,
  1,
  7,
  0,
  12,
  2,
  6,
  3,
  5,
  13,
  4,
  14,
  9,
  10,
  20,
  21,
  15,
  11,
  8,
  17,
  19],
 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1|CYP1A2': [3,
  31,
  34,
  15,
  32,
  20,
  0,
  10,
  25,
  1,
  11,
  28,
  8,
  37,
  14,
  27,
  9,
  12,
  26,
  29,
  35,
  38,
  21,
  40,
  22,
  2,
  23,
  7,
  5,
  41,
  4,
  24,
  6,
  19,
  17,
  13,
  16,
  39,
  36,
  18,
  30,
  33],
 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1|CYP2C9': [11,
  1,
  39,
  41,
  27,
  10,
  2,
  30,
  36,
  32,
  13,
  15,
  0,
  37,
  28,
  38,
  42,
  7,
  18,
  14,
  8,
  17,
  12,
  16,
  40,
  4,
  3,
  24,
  34,
  21,
  26,
  19,
  22,
  29,
  31,
  25,
  20,
  33,
  35,
  6,
  23,
  5,
  9],
 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1|CYP1A2': [26,
  1,
  29,
  13,
  30,
  28,
  14,
  5,
  24,
  23,
  9,
  33,
  22,
  10,
  17,
  36,
  0,
  2,
  3,
  38,
  7,
  4,
  27,
  35,
  16,
  6,
  31,
  25,
  32,
  34,
  11,
  8,
  12,
  21,
  15,
  18,
  39,
  19,
  20,
  37],
 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP3A4': [1,
  4,
  7,
  0,
  8,
  3,
  17,
  18,
  9,
  13,
  6,
  10,
  11,
  5,
  16,
  19,
  2,
  15,
  14,
  20,
  12],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP1A2': [0,
  10,
  7,
  6,
  13,
  17,
  5,
  21,
  8,
  16,
  12,
  26,
  28,
  20,
  19,
  23,
  2,
  11,
  27,
  9,
  15,
  22,
  14,
  24,
  25,
  3,
  4,
  1,
  18],
 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C|CYP2C9': [0,
  11,
  33,
  34,
  35,
  27,
  5,
  10,
  15,
  6,
  16,
  13,
  14,
  23,
  8,
  18,
  32,
  12,
  9,
  25,
  19,
  30,
  29,
  22,
  7,
  4,
  17,
  1,
  21,
  31,
  2,
  24,
  20,
  3,
  28,
  26],
 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1|CYP3A4': [10,
  0,
  6,
  21,
  7,
  26,
  17,
  8,
  23,
  5,
  20,
  13,
  19,
  2,
  12,
  16,
  22,
  28,
  11,
  3,
  9,
  4,
  15,
  18,
  1,
  14,
  24,
  25,
  27],
 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1|CYP1A2': [0,
  4,
  10,
  13,
  17,
  9,
  16,
  18,
  5,
  11,
  2,
  15,
  19,
  8,
  12,
  7,
  1,
  14,
  3,
  6],

4. 整理结果

In [32]:
substrates_total = df['sub_enz'].to_list()
rank_smartcyp = [dict_smartcyp_sub2rank.get(i,'None') for i in substrates_total]
rank_somp= [dict_somp_sub2rank.get(i,'None') for i in substrates_total]
df['rank_smartcyp'] = rank_smartcyp
df['rank_somp'] = rank_somp
df

,Unnamed: 0,substrate,Enzyme,truth,site_truth,predict_site,site_truth_atomidx,predict_site_atomidx,sub_enz,rank_smartcyp,rank_somp
0,0,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP1A2,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[32],"[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,None,"[14, 35, 29, 6, 7, 28, 34, 25, 24, 10, 12, 5, ..."
1,1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP2C9,CC(C)(O)c1cc(O)ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,"[6, 32, 10, 40]","[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[13, 34, 6, 33, 0, 2, 37, 28, 27, 10, 7, 5, 12...","[14, 0, 2, 35, 6, 7, 13, 21, 22, 25, 10, 34, 2..."
2,2,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP2D6,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(C)(O)c1ccccc1CC[C@H](c1cccc(/C=C/c2ccc3ccc(...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,[32],"[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[13, 34, 16, 14, 12, 6, 33, 0, 2, 20, 21, 37, ...","[14, 35, 7, 6, 10, 34, 25, 24, 12, 11, 13, 29,..."
3,3,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,CYP3A4,CC(C)(O)c1cc(O)ccc1CC[C@@H](SCC1(CC(=O)O)CC1)c...,CC(C)(O)c1c[cH:1]ccc1CC[C@@H](SCC1(CC(=O)O)CC1...,CC(O)(c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc...,"[6, 32, 10, 40]","[[40], [1], [15, 21], [32, 33, 34, 35, 37, 38]...",CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[13, 14, 12, 16, 34, 10, 28, 27, 20, 21, 39, 3...","[14, 10, 35, 28, 29, 6, 7, 34, 32, 25, 24, 13,..."
4,4,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,CYP2D6,CC(C)C=O|CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCC...,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CC[CH2:1]C2)...,CC(C)C[NH:1]Cc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)c...,"[22, 5, 6, 7, 23, 25]","[[4], [1], [25], [4], [23], [5], [22], [19, 23...",CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1|CY...,"[21, 22, 20, 23, 13, 3, 12, 19, 14, 11, 5, 0, ...","[20, 23, 12, 13, 8, 24, 11, 5, 14, 7, 25, 1, 1..."
...,...,...,...,...,...,...,...,...,...,...,...
69,69,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,CYP1A2,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1|O=C1CN=...,[18],"[[18], [15], [10, 17, 18], [16], [8], [3, 4], ...",O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP1A2,None,"[2, 7, 9, 15, 8, 6, 10, 16, 12, 0, 3, 5, 1, 14..."
70,70,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,CYP3A4,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=N[CH2:1]1|O=C1CN=...,[18],"[[18], [15], [10, 17, 18], [16], [8], [3, 4], ...",O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP3A4,"[2, 3, 8, 15, 6, 10, 12, 7, 9, 16, 18, 0, 1, 1...","[2, 15, 7, 9, 8, 6, 10, 16, 12, 3, 0, 13, 5, 1..."
71,71,O=P1(NCCCl)OCCCN1CCCl,CYP2C9,NP1(=O)OCCCN1CCCl|O=P1(NCCCl)OCCC(O)N1CCCl,O=P1(NCCCl)OCC[CH2:1]N1CCCl|O=P1([NH:1]CCCl)OC...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1([NH:1]CCCl)OCCC...,"[9, 2]","[[10], [2], [9], [10], [9], [8], [1, 12, 13], ...",O=P1(NCCCl)OCCCN1CCCl|CYP2C9,"[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]","[9, 11, 3, 10, 13, 0, 2, 5, 8, 6, 7, 1, 12, 4]"
72,72,O=P1(NCCCl)OCCCN1CCCl,CYP3A4,NP1(=O)OCCCN1CCCl|N[P@@]1(=O)OCCCN1CCCl|O=P1(N...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1(NCCCl)OCC[CH2:1...,O=P1(NCCCl)OCCC[N:1]1CCCl|O=P1([NH:1]CCCl)OCCC...,"[10, 9, 2]","[[10], [2], [9], [10], [9], [8], [1, 12, 13], ...",O=P1(NCCCl)OCCCN1CCCl|CYP3A4,"[9, 3, 11, 10, 2, 7, 8, 4, 12, 0, 6, 1]","[9, 11, 3, 7, 8, 13, 5, 12, 4, 0, 6, 2, 10, 1]"
73,73,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,CYP3A4,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,O[CH2:1]COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,OCCOCC[N:1]1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|OC...,[1],"[[6], [3, 5, 10], [3], [9], [18, 20, 21], [20,...",OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1|CYP3A4,"[5, 10, 7, 25, 8, 24, 6, 9, 1, 2, 4, 19, 22, 1...","[10, 5, 2, 4, 1, 14, 19, 22, 13, 15, 6, 7, 25,..."

In [33]:
df.to_pickle('./total_cyp.pickle')

In [34]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

In [35]:
df_total = pd.read_pickle('./total_cyp.pickle')

ourmodel_results_old = df_total['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.21621621621621623
top 3 accuracy = 0.4594594594594595
top 5 accuracy = 0.6081081081081081
top 1 accuracy = 0.16216216216216217
top 3 accuracy = 0.4864864864864865
top 5 accuracy = 0.6486486486486487
top 1 accuracy = 0.7027027027027027
top 3 accuracy = 0.8513513513513513
top 5 accuracy = 0.9324324324324325

In [36]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.216216   0.162162       0.702703
1  top3_recall       0.459459   0.486486       0.851351
2  top5_recall       0.608108   0.648649       0.932432

5. 按照酶整理结果

In [38]:
df_total['Enzyme'].unique()

array(['CYP1A2', 'CYP2C9', 'CYP2D6', 'CYP3A4'], dtype=object)

In [39]:
df_total_cyp1a2 = df_total[df_total['Enzyme'] == 'CYP1A2']

ourmodel_results_old = df_total_cyp1a2['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp1a2['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp1a2['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp1a2['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.0
top 3 accuracy = 0.0
top 5 accuracy = 0.0
top 1 accuracy = 0.14285714285714285
top 3 accuracy = 0.42857142857142855
top 5 accuracy = 0.5714285714285714
top 1 accuracy = 0.7142857142857143
top 3 accuracy = 0.7857142857142857
top 5 accuracy = 0.9285714285714286

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall            0.0   0.142857       0.714286
1  top3_recall            0.0   0.428571       0.785714
2  top5_recall            0.0   0.571429       0.928571

In [41]:
df_total_cyp2c9 = df_total[df_total['Enzyme'] == 'CYP2C9']

ourmodel_results_old = df_total_cyp2c9['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp2c9['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp2c9['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp2c9['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.25
top 3 accuracy = 0.5625
top 5 accuracy = 0.8125
top 1 accuracy = 0.25
top 3 accuracy = 0.5
top 5 accuracy = 0.6875
top 1 accuracy = 0.8125
top 3 accuracy = 0.875
top 5 accuracy = 0.9375

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall         0.2500     0.2500         0.8125
1  top3_recall         0.5625     0.5000         0.8750
2  top5_recall         0.8125     0.6875         0.9375

In [45]:
df_total_cyp2d6 = df_total[df_total['Enzyme'] == 'CYP2D6']

ourmodel_results_old = df_total_cyp2d6['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp2d6['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp2d6['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp2d6['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.29411764705882354
top 3 accuracy = 0.6470588235294118
top 5 accuracy = 0.7647058823529411
top 1 accuracy = 0.0
top 3 accuracy = 0.5294117647058824
top 5 accuracy = 0.7647058823529411
top 1 accuracy = 0.5882352941176471
top 3 accuracy = 0.8823529411764706
top 5 accuracy = 0.9411764705882353

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.294118   0.000000       0.588235
1  top3_recall       0.647059   0.529412       0.882353
2  top5_recall       0.764706   0.764706       0.941176

In [46]:
df_total_cyp3a4 = df_total[df_total['Enzyme'] == 'CYP3A4']

ourmodel_results_old = df_total_cyp3a4['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp3a4['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp3a4['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp3a4['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.25925925925925924
top 3 accuracy = 0.5185185185185185
top 5 accuracy = 0.7037037037037037
top 1 accuracy = 0.2222222222222222
top 3 accuracy = 0.48148148148148145
top 5 accuracy = 0.5925925925925926
top 1 accuracy = 0.7037037037037037
top 3 accuracy = 0.8518518518518519
top 5 accuracy = 0.9259259259259259

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.259259   0.222222       0.703704
1  top3_recall       0.518519   0.481481       0.851852
2  top5_recall       0.703704   0.592593       0.925926