1. metareact

In [1]:
import pandas as pd
from rdkit import Chem
def get_reactive_atom_indices(smiles):
    # 解析 SMILES
    mol = Chem.MolFromSmiles(smiles)
    
    # 获取标记为反应位点的原子
    reactive_atoms = []
    for atom in mol.GetAtoms():
        # 检查是否带有反应位点标记
        if atom.HasProp('molAtomMapNumber'):
            reactive_atoms.append(atom.GetIdx())  # 获取原子序号
    
    return reactive_atoms

from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

def standardize_smiles_with_atom_map(smiles: str) -> str:
    try:
        # 将 SMILES 转换为分子对象
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("Invalid SMILES string.")
        
        # 提取位点信息（Atom Maps）
        atom_map = {atom.GetIdx(): atom.GetAtomMapNum() for atom in mol.GetAtoms() if atom.GetAtomMapNum() > 0}
        
        # 标准化分子（使用 Standardizer）
        uncharger = rdMolStandardize.Uncharger()  # 去质子化
        mol = uncharger.uncharge(mol)
        
        # 去除多余氢原子
        mol = Chem.RemoveHs(mol)
        
        # 恢复位点信息（Atom Maps）
        for idx, map_num in atom_map.items():
            mol.GetAtomWithIdx(idx).SetAtomMapNum(map_num)
        
        # 返回标准化后的 SMILES
        standardized_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return standardized_smiles
    except Exception as e:
        return f"Error: {e}"

def df_col_getatomindices(dfname,col_old,flat=False):
    preds = dfname[col_old].to_list()
    preds = [i.split('|') for i in preds]
    try:
        preds = [list(map(standardize_smiles_with_atom_map,i)) for i in preds]
        ranks = [list(map(get_reactive_atom_indices,i)) for i in preds]
    except:
        ranks = []
        for k in preds:
            preds_part = []
            for x in k:
                try:
                    x = standardize_smiles_with_atom_map(x)
                    x_new = get_reactive_atom_indices(x)
                except:
                    x_new = []
                preds_part.append(x_new)
            ranks.append(preds_part)
    if flat == True:
        ranks_new = []
        for i in ranks:
            list_part = []
            for j in i:
                list_part = list_part + j
            ranks_new.append(list_part)
        return ranks_new
    else:
        return ranks
    
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [2]:
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

In [4]:
df = pd.read_csv('pred_results_drugbank_has_cyp_enzyme.csv')

In [6]:
site_truth = df_col_getatomindices(df,'site_truth',flat=True) 
predict_site = df_col_getatomindices(df,'site_predict') 
df['site_truth_atomidx'] = site_truth
df['predict_site_atomidx'] = predict_site
df['sub_enz'] = df['substrate']+'|' + df['Enzyme']
df

[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:11] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger
[11:38:12] Running Uncharger

,Unnamed: 0,substrate,Enzyme,truth,site_truth,site_predict,site_truth_atomidx,predict_site_atomidx,sub_enz
0,0,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CYP3A4,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(NC(=O)c2c[nH]c3c...,[10],"[[10], [10], [21], [20], [23], [10, 12], [18, ...",CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...
1,1,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CYP3A4,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"[[39], [32], [27, 30, 31, 32], [30, 31], [30, ...",CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...
2,2,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1,CYP3A4,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|...,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)[CH2...,CC1(C)CC(=O)N(CCCC[N:1]2CCN(c3ncccn3)CC2)C(=O)...,"[25, 11]","[[11], [18], [2, 11], [11], [25], [2], [14], [...",CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1|C...
3,3,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CYP2C9,CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC1,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CC(/C=C/C1=C([CH3:1])CCCC1(C)C)=C\C=C\C(C)=C\C...,[],"[[6], [21], [4, 5], [20], [21], [19], [20], []...",CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC...
4,4,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CYP3A4,CC1=C(/C=C/C(C)=C/C=C/C(C)=C\C(=O)O)C(C)(C)CCC...,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CC(/C=C/C1=C([CH3:1])CCCC1(C)C)=C\C=C\C(C)=C\C...,[],"[[6], [21], [4, 5], [20], [21], [19], [20], []...",CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC...
5,5,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP1A2,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...
6,6,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP2D6,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...
7,7,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP3A4,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...
8,8,CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](...,CYP3A4,CC(O)C(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@@H]5CO[...,CC(n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6...,CCC(C)[n:1]1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[...,[47],"[[4], [47], [22, 40], [47], [4], [48], [47], [...",CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](...
9,9,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC...,CYP3A4,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCNCC4)cc...,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CC[N:1](C...,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CC[N:1](C...,[21],"[[21], [24], [21], [22], [25], [21, 24], [21],...",CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC...
10,10,CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CYP2D6,CCNC(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CCN(...,[2],"[[2], [17], [2], [17], [4], [16], [16], [2], [...",CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP2D6
11,11,CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CYP3A4,CCNC(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CCN(...,[2],"[[2], [17], [2], [17], [4], [16], [16], [2], [...",CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP3A4
12,12,CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21,CYP2C9,COCCCN1C[C@H](N)c2cc(S(N)(=O)=O)sc2S1(=O)=O,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,[2],"[[2], [9], [5], [8, 9], [10], [9], [9], [8], [...",CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc2...
13,13,CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21,CYP3A4,COCCCN1C[C@H](N)c2cc(S(N)(=O)=O)sc2S1(=O)=O,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,[2],"[[2], [9], [5], [8, 9], [10], [9], [9], [8], [...",CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc2...
14,14,CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C,CYP2D6,CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C,CC[C@@H](c1cc(O)c[cH:1]c1)[C@@H](C)CN(C)C,CC[C@@H](c1cccc(O)c1)[C@@H](C)C[N:1](C)C|CC[C@...,[8],"[[13], [6], [2], [13], [6], [8], [9], [13], [1...",CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C|CYP2D6
15,15,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,C[N+](C)([O-])CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|C[...,[1],"[[1], [1], [3], [22, 23], [1, 3], [15], [1], [...",CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6
16,16,CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,C[N+](C)([O-])CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N...,C[N:1](C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc2...,[1],"[[1], [1], [1], [1, 3], [3], [22, 23], [1], [1...",CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CY...
17,17,CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CYP2C9,O=C1CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc2N1,C[N:1]1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CN1C(=O)CC(=O)N(c2ccc(O)[cH:1]c2)c2cc(Cl)ccc21...,[1],"[[13], [1], [7, 8, 9, 10, 11, 12, 13, 14], [14...",CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP2C9
18,18,CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CYP3A4,O=C1CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc2N1,C[N:1]1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CN1C(=O)CC(=O)N(c2ccc(O)[cH:1]c2)c2cc(Cl)ccc21...,[1],"[[13], [1], [7, 8, 9, 10, 11, 12, 13, 14], [14...",CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP3A4
19,19,CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2...,CYP3A4,CN1C=C[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc...,CN1[C@@H](c2nc3ccccc3[nH]2)C[C@H](NC(=O)Nc2ccc...,C[N:1]1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c...,"[26, 27]","[[1], [1], [23], [23], [24], [1], [24], [21, 2...",CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2...
20,20,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CYP3A4,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CNC(=O)c1cc(Oc2c[cH:1]c(NC(=O)[NH:1][c:1]3ccc(...,[31],"[[10, 15, 16, 27], [31], [1], [22], [16], [1, ...",CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...
21,21,CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,C[NH:1]CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[NH:1]CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CN[C...,[1],"[[1], [2], [1], [14], [2], [1], [15], [21, 22]...",CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6
22,22,COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...,CYP3A4,COc1c(O)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21|...,COc1c(OCCC[N:1]2CC[O:1]CC2)ccc2c1N=C(NC(=O)c1c...,COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...,"[8, 11, 8, 11, 12, 8, 11, 12, 13, 7, 11, 4]","[[32], [1], [29], [4], [34], [7, 11], [8, 11, ...",COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...
23,23,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,CYP3A4,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CC[N:1](C)CC4)c(O...,[22],"[[22], [10], [22], [27], [25], [24], [14], [15...",COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...
24,24,COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,CYP2C9,COc1cc(O)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)n...,COc1cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)...,COc1cc(OC)cc(N(CC[NH:1]C(C)C)c2ccc3ncc(-c4cnn(...,[30],"[[12], [30], [26], [9], [11], [32], [21], [7],...",COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...
25,25,COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,CYP3A4,COc1cc(O)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)n...,COc1cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)...,COc1cc(OC)cc(N(CC[NH:1]C(C)C)c2ccc3ncc(-c4cnn(...,[30],"[[12], [30], [26], [9], [11], [32], [21], [7],...",COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...
26,26,COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN...,CYP2D6,COc1cc2c(cc1O)CCN1C[C@@H](CC(C)C)[C@H](O)C[C@H...,COc1cc2c(cc1[O:1]C)CCN1C[C@@H](CC(C)C)[C@H](O)...,COc1cc2c(cc1[O:1]C)CCN1C[C@@H](CC(C)C)[C@H](O)...,"[8, 8]","[[8], [8], [16], [16], [18], [8], [8], [18], [...",COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN...
27,27,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,CYP3A4,CNCC[C@@](O)(c1cccc2ccccc12)[C@H](c1ccccc1)c1c...,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,[24],"[[24], [24], [35], [35], [24], [24], [24], [35...",COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...
28,28,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,CYP2C9,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cc[cH:1]cn...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cccc[n:1]3...,[20],"[[22], [20], [10], [22], [23], [8], [22], [4, ...",CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...
29,29,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,CYP3A4,CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)...,CS(=O)(=O)c1ccc(C(=O)Nc2cc(-c3ccccn3)c(Cl)[cH:...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cccc[n:1]3...,[22],"[[22], [20], [10], [22], [23], [8], [22], [4, ...",CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...
30,30,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CYP3A4,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](OS(=O)(=O)O...,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H]([OH:1])CC[C...,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,[11],"[[24], [10, 11], [24], [16], [24], [10, 11], [...",C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...
31,31,Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1,CYP3A4,Cc1c(OCC(F)(F)F)ccnc1CS(=O)(=O)c1nc2ccccc2[nH]1,Cc1c(OCC(F)(F)F)ccnc1C[S@@:1](=O)c1nc2ccccc2[nH]1,Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2c[cH:1]ccc...,[14],"[[20], [3], [3, 4], [14], [14], [20], [18, 19]...",Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]...
32,32,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,CYP3A4,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cc(O)cc3Cl)s2)cc(N2CC...,Cc1nc(Nc2ncc(C(=O)Nc3c(C)c[cH:1]cc3Cl)s2)cc(N2...,Cc1nc(Nc2ncc(C(=O)Nc3c(C)c[cH:1]cc3Cl)s2)cc(N2...,"[16, 26, 19]","[[16], [11, 12, 13, 15, 16, 17, 18, 19], [26],...",Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...
33,33,Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O,CYP3A4,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O,OC1N=C(c2ccccc2F)c2cc(Cl)ccc2-n2c1cnc2[CH3:1],OC1N=C(c2ccccc2F)c2cc(Cl)ccc2-n2c1cnc2[CH3:1]|...,[23],"[[23], [4, 5, 6, 12, 13, 21, 22, 23], [3], [22...",Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|CYP3A4
34,34,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP1A2,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...
35,35,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP2C9,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...
36,36,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP3A4,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...
37,37,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP1A2,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP1A2
38,38,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP2C9,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP2C9
39,39,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP3A4,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP3A4
40,40,O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2...,CYP3A4,O=C(O)CNC(=O)C1C(=O)N(C2CCC(O)CC2)C(=O)N([C@H]...,O=C(O)CNC(=O)C1C(=O)N(C2CCC[CH2:1]C2)C(=O)N(C2...,O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CC[CH2...,"[15, 24, 15, 24, 26, 27, 15, 23, 26, 27, 14, 2...","[[23], [20, 22, 23, 24, 25], [24], [4], [20, 2...",O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2...
41,41,O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...,CYP3A4,O=C(O)CNC(=O)C1C(=O)N(C2CC[C@H](O)[C@H](O)C2)C...,O=C(O)CNC(=O)C1C(=O)N(C2CC[CH2:1][C@H](O)C2)C(...,O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...,[14],"[[24, 25], [15, 16], [24, 25], [14], [15, 16],...",O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...
42,42,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,CYP2C9,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2c(O)...,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2c(cc...,O=C(O)C[C@@H:1](C[C@H](O)/C=C/c1c(C2CC2)nc2ccc...,[22],"[[4, 30], [4, 30], [7, 30], [20], [30], [29], ...",O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...
43,43,O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...,CYP3A4,O=C(O)CC(O)CC(=O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1...,O=[C:1]1CC(O)C[CH:1](/C=C/c2c(C3CC3)nc3ccccc3c...,O=C1OC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F)cc2)...,"[1, 6, 29]","[[27, 29], [1, 29], [18], [17], [24], [27, 28,...",O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...
44,44,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,CYP2C9,O=C1C(O)N=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,"[19, 24]","[[19], [2, 3, 4, 19], [3, 4, 19], [2, 3, 4, 19...",O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|CYP2C9
45,45,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,CYP3A4,O=C1C(O)N=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,"[19, 24]","[[19], [2, 3, 4, 19], [3, 4, 19], [2, 3, 4, 19...",O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|CYP3A4
46,46,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,CYP2D6,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3cc[cH:1]...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","[[20], [17], [11], [25], [31], [30], [12, 25],...",OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...
47,47,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,CYP2D6,OCCOc1ccc(Cc2cc([C@@H]3O[C@H](CO)[C@@H](O)[C@H...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCC[O:1]C4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[19, 11]","[[16], [22], [18, 19], [19], [22], [4, 6, 28, ...",OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...
48,48,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,CYP3A4,O=C(O)COc1ccc(Cc2cc([C@@H]3O[C@H](CO)[C@@H](O)...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCC[O:1]C4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[19, 18, 19, 11]","[[16], [22], [18, 19], [19], [22], [4, 6, 28, ...",OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...
49,49,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,CYP3A4,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,[23],"[[23], [2], [23], [14, 15], [2, 14, 22, 23], [...",OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2|CYP3A4

In [7]:
df.to_pickle('./predict_site_123_has_enzyme.pickle')

2. smartcyp

In [8]:
df_smartcyp = pd.read_pickle('/home/datahouse1/wangyitian/MetaPred/30_main_products/save_code/123/smartcyp_results_drugbank.pickle')
substrates = df_smartcyp['substrates'].to_list()
substrates = list(map(canonicalsmiles,substrates))
df_smartcyp['substrates'] = substrates
df_smartcyp['sub_enz'] = df_smartcyp['substrates'] + '|CYP' + df_smartcyp['enzyme']
df_smartcyp

,substrates,enzyme,scores,sub_enz
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,3A4,"{0: 3, 1: 21, 2: 10, 3: 1, 4: 20, 5: 17, 6: 16...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2D6,"{0: 6, 1: 21, 2: 13, 3: 3, 4: 20, 5: 17, 6: 16...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...
2,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2C9,"{0: 5, 1: 18, 2: 9, 3: 2, 4: 17, 5: 15, 6: 14,...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...
3,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,3A4,"{0: 3, 1: 14, 2: 13, 3: 11, 4: 18, 5: 5, 6: 10...",CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP3A4
4,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,2D6,"{0: 2, 1: 14, 2: 13, 3: 9, 4: 18, 5: 7, 6: 10,...",CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP2D6
...,...,...,...,...
364,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2D6,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 4, 6: 19...",Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...
365,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2C9,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 3, 6: 19...",Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...
366,c1cnc(N2CCNCC2)nc1,3A4,"{0: 6, 1: 7, 2: 5, 3: 8, 4: 4, 5: 1, 6: 3, 7: ...",c1cnc(N2CCNCC2)nc1|CYP3A4
367,c1cnc(N2CCNCC2)nc1,2D6,"{0: 1, 1: 5, 2: 4, 3: 8, 4: 7, 5: 2, 6: 6, 7: ...",c1cnc(N2CCNCC2)nc1|CYP2D6
368,c1cnc(N2CCNCC2)nc1,2C9,"{0: 5, 1: 7, 2: 6, 3: 8, 4: 4, 5: 1, 6: 3, 7: ...",c1cnc(N2CCNCC2)nc1|CYP2C9

In [9]:
scores_smartcyp = df_smartcyp['scores'].to_list()
smartcyp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in scores_smartcyp]
df_smartcyp['rank'] = smartcyp_sorted_atoms
df_smartcyp

,substrates,enzyme,scores,sub_enz,rank
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,3A4,"{0: 3, 1: 21, 2: 10, 3: 1, 4: 20, 5: 17, 6: 16...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,"[3, 18, 0, 9, 8, 10, 19, 16, 15, 2, 14, 7, 12,..."
1,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2D6,"{0: 6, 1: 21, 2: 13, 3: 3, 4: 20, 5: 17, 6: 16...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,"[9, 18, 3, 8, 10, 0, 19, 7, 12, 13, 15, 14, 16..."
2,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,2C9,"{0: 5, 1: 18, 2: 9, 3: 2, 4: 17, 5: 15, 6: 14,...",CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,"[9, 3, 8, 10, 0, 7, 12, 13, 18, 2, 14, 15, 19,..."
3,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,3A4,"{0: 3, 1: 14, 2: 13, 3: 11, 4: 18, 5: 5, 6: 10...",CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP3A4,"[19, 18, 0, 14, 5, 12, 9, 13, 15, 6, 3, 22, 2,..."
4,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,2D6,"{0: 2, 1: 14, 2: 13, 3: 9, 4: 18, 5: 7, 6: 10,...",CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP2D6,"[19, 0, 14, 18, 13, 15, 5, 12, 3, 6, 9, 22, 2,..."
...,...,...,...,...,...
364,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2D6,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 4, 6: 19...",Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,"[8, 9, 18, 24, 5, 7, 2, 32, 17, 19, 23, 25, 10..."
365,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,2C9,"{0: 12, 1: 13, 2: 6, 3: 11, 4: 16, 5: 3, 6: 19...",Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,"[8, 9, 5, 18, 24, 7, 2, 32, 10, 28, 30, 17, 19..."
366,c1cnc(N2CCNCC2)nc1,3A4,"{0: 6, 1: 7, 2: 5, 3: 8, 4: 4, 5: 1, 6: 3, 7: ...",c1cnc(N2CCNCC2)nc1|CYP3A4,"[5, 9, 7, 6, 8, 4, 2, 10, 0, 1, 11, 3]"
367,c1cnc(N2CCNCC2)nc1,2D6,"{0: 1, 1: 5, 2: 4, 3: 8, 4: 7, 5: 2, 6: 6, 7: ...",c1cnc(N2CCNCC2)nc1|CYP2D6,"[0, 5, 9, 7, 2, 10, 1, 11, 6, 8, 4, 3]"
368,c1cnc(N2CCNCC2)nc1,2C9,"{0: 5, 1: 7, 2: 6, 3: 8, 4: 4, 5: 1, 6: 3, 7: ...",c1cnc(N2CCNCC2)nc1|CYP2C9,"[5, 9, 7, 6, 8, 4, 0, 2, 10, 1, 11, 3]"

In [10]:
dict_smartcyp_sub2rank = dict(zip(df_smartcyp['sub_enz'].to_list(),smartcyp_sorted_atoms))
dict_smartcyp_sub2rank

{'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O|CYP3A4': [3,
  18,
  0,
  9,
  8,
  10,
  19,
  16,
  15,
  2,
  14,
  7,
  12,
  13,
  21,
  22,
  20,
  6,
  5,
  11,
  17,
  4,
  1],
 'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O|CYP2D6': [9,
  18,
  3,
  8,
  10,
  0,
  19,
  7,
  12,
  13,
  15,
  14,
  16,
  2,
  21,
  22,
  20,
  6,
  5,
  11,
  17,
  4,
  1],
 'CC(/C=C/C12OC1(C)CCCC2(C)C)=C\\C=C\\C(C)=C\\C(=O)O|CYP2C9': [9,
  3,
  8,
  10,
  0,
  7,
  12,
  13,
  18,
  2,
  14,
  15,
  19,
  16,
  6,
  5,
  11,
  4,
  1,
  22,
  20,
  17,
  21],
 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP3A4': [19,
  18,
  0,
  14,
  5,
  12,
  9,
  13,
  15,
  6,
  3,
  22,
  2,
  1,
  21,
  20,
  16,
  4,
  11,
  7,
  10,
  8],
 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP2D6': [19,
  0,
  14,
  18,
  13,
  15,
  5,
  12,
  3,
  6,
  9,
  22,
  2,
  1,
  21,
  20,
  16,
  4,
  11,
  7,
  10,
  8],
 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP2C9': [19,
  0,
  18,
  14,
  13,
  15,
  5,
  12,
  3,
  6,
  9,
  22,
  2,
  1,
  21,
  20,
  16,
  4,
  11,
  7,
  10,
  8],
 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1|CYP3A4': [34,
  0,
  20,
  7,
  30,
  14,
  15,
  13,
  23,
  26,
  5,
  6,
  22,
  36,
  3,
  2,
  1,
  24,
  27,
  4,
  21,
  11,
  10,
  8,
  17,
  32,
  29,
  31,
  16,
  33,
  19,
  12,
  9,
  35,
  18],
 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1|CYP2D6': [0,
  34,
  23,
  26,
  5,
  20,
  7,
  30,
  14,
  15,
  13,
  3,
  6,
  22,
  36,
  2,
  1,
  24,
  27,
  4,
  10,
  31,
  21,
  16,
  8,
  33,
  35,
  18,
  19,
  11,
  17,
  32,
  29,
  12,
  9],
 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1|CYP2C9': [0,
  23,
  26,
  22,
  30,
  34,
  20,
  5,
  3,
  7,
  6,
  14,
  15,
  13,
  36,
  2,
  24,
  1,
  27,
  21,
  4,
  32,
  29,
  31,
  19,
  33,
  18,
  17,
  16,
  8,
  35,
  12,
  9,
  10,
  11],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP3A4': [28,
  21,
  17,
  26,
  20,
  22,
  19,
  0,
  2,
  3,
  5,
  8,
  9,
  10,
  12,
  16,
  1,
  18,
  4,
  23,
  27,
  25,
  7,
  24,
  6,
  15,
  11,
  14,
  13],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP2D6': [28,
  21,
  20,
  0,
  2,
  3,
  19,
  22,
  17,
  8,
  9,
  10,
  26,
  5,
  12,
  16,
  1,
  18,
  4,
  23,
  27,
  25,
  7,
  24,
  13,
  15,
  11,
  14,
  6],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP2C9': [28,
  21,
  20,
  0,
  2,
  3,
  19,
  22,
  17,
  8,
  9,
  10,
  26,
  5,
  12,
  16,
  1,
  18,
  4,
  23,
  27,
  25,
  7,
  24,
  13,
  15,
  11,
  14,
  6],
 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1|CYP3A4': [28,
  32,
  26,
  27,
  29,
  31,
  25,
  34,
  20,
  33,
  22,
  5,
  16,
  13,
  36,
  0,
  2,
  3,
  12,
  37,
  7,
  10,
  38,
  19,
  17,
  30,
  1,
  4,
  39,
  6,
  9,
  8,
  24,
  23,
  11,
  21,
  35,
  18,
  14,
  15],
 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1|CYP2D6': [0,
  2,
  3,
  5,
  28,
  32,
  20,
  16,
  13,
  36,
  34,
  29,
  31,
  38,
  12,
  37,
  26,
  7,
  10,
  27,
  19,
  17,
  33,
  22,
  25,
  1,
  4,
  39,
  6,
  8,
  18,
  11,
  15,
  14,
  9,
  35,
  30,
  21,
  23,
  24],
 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1|CYP2C9': [28,
  32,
  27,
  26,
  29,
  31,
  25,
  34,
  20,
  0,
  2,
  3,
  33,
  22,
  16,
  19,
  17,
  5,
  13,
  36,
  38,
  12,
  37,
  7,
  10,
  30,
  1,
  35,
  18,
  23,
  21,
  24,
  4,
  15,
  39,
  14,
  6,
  11,
  8,
  9],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1|CYP3A4': [13,
  22,
  10,
  11,
  12,
  23,
  14,
  3,
  26,
  16,
  21,
  17,
  20,
  7,
  8,
  9,
  0,
  2,
  6,
  19,
  18,
  1,
  5,
  25,
  4,
  24,
  15],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1|CYP2D6': [0,
  2,
  3,
  26,
  17,
  20,
  13,
  22,
  10,
  16,
  21,
  11,
  14,
  7,
  12,
  23,
  8,
  6,
  9,
  19,
  1,
  18,
  5,
  25,
  4,
  24,
  15],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1|CYP2C9': [13,
  22,
  10,
  11,
  12,
  23,
  3,
  26,
  0,
  2,
  14,
  17,
  20,
  16,
  21,
  9,
  7,
  8,
  6,
  19,
  18,
  1,
  5,
  25,
  4,
  24,
  15],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1|CYP3A4': [13,
  21,
  10,
  11,
  12,
  22,
  14,
  16,
  20,
  3,
  25,
  7,
  8,
  9,
  18,
  0,
  2,
  17,
  19,
  6,
  1,
  5,
  24,
  15,
  4,
  23],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1|CYP2D6': [0,
  2,
  18,
  3,
  25,
  13,
  21,
  16,
  20,
  17,
  19,
  10,
  11,
  14,
  7,
  12,
  22,
  8,
  6,
  9,
  1,
  5,
  24,
  4,
  23,
  15],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1|CYP2C9': [13,
  21,
  10,
  11,
  12,
  22,
  18,
  16,
  20,
  3,
  25,
  0,
  2,
  14,
  17,
  19,
  9,
  7,
  8,
  6,
  1,
  5,
  24,
  15,
  4,
  23],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|CYP3A4': [13,
  21,
  10,
  11,
  12,
  22,
  25,
  14,
  16,
  20,
  3,
  7,
  8,
  9,
  18,
  0,
  2,
  17,
  19,
  6,
  26,
  1,
  5,
  24,
  15,
  4,
  23],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|CYP2D6': [25,
  0,
  2,
  18,
  3,
  13,
  21,
  16,
  20,
  17,
  19,
  10,
  11,
  14,
  7,
  12,
  22,
  8,
  6,
  9,
  26,
  1,
  5,
  24,
  4,
  23,
  15],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|CYP2C9': [13,
  21,
  10,
  11,
  25,
  12,
  22,
  18,
  16,
  20,
  3,
  14,
  0,
  2,
  17,
  19,
  9,
  8,
  7,
  6,
  26,
  1,
  5,
  24,
  15,
  4,
  23],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1|CYP3A4': [0,
  21,
  11,
  6,
  20,
  19,
  12,
  9,
  3,
  8,
  4,
  7,
  17,
  18,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1|CYP2D6': [0,
  21,
  20,
  11,
  19,
  6,
  12,
  17,
  18,
  8,
  7,
  9,
  4,
  3,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1|CYP2C9': [0,
  21,
  20,
  19,
  6,
  17,
  18,
  11,
  4,
  3,
  7,
  8,
  12,
  9,
  1,
  16,
  2,
  5,
  15,
  13,
  10,
  14],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O|CYP3A4': [0,
  20,
  11,
  6,
  19,
  12,
  9,
  3,
  8,
  4,
  7,
  17,
  18,
  14,
  15,
  22,
  13,
  21,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O|CYP2D6': [20,
  0,
  11,
  19,
  6,
  12,
  17,
  18,
  8,
  7,
  9,
  4,
  3,
  14,
  15,
  22,
  13,
  21,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O|CYP2C9': [20,
  0,
  19,
  6,
  17,
  18,
  11,
  4,
  3,
  7,
  8,
  12,
  9,
  22,
  21,
  1,
  16,
  2,
  5,
  15,
  13,
  10,
  14],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP3A4': [0,
  21,
  11,
  6,
  20,
  19,
  12,
  9,
  3,
  8,
  4,
  7,
  17,
  18,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP2D6': [0,
  21,
  20,
  11,
  19,
  6,
  12,
  17,
  18,
  8,
  7,
  9,
  4,
  3,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP2C9': [0,
  21,
  20,
  19,
  6,
  17,
  18,
  11,
  4,
  3,
  7,
  8,
  12,
  9,
  1,
  16,
  2,
  5,
  15,
  13,
  10,
  14],
 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP3A4': [0,
  21,
  11,
  6,
  20,
  19,
  12,
  9,
  3,
  8,
  4,
  7,
  17,
  18,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP2D6': [0,
  21,
  20,
  11,
  19,
  6,
  12,
  17,
  18,
  8,
  7,
  9,
  4,
  3,
  14,
  15,
  13,
  1,
  16,
  10,
  2,
  5],
 'CC1=C(/C=C/C(C)=C\\C=C\\C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP2C9': [0,
  21,
  20,
  19,
  6,
  17,
  18,
  11,
  4,
  3,
  7,
  8,
  12,
  9,
  1,
  16,
  2,
  5,
  15,
  13,
  10,
  14],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1|CYP3A4': [28,
  15,
  7,
  8,
  16,
  29,
  1,
  19,
  5,
  6,
  30,
  12,
  10,
  0,
  27,
  4,
  18,
  11,
  21,
  20,
  23,
  3,
  2,
  22,
  17,
  13,
  14,
  9],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1|CYP2D6': [28,
  15,
  7,
  8,
  1,
  0,
  19,
  16,
  29,
  5,
  6,
  30,
  12,
  10,
  27,
  4,
  18,
  11,
  21,
  20,
  23,
  3,
  2,
  22,
  13,
  14,
  9,
  17],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1|CYP2C9': [28,
  15,
  7,
  8,
  1,
  19,
  0,
  16,
  29,
  5,
  6,
  30,
  12,
  10,
  27,
  4,
  18,
  11,
  21,
  20,
  23,
  3,
  2,
  22,
  13,
  14,
  9,
  17],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1|CYP3A4': [29,
  7,
  15,
  8,
  22,
  16,
  30,
  1,
  5,
  19,
  6,
  31,
  12,
  10,
  0,
  28,
  4,
  18,
  11,
  3,
  21,
  20,
  2,
  24,
  23,
  17,
  13,
  9,
  14],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1|CYP2D6': [22,
  29,
  15,
  7,
  8,
  1,
  0,
  16,
  30,
  5,
  19,
  6,
  31,
  12,
  10,
  4,
  28,
  11,
  18,
  3,
  21,
  20,
  2,
  24,
  23,
  13,
  9,
  14,
  17],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1|CYP2C9': [22,
  29,
  15,
  7,
  8,
  1,
  0,
  16,
  30,
  5,
  19,
  6,
  31,
  12,
  10,
  4,
  28,
  11,
  18,
  3,
  21,
  20,
  2,
  24,
  23,
  13,
  9,
  14,
  17],
 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O|CYP3A4': [28,
  6,
  10,
  45,
  13,
  44,
  17,
  42,
  14,
  43,
  23,
  21,
  22,
  26,
  12,
  15,
  1,
  2,
  30,
  18,
  41,
  34,
  37,
  33,
  0,
  9,
  46,
  3,
  29,
  31,
  5,
  27,
  4,
  7,
  35,
  38,
  48,
  47,
  32,
  25,
  24,
  8,
  40,
  11,
  20,
  19,
  16],
 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O|CYP2D6': [28,
  1,
  30,
  6,
  10,
  45,
  17,
  42,
  13,
  44,
  14,
  43,
  0,
  23,
  21,
  22,
  2,
  26,
  12,
  15,
  3,
  34,
  37,
  29,
  18,
  41,
  31,
  33,
  5,
  27,
  4,
  9,
  46,
  7,
  35,
  38,
  48,
  47,
  8,
  19,
  11,
  16,
  32,
  25,
  24,
  40,
  20],
 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O|CYP2C9': [28,
  17,
  42,
  30,
  13,
  44,
  14,
  43,
  23,
  21,
  22,
  26,
  15,
  12,
  34,
  37,
  29,
  18,
  41,
  10,
  45,
  31,
  33,
  1,
  0,
  27,
  6,
  2,
  3,
  9,
  46,
  5,
  4,
  7,
  35,
  38,
  19,
  16,
  32,
  25,
  24,
  40,
  20,
  11,
  8,
  47,
  48],
 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP3A4': [8,
  12,
  15,
  9,
  10,
  21,
  4,
  1,
  2,
  3,
  20,
  19,
  18,
  17,
  16,
  7,
  0,
  23,
  24,
  22,
  6,
  5,
  11,
  14,
  13],
 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2D6': [21,
  8,
  1,
  12,
  15,
  9,
  0,
  2,
  10,
  4,
  3,
  20,
  19,
  18,
  17,
  16,
  7,
  23,
  24,
  22,
  13,
  5,
  6,
  11,
  14],
 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2C9': [8,
  1,
  12,
  15,
  9,
  10,
  2,
  0,
  4,
  3,
  7,
  16,
  17,
  21,
  18,
  20,
  19,
  13,
  5,
  6,
  11,
  14,
  24,
  22,
  23],
 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP3A4': [4,
  7,
  12,
  15,
  10,
  21,
  1,
  2,
  3,
  20,
  19,
  18,
  17,
  16,
  8,
  9,
  0,
  23,
  24,
  22,
  6,
  5,
  11,
  14,
  13],
 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2D6': [21,
  1,
  12,
  4,
  7,
  15,
  0,
  2,
  10,
  3,
  20,
  19,
  18,
  17,
  16,
  8,
  9,
  23,
  24,
  22,
  13,
  5,
  6,
  11,
  14],
 'CCCCCC(=O)CC[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2C9': [1,
  12,
  4,
  7,
  15,
  10,
  2,
  0,
  3,
  8,
  9,
  16,
  17,
  21,
  18,
  20,
  19,
  13,
  5,
  6,
  11,
  14,
  24,
  22,
  23],
 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F|CYP3A4': [16,
  18,
  20,
  14,
  1,
  2,
  3,
  4,
  10,
  0,
  17,
  8,
  22,
  19,
  21,
  15,
  12,
  13,
  11,
  5,
  7,
  6,
  23,
  9],
 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F|CYP2D6': [16,
  18,
  20,
  1,
  14,
  0,
  17,
  2,
  3,
  4,
  10,
  8,
  22,
  19,
  21,
  15,
  6,
  11,
  23,
  9,
  12,
  5,
  7,
  13],
 'CCCCCOC(=O)Nc1nc(=O)n([C@@H]2O[C@H](C)[C@@H](O)[C@H]2O)cc1F|CYP2C9': [1,
  16,
  18,
  2,
  0,
  3,
  20,
  17,
  4,
  14,
  10,
  8,
  22,
  19,
  21,
  15,
  5,
  7,
  6,
  23,
  9,
  13,
  11,
  12],
 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP3A4': [12,
  15,
  5,
  10,
  21,
  7,
  8,
  9,
  1,
  2,
  20,
  3,
  19,
  4,
  18,
  17,
  16,
  0,
  23,
  24,
  22,
  6,
  11,
  14,
  13],
 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2D6': [21,
  1,
  12,
  15,
  0,
  2,
  10,
  5,
  7,
  8,
  9,
  20,
  3,
  19,
  18,
  4,
  17,
  16,
  23,
  24,
  22,
  13,
  6,
  11,
  14],
 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2C9': [1,
  12,
  15,
  10,
  5,
  2,
  0,
  7,
  8,
  9,
  3,
  4,
  16,
  17,
  21,
  18,
  20,
  19,
  13,
  6,
  11,
  14,
  24,
  22,
  23],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP3A4': [22,
  20,
  24,
  21,
  6,
  2,
  30,
  19,
  25,
  1,
  10,
  32,
  27,
  26,
  13,
  0,
  23,
  31,
  4,
  33,
  18,
  5,
  7,
  3,
  9,
  8,
  16,
  17,
  29,
  11,
  28,
  15,
  14,
  12],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP2D6': [6,
  2,
  1,
  0,
  30,
  22,
  10,
  32,
  4,
  20,
  24,
  31,
  27,
  21,
  33,
  26,
  13,
  23,
  19,
  25,
  18,
  5,
  7,
  3,
  9,
  8,
  11,
  28,
  29,
  12,
  14,
  16,
  17,
  15],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP2C9': [22,
  6,
  2,
  21,
  1,
  20,
  24,
  0,
  30,
  23,
  4,
  31,
  10,
  32,
  33,
  27,
  19,
  25,
  26,
  13,
  18,
  5,
  7,
  3,
  9,
  8,
  29,
  11,
  28,
  12,
  14,
  16,
  17,
  15],
 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP3A4': [16,
  17,
  1,
  3,
  14,
  15,
  11,
  10,
  12,
  0,
  4,
  9,
  13,
  2,
  6,
  5,
  8,
  7],
 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP2D6': [11,
  0,
  4,
  1,
  3,
  16,
  10,
  12,
  17,
  9,
  13,
  2,
  14,
  15,
  6,
  5,
  8,
  7],
 'CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP2C9': [16,
  17,
  1,
  3,
  11,
  0,
  4,
  10,
  12,
  14,
  15,
  9,
  13,
  2,
  6,
  5,
  8,
  7],
 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP3A4': [1,
  3,
  2,
  10,
  8,
  22,
  6,
  4,
  7,
  16,
  0,
  19,
  5,
  20,
  21,
  18,
  9,
  17,
  15,
  14,
  12,
  13,
  11],
 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP2D6': [10,
  8,
  1,
  19,
  3,
  7,
  22,
  16,
  6,
  2,
  0,
  4,
  5,
  20,
  21,
  9,
  18,
  17,
  12,
  13,
  11,
  15,
  14],
 'CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21|CYP2C9': [1,
  10,
  8,
  3,
  2,
  7,
  0,
  6,
  19,
  4,
  16,
  22,
  5,
  9,
  20,
  21,
  18,
  17,
  12,
  13,
  15,
  11,
  14],
 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1|CYP3A4': [5,
  7,
  20,
  18,
  17,
  11,
  1,
  14,
  3,
  12,
  4,
  30,
  23,
  28,
  0,
  22,
  29,
  6,
  19,
  26,
  27,
  25,
  13,
  15,
  24,
  10,
  16,
  9,
  2,
  8,
  21],
 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1|CYP2D6': [18,
  14,
  11,
  1,
  17,
  0,
  12,
  5,
  7,
  20,
  3,
  23,
  28,
  4,
  30,
  22,
  29,
  6,
  26,
  27,
  25,
  19,
  13,
  24,
  15,
  10,
  2,
  16,
  9,
  21,
  8],
 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1|CYP2C9': [18,
  5,
  14,
  7,
  11,
  17,
  1,
  20,
  12,
  3,
  0,
  4,
  30,
  23,
  28,
  22,
  29,
  6,
  19,
  13,
  15,
  10,
  16,
  9,
  2,
  8,
  27,
  21,
  25,
  24,
  26],
 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1|CYP3A4': [7,
  12,
  14,
  13,
  22,
  1,
  11,
  16,
  5,
  4,
  8,
  19,
  18,
  0,
  15,
  25,
  28,
  21,
  26,
  27,
  6,
  20,
  24,
  2,
  3,
  23,
  9,
  17,
  10],
 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1|CYP2D6': [7,
  22,
  1,
  5,
  0,
  4,
  25,
  12,
  14,
  8,
  19,
  11,
  16,
  13,
  18,
  28,
  15,
  21,
  26,
  27,
  6,
  20,
  24,
  2,
  3,
  23,
  9,
  17,
  10],
 'CCOc1ccc(O)cc1OCCN[C@H](C)Cc1ccc(OC)c(S(N)(=O)=O)c1|CYP2C9': [7,
  12,
  1,
  14,
  22,
  5,
  13,
  11,
  0,
  4,
  8,
  16,
  15,
  19,
  18,
  25,
  28,
  6,
  2,
  3,
  9,
  10,
  21,
  20,
  26,
  27,
  17,
  23,
  24],
 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C|CYP3A4': [15,
  16,
  13,
  2,
  4,
  10,
  7,
  1,
  11,
  0,
  12,
  14,
  6,
  9,
  5,
  8,
  3],
 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C|CYP2D6': [7,
  15,
  16,
  13,
  4,
  10,
  0,
  1,
  2,
  12,
  11,
  14,
  6,
  9,
  5,
  8,
  3],
 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C|CYP2C9': [15,
  16,
  13,
  7,
  4,
  10,
  2,
  1,
  11,
  0,
  12,
  14,
  6,
  9,
  5,
  8,
  3],
 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C|CYP3A4': [14,
  15,
  12,
  2,
  4,
  6,
  1,
  9,
  10,
  5,
  0,
  11,
  13,
  8,
  7,
  3],
 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C|CYP2D6': [6,
  14,
  15,
  12,
  5,
  4,
  9,
  0,
  1,
  2,
  11,
  10,
  13,
  8,
  7,
  3],
 'CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C|CYP2C9': [14,
  15,
  12,
  6,
  4,
  9,
  2,
  5,
  1,
  10,
  0,
  11,
  13,
  8,
  7,
  3],
 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C|CYP3A4': [12,
  14,
  8,
  2,
  10,
  1,
  6,
  7,
  0,
  11,
  13,
  4,
  3,
  5,
  9],
 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C|CYP2D6': [12,
  14,
  10,
  8,
  2,
  1,
  0,
  6,
  11,
  7,
  13,
  4,
  3,
  5,
  9],
 'CC[C@@H]1C(=O)OC[C@@H]1Cc1cncn1C|CYP2C9': [12,
  14,
  10,
  8,
  2,
  1,
  6,
  0,
  11,
  7,
  13,
  4,
  3,
  5,
  9],
 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP3A4': [0,
  2,
  3,
  15,
  4,
  5,
  21,
  17,
  9,
  12,
  8,
  13,
  22,
  1,
  20,
  19,
  10,
  18,
  16,
  7,
  23,
  6,
  14],
 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6': [0,
  2,
  15,
  3,
  9,
  12,
  21,
  17,
  8,
  13,
  22,
  4,
  5,
  1,
  20,
  19,
  10,
  18,
  16,
  23,
  7,
  14,
  6],
 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2C9': [0,
  2,
  3,
  15,
  4,
  9,
  12,
  21,
  17,
  5,
  8,
  13,
  22,
  1,
  20,
  19,
  10,
  18,
  16,
  23,
  7,
  6,
  14],
 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP3A4': [0,
  2,
  3,
  15,
  4,
  5,
  21,
  17,
  9,
  12,
  8,
  13,
  22,
  1,
  20,
  19,
  10,
  18,
  16,
  7,
  23,
  6,
  14],
 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6': [0,
  2,
  15,
  3,
  9,
  12,
  21,
  17,
  8,
  13,
  22,
  4,
  5,
  1,
  20,
  19,
  10,
  18,
  16,
  23,
  7,
  14,
  6],
 'CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2C9': [0,
  2,
  3,
  15,
  4,
  9,
  12,
  21,
  17,
  5,
  8,
  13,
  22,
  1,
  20,
  19,
  10,
  18,
  16,
  23,
  7,
  6,
  14],
 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12|CYP3A4': [11,
  0,
  2,
  3,
  6,
  15,
  4,
  13,
  9,
  17,
  19,
  16,
  18,
  14,
  1,
  7,
  10,
  8,
  5,
  12,
  20],
 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12|CYP2D6': [11,
  15,
  17,
  0,
  2,
  13,
  16,
  6,
  18,
  3,
  14,
  9,
  4,
  19,
  1,
  10,
  7,
  12,
  8,
  20,
  5],
 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12|CYP2C9': [11,
  0,
  2,
  3,
  15,
  6,
  17,
  4,
  13,
  9,
  16,
  18,
  19,
  14,
  1,
  7,
  10,
  8,
  20,
  5,
  12],
 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12|CYP3A4': [0,
  2,
  3,
  6,
  14,
  4,
  12,
  9,
  10,
  16,
  18,
  15,
  17,
  13,
  1,
  7,
  8,
  11,
  5,
  19],
 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12|CYP2D6': [14,
  16,
  0,
  2,
  12,
  15,
  6,
  17,
  10,
  3,
  13,
  9,
  4,
  18,
  1,
  7,
  11,
  8,
  19,
  5],
 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12|CYP2C9': [0,
  2,
  3,
  14,
  6,
  16,
  4,
  12,
  9,
  10,
  15,
  17,
  18,
  13,
  1,
  7,
  8,
  19,
  11,
  5],
 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP3A4': [0,
  4,
  10,
  13,
  19,
  16,
  20,
  9,
  14,
  1,
  7,
  3,
  12,
  11,
  2,
  17,
  21,
  6,
  5,
  15,
  8],
 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP2D6': [0,
  19,
  4,
  10,
  13,
  20,
  1,
  16,
  9,
  14,
  7,
  3,
  12,
  11,
  2,
  17,
  21,
  6,
  5,
  15,
  8],
 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP2C9': [0,
  19,
  4,
  10,
  13,
  20,
  16,
  1,
  9,
  14,
  7,
  3,
  12,
  11,
  2,
  17,
  21,
  6,
  5,
  15,
  8],
 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1|CYP3A4': [0,
  2,
  18,
  4,
  25,
  24,
  22,
  23,
  3,
  17,
  11,
  15,
  10,
  16,
  8,
  20,
  5,
  1,
  14,
  13,
  21,
  26,
  12,
  27,
  19,
  9,
  7,
  6],
 'CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2ccccc2[nH]1|CYP2D6': [24,
  23,
  25,
  22,
  11,
  15,
  0,
  10,
  16,
  2,
  18,
  4,
  8,
  3,
  17,

In [11]:
df_smartcyp.to_pickle('./smartcyp_cyp_123.pickle')

3. somp

In [12]:
df_somp = pd.read_pickle('/home/datahouse1/wangyitian/MetaPred/30_main_products/save_code/123/somp_results_drugbank.pickle')
df_somp = df_somp[df_somp['enzyme']!='UGT']
substrates_somp = df_somp['substrates'].to_list()
substrates_somp = list(map(canonicalsmiles,substrates_somp))
df_somp['substrates'] = substrates_somp
df_somp['sub_enz'] = df_somp['substrates'] + '|CYP' + df_somp['enzyme']
scores_somp = df_somp['scores'].to_list()
somp_sorted_atoms = [[k for k, v in sorted(i.items(), key=lambda item: item[1])] for i in scores_somp]
df_somp['rank'] = somp_sorted_atoms
df_somp

,substrates,enzyme,scores,sub_enz,rank
0,C[C@H](N)Cc1ccccc1,2C9,"{0: 8, 1: 1, 2: 3, 3: 7, 4: 6, 5: 11, 6: 9, 7:...",C[C@H](N)Cc1ccccc1|CYP2C9,"[1, 8, 2, 7, 9, 4, 3, 0, 6, 10, 5]"
1,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,2D6,"{0: 11, 1: 8, 2: 17, 3: 6, 4: 7, 5: 20, 6: 19,...",N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1|CYP2D6,"[17, 20, 13, 16, 21, 3, 4, 1, 18, 8, 0, 19, 14..."
2,c1cnc(N2CCNCC2)nc1,1A2,"{0: 1, 1: 7, 2: 9, 3: 12, 4: 11, 5: 5, 6: 3, 7...",c1cnc(N2CCNCC2)nc1|CYP1A2,"[0, 7, 6, 8, 5, 9, 1, 11, 2, 10, 4, 3]"
3,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,2D6,"{0: 2, 1: 26, 2: 17, 3: 19, 4: 22, 5: 21, 6: 1...",Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,"[27, 0, 20, 9, 14, 16, 17, 28, 15, 7, 21, 26, ..."
4,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C9,"{0: 13, 1: 23, 2: 19, 3: 18, 4: 10, 5: 11, 6: ...",O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O|...,"[21, 7, 16, 8, 9, 15, 22, 17, 20, 4, 5, 14, 0,..."
...,...,...,...,...,...
694,CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC1,2D6,"{0: 2, 1: 16, 2: 20, 3: 9, 4: 10, 5: 5, 6: 11,...",CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC...,"[21, 0, 20, 19, 5, 8, 17, 18, 3, 4, 6, 11, 7, ..."
695,O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...,2C9,"{0: 10, 1: 20, 2: 1, 3: 5, 4: 24, 5: 6, 6: 18,...",O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...,"[2, 20, 7, 21, 3, 5, 12, 17, 22, 0, 27, 28, 19..."
696,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,3A4,"{0: 18, 1: 1, 2: 16, 3: 17, 4: 27, 5: 11, 6: 1...",CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,"[1, 20, 12, 22, 13, 19, 23, 18, 21, 26, 5, 6, ..."
698,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,3A4,"{0: 14, 1: 21, 2: 1, 3: 13, 4: 24, 5: 23, 6: 6...",O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|CYP3A4,"[2, 20, 16, 8, 7, 6, 17, 13, 9, 22, 23, 24, 3,..."
700,O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O,2C19,"{0: 8, 1: 18, 2: 21, 3: 14, 4: 5, 5: 3, 6: 16,...",O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O|...,"[21, 16, 5, 15, 4, 17, 14, 0, 8, 9, 10, 19, 7,..."

In [13]:
df_somp.to_pickle('./somp_cyp_123.pickle')

In [14]:
dict_somp_sub2rank = dict(zip(df_somp['sub_enz'].to_list(),somp_sorted_atoms))
dict_somp_sub2rank

{'C[C@H](N)Cc1ccccc1|CYP2C9': [1, 8, 2, 7, 9, 4, 3, 0, 6, 10, 5],
 'N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1|CYP2D6': [17,
  20,
  13,
  16,
  21,
  3,
  4,
  1,
  18,
  8,
  0,
  19,
  14,
  12,
  7,
  11,
  2,
  15,
  6,
  5,
  10,
  9],
 'c1cnc(N2CCNCC2)nc1|CYP1A2': [0, 7, 6, 8, 5, 9, 1, 11, 2, 10, 4, 3],
 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1|CYP2D6': [27,
  0,
  20,
  9,
  14,
  16,
  17,
  28,
  15,
  7,
  21,
  26,
  25,
  30,
  24,
  31,
  2,
  6,
  3,
  10,
  5,
  4,
  8,
  13,
  19,
  1,
  22,
  12,
  18,
  32,
  23,
  11,
  29],
 'O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O|CYP2C9': [21,
  7,
  16,
  8,
  9,
  15,
  22,
  17,
  20,
  4,
  5,
  14,
  0,
  19,
  10,
  18,
  6,
  3,
  2,
  13,
  11,
  12,
  1],
 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1|CYP1A2': [14,
  4,
  20,
  0,
  23,
  19,
  6,
  7,
  8,
  9,
  5,
  21,
  15,
  10,
  11,
  2,
  13,
  17,
  18,
  24,
  22,
  1,
  3,
  16,
  25,
  12],
 'COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(CCN(C)C)c1cccc2ccccc12|CYP3A4': [26,
  27,
  24,
  0,
  34,
  30,
  17,
  19,
  31,
  25,
  33,
  18,
  21,
  35,
  14,
  29,
  36,
  11,
  13,
  16,
  20,
  23,
  3,
  5,
  6,
  2,
  15,
  32,
  7,
  9,
  28,
  22,
  12,
  37,
  8,
  1,
  4,
  10],
 'O=c1[nH]c(=O)c2[nH]cnc2[nH]1|CYP2D6': [8, 4, 3, 6, 0, 1, 5, 9, 7, 2, 10],
 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)([C@@H](O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1|CYP2C9': [0,
  37,
  23,
  26,
  43,
  24,
  30,
  33,
  36,
  39,
  42,
  20,
  29,
  28,
  4,
  14,
  3,
  13,
  9,
  44,
  31,
  5,
  38,
  41,
  35,
  25,
  21,
  32,
  34,
  22,
  19,
  12,
  16,
  11,
  15,
  40,
  27,
  8,
  1,
  10,
  18,
  17,
  2,
  7,
  6],
 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@@]21C|CYP1A2': [31,
  25,
  1,
  18,
  22,
  11,
  21,
  2,
  9,
  13,
  15,
  20,
  23,
  30,
  10,
  0,
  28,
  14,
  32,
  26,
  16,
  19,
  34,
  17,
  27,
  29,
  12,
  3,
  4,
  5,
  33,
  8,
  24,
  6,
  7],
 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP3A4': [4,
  1,
  0,
  3,
  2,
  22,
  21,
  5,
  20,
  24,
  6,
  11,
  13,
  19,
  23,
  8,
  25,
  9,
  12,
  15,
  26,
  18,
  17,
  10,
  16,
  27,
  7,
  14,
  28],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP1A2': [21,
  0,
  2,
  1,
  8,
  3,
  19,
  20,
  5,
  4,
  6,
  11,
  17,
  18,
  13,
  7,
  9,
  10,
  16,
  12,
  14,
  15],
 'O=C1Nc2ccc([N+](=O)[O-])cc2C(c2ccccc2Cl)=NC1O|CYP3A4': [21,
  16,
  15,
  17,
  4,
  5,
  14,
  10,
  3,
  0,
  8,
  9,
  19,
  18,
  22,
  6,
  20,
  2,
  7,
  13,
  12,
  1,
  11],
 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(NCCO)cc3)n2)cc1|CYP2D6': [21,
  22,
  18,
  24,
  8,
  27,
  2,
  7,
  28,
  17,
  25,
  11,
  0,
  20,
  19,
  4,
  12,
  16,
  1,
  6,
  9,
  5,
  23,
  13,
  3,
  10,
  15,
  14,
  26],
 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@@]21C|CYP3A4': [10,
  4,
  1,
  33,
  0,
  23,
  16,
  2,
  9,
  13,
  15,
  17,
  21,
  24,
  31,
  27,
  32,
  26,
  11,
  29,
  35,
  3,
  5,
  20,
  19,
  12,
  22,
  8,
  30,
  14,
  28,
  6,
  34,
  18,
  25,
  7],
 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C|CYP2D6': [17,
  18,
  8,
  1,
  0,
  15,
  5,
  11,
  3,
  13,
  2,
  16,
  12,
  14,
  4,
  6,
  9,
  7,
  10],
 'O=C(C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1)OC1OC(C(=O)O)C(O)C(O)C1O|CYP2C9': [23,
  41,
  4,
  8,
  24,
  39,
  15,
  20,
  43,
  33,
  25,
  36,
  30,
  31,
  22,
  16,
  19,
  27,
  7,
  0,
  35,
  34,
  1,
  32,
  37,
  3,
  29,
  11,
  18,
  17,
  2,
  38,
  40,
  42,
  44,
  5,
  9,
  14,
  10,
  6,
  13,
  12,
  26,
  28,
  21],
 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2C9': [0,
  1,
  7,
  12,
  2,
  8,
  11,
  20,
  21,
  18,
  19,
  14,
  4,
  3,
  9,
  10,
  16,
  13,
  17,
  6,
  15,
  5,
  22],
 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1|CYP2C19': [12,
  1,
  8,
  15,
  0,
  4,
  22,
  6,
  7,
  5,
  24,
  31,
  13,
  3,
  21,
  25,
  30,
  18,
  27,
  32,
  19,
  23,
  16,
  14,
  28,
  26,
  9,
  17,
  29,
  20,
  11,
  10,
  2],
 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O|CYP2C19': [18,
  0,
  2,
  5,
  16,
  19,
  15,
  1,
  11,
  4,
  10,
  7,
  9,
  8,
  14,
  17,
  13,
  12,
  20,
  3,
  6],
 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1|CYP2C9': [8,
  0,
  15,
  18,
  20,
  3,
  4,
  2,
  23,
  9,
  12,
  14,
  13,
  16,
  1,
  19,
  17,
  6,
  5,
  10,
  11,
  22,
  21,
  7],
 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1|CYP1A2': [2,
  7,
  9,
  15,
  8,
  6,
  10,
  16,
  12,
  0,
  3,
  5,
  1,
  14,
  17,
  13,
  4,
  11,
  18],
 'O=C1CN=C(c2ccccc2Cl)c2cc([N+](=O)[O-])ccc2N1|CYP1A2': [2,
  8,
  7,
  9,
  19,
  18,
  6,
  13,
  20,
  0,
  16,
  17,
  15,
  1,
  5,
  10,
  3,
  11,
  14,
  12,
  21,
  4],
 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12|CYP2D6': [15,
  0,
  29,
  7,
  8,
  11,
  1,
  9,
  10,
  16,
  22,
  23,
  28,
  17,
  3,
  14,
  13,
  25,
  21,
  34,
  30,
  2,
  27,
  6,
  4,
  12,
  5,
  19,
  18,
  32,
  33,
  26,
  24,
  31,
  20],
 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1|CYP2D6': [0,
  25,
  42,
  5,
  17,
  3,
  29,
  32,
  35,
  38,
  41,
  14,
  28,
  4,
  20,
  13,
  27,
  23,
  11,
  15,
  8,
  24,
  21,
  31,
  9,
  40,
  10,
  34,
  2,
  33,
  12,
  16,
  18,
  36,
  37,
  22,
  19,
  26,
  39,
  30,
  6,
  1,
  7,
  43],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP2C19': [30,
  22,
  6,
  2,
  0,
  1,
  31,
  15,
  23,
  27,
  19,
  25,
  20,
  24,
  7,
  21,
  26,
  3,
  5,
  13,
  8,
  12,
  4,
  9,
  16,
  17,
  32,
  10,
  33,
  18,
  28,
  11,
  14,
  29],
 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1|CYP3A4': [12,
  5,
  0,
  14,
  16,
  17,
  21,
  13,
  23,
  30,
  15,
  20,
  3,
  24,
  29,
  9,
  26,
  8,
  7,
  2,
  19,
  27,
  25,
  22,
  4,
  6,
  28,
  1,
  11,
  18,
  10],
 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1|CYP2D6': [0,
  12,
  5,
  14,
  17,
  21,
  16,
  23,
  30,
  15,
  3,
  24,
  29,
  13,
  22,
  9,
  8,
  20,
  26,
  4,
  19,
  27,
  25,
  6,
  28,
  11,
  2,
  1,
  7,
  10,
  18],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|CYP2C9': [11,
  10,
  18,
  6,
  7,
  3,
  14,
  25,
  9,
  8,
  16,
  20,
  5,
  24,
  0,
  2,
  12,
  22,
  13,
  21,
  26,
  1,
  17,
  19,
  15,
  4,
  23],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP2D6': [30,
  2,
  0,
  22,
  1,
  6,
  31,
  19,
  25,
  23,
  15,
  20,
  24,
  7,
  21,
  13,
  27,
  26,
  3,
  5,
  9,
  4,
  16,
  17,
  10,
  18,
  28,
  8,
  12,
  32,
  11,
  14,
  33,
  29],
 'Nc1nc(=O)c2[nH]cnc2[nH]1|CYP3A4': [8, 7, 6, 4, 3, 5, 9, 0, 2, 1, 10],
 'COc1nc(N)nc2[nH]cnc12|CYP2D6': [10, 0, 5, 4, 3, 1, 2, 7, 9, 6, 8, 11],
 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12|CYP2C9': [30,
  2,
  21,
  22,
  0,
  15,
  18,
  1,
  6,
  33,
  31,
  4,
  16,
  17,
  23,
  32,
  9,
  10,
  27,
  19,
  25,
  26,
  20,
  24,
  13,
  3,
  7,
  5,
  12,
  8,
  29,
  28,
  11,
  14],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP1A2': [21,
  20,
  22,
  19,
  26,
  16,
  1,
  7,
  0,
  2,
  3,
  8,
  9,
  10,
  5,
  13,
  4,
  15,
  6,
  25,
  14,
  27,
  28,
  12,
  24,
  23,
  17,
  18,
  11],
 'COc1cc(C)c2[nH]ccc2c1CN1CC[C@H](O)C[C@H]1c1ccc(C(=O)O)cc1|CYP1A2': [12,
  0,
  15,
  14,
  16,
  5,
  23,
  30,
  9,
  17,
  21,
  24,
  29,
  8,
  19,
  3,
  26,
  13,
  20,
  22,
  25,
  27,
  2,
  18,
  4,
  11,
  6,
  28,
  1,
  10,
  7],
 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12|CYP2C19': [1,
  14,
  25,
  37,
  36,
  0,
  2,
  5,
  16,
  20,
  35,
  38,
  26,
  17,
  6,
  13,
  34,
  32,
  15,
  27,
  7,
  33,
  23,
  19,
  4,
  10,
  9,
  22,
  11,
  18,
  29,
  8,
  21,
  30,
  12,
  24,
  3,
  31,
  28],
 'O=S1(=O)CCNCN1|CYP2C19': [1, 4, 6, 0, 2, 5, 7, 3],
 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1|CYP2C19': [27,
  20,
  0,
  14,
  28,
  16,
  15,
  17,
  9,
  7,
  5,
  25,
  30,
  26,
  21,
  6,
  8,
  13,
  2,
  3,
  10,
  4,
  1,
  24,
  31,
  18,
  19,
  22,
  11,
  12,
  32,
  23,
  29],
 'O=c1[nH]c(=O)n(C2OC(COP(=O)(O)O)C(O)C2O)cc1F|CYP1A2': [6,
  9,
  15,
  11,
  8,
  13,
  14,
  12,
  17,
  10,
  16,
  18,
  19,
  7,
  3,
  4,
  21,
  0,
  20,
  1,
  5,
  2],
 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O|CYP2D6': [0,
  2,
  5,
  16,
  19,
  4,
  1,
  18,
  7,
  15,
  9,
  11,
  14,
  17,
  13,
  20,
  10,
  8,
  12,
  3,
  6],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@@H](O)O[C@@H]3O[C@]4(C)CC[C@@H]1[C@]23OO4|CYP2C19': [3,
  19,
  18,
  17,
  4,
  0,
  20,
  9,
  10,
  2,
  6,
  8,
  11,
  15,
  22,
  25,
  1,
  5,
  14,
  24,
  21,
  16,
  7,
  13,
  23,
  12],
 'O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1|CYP2C9': [1,
  10,
  5,
  7,
  6,
  14,
  15,
  4,
  8,
  13,
  16,
  0,
  2,
  11,
  12,
  3,
  9],
 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(=O)CO)C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1|CYP3A4': [0,
  25,
  4,
  37,
  3,
  29,
  32,
  35,
  38,
  41,
  28,
  42,
  20,
  27,
  14,
  5,
  31,
  40,
  34,
  13,
  36,
  17,
  33,
  23,
  11,
  15,
  21,
  9,
  24,
  8,
  10,
  12,
  22,
  2,
  19,
  18,
  16,
  39,
  30,
  26,
  6,
  7,
  43,
  1],
 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccc(O)cc2[nH]1|CYP2D6': [14,
  4,
  20,
  0,
  23,
  9,
  21,
  19,
  10,
  6,
  7,
  8,
  5,
  15,
  11,
  22,
  2,
  18,
  17,
  24,
  13,
  16,
  3,
  1,
  12,
  25],
 'N#Cc1ccc2c(c1)CO[C@@]2(CCC=O)c1ccc(F)cc1|CYP2C9': [13,
  14,
  16,
  21,
  12,
  17,
  20,
  3,
  4,
  11,
  1,
  0,
  8,
  18,
  19,
  7,
  2,
  9,
  15,
  6,
  10,
  5],
 'CCCCC[C@H](O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP2D6': [1,
  21,
  22,
  0,
  2,
  3,
  20,
  6,
  11,
  13,
  19,
  24,
  5,
  23,
  4,
  9,
  12,
  25,
  15,
  8,
  17,
  26,
  16,
  10,
  18,
  27,
  14,
  7,
  28],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C\\C(=O)O)C(C)(C)CCC1|CYP3A4': [21,
  0,
  2,
  1,
  19,
  20,
  8,
  3,
  17,
  18,
  4,
  5,
  6,
  11,
  7,
  9,
  13,
  16,
  10,
  12,
  14,
  15],
 'C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43C)[C@@H]1CC=C2c1cccnc1|CYP2C19': [15,
  3,
  26,
  2,
  28,
  5,
  7,
  13,
  20,
  12,
  22,
  21,
  11,
  16,
  9,
  0,
  25,
  8,
  18,
  23,
  24,
  29,
  27,
  1,
  10,
  19,
  17,
  6,
  4,
  14],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1|CYP2C9': [4,
  23,
  17,
  13,
  1,
  0,
  11,
  16,
  5,
  2,
  8,
  30,
  32,
  6,
  20,
  29,
  3,
  31,
  26,
  27,
  28,
  7,
  10,
  9,
  22,
  14,
  18,
  12,
  19,
  15,
  25,
  24,
  21],
 'C[C@H](N)Cc1ccccc1|CYP1A2': [8, 7, 9, 2, 4, 6, 10, 1, 0, 5, 3],
 'CCCCCC(=O)/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(=O)O|CYP3A4': [1,
  0,
  4,
  2,
  3,
  21,
  20,
  7,
  19,
  8,
  23,
  5,
  10,
  12,
  18,
  22,
  24,
  14,
  11,
  6,
  25,
  17,
  16,
  9,
  15,
  26,
  13,
  27],
 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(NCCO)cc3)n2)cc1|CYP2C19': [21,
  22,
  18,
  24,
  11,
  2,
  17,
  25,
  8,
  27,
  0,
  13,
  7,
  28,
  16,
  19,
  20,
  12,
  1,
  9,
  15,
  26,
  10,
  14,
  4,
  6,
  23,
  5,
  3],
 'O=C1CC(=O)N(c2ccccc2)c2cc(Cl)ccc2N1|CYP3A4': [16,
  9,
  8,
  10,
  13,
  17,
  7,
  11,
  2,
  14,
  6,
  4,
  0,
  3,
  15,
  1,
  12,
  18,
  19,
  5],
 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F|CYP2D6': [0,
  7,
  11,
  16,
  17,
  4,
  8,
  10,
  3,
  6,
  19,
  20,
  21,
  22,
  5,
  9,
  12,
  18,
  2,
  1,
  13,
  15,
  14],
 'Nc1nc(=O)c2[nH]cnc2[nH]1|CYP2C9': [7, 9, 0, 4, 6, 8, 3, 5, 2, 10, 1],
 'N#Cc1ccc2c(c1)COC2(CCC=O)c1ccc(F)cc1|CYP1A2': [13,
  17,
  20,
  16,
  21,
  12,
  4,
  3,
  11,
  14,
  8,
  18,
  1,
  7,
  19,
  0,
  15,
  2,
  6,
  5,
  10,
  9],
 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl|CYP3A4': [23,
  18,
  16,
  28,
  0,
  22,
  11,
  33,
  19,
  20,
  21,
  24,
  25,
  17,
  8,
  29,
  10,
  2,
  3,
  4,
  9,
  13,
  35,
  5,
  32,
  6,
  34,
  14,
  12,
  7,
  1,
  26,
  31,
  30,
  27,
  15],
 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)n2)cc1|CYP2C19': [22,
  24,
  21,
  11,
  2,
  8,
  30,
  0,
  17,
  28,
  25,
  13,
  26,
  16,
  7,
  31,
  19,
  18,
  27,
  20,
  12,
  1,
  29,
  9,
  15,
  10,
  4,
  14,
  23,
  6,
  5,
  3],
 'c1cnc(N2CCNCC2)nc1|CYP2D6': [0, 5, 9, 6, 8, 1, 11, 7, 3, 2, 10, 4],
 'CCO[C@H]1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)[C@H](c2ccc(C(=O)O)cc2)C1|CYP2C9': [7,
  15,
  1,
  12,
  8,
  6,
  5,
  4,
  22,
  0,
  3,
  13,
  24,
  31,
  25,
  30,
  32,
  18,
  27,
  20,
  21,
  28,
  23,
  14,
  26,
  19,
  2,
  10,
  29,
  11,
  17,
  16,
  9],
 'Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1|CYP2C19': [14,
  0,
  21,
  9,
  4,
  20,
  19,
  22,
  5,
  6,
  7,
  8,
  15,
  10,
  11,
  2,
  1,
  18,
  17,
  23,
  12,
  3,
  24,
  13,
  16],
 'OC(Cl)(Cl)C(c1ccc(Cl)cc1)c1ccccc1Cl|CYP3A4': [7,
  10,
  16,
  14,
  15,
  1,
  2,
  3,
  13,
  6,
  11,
  4,
  0,
  8,
  5,
  9,
  12,
  18,
  17],
 'O=c1[nH]c(=O)n(C2CC(O)C(CO)O2)cc1F|CYP1A2': [6,
  11,
  10,
  8,
  7,
  12,
  9,
  14,
  13,
  3,
  4,
  16,
  0,
  15,
  1,
  5,
  2],
 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3C(=O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@@]21C|CYP2C9': [11,
  25,
  31,
  1,
  22,
  2,
  9,
  13,
  15,
  20,
  23,
  30,
  10,
  0,
  32,
  18,
  26,
  21,
  28,
  34,
  19,
  3,
  17,
  4,
  14,
  16,
  8,
  27,
  12,
  5,
  29,
  24,
  33,
  6,
  7],
 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1|CYP2D6': [1,
  12,
  13,
  24,
  19,
  18,
  5,
  27,
  20,
  6,
  8,
  22,
  26,
  15,
  7,
  9,
  2,
  3,
  0,
  14,
  16,
  23,
  10,
  11,
  25,
  21,
  4,
  17],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1|CYP2D6': [1,
  0,
  5,
  2,
  29,
  8,
  12,
  16,
  28,
  31,
  19,
  30,
  6,
  3,
  4,
  20,
  13,
  7,
  17,
  24,
  25,
  26,
  27,
  18,
  10,
  22,
  11,
  14,
  23,
  21,
  15,
  9],
 'C[C@H](N)Cc1ccc(O)cc1|CYP3A4': [1, 7, 10, 4, 2, 0, 8, 6, 11, 3, 5, 9],
 'O=S1(=O)CCNCN1|CYP2D6': [1, 6, 4, 0, 2, 5, 7, 3],
 'O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O|CYP2D6': [14,
  23,
  13,
  15,
  22,
  24,
  11,
  20,
  12,
  16,
  21,
  25,
  9,
  27,
  7,
  18,
  17,
  3,
  8,
  26,
  6,
  10,
  19,
  5,
  0,
  1,
  4,
  2],
 'O=c1[nH]c(=O)n(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)cc1F|CYP2C9': [9,
  12,
  14,
  15,
  16,
  19,
  13,
  17,
  18,
  11,
  8,
  10,
  21,
  7,
  6,
  25,
  0,
  5,
  20,
  22,
  4,
  23,
  2,
  24,
  3,
  1],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP2C9': [8,
  9,
  10,
  0,
  2,
  3,
  21,
  20,
  26,
  7,
  22,
  1,
  13,
  25,
  14,
  19,
  5,
  12,
  6,
  28,
  4,
  24,
  17,
  27,
  16,
  23,
  11,
  15,
  18],
 'O=c1[nH]c(=O)n(C2CC(O)C(CO)O2)cc1F|CYP2C19': [10,
  11,
  8,
  7,
  6,
  12,
  9,
  13,
  0,
  16,
  4,
  14,
  15,
  3,
  1,
  5,
  2],
 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1|CYP1A2': [3,
  26,
  10,
  7,
  18,
  9,
  11,
  0,
  2,
  8,
  1,
  12,
  23,
  13,
  22,
  17,
  20,
  4,
  24,
  14,
  5,
  25,
  15,
  19,
  16,
  21,
  6],
 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(NCCO)cc3)n2)cc1|CYP3A4': [21,
  22,
  1,
  18,
  24,
  2,
  8,
  27,
  7,
  28,
  17,
  25,
  11,
  4,
  0,
  20,
  19,
  12,
  13,
  6,
  16,
  5,
  3,
  26,
  9,
  23,
  10,
  15,
  14],
 'CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C|CYP2C9': [17,
  18,
  16,
  15,
  0,
  14,
  12,
  1,
  3,
  13,
  8,
  2,
  5,
  11,
  7,
  10,
  4,
  6,
  9],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O|CYP3A4': [20,
  0,
  2,
  19,
  8,
  21,
  3,
  17,
  18,
  1,
  4,
  5,
  6,
  11,
  7,
  9,
  13,
  10,
  12,
  16,
  22,
  14,
  15],
 'C[C@@H]1CC[C@H]2[C@@H](C)[C@@H](O)O[C@@H]3O[C@]4(C)CC[C@@H]1[C@]23OO4|CYP3A4': [20,
  0,
  10,
  3,
  9,
  2,
  6,
  8,
  11,
  15,
  22,
  4,
  1,
  19,
  7,
  18,
  5,
  17,
  21,
  12,
  14,
  13,
  24,
  23,
  25,
  16],
 'O=c1[nH]c(=O)n(C2OC(CO)C(O)C2O)cc1F|CYP1A2': [6,
  9,
  11,
  8,
  13,
  10,
  12,
  14,
  15,
  7,
  3,
  4,
  17,
  0,
  16,
  1,
  5,
  2],
 'O=C(O)c1cc(/N=N/c2ccc(O)c(C(=O)O)c2)ccc1O|CYP3A4': [10,
  19,
  9,
  18,
  11,
  20,
  4,
  17,
  5,
  8,
  1,
  14,
  0,
  15,
  3,
  13,
  6,
  7,
  2,
  12,
  16,
  21],
 'CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1|CYP2C9': [4,
  17,
  13,
  1,
  0,
  11,
  16,
  5,
  2,
  8,
  29,
  31,
  6,
  20,
  3,
  28,
  30,
  25,
  26,
  27,
  7,
  10,
  9,
  22,
  14,
  21,
  23,
  18,
  12,
  19,
  15,
  24],
 'O=C(O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1|CYP2C19': [19,
  21,
  18,
  22,
  8,
  5,
  26,
  14,
  24,
  4,
  27,
  10,
  13,
  17,
  1,
  9,
  15,
  23,
  16,
  6,
  25,
  7,
  12,
  11,
  20,
  0,
  3,
  2],
 'C[C@H]1O[C@@H](n2cc(F)c(N)nc2=O)[C@H](O)[C@@H]1O|CYP3A4': [2,
  5,
  16,
  19,
  0,
  18,
  11,
  12,
  7,
  1,
  9,
  14,
  4,
  10,
  15,
  13,
  8,
  20,
  17,
  6,
  3],
 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1=O|CYP2C9': [0,
  2,
  21,
  20,
  19,
  1,
  17,
  18,
  3,
  8,
  5,
  6,
  11,
  4,
  22,
  7,
  10,
  9,
  16,
  13,
  12,
  14,
  15],
 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O|CYP2C19': [21,
  20,
  22,
  8,
  9,
  10,
  26,
  19,
  0,
  2,
  3,
  25,
  7,
  1,
  5,
  13,
  14,
  24,
  15,
  23,
  6,
  4,
  16,
  18,
  12,
  17,
  11,
  27,
  28],
 'O=C(O)c1cc(/N=N/c2ccc(O)c(C(=O)O)c2)ccc1O|CYP2C9': [6,
  7,
  10,
  19,
  9,
  18,
  4,
  17,
  1,
  14,
  11,
  20,
  5,
  8,
  0,
  15,
  3,
  13,
  12,
  21,
  2,
  16],
 'O=c1[nH]c(=O)n(C2CC(O)C(COP(=O)(O)OP(=O)(O)O)O2)cc1F|CYP2C9': [11,
  10,
  14,
  16,
  17,
  18,
  8,
  15,
  19,
  20,
  13,
  12,
  21,
  7,
  6,
  5,
  24,
  9,
  0,
  4,
  22,
  2,
  23,
  3,
  1],
 'O=c1[nH]cc(F)c(=O)[nH]1|CYP1A2': [3, 0, 4, 5, 1, 2, 7, 6, 8],
 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1|CYP2D6': [30,
  34,
  5,
  6,
  22,
  23,
  26,
  0,
  3,
  7,
  33,
  25,
  24,
  31,
  1,
  36,
  14,
  15,
  32,
  18,
  29,
  28,
  11,
  13,
  35,
  21,
  19,
  27,
  20,
  17,
  16,
  8,
  9,
  2,
  10,
  12,
  4],
 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O[C@@H]3O[C@H](C(=O)O)[C@@H](O)[C@H](O)[C@H]3O)cc2[nH]1|CYP1A2': [14,
  4,
  31,
  20,
  34,
  24,
  27,
  32,
  35,
  38,
  0,
  37,
  28,
  19,
  26,
  23,
  6,
  7,
  8,
  9,
  5,
  40,
  21,
  29,
  10,
  15,
  11,
  33,
  30,
  25,
  36,
  39,
  2,
  13,
  17,
  18,
  22,
  3,
  1,
  41,
  16,
  42,
  12],
 'O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2)C1=O|CYP2C9': [10,
  19,
  14,
  23,
  13,
  15,
  22,
  24,
  17,
  11,
  20,
  4,
  8,
  26,
  9,
  27,
  7,
  12,
  16,
  21,
  25,
  6,
  18,
  3,
  0,
  5,
  2,
  1],
 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O|CYP3A4': [2,
  1,
  21,
  3,
  35,
  0,
  38,
  27,
  13,
  14,
  44,
  45,
  18,
  42,
  23,
  34,
  17,
  43,
  9,
  47,
  10,
  46,
  11,
  28,
  19,
  12,
  15,
  29,
  6,
  24,
  16,
  8,
  31,
  30,
  49,
  48,
  22,
  36,
  40,
  5,
  37,
  32,
  39,
  4,
  33,
  7,
  20,
  25,
  26,
  41],
 'C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)Nc4cccc(C(=O)O)c4)C3)[C@H](C)[C@H]12|CYP3A4': [1,
  14,
  25,
  36,
  37,
  17,
  0,
  2,
  5,
  16,
  20,
  35,
  38,
  26,
  27,
  34,
  15,
  19,
  32,
  6,
  8,
  33,
  13,
  7,
  4,
  10,
  9,
  29,
  18,
  11,
  23,
  22,
  30,
  21,
  3,
  12,
  31,
  24,
  28],
 'O=c1[nH]cc(F)c(=O)[nH]1|CYP2C9': [5, 7, 0, 2, 4, 3, 1, 6, 8],
 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12|CYP2C19': [0,
  2,
  13,
  3,
  1,
  12,
  17,
  15,
  9,
  10,
  14,
  4,
  16,
  11,
  18,
  6,
  5,
  8,
  7,
  19],
 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C(O)CO)CC3|CYP2D6': [0,
  25,
  10,
  5,
  3,
  23,
  28,
  4,
  17,
  14,
  27,
  8,
  20,
  13,
  15,
  9,
  11,
  2,
  18,
  19,
  12,
  16,
  26,
  22,
  24,
  21,
  6,
  1,
  7],
 'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2|CYP3A4': [19,
  5,
  14,
  9,
  13,
  15,
  0,
  12,
  6,
  3,
  1,
  21,
  18,
  7,
  4,
  2,
  17,
  20,
  16,
  22,
  11,
  10,
  8],
 'O=c1[nH]c(=O)n(C2CC(O)C(CO)O2)cc1F|CYP2C9': [11,
  10,
  8,
  12,
  13,
  7,
  6,
  5,
  9,
  16,
  0,
  4,
  14,
  15,
  2,
  3,
  1],
 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1|CYP2C9': [0,
  17,
  18,
  1,
  15,
  12,

4. 整理结果

In [15]:
substrates_total = df['sub_enz'].to_list()
rank_smartcyp = [dict_smartcyp_sub2rank.get(i,'None') for i in substrates_total]
rank_somp= [dict_somp_sub2rank.get(i,'None') for i in substrates_total]
df['rank_smartcyp'] = rank_smartcyp
df['rank_somp'] = rank_somp
df

,Unnamed: 0,substrate,Enzyme,truth,site_truth,site_predict,site_truth_atomidx,predict_site_atomidx,sub_enz,rank_smartcyp,rank_somp
0,0,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CYP3A4,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(NC(=O)c2c[nH]c3c...,[10],"[[10], [10], [21], [20], [23], [10, 12], [18, ...",CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,"[28, 21, 17, 26, 20, 22, 19, 0, 2, 3, 5, 8, 9,...","[0, 2, 3, 8, 9, 10, 21, 20, 19, 26, 7, 22, 1, ..."
1,1,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CYP3A4,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"[[39], [32], [27, 30, 31, 32], [30, 31], [30, ...",CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,"[28, 32, 26, 27, 29, 31, 25, 34, 20, 33, 22, 5...","[26, 20, 0, 2, 3, 25, 1, 28, 32, 12, 37, 29, 3..."
2,2,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1,CYP3A4,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O|...,CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)[CH2...,CC1(C)CC(=O)N(CCCC[N:1]2CCN(c3ncccn3)CC2)C(=O)...,"[25, 11]","[[11], [18], [2, 11], [11], [25], [2], [14], [...",CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1|C...,"[13, 21, 10, 11, 12, 22, 14, 16, 20, 3, 25, 7,...","[10, 3, 25, 18, 7, 11, 12, 22, 13, 21, 0, 2, 9..."
3,3,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CYP2C9,CC1=C(/C=C/C(C)=C\C=C\C(C)=C\C(=O)O)C(C)(C)CCC1,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CC(/C=C/C1=C([CH3:1])CCCC1(C)C)=C\C=C\C(C)=C\C...,[],"[[6], [21], [4, 5], [20], [21], [19], [20], []...",CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC...,"[0, 21, 20, 19, 6, 17, 18, 11, 4, 3, 7, 8, 12,...","[21, 0, 2, 1, 19, 20, 17, 18, 8, 5, 6, 11, 3, ..."
4,4,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CYP3A4,CC1=C(/C=C/C(C)=C/C=C/C(C)=C\C(=O)O)C(C)(C)CCC...,CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC1,CC(/C=C/C1=C([CH3:1])CCCC1(C)C)=C\C=C\C(C)=C\C...,[],"[[6], [21], [4, 5], [20], [21], [19], [20], []...",CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C(=O)O)C(C)(C)CCC...,"[0, 21, 11, 6, 20, 19, 12, 9, 3, 8, 4, 7, 17, ...","[21, 0, 2, 1, 19, 20, 8, 3, 17, 18, 4, 5, 6, 1..."
5,5,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP1A2,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,None,"[23, 1, 0, 5, 31, 2, 8, 29, 32, 16, 6, 30, 12,..."
6,6,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP2D6,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,"[22, 29, 15, 7, 8, 1, 0, 16, 30, 5, 19, 6, 31,...","[23, 1, 0, 5, 2, 30, 8, 12, 16, 29, 32, 19, 31..."
7,7,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CYP3A4,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc([O:1]C)c(C...,[],"[[21], [4], [20, 21, 29, 30], [17, 18, 19, 20,...",CCC(=O)N1CC[C@H](Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(...,"[29, 7, 15, 8, 22, 16, 30, 1, 5, 19, 6, 31, 12...","[5, 32, 23, 0, 16, 1, 30, 2, 29, 31, 8, 4, 6, ..."
8,8,CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](...,CYP3A4,CC(O)C(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@@H]5CO[...,CC(n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](Cn6...,CCC(C)[n:1]1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[...,[47],"[[4], [47], [22, 40], [47], [4], [48], [47], [...",CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC[C@H]5CO[C@](...,"[28, 6, 10, 45, 13, 44, 17, 42, 14, 43, 23, 21...","[2, 1, 21, 3, 35, 0, 38, 27, 13, 14, 44, 45, 1..."
9,9,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC...,CYP3A4,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCNCC4)cc...,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CC[N:1](C...,CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CC[N:1](C...,[21],"[[21], [24], [21], [22], [25], [21, 24], [21],...",CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC...,"[22, 20, 24, 21, 6, 2, 30, 19, 25, 1, 10, 32, ...","[22, 30, 0, 2, 1, 6, 31, 23, 27, 19, 25, 20, 2..."
10,10,CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CYP2D6,CCNC(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CCN(...,[2],"[[2], [17], [2], [17], [4], [16], [16], [2], [...",CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP2D6,"[11, 0, 4, 1, 3, 16, 10, 12, 17, 9, 13, 2, 14,...","[1, 3, 11, 10, 12, 16, 9, 13, 17, 14, 5, 0, 4,..."
11,11,CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CYP3A4,CCNC(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN,CC[N:1](CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CCN(...,[2],"[[2], [17], [2], [17], [4], [16], [16], [2], [...",CCN(CC)C(=O)[C@@]1(c2ccccc2)C[C@H]1CN|CYP3A4,"[16, 17, 1, 3, 14, 15, 11, 10, 12, 0, 4, 9, 13...","[1, 3, 11, 0, 4, 10, 12, 9, 13, 16, 17, 14, 15..."
12,12,CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21,CYP2C9,COCCCN1C[C@H](N)c2cc(S(N)(=O)=O)sc2S1(=O)=O,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,[2],"[[2], [9], [5], [8, 9], [10], [9], [9], [8], [...",CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc2...,"[1, 10, 8, 3, 2, 7, 0, 6, 19, 4, 16, 22, 5, 9,...","[1, 11, 9, 7, 23, 6, 4, 5, 12, 0, 13, 14, 2, 8..."
13,13,CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21,CYP3A4,COCCCN1C[C@H](N)c2cc(S(N)(=O)=O)sc2S1(=O)=O,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,CC[NH:1][C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=...,[2],"[[2], [9], [5], [8, 9], [10], [9], [9], [8], [...",CCN[C@H]1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc2...,"[1, 3, 2, 10, 8, 22, 6, 4, 7, 16, 0, 19, 5, 20...","[1, 11, 9, 7, 4, 0, 8, 5, 13, 14, 21, 22, 3, 2..."
14,14,CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C,CYP2D6,CC[C@@H](c1cc(O)cc(O)c1)[C@@H](C)CN(C)C,CC[C@@H](c1cc(O)c[cH:1]c1)[C@@H](C)CN(C)C,CC[C@@H](c1cccc(O)c1)[C@@H](C)C[N:1](C)C|CC[C@...,[8],"[[13], [6], [2], [13], [6], [8], [9], [13], [1...",CC[C@@H](c1cccc(O)c1)[C@@H](C)CN(C)C|CYP2D6,"[6, 14, 15, 12, 5, 4, 9, 0, 1, 2, 11, 10, 13, ...","[16, 17, 7, 1, 0, 14, 10, 6, 3, 12, 5, 2, 15, ..."
15,15,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,C[N+](C)([O-])CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|C[...,[1],"[[1], [1], [3], [22, 23], [1, 3], [15], [1], [...",CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6,"[0, 2, 15, 3, 9, 12, 21, 17, 8, 13, 22, 4, 5, ...","[0, 2, 3, 1, 9, 12, 8, 13, 21, 22, 19, 10, 15,..."
16,16,CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,C[N+](C)([O-])CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N...,C[N:1](C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[N:1](C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc2...,[1],"[[1], [1], [1], [1, 3], [3], [22, 23], [1], [1...",CN(C)CCC[C@@]1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CY...,"[0, 2, 15, 3, 9, 12, 21, 17, 8, 13, 22, 4, 5, ...","[0, 2, 3, 1, 9, 12, 8, 13, 21, 22, 19, 10, 15,..."
17,17,CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CYP2C9,O=C1CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc2N1,C[N:1]1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CN1C(=O)CC(=O)N(c2ccc(O)[cH:1]c2)c2cc(Cl)ccc21...,[1],"[[13], [1], [7, 8, 9, 10, 11, 12, 13, 14], [14...",CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP2C9,"[0, 19, 4, 10, 13, 20, 16, 1, 9, 14, 7, 3, 12,...","[0, 1, 4, 19, 10, 13, 20, 17, 3, 6, 11, 16, 7,..."
18,18,CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CYP3A4,O=C1CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc2N1,C[N:1]1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21,CN1C(=O)CC(=O)N(c2ccc(O)[cH:1]c2)c2cc(Cl)ccc21...,[1],"[[13], [1], [7, 8, 9, 10, 11, 12, 13, 14], [14...",CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21|CYP3A4,"[0, 4, 10, 13, 19, 16, 20, 9, 14, 1, 7, 3, 12,...","[0, 19, 10, 13, 20, 4, 16, 11, 9, 14, 17, 8, 1..."
19,19,CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2...,CYP3A4,CN1C=C[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc...,CN1[C@@H](c2nc3ccccc3[nH]2)C[C@H](NC(=O)Nc2ccc...,C[N:1]1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c...,"[26, 27]","[[1], [1], [23], [23], [24], [1], [24], [21, 2...",CN1CC[C@@H](NC(=O)Nc2ccc(C#N)cc2)C[C@@H]1c1nc2...,"[0, 2, 18, 4, 25, 24, 22, 23, 3, 17, 11, 15, 1...","[0, 2, 26, 25, 3, 18, 1, 19, 5, 20, 11, 17, 24..."
20,20,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CYP3A4,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,CNC(=O)c1cc(Oc2c[cH:1]c(NC(=O)[NH:1][c:1]3ccc(...,[31],"[[10, 15, 16, 27], [31], [1], [22], [16], [1, ...",CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,"[0, 31, 29, 5, 9, 28, 18, 17, 26, 10, 27, 1, 1...","[0, 31, 17, 18, 10, 27, 9, 28, 26, 29, 8, 13, ..."
21,21,CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,CYP2D6,N#Cc1ccc2c(c1)COC2(CCCN)c1ccc(F)cc1,C[NH:1]CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,C[NH:1]CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CN[C...,[1],"[[1], [2], [1], [14], [2], [1], [15], [21, 22]...",CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21|CYP2D6,"[0, 14, 2, 8, 11, 20, 16, 1, 7, 12, 21, 3, 4, ...","[0, 2, 8, 11, 7, 12, 20, 21, 18, 9, 14, 19, 10..."
22,22,COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...,CYP3A4,COc1c(O)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21|...,COc1c(OCCC[N:1]2CC[O:1]CC2)ccc2c1N=C(NC(=O)c1c...,COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...,"[8, 11, 8, 11, 12, 8, 11, 12, 13, 7, 11, 4]","[[32], [1], [29], [4], [34], [7, 11], [8, 11, ...",COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1...,"[9, 13, 7, 8, 32, 27, 10, 12, 0, 33, 5, 31, 14...","[7, 5, 0, 21, 9, 13, 10, 12, 8, 31, 6, 14, 25,..."
23,23,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,CYP3A4,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CC[N:1](C)CC4)c(O...,[22],"[[22], [10], [22], [27], [25], [24], [14], [15...",COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc...,"[23, 21, 24, 20, 25, 18, 22, 19, 0, 28, 16, 5,...","[23, 18, 16, 28, 0, 22, 11, 33, 19, 20, 21, 24..."
24,24,COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,CYP2C9,COc1cc(O)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)n...,COc1cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)...,COc1cc(OC)cc(N(CC[NH:1]C(C)C)c2ccc3ncc(-c4cnn(...,[30],"[[12], [30], [26], [9], [11], [32], [21], [7],...",COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,"[13, 11, 0, 6, 26, 12, 3, 10, 14, 15, 28, 24, ...","[13, 0, 6, 25, 26, 9, 10, 23, 17, 16, 11, 24, ..."
25,25,COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,CYP3A4,COc1cc(O)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)n...,COc1cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)...,COc1cc(OC)cc(N(CC[NH:1]C(C)C)c2ccc3ncc(-c4cnn(...,[30],"[[12], [30], [26], [9], [11], [32], [21], [7],...",COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)...,"[13, 11, 12, 0, 6, 26, 10, 3, 17, 7, 32, 20, 2...","[13, 0, 6, 26, 11, 10, 17, 23, 16, 24, 14, 15,..."
26,26,COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN...,CYP2D6,COc1cc2c(cc1O)CCN1C[C@@H](CC(C)C)[C@H](O)C[C@H...,COc1cc2c(cc1[O:1]C)CCN1C[C@@H](CC(C)C)[C@H](O)...,COc1cc2c(cc1[O:1]C)CCN1C[C@@H](CC(C)C)[C@H](O)...,"[8, 8]","[[8], [8], [16], [16], [18], [8], [8], [18], [...",COc1cc2c(cc1OC)[C@H]1C[C@@H](O)[C@H](CC(C)C)CN...,"[0, 9, 17, 18, 16, 21, 19, 10, 15, 12, 3, 22, ...","[0, 9, 19, 24, 25, 11, 14, 17, 3, 22, 20, 21, ..."
27,27,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,CYP3A4,CNCC[C@@](O)(c1cccc2ccccc12)[C@H](c1ccccc1)c1c...,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,[24],"[[24], [24], [35], [35], [24], [24], [24], [35...",COc1nc2ccc(Br)cc2cc1[C@@H](c1ccccc1)[C@@](O)(C...,"[25, 26, 23, 0, 13, 5, 3, 22, 33, 6, 34, 30, 3...","[26, 27, 24, 0, 34, 30, 17, 19, 31, 25, 33, 18..."
28,28,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,CYP2C9,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cc[cH:1]cn...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cccc[n:1]3...,[20],"[[22], [20], [10], [22], [23], [8], [22], [4, ...",CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,"[0, 20, 22, 19, 21, 18, 5, 26, 12, 6, 23, 13, ...","[1, 20, 12, 2, 3, 10, 5, 19, 26, 23, 25, 18, 1..."
29,29,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,CYP3A4,CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)...,CS(=O)(=O)c1ccc(C(=O)Nc2cc(-c3ccccn3)c(Cl)[cH:...,CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3cccc[n:1]3...,[22],"[[22], [20], [10], [22], [23], [8], [22], [4, ...",CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)...,"[0, 22, 6, 12, 23, 20, 5, 26, 13, 19, 18, 21, ...","[1, 20, 12, 22, 13, 19, 23, 18, 21, 26, 5, 6, ..."
30,30,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,CYP3A4,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](OS(=O)(=O)O...,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H]([OH:1])CC[C...,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,[11],"[[24], [10, 11], [24], [16], [24], [10, 11], [...",C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,"[18, 17, 10, 9, 7, 6, 24, 12, 13, 4, 2, 3, 5, ...","[28, 21, 8, 11, 3, 2, 26, 9, 15, 22, 16, 5, 7,..."
31,31,Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]1,CYP3A4,Cc1c(OCC(F)(F)F)ccnc1CS(=O)(=O)c1nc2ccccc2[nH]1,Cc1c(OCC(F)(F)F)ccnc1C[S@@:1](=O)c1nc2ccccc2[nH]1,Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2c[cH:1]ccc...,[14],"[[20], [3], [3, 4], [14], [14], [20], [18, 19]...",Cc1c(OCC(F)(F)F)ccnc1C[S@@](=O)c1nc2ccccc2[nH]...,"[14, 4, 0, 22, 13, 21, 19, 20, 9, 11, 10, 17, ...","[14, 0, 21, 20, 4, 11, 19, 22, 9, 10, 5, 6, 7,..."
32,32,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,CYP3A4,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cc(O)cc3Cl)s2)cc(N2CC...,Cc1nc(Nc2ncc(C(=O)Nc3c(C)c[cH:1]cc3Cl)s2)cc(N2...,Cc1nc(Nc2ncc(C(=O)Nc3c(C)c[cH:1]cc3Cl)s2)cc(N2...,"[16, 26, 19]","[[16], [11, 12, 13, 15, 16, 17, 18, 19], [26],...",Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,"[27, 24, 31, 26, 25, 30, 28, 14, 23, 0, 20, 16...","[27, 28, 0, 16, 14, 17, 26, 20, 15, 25, 30, 9,..."
33,33,Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O,CYP3A4,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O,OC1N=C(c2ccccc2F)c2cc(Cl)ccc2-n2c1cnc2[CH3:1],OC1N=C(c2ccccc2F)c2cc(Cl)ccc2-n2c1cnc2[CH3:1]|...,[23],"[[23], [4, 5, 6, 12, 13, 21, 22, 23], [3], [22...",Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|CYP3A4,"[22, 0, 21, 3, 17, 8, 15, 11, 16, 18, 7, 2, 5,...","[0, 22, 8, 17, 16, 7, 15, 18, 11, 3, 2, 1, 9, ..."
34,34,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP1A2,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,None,"[21, 25, 8, 29, 7, 30, 2, 11, 19, 12, 22, 24, ..."
35,35,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP2C9,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,"[21, 25, 22, 24, 2, 20, 18, 26, 15, 13, 28, 7,...","[20, 22, 24, 2, 11, 0, 15, 8, 29, 7, 30, 23, 1..."
36,36,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,CYP3A4,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOC[CH2:1]4)...,[25],"[[25], [3], [24], [23, 24], [27], [20, 25], [1...",N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2...,"[21, 25, 2, 18, 26, 22, 24, 20, 15, 13, 28, 7,...","[1, 22, 24, 2, 8, 29, 21, 25, 7, 30, 17, 27, 1..."
37,37,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP1A2,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP1A2,None,"[17, 5, 14, 18, 4, 6, 16, 13, 19, 3, 7, 8, 9, ..."
38,38,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP2C9,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP2C9,"[14, 5, 4, 6, 21, 17, 3, 7, 13, 18, 16, 2, 19,...","[8, 14, 1, 12, 4, 6, 5, 13, 17, 9, 18, 0, 3, 7..."
39,39,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1,CYP3A4,O=C(C1CCC(O)CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C(C1CC[CH2:1]CC1)N1CC(=O)N2CCc3ccccc3C2C1,O=C1C[N:1](C(=O)C2CCCCC2)CC2c3ccccc3CCN12|O=C(...,[5],"[[3], [5], [6], [15, 16, 17, 18, 19, 20], [12,...",O=C(C1CCCCC1)N1CC(=O)N2CCc3ccccc3C2C1|CYP3A4,"[21, 14, 5, 4, 6, 3, 7, 13, 2, 9, 22, 17, 18, ...","[14, 5, 17, 16, 4, 6, 18, 13, 3, 7, 19, 8, 1, ..."
40,40,O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2...,CYP3A4,O=C(O)CNC(=O)C1C(=O)N(C2CCC(O)CC2)C(=O)N([C@H]...,O=C(O)CNC(=O)C1C(=O)N(C2CCC[CH2:1]C2)C(=O)N(C2...,O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CC[CH2...,"[15, 24, 15, 24, 26, 27, 15, 23, 26, 27, 14, 2...","[[23], [20, 22, 23, 24, 25], [24], [4], [20, 2...",O=C(O)CNC(=O)C1C(=O)N(C2CCCCC2)C(=O)N(C2CCCCC2...,"[7, 3, 14, 23, 13, 15, 22, 24, 12, 16, 21, 25,...","[14, 23, 13, 15, 22, 24, 1, 11, 20, 3, 7, 12, ..."
41,41,O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...,CYP3A4,O=C(O)CNC(=O)C1C(=O)N(C2CC[C@H](O)[C@H](O)C2)C...,O=C(O)CNC(=O)C1C(=O)N(C2CC[CH2:1][C@H](O)C2)C(...,O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...,[14],"[[24, 25], [15, 16], [24, 25], [14], [15, 16],...",O=C(O)CNC(=O)C1C(=O)N(C2CCC[C@H](O)C2)C(=O)N([...,"[24, 15, 3, 28, 14, 13, 23, 26, 12, 22, 27, 17...","[31, 13, 26, 14, 15, 1, 25, 29, 22, 16, 23, 27..."
42,42,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,CYP2C9,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2c(O)...,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2c(cc...,O=C(O)C[C@@H:1](C[C@H](O)/C=C/c1c(C2CC2)nc2ccc...,[22],"[[4, 30], [4, 30], [7, 30], [20], [30], [29], ...",O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,"[20, 19, 9, 18, 13, 14, 15, 26, 29, 10, 21, 25...","[22, 5, 9, 21, 27, 32, 20, 16, 17, 23, 18, 28,..."
43,43,O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...,CYP3A4,O=C(O)CC(O)CC(=O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1...,O=[C:1]1CC(O)C[CH:1](/C=C/c2c(C3CC3)nc3ccccc3c...,O=C1OC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F)cc2)...,"[1, 6, 29]","[[27, 29], [1, 29], [18], [17], [24], [27, 28,...",O=C1CC(O)CC(/C=C/c2c(C3CC3)nc3ccccc3c2-c2ccc(F...,"[7, 6, 3, 2, 20, 8, 26, 27, 28, 5, 22, 24, 21,...","[20, 6, 8, 13, 16, 12, 17, 21, 19, 22, 7, 27, ..."
44,44,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,CYP2C9,O=C1C(O)N=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,"[19, 24]","[[19], [2, 3, 4, 19], [3, 4, 19], [2, 3, 4, 19...",O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|CYP2C9,"[2, 8, 3, 20, 7, 9, 16, 6, 17, 13, 19, 21, 10,...","[2, 20, 8, 16, 7, 3, 0, 19, 17, 6, 9, 22, 23, ..."
45,45,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F,CYP3A4,O=C1C(O)N=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2[N:1]1CC(F)(F)F...,"[19, 24]","[[19], [2, 3, 4, 19], [3, 4, 19], [2, 3, 4, 19...",O=C1CN=C(c2ccccc2F)c2cc(Cl)ccc2N1CC(F)(F)F|CYP3A4,"[2, 3, 20, 8, 16, 6, 13, 7, 9, 17, 19, 21, 10,...","[2, 20, 16, 8, 7, 6, 17, 13, 9, 22, 23, 24, 3,..."
46,46,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,CYP2D6,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3cc[cH:1]...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","[[20], [17], [11], [25], [31], [30], [12, 25],...",OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,"[18, 17, 5, 11, 25, 21, 19, 24, 26, 4, 6, 10, ...",None
47,47,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,CYP2D6,OCCOc1ccc(Cc2cc([C@@H]3O[C@H](CO)[C@@H](O)[C@H...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCC[O:1]C4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[19, 11]","[[16], [22], [18, 19], [19], [22], [4, 6, 28, ...",OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,"[1, 20, 30, 21, 22, 2, 28, 18, 26, 11, 17, 4, ...","[19, 20, 1, 9, 23, 24, 3, 6, 29, 32, 35, 8, 31..."

In [16]:
df.to_pickle('./total_cyp_123.pickle')

In [17]:
def get_unique_numbers(nums, n):
    """
    从列表中提取前 n 个不同的数字。

    参数:
        nums (list): 输入的数字列表。
        n (int): 需要提取的不同数字的数量。

    返回:
        list: 包含前 n 个不同数字的列表。
    """
    unique_nums = []
    seen = set()

    for num in nums:
        if num not in seen:
            unique_nums.append(num)
            seen.add(num)
        if len(unique_nums) == n:
            break

    return unique_nums

In [18]:
df_total = pd.read_pickle('./total_cyp_123.pickle')

ourmodel_results_old = df_total['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

top 1 accuracy = 0.04
top 3 accuracy = 0.26
top 5 accuracy = 0.4
top 1 accuracy = 0.14
top 3 accuracy = 0.34
top 5 accuracy = 0.46
top 1 accuracy = 0.5
top 3 accuracy = 0.74
top 5 accuracy = 0.86

In [19]:
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall           0.04       0.14           0.50
1  top3_recall           0.26       0.34           0.74
2  top5_recall           0.40       0.46           0.86

5. 按照酶整理结果

In [20]:
df_total['Enzyme'].unique()

array(['CYP3A4', 'CYP2C9', 'CYP1A2', 'CYP2D6'], dtype=object)

In [21]:
df_total_cyp1a2 = df_total[df_total['Enzyme'] == 'CYP1A2']

ourmodel_results_old = df_total_cyp1a2['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp1a2['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp1a2['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp1a2['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)
df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.0
top 3 accuracy = 0.0
top 5 accuracy = 0.0
top 1 accuracy = 0.0
top 3 accuracy = 0.6666666666666666
top 5 accuracy = 0.6666666666666666
top 1 accuracy = 0.3333333333333333
top 3 accuracy = 0.6666666666666666
top 5 accuracy = 0.6666666666666666

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall            0.0   0.000000       0.333333
1  top3_recall            0.0   0.666667       0.666667
2  top5_recall            0.0   0.666667       0.666667

In [22]:
df_total_cyp2c9 = df_total[df_total['Enzyme'] == 'CYP2C9']

ourmodel_results_old = df_total_cyp2c9['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp2c9['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp2c9['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp2c9['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.0
top 3 accuracy = 0.3333333333333333
top 5 accuracy = 0.4444444444444444
top 1 accuracy = 0.1111111111111111
top 3 accuracy = 0.3333333333333333
top 5 accuracy = 0.3333333333333333
top 1 accuracy = 0.3333333333333333
top 3 accuracy = 0.7777777777777778
top 5 accuracy = 0.7777777777777778

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.000000   0.111111       0.333333
1  top3_recall       0.333333   0.333333       0.777778
2  top5_recall       0.444444   0.333333       0.777778

In [23]:
df_total_cyp2d6 = df_total[df_total['Enzyme'] == 'CYP2D6']

ourmodel_results_old = df_total_cyp2d6['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp2d6['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp2d6['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp2d6['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.0
top 3 accuracy = 0.0
top 5 accuracy = 0.1111111111111111
top 1 accuracy = 0.1111111111111111
top 3 accuracy = 0.1111111111111111
top 5 accuracy = 0.3333333333333333
top 1 accuracy = 0.6666666666666666
top 3 accuracy = 0.6666666666666666
top 5 accuracy = 0.8888888888888888

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.000000   0.111111       0.666667
1  top3_recall       0.000000   0.111111       0.666667
2  top5_recall       0.111111   0.333333       0.888889

In [24]:
df_total_cyp3a4 = df_total[df_total['Enzyme'] == 'CYP3A4']

ourmodel_results_old = df_total_cyp3a4['predict_site_atomidx'].to_list()
ourmodel_results_new = []
for i in ourmodel_results_old:
    list_part = []
    for j in i:
        list_part = list_part + j
    ourmodel_results_new.append(list_part)

true_sites_old = df_total_cyp3a4['site_truth_atomidx'].to_list()

def acc_top_n(n,modelresults,true_sites):
    modelresults = [i[:n] for i in modelresults]
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

def acc_top_n_old(n,modelresults,true_sites):
    total_num = len(true_sites)
    correct_num = 0
    for idx,i in enumerate(true_sites):
        modelresult = modelresults[idx]
        modelresult = get_unique_numbers(modelresult, n)
        modelresult = set(modelresult)
        i = set(i)
        intersection = i & modelresult
        if len(intersection) > 0:
            correct_num = correct_num + 1
    acc = correct_num/total_num
    print(f'top {n} accuracy = {acc}')
    return acc

smartcyp_ranks = df_total_cyp3a4['rank_smartcyp'].to_list()
smartcyp_top1_acc = acc_top_n(1,smartcyp_ranks,true_sites_old)
smartcyp_top3_acc = acc_top_n(3,smartcyp_ranks,true_sites_old)
smartcyp_top5_acc = acc_top_n(5,smartcyp_ranks,true_sites_old)
smartcyp_topn = []
smartcyp_topn.append(smartcyp_top1_acc)
smartcyp_topn.append(smartcyp_top3_acc)
smartcyp_topn.append(smartcyp_top5_acc)

somp_ranks = df_total_cyp3a4['rank_somp'].to_list()
somp_top1_acc = acc_top_n(1,somp_ranks,true_sites_old)
somp_top3_acc = acc_top_n(3,somp_ranks,true_sites_old)
somp_top5_acc = acc_top_n(5,somp_ranks,true_sites_old)
somp_topn = []
somp_topn.append(somp_top1_acc)
somp_topn.append(somp_top3_acc)
somp_topn.append(somp_top5_acc)

ourmodel_top1_acc = acc_top_n_old(1,ourmodel_results_new,true_sites_old)
ourmodel_top3_acc = acc_top_n_old(3,ourmodel_results_new,true_sites_old)
ourmodel_top5_acc = acc_top_n_old(5,ourmodel_results_new,true_sites_old)
ourmodel_topn = []
ourmodel_topn.append(ourmodel_top1_acc)
ourmodel_topn.append(ourmodel_top3_acc)
ourmodel_topn.append(ourmodel_top5_acc)

df = pd.DataFrame()
df['top_n'] = ['top1_recall','top3_recall','top5_recall']
df['smartcyp_topn'] = smartcyp_topn
df['somp_topn'] = somp_topn
df['ourmodel_topn'] = ourmodel_topn
df

top 1 accuracy = 0.06896551724137931
top 3 accuracy = 0.3448275862068966
top 5 accuracy = 0.5172413793103449
top 1 accuracy = 0.1724137931034483
top 3 accuracy = 0.3793103448275862
top 5 accuracy = 0.5172413793103449
top 1 accuracy = 0.5172413793103449
top 3 accuracy = 0.7586206896551724
top 5 accuracy = 0.896551724137931

         top_n  smartcyp_topn  somp_topn  ourmodel_topn
0  top1_recall       0.068966   0.172414       0.517241
1  top3_recall       0.344828   0.379310       0.758621
2  top5_recall       0.517241   0.517241       0.896552