In [4]:
import pandas as pd
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/main_cases/pred_results_score_new.csv')
substrates = df['substrate'].to_list()

In [5]:
from rdkit import Chem

In [6]:
def canonicalsmiles(smi):
    mol = Chem.MolFromSmiles(smi)
    smi_new = Chem.MolToSmiles(mol)
    return smi_new

In [7]:
i = 1
filepath = f'SMARTCYP_results ({i}).csv'
df_part = pd.read_csv(filepath)
df_part

,Unnamed: 0,Molecule_Name,Molecule_Number,Atom_Number,Atom_Name,Atom,Span2end,Span2end_N_Correction,Span2end_CO_Correction,COO-Dist,...,Reactivity,Energy,3A4 Score,2D6 Score,2C9 Score,3A4 Ranking,2D6 Ranking,2C9 Ranking,N_ox,Similarity
0,0,Smiles,0,1,C,C.2,4,26.84,23.64,0,...,999.0,999.0,992.473051,1025.628840,1022.428840,25,25,25,0.0,0.000000
1,1,Smiles,0,2,C,C.3,5,26.85,23.65,0,...,80.8,80.8,74.140326,106.885063,103.685063,8,10,10,0.0,0.333333
2,2,Smiles,0,3,C,C.4,6,26.86,23.66,0,...,999.0,999.0,993.469661,1025.803345,1022.603345,28,31,31,0.0,0.000000
3,3,Smiles,0,4,C,C.5,7,26.87,23.67,0,...,999.0,999.0,993.905437,1025.828069,1022.628069,31,32,32,0.0,0.000000
4,4,Smiles,0,5,C,C.6,8,26.88,23.68,0,...,86.3,86.3,80.889001,112.400580,109.200580,13,15,15,0.0,0.333333
5,5,Smiles,0,6,C,C.7,9,26.89,23.69,0,...,999.0,999.0,994.581230,1025.681756,1022.481756,35,27,27,0.0,0.000000
6,6,Smiles,0,7,N,N.8,9,26.89,23.69,0,...,999.0,999.0,994.839588,1025.940114,1022.740114,36,36,36,0.0,0.333333
7,7,Smiles,0,8,C,C.9,9,26.89,23.69,0,...,77.2,77.2,72.240961,103.341487,100.141487,5,8,8,0.0,0.333333
8,8,Smiles,0,9,C,C.10,8,26.88,23.68,0,...,999.0,999.0,994.220071,1025.731650,1022.531650,33,30,30,0.0,0.000000
9,9,Smiles,0,10,O,O.11,7,26.87,23.67,0,...,999.0,999.0,993.947368,1025.870000,1022.670000,32,34,34,0.0,0.000000
10,10,Smiles,0,11,C,C.12,6,26.86,23.66,0,...,62.2,62.2,54.152992,86.486676,83.286676,1,1,1,0.0,1.000000
11,11,Smiles,0,12,C,C.13,8,26.88,23.68,0,...,75.9,75.9,71.007339,102.518918,99.318918,4,7,7,0.0,0.400000
12,12,Smiles,0,13,C,C.14,7,26.87,23.67,0,...,999.0,999.0,993.775731,1025.698363,1022.498363,30,28,28,0.0,0.000000
13,13,Smiles,0,14,N,N.15,6,26.86,23.66,0,...,89.6,89.6,83.793539,116.127223,112.927223,15,17,17,0.0,0.333333
14,14,Smiles,0,15,C,C.16,5,26.85,23.65,0,...,999.0,999.0,992.920706,1025.665443,1022.465443,26,26,26,0.0,0.000000
15,15,Smiles,0,16,C,C.17,4,26.84,23.64,0,...,84.1,84.1,76.770075,109.925865,106.725865,9,11,11,0.0,0.666667
16,16,Smiles,0,17,C,C.18,3,20.10,17.70,0,...,80.8,80.8,73.071904,99.908746,97.508746,7,5,5,0.0,0.666667
17,17,Smiles,0,18,C,C.19,2,13.40,11.80,0,...,999.0,999.0,991.675632,1012.233526,1010.633526,23,23,23,0.0,0.000000
18,18,Smiles,0,19,C,C.20,3,20.10,17.70,0,...,999.0,999.0,992.001141,1018.837983,1016.437983,24,24,24,0.0,0.000000
19,19,Smiles,0,21,C,C.22,4,26.84,23.64,0,...,84.1,84.1,76.833124,109.988913,106.788913,10,12,12,0.0,0.333333
20,20,Smiles,0,22,C,C.23,1,6.70,5.90,0,...,999.0,999.0,991.144485,1005.423432,1004.623432,20,20,20,0.0,0.000000
21,21,Smiles,0,23,N,N.24,0,0.00,0.00,0,...,89.6,89.6,79.662399,87.662399,87.662399,12,2,2,0.0,0.666667
22,22,Smiles,0,24,O,O.25,0,0.00,0.00,0,...,999.0,999.0,991.000000,999.000000,999.000000,19,19,19,0.0,0.666667
23,23,Smiles,0,25,O,O.26,6,26.86,23.66,0,...,999.0,999.0,993.526316,1025.860000,1022.660000,29,33,33,0.0,0.666667
24,24,Smiles,0,26,C,C.27,7,26.87,23.67,0,...,75.9,75.9,69.911893,101.834524,98.634524,2,6,6,0.0,0.400000
25,25,Smiles,0,27,C,C.28,6,26.86,23.66,0,...,89.6,89.6,81.837145,114.170829,110.970829,14,16,16,0.0,0.666667
26,26,Smiles,0,28,O,O.29,8,26.88,23.68,0,...,999.0,999.0,994.368421,1025.880000,1022.680000,34,35,35,0.0,0.333333
27,27,Smiles,0,29,C,C.30,3,20.10,17.70,0,...,80.8,80.8,72.967315,99.804158,97.404158,6,4,4,0.0,0.666667
28,28,Smiles,0,30,C,C.31,4,26.84,23.64,0,...,86.3,86.3,79.031675,112.187464,108.987464,11,14,14,0.0,0.666667
29,29,Smiles,0,31,C,C.32,5,26.85,23.65,0,...,999.0,999.0,992.975563,1025.720300,1022.520300,27,29,29,0.0,0.000000
30,30,Smiles,0,32,N,N.33,4,26.84,23.64,0,...,92.1,92.1,85.741885,118.897675,115.697675,18,18,18,0.0,0.333333
31,31,Smiles,0,33,N,N.34,3,20.10,17.70,0,...,92.1,92.1,84.401832,111.238674,108.838674,17,13,13,0.0,0.333333
32,32,Smiles,0,34,N,N.35,2,13.40,11.80,0,...,92.1,92.1,84.056546,104.614441,103.014441,16,9,9,0.0,0.333333
33,33,Smiles,0,35,C,C.36,3,20.10,17.70,0,...,78.1,78.1,70.343251,97.180094,94.780094,3,3,3,0.0,0.333333
34,34,Smiles,0,36,C,C.37,2,13.40,11.80,0,...,999.0,999.0,991.634248,1012.192143,1010.592143,22,22,22,0.0,0.000000
35,35,Smiles,0,37,C,C.38,1,6.70,5.90,0,...,999.0,999.0,991.415912,1005.694859,1004.894859,21,21,21,0.0,0.000000

In [8]:
df_new = pd.DataFrame(columns=['substrates','enzyme','scores'])
from rdkit import Chem

subs_new = []
enzymes_new = []
scores_new = []

for i in range(len(substrates)):
    sub = substrates[i]
    sub = canonicalsmiles(sub)
    if i == 0:
        filepath = f'SMARTCYP_results.csv'
    else:
        filepath = f'SMARTCYP_results ({i}).csv'

    df_part = pd.read_csv(filepath)

    # 解析 SMILES
    molecule = Chem.MolFromSmiles(sub)
    # 获取原子数
    atom_count = molecule.GetNumAtoms()

    # try:
    atomidxs = df_part['Atom_Number'].to_list()
    # assert atom_count == max(atomidxs)+1

    ranks_3a4 = df_part['3A4 Ranking'].to_list()
    ranks_2d6 = df_part['2D6 Ranking'].to_list()
    ranks_2c9 = df_part['2C9 Ranking'].to_list()
    dict_atomidx2rank3a4 = dict(zip(atomidxs,ranks_3a4))
    dict_atomidx2rank2d6 = dict(zip(atomidxs,ranks_2d6))
    dict_atomidx2rank2c9 = dict(zip(atomidxs,ranks_2c9))

    subs_new.append(sub)
    subs_new.append(sub)
    subs_new.append(sub)

    enzymes_new.append('3A4')
    enzymes_new.append('2D6')
    enzymes_new.append('2C9')

    scores_new.append(dict_atomidx2rank3a4)
    scores_new.append(dict_atomidx2rank2d6)
    scores_new.append(dict_atomidx2rank2c9)

    # except:
    #     print(sub)
    #     print(len(df_part))
    #     print(atom_count)

df_new['substrates'] = subs_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = scores_new

df_new

,substrates,enzyme,scores
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,3A4,"{0: 21, 1: 22, 2: 14, 3: 6, 4: 24, 5: 13, 6: 1..."
1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2D6,"{0: 20, 1: 22, 2: 14, 3: 9, 4: 24, 5: 11, 6: 1..."
2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2C9,"{0: 20, 1: 22, 2: 14, 3: 8, 4: 24, 5: 13, 6: 1..."
3,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,3A4,"{1: 25, 2: 8, 3: 28, 4: 31, 5: 13, 6: 35, 7: 3..."
4,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,2D6,"{1: 25, 2: 10, 3: 31, 4: 32, 5: 15, 6: 27, 7: ..."
...,...,...,...
85,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2D6,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
86,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2C9,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
87,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,3A4,"{0: 11, 1: 12, 2: 6, 3: 5, 4: 4, 5: 13, 6: 4, ..."
88,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."
89,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2C9,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."

In [9]:
df_new.to_pickle('smartcyp_results_30.pickle')

In [10]:
df = pd.read_pickle('smartcyp_results_30.pickle')
df

,substrates,enzyme,scores
0,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,3A4,"{0: 21, 1: 22, 2: 14, 3: 6, 4: 24, 5: 13, 6: 1..."
1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2D6,"{0: 20, 1: 22, 2: 14, 3: 9, 4: 24, 5: 11, 6: 1..."
2,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2C9,"{0: 20, 1: 22, 2: 14, 3: 8, 4: 24, 5: 13, 6: 1..."
3,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,3A4,"{1: 25, 2: 8, 3: 28, 4: 31, 5: 13, 6: 35, 7: 3..."
4,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,2D6,"{1: 25, 2: 10, 3: 31, 4: 32, 5: 15, 6: 27, 7: ..."
...,...,...,...
85,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2D6,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
86,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,2C9,"{0: 22, 1: 18, 2: 19, 3: 13, 4: 12, 5: 11, 6: ..."
87,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,3A4,"{0: 11, 1: 12, 2: 6, 3: 5, 4: 4, 5: 13, 6: 4, ..."
88,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2D6,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."
89,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,2C9,"{0: 11, 1: 12, 2: 6, 3: 4, 4: 5, 5: 13, 6: 5, ..."

In [11]:
import pandas as pd

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result

# 示例
result = group_by_column_to_dict(df, 'substrates', 'scores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: 87, 7: 28, 8: 93, 9: 50, 10: 58, 11: 54, 12: 59, 13: 63, 14: 22, 15: 73, 16: 102, 17: 14, 18: 99, 19: 46, 20: 34, 21: 90, 22: 11, 23: 79, 24: 21, 25: 7, 26: 66, 27: 11, 28: 66, 29: 21, 30: 69, 31: 28, 32: 73, 33: 37, 34: 90, 35: 41, 36: 93, 37: 45, 38: 96}, 'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: 66, 7: 111, 8: 43, 9: 101, 10: 52, 11: 69, 12: 98, 13: 87, 14: 81, 15: 81, 16: 28, 17: 45, 18: 45, 19: 106, 20: 103, 21: 46, 22: 63, 23: 16, 24: 78, 25: 22, 26: 21, 27: 31, 28: 34, 29: 84, 30: 55, 31: 110, 32: 114, 33: 29, 34: 37, 35: 114, 36: 46, 37: 15, 38: 26, 39: 22, 40: 75, 41: 10, 42: 10}, 'CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1': {0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 36, 7: 63, 8: 7, 9: 69, 10: 69, 11: 74, 12: 45, 13: 14, 14: 41, 15: 70, 16: 30, 17: 21, 18: 16, 19: 54, 20: 16, 21: 8, 22: 13, 23: 27, 24: 57, 25: 37}, 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)SCCS2': {0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: 37, 7: 37, 8: 78, 9: 48, 10: 33, 11: 81, 12: 8, 13: 11, 14: 11, 15: 8, 16: 36, 17: 4, 18: 79, 19: 45, 20: 16, 21: 29, 22: 23, 23: 17, 24: 8, 25: 28, 26: 55, 27: 52, 28: 69, 29: 59, 30: 86, 31: 81, 32: 58}, 'CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@]6(C)C[C@H](O)[C@H](OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CC[C@@]5(C)[C@]3(C)C[C@H]4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O': {0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175, 6: 97, 7: 115, 8: 87, 9: 84, 10: 184, 11: 193, 12: 186, 13: 102, 14: 96, 15: 132, 16: 112, 17: 81, 18: 206, 19: 109, 20: 98, 21: 185, 22: 124, 23: 109, 24: 90, 25: 124, 26: 185, 27: 210, 28: 116, 29: 78, 30: 197, 31: 22, 32: 65, 33: 60, 34: 68, 35: 57, 36: 125, 37: 181, 38: 163, 39: 19, 40: 50, 41: 156, 42: 59, 43: 153, 44: 6, 45: 144, 46: 18, 47: 8, 48: 147, 49: 138, 50: 14, 51: 138, 52: 141, 53: 43, 54: 150, 55: 34, 56: 159, 57: 168, 58: 172, 59: 71, 60: 190, 61: 56, 62: 181, 63: 45, 64: 200, 65: 203, 66: 197, 67: 131, 68: 133, 69: 42, 70: 156, 71: 42, 72: 156, 73: 156, 74: 16, 75: 34, 76: 147, 77: 150, 78: 31, 79: 11, 80: 138, 81: 21, 82: 31, 83: 141, 84: 138}, 'CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N)ncnn23)[C@H](O)[C@@H]1O)Oc1ccccc1': {0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6: 23, 7: 29, 8: 98, 9: 89, 10: 75, 11: 70, 12: 82, 13: 30, 14: 19, 15: 70, 16: 67, 17: 4, 18: 17, 19: 54, 20: 33, 21: 61, 22: 25, 23: 85, 24: 24, 25: 94, 26: 101, 27: 85, 28: 52, 29: 55, 30: 40, 31: 55, 32: 52, 33: 80, 34: 85, 35: 85, 36: 46, 37: 43, 38: 23, 39: 38, 40: 23, 41: 38}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 37, 7: 56, 8: 60, 9: 57, 10: 53, 11: 40, 12: 60, 13: 48, 14: 45, 15: 45, 16: 30, 17: 11, 18: 5, 19: 15, 20: 30, 21: 24, 22: 11}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 45, 7: 23, 8: 28, 9: 23, 10: 28, 11: 16, 12: 76, 13: 77, 14: 43, 15: 32, 16: 20, 17: 66, 18: 68, 19: 71, 20: 36, 21: 49, 22: 57, 23: 54, 24: 9, 25: 16, 26: 16, 27: 26, 28: 35}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 14, 7: 16, 8: 45, 9: 51, 10: 54, 11: 19, 12: 11, 13: 30, 14: 5, 15: 26, 16: 5, 17: 26, 18: 12, 19: 41}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: 77, 7: 35, 8: 82, 9: 14, 10: 28, 11: 5, 12: 22, 13: 81, 14: 9, 15: 78, 16: 47, 17: 66, 18: 35, 19: 51, 20: 9, 21: 26, 22: 54, 23: 13, 24: 57, 25: 34, 26: 72, 27: 69, 28: 46, 29: 39}, 'CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: 108, 8: 21, 9: 93, 10: 100, 11: 3, 12: 18, 13: 86, 14: 49, 15: 78, 16: 31, 17: 17, 18: 69, 19: 72, 21: 34, 22: 60, 23: 16, 24: 57, 25: 95, 26: 14, 27: 46, 28: 104, 29: 14, 30: 39, 31: 85, 32: 54, 33: 43, 34: 34, 35: 9, 36: 66, 37: 63}, 'CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33, 7: 15, 8: 20, 9: 11, 10: 38, 11: 61, 12: 63, 13: 35, 14: 59, 15: 26, 16: 21, 17: 50, 18: 46, 19: 42, 23: 55, 25: 29, 26: 20, 27: 15}, 'CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@@](C)(Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCNC(=N)N)C(N)=O': {0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6: 20, 7: 130, 8: 10, 9: 7, 10: 115, 11: 166, 12: 177, 13: 9, 14: 82, 15: 76, 16: 81, 17: 119, 18: 175, 19: 186, 20: 56, 21: 94, 22: 89, 23: 14, 24: 40, 25: 151, 26: 35, 27: 32, 28: 124, 29: 175, 30: 181, 31: 186, 32: 111, 33: 61, 34: 161, 35: 105, 36: 102, 37: 99, 38: 102, 39: 105, 40: 124, 41: 166, 42: 172, 43: 94, 44: 47, 45: 154, 46: 19, 47: 131, 48: 135, 49: 33, 50: 36, 51: 54, 52: 57, 53: 141, 54: 118, 55: 68, 56: 151, 57: 144, 58: 67, 59: 138, 60: 61, 61: 50, 62: 30, 63: 38, 64: 108}, 'CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNC[C@H](O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6: 139, 7: 115, 8: 58, 9: 76, 10: 47, 11: 128, 12: 133, 13: 123, 14: 79, 15: 67, 16: 51, 17: 67, 18: 79, 19: 130, 20: 115, 21: 124, 22: 41, 23: 9, 24: 87, 25: 3, 26: 6, 27: 25, 28: 32, 29: 124, 30: 61, 31: 126, 32: 68, 33: 79, 34: 120, 35: 13, 36: 18, 37: 14, 38: 27, 39: 120, 40: 105, 41: 70, 42: 56, 43: 92, 44: 36, 45: 91, 46: 102, 47: 99, 48: 96, 49: 44, 50: 43, 51: 130, 52: 79, 53: 68}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18, 7: 18, 8: 33, 9: 39, 10: 25, 11: 36, 12: 6, 13: 30}, 'COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)(C(F)(F)F)[C@H]2C)ccc(F)c1F': {0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 75, 7: 80, 8: 42, 9: 69, 10: 28, 11: 31, 12: 9, 13: 54, 14: 48, 15: 19, 16: 45, 17: 31, 18: 80, 19: 74, 20: 35, 21: 66, 25: 20, 26: 38, 27: 23, 28: 10, 29: 51, 31: 57}, 'COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1': {0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 24, 7: 33, 8: 30, 9: 21, 10: 57, 11: 9, 12: 51, 13: 15, 14: 7, 15: 39, 16: 10, 17: 39, 18: 15, 19: 42, 20: 18, 21: 48, 22: 36, 23: 27}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 60, 7: 66, 8: 63, 9: 27, 10: 33, 11: 64, 12: 59, 13: 54, 14: 52, 15: 28, 16: 45, 17: 15, 18: 6, 19: 41, 20: 6, 21: 15, 22: 33, 23: 27, 24: 21, 25: 32, 26: 11, 27: 52, 28: 14}, 'Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12': {0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11, 7: 57, 8: 63, 9: 60, 10: 42, 11: 21, 12: 39, 13: 66, 14: 35, 15: 29, 16: 22, 17: 48, 18: 22, 19: 16, 20: 19, 21: 32, 22: 54}, 'Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: 60, 7: 9, 8: 3, 9: 48, 10: 6, 11: 48, 12: 9, 13: 54, 14: 13, 15: 57, 16: 45, 17: 76, 18: 14, 19: 73, 20: 34, 21: 31, 22: 68, 23: 63, 24: 31, 25: 30, 26: 51, 28: 30, 29: 31, 30: 24}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 42, 7: 28, 8: 31, 9: 17, 10: 58, 11: 30, 12: 31, 13: 24, 14: 10, 15: 20, 16: 45, 17: 8, 18: 50, 20: 31, 21: 28, 22: 58, 23: 58, 24: 17}, 'Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@H]3CC3(F)F)n2)cn1': {0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 35, 7: 51, 8: 43, 9: 69, 10: 18, 11: 9, 12: 10, 13: 32, 14: 32, 15: 10, 16: 9, 17: 47, 18: 63, 19: 57, 20: 17, 21: 10, 22: 54, 25: 40, 26: 23, 27: 33}, 'Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 66, 7: 45, 8: 70, 9: 12, 10: 15, 11: 73, 12: 19, 13: 30, 14: 67, 15: 34, 16: 27, 17: 51, 18: 27, 19: 34, 21: 42, 22: 77, 23: 54, 24: 48, 25: 27, 26: 3, 27: 33, 28: 7}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 42, 7: 78, 8: 78, 9: 29, 10: 38, 11: 32, 12: 74, 13: 78, 14: 48, 15: 18, 16: 7, 17: 18, 18: 56, 19: 52, 20: 76, 21: 76, 22: 36, 23: 81, 24: 37, 25: 8, 26: 64, 27: 33, 28: 25, 29: 33, 30: 25, 31: 59, 32: 55}, 'NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: 34, 7: 14, 8: 59, 9: 66, 10: 38, 11: 29, 12: 53, 14: 29, 15: 38, 16: 38, 17: 8, 18: 24, 19: 63, 20: 22, 21: 33, 22: 14, 23: 52, 24: 58, 25: 13, 26: 4, 27: 48, 28: 8, 29: 38}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: 14, 7: 13, 8: 3, 9: 30, 10: 25, 14: 25, 15: 33, 16: 9, 17: 6, 18: 22}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: 60, 7: 54, 8: 48, 12: 28, 13: 41, 14: 76, 15: 69, 16: 9, 17: 3, 18: 69, 19: 38, 20: 38, 21: 16, 22: 51, 23: 19, 24: 16, 25: 7, 26: 25, 27: 57, 28: 32, 29: 20, 30: 23}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73, 7: 73, 8: 23, 9: 58, 10: 56, 11: 54, 12: 63, 13: 27, 14: 57, 15: 58, 16: 22, 17: 18, 18: 33, 19: 30, 20: 18, 21: 22, 22: 75, 23: 63, 24: 69, 25: 67, 26: 63, 27: 15, 28: 42, 29: 11, 30: 39, 31: 4, 32: 30}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: 13, 7: 51, 8: 48, 9: 25, 10: 24, 11: 4, 12: 24, 13: 25, 14: 42, 15: 23, 16: 24, 17: 62, 18: 58, 19: 8, 20: 45, 21: 22, 22: 14, 23: 10, 24: 14, 25: 22, 26: 24, 27: 23}, 'O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: 36, 7: 31, 8: 77, 9: 83, 10: 18, 11: 78, 12: 43, 13: 44, 14: 75, 15: 17, 16: 18, 17: 7, 18: 18, 19: 60, 20: 18, 21: 7, 22: 44, 23: 43, 24: 64, 25: 73, 26: 20, 27: 17, 28: 54, 29: 51, 30: 34, 31: 60, 32: 57}}

In [12]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
smartcyp_results = [result_new[i] for i in substrates]
df_total['smartcyp_results'] = smartcyp_results
df_total

,name,substrate,predict,top_n,sites,gnn_results,smartcyp_results
0,1,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1CC2(C[C@H]...,2,[30],"{0: 20, 1: 3, 2: 7, 3: 11, 4: 19, 5: 8, 6: 1, ...","{0: 61, 1: 66, 2: 42, 3: 23, 4: 72, 5: 37, 6: ..."
1,2,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-...,CC[C@@H](C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(O)c(-c...,3,"[28, 37]","{0: 41, 1: 37, 2: 12, 3: 1, 4: 27, 5: 3, 6: 17...","{1: 75, 2: 28, 3: 90, 4: 95, 5: 43, 6: 89, 7: ..."
2,3,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21,CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(CO)CC21 0.57|...,1,[20],"{0: 5, 1: 4, 2: 9, 3: 11, 4: 14, 5: 23, 6: 3, ...","{0: 27, 1: 8, 2: 20, 3: 33, 4: 24, 5: 59, 6: 3..."
3,4,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)c1,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12 0.83|...,1,[3],"{0: 18, 1: 4, 2: 16, 3: 3, 4: 21, 5: 17, 6: 22...","{0: 5, 1: 51, 2: 48, 3: 36, 4: 60, 5: 24, 6: 3..."
4,5,Cc1ccc(N)cc1C(=O)N[C@H](C)c1cccc2ccccc12,CC(=O)Nc1ccc(C)c(C(=O)N[C@H](C)c2cccc3ccccc23)...,2,[3],"{0: 17, 1: 21, 2: 18, 3: 9, 4: 8, 5: 2, 6: 13,...","{0: 10, 1: 51, 2: 30, 3: 6, 4: 45, 5: 3, 6: 11..."
5,6,Cn1cc(Nc2nccc(N3C[C@H]4CC[C@@H](C3)N4C(=O)[C@@...,O=C([C@@H]1CC1(F)F)N1[C@H]2CC[C@@H]1CN(c1ccnc(...,4,[4],"{0: 1, 1: 3, 2: 25, 3: 22, 4: 2, 5: 28, 6: 12,...","{0: 3, 1: 38, 2: 26, 3: 60, 4: 24, 5: 66, 6: 3..."
6,7,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4c...,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3c[nH]c4c...,2,[40],"{0: 30, 1: 38, 2: 19, 3: 43, 4: 13, 5: 33, 6: ...","{0: 4, 1: 51, 2: 97, 3: 90, 4: 69, 5: 111, 6: ..."
7,8,Cc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]...,OCc1ccc([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H...,3,"[12, 13]","{0: 24, 1: 31, 2: 27, 3: 21, 4: 20, 5: 22, 6: ...","{0: 21, 1: 68, 2: 40, 3: 41, 4: 75, 5: 18, 6: ..."
8,10,O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12,Nc1ccsc1C(=O)Nc1ccc(OC(F)(F)F)cc1 0.73|O=C(Nc1...,2,[23],"{0: 10, 1: 1, 2: 7, 3: 30, 4: 18, 5: 11, 6: 14...","{0: 76, 1: 67, 2: 45, 3: 66, 4: 41, 5: 28, 6: ..."
9,11,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[...,NC1(C(=O)N[C@@H](CCOC2O[C@H](C(=O)O)[C@@H](O)[...,1,[8],"{0: 12, 1: 6, 2: 2, 3: 10, 4: 4, 5: 13, 6: 16,...","{0: 21, 1: 75, 2: 71, 3: 70, 4: 45, 5: 23, 6: ..."
10,12,CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CCOc1ccc(NC(=O)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=...,CC1=CC(C)=C2NC(C(CN3CCOC3=N)=CC2=C1)=O,"[7, 8, 13]","{0: 25, 1: 6, 2: 9, 3: 15, 4: 18, 5: 27, 6: 30...","{0: 31, 1: 15, 2: 60, 3: 63, 4: 39, 5: 46, 6: ..."
11,13,COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1,COc1ccc2c(Oc3ccc(C4(C(=O)O)CCOCC4)cc3)ccnc2n1 ...,4,[16],"{0: 3, 1: 5, 2: 6, 3: 8, 4: 9, 5: 26, 6: 13, 7...","{0: 3, 1: 41, 2: 44, 3: 18, 4: 26, 5: 56, 6: 6..."
12,14,C/C=C/C#CC#CC(O)C(/C=C/CCCO)OC1OC(COC2OC(CO)C(...,C/C=C/C#CC#CC(O)C(CC(=O)N[C@@H](CSC=CC(N)C(=O)...,3,[21],"{0: 25, 1: 30, 2: 23, 3: 20, 4: 12, 5: 16, 6: ...","{0: 11, 1: 20, 2: 33, 3: 74, 4: 80, 5: 84, 6: ..."
13,15,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,O=S(=O)(c1cnc(CO)s1)N1CCC(c2cn3ncnc3cc2Cl)CC1 ...,1,[7],"{0: 19, 1: 15, 2: 18, 3: 21, 4: 8, 5: 1, 6: 3,...","{0: 3, 1: 49, 2: 32, 3: 22, 4: 55, 5: 63, 6: 4..."
14,16,COc1ccc(CCCCOC2OC(CO)[C@@H](O)[C@H](O)[C@H]2O)cc1,OCC1OC(OCCCCc2ccc(O)cc2)[C@H](O)[C@@H](O)[C@@H...,1,[1],"{0: 1, 1: 4, 2: 6, 3: 5, 4: 7, 5: 13, 6: 22, 7...","{0: 4, 1: 42, 2: 45, 3: 27, 4: 36, 5: 54, 6: 2..."
15,17,O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c...,COc1c(O)c(O[C@@H]2O[C@@H](C(=O)O)[C@H](O)[C@H]...,2,[6],"{0: 27, 1: 26, 2: 25, 3: 32, 4: 28, 5: 14, 6: ...","{0: 30, 1: 36, 2: 30, 3: 8, 4: 45, 5: 7, 6: 73..."
16,18,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,CN1CCC[C@@H](OC(=O)[C@](O)(c2ccccc2)c2cccc(OCC...,2,[6],"{0: 18, 1: 12, 2: 28, 3: 29, 4: 23, 5: 3, 6: 6...","{0: 143, 1: 122, 2: 84, 3: 32, 4: 55, 5: 24, 6..."
17,19,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(...,CC[C@H](C)C(=O)N1CCC(NC(=O)Nc2ccc(O)c(F)c2)CC1...,3,[27],"{0: 15, 1: 22, 2: 14, 3: 21, 4: 1, 5: 3, 6: 13...","{0: 13, 1: 4, 2: 9, 3: 19, 4: 51, 5: 45, 6: 33..."
18,20,CN(C(=O)Cc1cccs1)[C@@H](Cc1c[nH]c2ccccc12)C(=O...,C[C@@](Cc1ccccc1)(NC(=O)[C@H](Cc1c[nH]c2ccccc1...,5,[],"{0: 2, 1: 1, 2: 4, 3: 12, 4: 35, 5: 63, 6: 52,...","{0: 152, 1: 167, 2: 52, 3: 85, 4: 79, 5: 8, 6:..."
19,21,CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2...,CCNC(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)...,3,[18],"{0: 13, 1: 8, 2: 2, 3: 9, 4: 17, 5: 1, 6: 3, 7...","{0: 9, 1: 17, 2: 12, 3: 43, 4: 65, 5: 60, 6: 4..."
20,22,COc1c([C@H]2C(C(=O)Nc3ccnc(C(N)=O)c3)O[C@@](C)...,C[C@H]1[C@@H](c2ccc(F)c(F)c2O)C(C(=O)Nc2ccnc(C...,1,[11],"{0: 5, 1: 4, 2: 16, 3: 17, 4: 9, 5: 14, 6: 2, ...","{0: 3, 1: 60, 2: 63, 3: 77, 4: 15, 5: 11, 6: 7..."
21,23,CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12,CCN(CC)CCc1c[nH]c2cccc(O)c12 0.91|CCNCCc1c[nH]...,1,[15],"{0: 6, 1: 2, 2: 7, 3: 3, 4: 5, 5: 10, 6: 13, 7...","{0: 9, 1: 36, 2: 33, 3: 40, 4: 48, 5: 23, 6: 1..."
22,24,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(=O)...,N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCC[C@@H]3C(N)=...,O=C([C@H]1CCCN1C(C2=CC=CC(S(N)(=O)=O)=C2)=O)NC...,[4],"{0: 6, 1: 7, 2: 13, 3: 22, 4: 14, 5: 1, 6: 4, ...","{0: 76, 1: 70, 2: 3, 3: 18, 4: 14, 5: 20, 6: 4..."
23,25,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,C[C@H](N[P@](=O)(OC[C@H]1O[C@@](C#N)(c2ccc3c(N...,1,[6],"{0: 14, 1: 18, 2: 22, 3: 26, 4: 30, 5: 5, 6: 6...","{0: 61, 1: 5, 2: 11, 3: 96, 4: 101, 5: 105, 6:..."
24,26,O=C1CC[C@@H](N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc...,O=C1CC[C@@H](N2Cc3c(O)cccc3C2=O)C(=O)N1 0.79|N...,[H][C@]1(CCC(NC1=O)=O)N2CC3=C(C2=O)C=CC=C3OCC4...,[21],"{0: 17, 1: 6, 2: 5, 3: 14, 4: 12, 5: 8, 6: 9, ...","{0: 28, 1: 46, 2: 11, 3: 73, 4: 68, 5: 20, 6: ..."
25,27,CNC(C)Cc1ccc2c(c1)OCO2,CC(N)Cc1ccc2c(c1)OCO2 0.82|CN[C@@H](C)Cc1ccc2c...,1,[12],"{0: 2, 1: 1, 2: 3, 3: 5, 4: 4, 5: 8, 6: 7, 7: ...","{0: 4, 1: 13, 2: 8, 3: 26, 4: 17, 5: 42, 6: 18..."
26,28,Cn1cnc2ncn(Cc3nc([C@@H]4CO[C@@H](c5ccc(Cl)cc5)...,O=c1c2[nH]cnc2ncn1Cc1nc([C@@H]2CO[C@@H](c3ccc(...,CN1C=NC2=C1C(N(C(N2)=O)CC3=NC([C@@H]4CO[C@H](C...,[6],"{0: 6, 1: 10, 2: 26, 3: 15, 4: 28, 5: 5, 6: 2,...","{0: 57, 1: 60, 2: 70, 3: 38, 4: 20, 5: 8, 6: 6..."
27,29,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,CC1OC(OC2C(OC(=O)[C@]34CCC(C)(C)CC3C3=CCC5[C@@...,1,[28],"{0: 80, 1: 83, 2: 84, 3: 71, 4: 75, 5: 70, 6: ...","{0: 159, 1: 58, 2: 67, 3: 164, 4: 111, 5: 175,..."
28,30,O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1,O=C(c1cccnc1-c1cc[n+]([O-])cc1)N1CCC(O)(Cc2ccc...,4,[25],"{0: 22, 1: 4, 2: 19, 3: 16, 4: 11, 5: 5, 6: 12...","{0: 65, 1: 58, 2: 57, 3: 37, 4: 34, 5: 35, 6: ..."
29,31,O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2,NaN,O=C(O)C1OC(OC2(CC3=CC=CC=C3)CCN(C(=O)C3=CC=CN=...,"[1, 8, 9, 10, 14, 15, 16, 17, 18]","{0: 10, 1: 2, 2: 13, 3: 22, 4: 15, 5: 19, 6: 2...","{0: 33, 1: 36, 2: 18, 3: 13, 4: 14, 5: 39, 6: ..."

In [25]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')